SUBROUTINE ESNUTR
IMPLICIT NONE
!----------
! ESTB $Id: esnutr.f 2862 2019-11-19 13:41:38Z ckeyser01 $
!----------
!
!     INTERFACE ROUTINE TO COUPLE THE REGEN MODEL AND PROGNOSIS.
!
!  MODIFIED FOR ALASKA TO MAKE AUTOESTAB KICK IN
!  EVERY 50 YEARS INSTEAD OF EVERY 20 (ANTOS ET AL,2000)
!----------
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'OUTCOM.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'ESHAP.f90'
!
!
INCLUDE 'ESHAP2.f90'
!
!
!OMMONS
!
!----------
!  VARIABLE DECLARATIONS:
!----------
!
LOGICAL DEBUG,LONE
!
INTEGER NCLAS
PARAMETER (NCLAS=INT(REAL(MAXTRE) * 0.4))
!
INTEGER I,IACTK,IDT,ISQ,IST,ITODO,ITRGT,J,KD,KDT,KEEP
INTEGER NP,NP1,NPNATS,NT,NTODO
!
INTEGER IESTB(3),MYACT2(5),IGRP,IULIM,IG,IGSP
!
REAL XCUF,XTPA
!
REAL PRMS(3)
!----------
!  DATA STATEMENTS:
!----------
DATA IESTB/427,428,429/,MYACT2/95,440,442,430,431/
!
!----------
LONE=.FALSE.
!
!     SET THE DEBUG OPTION
!
CALL DBCHK (DEBUG,'ESNUTR',6,ICYC)
!
!     CALL ESADDT TO ADD TREES (OR OPTIONS) FROM EXTERNAL SOURCES
!
CALL ESADDT(1)
!
!     PROCESS SPECMULT, STOCKADJ, AND HTADJ OPTIONS.
!
CALL OPFIND (3,MYACT2,NTODO)
IF (DEBUG) WRITE (JOSTND,5) NTODO
5 FORMAT ('IN ESNUTR: OPTS NTODO=',I2)
IF (NTODO.GT.0) THEN
   KDT=IY(ICYC)
   DO 60 I=1,NTODO
   CALL OPGET (I,2,IDT,IACTK,NP,PRMS)
   IF (IACTK.LT.0) GOTO 60
   IF (IACTK.EQ.95) THEN
     J=IFIX(PRMS(1))
     IF(J .LT. 0) THEN
       IGRP = -J
       IULIM = ISPGRP(IGRP,1)+1
       DO 19 IG=2,IULIM
       IGSP = ISPGRP(IGRP,IG)
       XESMLT(IGSP)=PRMS(2)
19        CONTINUE
     ELSEIF (J .EQ. 0) THEN
       DO 20 J=1,MAXSP
       XESMLT(J)=PRMS(2)
20        CONTINUE
     ELSE
       XESMLT(J)=PRMS(2)
     ENDIF
 ELSEIF (IACTK.EQ.440) THEN
     STOADJ=PRMS(1)
   ELSEIF (IACTK.EQ.442) THEN
     J=IFIX(PRMS(1))
     IF(J .LT. 0) THEN
       IGRP = -J
       IULIM = ISPGRP(IGRP,1)+1
       DO 21 IG=2,IULIM
       IGSP = ISPGRP(IGRP,IG)
       HTADJ(IGSP)=PRMS(2)
21        CONTINUE
     ELSEIF (J .EQ. 0) THEN
       DO 30 J=1,MAXSP
       HTADJ(J)=PRMS(2)
30        CONTINUE
     ELSE
       HTADJ(J)=PRMS(2)
     ENDIF
   ENDIF
   CALL OPDONE (I,KDT)
60    CONTINUE
ENDIF
!
!     IF THE DATE OF DISTURBANCE IS -9999 THEN IT HAS NEVER BEEN
!     ESTABLISHED...SET THE DEFAULT VALUE TO 20 YRS PRIOR TO INVENTORY.
!
IF (IDSDAT.EQ.-9999) IDSDAT=IY(1)-20
!
!     SET DATE OF LAST REMOVAL.  RULES: IF MORE THAN ZERO TREES
!     HAVE BEEN CUT THIS CYCLE.
!
IF (IYRLRM.EQ.-9999 ) IYRLRM=IY( 1  )-20
IF (ONTREM(7).GT.0.0) IYRLRM=IY(ICYC)
!
!     LOGIC FOR CALLING THE SPROUT SUBROUTINE.
!
IF (DEBUG) WRITE (JOSTND,70) ITRNRM,LSPRUT
70 FORMAT ('IN ESNUTR: ITRNRM=',I5,'; LSPRUT=',L2)
IF (LSPRUT) THEN
   IF (ITRNRM.GE.1) THEN
      IF(ITRN+ITRNRM.GT.MAXTRE) THEN
         ITRGT=MAXTRE-ITRNRM
         IF (NCLAS.GT.ITRGT) ITRGT=NCLAS
         CALL ESCPRS (ITRGT,DEBUG)
      ENDIF
      CALL ESUCKR
!
!           SET THE VALUE OF IREC1 TO POINT TO THE LAST LOCATION IN THE
!           TREELIST. CALL SPESRT TO REESTABLISH THE SPECIES ORDER SORT.
!
      IREC1=ITRN
      CALL SPESRT
!
!           REESTABLISH THE DIAMETER SORT (INCLUDE THE NEW TREES).
!
      IF (ITRN .GT. 0) CALL RDPSRT (ITRN,DBH,IND,.TRUE.)
!
!           SET IFST=1 SO THAT THE SAMPLE TREE RECORDS WILL BE REPICKED
!           NEXT TIME DIST IS CALLED.
!
      IFST=1
   ENDIF
ELSE
!
!        INSURE THAT ITRNRM IS ZERO
!
   ITRNRM=0
ENDIF
!
!     SET KDT TO THE LAST YEAR OF THE CYCLE.
!
KDT=IY(ICYC+1)-1
!
!     FIND OUT IF THE REGEN MODEL IS TO BE CALLED THIS CYCLE.
!     FIRST, FIND ALL TALLYONE'S THAT ARE SCHEDULED FOR THIS CYCLE.
!
CALL OPFIND (1,IESTB(2),NTODO)
!
!     IF THERE IS NO TALLYONE, LOOK FOR A TALLYTWO.
!
IF (NTODO.EQ.0) THEN
   CALL OPFIND (1,IESTB(3),NTODO)
!
!        IF THERE IS NO TALLYTWO, BRANCH TO TALLY PROCESSING.
!
   IF (NTODO.EQ.0) GOTO 100
ENDIF
!
!     GET EITHER TALLY (ONE OR TWO), COMPUTE NTALLY (THE TALLY NUMBER),
!     USING THE ACTIVITY CODES.
!
CALL OPGET (NTODO,1,IDT,IACTK,NP,PRMS)
IF (IACTK.LT.0) GOTO 100
NTALLY=IACTK-427
IDSDAT=IFIX(PRMS(1))
LONE=.TRUE.
!
!     CONVERT IDSDAT TO YEAR IF REQUIRED
!
IF((IDSDAT.LT.1000).AND.(IDSDAT.GE.1))IDSDAT=IY(IDSDAT)
!
!     IF THE SCHEDULING OF TALLYONE OR TALLYTWO RESULTS IN THEM
!     BEING ACCOMPLISHED GREATER THAN 20 YEARS FROM THE DATE OF
!     DISTURBANCE, ISSUE AN ERROR MESSAGE, CANCEL THEM, RETURN.
!
IF(KDT+1-IDSDAT.GT.20) THEN
   WRITE (JOSTND,80) IDSDAT,KDT,NTALLY
80    FORMAT(/'REGENERATION MODEL CANNOT PREDICT REGENERATION', &
        ' TALLIES BEYOND 20 YEARS FROM DATE OF DISTURBANCE',/, &
        'DISTURBANCE DATE=',I6,'  TALLY DATE=',I6,'  TALLY=',I3)
   GOTO 300
ENDIF
!
!     IF THIS IS A TALLYTWO: FIND OUT IF TALLYONE HAS BEEN EXECUTED
!     WITHIN THE LAST 19 YEARS.  IF ONE HAS NOT BEEN, CHANGE THE
!     TALLYTWO TO TALLYONE.
!
IF (NTALLY.EQ.2) THEN
   ISQ=0
   CALL OPSTUS (428,IDSDAT,KDT,ISQ,NT,IDT,NP1,IST,KD)
   IF (KD.GT.0 .OR. IST.LE.IDSDAT) THEN
      WRITE (JOSTND,90) IY(ICYC+1)-1
90       FORMAT (/,'TALLYTWO CHANGED TO TALLYONE. YEAR=',I4)
      NTALLY=1
   ENDIF
ENDIF
GOTO 200
100 CONTINUE
!
!     CHECK FOR THE TALLY KEYWORD.
!
CALL OPFIND (1,IESTB(1),NTODO)
!
IF (DEBUG) WRITE (JOSTND,105) NTODO,IDSDAT
105 FORMAT ('IN ESNUTR: NTODO=',I4,'; IDSDAT=',I5)
!
!     IF A TALLY ACTIVITY IS PRESENT, FIND THE ONE WITH THE 'LATEST'
!     DATE OF DISTURBANCE, SET NTALLY=1, CALL OPDONE, AND BRANCH TO
!     ESTAB CALLING SEQUENCE.
!
IF (NTODO.GT.0) THEN
   IDSDAT=-1
   DO 110 ITODO=1,NTODO
   CALL OPGET(ITODO,1,IDT,IACTK,NP,PRMS)
   IF (IACTK.LT.0) GOTO 120
   I=IFIX(PRMS(1))
   IF (I.GT.IDSDAT) THEN
      IDSDAT=I
      ISQ=ITODO
   ENDIF
110    CONTINUE
!
!     CONVERT IDSDAT TO YEAR IF REQUIRED
!
   IF((IDSDAT.LT.1000).AND.(IDSDAT.GE.1))IDSDAT=IY(IDSDAT)
!
!        IF THE TALLY GREATER THAN 20 YEARS FROM THE DATE OF
!        DISTURBANCE, ISSUE AN ERROR MESSAGE, CANCEL THEM, RETURN.
!
   IF(KDT+1-IDSDAT.GT.20) THEN
      WRITE (JOSTND,80) IDSDAT,KDT,NTALLY
      GOTO 300
   ENDIF
!
   NTODO=ISQ
   NTALLY=1
   GOTO 200
ENDIF
120 CONTINUE
!
!     SET NUMBER OF ACTIVITIES TO DO TO ZERO...THE FOLLOWING LOGIC
!     TRIGGERS ESTAB CALLS WITHOUT AN ACTIVITY BEING PRESENT.
!
NTODO=0
!
!     CALL FOR AUTAL: AUTOMATIC TALLIES.
!
IF (LAUTAL) THEN
!
!        AUTAL: IF BETWEEN 'THRES1' TO 'THRES2' PERCENT OF STAND HAS
!        BEEN REMOVED, THEN, SET UP ONE TALLY 1.
!        IF OVER 'THRES2' PERCENT OF STAND HAS BEEN REMOVED, SET UP A
!        NORMAL TALLY SEQUENCE.
!
   XTPA=0.0
   IF (ONTCUR(7).GT.0.0) XTPA=ONTREM(7)/ONTCUR(7)
   XCUF=0.0
   IF (OCVCUR(7).GT.0.0) XCUF=OCVREM(7)/OCVCUR(7)
   XTES=AMAX1(XTPA,XCUF)
   LONE=(XTES.GE.THRES1.AND.XTES.LT.THRES2)
   IF (DEBUG) WRITE (JOSTND,130) XTPA,XCUF,LONE
130    FORMAT ('IN ESNUTR: XTPA XCUF=',2F6.3,'; LONE=',L2)
   IF (LONE .OR. (XTPA.GE.THRES2 .OR. XCUF.GE.THRES2)) THEN
      IDSDAT=IY(ICYC)
      NTALLY=1
      KDT=IY(ICYC+1)-1
!
!           ADD THE TALLY TO THE ACTIVITY SCHEDULE.
!
      PRMS(1)=FLOAT(IDSDAT)
      CALL OPADD (KDT,IESTB(1),KDT,1,PRMS,I)
      GOTO 200
   ENDIF
ENDIF
!
!     CALL ESTAB IF CURRENT DATE IS WITHIN 20-YRS OF A DISTURBANCE
!     AND IF NTALLY IS GT 0.
!
IF (DEBUG) WRITE (JOSTND,150) KDT,IDSDAT,NTALLY
150 FORMAT ('IN ESNUTR: KDT=',I6,'; IDSDAT=',I6,'; NTALLY=',I5)
!
IF (KDT-IDSDAT.LE.19 .AND. NTALLY.GT.0) THEN
   PRMS(1)=FLOAT(IDSDAT)
   NTALLY=NTALLY+1
   PRMS(2)=FLOAT(NTALLY)
   NP=2
   KDT=IY(ICYC+1)-1
   CALL OPADD (KDT,IESTB(1),KDT,NP,PRMS,I)
   GOTO 200
ENDIF
!
!     CALL ESTAB FOR INGROWTH...RULES:
!     1. IF THERE ARE NO TALLYIES SCHEDULED IN THE NEXT CYCLE.
!     2. IF THE CURRENT YEAR IS GE THAN 39 YEARS PAST THE LAST DATE
!        OF DISTURBANCE, OR THERE ARE NO TREES IN THE TREE LIST.
!
IF (LINGRW) THEN
!
!        CHECK TO SEE IF THERE ARE ANY TALLIES IN THE NEXT CYCLE.
!        CALL OPCSET TO SET POINTERS TO THE NEXT CYCLE AND CALL OPFIND.
!
   IF (IFINT.LE.20) THEN
      CALL OPCSET (ICYC+1)
      CALL OPFIND (3,IESTB,KEEP)
      CALL OPCSET (ICYC)
      IF (DEBUG) WRITE (JOSTND, &
            '(''IN ESNUTR: TALLIES NEXT CYCLE='',I3)') KEEP
      IF (KEEP.GT.0) GOTO 400
   ENDIF
!
   IF (DEBUG) WRITE(JOSTND,160) ITRN,ICYC,IY(ICYC+1),IYRLRM, &
         IDSDAT
160    FORMAT('IN ESNUTR: ITRN=',I4,'  ICYC=',I3,'  IY(ICYC+1)=', &
         I5,'  IYRLRM=',I5,'  IDSDAT=',I5)
   IF ((ITRN.EQ.0 .AND. ICYC.EQ.1)   .OR. &
          (IY(ICYC+1)-IDSDAT .GE. 40) ) THEN
!
!           SET NTALLY=99 TO SIGNAL ESTAB THAT THIS IS INGROWTH
!           AND SET THE DATE OF DISTURBANCE EQUAL TO 20 YEARS AGO.
!
      NTALLY=99
      IDSDAT=IY(ICYC+1)-20
      LONE=.TRUE.
      IDT=0
      GOTO 200
    ENDIF
ENDIF
!
!     CALL ESTAB IF THERE ARE PLANT OR NATURAL KEYWORDS IN THE CASE
!     WHERE ESTAB WOULD NOT OTHERWISE BE CALLED.
!
CALL OPFIND (2,MYACT2(4),NPNATS)
IF (DEBUG) WRITE (JOSTND,170) NPNATS
170 FORMAT ('IN ESNUTR: OPTS NPNATS=',I2)
IF (NPNATS.GT.0) THEN
!
!        CALL ESTAB WITH NTALLY=99 AND AN OLD DATE OF DISTURBANCE
!
   NTALLY=99
   IDSDAT=IY(ICYC+1)-20
   IDT=0
   GOTO 200
ENDIF
!
IF (DEBUG) WRITE (JOSTND,'(''IN ESNUTR: NO ESTAB.'')')
!
GOTO 400
!
!     CALLING SEQUENCE USED REGARDLESS OF THE OPTION FOR TALLIES.
!
200 CONTINUE
!
!     THE DATE OF LAST REMOVAL IS NO OLDER THAN THE DATE OF DISTURB.
!
IF (IYRLRM.LT.IDSDAT) IYRLRM=IDSDAT
!
!     IF ALL OF THE PLOTS ARE NONSTOCKABLE, WRITE A MSG, BRANCH
!     TO CANCEL THESE TALLIES, AND RETURN.
!
IF (IPINFO.GE.4) THEN
   WRITE (JOSTND,210) NPLT,IY(ICYC+1)-1
210    FORMAT (/,'NOTE: NONE OF THE PLOTS ARE STOCKABLE. ', &
              ' STAND ID: ',A,'; YEAR=',I5)
   GOTO 300
ENDIF
!
!     SIGNAL THAT THE TALLY IS DONE (ONLY IF NTODO IS GT 0).
!     THIS IS DONE BEFORE CALL TO ESTAB BECAUSE ESTAB CALLS OPFIND
!     AND CALLS TO OPFIND CANNOT BE NESTED.
!
IF (NTODO.GT.0) CALL OPDONE (NTODO,KDT)
!
!     MAKE SURE THERE IS ROOM IN THE TREELIST TO HOLD NEW TREES.
!
IF (ITRN.GT.MAXTRE*.7 .AND. NTODO.GT.0) CALL ESCPRS (NCLAS,DEBUG)
!
!     ESTABLISH NEW TREES
!
IF (DEBUG) WRITE (JOSTND,220) IDT,IDSDAT,IYRLRM,LONE, &
                                 NTALLY,KDT,ITRN,NTODO
220 FORMAT('IN ESNUTR: CALLING ESTAB: IDT=',I5,'; IDSDAT=',I5, &
          '; IYRLRM=',I5,'; LONE=',L2/T12,'NTALLY=',I3,'; KDT=', &
          I5,'; ITRN=',I5,'; NTODO=',I2)
!
CALL ESTAB (KDT)
!
!     REESTABLISH THE DIAMETER SORT (INCLUDE THE NEW TREES).
!
IF(ITRN .GT. 0) CALL RDPSRT (ITRN,DBH,IND,.TRUE.)
!
!     SET IFST=1 SO THAT THE SAMPLE TREE RECORDS WILL BE REPICKED
!     NEXT TIME DIST IS CALLED.
!
IFST=1
!
!     IF THE CALL WAS BASED ON A TALLYONE OR TALLYTWO, OR
!     IF THE CALL WAS TRIGGERED BY A MODERATE REMOVAL, OR INGROWTH
!     THEN, SET NTALLY EQUAL TO 0.
!
IF (LONE) NTALLY=0
300 CONTINUE
!
!     FIND ALL OF THE TALLIES THAT ARE SCHEDULED FOR THIS CYCLE, BUT
!     NOT YET DONE, AND DELETE THEM.
!
CALL OPFIND (3,IESTB,NTODO)
IF(NTODO.GT.0) THEN
   DO 310 I=1,NTODO
   CALL OPDEL1(I)
310    CONTINUE
ENDIF
400 CONTINUE
RETURN
END
