SUBROUTINE VARGET (WK3,IPNT,ILIMIT,REALS,LOGICS,INTS)
IMPLICIT NONE
!----------
! AK $Id$
!----------
!
!     READ THE VARIANT SPECIFIC VARIABLES.
!
!     PART OF THE PARALLEL PROCESSING EXTENSION TO PROGNOSIS.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
INCLUDE 'ESPARM.f90'

INCLUDE 'ESCOMN.f90'
INCLUDE 'PLOT.f90'
INCLUDE 'VARCOM.f90'
!
!
!OMMONS
!
!     NOTE: THE ACTUAL STORAGE LIMIT FOR INTS, LOGICS, AND REALS
!     IS MAXTRE (SEE PRGPRM).
!
INTEGER ILIMIT,IPNT,MXL,MXI,MXR
PARAMETER (MXL=1,MXI=2,MXR=5)
LOGICAL LOGICS(*)
REAL WK3(MAXTRE)
INTEGER INTS(*)
REAL REALS(*)
LOGICAL LDANUW
REAL RDANUW
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
LDANUW = LOGICS(1)
RDANUW = REALS(1)
RDANUW = WK3(1)
!----------
!
!     GET THE INTEGER SCALARS.
!
CALL IFREAD (WK3, IPNT, ILIMIT, INTS, MXI, 2)
IIFORTP  = INTS ( 1)
IFT0     = INTS ( 2)
!
!     GET THE INTEGER ARRAYS.
!
!     GET THE LOGICAL SCALARS.
!
!**   CALL LFREAD (WK3, IPNT, ILIMIT, LOGICS, MXL, 2)
!
!     GET THE REAL SCALARS.
!
!**   CALL BFREAD (WK3, IPNT, ILIMIT, REALS, MXR, 2)
!**           = REALS( 1)
!
!     READ THE REAL ARRAYS
!
CALL BFREAD (WK3, IPNT, ILIMIT, OCURFT,    MAXSP*14, 2) ! from ESCOMN.F77
CALL BFREAD (WK3, IPNT, ILIMIT, HTT11,     MAXSP,    2) ! from ESCOMN.F77
CALL BFREAD (WK3, IPNT, ILIMIT, HTT12,     MAXSP,    2)
CALL BFREAD (WK3, IPNT, ILIMIT, HTT13,     MAXSP,    2)
CALL BFREAD (WK3, IPNT, ILIMIT, XMAXPT,    MAXPLT,   2)

RETURN
END

SUBROUTINE VARCHGET (CBUFF, IPNT, LNCBUF)
IMPLICIT NONE
!----------
!     Get variant-specific character data
!----------

INCLUDE 'PRGPRM.f90'

INTEGER LNCBUF
CHARACTER CBUFF(LNCBUF)
INTEGER IPNT
INTEGER IDANUW
CHARACTER CDANUW
! Stub for variants which need to get/put character data
! See /bc/varget.f and /bc/varput.f for examples of VARCHGET and VARCHPUT
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
IDANUW = IPNT
CDANUW = CBUFF(1)

RETURN
END
