SUBROUTINE DGFASP(D,ASPDG,CR,BARK,SI,DEBUG)
IMPLICIT NONE
!----------
! UT $Id$
!----------
!   CALCULATES DIAMETER GROWTH RATES FOR LARGE ASPEN TREES
!----------
!
!OMMONS
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'COEFFS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'OUTCOM.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'PDEN.f90'
!
!
!OMMONS
!----------
LOGICAL DEBUG
REAL SI,BARK,CR,ASPDG,D,XSITE,REL,ASPCR,POT,FOFR,GOFAD,BAACT
REAL VALMOD,PREDGR
!----------
! PEEL OFF THE SPECIES INDICATOR ON THE SITE INDEX
!----------
XSITE = SI
REL=D/RMSQD
ASPCR=CR/10.0
!----------
! CALC THE POTENTIAL GROWTH
!----------
POT=(.4755 - 3.8336E-6 * D **4.1488) &
       + (4.510E-2 * ASPCR * D **.67266)
IF(POT .LE. 0.0)POT = 0.01
!----------
! CALC FUNCTION OF RELATIVE DENSITY
!----------
FOFR=1.07528 * (1.0 - EXP(-1.89022 * REL))
!----------
! CALC FUNCTION OF AVE DIA
!----------
GOFAD=2.1963E-1 * (RMSQD + 1.0) **0.73355
!----------
! CALC MODIFIER VALUE CORRECTED FOR PLOT DENSITY
! THE NEXT TWO LINES ARE A TEMPORARY FIX.
!----------
BAACT=BA
IF(BAACT .GE. 310.0) BAACT=305.
VALMOD=1.0 - EXP(-FOFR * GOFAD * ((310.0-BAACT)/310.0) &
           **0.5)
!----------
! CALC PRED DIA IN REAL TERMS CORRECTED FOR SITE
!----------
PREDGR=POT * VALMOD * (.48630 + 0.01258 * XSITE)
!----------
! CHANGE DG TO LN(DDS)
!----------
ASPDG=ALOG(2.0*D*BARK*PREDGR + PREDGR*PREDGR)
!
IF(DEBUG)WRITE(JOSTND,900)D,CR,POT,FOFR,GOFAD,VALMOD, &
    ASPDG,PREDGR,BARK,XSITE
900 FORMAT(' IN ASPEN DIA GR: D=',F6.1, &
    ' ASPCR=',F5.1,' POT=',E10.4,' FOFR=',E10.4,' GOFAD=',E10.4, &
    ' VALMOD=',E10.4,' ASPDG=',E10.4,/,15X,' PREDGR =', &
   E10.4,'  BARK =',F10.6,'XSITE =',F10.2)
!
RETURN
END
