SUBROUTINE FORKOD
IMPLICIT NONE
!----------
! UT $Id$
!----------
!
!     TRANSLATES FOREST CODE INTO A SUBSCRIPT, IFOR, AND IF
!     KODFOR IS ZERO, THE ROUTINE RETURNS THE DEFAULT CODE.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
!OMMONS
!
!  ------------------------
!  NATIONAL FORESTS:
!  401 = ASHLEY
!  407 = DIXIE
!  408 = FISHLAKE
!  410 = MANTI LASAL
!  418 = UINTA
!  419 = WASATCH
!  404 = CACHE (MAPPED TO WASATCH)
!  409 = HUMBOLDT (MAPPED TO FISHLAKE)
!  417 = TOIYABE (MAPPED TO FISHLAKE)
!  ------------------------
!  RESERVATION PSUEDO CODES:
!  7702 = FORT MOJAVE RESERVATION       (MAPPED TO 417 TOIYABE)
!  7711 = FORT MCDERMITT INDIAN RES.    (MAPPED TO 409 HUMBOLDT)
!  7712 = PYRAMID LAKE PAIUTE RES.      (MAPPED TO 409 HUMBOLDT)
!  7714 = SUMMIT LAKE RESERVATION       (MAPPED TO 409 HUMBOLDT)
!  7715 = WALKER RIVER RESERVATION      (MAPPED TO 417 TOIYABE)
!  7716 = YOMBA RESERVATION             (MAPPED TO 417 TOIYABE)
!  7717 = SKULL VALLEY RESERVATION      (MAPPED TO 419 WASATCH)
!  7718 = UINTAH AND OURAY RESERVATION  (MAPPED TO 401 ASHLEY)
!  7721 = DUCK VALLEY RESERVATION       (MAPPED TO 409 HUMBOLDT)
!  7722 = SOUTH FORK RESERVATION        (MAPPED TO 409 HUMBOLDT)
!  7723 = GOSHUTE RESERVATION           (MAPPED TO 409 HUMBOLDT)
!  7728 = KAIBAB INDIAN RESERVATION     (MAPPED TO 407 DIXIE)
!  7729 = PAIUTE (UT) RESERVATION       (MAPPED TO 407 DIXIE)
!  7835 = TIMBI-SHA SHOSHONE RES.       (MAPPED TO 417 TOIYABE)
!  7920 = UTE MOUNTAIN RESERVATION      (MAPPED TO 410 MANTI-LA SAL)
!  8001 = NAVAJO NATION RESERVATION     (MAPPED TO 410 MANTI-LA SAL)
!  ------------------------

INTEGER JFOR(9),KFOR(9),NUMFOR,I
LOGICAL USEIGL, FORFOUND
DATA JFOR/401,407,408,410,418,419,404,409,417/,NUMFOR/9/
DATA KFOR/9*1/

USEIGL = .TRUE.
FORFOUND = .FALSE.


SELECT CASE (KODFOR)
!       CROSSWALK FOR RESERVATION PSUEDO CODES & LOCATION CODE
  CASE (7702)
    WRITE(JOSTND,61)
61     FORMAT(/,'********',T12,'FORT MOJAVE RESERVATION (7702) ', &
       'BEING MAPPED TO TOIYABE (417) FOR FURTHER PROCESSING.')
    IFOR = 9
  CASE (7711)
    WRITE(JOSTND,62)
62     FORMAT(/,'********',T12,'FORT MCDERMITT INDIAN RES. (7711) ', &
       'BEING MAPPED TO HUMBOLDT (409) FOR FURTHER PROCESSING.')
    IFOR = 8
  CASE (7712)
    WRITE(JOSTND,63)
63     FORMAT(/,'********',T12,'PYRAMID LAKE PAIUTE RES. (7712) ', &
       'BEING MAPPED TO HUMBOLDT (409) FOR FURTHER PROCESSING.')
    IFOR = 8
  CASE (7714)
    WRITE(JOSTND,64)
64     FORMAT(/,'********',T12,'SUMMIT LAKE RESERVATION (7714) ', &
       'BEING MAPPED TO HUMBOLDT (409) FOR FURTHER PROCESSING.')
    IFOR = 8
  CASE (7715)
    WRITE(JOSTND,65)
65     FORMAT(/,'********',T12,'WALKER RIVER RESERVATION (7715) ', &
       'BEING MAPPED TO TOIYABE (417) FOR FURTHER PROCESSING.')
    IFOR = 9
  CASE (7716)
    WRITE(JOSTND,66)
66     FORMAT(/,'********',T12,'YOMBA RESERVATION (7716) BEING ', &
       'MAPPED TO TOIYABE (417) FOR FURTHER PROCESSING.')
    IFOR = 9
  CASE (7717)
    WRITE(JOSTND,67)
67     FORMAT(/,'********',T12,'SKULL VALLEY RESERVATION (7717) ', &
       'BEING MAPPED TO WASATCH (419) FOR FURTHER PROCESSING.')
    IFOR = 6
  CASE (7718)
    WRITE(JOSTND,68)
68     FORMAT(/,'********',T12,'UINTAH AND OURAY RESERVATION (7718)', &
       ' BEING MAPPED TO ASHLEY (401) FOR FURTHER PROCESSING.')
    IFOR = 1
  CASE (7721)
    WRITE(JOSTND,69)
69     FORMAT(/,'********',T12,'DUCK VALLEY RESERVATION (7721) ', &
       'BEING MAPPED TO HUMBOLDT (409) FOR FURTHER PROCESSING.')
    IFOR = 8
  CASE (7722)
    WRITE(JOSTND,70)
70     FORMAT(/,'********',T12,'SOUTH FORK RESERVATION (7722) ', &
       'BEING MAPPED TO HUMBOLDT (409) FOR FURTHER PROCESSING.')
    IFOR = 8
  CASE (7723)
    WRITE(JOSTND,71)
71     FORMAT(/,'********',T12,'GOSHUTE RESERVATION (7723) BEING ', &
       'MAPPED TO HUMBOLDT (409) FOR FURTHER PROCESSING.')
    IFOR = 8
  CASE (7728)
    WRITE(JOSTND,72)
72     FORMAT(/,'********',T12,'KAIBAB INDIAN RESERVATION (7728) ', &
       'BEING MAPPED TO DIXIE (407) FOR FURTHER PROCESSING.')
    IFOR = 2
  CASE (7729)
    WRITE(JOSTND,73)
73     FORMAT(/,'********',T12,'PAIUTE (UT) RESERVATION (7729) ', &
       'BEING MAPPED TO DIXIE (407) FOR FURTHER PROCESSING.')
    IFOR = 2
  CASE (7835)
    WRITE(JOSTND,74)
74     FORMAT(/,'********',T12,'TIMBI-SHA SHOSHONE RES. (7835) ', &
       'BEING MAPPED TO TOIYABE (417) FOR FURTHER PROCESSING.')
    IFOR = 9
  CASE (7920)
    WRITE(JOSTND,75)
75     FORMAT(/,'********',T12,'UTE MOUNTAIN RESERVATION (7920) ', &
       'BEING MAPPED TO MANTI-LA SAL (410) FOR FURTHER PROCESSING.')
    IFOR = 4
  CASE (8001)
    WRITE(JOSTND,76)
76     FORMAT(/,'********',T12,'NAVAJO NATION RESERVATION (8001) ', &
       'BEING MAPPED TO MANTI-LA SAL (410) FOR FURTHER PROCESSING.')
    IFOR = 4
!       END CROSSWALK FOR RESERVATION PSUEDO CODES & LOCATION CODE

  CASE DEFAULT

!         CONFIRMS THAT KODFOR IS AN ACCEPTED FVS LOCATION CODE
!         FOR THIS VARIANT FOUND IN DATA ARRAY JFOR
    DO 10 I=1,NUMFOR
      IF (KODFOR .EQ. JFOR(I)) THEN
        IFOR = I
        FORFOUND = .TRUE.
        EXIT
      ENDIF
10     CONTINUE

!         LOCATION CODE ERROR TRAP
    IF (.NOT. FORFOUND) THEN
      CALL ERRGRO (.TRUE.,3)
      WRITE(JOSTND,11) JFOR(IFOR)
11       FORMAT(/,'********',T12,'FOREST CODE USED IN THIS ', &
         'PROJECTION IS',I4)
      USEIGL = .FALSE.
    ENDIF

END SELECT

!     FOREST MAPPING CORRECTION
SELECT CASE (IFOR)
  CASE (7)
    WRITE(JOSTND,21)
21     FORMAT(/,'********',T12,'CACHE NF (404) BEING MAPPED TO ', &
       'WASATCH (419) FOR FURTHER PROCESSING.')
    IFOR = 6
  CASE (8)
    WRITE(JOSTND,22)
22     FORMAT(/,'********',T12,'HUMBOLDT NF (409) BEING MAPPED TO ', &
       'FISHLAKE (408) FOR FURTHER PROCESSING.')
    IFOR = 3
  CASE (9)
    WRITE(JOSTND,23)
23     FORMAT(/,'********',T12,'TOIYABE NF (417) BEING MAPPED TO ', &
       'FISHLAKE (408) FOR FURTHER PROCESSING.')
    IFOR = 3
END SELECT

!     SET THE IGL VARIABLE ONLY IF DEFAULT FOREST IS USED
!     GEOGRAPHIC LOCATION CODE: 1=NORTH, 2=CENTRAL, 3=SOUTH
!     USED TO SET SOME EQUATIONS IN REGENERATION AND PERHAPS
!     HEIGHT-DIAMETER IN DIFFERENT VARIANTS.
IF (USEIGL) IGL = KFOR(IFOR)

KODFOR=JFOR(IFOR)
RETURN
END
