SUBROUTINE MAICAL
IMPLICIT NONE
!----------
! UT $Id$
!----------
!  THIS SUBROUTINE CALCULATES THE MAI FOR THE STAND. IT IS CALLED
!  FROM CRATET.
!----------
!
!OMMONS
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'COEFFS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'OUTCOM.f90'
!
!
INCLUDE 'HTCAL.f90'
!
!
!OMMONS
!
!----------
LOGICAL DEBUG
INTEGER ISPNUM(MAXSP),ISICD,IERR
REAL SSSI,ADJMAI
!----------
!  INITIALIZE INTERNAL VARIABLES:
!
! SPECIES ORDER FOR UTAH VARIANT:
!
!  1=WB,  2=LM,  3=DF,  4=WF,  5=BS,  6=AS,  7=LP,  8=ES,  9=AF, 10=PP,
! 11=PI, 12=WJ, 13=GO, 14=PM, 15=RM, 16=UJ, 17=GB, 18=NC, 19=FC, 20=MC,
! 21=BI, 22=BE, 23=OS, 24=OH
!
! VARIANT EXPANSION:
! GO AND OH USE OA (OAK SP.) EQUATIONS FROM UT
! PM USES PI (COMMON PINYON) EQUATIONS FROM UT
! RM AND UJ USE WJ (WESTERN JUNIPER) EQUATIONS FROM UT
! GB USES BC (BRISTLECONE PINE) EQUATIONS FROM CR
! NC, FC, AND BE USE NC (NARROWLEAF COTTONWOOD) EQUATIONS FROM CR
! MC USES MC (CURL-LEAF MTN-MAHOGANY) EQUATIONS FROM SO
! BI USES BM (BIGLEAF MAPLE) EQUATIONS FROM SO
! OS USES OT (OTHER SP.) EQUATIONS FROM UT
!
!----------
DATA ISPNUM/ &
     101, 101, 202, 015, 093, 746, 108, 093, 019, 122, &
     101, 101, 101, 101, 101, 101, 101, 101, 101, 746, &
     746, 101, 101, 101/
!-----------
!  SEE IF WE NEED TO DO SOME DEBUG.
!-----------
CALL DBCHK (DEBUG,'MAICAL',6,ICYC)
!
IF(DEBUG) WRITE(JOSTND,3)ICYC
3 FORMAT(' ENTERING SUBROUTINE MAICAL  CYCLE =',I5)
!-------
!   RMAI IS FUNCTION TO CALCULATE ADJUSTED MAI.
!-------
IF (ISISP .EQ. 0) ISISP=3
SSSI=SITEAR(ISISP)
IF (SSSI .EQ. 0.) SSSI=140.0
ISICD=ISPNUM(ISISP)
RMAI=ADJMAI(ISICD,SSSI,10.0,IERR)
IF(RMAI .GT. 128.0)RMAI=128.0
IF(DEBUG) WRITE(JOSTND,10)ICYC,RMAI
10 FORMAT(' LEAVING SUBROUTINE MAICAL  CYCLE =',I5,5X,'RMAI =',F10.3)
RETURN
END
