SUBROUTINE RDATV (L,LTREE)
IMPLICIT NONE
!----------
! RD $Id$
!----------
!
!  RETURNS L=TRUE, TO INDICATE THAT ROOT DISEASE MODEL IS AVAILABLE
!  WITH THE PROGRAM BEING RUN AND IS ACTUALLY BEING CALLED.
!
!  CALLED BY :
!     RDCMPR  [ROOT DISEASE]
!     RDMN1   [ROOT DISEASE]
!     RDTDEL  [ROOT DISEASE]
!     RDTRP   [ROOT DISEASE]
!     INITRE  [PROGNOSIS]
!     INTREE  [PROGNOSIS]
!
!  CALLS     :
!     NONE
!
!  PARAMETERS :
!     L     - FLAG THAT IS SET TO TRUE WHEN THE ROOT DISEASE MODEL IS
!             BEING RUN.
!     LTREE - FLAG IS TRUE IF MODEL IS BEING INITIALIZED BY THE
!             INPUT TREELIST.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
INCLUDE 'RDPARM.f90'
!
!
INCLUDE 'RDADD.f90'
!
!
!OMMONS
!
LOGICAL L, LTREE

L = RRTINV .OR. RRMAN
LTREE = RRTINV

RETURN
END
