SUBROUTINE RDESCP (LMAXTR,MXRR)
IMPLICIT NONE
!----------
! RD $Id$
!----------
!
!  THIS ROOT DISEASE MODEL SUBROUTINE INSURES THAT THERE IS ROOM
!  IN THE TREELIST FOR ESTAB TREES. IF THERE IS ACTIVE ROOT DISEASE,
!  MXRR WILL BE RETURNED AS THE RD MODEL TREE RECORD LIMIT (IRRTRE).
!
!  CALLED BY :
!     ESTAB   [PROGNOSIS]
!
!  PARAMETERS :
!     LMAXTR - MAXIMUM NUMBER OF PROGNOSIS MODEL TREE RECORDS
!              (NAME CHANGED TO AVOID CONFLICT WITH MAXTRE IN
!               PRGPRM FILE.)
!     MXRR   - MAXIMUM NUMBER OF RROT TREE RECORDS
!
!  Revision History :
!   08/14/12 - Last revision date.
!   08/28/14 Lance R. David (FMSC)
!     Added implicit none and declared variables.
!
!----------------------------------------------------------------------
!
!OMMONS
!
!
INCLUDE  'PRGPRM.f90'
INCLUDE  'RDPARM.f90'
INCLUDE  'RDCOM.f90'
!
!
!OMMONS
!
INTEGER  IDI, LMAXTR, MXRR
REAL     TPAREA

TPAREA = 0.0
DO 100 IDI=1,ITOTRR
   TPAREA = TPAREA + PAREA(IDI)
100 CONTINUE

IF (IROOT .EQ. 0 .OR. TPAREA .EQ. 0.0) THEN
   MXRR = LMAXTR
ELSE
   MXRR = IRRTRE
ENDIF

RETURN
END
