SUBROUTINE RDIOUT
IMPLICIT NONE
!----------
! RD $Id$
!----------
!
!  PRODUCES OPTIONAL OUTPUT (IN A SEPARATE FILE) OF THE RESULTS
!  OF MONTE CARLO SIMULATIONS OF INFECTION WITHIN A CENTER
!
!  CALLED BY :
!     RDCNTL  [ROOT DISEASE]
!
!  CALLS     :
!     DBCHK   (SUBROUTINE)   [PROGNOSIS]
!
!  PARAMETERS :
!     NONE
!
!  COMMON BLOCK VARIABLES :
!     ANUINF: ARRAY CONTAINING INDIVIDUAL SIMULATION RESULTS
!     CORINF: ARRAY CONTAINING THE AVERAGE RESULT AND THE TOTAL UNINF. TREES BEFORE
!             ANY INFECTION OCCURS
!
!  LOCAL VARIABLES :
!     ISDOUT:  NUMBER OF OUTPUT FILE
!
!  REVISION HISTORY:
!  18-JUN-2001 Lancd R. David (FHTET)
!    Added Stand ID and Management ID line to report header.
!   08/28/14 Lance R. David (FMSC)
!     Added implicit none and declared variables.
!
!----------------------------------------------------------------------
!
!.... PARAMETER INCLUDE FILES
!
INCLUDE 'PRGPRM.f90'
INCLUDE 'RDPARM.f90'
!
!.... COMMON INCLUDE FILES
!
INCLUDE 'ARRAYS.f90'
INCLUDE 'CONTRL.f90'
INCLUDE 'PLOT.f90'
INCLUDE 'RDARRY.f90'
INCLUDE 'RDCOM.f90'
INCLUDE 'RDCRY.f90'
INCLUDE 'RDADD.f90'
!
!
CHARACTER*1 CHTYPE(ITOTRR)
INTEGER  ISIM, J, JYR, MAXSIM, N
REAL     AVG, SD, SUMX, UINUM

DATA CHTYPE /'P','S','A','W'/

IF (IROOT .EQ. 0) RETURN

!     IF MONTE CARLO OUTPUT WAS NOT REQUESTED THEN RETURN

IF (ISDOUT .LE. 0) RETURN

MAXSIM = MIN(NINSIM,10)

IF (ICYC .EQ. 1) THEN
!
!         WRITE THE TABLE HEADERS
!
    WRITE (ISDOUT,1100)
    WRITE (ISDOUT,1105)
    WRITE (ISDOUT,1100)
    WRITE (ISDOUT,1110) NPLT, MGMID
    WRITE (ISDOUT,1115)
    WRITE (ISDOUT,1120)
    WRITE (ISDOUT,1155) (N,N=1,MAXSIM)
    WRITE (ISDOUT,1160)

ENDIF

JYR = IY(ISTEP) - 1

DO 5000 IRRSP=MINRR,MAXRR

   IF (PAREA(IRRSP) .LE. 0.0) GOTO 5000

   AVG = CORINF(IRRSP,1)
   UINUM = CORINF(IRRSP,2)

   SUMX = 0.0
   SD = 0.0
   DO 100 ISIM=1,NINSIM
      SUMX = SUMX + (ANUINF(IRRSP,ISIM) - AVG)**2
100    CONTINUE
   IF (NINSIM .GT. 1) SD = SQRT(SUMX) / FLOAT(NINSIM - 1)

   WRITE(ISDOUT,2099) JYR,CHTYPE(IRRSP),NINSIM,AVG,SD,UINUM, &
                         (ANUINF(IRRSP,J),J=1,MAXSIM)
   WRITE(ISDOUT,2199) (INFISD(IRRSP,J),J=1,MAXSIM)
!         WRITE(ISDOUT,2200) (SPRQMD(IRRSP,J),J=1,MAXSIM)

5000 CONTINUE

WRITE(ISDOUT,1121)

RETURN

1100 FORMAT (' ',53('* '))
1105 FORMAT (' ',43X,'WESTERN ROOT DISEASE MODEL')
1110 FORMAT (' ',33X,'STAND ID= ',A26,5X,'MANAGEMENT ID= ',A4)
1115 FORMAT (' ',35X,'INSIDE CENTER INFECTION SIMULATION RESULTS')
1120 FORMAT (' ',106('-'))
1121 FORMAT (' ')
1155 FORMAT (1X,'YEAR',2X,'TYPE',2X,'NUM',2X,'AVG',3X,'SD',3X, &
           '#UNINF',1X,10(4X,'#',I2))
1160 FORMAT (1X,106('-'))

2099 FORMAT (1X,I4,4X,A1,3X,I2,2X,F4.0,2X,F4.0,2X,F6.0,2X,10(3X,F4.0))
2199 FORMAT (37X,10(4X,I2,1X))
! 2200 FORMAT (37X,10(3X,F4.1))

END
