SUBROUTINE RDMN1(INUM)
IMPLICIT NONE
!----------
! RD $Id$
!----------
!
!  THIS SUBROUTINE IS CALLED FROM PROGNOSIS MAIN AND INITIALIZES THE
!  GENERAL ROOT DISEASE MODEL.
!
!  CALLED BY :
!     MAIN    [PROGNOSIS]
!
!  CALLS     :
!     RDATV   (SUBROUTINE)   [ROOT DISEASE]
!     RDRANI  (SUBROUTINE)   [ROOT DISEASE]
!     COMPRS  (SUBROUTINE)   [PROGNOSIS]
!     OPADD   (SUBROUTINE)   [PROGNOSIS]
!     OPINCR  (SUBROUTINE)   [PROGNOSIS]
!     OPFIND  (SUBROUTINE)   [PROGNOSIS]
!     OPDONE  (SUBROUTINE)   [PROGNOSIS]
!     SPESRT  (SUBROUTINE)   [PROGNOSIS]
!     RDPSRT  (SUBROUTINE)   [PROGNOSIS]
!     PCTILE  (SUBROUTINE)   [PROGNOSIS]
!     DIST    (SUBROUTINE)   [PROGNOSIS]
!     COMP    (SUBROUTINE)   [PROGNOSIS]
!     RDSETP  (SUBROUTINE)   [ROOT DISEASE]
!
!  PARAMETERS :
!     INUM   -
!
!  Revision History:
!     21-MAR-00 Lance David (FHTET)
!       Removed equivalence of FVS array WK6 to RD array SPCNT and
!       corrected the initialization process of SPCNT based on
!       parameter MAXSP instead of literal 11.
!       Reduced RETURN statements to 1 at the end of routine.
!       Added debug code.
!     25-MAR-2003 Lance R. David (FHTET)
!       WK2 from ARRAYS common area is reset to zero before compression of
!       treelist is requested. SVS processing had used WK2 and left residual
!       values in it and comprs expects values in WK2 to be mortality which
!       has not yet been predicted.
!       Gary Dixon and Lance David discussed this problem and agreed
!       on this solution to reset WK2 in this routine.
!   08/29/14 Lance R. David (FMSC)
!     Added implicit none and declared variables.
!
!----------------------------------------------------------------------
!
!.... PARAMETER INCLUDE FILES
!
INCLUDE 'PRGPRM.f90'
INCLUDE 'RDPARM.f90'
!
!.... COMMON INCLUDE FILES
!
INCLUDE 'CONTRL.f90'
INCLUDE 'RDCOM.f90'
INCLUDE 'ARRAYS.f90'
INCLUDE 'OUTCOM.f90'
!
LOGICAL  LGO, LTEE, DEBUG
INTEGER  I, ICCY, IDI, II, IM, INUM, IS, KDT, MYACT(1)
REAL     PRMS(2), SPCNT(MAXSP,3), TPAREA

DATA MYACT /250/

!.... SEE IF WE NEED TO DO SOME DEBUG.

CALL DBCHK (DEBUG,'RDMN1',5,ICYC)
IF (DEBUG) WRITE (JOSTND,*) 'ENTER RDMN1:  INUM=',INUM

!     CHECK TO SEE IF GENERAL ROOT DISEASE MODEL IS ACTIVE

CALL RDATV (LGO,LTEE)

!     IF THIS IS FIRST CALL TO RDMN1 THEN PRINT SUMMARY ROOT DISEASE INFO.
!     READ IN FROM TREE LIST

IF (LGO .AND. INUM .EQ. 1) CALL RDTOUT
!
!     RETURN IF GENERAL ROOT DISEASE MODEL NOT ACTIVE OR THERE IS NO
!     ROOT DISEASE.
!
TPAREA = 0.0
DO 33 IDI=1,ITOTRR
   TPAREA = TPAREA + PAREA(IDI)
33 CONTINUE
IF (.NOT. LGO .OR. TPAREA .EQ. 0.0) GOTO 225      !RETURN
!
!     IF THIS IS FIRST CALL TO RDMN1 THEN SEED RANDOM NUMBER GENERATOR.
!
IF (INUM .EQ. 1) CALL RDRANI(DSEED)

!
!     IF TREELIST INITIALIZATION IN EFFECT AND THIS IS FIRST PASS
!     THRU RDMN1 THEN CALL RDSETP TO CALCULATE INITIALIZATION VALUES.
!     IF TREELIST INITIALIZATION IN EFFECT AND THIS IS SECOND CALL TO
!     RDMN1 THEN COMPRESS IF NUMBER OF TREES GREATER THAN VALUE
!     SPECIFIED WITH RRCOMP KEYWORD. IF NO COMPRESS TO BE DONE THEN
!     RETURN
!
IF (LTEE) THEN
   IF (INUM .EQ. 1) THEN
      GOTO 222
   ELSEIF (INUM .EQ. 2 .AND. ITRN .GT. IRCOMP) THEN
      GOTO 90
   ELSE
      GOTO 225
   ENDIF
ENDIF

!
!     IF MANUAL INITIALIZATION AND THIS IS FIRST PASS THRU RDMN1 THEN
!     RETURN.  IF MANUAL INIT AND THIS IS SECOND PASS THRU RDMN1 AND
!     COMPRESSION DESIRED THEN COMPRESS.  NOTE THAT COMPRESSION IS
!     CALLED IF THERE ARE MORE THAN IRRTRE TREE RECORDS.  IN THIS
!     SITUATION ONLY PROGNOSIS TREE VARIABLES ARE COMPRESSED AND NOT
!     ROOT DISEASE VARIABLES.  OTHERWISE ROOT DISEASE COMPRESS
!     WOULD REACH OUTSIDE ROOT DISEASE ARRAY BOUNDARIES.  DEACTIVATION
!     OF ROOT DISEASE COMPRESS IS ACCOMPLISHED BY INSERTING SPECIAL CODE
!     IN RDCMPR AND RDTDEL.
!
IF (.NOT. LTEE) THEN
   IF (INUM .EQ. 1) THEN
      GOTO 225                  !RETURN
   ELSEIF (INUM .EQ. 2 .AND. ITRN .LE. IRRTRE) THEN
      GOTO 222
   ELSE
      GOTO 90
   ENDIF
ENDIF

!
!     COMPRESS THE TREE LIST FOR ROOT DISEASE IF NUMBER OF TREES
!     EXCEEDS DEFAULT VALUE FOR ROOT DISEASE MODEL.
!
!     25-MAR-2003
!     The FVS compression routine expects values in the WK2 array to
!     be mortality. Mortality has not been predicted at this time, but
!     other processes (SVS) may have used WK2 and left residual values.
!     WK2 needs to be reset to zero for compression to function properly.
!     As of this date, the next user of the WK2 array is CUTS which
!     stores (not retrieves) removal priority values in WK2.
!     This change was discussed and agreed upon by Gary Dixon and Lance David.

90 CONTINUE
ICCY = 1
KDT = IY(ICCY)

DO 91 I =1,ITRN
   WK2(I)=0.0
91 CONTINUE

CALL COMPRS (IRCOMP,0.5)

!
!     ADD OPTION PROCESSING LOGIC FOR COMPRS.
!
PRMS(1) = FLOAT(IRCOMP)
PRMS(2) = 0.5

CALL OPADD (KDT,MYACT(1),KDT,2,PRMS,II)

!
!     REESTABLISH THE SPECIES-ORDER SORT.
!
CALL SPESRT
!
!     REESTABLISH THE DIAMETER SORT.
!
CALL RDPSRT (ITRN,DBH,IND,.TRUE.)
!
!     INITIALIZE SPCNT (EQUIVALENCED TO WK6).
!
!LRD     DO 50 I=1,33
!LRD         WK6(I) = 0.0

DO 50 I=1,MAXSP
  DO 49 II=1,3
    SPCNT(I,II) = 0.0
49   CONTINUE
50 CONTINUE

!
!     RE-COMPUTE THE SPECIES COMPOSITION
!
DO 60 I=1,ITRN
   IS = ISP(I)
   IM = IMC(I)
   SPCNT(IS,IM) = SPCNT(IS,IM) + PROB(I)
60 CONTINUE

!
!     RE-COMPUTE THE DISTRIBUTION OF TREES PER ACRE AND SPECIES-
!     TREE CLASS COMPOSITON BY TREES PER ACRE.
!
!     (MAKE SURE IFST=1, TO GET A NEW SET OF POINTERS TO THE
!      DISTRIBUTIONS).
!
IFST = 1
CALL PCTILE (ITRN,IND,PROB,WK3,ONTCUR(7))
CALL DIST (ITRN,ONTCUR,WK3)
CALL COMP (OSPCT,IOSPCT,SPCNT)
IF (LTEE .AND. INUM .EQ. 2) GOTO 225
!
!     CALL ROOT DISEASE SETUP ROUTINE.
!
222 CONTINUE
CALL RDSETP

225 CONTINUE
IF (DEBUG) WRITE (JOSTND,*) 'EXIT RDMN1'
RETURN
END
