SUBROUTINE RDMN2 (XFINT)
IMPLICIT NONE
!----------
! RD $Id$
!----------
!
!  SETS UP INITIAL CONDITIONS FOR THE OTHER AGENTS AND ROOT DISEASE
!  MODELS, AND UPDATES THE STUMP LISTS. NOTE THAT THIS HAPPENS BEFORE
!  TRIPLING AND COMPRESSION
!
!  CALLED BY :
!     GRINCR  [PROGNOSIS]
!
!  CALLS     :
!     DBCHK   (SUBROUTINE)   [PROGNOSIS]
!     RDSUM   (SUBROUTINE)   [ROOT DISEASE]
!     RDSHST  (SUBROUTINE)   [ROOT DISEASE]
!
!  PARAMETERS :
!     XFINT  -
!
!  Revision History :
!   03/01/95 - Last revision date.
!   08/29/14 Lance R. David (FMSC)
!     Added implicit none and declared variables.
!   03/01/2016 Lance R. David (FMSC)
!     Moved check to exit if not active, no trees or no disease area
!     to top.
!----------------------------------------------------------------------
!
!OMMONS
!
! PARAMETER FILES
INCLUDE 'PRGPRM.f90'
INCLUDE 'RDPARM.f90'
!
!OMMONS
INCLUDE 'RDCOM.f90'
INCLUDE 'RDARRY.f90'
INCLUDE 'RDCRY.f90'
INCLUDE 'ARRAYS.f90'
INCLUDE 'CONTRL.f90'
INCLUDE 'RDADD.f90'

LOGICAL  DEBUG
INTEGER  I, IDI, J
REAL     TPAREA, XFINT

!     Exit if not active or no trees.
IF (IROOT .EQ. 0 .OR. ITRN .EQ. 0) RETURN
!
!     SEE IF WE NEED TO DO SOME DEBUG.
!
CALL DBCHK (DEBUG,'RDMN2',5,ICYC)

ISTEP = ISTEP + 1
IF (DEBUG) WRITE (JOSTND,100) ICYC, ISTEP
100 FORMAT (' RDMN2 :  ICYC ISTEP=',2I5)
IYEAR = IYEAR + INT(XFINT)
TPAREA = 0.0
DO 105 IDI=MINRR,MAXRR
   TPAREA = TPAREA + PAREA(IDI)
105 CONTINUE

!     Exit if no disease area.
IF (TPAREA .EQ. 0.0) RETURN

!
!     INCREMENT THE TIME STEP COUNTERS FOR THE GENERAL ROOT DISEASE
!     MODEL.
!
!     ZERO OUT VARIABLES FOR THE SIMULATION.
!
!     PROBIN IS USED THE CARRYOVER MODEL
!
DO 350 IDI=MINRR,MAXRR
   DO 300 I=1,2
      DO 200 J=1,5
         PROBIN(IDI,I,J) = 0.0
200       CONTINUE
300    CONTINUE
350 CONTINUE

!
!     INITIALIZE RRKILL (RDKILL IS NEEDED NEXT TIMESTEP (AS PRANKL) SO WILL
!                        NOT BE ZEROED HERE)
!
DO 400 I=1,ITRN
   RRKILL(I) = 0.0
!         RDKILL(I) = 0.0
400 CONTINUE

!
!     SUM THE ARRAY PROBI INTO THE ACCUMULATOR ARRAY PROBIT.
!
CALL RDSUM (ITRN,PROBIT,PROBI,ISTEP)

!
!     UPDATE THE STUMP HISTORY ARRAYS.
!
CALL RDSHST

RETURN
END
