SUBROUTINE RDPRIN (IRRTR)
IMPLICIT NONE
!----------
! RD $Id$
!----------
!
!  THIS SUBROUTINE CALCULATES THE NUMBER OF TREES PER ACRE THAT EACH
!  TREE RECORD REPRESENTS FOR THE ROOT DISEASE MODEL TREE CLASSES PROBI,
!  FPROB,PROBIU AND PROPI. THIS ROUTINE IS CALLED FROM NOTRE. THESE
!  INITIAL CALCULATIONS ARE MODIFIED IN RRINIT TO PUT THEM ON THE PROPER
!  ACERAGE BASIS. IPRFL=0 IF TREE IS OUTSIDE DISEASE PATCH,IPRFL=1-3
!  IF TREE IS INSIDE PATCH AND INFECTED WITH CORRESPONDING SEVERITY,
!  IPRFL=4 IF IT IS A DEAD INFECTED STUMP AND IPRFL=5 IF TREE IS INSIDE
!  PATCH AND NOT INFECTED
!  THIS ROUTINE IS SKIPPED IF THE DISEASE IS BEING INITIALIZED MANUALLY
!
!  CALLED BY :
!     NOTRE   [PROGNOSIS]
!
!  CALLS     :
!     NONE
!
!  PARAMETERS :
!     IRRTR  -
!
! REVISION HISTORY:
!   21-MAY-2002  Lance R. David (FHTET)
!     The previous date of change was March 1, 1995.
!     The TPA represented by dead tree records was unadjusted as
!     described at the point of change below and further described in
!     the FVS subroutine NOTRE. To facilitate the unadjustment, FVS
!     common PLOT.F77 was added.
!     This error was discovered by Don Robinson of ESSA.
!   17-JUN-2002  Lance R. David (FHTET)
!     Added debug.
!   08/29/14 Lance R. David (FMSC)
!     Added implicit none and declared variables.
!
!----------------------------------------------------------------------
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
INCLUDE 'RDPARM.f90'
INCLUDE 'ARRAYS.f90'
INCLUDE 'CONTRL.f90'
INCLUDE 'PLOT.f90'
INCLUDE 'RDCOM.f90'
INCLUDE 'RDARRY.f90'
INCLUDE 'RDADD.f90'

LOGICAL  DEBUG
INTEGER  IDI, IRRTR, ISL, KSP
REAL     ANS, HHT, PROBB, RTD

!
!     SEE IF WE NEED TO DO SOME DEBUG.
!
CALL DBCHK (DEBUG,'RDPRIN',6,ICYC)

!
!     IF ROOT DISEASE NOT BEING INITIALIZED BY INPUT TREELIST SKIP
!     TREES/ACRE ASSIGNMENTS. ALSO SKIP IF NUMBER OF TREES > IRRTRE
!     UNLESS THEY ARE DISEASED STUMPS
!
!      IF (.NOT. RRTINV .OR. IRRTR .GT. IRRTRE) GOTO 50
IF (.NOT. RRTINV) GOTO 50
IF (IRRTR .GT. IRRTRE .AND. IPRFL(IRRTR) .NE. 4) GOTO 50
!
!     PROCESS TREES TO MAKE INITIAL CALCULATION
!
IF (IPRFL(IRRTR) .EQ. 0) THEN

!       TREE IS UNINFECTED

  FPROB(IRRTR) = PROB(IRRTR)

ELSEIF (IPRFL(IRRTR) .GE. 1 .AND. IPRFL(IRRTR) .LE. 3) THEN

!       TREE IS INFECTED

  IDI = MAXRR
  IF (MAXRR .LT. 3) IDI = IDITYP(IRTSPC(ISP(IRRTR)))
  PROBI(IRRTR,1,1) = PROB(IRRTR)
!        PROPI(IRRTR,1) = RRINCS(IDI)

ELSEIF (IPRFL(IRRTR) .EQ. 5) THEN

!       TREE IS UNINFECTED BUT INSIDE THE CENTER
  PROBIU(IRRTR) = PROB(IRRTR)

ELSEIF (IPRFL(IRRTR) .EQ. 4) THEN

!        TREE IS AN INFECTED STUMP
!
!        CALCULATE THE ROOT RADIUS OF THE STUMP.

   KSP = ISP(IRRTR)
   CALL RDROOT(KSP,DBH(IRRTR),ANS,PROOT(IRTSPC(KSP)), &
                  RSLOP(IRTSPC(KSP)),HHT)
   RTD = ANS

!        FIND THE SIZE CLASS FOR THE STUMP AND PLACE THE STUMP
!        INTO THE STUMP ARRAY.
!        THE PROB FOR THIS DEAD TREE RECORD NEEDS TO BE UNADJUSTED
!        AS EXPLAINED IN THE FVS SUBROUTINE NOTRE. SIMPLY STATED, THIS
!        RECORD WAS ADJUSTED BASED ON THE GROWTH MEASUREMENT PERIOD AND
!        MORTALITY OBSERVATION PERIOD SO THAT BACKDATED DENSITY IS
!        IS ACCURATE FOR FVS CALIBRATION. FOR EXAMPLE, LIVE TREES MEASURED
!        WITH A GROWTH PERIOD OF 10 YEARS AND DEAD TREES MEASURED WITH A
!        MORTALITY OBSERVATION PERIOD OF 5 YEARS LEAVES THE NUMBER OF DEAD
!        TREES UNDER-REPRESENTED FOR THE 10 YEAR PERIOD.

   ISTFLG = 0
   PROBB = (PROB(IRRTR)/GROSPC/(FINT/FINTM))* SAREA
   CALL RDSSIZ(KSP,DBH(IRRTR),STCUT,ISL,ISPS,IRTSPC)
   CALL RDSTP (ISL,KSP,PROBB,DBH(IRRTR),RTD)

!        RESET AGE. ASSUME ALL LARGER STUMPS IN THE TREE LIST ARE
!        15 YRS OLD (OR HOWEVER OLD USER DECIDES.)

   IDI = MAXRR
   IF (MAXRR .LT. 3) IDI = IDITYP(IRTSPC(KSP))
   JRAGED(IDI,ISPS(IRTSPC(KSP)),ISL,1) = -DEDAGE(ISL)

ENDIF
IF (DEBUG) WRITE(JOSTND,777) ICYC,IRRTR,PROBI(IRRTR,1,1), &
              PROBIU(IRRTR),FPROB(IRRTR)
777 FORMAT(' IN RDPRIN: ICYC,IRRTR,PROBI,PROBIU,FPROB',2(I4),3F8.2)

50 CONTINUE
RETURN
END
