SUBROUTINE RDRATE (NSIM)
IMPLICIT NONE
!----------
! RD $Id$
!----------
!
!  THIS SUBROUTINE CALCULATES SPREAD RATE TO APPLY TO EACH CENTER
!  USING THE RANGE OF VALUES CALCULATED BY THE SPREAD RATE MODEL.
!  CENTERS THAT HAD A ZERO SPREAD RATE LAST YEAR ARE MORE LIKELY TO
!  HAVE A ZERO SPREAD RATE THIS YEAR UNLESS THOSE CENTERS ARE SHRINKING
!  CENTERS.
!
!  CALLED BY :
!     RDSPRD  [ROOT DISEASE]
!
!  CALLS     :
!     DBCHK   (SUBROUTINE)   [PROGNOSIS]
!
!  DEFINITIONS:
!     RRA:    CALCULATED SPREAD RATE FOR EACH CENTER
!     NSIM:   NUMBER OF SIMULATIONS THAT WERE DONE BY THE MONTE CARLO SPREAD MODEL
!     MCRATE: THE RESULT OF EACH OF THE NSIM SIMULATIONS
!     GCENTS: THE NUMBER OF NON-SHRINKING CENTERS (POTENTIALLY GROWING CENTERS)
!
!  Revision History:
!    25-APR-00 Lance R. David (FHTET)
!       Reduced RETURN statements to 1 at the end of routine.
!       Added Debug code.
!    06-AUG-01 Lance R. David (FHTET)
!       Initialization of entire arrays RRA and IPNT instead of just the number
!       of elements represented equal to the current number of centers. That
!       method left calculations using uninitialized elements when the number of
!       disease centers exceeded the number of Monte Carlo simulations.
!   09/02/14 Lance R. David (FMSC)
!     Added implicit none and declared variables.
!
!----------------------------------------------------------------------
!
!.... PARAMETER INCLUDE FILES
!
INCLUDE 'PRGPRM.f90'
INCLUDE 'RDPARM.f90'
!
!.... COMMON INCLUDE FILES
!
INCLUDE 'CONTRL.f90'
INCLUDE 'PLOT.f90'
INCLUDE 'RDCOM.f90'
INCLUDE 'RDARRY.f90'
INCLUDE 'ARRAYS.f90'
INCLUDE 'RDADD.f90'
!
LOGICAL DEBUG, LZERO

INTEGER GCENTS, I, IPNT(100), J, K, NSIM, NUM

REAL    DIV, REM, RRA(100), TEMP, TRR

!
!     SEE IF WE NEED TO DO SOME DEBUG.
!
CALL DBCHK (DEBUG,'RDRATE',6,ICYC)

IF (DEBUG) WRITE (JOSTND,*) &
      'BEGIN RDRATE:  IRRSP=',IRRSP,' NCENTS=',NCENTS(IRRSP)


!     BEGIN PROGRAM

!     INITIALIZE VARIABLES
DO 50 I=1,100
  RRA(I) = 0.0
  IPNT(I) = I
50 CONTINUE

GCENTS = NCENTS(IRRSP) - NSCEN(IRRSP)

IF (DEBUG) WRITE (JOSTND,*) &
     'IN RDRATE: GCENTS=',GCENTS,' NSIM=',NSIM

IF (GCENTS .LE. 0) THEN
   RRRATE(IRRSP) = 0.0
   GOTO 900                ! RETURN
ENDIF

LZERO = .FALSE.
REM = 0.0
K = 1
IF (GCENTS .LE. NSIM) THEN

!       THERE ARE FEWER CENTERS THAN THERE WERE SIMULATIONS SO TAKE THE
!       AVERAGE OF VARIOUS SIMULATIONS AS A SPREAD RATE TO APPLY

  DIV = FLOAT(NSIM) / (FLOAT(GCENTS) + 1E-9)

  DO 150 I= 1, GCENTS
    NUM = INT(DIV + REM)
    REM = DIV + REM - NUM

    DO 100 J= 1, NUM
      RRA(I) = RRA(I) + MCRATE(IRRSP,K)
      K = K + 1
      IF (K .GT. NSIM) NUM = J
100     CONTINUE

      RRA(I) = RRA(I) / (FLOAT(NUM) + 1E-9)
      IF ((.NOT. LZERO) .AND. (RRA(I) .EQ. 0.0)) LZERO = .TRUE.
150   CONTINUE
ELSE

!       THERE ARE MORE CENTERS THAN THERE WERE SIMULATIONS SO APPLY EACH
!       SIMULATED VALUE TO ONE OR MORE CENTERS.

  I = 1
  DIV = FLOAT(GCENTS) / FLOAT(NSIM)
200   CONTINUE

  NUM = INT(DIV + REM)
  REM = DIV + REM - NUM

  DO 250 J= 1, NUM
    RRA(I) = MCRATE(IRRSP,K)
    I = I + 1
    IF ((.NOT. LZERO) .AND. (RRA(I) .EQ. 0.0)) LZERO = .TRUE.
250   CONTINUE

  K = MIN0(NSIM,K + 1)
  IF (I .LE. GCENTS) GOTO 200

ENDIF

!     NOW SORT RRA ARRAY ENOUGH SO THAT THE ZEROS COME TO THE TOP (OTHER
!     VALUES MUST REMAIN UNSORTED)

IF (LZERO) THEN
  DO 350 I= 1,GCENTS
    IF (RRA(I) .EQ. 0.0) THEN
      DO 300 J= I,2, -1
        IF (RRA(J-1) .GT. 0.0) THEN
          TEMP = RRA(J)
          RRA(J) = RRA(J-1)
          RRA(J-1) = TEMP
        ELSE
          GOTO 350
        ENDIF
300       CONTINUE
    ENDIF
350   CONTINUE

!     SET UP POINTERS TO LAST YEAR'S SPREAD RATES TO GET ZEROS AT THE TOP
!     AND SHRINKING CENTERS AT THE BOTTOM. IGNORE ZEROS FROM RECENTLY CREATED
!     SPORE CENTERS
!     (IPNT IS INITIALIZED ABOVE TO BE IPNT(I) = I)

  DO 450 I= 1,NCENTS(IRRSP)
     IF (SHCENT(IRRSP,I,2) .GT. 0.0) THEN
        DO 425 J= I,NCENTS(IRRSP)-1
           IPNT(J) = IPNT(J+1)
425         CONTINUE
        IPNT(NCENTS(IRRSP)) = I
     ELSEIF ((RRATES(IRRSP,I) .EQ. 0.0) .AND. &
                       (ICENSP(IRRSP,I) .EQ. 0)) THEN
       DO 400 J= I,2, -1
         IPNT(J) = IPNT(J-1)
400        CONTINUE
       IPNT(1) = I
     ENDIF
450   CONTINUE
ENDIF

IF (DEBUG) WRITE (JOSTND,*) 'IN RDRATE: MCRATE=',MCRATE
IF (DEBUG) WRITE (JOSTND,*) 'IN RDRATE: RRA=',RRA

!     ASSIGN SPREAD RATES TO CENTERS BASED ON THE POINTER ARRAY

TRR = 0.0
DO 500 I=1,GCENTS
  RRATES(IRRSP,IPNT(I)) = RRA(I)
  TRR = TRR + RRA(I)
500 CONTINUE

IF (DEBUG) WRITE (JOSTND,*) &
     'IN RDRATE: TRR=',TRR,' GCENTS=',GCENTS

RRRATE(IRRSP) = TRR / (FLOAT(GCENTS) + 1E-9)

900 CONTINUE
IF (DEBUG) WRITE (JOSTND,*) 'EXIT RDRATE: RRRATE=',RRRATE(IRRSP)
RETURN
END
