SUBROUTINE RDZERO
IMPLICIT NONE
!----------
! RD $Id$
!----------
!
!  THIS SUBROUTINE TAKES THE CENTERS, CHECKS IF THE RADIUS OF ANY IS ZERO
!  (OR SMALL, LESS THAN 0,01)
!  AND REMOVES IT FROM CONSIDERATION. WHEN A CENTER IS REMOVED, ALL VARIABLES
!  REFERENCING A CENTER BY CENTER NUMBER MUST BE UPDATED.
!
!  CALLED BY :
!     RDCNTL  [ROOT DISEASE]
!
!  CALLS     :
!     DBCHK   (SUBROUTINE)   [PROGNOSIS]
!
!  DEFINITIONS:
!
!  Revision History:
!   10/04/93 - Last revision date.
!   09/04/14 Lance R. David (FMSC)
!     Added implicit none and declared variables.
!
!----------------------------------------------------------------------
!
!
!.... PARAMETER INCLUDE FILES
!
INCLUDE 'PRGPRM.f90'
INCLUDE 'RDPARM.f90'
!
!.... COMMON INCLUDE FILES
!
INCLUDE 'CONTRL.f90'
INCLUDE 'PLOT.f90'
INCLUDE 'RDCOM.f90'
INCLUDE 'RDARRY.f90'
INCLUDE 'ARRAYS.f90'
INCLUDE 'RDADD.f90'
!
LOGICAL DEBUG
INTEGER I, ICEN, ICENT, JCEN

!
!     SEE IF WE NEED TO DO SOME DEBUG.
!
CALL DBCHK (DEBUG,'RDZERO',6,ICYC)

IF (DEBUG) WRITE (JOSTND,1)
1 FORMAT (' STARTING RDZERO')

!     BEGIN PROGRAM
ICENT = NCENTS(IRRSP)

DO 300 ICEN= ICENT,1,-1
  IF (PCENTS(IRRSP,ICEN,3) .LE. 0.01) THEN

!         REDUCE THE NUMBER OF CENTERS
    NCENTS(IRRSP) = NCENTS(IRRSP) - 1
    IF (SHCENT(IRRSP,ICEN,2) .GT. 0.0) &
                       NSCEN(IRRSP) = NSCEN(IRRSP) - 1

!         MOVE EVERYTHING UP ONE PLACE
    DO 200 JCEN= ICEN,ICENT-1
      DO 150 I= 1,3
        PCENTS(IRRSP,JCEN,I) = PCENTS(IRRSP,JCEN+1,I)
        SHCENT(IRRSP,JCEN,I) = SHCENT(IRRSP,JCEN+1,I)
150       CONTINUE
      ICENSP(IRRSP,JCEN) = ICENSP(IRRSP,JCEN+1)
      RRATES(IRRSP,JCEN) = RRATES(IRRSP,JCEN+1)
200     CONTINUE

!         IF THIS IS THE FIRST CENTER TO BE REMOVED, PUT A ZERO IN THE LAST PLACE
    IF (NCENTS(IRRSP) .EQ. (ICENT-1)) THEN
      ICENSP(IRRSP,ICENT) = 0
      RRATES(IRRSP,ICENT) = 0.0
      DO 100 I= 1,3
        PCENTS(IRRSP,ICENT,I) = 0.0
        SHCENT(IRRSP,ICENT,I) = 0.0
100       CONTINUE
    ENDIF
  ENDIF
300 CONTINUE


RETURN
END
