SUBROUTINE GRCLAS (NRECS,IPT,ATR,ISC,NCLAS,NATR,CLAS, &
                      PROB,IMPROB,IPOS,MAXCLS,ITWO)
IMPLICIT NONE
!----------
! DFTM $Id$
!----------
!
!     CALLED FROM 'GARBEL'   N.L. CROOKSTON  JAN 1978 & JAN 1981
!
!          NRECS = LENGTH OF POINTER ARRAY
!          IPT   = POINTER ARRAY
!          NCLAS = NUMBER OF CLASSES
!          CLAS  = CLASSIFIED ARRAY (ONE WHICH HOLDS CLASSIFIED DATA)
!          PROB  = WEIGHT OF EACH MEMBER OF ATR
!          IPOS  = THE POSITION WITHIN 'CLAS' OF THIS ATTRIBUTE
!          IMPROB= POSITION WITHIN CLAS OF PROB
!          NATR  = NUMBER OF ATTRIBUTES (NEEDED FOR OBJECT
!                  TIME DIMENSIONING OF CLAS.)
!          ISC   = SECTOR POINTERS TO BE USED WITH 'IPT'
!
!  03-APR-2002 Lance R. David (FHTET)
!     Arrays dimensioned "1" changed to "*" so that array size is
!     inherited from calling routine.
!----------

INTEGER IPOS,IMPROB,NCLAS,NRECS,MAXCLS,ITWO,ISC,NATR
INTEGER IPT,I3,I1,I2,J,II,I
REAL CLAS,PROB,ATR,XP

DIMENSION IPT(*),ISC(MAXCLS,ITWO),PROB(*),CLAS(MAXCLS,NATR), &
             ATR(*)
!
I3 = IPOS
DO 20 J = 1, NCLAS
I1 = ISC(J,1)
I2 = ISC(J,2)
CLAS(J,I3) = 0.0
!
DO 10 II = I1, I2
I = IPT(II)
CLAS (J,I3) = CLAS (J,I3) + ATR(I) * PROB(I)
10 CONTINUE
!
XP = CLAS (J,IMPROB)
IF ( XP .GT. 1.E-30 ) CLAS (J,I3) = CLAS (J,I3) / XP
20 CONTINUE
!
RETURN
END
