SUBROUTINE INSCYC (IFROM,IBOUND,ISPOT,LCHFNT,LMORE,IOUT,DEBU)
IMPLICIT NONE
!----------
! DFTM $Id$
!----------
!
!     THIS ROUTINE INSERTS A CYCLE IN THE SPECIFED SPOT
!     AFTER FIRST INSURING THAT ONE DOES NOT EXIST IN THE SPOT
!     REQUESTED AND THAT THERE IS ROOM FOR THE THE CYCLE WITHIN THE
!     THE TOTAL LENGTH OF PROJECTION YEARS REQUESTED BY THE
!     USER. THE ROUTINE INSURES THAT IFINT AND FINT ARE PROPERLY
!     SET WHEN A CYCLE IS INSERTED.
!
!     NICK CROOKSTON;    PROGRAMMER.   INT -- MOSCOW  MAY 1978
!     REVISED BY CROOKSTON TO WORK WITH THE WAY OPTIONS ARE
!     HANDLED IN VERSION 4.0 --- MAY 1981 (3 YRS LATER)
!     REVISED BY CROOKSTON TO WORK WITH PPE (FEB 1983).
!     REVISED BY CROOKSTON TO UPGRADE TREELIST PROCESSING (APR 1984).
!
!
!     LCHFNT= TRUE IF YOU WANT IFINT & FINT TO BE RESET.
!     LMORE = TRUE IF YOU HAVE MORE CYCLES TO INSERT BESIDES THIS
!             PARTICLAR CYCLE.  THIS IS MENT TO BE A CPU TIME SAVER.
!             IF YOU DO NOT UNDERSTAND WHAT ITS VALUE SHOULD BE,
!             ALWAYS SET IT FALSE.
!     IFROM = THE CYCLE NUMBER THAT IBOUND IS TO BE ADDED.
!     IBOUND= THE NUMBER OF YEARS HENCE THAT YOU WISH TO INSURE
!             THAT A CYCLE WILL EXEC.
!     ISPOT = THE SUBSCRIPT OF THE INSERTED CYCLE
!     IOUT  = PRINT UNIT NUMBER FOR DEBUG MSG.
!     DEBU  = TRUE IF DEBUGING
!     IYLAST= NUMBER OF CYCLES PLUS 1 (NCYC+1)
!
LOGICAL  DEBU,LCHFNT,LMORE,LOK
!
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
!OMMONS

INTEGER IOUT,ISPOT,IBOUND,IFROM,IYLAST,I,IYPB,I1,I2

!     **********     EXECUTION BEGINS     **********
!
IYLAST = NCYC + 1
IF ( DEBU  ) THEN
   WRITE (IOUT,5) (IY(I),I=1,IYLAST)
5    FORMAT (/,' INSCYC:IY= ',20I6,/,6X,21I6)
ENDIF
!
!     STEP1 CHECK TO SEE IF THE PROPER CYCLING EXISTS.
!
ISPOT = 0
DO 10 I= IFROM, IYLAST
ISPOT = I
IF ( IY(I) .GT. IY(IFROM) + IBOUND ) GO TO 20
IF ( IY(I) .EQ. IY(IFROM) + IBOUND ) GO TO 200
10 CONTINUE
!
!     THE LAST YEAR OF THE LAST CYCLE IS LESS THAN THE CYCLE
!     YEAR THAT IS REQUESTED.  CHECK WITH PPE TO INSURE IT IS OK TO
!     CHANGE THE CYCLE.  IF IT IS OK, THEN SET THE LAST YEAR OF THE
!     LAST CYCLE EQUAL TO THE YEAR THAT IS REQUESTED.
!
IYPB=IY(IFROM)+IBOUND
CALL PPECYC (IYPB,LOK)
IF (LOK) GOTO 15
ISPOT=0
RETURN
15 CONTINUE
I1 = NCYC
GO TO 100
20 CONTINUE
IF ( ISPOT .GT. 40 ) CALL ERRGRO (.FALSE.,19)
!
!     CHECK WITH PARALLEL PROCESSING EXTENSION...
!
CALL PPECYC (IYPB,LOK)
IF (LOK) GOTO 25
ISPOT=0
RETURN
25 CONTINUE
!
!     STEP2 RESET NCYC
!
NCYC = NCYC + 1
IYLAST = NCYC + 1
!
!     STEP3 MOVE VALUES; MAKE ROOM FOR THE TO-BE-INSERTED CYCLE.
!
I = 0
30 CONTINUE
I1 = NCYC - I
I2 = I1 - 1
IY  (IYLAST-I) = IY  (IYLAST-I-1)
I = I + 1
!
IF ( I2 .GE. ISPOT ) GO TO 30
IY  (IYLAST-I) = IY  (IYLAST-I-1)
!
!     STEP4 READY TO INSERT.
!
IY ( ISPOT ) = IY ( IFROM ) + IBOUND
I1 = ISPOT - 1
I2 = ISPOT + 1
IF (LMORE) GOTO 230
CALL OPCYCL (NCYC,IY)
CALL OPCSET (ICYC)
GO TO 230
100 CONTINUE
IY(I1+1) = IY(IFROM) + IBOUND
GO TO 230
!
200 CONTINUE
ISPOT = 0
!
230 CONTINUE
!
!     STEP5 RESET IFINT AND FINT
!
IF ( .NOT. LCHFNT ) GO TO 235
IFINT = IY(ICYC+1) - IY(ICYC)
FINT = IFINT
235 CONTINUE
!
IF ( .NOT. DEBU  ) RETURN
WRITE (IOUT,240)  IFROM,IBOUND,ISPOT,LCHFNT,ICYC,NCYC,IFINT,LMORE
240 FORMAT (' INSCYC: BEFORE RETURN:',/,' IFROM    IBOUND     ISPOT', &
           '     LCHFNT     ICYC     NCYC      IFINT     LMORE',/, &
           I5,2I10,L10,3I10,L10)
WRITE (IOUT,5) (IY(I),I=1,IYLAST)
RETURN
END
