FUNCTION TMBCHL (XBAR, STDEV)
IMPLICIT NONE
!----------
! DFTM $Id$
!----------
!----------
!  THIS FUNCTION RETURNS A RANDOM NUMBER DRAWN FROM THE
!  NORMAL DISTRIBUTION DESCRIBED BY (XBAR,STDEV).  THIS FUNCTION
!  UTILIZES THE COMPOSITE REJECTION TECHNIQUE DEVELOPED BY
!  BATCHELOR AND DESCRIBED IN:
!
!      TOCHER, K.D.  1963. THE ART OF SIMULATION. D. VAN NOSTRAND
!                    COMPANY, INC. PRINCETON, NJ. 184 P. (PP 24/27).
!
!  DEFINITION OF VARIABLES.
!
!    TMBCHL -- GENERATED NORMAL RANDOM VARIABLE.
!    TMRANN -- SUBROUTINE THAT GENERATES UNIFORM RANDOM NUMBERS.
!    XBAR   -- MEAN OF THE NORMAL DISTRIBUTION FROM WHICH TMBCHL
!              IS DRAWN.
!    STDEV  -- STANDARD DEVIATION OF THE NORMAL DISTRIBUTION FROM
!              WHICH TMBCHL IS DRAWN.
!
!  DEFINITION OF INTERNAL VARIABLES.
!
!         X -- COMPUTED ORDINAL OF THE STANDARDIZED NORMAL
!              DISTRIBUTION FUNCTION.
!         U -- UNIFORM RANDOM NUMBER DRAWN TO REPRESENT THE INTEGRAL
!              OF THE STANDARDIZED NORMAL PDF EVALUATED FROM -X TO
!              X.  IF U IS LESS THAN 2/3, X IS APPROXIMATED FROM A
!              UNIFORM DISTRIBUTION.  OTHERWISE, X IS APPROXIMATED
!              FROM A NEGATIVE EXPONENTIAL DISTRIBUTION.
!         Z -- VALUE COMPUTED ASSUMING X IS EXPONENTIALLY
!              DISTRIBUTED.
!         Y -- EXPONENTIALLY DISTRIBUTED RANDOM VARIATE.  IF Y IS
!              LESS THAN OR EQUAL TO Z, X IS REJECTED AND REDRAWN.
!        R1 -- UNIFORM RANDOM NUMBER DRAWN TO GENERATE Y.
!        R2 -- UNIFORM RANDOM NUMBER DRAWN TO ASSIGN A SIGN TO X.
!

REAL STDEV,XBAR,TMBCHL,U,R1,R2,X,Y,Z,A,SIGNX

10 CONTINUE
!
!     DRAW THREE UNIFORM RANDOM NUMBERS;  U, R1, AND R2.
!
CALL TMRANN(U)
CALL TMRANN(R1)
CALL TMRANN(R2)

!
!     DETERMINE METHOD OF APPROXIMATION.
!
IF (U .LE. (2.0 / 3.0)) GOTO 20

!
!     CALCULATE X AND Z ASSUMING A NEGATIVE EXPONENTIAL DISTRIBUTION.
!
X = 1.0 - 0.5 * ALOG(3.0 * U - 2.0)
Z = 0.5 * (X - 2.0)**2
GOTO 30

!
!     CALCULATE X AND Z ASSUMING A UNIFORM DISTRIBUTION.
!
20 X = 1.5 * U
Z = 0.5 * X * X

!
!     DRAW REJECTION PARAMETER FROM AN EXPONENTIAL DISTRIBUTION AND
!     DETERMINE IF REJECTION IS NECESSARY.
!
30 Y = -ALOG(R1)
IF (Y .LE. Z) GOTO 10

!
!     SELECT THE SIGN OF X
!
A = 0.5 - R2
SIGNX = A / ABS(A)
X = X * SIGNX
!
!  SCALE STANDARDIZED NORMAL RANDOM VARIATE FOR INPUT MEAN AND
!  STANDARD DEVIATION AND RETURN IT AS TMBCHL.
!
TMBCHL = X * STDEV + XBAR

RETURN
END
