SUBROUTINE TMDAM (II, ICODES)
IMPLICIT NONE
!----------
! DFTM $Id$
!----------
!
!     CALLED BY PROGNOSIS VERSION 6.0
!     CALLED BY:  SUBAROUTINE DAMCDS
!
!     THIS ROUTINE WILL BE USED IN FUTURE UPDATES TO THE DOUGLAS FIR TUSSOCK
!     MOTH MODEL.  IT WILL BE USED TO READ IN DAMAGE CODES FROM THE STAND DATA.
!
!     FVS TREE VARIABLES THAT MAY BE NEEDED FOR PROCESSING OF DAMAGE CODES
!     CAN BE ACCESSED BY INCLUDING THE NECESSARY COMMON BLOCKS.
!
INTEGER II, ICODES(6)

RETURN
END

