SUBROUTINE TMOUT
IMPLICIT NONE
!----------
! DFTM $Id$
!----------
!
!     PRINT FINAL TUSSOCK MOTH ACTIVITY SUMMARY
!
!     PART OF THE DFTM EXTENSION OF THE PROGNOSIS SYSTEM.
!
! Revision History:
!   23-DEC-99; Lance R. David (FHTET-FC)
!      Updated for expansion of FVS stand id (variable NPLT)
!      from 8 to 26 characters.
!   01-APR-2013 Lance R. David (FMSC)
!      A few variables defined locally were already defined
!      in a common block. Local declaration removed.
!
!----------
!
!OMMONS
!
INCLUDE 'PRGPRM.f90'

INCLUDE 'CONTRL.f90'

INCLUDE 'PLOT.f90'

INCLUDE 'TMCOM1.f90'
!
!OMMONS
!
CHARACTER*3 YES, NO, WASTHR

CHARACTER*132 PRNT

INTEGER I

DATA YES /'YES'/,  NO /'NO'/
LOGICAL LOPEN

!
!     CHECK TO SEE IF OUTPUT FILE IS OPEN.  IF NOT OPEN THEN EXIT.
!
INQUIRE (UNIT=JODFTM, OPENED=LOPEN)
IF (.NOT. LOPEN) GOTO 200

!
!     IF THE DFTM OUTPUT FILE DATA SET REFERENCE NUMBER IS
!     EQUAL TO THE MAJOR PRINT FILE NUMBER; THEN RETURN.
!
IF (JODFTM .EQ. JOSTND) RETURN

!
!     REWIND DFTM OUTPUT FILE.
!
REWIND JODFTM

!
!     IF THE REPORT LEVEL IS ZERO; RETURN
!
IF (ITMREP .EQ. 0) RETURN

CALL TMHED (JOSTND, NPLT, MGMID)
IF (ITMREP .EQ. 1) GOTO 50

10 CONTINUE
READ (JODFTM,20,END=40) PRNT
20 FORMAT (A132)

WRITE (JOSTND,20) PRNT
GOTO 10

40 CONTINUE
!
!     READY THE OUTPUT FILE FOR ANOTHER STAND.
!
REWIND JODFTM
!
50 CONTINUE
!
WRITE (JOSTND,9016)NPLT
9016 FORMAT (/22('-'),' DFTM OUTBREAK SUMMARY TABLE  ',25('-'),/, &
         'STAND ID = ',A26,//, &
         '------ CYCLE ------',8X,'YEAR OF',T46,'CONDITIONAL',T67, &
         'WAS THERE AN'/'NUMBER',T15,'YEARS',5X,'REGIONAL DFTM', &
         T46,'PROBABILITY',10X,'OUTBREAK IN'/T28,'OUTBREAK',7X, &
         'OF STAND OUTBREAK         STAND?'/79('-')/)

DO 140 I=1,NCYC
  WASTHR = NO
  IF (TMWORK(I)) WASTHR = YES
  IF (TMYRS(I) .EQ. 0) WRITE (JOSTND,9017) I, IY(I), IY(I+1), &
                          TMPRB(I), WASTHR
  IF (TMYRS(I) .NE. 0) WRITE (JOSTND,9018) I, IY(I), IY(I+1), &
                          TMYRS(I), TMPRB(I), WASTHR
9017   FORMAT(I3,I9,' -',I5,T45,F10.3,T71,A3)
9018   FORMAT(I3,I9,' -',I5,I14,T45,F10.3,T71,A3)
140 CONTINUE

200 CONTINUE

RETURN
END
