BLOCK DATA CUBRDS
IMPLICIT NONE
!----------
! WC $Id$
!----------
!  DEFAULT PARAMETERS FOR THE CUBIC AND BOARD FOOT VOLUME EQUATIONS.
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'VOLSTD.f90'
!
!
!OMMONS
!----------
!  COEFFICIENTS FOR CUBIC FOOT VOLUME FOR TREES THAT ARE SMALLER THAN
!  THE TRANSITION SIZE
!----------
DATA CFVEQS/ 273*0.0 /
!----------
!  COEFFICIENTS FOR CUBIC FOOT VOLUME FOR TREES THAT ARE LARGER THAN
!  THE TRANSITION SIZE
!----------
DATA CFVEQL/ 273*0.0 /
!----------
!  FLAG IDENTIFYING THE SIZE TRANSITION VARIABLE; 0=D, 1=D2H
!----------
DATA ICTRAN/39*0/
!----------
!  TRANSITION SIZE.  TREES OF LARGER SIZE (D OR D2H) WILL COEFFICIENTS
!  FOR LARGER SIZE TREES.
!----------
DATA CTRAN/ 39*0.0 /
!----------
!  COEFFICIENTS FOR BOARD FOOT VOLUME FOR TREES THAT ARE SMALLER THAN
!  THE TRANSITION SIZE
!----------
DATA BFVEQS/ 273*0.0 /
!----------
!  COEFFICIENTS FOR BOARD FOOT VOLUME FOR TREES THAT ARE LARGER THAN
!  THE TRANSITION SIZE
!----------
DATA BFVEQL/ 273*0.0/
!----------
!  FLAG IDENTIFYING THE SIZE TRANSITION VARIABLE; 0=D, 1=D2H
!----------
DATA IBTRAN/ 39*0 /
!----------
!  TRANSITION SIZE.  TREES OF LARGER SIZE (D OR D2H) WILL USE COEFFICIENTS
!  FOR LARGER SIZE TREES.
!----------
DATA BTRAN/ 39*0.0 /
END
