SUBROUTINE DGBND (ISPC,DBH,DDG)
IMPLICIT NONE
!----------
! WC $Id$
!----------
!  THIS SUBROUTINE IS USED TO INSURE THAT A MAXIMUM VALUE FOR DG
!  IS NOT EXCEEDED.
!
! ALL SPECIES EXCEPT REDWOOD USE THE SAME BOUNDING FUNCTION WHICH
! WAS DEVELOPED FOR DOUGLAS-FIR.
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
!OMMONS
!
!----------
! MAX DG CHECK.
!----------
INTEGER ISPC
REAL DDG,DBH,TEMDBH,DGMAX

! INCOMING DIAMETER INCREMENT IS ASSIGNED TO DDG IF SPECIES IS REDWOOD
! ALL OTHER SPECIES HAVE BOUNDING LOGIC APPLIED
SELECT CASE(ISPC)
  CASE(17)
    DDG=DDG
  CASE DEFAULT
    TEMDBH=DBH
    IF(TEMDBH .GT. 150.)TEMDBH=150.
    DGMAX = (7.92*EXP(-0.03*TEMDBH))
    IF(DDG .GT. DGMAX) DDG = DGMAX
    IF(DDG .LT. 0.0) DDG = 0.0
END SELECT
!----------
! CHECK FOR SIZE CAP COMPLIANCE.
!----------
IF((DBH+DDG).GT.SIZCAP(ISPC,1).AND.SIZCAP(ISPC,3).LT.1.5)THEN
  DDG=SIZCAP(ISPC,1)-DBH
  IF(DDG .LT. 0.01) DDG=0.01
ENDIF

RETURN
END
