SUBROUTINE DUBSCR(ISPC,D,H,PRD,QMDPLT,CR,TPCT,TPCCF)
IMPLICIT NONE
!----------
! WC $Id$
!----------
!
!  THIS SUBROUTINE CALCULATES CROWN RATIOS FOR TREES
!  IN THE INVENTORY THAT ARE MISSING CROWN RATIO
!  MEASUREMENTS AND ARE LESS THAN 1.0 INCH DBH.
!
!  ALSO USED TO DUB CROWN RATIOS FOR ALL DEAD TREES.
!
!  SF,WF,GF,AF,RF,NF,ES  USES BCR_(1) COEFFICIENTS
!  DF USES BCR_(2) COEFFICIENTS
!  YC,IC,RC,WH,MH USES BCR_(3) COEFFICIENTS
!  LP,JP,SP,WP,PP,LL,WB,KP,PY USES BCR_(4) COEFFICIENTS
!  BM,RA,WA,PB,GC,AS,CO,WO,DG,HW,BC,WI CONSTANT ICR=5
!  J  CONSTANT ICR=9
!
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'PDEN.f90'
!
!
!OMMONS
!
LOGICAL DEBUG
EXTERNAL RANN
REAL BCR0(6),BCR1(6),BCR2(6),CRSD(6)
REAL BACHLO,CR,D,FCR,H,HDR,PRD,QMDPLT,SD,TPCCF,TPCT
INTEGER IMAP(39),ISPC,IISPC
REAL RDANUW
!
DATA IMAP/7*1,2*3,1,5*4,2*2,3*3,8*5,6,4*4,6*5/
!
DATA BCR0/ &
    8.042774, 8.477025, 7.558538, 6.489813, 5.000000, 9.000000/
DATA BCR1/ &
    0.007198, -0.018033, -0.015637, -0.029815, 0.000000, 0.000000/
DATA BCR2/ &
    -0.016163, -0.018140, -0.009064, -0.009276, 0.000000, 0.000000/
DATA CRSD/ &
    1.3167, 1.3756, 1.9658, 2.0426, 0.5, 0.5/
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
RDANUW = D
RDANUW = TPCCF
RDANUW = TPCT
!-----------
!  CHECK FOR DEBUG.
!-----------
CALL DBCHK (DEBUG,'DUBSCR',6,ICYC)
!----------
!  EXPECTED CROWN RATIO IS A FUNCTION OF SPECIES, HEIGHT,
!  AND BASAL AREA. THE EQUATION RETURNS A CROWN CODE VALUE 0-9
!----------
IISPC=IMAP(ISPC)

!----------
! EXPECTED CROWN RATIO FOR RW IS A FUNCTION OF DBH, HEIGHT DIAMETER
! RATIO (H/D), RELATIVE DENSITY AND RELATIVE DIAMETER THE MODEL IS BASED
! ON THE LOGISTIC FUNCTION, AND RETURNS A VALUE BETWEEN ZERO AND ONE.
!----------

! CALCULATE HDR
HDR = (H*12)/D

! RW CR CALCULATION
IF(ISPC .EQ. 17) THEN
  CR =  -1.021064 + 0.309296*LOG(HDR) + &
           0.869720*PRD - 0.116274*(D/QMDPLT)

! RW DEBUG
  IF(DEBUG)WRITE(JOSTND,*)'IN DUBSCR - RW',' D=',D,' H=',H, &
     ' PRD=',PRD,' QMDPLT=',QMDPLT,' HDR=', HDR,' CR=',CR

!----------
!  EXPECTED CROWN RATIO IS A FUNCTION OF SPECIES, HEIGHT,
!  AND BASAL AREA. THE EQUATION RETURNS A CROWN CODE VALUE 0-9
!----------

! ALL OTHER SPECIES CR CALCULATION
ELSE
  CR=BCR0(IISPC) + BCR1(IISPC)*H + BCR2(IISPC)*BA
ENDIF

!----------
!  ASSIGN A RANDOM ERROR TO THE CROWN RATIO PREDICTION
!  VALUES OF CRSD ARE THE STANDARD ERROR VALUES FROM REGRESSION
!  REDWOOD GETS VALUE OF 0.15 ASSIGNED TO REFLECT NEW CR
!  EQUATION.Coo
!----------
SD=CRSD(IISPC)
IF(ISPC .EQ. 17) SD=0.15
10 FCR=BACHLO(0.0,SD,RANN)
IF(ABS(FCR).GT.SD) GO TO 10
IF(DEBUG)WRITE(JOSTND,*)' IN DUBSCR H,BA,CR,FCR= ', &
   H,BA,CR,FCR
CR=CR+FCR
!----------
!  CONVERT CODE VALUE TO A CROWN RATIO PROPORTION 0-1.
!----------
IF(ISPC .EQ. 17) THEN
  CR = 1.0/(1.0 + EXP(CR))
ELSE
  CR=((CR-1.0)*10.0 + 1.0) / 100.
END IF

IF(CR .GT. .95) CR=.95
IF(CR .LT. .05) CR=.05

IF(DEBUG)WRITE(JOSTND,600)ISPC,H,BA,CR
600 FORMAT(' IN DUBSCR, ISPC= ',I2,' H= ',F5.1,' BA= ',F9.4, &
   ' CR= ',F4.3)
RETURN
END
