SUBROUTINE ESSUBH (I,HHT,EMSQR,DILATE,DELAY,ELEVDUM,IHTSER,GENTIM, &
                      TRAGE)
IMPLICIT NONE
!----------
! WC $Id$
!----------
!     ASSIGNS HEIGHTS TO SUBSEQUENT AND PLANTED TREE RECORDS
!     CREATED BY THE ESTABLISHMENT MODEL.
!     COMING INTO ESSUBH, TRAGE IS THE AGE OF THE TREE AS SPECIFIED ON
!     THE PLANT OR NATURAL KEYWORD.  LEAVING ESSUBH, TRAGE IS THE NUMBER
!     BETWEEN PLANTING (OR NATURAL REGENERATION) AND THE END OF THE
!     CYCLE.  AGE IS TREE AGE UP TO THE TIME REGENT WILL BEGIN GROWING
!     THE TREE.
!
!     CALLED FROM **ESTAB
!     CALLS **SMHGDG
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'ESPARM.f90'
!
!
INCLUDE 'ESCOMN.f90'
!
!
INCLUDE 'PLOT.f90'
!
!OMMONS
!----------
LOGICAL DEBUG
INTEGER I,IHTSER,N,ITIME,ID
REAL    AGE,EMSQR,DILATE,DELAY,ELEVDUM,GENTIM,HHT,TRAGE
REAL    DGS,HG,DD
REAL RDANUW
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
RDANUW = ELEVDUM
!----------
!  CHECK FOR DEBUG
!----------
CALL DBCHK (DEBUG,'ESSUBH',6,ICYC)
IF(DEBUG) &
   WRITE(JOSTND,*)'ENTERING ESSUBH - ICYC,TRAGE= ',ICYC,TRAGE
IF(DEBUG)WRITE(JOSTND,*)' I,HHT,EMSQR,DILATE,DELAY,ELEV,IHTSER,', &
   'GENTIM,TRAGE= ',I,HHT,EMSQR,DILATE,DELAY,ELEV,IHTSER,GENTIM,TRAGE
!
N=INT(DELAY + 0.5)
IF(N.LT.-3) N=-3
DELAY=REAL(N)
ITIME=INT(TIME + 0.5)
IF(N.GT.ITIME) DELAY=TIME
AGE=TIME-DELAY-GENTIM+TRAGE
IF(AGE.LT.1.0) AGE=1.0
TRAGE=TIME-DELAY
!----------
!  CALL SMHGDG TO CALCULATE SEEDLING HEIGHT 5 YEARS AFTER PLANTING
!  OR END OF CYCLE, WHICHEVER COMES FIRST
!  ASSUME INITIAL CONDITIONS (MODE=0) AT TIME OF PLANTING
!----------
!
!  CALL SMHGDG TO GET 5 YEAR GROWTH, AT SPECIES LEVEL, ID=0
!  ASSUME INITIAL SEEDLING HEIGHT = 1.0 FT
!  REDWOOD DOES NOT USE PREDICTION FROM SMHGDG ROUTINE. REDWOOD
!  GETS A VALUE OF 2.0 ASSIGNED TO HHT AS IS DONE IN CA VARIANT.
!
ID=0
HHT=1.0
DD=.1

!  DETERMINE HHT CALCULATION BASED ON SPECIES
IF(I .EQ. 17) THEN
  HHT = 2.0
  IF(DEBUG)WRITE(JOSTND,*)'LEAVING ESSUBH RW DEBUG', ' ISPC=',I, &
    ' HHT=',HHT
ELSE
  CALL SMHGDG(ID,I,HHT,DD,HG,DGS,ICYC,JOSTND,DEBUG,0)
  HHT=HHT+HG
!
!  SCALE FOR DELAY (NUMBER OF YEARS BETWEEN START OF CYCLE AND PLANTING)
!  (0 TO FINT-1) IF DELAY IS MORE THAN 5 YEARS THEN GROWTH IS SCALED
!  IN REGENT

  IF(FINT.LT.5)HHT=HHT*FINT/5.
!
  IF(DEBUG) THEN
  WRITE(JOSTND,*)' LEAVING ESSUBH -ICYC,I,AGE,TRAGE,', &
   'TIME,DELAY,HHT= ',ICYC,I,AGE,TRAGE,TIME,DELAY,HHT
  ENDIF
ENDIF
!
RETURN
END
