SUBROUTINE ESTUMP (JSSP,DBH,PREM,JPLOT,ISHAG)
IMPLICIT NONE
!----------
! WC $Id$
!----------
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ESPARM.f90'
!
!
INCLUDE 'ESHOOT.f90'
!
!
INCLUDE 'ESHAP.f90'
!
!
INCLUDE 'ESCOMN.f90'
!
!
!OMMONS
!
!     STORE INFORMATION FOR STUMP SPROUT SUBROUTINE.
!
INTEGER JPLOT,JSSP,I,ISSP,IDBH
REAL PREM,DBH,DBHEND
INTEGER*4 MDBH,IPLT,MSP
INTEGER ISHAG
DATA MDBH/10000000/,MSP/10000/
DO 10 I=1,NSPSPE
IF(JSSP.EQ.ISPSPE(I)) GO TO 11
10 CONTINUE
GO TO 900
11 CONTINUE
ISSP=I
!
!     DETERMINE DIAMETER CLASS OF THE TREE BEING CUT.
!
DO 100 I=1,NDBHCL-1
DBHEND=(DBHMID(I)+DBHMID(I+1))/2.0
IF(DBH.GT.DBHEND) GO TO 100
IDBH=I
GO TO 110
100 CONTINUE
IDBH=NDBHCL
110 CONTINUE
IPLT=JPLOT
IF(IPLT.GT.9999) IPLT=9999
ITRNRM=ITRNRM+1
!----------
! ISHOOT() IS A NUMBER COMPOSED OF DDDSSSPPPP, WHERE DDD = DBH CLASS,
! SSS = SPECIES, AND PPPP = PLOT.  DECODED IN **ESUCKR**.
! PRBREM() CONTAINS AMOUNT OF PROB REMOVED IN CUTTING TREE RECORD.
!----------
DSTUMP(ITRNRM) = DBH
ISHOOT(ITRNRM) = IDBH*MDBH + ISSP*MSP + IPLT
PRBREM(ITRNRM) = PREM
JSHAGE(ITRNRM) = ISHAG
IF(JSSP.EQ.26)THEN
  ASTPAR = ASTPAR + PREM
  ASBAR = ASBAR + 0.0054542*PREM*DBH**2.
ENDIF
900 CONTINUE
RETURN
END
