SUBROUTINE FORKOD
IMPLICIT NONE
!----------
! WC $Id$
!----------
!
!     TRANSLATES FOREST CODE INTO A SUBSCRIPT, IFOR, AND IF
!     KODFOR IS ZERO, THE ROUTINE RETURNS THE DEFAULT CODE.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
!OMMONS
!
!  ------------------------
!  NATIONAL FORESTS:
!  603 = GIFFORD PINCHOT
!  605 = MT BAKER - SNOQUALMIE
!  606 = MT HOOD
!  610 = ROGUE RIVER
!  615 = UMPQUA
!  618 = WILLAMETTE
!  708 = BLM SALEM ADU
!  709 = BLM EUGENE ADU
!  710 = BLM ROSEBURG ADU
!  711 = BLM MEDFORD ADU
!  613 = MT BAKER-SNOQUALMIE (MAP TO MT BAKER-SNOQUALMIE)
!  ------------------------
!  RESERVATION PSUEDO CODES:
!  8124 = SAUK-SUIATTLE RESERVATION (MAPPED TO 605 MT. BAKER)
!  8130 = YAKAMA NATION RESERVATION (MAPPED TO 603 GIFFORD PINCHOT)
!  ------------------------

INTEGER JFOR(11),KFOR(11),NUMFOR,I
LOGICAL USEIGL, FORFOUND
DATA JFOR/603,605,606,610,615,618,708,709,710,711,613/, NUMFOR/11/
DATA KFOR/ 11*1 /

USEIGL = .TRUE.
FORFOUND = .FALSE.


SELECT CASE (KODFOR)

!       CROSSWALK FOR RESERVATION PSUEDO CODES & LOCATION CODE
  CASE (8124)
    WRITE(JOSTND,62)
62     FORMAT(/,'********   ',T12,'SAUK-SUIATTLE RESERVATION (8124)', &
       ' BEING MAPPED TO MT. BAKER NF (605) FOR FURTHER PROCESSING.')
    IFOR = 2
  CASE (8130)
    WRITE(JOSTND,63)
63     FORMAT(/,'********   ',T12,'YAKAMA NATION RESERVATION (8130)', &
       ' BEING MAPPED TO GIFFORD PINCHOT NF (603) FOR FURTHER', &
       ' PROCESSING.')
    IFOR = 1
!       END CROSSWALK FOR RESERVATION PSUEDO CODES & LOCATION CODE



  CASE DEFAULT

!         CONFIRMS THAT KODFOR IS AN ACCEPTED FVS LOCATION CODE
!         FOR THIS VARIANT FOUND IN DATA ARRAY JFOR
    DO 10 I=1,NUMFOR
      IF (KODFOR .EQ. JFOR(I)) THEN
        IFOR = I
        FORFOUND = .TRUE.
        EXIT
      ENDIF
10     CONTINUE

!         LOCATION CODE ERROR TRAP
    IF (.NOT. FORFOUND) THEN
      CALL ERRGRO (.TRUE.,3)
      WRITE(JOSTND,11) JFOR(IFOR)
11       FORMAT(/,'********',T12,'FOREST CODE USED IN THIS ', &
         'PROJECTION IS',I4)
      USEIGL = .FALSE.
    ENDIF

END SELECT


!     FOREST MAPPING CORRECTION
SELECT CASE (IFOR)
  CASE (11)
    WRITE(JOSTND,21)
21     FORMAT(/,'********',T12,'MT BAKER-SNOQUALMIE NF (613) BEING ', &
       'MAPPED TO MT BAKER-SNOQUALMIE (605) FOR FURTHER PROCESSING.')
    IFOR = 2
END SELECT

!     SET THE IGL VARIABLE ONLY IF DEFAULT FOREST IS USED
!     GEOGRAPHIC LOCATION CODE: 1=NORTH, 2=CENTRAL, 3=SOUTH
!     USED TO SET SOME EQUATIONS IN REGENERATION AND PERHAPS
!     HEIGHT-DIAMETER IN DIFFERENT VARIANTS.
IF (USEIGL) IGL = KFOR(IFOR)

KODFOR=JFOR(IFOR)
RETURN
END
