SUBROUTINE KSSTAG (IPRINT,KEYWRD,LNOTBK,ARRAY,LKECHO)
IMPLICIT NONE
!----------
! METRIC-BASE $Id$
!----------
!
!   THIS SUBROUTINE PROCESSES THE KEYWORD FOR THE STAND STRUCTURAL
!   CLASSES CALCULATIONS.  SEE SUBROUTINE SSTAGE.
!
!   N.L.CROOKSTON - INT MOSCOW - JUNE 1996 AND WITH
!   A.R.STAGE - INT MOSCOW - JUNE 1997
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'SSTGMC.f90'
!
!
INCLUDE 'METRIC.f90'
!OMMONS
!

CHARACTER*8  KEYWRD
REAL         ARRAY(7)
INTEGER      IPRINT
LOGICAL      LNOTBK(7),LKECHO

!     TURN ON THE CALCULATIONS.

LCALC = .TRUE.

!     PROCESS THE KEYWORD FOR THE STRUCTURAL STAGE ROUTINE.

!     IF THE FIRST FIELD CONTAINS A CHARACTER, THEN WE ARE PRINTING.

IF (LNOTBK(1)) THEN
   IF (ARRAY(1).EQ.0) THEN
      LPRNT = .FALSE.
   ELSE
      LPRNT = .TRUE.
   ENDIF
ENDIF
IF (LPRNT) THEN
   ARRAY(1)=1.
ELSE
   ARRAY(1)=0.
ENDIF

!     THE PERCENTAGE OF A TREE HEIGHT THAT A GAP MUST EXCEED.

IF (LNOTBK(2)) GAPPCT=ARRAY(2)

!     THE DBH BREAK BETWEEN SEEDLING/SAPLINGS AND POLE-SIZED TREES

IF (LNOTBK(3)) SSDBH=ARRAY(3) * CMtoIN

!     THE DBH BREAK BETWEEN POLES-SIZED TREES AND LARGE (OLDER)

IF (LNOTBK(4)) SAWDBH=ARRAY(4) * CMtoIN

!     THE MINIMUM COVER PERCENT TO QUALIFY A POTENTIAL STRATUM.

IF (LNOTBK(5)) CCMIN=ARRAY(5)

!     THE MINIMUM TREES/HA THAT MUST BE EXCEEDED FOR A STAND
!     THAT HAS LESS THAN 5% COVER TO BE CLASSIFIED STAND INIT.

IF (LNOTBK(6)) TPAMIN=ARRAY(6) / HAtoACR

!     THE PERCENTAGE OF THE MAXIMUM STAND DENSITY INDEX THAT MUST
!     BE EXCEEDED FOR A STAND TO BE CLASSIFIED STEM EXCLUSION
!     RATHER THAN STAND INITIATION

IF (LNOTBK(7)) PCTSMX=ARRAY(7)

IF(LKECHO)WRITE (IPRINT,200) KEYWRD,ARRAY(1),GAPPCT, &
     SSDBH*INtoCM,SAWDBH*INtoCM,CCMIN, &
     TPAMIN / ACRtoHA,PCTSMX
200 FORMAT (/A8,'   STAND STRUCTURAL CLASSES WILL BE ', &
     'COMPUTED.'/T12, &
     'OUTPUT PRINTING CODE = ',F3.0,' (0=NO OUTPUT, 1=PRINT)'/T12, &
     'THE PERCENTAGE OF A TREE HEIGHT THAT A GAP MUST EXCEED =', &
      T76,F6.1/T12, &
     'THE DBH BREAK BETWEEN SEEDLING/SAPLINGS AND ', &
     'POLE-SIZED TREES =',T76,F6.1/T12, &
     'THE DBH BREAK BETWEEN POLE-SIZED AND LARGE, OLDER, TREES =', &
      T76,F6.1/T12, &
     'THE MINIMUM COVER PERCENT TO QUALIFY A POTENTIAL STRATUM =', &
      T76,F6.1/T12, &
     'THE MINIMUM TREE/HA TO BE CLASSIFIED STAND INITIATION =', &
      T76,F6.1/T12, &
     'THE MINIMUM PERCENT OF MAXSDI TO BE CLASSIFIED ', &
     'STEM EXCLUSION =',T76,F6.1)
RETURN
END
