SUBROUTINE OPFIND (NMYA,MYACTS,NTODO)
IMPLICIT NONE
!----------
! METRIC-BASE $Id$
!----------
!
!     OPTION PROCESSING ROUTINE - NL CROOKSTON - JAN 1981 - MOSCOW
!
!     OPFIND FINDS THE NUMBER OF (NTODO) ACTIVITIES THAT THE CALLING
!     ROUTINE IS CAPABLE OF DOING IN THE LIST OF ACTIVITIES THAT ARE
!     TO BE DONE DURING THE CURRENT CYCLE.
!
!     NMYA  = THE NUMBER OF ACTIVITIES THE CALLING ROUTINE IS CAPABLE
!             OF ACCOMPLISHING (DIMENSION OF MYACTS).
!     MYACTS= THE LIST OF ACTIVITIES IN ASCENDING ORDER.
!     NTODO = THE NUMBER OF ACTIVITIES WHICH ARE TO BE DONE THIS
!             CYCLE.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'OPCOM.f90'
!
!
INCLUDE 'METRIC.f90'
!
!
!OMMONS
!
REAL PRMS(*)
INTEGER MYACTS(*)
INTEGER NTODO,NMYA,NPRMS,IACTK,IDT,MXPM,ITODO1,IREFN,IRC,J1,J2,J
INTEGER ITODO5,ILEN,I,NPRMS1,ITODO2,IDT4,ITODO3,ITODO4,ISQNUM
INTEGER IYR2,IYR1,I2,II,I3,IDT3
CHARACTER*(*) STR

INTEGER IX
!
!     ARRAY OF CONVERSION FACTORS TO GIVE PRMS ARRAY IN THE
!     USER'S CHOICE OF UNITS: VECTOR OF 1'S BY DEFAULT
!
REAL XMLT(N_METRIC_PRMS)
!
!     FIND THE ACTIVITIES.  STORE A LIST OF POINTERS TO THE
!     ACTIVITIES IN THE ARRAY IPTODO.
!
CALL OPMERG (NMYA,MYACTS,NTODO)
KTODO=NTODO
RETURN
!
!
ENTRY OPGET (ITODO1,MXPM,IDT,IACTK,NPRMS,PRMS)
!
!     OPGET GETS THE "ITH" ACTIVITY OF THE NUMBER OF ACTIVITIES
!     TO DO (NTODO) WHICH ARE FOUND BY CALLING OPFIND.
!
!     ITODO1= WHICH OF THE NUMBER TO DO THE USER WANTS RETURNED.
!             FOR EXAMPLE: IF NTODO=6 AND THE ROUTINE CALLING OPGET
!             WANTS THE 5TH OF THE 6 ACTIVITIES, THEN I IS SET EQUAL
!             TO 5.
!     MXPM  = THE DIMENSION OF PRMS; THE MAXIMUM NUMBER OF PARMS
!             WHICH CAN BE RETURNED TO THE CALLING ROUTINE.
!     IDT   = THE DATE THE OPTION IS SCHEDULED TO OCCUR.
!     IACTK = RETURN THE ACTUAL ACTIVITY KODE; OR:
!             -1 IF I IS GREATER THAN THE NUMBER TO DO, OR
!             -ACTUAL ACTIVITY CODE IF THE ACTIVITIY WAS FLAGED AS
!             DELETED OR ACCOMPLISHED BETWEEN THIS CALL TO OPGET AND THE
!             LAST CALL TO OPFIND.  ACTIVITIES DELETED AT OTHER TIMES
!             WILL NOT BE "FOUND" BY OPFIND.
!     NPRMS = THE ACTUAL NUMBER OF PARAMETERS RETURNED; OR:
!             -NPRMS IF THE NUMBER OF PARAMETERS PRESENT FOR THE
!             OPTION IS GREATER THAN THE VALUE OF 'MXPM''.
!             IABS(NPRMS) IS EQUAL TO THE NUMBER OF PARMS PRESENT.
!     PRMS  = THE PARAMETERS ARRAY.
!

!     SET THE DEFAULT VALUE FOR THE IMPERIAL->METRIC CONVERSIONS

DO I=1,N_METRIC_PRMS
  XMLT(I) = 1.
ENDDO
!
!     SET THE ACTIVITY CODE
!
IF (ITODO1 .LE. KTODO) GOTO 10
IACTK=-1
RETURN
10 CONTINUE
IREFN=IPTODO(ITODO1)
NPRMS=0
IACTK=-1
!
!     IF THE PARAMETER POINTER IS LESS THAN ZERO, THE PARMS ARE AN
!     EXPRESSION.  CALL OPEVAL TO EVALUATE THE EXPRESSION AND LOAD
!     THE PARAMETER ARRAYS.
!     CALL MCNVRT TO CONVERT EXPRESSIONS WITH
!     METRIC UNITS INTO IMPERIAL EQUIVALENTS.
!
IF (IACT(IREFN,2).LT.0) THEN
  CALL OPEVAL (IREFN,IRC)
  IF (IRC.NE.0) RETURN
  CALL MCNVRT (IACT(IREFN,1),1,PRMS,XMLT)
ENDIF

IF (IACT(IREFN,4).EQ.0) IACTK=1
IACTK=IACT(IREFN,1)*IACTK
IDT=IDATE(IREFN)
!
!     SET NUMBER OF PARAMETERS
!
J1=IACT(IREFN,2)
IF (J1.EQ.0) RETURN
J2=IACT(IREFN,3)
NPRMS=J2-J1+1
IF (NPRMS .LE. MXPM) GOTO 20
J2=J2-(NPRMS-MXPM)
NPRMS=-NPRMS
20 CONTINUE
!
!     MOVE THE PARAMETERS.
!
DO 30 J=J1,J2
  IX = J-J1+1
  IF (IX .GT. 0 .AND. IX .LE. N_METRIC_PRMS) &
       PARMS(J)=PARMS(J)*XMLT(IX)
  PRMS(IX)=PARMS(J)
30 CONTINUE
RETURN
!
!
ENTRY OPGETC (ITODO5,STR)
!
!     OPGETC GETS CHARACTER STRING ASSOCIATED WITH THE "ITODO5" ACTIVITY
!
!     ITODO5= WHICH OF THE NUMBER TO DO THE USER WANTS RETURNED.
!     STR   = THE CHARACTER STRING, BLANK IF NONE...OR BLANK IF
!             THE COMMAND IS TOO LONG FOR STR.
!
STR=' '
ILEN=LEN(STR)
IF (ITODO5 .GT. KTODO) RETURN
IREFN=IPTODO(ITODO5)
IF (IACT(IREFN,5).EQ.0) RETURN
J=1
DO I=IACT(IREFN,5),MXCACT
   IF(J.GT.ILEN) THEN
      STR=' '
      RETURN
   ENDIF
   IF(CACT(I).EQ.CHAR(0)) RETURN
   STR(J:J)=CACT(I)
   J=J+1
ENDDO
RETURN
!
!
ENTRY OPCHPR (ITODO2,NPRMS1,PRMS)
!
!     OPCHPR IS USED TO CHANGE THE VALUE OF A STORED PARAMETER OF
!     FOR AN ACTIVITY.  YOU CAN NOT CHANGE THE PARAMETER VALUES OF
!     ACTIVITIES WHICH HAVE COMPUTABLE PARAMETERS THAT HAVE NOT BEEN
!     COMPUTED.
!
!     ITODO2 = THE "ITH" ACTIVITY OF THE "NTODO".
!     NPRMS1  = THE NUMBER OF PARAMETERS IN PRMS.
!     PRMS   = THE NEW PARAMETERS.
!
IF (ITODO2.LE.KTODO) THEN
   IREFN=IPTODO(ITODO2)
!
!        IF THERE IS ENOUGH ROOM IN PARMS, AND IF THE ACTIVITY GROUP
!        DOES NOT HAVE UNCOMPUTED, COMPUTABLE PARAMETERS, THEN
!        STORE THE NEW PARAMETERS. DON'T WRITE OVER THE OLD PARAMETERS.
!
   IF (IMPL+NPRMS1-1.LE.ITOPRM .AND. IACT(IREFN,2).GE.0) THEN
      IACT(IREFN,2)=IMPL
      DO 35 J=1,NPRMS1
      PARMS(IMPL)=PRMS(J)
      IMPL=IMPL+1
35       CONTINUE
      IACT(IREFN,3)=IMPL-1
   ENDIF
ENDIF
RETURN
!
!
ENTRY OPDONE (ITODO3,IDT4)
!
!     OPDONE IS USED TO SET THE DATE AN OPTION IS ACTUALLY
!     ACCOMPLISHED; THEREFORE MAINTAINING AN ACCURATE HISTORY OF
!     ACTIVITIES.  IT CAN ALSO BE USED TO SET THE STATUS OF THE
!     ACTIVITY TO ANY VALUE PASSED AS 'IDT4', EXCEPT 0.
!
!     ITODO3= THE "ITH" ACTIVITY OF THE "NTODO".
!     IDT4  = THE YEAR THE ACTIVITY IS ACTUALLY IMPLEMENTED.
!
IF (ITODO3 .GT. KTODO) RETURN
IREFN=IPTODO(ITODO3)
ISEQDN=ISEQDN+1
ISEQ(IREFN)=ISEQDN
IACT(IREFN,4)=IDT4
IF (IDT4.EQ.0) IACT(IREFN,4)=1
RETURN
!
!
ENTRY OPDEL1 (ITODO4)
!
!     OPDEL1 IS USED TO DELETE THE ITH ACTIVITY OF THE NTODO.
!
IF (ITODO4 .GT. KTODO) RETURN
IREFN=IPTODO(ITODO4)
IACT(IREFN,4)=-1
RETURN
!
!
ENTRY OPDEL2 (IYR1,IYR2,IACTK,ISQNUM)
!
!     OPDEL2 IS USED TO DELETE ALL OF THE OCCURACES OF ACTIVITY
!     IACTK FROM THE ACTIVITY SCHEDULE IF IT MEETS THE FOLLOWING
!     SEARCH RESTRICTIONS:
!
!             A.  NOT YET ACCOMPLISHED
!             B.  IS SCHEDULED TO OCCUR ON OR AFTER IYR1 AND
!                 ON OR BEFORE IYR2,
!             C.  MEETS 'ISQNUM' RESTRICTIONS:
!                 ISQNUM=0, DELETE ALL OCCURANCES
!                 ISQNUM>0, DELETE OCCURANCE ISQNUM
!                 ISQNUM<0, DELETE ALL EXCEPT IABS(ISQNUM) TIMES
!                           THE ACTIVITY IS SCHEDULED.
!
!     J1=COUNTER, STORES THE NUMBER OF OCCURANCES FOUND.
!
J1=0
I2=IMGL-1
DO 50 II=1,I2
I3=IOPSRT(II)
IDT3=IDATE(I3)
IF (.NOT.(IDT3.GE.IYR1.AND.IDT3.LE.IYR2.AND.IACT(I3,4).EQ.0 &
       .AND.IACT(I3,1).EQ.IACTK)) GOTO 50
IF (ISQNUM.EQ.0) GOTO 40
J1=J1+1
IF (J1.NE.ISQNUM) GOTO 50
40 CONTINUE
IACT(I3,4)= -1
IF (ISQNUM .GT. 0) RETURN
50 CONTINUE
IF (ISQNUM .GE. 0) RETURN
IF (-ISQNUM .GE. J1) RETURN
!
!     NOTE: ISQNUM < 0, AND THERE ARE MORE OCCURANCES THAN -ISQNUM;
!     THEREFORE, WE MUST DELETE ALL EXCEPT -ISQNUM TIMES THE ACTIVITY
!     OCCURES BETWEEN IYR1 AND IYR2.
!
!     J2 IS USED TO COUNT THE NUMBER OF DELETIONS, AND
!     J1 IS HOLDS THE NUMBER OF DELETIONS WHICH MUST BE ACCOMPLISHED.
!
J2=0
J1=J1+ISQNUM
DO 60 II=1,I2
I3=IOPSRT(II)
IDT3=IDATE(I3)
IF (.NOT.(IDT3.GE.IYR1.AND.IDT3.LE.IYR2.AND.IACT(I3,4).EQ.0 &
       .AND.IACT(I3,1).EQ.IACTK)) GOTO 60
IACT (I3,4)= -1
J2=J2+1
IF (J2 .GE. J1) RETURN
60 CONTINUE
RETURN
!
!
ENTRY OPDEL3 (IACTK)
!
!     OPDEL3 IS USED TO DELETE AN ACTIVITY IF IT OCCURS AS ONE
!     OF THE ACTIVITIES TO BE SCHEDULED WHEN ANY EVENT OCCURS.
!
I2=IEPT+1
IF (I2.GT.MAXACT) RETURN
DO 80 I=I2,MAXACT
IF (IACT(I,1).EQ.IACTK) IACT(I,4)= -1
80 CONTINUE
RETURN
END
