!ODE SEGMENT DFBCOM
!----------
! DFB-COMMON $Id$
!----------

LOGICAL DEBUIN, WORKIN(MAXCYC), LEPI, LDFBON, LINV, LINPRG, &
           LBAMOD, LXNOTE

INTEGER ILENTH, IDBSCH, IDFBYR(MAXCY1), ISMETH, IWAIT, &
           IPAST, IYOUT, IPT(MAXTRE), JODFB, JODFBX, IDFSPC, &
           IFVSSP(MAXSP), NDAMS

REAL    DEADDF(20), START(20), A45DBH, EXSTDV, EPIPRB, &
           PRBDFB(MAXCYC)
REAL    PBADF4, DBEVNT, BADF9, BA9, OKILL, PRPWIN, MINDEN
REAL    PREKLL, MWINHT, WINSUC(39), PRPMRT(MAXSP)
REAL    ROWDOM(MAXSP)
REAL    EXPCTD, LIVEDF(20), DFKILL, PERDD(4), ORSEED, SS

COMMON /DFBCOM/ DEADDF, START, ILENTH, A45DBH, EXSTDV, EPIPRB, &
           PRBDFB, DEBUIN, WORKIN, LEPI, LDFBON, PBADF4, JODFB, &
           IDBSCH, IDFBYR, ISMETH, IWAIT, DBEVNT, IPAST, BADF9, &
           BA9, OKILL, PRPWIN, MINDEN, IYOUT, PREKLL, MWINHT, &
           WINSUC, IPT, PRPMRT, LINV, NDAMS, ROWDOM, EXPCTD, LIVEDF, &
           DFKILL, LINPRG, PERDD, JODFBX, LBAMOD, ORSEED, IDFSPC, &
           IFVSSP, LXNOTE


DOUBLE PRECISION S0, S1

COMMON /DFRCOM/ S0, S1, SS

!
!     A45DBH -- THE AVERAGE DIAMETER OF ALL DOUGLAS-FIR TREES THAT
!               HAVE A DBH >= 4.5 INCHES.
!     BA9    -- THE STAND BASAL AREA FOR ALL TREES >= 9.0 INCH DBH.
!     BADF9  -- THE BASAL AREA THAT IS IN DOUGLAS-FIR TREES >= 9.0
!               INCHES.
!     DBEVNT -- THE ANNUAL PROBABILITY OF A DOUGLAS-FIR BEETLE
!               REGIONAL OUTBREAK OCCURING.
!     DEADDF -- ARRAY THAT HOLDS THE NUMBER OF DOUGLAS-FIR TREES KILLED
!               FOR EACH DIAMETER CLASS.
!     DEBUIN -- FLAG SET TO .TRUE. IF THE DEBUG KEYWORD WAS USED.
!     DFKILL -- THE PROJECTED DOUGLAS-FIR TREES/ACRE THAT WILL BE KILLED
!               BY THE CURRENT BEETLE OUTBREAK.
!     EPIPRB -- A USER SPECIFIED OUTBREAK PROBABILITY USED WITH
!               RANSTART.  SET BY THE KEYWORD STOPROB.
!     EXPCTD -- THE NUMBER OF DF TREES EXPECTED TO DIE IN EACH YEAR
!               OF A DFB OUTBREAK.
!     EXSTDV -- THE STANDARD DEVIATION USED WITH EXPCTD TO DRAW A
!               RANDOM NUMBER FROM A NORMAL DISTRIBUTION.  THE RANDOM
!               NUMBER DRAWN IS USED IN THE CALCULATON OF HOW MANY
!               TREES/ACRE THAT WILL BE KILLED BY THE DFB.
!     IDBSCH -- HOLDS THE TYPE OF SCHEDULING USED.  1 = MANUAL
!               SCHEDULEING OF REGIONAL OUTBREAKS.  2 = RANDOM
!               SCHEDULEING OF REGIONAL OUTBREAKS.
!     IDFBYR -- ARRAY THAT HOLDS THE YEARS THAT REGIONAL OUTBREAKS
!               OCCUR.  IDFBYR(41) HOLDS THE NUMBER OF REGIONAL
!               OUTBREAKS.
!     IDFSPC -- THE FVS SPECIES NUMBER FOR DF (DOUGLAS-FIR).
!               SET IN BLOCK DATA DFBLKD.
!     IFVSSP -- AN INDEX ARRAY USED TO INDEX THE SPECIES SPECIFIC
!               VALUES IN THE WINSUC ARRAY.  THE VALUES IN IFVSSP ARE
!               VARIANT SPECIFIC.  THIS ARRAY IS USED TO MATCH UP THE
!               FVS SPECIES WITH THE SPECIES FOR THE WINSUC ARRAY.
!     ILENTH -- THE LENGTH OF THE DOUGLAS-FIR BEETLE OUTBREAK.  SET
!               BY THE KEYWORD OLENGTH. (DEFAULT IS 4 YEARS).
!     IPAST  -- YEAR OF LAST RECORDED DOUGLAS-FIR BEETLE OUTBREAK.
!     IPT    -- INDEX ARRAY THAT HOLDS POINTERS TO THE TREE RECORDS THAT
!               HAVE DFB DAMAGE CODES.
!     ISMETH -- HOLDS THE STARTING METHOD USED.  1 = MANUAL START
!               (MANSTART).  2 = RANDOM START (RANSTART).
!     IWAIT  -- MINIMUM WAITING PERIOD BETWEEN REGIONAL OUTBREAKS.
!     IYOUT  -- HOLDS THE NUMBER OF YEARS THAT AN OUTBREAK HAS BEEN IN
!               PROGRESS.  USER ENTERS IT WITH KEYWORD CUROUTBK.
!     JODFB  -- THE UNIT NUMBER FOR THE DOUGLAS-FIR BEETLE OUTPUT
!               FILE.
!     JODFBX -- FLAG THAT IS SET TO 0 UNLESS THE USER WANTS THE SUMMARY
!               OUTPUT PRINTED IN A SEPERATE FILE FOR POST PROCESSING
!               AND THEN IT HOLDS THE UNIT NUMBER FOR THE OUTPUT FILE.
!     LBAMOD -- FLAG THAT IS SET TO .TRUE. WHEN THE DFB MORTALITY IS
!               CALCULATED USING THE BASAL AREA METHOD.  THE DEFAULT
!               IS .FALSE. (THE DBH METHOD IS USED FOR MORTALITY).
!     LDFBON -- LOGICAL VARIABLE SET TO .TRUE. WHEN THE DOUGLAS-FIR
!               BEETLE MODEL HAS BEEN INITIALIZED AND IS IN USE.
!     LEPI   -- LOGICAL VARIABLE SET TO .TRUE. WHEN THE USER SPECIFIES
!               THE OUTBREAK PROBABILITY WITH THE KEYWORD STOPROB.
!     LINPRG -- LOGICAL VARIABLE SET TO .TRUE. IF THE KEYWORD CUROUTBK
!               IS BEING USED (OUTBREAK IN PROGRESS AT THE START OF THE
!               SIMULATION).
!     LINV   -- LOGICAL VARIABLE SET TO .TRUE. WHEN THE MORTALITY DATA
!               FOR AN OUTBREAK IN PROGRESS IS TO BE TAKEN FROM THE TREE
!               LIST.
!     LIVEDF -- ARRAY THAT HOLDS THE TREES/ACRE OF LIVE DOUGLAS-FIR FOR
!               EACH DBH CLASS.
!     MINDEN -- THE MINIMUM NUMBER OF TREES/ACRE THAT IS NECESSARY FOR
!               A WINDTHROW TO OCCUR.
!     MWINHT -- THE MINIMUM HEIGHT A TREE MUST BE BEFORE IT CAN BE
!               ELIGIBLE FOR WINDTHROW.
!     NDAMS  -- HOLDS THE NUMBER OF TREE RECORDS THAT ARE READ IN WITH
!               DFB DAMAGE CODES.
!     OKILL  -- USED TO ADD OTHER MORTALITY TO THE DFB MODEL (EXTRA
!               MORTALITY FROM WINDTHROW).
!     ORSEED -- THE ORIGINAL RANDOM NUMBER SEED.  INITIALIZED IN DFBINT
!               AND ALSO IN DFBRAN.
!     PBADF4 -- THE PROPORTION OF STAND BASAL AREA IN DOUGLAS-FIR TREES
!               WITH DBH >= 4.5 INCHES.
!     PERDD  -- ARRAY THAT HOLDS THE PERCENTAGE OF TREES THAT WILL HAVE
!               DIED BY THE END OF EACH YEAR OF A 4 YEAR DFB OUTBREAK.
!               USED TO CALCULATE THE NUMBER OF TREES THAT ARE LEFT TO
!               KILL IN AN OUTBREAK IN PROGRESS.
!     PRBDFB -- ARRAY THAT HOLDS THE PROBABILITY OF A DOUGLAS-FIR
!               BEETLE OUTBREAK OCCURING FOR EACH CYCLE.
!     PREKLL -- THE TOTAL TREES/ACRE THAT WERE KILLED BY THE DFB BEFORE
!               THE MODEL IS STARTED.  ENTERED BY THE USER IN KEYWORD
!               CUROUTBK OR IT IS READ FROM THE TREELIST.
!     PRPMRT -- ARRAY THAT HOLDS THE PROPORTION OF TREES/ACRE TO
!               WINDTHROW IN A TREE RECORD FOR EACH SPECIES.
!     PRPWIN -- THE PROPORTION OF ELIGIBLE TREES TO WINDTHROW.  USER
!               ENTERS THE VALUE THROUGH THE WINDTHR KEYWORD.
!     ROWDOM -- ARRAY THAT HOLDS THE PERCENTILE AT WHICH TREES
!               CAN BE WINDTHROWN FOR EACH SPECIES.
!     START  -- ARRAY THAT HOLDS THE NUMBER OF DOUGLAS-FIR TREES IN EACH
!               DIAMETER CLASS AT THE BEGINNING OF AN OUTBREAK.
!     WINSUC -- ARRAY THAT HOLDS THE SPECIES SPECIFIC VALUES FOR THE
!               RELATIVE SUSCEPTIBILITY OF TREE SPECIES TO WINDTHROW.
!     WORKIN -- LOGICAL ARRAY THAT IS SET TO .TRUE. FOR EVERY
!               CYCLE THAT AN OUTBREAK OCCURS.
!
!C-----END SEGMENT
