SUBROUTINE ORIN (DEBUG,LKECHO,LNOTRE)
IMPLICIT NONE
!----------
! VORGANON $Id$
!----------
!
!     ORGANON EXTENSION KEYWORD PROCESSOR.
!----------
!OMMONS
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'VOLSTD.f90'
!
!
INCLUDE 'ORGANON.f90'
!
!OMMONS
!----------
! VARIABLE DECLARATIONS:
!----------
INTEGER    KWCNT
PARAMETER (KWCNT = 7)
!
LOGICAL      LNOTBK(12)
LOGICAL      LKECHO,LNOTRE
LOGICAL      DEBUG
!
CHARACTER*8  TABLE(KWCNT)
CHARACTER*8  KEYWRD
CHARACTER*10 KARD(12)
CHARACTER    FNAME*80
INTEGER      KODE,IPRMPT,NUMBER
INTEGER      ORGINP
!
REAL         ARRAY(12)
!----------
! INITIALIZATIONS:
!----------
!
DATA TABLE / &
       'END     ', &  ! Option 100
       'ORGINFO ', &  ! Option 200
       'ORGVOLS ', &  ! Option 300
       'INPFILE ', &  ! Option 400
       'OSUCFVOL', &  ! Option 500
       'OSUBFVOL', &  ! Option 600
       'ORGOFF  '/      ! Option 700
!
!----------
!     **********          EXECUTION BEGINS          **********
!----------
!
10 CONTINUE
!----------
! CALL KEYWORD READER
!----------
CALL KEYRDR (IREAD,JOSTND,DEBUG,KEYWRD,LNOTBK, &
                ARRAY,IRECNT,KODE,KARD,LFLAG,LKECHO)
!----------
!  RETURN KODES 0=NO ERROR,1=COLUMN 1 BLANK OR ANOTHER ERROR,2=EOF
!               LESS THAN ZERO...USE OF PARMS STATEMENT IS PRESENT.
!----------

IF (KODE.LT.0) THEN
   IPRMPT=-KODE
ELSE
   IPRMPT=0
ENDIF
IF (KODE .LE. 0) GO TO 30
IF (KODE .EQ. 2) CALL ERRGRO(.FALSE.,2)
CALL ERRGRO (.TRUE.,6)
GOTO 10
!----------
!  CHECK FOR VALID ORGANON KEYWORD
!----------
30 CONTINUE
CALL FNDKEY (NUMBER,KEYWRD,TABLE,KWCNT,KODE,.FALSE.,JOSTND)
!----------
!  RETURN KODES 0=NO ERROR,1=KEYWORD NOT FOUND,2=KEYWORD NOT SPELLED CORRECTLY
!----------
IF (KODE .EQ. 0) GOTO 90
IF (KODE .EQ. 1) THEN
   CALL ERRGRO (.TRUE.,1)
   GOTO 10
ENDIF
GOTO 90
!----------
!     SPECIAL END-OF-FILE TARGET (USED IF YOU READ PARAMETER CARDS)
!----------
CALL ERRGRO (.FALSE.,2)
!----------
!     PROCESS OPTIONS
!----------
90 CONTINUE
GO TO(100, 200, 300, 400, 500, 600, 700), NUMBER
!
!
!  ==========  OPTION NUMBER  1: END       ===========================END
!
100 CONTINUE
IF(LKECHO) THEN
WRITE(JOSTND,105) KEYWRD
105 FORMAT (/A8,'   END OF ORGANON KEYWORDS')
ENDIF
GO TO 2000
!
!
!  ==========  OPTION NUMBER  2: ORGINFO   =======================ORGINFO
!
!  F1 = MODEL TYPE = (1,2,3)
!  F2 = UNEVEN-AGED = 0,  EVEN-AGED = 1
!  F3 = NO MAXSDI_MORTALITY = 0, MAXSDI_MORTALITY = 1
!  F4 = HEIGHT CALIBRATION FLAG (0 = NO, 1 = YES (DEFAULT))
!  F5 = HEIGHT-TO-CROWN BASE CALIBRATION FLAG (0 = NO, 1 = YES (DEFAULT))
!  F6 = DIAMETER GROWTH CALIBRATION FLAG (0 = NO, 1 = YES (DEFAULT))
!
200 CONTINUE
!
!  F1:
!  ASSIGN THE MODEL TYPE. INITIALIZED TO 0 IN **GRINIT**; DEFAULT SET TO
!  1 OR 2 DEPENDING ON VARIANT IN **SITSET** IF IT ISN'T SET HERE
!
IF (LNOTBK(1)) THEN
  IMODTY = IFIX(ARRAY(1))
!
  SELECT CASE (VARACD)
!
    CASE ('OC')
      IF(IMODTY .NE. 1) THEN
        IF(LKECHO ) WRITE(JOSTND,202) KEYWRD
202         FORMAT (/1X,A8,'   INVALID VERSION. USING VERSION 1 = SWO' &
           )
        IMODTY = 1
      ENDIF
!
    CASE DEFAULT
      IF((IMODTY .LT. 2) .OR. (IMODTY .GT. 3)) THEN
        IF(LKECHO ) WRITE(JOSTND,204) KEYWRD
204         FORMAT (/1X,A8,'   INVALID VERSION. USING VERSION 2 = NWO' &
           )
        IMODTY = 2
      ENDIF
!
  END SELECT
ENDIF
!
!  F2:
!  ASSIGN THE UNEVEN-AGE/EVEN-AGED FLAG FROM THE SECOND POSITION
!  DEFAULT IS THAT THE STAND IS EVEN AGED (SET IN **GRINIT**)
!  0=UNEVEN-AGED STAND; 1=EVEN-AGED STAND
!  IF THIS FLAG INDICATES EVEN-AGED BUT STAND AGE DOES NOT GET SET USING
!  THE STDINFO KEYWORD OR FROM THE ORGANON .INP FILE, THEN THIS WILL
!  GET SET TO UNEVEN-AGED IN **SITSET**
!
IF (LNOTBK(2)) THEN
  INDS(4) = IFIX(ARRAY(2))
  IF((INDS(4).LT.0) .OR. (INDS(4).GT.1))THEN
    INDS(4) = 1
    IF(LKECHO ) WRITE(JOSTND,206) KEYWRD
206     FORMAT (/1X,A8,'   INVALID EVEN-AGED/UNEVEN-AGED FLAG.', &
       ' USING 1 = EVEN-AGED')
  ENDIF
ENDIF
!
!  F3:
!  ASSIGN THE ADDITIONAL MORTALITY FLAG
!  0 = NO ADDITIONAL MORTALITY
!  1 = CALCULATE ADDITIONAL MORTALITY USING MAX SDI (DEFAULT SET IN **GRINIT**)
!
IF (LNOTBK(3)) THEN
  INDS(9) = IFIX(ARRAY(3))
  IF((INDS(9).LT.0) .OR. (INDS(9).GT.1))THEN
    INDS(9) = 1
    IF(LKECHO ) WRITE(JOSTND,208) KEYWRD
208     FORMAT (/1X,A8,'   INVALID MORTALITY FLAG. USING 1 = YES')
  ENDIF
ENDIF
!
!  F4:
!  ASSIGN HEIGHT CALIBRATION VALUES. DEFAULT SET TO 1 = YES (CALCULATE
!  AND USE CALIBRATION VALUES) IN **GRINIT**.
!
IF (LNOTBK(4)) THEN
  INDS(1) = IFIX(ARRAY(4))
  IF((INDS(1).LT.0) .OR. (INDS(1).GT.1))THEN
    INDS(1) = 1
    IF(LKECHO) WRITE(JOSTND,210) KEYWRD
210     FORMAT (/1X,A8,'   INVALID HEIGHT CALIBRATION FLAG.', &
       ' USING 1 = YES')
  ENDIF
ENDIF
!
!  F5:
!  ASSIGN HEIGHT-TO-CROWN BASE CALIBRATION VALUES. DEFAULT SET TO 1 = YES
!  (CALCULATEAND USE CALIBRATION VALUES) IN **GRINIT**.
!
IF (LNOTBK(5)) THEN
  INDS(2) = IFIX(ARRAY(5))
  IF((INDS(2).LT.0) .OR. (INDS(2).GT.1))THEN
    INDS(2) = 1
    IF(LKECHO) WRITE(JOSTND,212) KEYWRD
212     FORMAT (/1X,A8,'   INVALID HEIGHT-TO-CROWN BASE CALIBRATION ', &
       ' FLAG. USING 1 = YES')
  ENDIF
ENDIF
!
!  F6:
!  ASSIGN HEIGHT CALIBRATION VALUES. DEFAULT SET TO 1 = YES (CALCULATE
!  AND USE CALIBRATION VALUES) IN **GRINIT**.
!
IF (LNOTBK(6)) THEN
  INDS(3) = IFIX(ARRAY(6))
  IF((INDS(3).LT.0) .OR. (INDS(3).GT.1))THEN
    INDS(3) = 1
    IF(LKECHO) WRITE(JOSTND,214) KEYWRD
214     FORMAT (/1X,A8,'   INVALID DIAMETER GROWTH CALIBRATION FLAG.', &
       ' USING 1 = YES')
  ENDIF
ENDIF
!
! WRITE THE KEYWORD OUTPUT TO THE OUTPUT FILE.
! ORGINFO:
!   ORGANON MODEL TYPE (1=SWO,2=NWO,3=SMC)
!   STAND TYPE (0=UNEVEN-AGED,1=EVEN-AGED)= 0
!   ADDITIONAL MAX-SDI MORTALITY (0=NO,1=YES)
!   HEIGHT CALIBRATION (0=NO,1=YES)
!   HEIGHT-TO-CROWN BASE CALIBRATION (0=NO,1=YES)
!   DIAMETER GROWTH CALIBRATION (0=NO,1=YES)
!
IF (LKECHO) THEN
  WRITE(JOSTND,216) KEYWRD,IMODTY,INDS(4),INDS(9),INDS(1),INDS(2), &
     INDS(3)
216   FORMAT (/A8,'   ORGANON ', &
          'VARIANT (1=SWO,2=NWO,3=SMC) = ',I2, &
          '; EVEN-AGED (0=NO,1=YES) = ',I2, &
          '; MAX-SDI MORTALITY (0=NO,1=YES) = ',I2,';',/,11X, &
          'HEIGHT CALIBRATION (0=NO,1=YES)=',I2, &
          '; HEIGHT-TO-CROWN BASE CALIBRATION (0=NO,1=YES)=',I2, &
          ';',/,11X,'DIAMETER GROWTH CALIBRATION (0=NO,1=YES)=',I2)
END IF
GOTO 10
!
!
!  ==========  OPTION NUMBER  3: ORGVOLS   ======================ORGVOLS
!
!  F1 = VOLUME COMPUTATION METHOD (0 is FVS NVEL EQUATIONS; 1 IS ORGANON OSU
!       VOLUME EQUATIONS) DEFAULT IS 0
!
!  THESE VARIABLES ARE INITIALIZED IN SUBROUTINE **GRINIT**, AND ONLY
!  USED IN THE CALL TO THE ORGANON **VOLCAL** SUBROUTINE WHEN ORGANON
!  VOLUMES ARE BEING COMPUTED.
!
300 CONTINUE
!
!  F1: ORGANON VOLUMES ON/OFF.
!
IF (LNOTBK(1)) THEN
  IF(ARRAY(1) .GE. 1.) THEN
    LORGVOLS = .TRUE.
  ENDIF
ENDIF
!
! WRITE THE KEYWORD OUTPUT TO THE OUTPUT FILE.
!
IF (LKECHO) THEN
  IF(ARRAY(1) .GE. 1.)THEN
    WRITE(JOSTND,310) KEYWRD
310     FORMAT (/A8, &
       '   ORGANON OSU VOLUME EQUATIONS WILL BE USED WHEN COMPUTING', &
       ' VOLUMES.')
  ENDIF
ENDIF
GO TO 10
!
!
!  ==========  OPTION NUMBER  4: INPFILE   ======================INPFILE
!
!  SUPPLEMENTAL RECORD = FILENAME
!
!  USE UNIT NUMBER 80 FOR ORGANON .INP FILE INPUT
!
400 CONTINUE
!
! READ FILE NAME FROM THE SUPPLEMENTAL RECORD
!
READ(IREAD,402)FNAME
402 FORMAT(A80)
!
! OPEN THE FILE
!
ORGINP=80
OPEN(UNIT=ORGINP,FILE=TRIM(FNAME),STATUS='OLD',RECL=101,ERR=420)
IF(LKECHO) THEN
  WRITE(JOSTND,404) KEYWRD,FNAME
404   FORMAT(/A8,'   FILE NAME = ',A80)
ENDIF
!
CALL ORG_INTREE(ORGINP,LKECHO)
!
BAF = -1.0
BRK = 0.0
LNOTRE=.TRUE.
!
!  IF STARTING FROM A PREPPED FILE, TURN THE ORGANON PREPARED FILE
!  SWITCH TO TRUE SO **PREPARE** WON'T GET CALLED FROM **CRATET**
!
LORGPREP=.TRUE.
!
CLOSE(80)
GO TO 10
!
!  FILE DID NOT OPEN
!
420 CONTINUE
IF (LKECHO) THEN
  WRITE(JOSTND,422) KEYWRD,FNAME
422   FORMAT (/1X,A8,'   FILE DID NOT OPEN: FILE NAME = ',A80)
ENDIF
GO TO 10
!
!
!  ==========  OPTION NUMBER  5: OSUCFVOL    ======================OSUCFVOL
!                                              DEFAULT   VARIABLE
!  F1 = SOFTWOODS CF TOP DIB, IN INCHES          0.0     CFTD
!  F2 = SOFTWOODS CF STUMP HEIGHT, IN FEET       0.0     CFSH
!  F3 = HARDWOODS CF TOP DIB, IN INCHES          0.0     CFTDHW
!
!  THESE VARIABLES ARE: IN THE ORGANON.F77 COMMON BLOCK, INITIALIZED IN
!  SUBROUTINE **GRINIT**, AND ONLY USED IN THE CALL TO THE ORGANON **VOLCAL**
!  SUBROUTINE WHEN ORGANON VOLUMES ARE BEING COMPUTED (LORGVOLS=.TRUE.)
!
500 CONTINUE
!
!  F1: SOFTWOODS CF TOP DIB, IN INCHES.
!
IF (LNOTBK(1)) THEN
  CFTD =   ARRAY(1)
  IF(CFTD .LT. 0.0) CFTD=0.0
  IF(CFTD .GT. 6.0) CFTD=6.0
ENDIF
!
!  F2: SOFTWOODS CF STUMP HEIGHT, IN FEET.
!
IF (LNOTBK(2)) THEN
  CFSH =   ARRAY(2)
  IF(CFSH .GE. 4.5) CFSH=4.49
ENDIF
!
!  F3: HARDWOODS CF TOP DIB, IN INCHES.
!
IF (LNOTBK(3)) THEN
  CFTDHW =   ARRAY(3)
ENDIF
!
! WRITE THE KEYWORD OUTPUT TO THE OUTPUT FILE.
!
IF (LKECHO) THEN
  WRITE(JOSTND,511) KEYWRD,CFTD,CFSH,CFTDHW
511   FORMAT (/A8, &
     '   SOFTWOODS TOP DIB IS ',F4.1,' INCHES; ', &
     'SOFTWOODS STUMP HEIGHT IS ',F4.1,' FEET; ', &
     'HARDWOODS TOP DIB IS ',F4.1,' INCHES')
ENDIF
GO TO 10
!
!
!  ==========  OPTION NUMBER  6: OSUBFVOL   ======================OSUBFVOL
!
!                                              DEFAULT   VARIABLE
!  F1 = BF TOP DIB, IN INCHES                    6.0     LOGTD
!  F2 = LOG TRIM ALLOWANCE, IN INCHES            8.0     LOGTA
!  F3 = BF STUMP HT, IN FEET                     0.0     LOGSH
!  F4 = TARGET LOG LENGTH, IN FEET              32.0     LOGLL
!  F5 = MINIMUM LOG LENGTH, IN FEET              8.0     LOGML
!
!  THESE VARIABLES ARE: IN THE ORGANON.F77 COMMON BLOCK, INITIALIZED IN
!  SUBROUTINE **GRINIT**, AND ONLY USED IN THE CALL TO THE ORGANON **VOLCAL**
!  SUBROUTINE WHEN ORGANON VOLUMES ARE BEING COMPUTED (LORGVOLS=.TRUE.)
!
600 CONTINUE
!
!  F1: BF LOG TOP DIAMETER, IN INCHES.
!
IF (LNOTBK(1)) THEN
  LOGTD =   ARRAY(1)
  IF(LOGTD .LT. 2.0) LOGTD=2.0
ENDIF
!
!  F2: BF LOG TRIM, IN INCHES.
!
IF (LNOTBK(2)) THEN
  LOGTA =   ARRAY(2)
ENDIF
!
!  F3: BF STUMP HEIGHT
!
IF (LNOTBK(3)) THEN
  LOGSH =   ARRAY(3)
  IF(LOGSH .GE. 4.5) LOGSH=4.49
ENDIF
!
!  F4: BF TARGET LOG LENGTH, IN FEET.
!
IF (LNOTBK(4)) THEN
  LOGLL =  ARRAY(4)
ENDIF
!
!  F5: MINIMUM LOG LENGTH, IN FEET.
!
IF (LNOTBK(5)) THEN
  LOGML =  ARRAY(5)
ENDIF
!
! WRITE THE KEYWORD OUTPUT TO THE OUTPUT FILE.
!
IF (LKECHO .AND. LORGVOLS ) THEN
  WRITE(JOSTND,611) KEYWRD, LOGTD,LOGTA,LOGSH,LOGLL,LOGML
611   FORMAT (/A8, &
     '   MINIMUM LOG TOP DIAMETER IS ',F4.1,' INCHES; ', &
     'TRIM ALLOWANCE IS ',F4.1,' INCHES; ', &
     'STUMP HEIGHT IS ',F4.1,' FEET; ',/11X, &
     'LOG LENGTH IS ', F4.1, ' FEET; ', &
     'MINIMUM LOG LENGTH IS ',F4.1,' FEET')
ENDIF
GO TO 10
!
!
!  ==========  OPTION NUMBER  8: ORGOFF    =======================ORGOFF
!
700 CONTINUE
LORGANON = .FALSE.
IF(LKECHO) THEN
WRITE(JOSTND,701) KEYWRD
701 FORMAT (/A8, &
   '   ORGANON GROWTH AND MORTALITY EQUATIONS TURNED OFF')
ENDIF
GO TO 10
!
!
2000 CONTINUE
RETURN
END

