SUBROUTINE DUBSCR(D,CR)
IMPLICIT NONE
!----------
! SN $Id$
!----------
!  THIS SUBROUTINE CALCULATES CROWN RATIOS FOR CYCLE 0.0
!  DEAD TREES
!----------
!OMMONS
!
!
!      INCLUDE 'PRGPRM.F77'
!
!
!      INCLUDE 'CONTRL.F77'
!
!
!OMMONS
!      EXTERNAL RANN
!----------
!  EXPECTED CROWN RATIO IS A FUNCTION OF, DBH,
!  AND RETURNS A VALUE BETWEEN 0.30 ZERO AND 0.70
!
REAL CR,D
!----------
IF (D .LE. 24.) THEN
CR= 0.70-0.40/24.*D
ELSE
CR= 0.30
ENDIF
!----------
!  RANDOM COMPONENT NOT CURRENTLY IMPLEMENTED
!
!  A RANDOM ERROR IS ASSIGNED TO THE CROWN RATIO PREDICTION
!  PRIOR TO THE LOGISTIC TRANSFORMATION.  LINEAR REGRESSION
!  WAS USED TO FIT THE MODEL AND THE ELEMENTS OF CRSD ARE THE
!  STANDARD ERRORS FOR THE LINEARIZED MODEL BY SPECIES.
!----------
!      SD=CRSD(ISPC)
!   10 CONTINUE
!      FCR=0.0
!      IF (DGSD.GE.1.0) FCR=BACHLO(0.0,SD,RANN)
!      IF(ABS(FCR).GT.SD) GO TO 10
!      CR=1.0/(1.0 + EXP(CR+FCR))
!
IF(CR.LT.0.05) CR=0.05
IF(CR.GT.0.95) CR=0.95
RETURN
END
