SUBROUTINE VARGET (WK3,IPNT,ILIMIT,REALS,LOGICS,INTS)
IMPLICIT NONE
!----------
! SN $Id$
!----------
!
!     READ THE VARIANT SPECIFIC VARIABLES.
!
!     PART OF THE PARALLEL PROCESSING EXTENSION TO PROGNOSIS.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'SNCOM.f90'
!
!
!OMMONS
!
!     NOTE: THE ACTUAL STORAGE LIMIT FOR INTS, LOGICS, AND REALS
!     IS MAXTRE (SEE PRGPRM).
!
INTEGER ILIMIT,IPNT,MXL,MXI,MXR
PARAMETER (MXL=1,MXI=2,MXR=1)
LOGICAL LOGICS(*)
REAL WK3(MAXTRE)
INTEGER INTS (*)
REAL REALS (*)
REAL RDANUW
LOGICAL LDANUW
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
RDANUW = REALS(1)
LDANUW = LOGICS(1)
!
!
!     GET THE INTEGER SCALARS.
!
CALL IFREAD (WK3, IPNT, ILIMIT, INTS, MXI, 2)
KODIST = INTS(1)
ISEFOR = INTS(2)
!
!     GET THE LOGICAL SCALARS.
!
!**   CALL LFREAD (WK3, IPNT, ILIMIT, LOGICS, MXL, 2)
!
!     GET THE REAL SCALARS.
!
!**   CALL BFREAD (WK3, IPNT, ILIMIT, REALS, MXR, 2)
RETURN
END

SUBROUTINE VARCHGET (CBUFF, IPNT, LNCBUF)
IMPLICIT NONE
!----------
!     Get variant-specific character data
!----------
!
!OMMONS
!
INCLUDE 'PRGPRM.f90'
!
INTEGER LNCBUF
CHARACTER CBUFF(LNCBUF)
INTEGER IPNT
INTEGER IDANUW
CHARACTER CDANUW
! Stub for variants which need to get/put character data
! See /bc/varget.f and /bc/varput.f for examples of VARCHGET and VARCHPUT
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
IDANUW = IPNT
CDANUW = CBUFF(1)
!
RETURN
END
