SUBROUTINE ESSUBH (I,HHT,EMSQR,DILATE,DELAY,ELEV,ISER,GENTIM, &
     TRAGE)
IMPLICIT NONE
!----------
! NC $Id$
!----------
!
!     ASSIGNS HEIGHTS TO SUBSEQUENT AND PLANTED TREE RECORDS
!     CREATED BY THE ESTABLISHMENT MODEL.
!
!
!     COMING INTO ESSUBH, TRAGE IS THE AGE OF THE TREE AS SPECIFIED ON
!     THE PLANT OR NATURAL KEYWORD.  LEAVING ESSUBH, TRAGE IS THE NUMBER
!     BETWEEN PLANTING (OR NATURAL REGENERATION) AND THE END OF THE
!     CYCLE.  AGE IS TREE AGE UP TO THE TIME REGENT WILL BEGIN GROWING
!     THE TREE.
!----------
!  COMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ESPARM.f90'
!
!
INCLUDE 'ESCOMN.f90'
!----------
!  DECLARATIONS
!----------
INTEGER I,ISER,N,ITIME
REAL    HHT,DELAY,DILATE,ELEV,EMSQR,GENTIM,TRAGE,AGE
REAL RDANUW
INTEGER IDANUW
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
RDANUW = DILATE
RDANUW = ELEV
RDANUW = EMSQR
IDANUW = ISER
!----------
N=INT(DELAY+0.5)
IF(N.LT.-3) N=-3
DELAY=FLOAT(N)
ITIME=INT(TIME+0.5)
IF(N.GT.ITIME) DELAY=TIME
AGE=TIME-DELAY-GENTIM+TRAGE
IF(AGE.LT.1.0) AGE=1.0
TRAGE=TIME-DELAY
SELECT CASE (I)
!
!     HEIGHT OF TALLEST SUBSEQUENT SPECIES 1 (OC)
!
CASE (1)
HHT = 1.0
!
!     HEIGHT OF TALLEST SUBS. SPECIES 2 (SP)
!
CASE (2)
HHT = 1.0
!
!     HT OF TALLEST SUBS. SPECIES 3 (DF)
!
CASE (3)
HHT = 1.0
!
!     HT OF TALLEST SUBS. SPECIES 4 (WF)
!
CASE (4)
HHT = 1.0
!
!     HT OF TALLEST SUBS. SPECIES 5 ( M)
!
CASE (5)
HHT = 7.0
!
!     HT OF TALLEST SUBS. SPECIES 6 (IC)
!
CASE (6)
HHT = 1.0
!
!     HT OF TALLEST SUBS. SPECIES 7 (BO)
!
CASE (7)
HHT = 7.0
!
!     HT OF TALLEST SUBS. SPECIES 8 (TO)
!
CASE (8)
HHT = 7.0
!
!     HT OF TALLEST SUBS. SPECIES 9 (RF)
!
CASE (9)
HHT = 1.0
!
!     HEIGHT OF TALLEST SUBS. SPECIES 10 (PP)
!
CASE (10)
HHT = 0.8
!
!     HT OF TALLEST SUBS. SPECIES 11 (OH)
!
CASE (11)
HHT = 7.0
!
!     HT OF TALLEST SUBS. SPECIES 12 (RW)
!
CASE (12)
HHT = 2.0
!
END SELECT
RETURN
END
!**END OF CODE SEGMENT





