SUBROUTINE EXCFIM
IMPLICIT NONE
!----------
! FIRE-BASE $Id$
!----------
!
!     EXTRA EXTERNAL REFERENCES FOR THE CFIM (Crown Fire Initiation Model) FROM FVS-BC
!     FOR USE WHEN CFIM IS NOT LINKED TO FFE
!
CHARACTER*8 CFTMP
INTEGER  IYR,FMOIS,CANBURN,FCLS,FLAME,FMD
REAL     ROS,INTSTY,UWIND,IBYRAM
REAL RDANUW
INTEGER IDANUW
CHARACTER*8 CDANUW
!----------
!  ENTRY FMCANC
!----------
ENTRY FMCANC (IYR,FMOIS,CFTMP,CANBURN,ROS,INTSTY,FCLS)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
IDANUW = IYR
IDANUW = FMOIS
IDANUW = CANBURN
IDANUW = FCLS
CDANUW(1:8) = CFTMP(1:8)
RDANUW = ROS
RDANUW = INTSTY
!
RETURN
!----------
!  ENTRY FMCFIM
!----------
ENTRY FMCFIM(IYR,FMD,UWIND,IBYRAM,FLAME,CANBURN,ROS)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
IDANUW = IYR
IDANUW = FMD
IDANUW = FLAME
IDANUW = CANBURN
RDANUW = UWIND
RDANUW = IBYRAM
RDANUW = ROS
!
RETURN
END
