SUBROUTINE FMDYN (SM,LG,ITYP,XPTS,EQWT,IPTR,ICLSS,LDYN,FMD)
IMPLICIT NONE
!----------
! FIRE-BASE $Id$
!----------
!     CALLED FROM: FMCFMD
!
!  PURPOSE:
!     THIS SUBROUTINE RETURNS THE SET OF UP TO 4, (TYPICALLY 2) FUEL
!     MODELS THAT WOULD BE USED IF THE DYNAMIC FUEL MODEL IS SELECTED
!
!************DYNAMIC FUEL MODEL CALCULATIONS***************
!
!     THIS ROUTINE FINDS A GROUP OF FIRE MODELS MOST APPROPRIATE TO
!     THE INPUT COMBINATION OF LARGE AND SMALL FUEL COMPONENTS.
!
!     THIS ROUTINE TAKES AS INPUT VARIABLES SMALL AND LARGE; A POINT
!     IN A 2-SPACE, REPRESENTING SMALL AND LARGE FUEL. THE POINT IS
!     COMPARED TO THE FUEL MODELS, EACH OF WHICH IS REPRESENTED BY A
!     STRAIGHT LINE ENCODED WITH XPTS(). THE NEAREST NEIGHORING LINES
!     ARE FOUND AND THE INVERSE OF THE DISTANCE TO THOSE LINES IS
!     USED AS THE WEIGHT WHICH IS GIVEN FOR THE FUEL MODEL ASSOCIATED
!     WITH THE LINE.
!
!     USUALLY THERE WILL BE TWO NEIGHBORING LINES (ONE TO THE LEFT AND
!     ONE TO THE RIGHT OF THE POINT). IN CASES WHERE THE POINT IS BEYOND
!     THE UPPER/LOWER-MOST LINE, THERE WILL BE ONLY ONE NEIGHBOR, AND IN
!     CASES WHERE HORIZONTAL, VERTICAL AND SLOPING LINES CROSS, THERE
!     MAY BE AS MANY AS FOUR NEIGHBOURS. THE LAST CASE IS UNUSUAL AND
!     WILL ONLY OCCUR IF THE MODEL WRITER KNOWINGLY MIXES IN THESE
!     TYPES OF LINES.
!
!     THE VECTORS FWT(5) AND FMOD(5) ARE PRODUCED AS OUTPUT. FOR EACH
!     NON-ZERO FMOD(I) THERE WILL BE A NON-ZERO WEIGHT GIVEN TO THE
!     CORRESPONDING FMOD() MODEL. WEIGHTS SUM TO 1.0
!
!----------------------------------------------------------------------
!
INCLUDE 'PRGPRM.f90'
INCLUDE 'CONTRL.f90'

INCLUDE 'FMPARM.f90'
INCLUDE 'FMCOM.f90'
INCLUDE 'FMFCOM.f90'

!     LOCAL VARIABLE DEFINITIONS:
!
!     SM:         SMALL FUEL LOAD
!     LG:         LARGE FUEL LOAD
!     LOK:        LOGICAL: TRUE IF MODEL IS A CANDIDATE;OTHERWISE FALSE
!     ITYP:       0 FOR SLANTED LINES; -1 FOR HORIZ; 1 FOR VERTICAL
!     XPTS(-,1):  FOR EACH FUEL MODEL, X-INTERCEPT (VALUE OF SMALL WHEN LARGE=0)
!     XPTS(-,2):  FOR EACH FUEL MODEL, Y-INTERCEPT (VALUE OF LARGE WHEN SMALL=0)
!     EQMOD:      INDEX OF ANY COLLINEAR FUEL MODEL (OTHERWISE 0)
!     EQWT:       WT OF ANY COLLINEAR FUEL MODEL (OTHERWISE 0)
!     IPTR:       LABEL/TAG FOR EACH FIRE MODEL CLASS
!     ICLSS:      LENGTH OF NUMEROUS VECTORS (IPTR,ITYP,EQMOD,EQWT,XPTS)
!     LDYN:       IS DYNAMIC MODELLING NEEDED OR NOT
!     FMD:        DOMINANT FUEL MODEL (ASSIGNED ON RETURN)
!
!**********************************************************************
!
INTEGER   ICLSS
INTEGER   I, II, J, K, K2
INTEGER   IPTR, ITYP, FMD
INTEGER   FMOD2, NBR(4), INDX(MXFMOD)
INTEGER   EQMOD(ICLSS)
REAL      SM, LG
REAL      XPTS, XD, YD
REAL      PT(2), NPT(2), M1, M2, B1, B2, XP, YP, XWT
REAL      EQWT, FWT2
REAL      PRV(4), WT(4)
LOGICAL   DEBUG, LOK, FMCHKFWT, LDYN

DIMENSION IPTR(ICLSS), ITYP(ICLSS), EQWT(ICLSS)
DIMENSION XPTS(ICLSS,2), XD(ICLSS), YD(ICLSS), LOK(ICLSS)
DIMENSION FWT2(MXFMOD), FMOD2(MXFMOD)

CALL DBCHK (DEBUG,'FMDYN',5,ICYC)

!     INITIALIZE WEIGHTS OF DYNAMIC FIRE MODELS

DO I= 1,4
  NBR(I) = 0
ENDDO

DO I = 1,MXFMOD
  FMOD(I)  = 0
  FWT(I)   = 0.
  FMOD2(I) = 0
  FWT2(I)  = 0.
ENDDO

DO I = 1,ICLSS
  EQMOD(I) = 0
  LOK(I)   = .FALSE.
ENDDO

PT(1) = SM
PT(2) = LG
!
!     EMPTY-HANDED IF EITHER SMALL OR LARGE IS NEGATIVE
!
IF (PT(1) .LT. 0.0 .OR. PT(2) .LT. 0.0) GOTO 999
!
!     SET LOK() VECTOR
!
DO I = 1,ICLSS
  IF (EQWT(I) .GT. 0.0) LOK(I) = .TRUE.
ENDDO
!
!     UNSET LINES THAT ARE LOK, BUT WITH INVALID COEFFICIENTS
!
DO I = 1, ICLSS
  IF (LOK(I)) THEN
    J = ITYP(I)
    IF ((J .EQ. 0 .AND. &
           (XPTS(I,1) .EQ. 0..OR. XPTS(I,2) .EQ. 0.0)) .OR. &
           (J .EQ. -1 .AND. XPTS(I,2) .EQ. 0) .OR. &
           (J .EQ.  1 .AND. XPTS(I,1) .EQ. 0)) THEN
      LOK(I)  = .FALSE.
      EQWT(I) = 0.0
    ENDIF
  ENDIF
ENDDO
!
!     SET EQMOD() VECTOR
!
DO I = 1,ICLSS
  EQMOD(I) = 0
ENDDO
DO I = 1,ICLSS
  IF (LOK(I)) THEN
    DO J = I,ICLSS
      IF (EQMOD(J) .EQ. 0 .AND. &
           LOK(J) .AND. &
           XPTS(I,1) .EQ. XPTS(J,1) .AND. &
           XPTS(I,2) .EQ. XPTS(J,2)) EQMOD(J) = I
    ENDDO
  ENDIF
ENDDO
!
!     RESCALE SO THAT THE COLINEAR EQWT ELEMENTS SUM TO 1.0
!
DO I = 1,ICLSS
  IF (LOK(I)) THEN
    XWT = 0.0
    DO J = I,ICLSS
      IF (LOK(J) .AND. EQMOD(J) .EQ. I) XWT= XWT+ EQWT(J)
    ENDDO
    IF (XWT .GT. 1.0E-6) THEN
      DO J = I,ICLSS
        IF (LOK(J) .AND. EQMOD(J) .EQ. I) EQWT(J) = EQWT(J)/XWT
      ENDDO
    ENDIF
  ENDIF
ENDDO
!
!     COMPUTE VECTOR XD() CONTAINING DISTANCE TO THE LEFT (<0) AND RIGHT
!     (>0) LINES RELATIVE TO THE SAMPLE POINT. DO THE SAME WITH YD() FOR
!     UPPER (>0) AND LOWER (<0) SAMPLE POINTS. IN WELL-BEHAVED SITUATIONS
!     THEY WILL BE THE SAME, BUT TO HANDLE THE HORIZONTAL AND VERTICAL
!     CASES, THE TWO SEARCHES ARE REQUIRED. THERE ARE CASES (WITH ISOLINES
!     THAT CROSS IN A COMPLICATED WAY) THAT WILL NOT BE DONE PROPERLY:
!     THESE WOULD REQUIRE A SMARTER NEIGHBOR SEARCH. IN SOME CASES THE
!     SAMPLE POINT WILL BE THE LARGEST OR SMALLEST; THESE CORRESPOND TO
!     BEING ABOVE OR BELOW THE GREATEST OR SMALLEST ISOLINE.
!
!     XD() HOLDS DISTANCE ON X-AXIS FROM POINT TO WHERE IT CROSSES EACH LINE
!     IF <0, THEN TO THE LEFT; >0 THEN TO THE RIGHT; HORIZONTAL/VERTICAL CASES
!     ARE GIVEN AN ARBITRARY LARGE NUMBER
!
DO 20 I = 1, ICLSS
  IF (.NOT. LOK(I)) GOTO 20
  J = ITYP(I)
  XD(I) = 0.
  YD(I) = 0.
  IF (J .EQ. 0) THEN
    M1 = XPTS(I,2) / (-XPTS(I,1))
    B1 = XPTS(I,2)
    XP = (PT(2) - B1 ) / M1
    YP = M1 * PT(1) + B1
    XD(I) = XP - PT(1)
    YD(I) = YP - PT(2)
  ELSEIF (J .EQ. 1) THEN ! VERTICAL
    XD(I) = XPTS(I,1) - PT(1)
  ELSEIF (J .EQ. -1) THEN ! HORIZONTAL
    YD(I) = XPTS(I,2) - PT(2)
  ENDIF
20 CONTINUE
!
!     FIND CLOSEST NEIGHBORS IN LEFT/RIGHT AND UP/DOWN DIRECTION
!     AND STORE INDICES IN NBR() ARRAY. DUPLICATES ARE OK
!
PRV(1) = -9.99E+30
PRV(2) =  9.99E+30
PRV(3) = -9.99E+30
PRV(4) =  9.99E+30

DO 22 I = 1,ICLSS
  IF (.NOT. LOK(I)) GOTO 22
  J = ITYP(I)
  IF (J .EQ. 0 .OR. J .EQ. 1) THEN ! NORMAL OR VERTICAL
    IF (XD(I) .LT. 0. .AND. XD(I) .GT. PRV(1)) THEN
      PRV(1) = XD(I)
      NBR(1) = I
    ELSEIF (XD(I) .GE. 0. .AND. XD(I) .LT. PRV(2)) THEN
      PRV(2) = XD(I)
      NBR(2) = I
    ENDIF
  ENDIF
  IF (J .EQ. 0 .OR. J .EQ. -1) THEN ! NORMAL OR HORIZONTAL
    IF (YD(I) .LT. 0. .AND. YD(I) .GT. PRV(3)) THEN
      PRV(3) = YD(I)
      NBR(3) = I
    ELSEIF (YD(I) .GE. 0. .AND. YD(I) .LT. PRV(4)) THEN
      PRV(4) = YD(I)
      NBR(4) = I
    ENDIF
  ENDIF
22 CONTINUE
!
!     FIND DISTANCE FROM TRIAL POINT TO EACH DEFINED LINE;
!     FIND THE NEAREST TWO LINES IF WITHIN THE DOMAIN; OTHERWISE
!     FIND THE NEAREST ONE LINE IF OUTSIDE THE DOMAIN
!
!     M1 = SLOPE OF ISOLINE
!     B1 = INTERCEPT OF "ISOLINE"
!     M2 = SLOPE OF LINE NORMAL ISOLINE
!     B2 = INTERCEPT OF LINE NORMAL TO "ISOLINE"
!
!     DISTANCE IS PLACE IN WT() VECTOR
!
DO 30 K = 1,4
  I = NBR(K)
  IF (I .EQ. 0) GOTO 30
  IF (.NOT. LOK(I)) GOTO 30
  J = ITYP(I)
  IF (J .EQ. 0) THEN
    M1 = XPTS(I,2) / (-XPTS(I,1))
    B1 = XPTS(I,2)
    M2 = -(1./M1)
    B2 = PT(2) - (M2 * PT(1))
    NPT(1) = (B2 - B1) / (M1 - M2)
    NPT(2) = M2 * NPT(1) + B2
    WT(K) = SQRT((PT(2) - NPT(2))**2 + (PT(1) - NPT(1))**2)
  ELSEIF (J .EQ. 1) THEN ! VERTICAL
    WT(K) = ABS(XPTS(I,1) - PT(1))
  ELSEIF (J .EQ. -1) THEN ! HORIZONTAL
    WT(K) = ABS(XPTS(I,2) - PT(2))
  ENDIF
30 CONTINUE
!
!     MERGE DUPLICATE INDICES; WHEN FINISHED, K IS THE NEXT
!     OPEN POSITION IN THE FWT/FMOD ARRAYS
!
K2 = 0
DO 40 I = 1,4
  IF (NBR(I) .EQ. 0) GOTO 40
  K2 = K2 + 1
  DO 41 J = 1, I
    IF (FMOD(J) .EQ. NBR(I)) THEN
      K = J
      GOTO 42
    ENDIF
41   CONTINUE
  K = K2
  IF (FMCHKFWT(K)) FMOD(K) = NBR(I)
42   IF (FMCHKFWT(K)) FWT(K)  = FWT(K) + WT(I)
40 CONTINUE
!
!     REWEIGHT BY INVERSE OF DISTANCE
!
XWT = 0.
DO 50 I = 1,MXFMOD
  IF (FMOD(I) .EQ. 0) GOTO 50
  FWT(I) = 1.0/(FWT(I) + 1.0E-6)
  XWT = XWT + FWT(I)
50 CONTINUE
DO 55 I = 1, MXFMOD
  IF (FMOD(I) .EQ. 0) GOTO 55
  FWT(I) = FWT(I) / XWT
55 CONTINUE
!
!     MOVE ALL NON-ZERO FWT/FMOD, LEAVING ALL OPEN SPOTS
!     AT THE BOTTOM OF THE ARRAY
!
K = 0
DO 60 I = 1,MXFMOD
  IF (FMOD(I) .EQ. 0) GOTO 60
  K = K + 1
  IF (I .NE. K .AND. FMCHKFWT(K)) THEN
    FMOD(K) = FMOD(I)
    FWT(K)  = FWT(I)
    FMOD(I) = 0
    FWT(I)  = 0.0
  ENDIF
60 CONTINUE
!
!     WALK THROUGH LIST OF MODELS AND SAVE THE WEIGHT TO BE SHARED
!     AMONG THE OVERLAPPING MODELS
!
DO I = 1,MXFMOD
  FMOD2(I)  = 0
  FWT2(I)   = 0.
ENDDO

K=1
DO I = 1,MXFMOD
  IF (FMOD(I) .NE. 0) THEN
    II  = FMOD(I)
    XWT = FWT(I)
    IF (EQMOD(II) .EQ. 0 .AND. FMCHKFWT(K)) THEN
      FWT2(K)  = FWT(I)
      FMOD2(K) = FMOD(I)
      K        = K + 1
    ELSE
      DO J = 1,ICLSS
        IF (EQMOD(J) .EQ. EQMOD(II) .AND. &
               EQWT(J) .GT. 0.0) THEN
          IF (FMCHKFWT(K)) THEN
            FWT2(K)  = FWT2(K) + EQWT(J) * XWT
            FMOD2(K) = J
            K        = K + 1
          ENDIF
        ENDIF
      ENDDO
    ENDIF
  ENDIF
ENDDO
!
!     MERGE IN ANY DUPLICATES THAT MAY HAVE ARISEN FROM
!     THE ADDITION OF COLINEAR FUEL MODELS (IMPOSSIBLE UNDER
!     CURRENT FUEL MODEL DEFINITIONS)
!
999 K2 = 0
DO I = 1,MXFMOD
  FMOD(I)  = 0
  FWT(I)   = 0.
ENDDO

DO 70 I = 1,MXFMOD
  IF (FMOD2(I) .EQ. 0) GOTO 70
  K2 = K2 + 1
  DO J = 1, I
    IF (FMOD(J) .EQ. FMOD2(I)) THEN
      K = J
      GOTO 72
    ENDIF
  ENDDO
  K = K2
  IF (FMCHKFWT(K)) FMOD(K) = FMOD2(I)
72   IF (FMCHKFWT(K)) FWT(K)  = FWT(K) + FWT2(I)
70 CONTINUE

DO 75 I = 1,MXFMOD
  IF (FMOD(I) .EQ. 0) GOTO 75
  FMOD(I) = IPTR(FMOD(I))
75 CONTINUE
!
!     SORT WEIGHTS SUCH THAT HIGHEST WEIGHT IS ALWAYS FIRST
!     WHAT ABOUT TIES?
!
CALL RDPSRT (MXFMOD,FWT,INDX,.TRUE.)
DO I = 1,MXFMOD
  J= INDX(I)
  FMOD2(I) = FMOD(J)
  FWT2(I)  = FWT(J)
ENDDO
DO I = 1,MXFMOD
  FMOD(I) = FMOD2(I)
  FWT(I)  = FWT2(I)
ENDDO
!
!     TRUNCATE NUMBER OF FUEL MODELS TO 4 AND REWEIGHT,
!     IN THE RARE CASE THAT >4 MODELS HAVE BEEN SELECTED
!     THIS SOMETIMES HAPPENS IN THE EC, WITH THE 5TH MODEL
!     WEIGHT AT 2-3% OF THE TOTAL.
!     (CONVERSATION WITH NICK; 3 DECEMBER 2002)
!
XWT = 0.0
DO I = 1,4
  XWT = XWT + FWT(I)
ENDDO
IF (XWT .GT. 1.0E-6) THEN
  DO I = 1,4
    FWT(I) = FWT(I) / XWT
  ENDDO
  DO I = 5,MXFMOD
    FMOD(I) = 0
    FWT(I)  = 0.0
  ENDDO
ENDIF
!
!     SELECT NON-DYNAMIC MODEL BASED ON MOST HEAVILY WEIGHTED MODEL
!     FAILSAFE IS TO NAME MODEL 8 AND ISSUE A WARNING
!
FMD = -1
IF (FWT(1) .GT. 1.0E-6) FMD = FMOD(1)
IF (FMD .LT. 0) THEN
  FMOD(1) = 8
  FWT(1)  = 1.0
  NFMODS  = 1
  DO I = 2,MXFMOD
    FMOD(I) = 0
    FWT(I)  = 0.0
  ENDDO
  CALL RCDSET(2, .TRUE.)
ENDIF
!
!     COMPUTE THE NUMBER OF ACTIVE MODELS
!
DO I = 1,MXFMOD
  IF (FWT(I) .LE. 1.0E-6) THEN
    NFMODS = I-1
    EXIT
  ENDIF
ENDDO
NFMODS = MIN(NFMODS,4)
!
!     IF STATIC FUEL MODEL IS DESIRED, UNSET ALL OTHER WEIGHTS
!
IF (.NOT. LDYN) THEN
  FMOD(1) = FMD
  FWT(1)  = 1.0
  NFMODS  = 1
  DO I = 2, MXFMOD
    FMOD(I) = 0
    FWT(I)  = 0.0
  ENDDO
ENDIF

IF (DEBUG) WRITE (JOSTND,80) FMD, FMOD,FWT
80 FORMAT (' FMDYN, FMD=',I4,' FMOD=',5I4,' FWT=',5F7.2)

RETURN
END
