SUBROUTINE FMGFMV(IYR, IFMD)
IMPLICIT NONE
!----------
! FIRE-BASE $Id$
!----------
!  PURPOSE:
!     THIS SUBROUTINE LOADS THE FUEL MODEL PARAMETER VALUES FOR
!     THE FUEL MODEL PASSED AS IFMOD.
!----------------------------------------------------------------------
!
!  CALL LIST DEFINITIONS:
!    IYR:      CALENDAR YEAR
!    IFMD:     FUEL MODEL NUMBER
!
!  LOCAL VARIABLE DEFINITIONS:
!
!  COMMON BLOCK VARIABLES AND PARAMETERS:
!
!**********************************************************************

!.... PARAMETER INCLUDE FILES.

INCLUDE 'PRGPRM.f90'
INCLUDE 'FMPARM.f90'

!.... COMMON INCLUDE FILES.

INCLUDE 'FMFCOM.f90'
INCLUDE 'FMCOM.f90'
INCLUDE 'CONTRL.f90'

!     LOCAL VARIABLE DECLARATIONS

INTEGER  IYR,IFMD,I,J,IRTNCD
LOGICAL  DEBUG
REAL     SUMPS
REAL     X(2), Y(2), ALGSLP, WT
!-----------
!     FIXED VALUES FOR INTERPOLATION FUNCTION
!-----------
DATA     Y / 0.0, 1.0 /

!----------
!     BEGIN ROUTINE
!  INITIALIZE VARIABLES
!----------
DO I = 1,2
  DO J = 1,4
    MPS(I,J)=0
  ENDDO
!
  DO J = 1,7
    FWG(I,J)=0.0
  ENDDO
ENDDO
!
MEXT(1)=0.0
MEXT(2)=0.0
MEXT(3)=0.0
!-----------
!  CHECK FOR DEBUG.
!-----------
CALL DBCHK (DEBUG,'FMGFMV',6,1)
IF (DEBUG) WRITE(JOSTND,7)
7 FORMAT(' ENTERING ROUTINE FMGFMV ')
!
!     Number of fuel categories:
!     ND: 0=no dead, 1=1hr, 2=10hrs, 3=100hrs. NL: 0=No live, 1=live
!        Even though these values are saved in NUMD and NUML,
!        we are going to recalculate them here (because the user may
!        have changed them in the keyword DEFULMOD). If FWG > 0 then
!        the fuel category is present.
!
ND    = 0
NL    = 0
SUMPS = 0.0

!     SET DEAD HERB SAV TO LIVE HERB SAV
SURFVL(IFMD,1,4) = SURFVL(IFMD,2,2)

DO I = 1,2
  DO J = 1,4
    MPS(I, J) = SURFVL(IFMD,I,J)
    FWG(I, J) = FMLOAD(IFMD,I,J)
  ENDDO
ENDDO

!     PUT SOME OF THE LIVE HERBS INTO THE DEAD HERB CATEGORY (BASED ON
!     MOISTURE) FOR THE DYNAMIC FUEL MODELS (not fm 2)
IF ((FMLOAD(IFMD,2,2) .GT. 0) .AND. (IFMD .NE. 2) .AND. &
        (MOIS(2,2) .LT. 1.2)) THEN
  X(1) =  .30
  X(2) =  1.2
  WT = ALGSLP(MOIS(2,2),X,Y,2)
  FWG(1,4) = (1 - WT)*FMLOAD(IFMD,2,2)
  FWG(2,2) = WT*FMLOAD(IFMD,2,2)
ENDIF

DO I = 1,2
  DO J = 1,4
    IF (I .EQ. 1 .AND. FWG(I,J) .GT. 0.0) ND = ND + 1
    IF (I .EQ. 2 .AND. FWG(I,J) .GT. 0.0) NL = NL + 1
    SUMPS = SUMPS + MPS(I,J)
  ENDDO
ENDDO
DEPTH   = FMDEP(IFMD)
MEXT(1) = MOISEX(IFMD)
!
!     CHECK FOR ERRORS THAT CAN HAPPEN IF THE USER WANTED TO USE A FUEL
!     MODEL (FUELMODL) THAT HAS NOT YET BEEN DEFINED OR HAS BEEN INCOMPLETELY
!     DEFINED.
!
!     IF THERE ARE NO LIVE OR DEAD CLASSES, OR IF THE SURFACE TO VOLUME
!     RATIO IS <=0 FOR ALL CLASSES. OR IF DEPTH IS ZERO, THEN SOMETHING
!     IS SERIOUSLY WRONG. EXIT WITH AN ERROR CODE.
!
IF (DEBUG) WRITE(JOSTND,9) ND, NL, SUMPS, DEPTH
9 FORMAT(' FMGFMV, ND=',I2,' NL=',I2,' SUMPS=',F10.3,'DEPTH=',F7.3)

IF ((ND .LE. 0 .AND. NL .LE. 0) .OR. SUMPS .LE. 0.0 .OR. &
       DEPTH .LE. 0.0) THEN
  WRITE(JOSTND,'("/ ")')
  WRITE(JOSTND,'("/ *** FFE: FATAL PROBLEM: YEAR = ", I4)') IYR
  WRITE(JOSTND,'("/ *** FFE: FUEL MODEL = ", I2)') IFMD
  WRITE(JOSTND,'("/ *** FFE: NO LIVE OR DEAD CLASSES, NO", &
       " FUEL SURF/VOL, OR NO DEPTH DEFINED")')
  WRITE(JOSTND,'("/ *** FFE: CHECK ""DEFULMOD"" AND", &
       " ""FUELMODL"" KEYWORD USE")')
  WRITE(JOSTND,'("/ *** FFE: EXITING")')
  CALL ERRGRO(.FALSE.,4)
  CALL fvsGetRtnCode(IRTNCD)
  IF (IRTNCD.NE.0) RETURN
ENDIF
!
!     ADD THE DEPTH MODIFIER BASED ON ACTIVITY-RELATED FUEL TREATMENTS
!     SEE **FMUSRFM** FOR CALCULATION OF DPMOD
!
DEPTH = DEPTH * DPMOD

RETURN
END
