SUBROUTINE FMSVSYNC
IMPLICIT NONE
!----------
! FIRE-BASE $Id$
!----------
!
!     STAND VISUALIZATION GENERATION
!     A.H.DALLMANN -- RMRS MOSCOW -- MAY 2000
!
!     SYNCHRONIZES THE SV OUTPUT SNAGS WITH THE SNAGS THAT THE FIRE
!     MODEL IS KEEPING TRACK OF.
!
!     *****  UNDER DEVELOPMENT ******
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
INCLUDE 'FMPARM.f90'
!
!
INCLUDE 'CONTRL.f90'
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'FMCOM.f90'
INCLUDE 'FMFCOM.f90'
!
!
INCLUDE 'SVDATA.f90'
INCLUDE 'SVDEAD.f90'
!
!
!OMMONS
!
REAL FMTOTAL
INTEGER D,S
INTEGER SVTOTAL
INTEGER DBHCL
LOGICAL DEBUG

REAL CURFMSN(19,MAXSP)
INTEGER CURSVSN(19,MAXSP)
INTEGER I

CALL DBCHK (DEBUG,'FMSVSYNC',8,ICYC)

IF (DEBUG) WRITE (JOSTND,'('' IN FMSVSYNC, JSVOUT='',I4)') JSVOUT

!     NO NEED TO SYNC THE DATA IF VISUALIZATION IS NOT BEING DONE!

IF (JSVOUT.EQ.0) RETURN

!     CLEAR OUT OUT TEMP LIST

DO D=1,19
   DO S=1,MAXSP
      CURFMSN(D,S) = 0.
      CURSVSN(D,S) = 0
   ENDDO
ENDDO

FMTOTAL = 0.
SVTOTAL = 0

!     ADD UP ALL OF THE DIFFERENT DENSITIES FROM THE FIRE SNAGS.

DO I=1,NSNAG
   DBHCL = INT(DBHS(I)/2.0+1)
   IF (DBHCL .GT. 19) DBHCL = 19

   CURFMSN(DBHCL,SPS(I))=CURFMSN(DBHCL,SPS(I))+DENIS(I)+DENIH(I)
   IF (DBHCL .GE. 2) FMTOTAL = FMTOTAL + DENIS(I) + DENIH(I)
ENDDO

!     ADD UP ALL OF THE STANDING SV SNAGS IN EACH CATEGORY OF THE FIRE SNAGS.

DO I=1,NSVOBJ

  IF (IOBJTP(I).NE.2) CYCLE
  IF (FALLDIR(IS2F(I)).EQ.-1) THEN

!           THIS IS A STANDING SNAG, GET THE DIAMETER CLASS AND SPECIES

      DBHCL = INT(ODIA(IS2F(I)) / 2.0 + 1.0)
      IF (DBHCL .GT. 19) DBHCL = 19

!           NOW THAT WE HAVE THE CORRECT DIAMETER CLASS, WE NEED TO
!           ADD ONE TO THE MATCHING SPECIES-DIAMETER COUNT

      CURSVSN(DBHCL,ISNSP(IS2F(I)))=CURSVSN(DBHCL,ISNSP(IS2F(I))) &
              + 1

!           ADD ONE TO THE SVTOTAL AS WELL.
!
      IF (DBHCL .GE. 2) SVTOTAL = SVTOTAL + 1
   ENDIF

ENDDO

!     DISPLAY THE DIFFERENCE BETWEEN THE PROB AND THE OBJECTS.

IF (DEBUG) THEN

   DO S=1,MAXSP
      DO D=2,19
         IF (CURFMSN(D,S)+CURSVSN(D,S).GT.0.) THEN
            WRITE (JOSTND,10) S,D,CURFMSN(D,S),CURSVSN(D,S)
10             FORMAT (' Species=',A,' DBHClass=',I3,' CURFM=', &
                        F8.3,' CURSVSN=',I4)
         ENDIF
      ENDDO
   ENDDO
   WRITE (JOSTND,'('' TOTAL DIFF='',F10.3)') SVTOTAL-FMTOTAL
ENDIF

RETURN
END









