SUBROUTINE FMSVFL (NOUT)
IMPLICIT NONE
!----------
! FIRE-BASE $Id$
!----------
!     FIRE MODEL STAND VISUALIZATION GENERATION
!     N.L.CROOKSTON -- RMRS MOSCOW -- JANUARY 2000
!     A.H.DALLMANN  -- RMRS MOSCOW -- JANUARY 2000
!     D. ROBINSON   -- ESSA        -- MAY 2005
!
!     INPUT:
!     NOUT  =THE OUTPUT FILE REFERENCE NUMBER
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'

INCLUDE 'FMPARM.f90'

INCLUDE 'SVDATA.f90'

INCLUDE 'FMSVCM.f90'

INCLUDE 'FMCOM.f90'

INCLUDE 'FMFCOM.f90'

INCLUDE 'METRIC.f90'

!OMMONS

EXTERNAL SVRANN
INTEGER  NOUT,NFLF,NFLAMES,NFLMS,IFLAMES,II,IFLR0T
REAL     WIDTHMIN,TILTBASE,WMAX,WIDTH,FLMX,FLMY,BACHLO,TEMP, &
            TEMP2,TMPDIST,TMPPCT,TMPVAR,TMPHEIGHT,FLMHT,FMWDTH, &
            FLMWDTH,X,FLMTILT,XD,XR,XR2

!     OUTPUT THE FIRE LINE

WRITE (NOUT,10) '#FIRE_LINE ',FMY2
10 FORMAT (A,100(1X,F6.2))

!     OUTPUT THE FUEL LOADS BEFORE AND AFTER THE FIRE LINE

WRITE (NOUT, 10) '#PRE_FIRE_LOAD',TCWD
WRITE (NOUT, 10) '#POST_FIRE_LOAD',TCWD2

!     CALCULATE THE GEOMETRY INFORMATION USED BY THE FLAME OUTPUT.

!     WIDTH REFERS TO THE MAX-X VALUE OF THE STAND.  IT IS SHIFTED
!     BY MINWIDTH.

WIDTHMIN = 0.

!     CALCULATE THE FLAMES TILT ANGLE BASED ON THE WIND.

IF (FWIND.LE.1.) THEN
  TILTBASE = 5.
ELSEIF (FWIND.LE.10.) THEN
  TILTBASE = 15.
ELSEIF (FWIND.LE.35.) THEN
  TILTBASE = 30.
ELSE
  TILTBASE = 40.
ENDIF

!     FOR ONLY PASSIVE (TORCHING) OR SURFACE FIRES, DRAW SOME FLAMES
!     ON THE GROUND IN A FLAME WALL.

IF (FIRTYPE .EQ. 1) THEN
  NFLF = 0
ELSE
  NFLF = 250
ENDIF

IF (IMETRIC.EQ.0) THEN
  IF (IPLGEM .LE. 1) THEN
    WMAX   = 208.71
    WIDTH  = 208.71
  ELSE
    WMAX   = 235.50
  ENDIF
ELSE
  IF (IPLGEM .LE. 1) THEN
    WMAX   = 100.0
    WIDTH  = 100.0
  ELSE
    WMAX   = 112.84
  ENDIF
ENDIF
FLPART = WMAX / NFLPTS

!     NFLAMES IS THE NUMBER OF RANDOM FLAME OBJECTS TO DRAW.

NFLAMES = NFLF
NFLMS = NFLAMES

DO 30 IFLAMES=1, NFLAMES

!       INITIALIZE THE FLAMES

  IF (IFLAMES .LE. NFLF) THEN

!         CALCULATE AN INITIAL X-VALUE.  BRANCH BACK IF THE POINT IS REJECTED

20     CONTINUE
    CALL SVRANN( FLMX )
    FLMX = FLMX * WMAX

!         FIGURE OUT WHICH FLAME SECTION THIS VALUE WOULD BE IN.

    II = IFIX( FLMX / FLPART )
    IF ( II.GT.NFLPTS ) THEN
      II = NFLPTS
    ELSEIF ( II.LT.1 ) THEN
      II = 1
    ENDIF

!         BASE THE INITIAL Y-VALUE ON THE SECTION.

    FLMY = BACHLO( FMY2(II), 2.5, SVRANN )

!         IF THE Y IS OUTSIDE THE ALLOWED RANGE ,
!         THEN WE SHOULDN'T DRAW THE FLAME.

    IF ( FLMY .LT. 0. .OR. FLMY .GT. WMAX ) GOTO 30

!         CHECK TO MAKE SURE THIS VALUE IS WITHIN THE STAND

    IF (IPLGEM .GT. 1) THEN

!           Calculate the width based on FLMY
!           D=235.50, R=117.75, R^2 = 13865.06250

      IF (IMETRIC.EQ.0) THEN
        XD  =   235.50
        XR  =   117.75
        XR2 = 13865.06
      ELSE
        XD  =   112.84
        XR  =    56.42
        XR2 =  3183.22
      ENDIF

      IF (FLMY .GT. XR) THEN
        TEMP  = FLMY - XR
        TEMP2 = TEMP**2
        WIDTH = 2. * SQRT(XR2 - (FLMY-XR)**2)
      ELSE
        TEMP  = XR - FLMY
        TEMP2 = TEMP**2
        WIDTH = 2. * SQRT(XR2 - (XR-FLMY)**2 )
      ENDIF
      WIDTHMIN = (XD - WIDTH) / 2.
    ENDIF

!         IF THE X-VALUE DOESN'T WORK WITH THE Y-VALUE, REDO THE
!         CALCULATION.

    IF ( FLMX.LT.WIDTHMIN .OR. &
            FLMX.GT.(WIDTHMIN+WIDTH) ) GOTO 20

!         CALCULATE THE FLAME HEIGHT.  IN FRONT OF THE MAIN WALL, THE
!         FLAMES WILL LIKELY BE ABOUT 10% FULL, 100% AT THE MAIN WALL
!         AND TAILING OFF WITH AN F(X) = X^3 FUNCTION.

    IF ( FLMY.GT.(FMY2(II)+1.0) ) THEN

!           TMPDIST IS GUARANTEED TO BE GREATER THAN 1.0 AT THIS POINT

      TMPDIST = FLMY - FMY2(II)
      TMPPCT = 1.0 / TMPDIST
      TMPVAR = 1.0 - TMPPCT**2
      TMPHEIGHT = FLAMEHT - ((FLAMEHT * TMPVAR))
      FLMHT = BACHLO(TMPHEIGHT, TMPHEIGHT * 0.05, SVRANN)

    ELSEIF (FLMY.GE.(FMY2(II)-1.0)) THEN
      FLMHT = BACHLO(FLAMEHT, FLAMEHT * 0.1, SVRANN)
    ELSE

!           TMPDIST IS GUARANTEED TO BE GREATER THAN 1.0 AT THIS POINT

      TMPDIST = FMY2(II) - FLMY
      TMPPCT = 1.0 / TMPDIST
      TMPVAR = 1.0 - TMPPCT**3
      TMPHEIGHT = FLAMEHT - ((FLAMEHT * TMPVAR)/2.0)
      FLMHT = BACHLO(TMPHEIGHT, TMPHEIGHT * 0.05, SVRANN)
    ENDIF
  ELSE

!       ANY RANDOM FLAMES WOULD BE DRAWN HERE.

  ENDIF

  CALL SVRANN( FMWDTH )
  FLMWDTH = FMWDTH * FLAMEHT + 1.0
  FLMTILT = BACHLO(TILTBASE, 5.0, SVRANN)
  CALL SVRANN(X)
  IFLR0T=INT(X*360.)

!       GO AHEAD AND WRITE OUT THE FIRE INFORMATION TO THE SVS FILE.

  IF (IMETRIC.EQ.0) THEN
    WRITE (NOUT,25) IFLAMES+NSVOBJ, &
         FLMHT,FLMTILT,IFLR0T,FLMWDTH,FLMX,FLMY,0.
  ELSE
   WRITE (NOUT,25) IFLAMES+NSVOBJ, &
         FLMHT*FTtoM,FLMTILT,IFLR0T,FLMWDTH*FTtoM,FLMX,FLMY,0.
  ENDIF

25   FORMAT ('@flame.eob',T16,I5,' 99 0 1 0',2F6.0,I5,' 0',F6.1, &
       ' 0 0 0 0 0 0 0 1 0',3F8.2)
30 CONTINUE

RETURN
END

SUBROUTINE FMGETFL(ASIZE, FLINE)
!----------
!     **FMGETFL--FIRE   DATE OF LAST REVISION: 06/19/02
!----------
!
!     FIRE MODEL GET FIRE LINE INFORMATION
!     D.L.GAMMEL -- SEM -- JUNE 2002
!
!     INPUT:
!     ASIZE  =THE SIZE OF THE ARRAY PASSED IN
!     FLINE  =THE ARRAY TO BE FILLED WITH THE FIRE LINE INFO
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
INCLUDE 'SVDATA.f90'
!
INCLUDE 'FMSVCM.f90'
!
!OMMONS
!
REAL FLINE
INTEGER ASIZE

DIMENSION FLINE(ASIZE)

DO I = 1,MIN(ASIZE,NFLPTS)
   FLINE(I) = FMY2(I)
ENDDO

END


