SUBROUTINE FMSVTOBJ(IFTYP)
IMPLICIT NONE
!----------
! FIRE-BASE $Id$
!----------
!
!     STAND VISUALIZATION GENERATION
!     A.H.DALLMANN -- RMRS MOSCOW -- JANUARY 2000
!
!     COPIES THE CURRENT CONTENTS OF IOBJTP VECTOR INTO TIOBJTP VECTOR
!     SO THAT SVMORT (ETC) CAN MANIPULATE THE OBJECT LIST AND CAN BE COMPARED
!     AN ORIGINAL.
!
!     CALLED FROM FMEFF.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'SVDATA.f90'
!
!
INCLUDE 'SVDEAD.f90'
!
!
INCLUDE 'FMSVCM.f90'
!
!
!OMMONS
!
INTEGER I,IFTYP

DO I = 1,NSVOBJ
   IOBJTPTMP(I) = IOBJTP(I)
   IS2FTMP(I) = IS2F(I)
ENDDO

!     SINCE THIS IS ONLY CALLED FROM FMEFF.F, WE NEED TO
!     CONVERT STANDING "GREEN" AND "RED" SNAGS INTO STANDING BURNED
!     SNAGS (CROWNING AND TORCHING FIRES ONLY)

DO I = 1,NSVOBJ
   IF (IOBJTP(I) .EQ. 2) THEN
      IF (FALLDIR(IS2F(I)) .EQ. -1) THEN
         IF (IFTYP.EQ.1 .OR. IFTYP.EQ.2 ) THEN
            IF (ISTATUS(IS2F(I)) .EQ. 2) THEN
               ISTATUS(IS2F(I)) = 5
            ELSE IF (ISTATUS(IS2F(I)) .EQ. 3) THEN
               ISTATUS(IS2F(I)) = 6
            ELSE IF (ISTATUS(IS2F(I)) .EQ. 4) THEN
               ISTATUS(IS2F(I)) = 6
            ENDIF
         ENDIF
      ELSE
!
!              ALWAYS CONVERT LAYING SNAGS INTO BURNED SNAGS.
!
         IF (ISTATUS(IS2F(I)) .EQ. 2) THEN
            ISTATUS(IS2F(I)) = 5
         ELSE IF (ISTATUS(IS2F(I)) .EQ. 3) THEN
            ISTATUS(IS2F(I)) = 6
         ELSE IF (ISTATUS(IS2F(I)) .EQ. 4) THEN
            ISTATUS(IS2F(I)) = 6
         ENDIF
      ENDIF
   ENDIF
ENDDO

RETURN
END

















