SUBROUTINE FMTRIP (ITFN,I,WEIGHT)
IMPLICIT NONE
!----------
! FIRE-BASE $Id$
!----------
!
!  THIS FIRE/SNAGE MODEL SUBROUTINE IS USED
!  TO TRIPLE THE FIRE/SNAG ATTRIBUTES
!
!  CALLED BY :
!     TRIPLE  [PROGNOSIS]
!
!  CALLS     :
!     FMATV
!
!  PARAMETERS :
!     ITFN   -
!     I      -
!     WEIGHT -
!
!OMMONS
!
INCLUDE 'PRGPRM.f90'
INCLUDE 'FMPARM.f90'
INCLUDE 'ARRAYS.f90'
INCLUDE 'FMCOM.f90'

INTEGER I,ITFN,JJ
REAL    WEIGHT

!     NO TRIPLING IS REQUIRED IF THE FIRE/SNAG MODEL IS ABSENT

IF (.NOT. LFMON) RETURN

FMPROB(ITFN) = FMPROB(I) * WEIGHT
FMICR(ITFN)  = FMICR(I)

OLDHT(ITFN)  = OLDHT(I)
OLDCRL(ITFN) = OLDCRL(I)
GROW(ITFN) = GROW(I)

DO JJ = 0, 5
  OLDCRW(ITFN, JJ) = OLDCRW(I, JJ)
  CROWNW(ITFN, JJ) = CROWNW(I, JJ)
ENDDO

RETURN
END

