SUBROUTINE VOLS
IMPLICIT NONE
!----------
! VLS $Id$
!----------
!
!  THIS SUBROUTINE CALCULATES TREE VOLUMES AND COMPUTES
!  DISTRIBUTION AND COMPOSITION VECTORS FOR VOLUME AND ACCRETION.
!
!  NATCRS, OCFVOL, AND OBFVOL ARE ENTRY POINTS IN SUBROUTINE
!  **VARVOL**, WHICH IS VARIANT SPECIFIC.
!----------
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'COEFFS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'OUTCOM.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'VOLSTD.f90'
!
!
!OMMONS
!
!----------
!  DIMENSIONS FOR INTERNAL VARIABLES.
!
!  SPCCC -- TOTAL  CUBIC VOLUME BY SPECIES AND TREE CLASS.
!  SPCAC -- TOTAL  CUBIC VOLUME ACCRETION BY SPECIES AND TREE CLASS.
!  SPCMC -- MERCH CUBIC VOLUME BY SPECIES AND TREE CLASS.
!  SPCSC -- TOTAL SAWLOG CUBIC VOLUME BY SPECIES AND TREE CLASS.
!  SPCBV -- MERCH SAWLOG BOARD VOLUME BY SPECIES AND TREE CLASS.
!
!  THESE VALUES DO NOT INCLUDE CYCLE 0 DEAD TREES.
!  IPASS=1 FOR LIVE TREES;  IPASS=2 FOR CYCLE 0 DEAD TREES.
!
!  BTKFLG - LOGICAL VARIABLES TO INDICATE WHETHER THE VOLUME ESTIMATE
!  CTKFLG   NEEDS TO BE ADJUSTED FOR TOPKILL OR NOT:
!           BTKFLG FOR SAWLOG VOLUME (CUBIC AND BOARD FT)
!           CTKFLG FOR CUBIC PULPWOOD VOLUME
!           .TRUE.  = ADJUST ESTIMATE FOR TOPKILL
!           .FALSE. = NO ADJUSTMENT NEEDED (ALREADY ACCOUNTED FOR).
!
!  VN   = TOTAL MERCH CUBIC FOOT VOLUME (PULPWOOD + SAWLOG CUBIC)
!  VM   = SAWLOG CUBIC FOOT VOLUME
!  BBFV = SAWLOG BOARD FOOT VOLUME
!
!   UPON EXITING THIS ROUTINE:
!   CFV = CARRIES TOTAL MERCH VOLUME IN EASTERN VARIANTS.  THIS IS
!         COMPOSED OF PULPWOOD CUBIC AND SAWLOG CUBIC.
!   WK1 = CARRIES SAWLOG CUBIC FOOT VOLUME.
!   BFV = CARRIES SAWLOG BOARD FOOT VOLUME.
!
!   PULPWOOD CUBIC VOLUME IS CALCULATED AS CFV()-WK1().
!----------
INTEGER DLIEQN,DLLMOD,FOREST
LOGICAL DEBUG
REAL SPCCC(MAXSP,3),SPCAC(MAXSP,3),SPCBV(MAXSP,3),SPCMC(MAXSP,3)
REAL SPCSC(MAXSP,3)
REAL DBHCLS(9)
INTEGER I,J,IPASS,ILOW,IHI,ISPC,IT,IM,ICDF,IBDF
REAL P,D,H,BARK,BRATIO,D2H,VN,VM,VMAX,BBFV,TEMCFI,TEMVOL,ALGSLP
REAL VOLCOR,PULPV,BFMAX
REAL TCF, MCF, SCF
LOGICAL TKILL,LCONE,BTKFLG,CTKFLG
!----------
!  INITIALIZE DBH CLASSES.
!----------
DATA DBHCLS/0.0,5.0,10.0,15.0,20.0,25.0,30.0,35.0,40.0/
!-----------
!  CHECK FOR DEBUG.
!-----------
CALL DBCHK (DEBUG,'VOLS',4,ICYC)
DO J=1,2
  DO I=1,MAXTRE
    HT2TD(I,J)=0.
  ENDDO
ENDDO
IF (ITRN.LE.0) GOTO 2
DO I=1,MAXSP
  DO J=1,3
    SPCCC(I,J)=0.0
    SPCAC(I,J)=0.0
    SPCMC(I,J)=0.0
    SPCSC(I,J)=0.0
    SPCBV(I,J)=0.0
  ENDDO
ENDDO
2 CONTINUE
IPASS=1
ILOW=1
IHI=ITRN
!----------
!  CALL VOLKEY TO PROCESS KEYWORDS USED TO CHANGE VOLUME STANDARDS AND
!  EQUATIONS.
!----------
CALL VOLKEY (DEBUG)
IF (ITRN.LE.0) GOTO 205
!----------
!  SET THE FOREST CODE
!----------
SELECT CASE (VARACD)
!
  CASE ('SN')
    FOREST=(KODFOR-80000)/100
!
  CASE DEFAULT
    FOREST = KODFOR-900
!
END SELECT
!----------
!  ENTER TREE BY TREE LOOP TO CALCULATE VOLUMES AND COMPILE
!  SUMMARY ARRAYS.
!
!  I -- SUBSCRIPT TO TREE RECORD.
!  P -- NUMBER OF TREES PER ACRE REPRESENTED BY TREE I.
!  D -- DIAMETER OF TREE I.
!  H -- HEIGHT OF TREE I.
!  ISPC -- SPECIES OF TREE I.
!  WK5 -- ARRAY CONTAINING TOTAL ANNUAL MERCH CUBIC VOLUME ACCRETION
!    PER ACRE FOR EACH TREE.  THIS ARRAY IS NOT LOADED
!    IF LSTART IS TRUE.
!  VN -- USED TO TEMPORARILY STORE TOTAL MERCH CUBIC VOLUME FOR TREE I.
!----------
10 CONTINUE
DO 200 I=ILOW,IHI
WK5(I)=0.0
P=PROB(I)
IF(P.LE.0.0) GO TO 200
ISPC=ISP(I)
D=DBH(I)
H = HT(I)
!----------
!  INITIALIZE TOP KILL FLAG FOR NEXT TREE; IF TOPKILLED, ASSIGN H TO
!  NORMHT.
!----------
TKILL = H.GE.4.5 .AND. ITRUNC(I).GT.0
IF(TKILL) H=NORMHT(I)/100.0
!----------
!  IF NOT INITIAL SUMMARY, ADD DG TO DBH; ASSIGN D2H.
!----------
BARK=BRATIO(ISPC,D,H)
IF(.NOT.LSTART) D=D+DG(I)/BARK
D2H=D*D*H
!**************************************************
!        TOTAL MERCH VOLUME SECTION               *
!**************************************************
!----------
!  INITIALIZE VOLUME ESTIMATES.
!----------
VN=0.
VM=0.
VMAX=0.
BFMAX=0.

TCF=0.
MCF=0.
SCF=0.
BBFV=0.
IF(DEBUG)WRITE(JOSTND,*)' CUBIC SECTION, I,ISPC,METHC= ', &
   I,ISPC,METHC(ISPC)
!----------
!  CALCULATE TOTAL MERCH CUBIC VOLUME. CORRECT FOR TOP KILL IF NEEDED.
!----------
IT=I
IF((METHC(ISPC).EQ.5) .OR. &
      (METHC(ISPC).EQ.6) .OR. &
      (METHC(ISPC).EQ.10)) THEN
  CALL NATCRS (TCF,MCF,SCF,BBFV,ISPC,D,H,TKILL,BARK,ITRUNC(I), &
                  VMAX,BFMAX,CTKFLG,BTKFLG,IT)
ELSEIF (METHC(ISPC).EQ.8) THEN
  CALL OCFVOL (VN,VM,ISPC,D,H,TKILL,BARK,ITRUNC(I),VMAX,LCONE, &
                  CTKFLG,IT)
ELSE
  CALL CFVOL (ISPC,D,H,D2H,VN,VM,VMAX,TKILL,LCONE,BARK,ITRUNC(I), &
                 CTKFLG)
ENDIF
IF(CTKFLG .AND. TKILL .AND. VMAX .GT. 0.) &
    CALL CFTOPK (ISPC,D,H,TCF,MCF,SCF,VMAX,LCONE,BARK,ITRUNC(I))
!----------
!  LOAD WK1 WITH MERCH CUBIC SAWLOG VOLUME PER TREE.
!----------
 WK1(I)=VM
 MCFV(I)=MCF
 SCFV(I)=SCF
!----------
!  SUMMARIZE VOLUME BY SPECIES AND TREE CLASS.  IF LSTART IS
!  FALSE, LOAD WK5 AND SUMMARIZE ACCRETION BY SPECIES AND TREE
!  CLASS. DO NOT DO THIS FOR CYCLE 0 DEAD TREES.
!----------
IF(IPASS .EQ. 2) GO TO 15
IM=IMC(I)
!----------
!  STORE LAST CYCLE CFV CORRECTED FOR DEFECT FOR USE LATER IN
!  COMPUTING ACCRETION.
!----------
TEMCFI=CFV(I)
!
SPCCC(ISPC,IM)=SPCCC(ISPC,IM)+TCF*P
!----------
!  LOAD CFV WITH TOTAL CUBIC VOLUME PER TREE.
!  WK1 CONTAINS THE MERCH CUBIC SAWLOG VOLUME PER TREE.
!----------
15 CONTINUE
CFV(I)=TCF
 TEMVOL=CFV(I)-WK1(I)
ICDF= DEFECT(I)/1000000
IF(CFV(I).GT.0.0 .AND. LCVOLS) THEN
!----------
!       COMPUTE DEFECT CORRECTION FACTOR FOR CUBIC FOOT PULPWOOD VOLUME.
!       TAKE LARGEST OF 1) INPUT CF DEFECT PERCENT, 2) COMPUTED LINEAR
!       INTERPOLATION VALUE, OR 3) COMPUTED LOG-LINEAR MODEL VALUE.
!----------
  DLIEQN=NINT(ALGSLP(D,DBHCLS,CFDEFT(1,ISPC),9) * 100.)
  IF(DLIEQN.GT.ICDF) ICDF=DLIEQN
  IF(CFLA0(ISPC).EQ.0.0 .AND. CFLA1(ISPC).EQ.1.0) THEN
     VOLCOR=TEMVOL
    VOLCOR=MCFV(I)
  ELSE
    VOLCOR=EXP(CFLA0(ISPC)+CFLA1(ISPC)*ALOG(MCFV(I)))
  ENDIF
  IF(MCFV(I) .EQ. 0.)GO TO 20
  DLLMOD=NINT(((MCFV(I)-VOLCOR)/MCFV(I)) * 100.)
  IF(DLLMOD.GT.ICDF) ICDF=DLLMOD
20   CONTINUE
  IF(ICDF.GT.99) ICDF=99
  IF(ICDF.LT. 0) ICDF= 0
ENDIF
!----------
!  CALL ECON EXTENSION TO PROCESS VOLUME INFORMATION
!----------
IF (MCFV(I) .GT. 0.0) CALL ECVOL(IT,LOGDIA,LOGVOL,.TRUE.)
!
!**************************************************
!        BOARD FOOT SAWLOG VOLUME SECTION         *
!**************************************************
!----------
!  COMPUTE SCRIBNER BOARD FOOT VOLUME TO A VARIABLE TOP FOR TREES
!  OF MINIMUM MERCHANTABLE DBH AND LARGER.
!----------
BFV(I)=0.0
IBDF= DEFECT(I)/10000 - (DEFECT(I)/1000000)*100
IF(D.LT.BFMIND(ISPC).OR.D.LE.BFTOPD(ISPC)) GO TO 150
!----------
!   CALCULATE SCRIBNER BOARD FOOT VOLUME.
!   NOTE: METHODS 6 AND 9 GIVE SAME ANSWERS IN EASTERN VARIANTS
!         METHOD 9 IS FOR INTERNATIOAL BF VOLUMES, AND WE CURRENTLY
!         DONT RETURN THOSE FROM VARVOL IN THE EAST.
!----------
IF(DEBUG)WRITE(JOSTND,*)' BOARD SECTION, I,ISPC,D,H,METHB= ', &
   I,ISPC,D,H,METHB(ISPC)
!
IF(METHB(ISPC).EQ.5 .OR. &
      METHB(ISPC).EQ.6 .OR. &
      METHB(ISPC).EQ.9) THEN
  IF(METHC(ISPC).EQ.6 .OR. METHC(ISPC).EQ.10) THEN
    GO TO 100
  ELSE
  CALL NATCRS (TCF,MCF,SCF,BBFV,ISPC,D,H,TKILL,BARK,ITRUNC(I), &
                  VMAX,BFMAX,CTKFLG,BTKFLG,IT)
  ENDIF
ELSEIF (METHB(ISPC).EQ.8) THEN
  IT=I
  CALL OBFVOL (BBFV,ISPC,D,H,TKILL,BARK,ITRUNC(I),BFMAX,LCONE, &
                  BTKFLG,IT)
ELSE
  CALL BFVOL (ISPC,D,H,D2H,BBFV,TKILL,LCONE,BARK,BFMAX,ITRUNC(I), &
                 BTKFLG)
ENDIF
!----------
!  CORRECT FOR TOPKILL IF NEEDED.
!  LOAD BFV WITH SCRIBNER BOARD FOOT VOLUME CORRECTED FOR TOPKILL.
!----------
100 CONTINUE
IF(BTKFLG .AND. TKILL .AND. BFMAX .GT. 0.) &
    CALL BFTOPK (ISPC,D,H,BBFV,LCONE,BARK,BFMAX,ITRUNC(I))
BFV(I)=BBFV
IF(BFV(I).GT.0.0 .AND. LBVOLS) THEN
!----------
!     COMPUTE DEFECT CORRECTION FACTOR FOR BOARD FOOT VOLUME.
!     TAKE LARGEST OF 1) INPUT BF DEFECT PERCENT, 2) COMPUTED LINEAR
!     INTERPOLATION BF VALUE, OR 3) COMPUTED LOG-LINEAR MODEL BF VALUE.
!----------
  DLIEQN=NINT(ALGSLP(D,DBHCLS,BFDEFT(1,ISPC),9) * 100.)
  IF(DLIEQN.GT.IBDF)IBDF=DLIEQN
  IF(BFLA0(ISPC).EQ.0.0 .AND. BFLA1(ISPC).EQ.1.0) THEN
    VOLCOR=BFV(I)
  ELSE
    VOLCOR=EXP(BFLA0(ISPC)+BFLA1(ISPC)*ALOG(BFV(I)))
  ENDIF
  DLLMOD=NINT(((BFV(I)-VOLCOR)/BFV(I)) * 100.)
  IF(DLLMOD.GT.IBDF)IBDF=DLLMOD
  IF(IBDF.GT.99)IBDF=99
  IF(IBDF.LT. 0)IBDF= 0
ENDIF
!----------
!  CALL ECON EXTENSION TO PROCESS VOLUME INFORMATION
!----------
IF (BFV(I) .GT. 0.0) CALL ECVOL(IT,LOGDIA,LOGVOL,.FALSE.)
!
!----------
!  RESET NEGATIVE VOLUMES TO ZERO, ADJUST FOR DEFECT, AND COMPILE TOTAL.
!  CONSIDER 99% DEFECT AS 100% DEFECT.
!  AT THIS POINT:
!     CFV = TOTAL MERCH CUBIC VOLUME (SAWLOG CUBIC + PULPWOOD CUBIC)
!     WK1 = MERCH CUBIC SAWLOG VOLUME PER TREE
!     BFV = MERCH BOARD SAWLOG VOLUME PER TREE
!  DEFINE:
!   PULPV = PULPWOOD VOLUME PER TREE
!----------
150 CONTINUE
IF(BFV(I).LT.0.) BFV(I)=0.
IF(CFV(I).LT.0.) CFV(I)=0.
IF(MCFV(I).LT.0.) MCFV(I)=0.
IF(SCFV(I).LT.0.) SCFV(I)=0.
 PULPV=CFV(I)-WK1(I)
!----------
!     CORRECT PULPWOOD CUBIC VOLUME FOR FORM AND DEFECT.
!     CONSIDER 99% DEFECT AS 100% DEFECT.
!----------
IF(ICDF.LT.99) THEN
  MCFV(I)=MCFV(I)*(1.-FLOAT(ICDF)/100.)
ELSE
  MCFV(I)=0.
ENDIF
!----------
!     CORRECT MERCHANTABLE BOARD FOOT VOLUME FOR FORM AND DEFECT.
!     CONSIDER 99% DEFECT AS 100% DEFECT.
!----------
IF(IBDF.LT.99) THEN
  BFV(I)=BFV(I)*(1.-FLOAT(IBDF)/100.)
   WK1(I)=WK1(I)*(1.-FLOAT(IBDF)/100.)
ELSE
  BFV(I)=0.
   WK1(I)=0.
ENDIF
!----------
!     RESET THE TOTAL MERCH CUBIC TO THE CORRECTED SUM
!     AND COMPUTE ACCRETION
!----------
 CFV(I)=PULPV+WK1(I)
IF(.NOT.LSTART) THEN
  IF(TEMCFI.GT.CFV(I))THEN
    WK5(I)=0.
  ELSE
      WK5(I)=(CFV(I)-TEMCFI)*P/FINT
  ENDIF
  SPCAC(ISPC,IM)=SPCAC(ISPC,IM)+WK5(I)
ENDIF
!
IF(IPASS .EQ. 1) SPCBV(ISPC,IM)=SPCBV(ISPC,IM)+BFV(I)*P
IF(IPASS .EQ. 1) SPCMC(ISPC,IM)=SPCMC(ISPC,IM)+WK1(I)*P
!----------
!  SET VALUES IN CODED DEFECT NUMBER TO INDICATE THE ACTUAL DEFECT
!  PERCENTAGES APPLIED THIS CYCLE.
!  DEFECT CODED AS 11223344, WHERE 11=INPUT MC DEFECT %, 22=INPUT BF
!  DEFECT PERCENT, 33=MC DEFECT % USED THIS CYCLE, 44=BF DEFECT % USED
!  THIS CYCLE.
!----------
DEFECT(I)=((DEFECT(I)/10000)*10000) + ICDF*100 + IBDF
IF(DEBUG)WRITE(JOSTND,*)' IN VOLS, I= ',I,' DEFECT= ',DEFECT(I)
!----------
!  PRINT DEBUG OUTPUT IF DESIRED
!----------
IF(.NOT.DEBUG) GO TO 200
WRITE(JOSTND,9000)I,VN,WK1(I),WK5(I),CFV(I), &
        SPCAC(ISPC,1),SPCAC(ISPC,2),SPCAC(ISPC,3),SPCCC(ISPC,1), &
        SPCCC(ISPC,2),SPCCC(ISPC,3),ISPC,D,H
9000 FORMAT(' IN VOLS, I=',I4,' VN=',E15.6,' WK1=',E15.6,/, &
     '  WK5=',E15.6,' CFV=',E15.6, &
     ' SPCAC=',3(E15.6,',')/'  SPCCC=',3(E15.6,','),' ISPC=',I2, &
     ' DBH=',E11.2,' NORMAL HT=',E11.2)
!----------
!  END OF TREE LOOP.
!----------
200 CONTINUE
205 CONTINUE
IF(IPASS .EQ. 2) GO TO 250
!----------
!  DETERMINE SPECIES-TREE CLASS COMPOSITION FOR ALL VOLUME STANDARDS.
!----------
CALL COMP(OSPCV,IOSPCV,SPCCC)
CALL COMP(OSPBV,IOSPBV,SPCBV)
CALL COMP(OSPMC,IOSPMC,SPCMC)
CALL COMP(OSPSC,IOSPSC,SPCSC)
!----------
!  DETERMINE SPECIES-TREE CLASS COMPOSITION AND PERCENTILE POINTS IN
!  THE DISTRIBUTION OF DIAMETERS FOR ANNUAL TOTAL CUBIC FOOT ACCRETION.
!  BYPASS IF LSTART IS TRUE.
!----------
IF(LSTART) GO TO 210
CALL COMP(OSPAC,IOSPAC,SPCAC)
CALL PCTILE(ITRN,IND,WK5,WK3,OACC(7))
CALL DIST(ITRN,OACC,WK3)
210 CONTINUE
!----------
!  CALCULATE VOLUMES FOR CYCLE 0 DEAD TREES.
!----------
IF(IREC2 .GT. MAXTRE) GO TO 250
IPASS=2
ILOW=IREC2
IHI=MAXTRE
GO TO 10
!----------
!  END OF VOLS.
!----------
250 CONTINUE
RETURN
END
