SUBROUTINE ESINIT
IMPLICIT NONE
!----------
! ESTB $Id$
!----------
!     CALLED FROM INITRE, ONLY ONCE, TO INITIALIZE REGEN. MODEL.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'ESPARM.f90'
!
!
INCLUDE 'ESCOMN.f90'
!
!
INCLUDE 'ESHAP.f90'
!
!
INCLUDE 'ESHAP2.f90'
!
!
INCLUDE 'ESRNCM.f90'
!
!
INCLUDE 'ESWSBW.f90'
!
!
!OMMONS
!
INTEGER NSTK,I,KODE,JSTND
REAL X
CHARACTER*256 CNAME
EQUIVALENCE (NSTK,SUMPRB)
LOGICAL LTEMP,LKECHO
DO 10 I=1,MAXSP
HTADJ(I)=0.0
XESMLT(I)=1.0
10 CONTINUE
ITRNRM=0
NSTK=0
NBWHST=0
STOADJ=1.0
CONFID=5.0
LINGRW=.TRUE.
LAUTAL=.TRUE.
LSPRUT=.TRUE.
IPRINT=1
INADV=0
LOAD=0
IBLK=0
MINREP=50
KDTOLD=-99
IPINFO=0
NTALLY=0
IDSDAT=-9999
IYRLRM=-9999
XTES=0.0
THRES1=0.10
THRES2=0.30
CALL ESRNSD (.FALSE.,X)
NPTIDS=0
INQUIRE (UNIT=JOREGT,OPENED=LTEMP)
CNAME=TRIM(KWDFIL)//'_RegenRpt.txt'
!        CALL MYOPEN (JOREGT,CNAME,4,133, 0,1,1,0,KODE)
CALL MYOPEN (JOREGT,CNAME,1,133, 0,1,1,0,KODE)
IF(KODE.GT.0) WRITE(*,'(''OPEN FAILED FOR '',I4)') JOREGT
RETURN
!
!     CALLED FROM INITRE WHEN NOTREES KEYWORD IS ENTERED.
!
ENTRY ESEZCR (JSTND,LKECHO)
INADV=1
IF(LKECHO)WRITE(JSTND,30)
30 FORMAT(T12,'(EZCRUISE OPTION IN REGENERATION ESTABLISHMENT ', &
     'MODEL IS AUTOMATICALLY INVOKED.)'  )
RETURN
END
