SUBROUTINE ESOUT (LFG)
IMPLICIT NONE
!----------
! ESTB $Id$
!----------
!
!     PART OF THE ESTABLISHMENT MODEL SUBSYSTEM.  COPIES THE
!     PRINT DATA FROM FILE JOREGT TO JOSTND. CALLED FROM MAIN.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'ESHAP.f90'
!
!
INCLUDE 'ESHAP2.f90'
!
!
!OMMONS
!
INTEGER ISTLNB, ISTAT, ICOUNT
CHARACTER*132 RECORD
LOGICAL LFG,LL
!
!     IF NO OUTPUT IS ASKED FOR (IPRINT = 0), DO NOT OPEN THE FILE.
!
IF (IPRINT.EQ.0 .OR. JOREGT.EQ.JOSTND) RETURN
!
!     IS FILE OPENED?
!
INQUIRE(UNIT=JOREGT,OPENED=LL)
IF (.NOT.LL) RETURN
!
!     REWIND THE ESTAB OUTPUT FILE.
!
ENDFILE JOREGT
REWIND JOREGT
!
!     COPY THE FILE TO THE PRINTER.
!
10 CONTINUE
READ (JOREGT,20,END=40) RECORD
20 FORMAT (A)
IF (.NOT.LFG) THEN
   LFG=.TRUE.
   WRITE (JOSTND,30)
30    FORMAT (132('-'))
ENDIF

IF (RECORD.NE.' ') THEN
   WRITE (JOSTND,20) RECORD(1:MAX0(1,ISTLNB(RECORD)))
ELSE
   WRITE (JOSTND,20)
ENDIF
GOTO 10
40 CONTINUE
!
!     PREPARE THE FILE FOR THE NEXT STAND.
!
!      REWIND JOREGT
CLOSE (JOREGT, STATUS="DELETE",IOSTAT=ISTAT)
ICOUNT=0
DO WHILE (ISTAT /= 0)
  ICOUNT = ICOUNT + 1
  CALL SLEEP(1)
  CLOSE (JOREGT, STATUS="DELETE",IOSTAT=ISTAT)
  IF(ICOUNT .GE. 10) THEN
    WRITE(*,*) 'ATTEMPT TO CLOSE FILE AT ESOUT LINE 60 FAILED'
    EXIT
  END IF
END DO
RETURN
END
