SUBROUTINE ESPLT1 (ITREI,IMC1,NPNVRS,IPVARS)
IMPLICIT NONE
!----------
! ESTB $Id$
!----------
!
!     CALLED BY INTREE TO PASS PLOT SPECIFIC VARIABLES TO THE
!     ESTABLISHMENT MODEL.
!
!     ITREI = PLOT IDENTIFICATION.
!     IMC1  = MANAGEMENT CODE, 8=NONSTOCKABLE.
!     NPNVRS= THE NUMBER OF PLOT SITE VARIABLES PASSED.
!     IPVARS= A VECTOR OF PLOT SPECIFIC SITE ATTRIBUTES.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ESHAP.f90'
!
!
INCLUDE 'ESHAP2.f90'
!
!
!OMMONS
!
INTEGER IMC1,ITREI,NPNVRS,IPVARS(NPNVRS),NSID(MAXPLT),NSTK,I
INTEGER IRTNCD
!
!     WARNING: ESB1 AND SUMPRB ARE BOTH MEMBERS OF /ESHAP2/ ... THEY
!              ARE BEING USED TO PASS DATA FROM ESPLT1 TO ESPLT2.
!
EQUIVALENCE (NSID,ESB1),(NSTK,SUMPRB)
!
!     IF PLOT DATA ALREADY READ USING PLOTINFO OPTION, THEN:
!     BRANCH TO CHECK THE STOCKABILITY STATUS OF THIS PLOT.
!
IF (IPINFO.EQ.1) GOTO 20
!
!     ELSE: SAVE THE PLOT STOCKABILITY.
!
NPTIDS=NPTIDS+1
!
!     IF TOO MANY POINTS, ERROR.
!
IF (NPTIDS.GT.MAXPLT) CALL ERRGRO(.FALSE.,13)
CALL fvsGetRtnCode(IRTNCD)
IF (IRTNCD.NE.0) RETURN
!
!     SAVE THE PLOT IDENTIFICATION.
!
IPTIDS(NPTIDS)=ITREI
!
!     IF THIS IS A NON-STOCKABLE PLOT, THEN INDICATE BY SETTING THE SITE
!     PREP CODE EQUAL -1.
!
IPPREP(NPTIDS)=0
IF (IMC1.NE.8) GOTO 10
IPPREP(NPTIDS)=-1
RETURN
10 CONTINUE
!
!     IF PLOT VARIABLES ARE NOT BEING PASSED, THEN: RETURN.
!
IF (NPNVRS.LE.1) RETURN
IPINFO=2
PSLO(NPTIDS)=FLOAT(IPVARS(1))
PASP(NPTIDS)=FLOAT(IPVARS(2))
IPHAB(NPTIDS)=IPVARS(3)
IPHYS(NPTIDS)=IPVARS(4)
IPPREP(NPTIDS)=IPVARS(5)
RETURN
20 CONTINUE
!
!     THE SITE DATA HAS BEEN READ USING PLOTINFO.  CHECK THE
!     STOCKABILITY OF THIS PLOT.
!
IF (IMC1.NE.8) RETURN
!
!     PLOT IS NONSTOCKABLE, FIND THE PLOT ID CODE AND CHANGE THE
!     SITE PREP CODE TO -1 INDICATING THAT THE POINT IS NONSTOCKABLE.
!
DO 30 I=1,NPTIDS
IF (IPTIDS(I).NE.ITREI) GOTO 30
IPPREP(I)=-1
RETURN
30 CONTINUE
!
!     IF YOU CAN'T FIND THE PLOT ID, THEN: SAVE IT IN A LIST OF
!     NONSTOCKABLE IDS.
!
NSTK=NSTK+1
NSID(NSTK)=ITREI
RETURN
END
