SUBROUTINE BFVOL(ISPC,D,H,D2H,BBFV,TKILL,LCONE,BARK,VMAX,ITHT, &
                    BTKFLG)
IMPLICIT NONE
!----------
! CR $Id$
!----------
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'COEFFS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'OUTCOM.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'VOLSTD.f90'
!
!
!OMMONS
!
!  ************** BOARD FOOT MERCHANTABILITY SPECIFICATIONS ********
!
!  BFVOL CALCULATES BOARD FOOT VOLUME OF ANY TREE LARGER THAN A MINIMUM
!  DBH SPECIFIED BY THE USER.  MINIMUM DBH CAN VARY BY SPECIES,
!  BUT CANNOT BE LESS THAN 2 INCHES.  MINIMUM MERCHANTABLE DBH IS
!  SET WITH THE BFVOLUME KEYWORD.  FOR METHB = 1-4 MERCHANTABLE
!  TOP DIAMETER CAN BE SET TO ANY VALUE BETWEEN 2 IN. AND MINIMUM DBH.
!  MINIMUM DBH AND TOP DIAMETER ARE ASSUMED TO BE MEASURED OUTSIDE
!  BARK--IF DIB IS DESIRED, ALLOW FOR DOUBLE BARK THICKNESS IN
!  SPECIFICATIONS.
!
!  VOLUME CAN BE COMPUTED BY FORMULA (METHB=1 OR 2) OR BY APPLYING THE
!  REGION 6 LOG RULES (METHB=3 OR 4).
!
!  FOR METHB=1 KEMP'S EQUATIONS ARE USED.  KEMP'S EQUATIONS IMPLY
!  SPECIFIC MERCHANTABILITY STANDARDS WHICH ARE:
!  STANDARDS (9" MINIMUM DBH, 8" MINIMUM TOP DIAMETER, AND 1' STUMP).
!  VOLUME ABOVE THE 8" TOP IS IGNORED.
!
!  ALL PARAMETERS IN THE KEMP EQUATION FORM CAN BE REPLACED BY THE
!  USER WITH THE BFVOLEQU KEYWORD.  IF A USER ENTERS THEIR OWN EQUATION
!  IT IS ASSUMED TO APPLY FROM THE STUMP TO THE MERCH TOP.
!
!  DEFAULT COEFFICIENTS FOR THE KEMP EQUATIONS ARE LOADED IN BLKDAT.
!  VARIANTS OTHER THAN NORTH IDAHO MAY HAVE DEFAULT COEFFICIENTS FOR
!  THE KEMP EQUATION FORM, BUT THEY AREN'T KEMP'S EQUATIONS. IN THIS
!  CASE THE KEMP MERCHANTABILITY STANDARDS STATED ABOVE DO NOT APPLY.
!
!  VOLUME LOSS DUE TO TOP DAMAGE (TKILL=.TRUE.) IS ESTIMATED WITH A
!  BEHRE HYPERBOLA TAPER MODEL, WITH PARAMETERS ESTIMATED FROM TOTAL
!  CUBIC FOOT VOLUME, HEIGHT AND DIAMETER.
!
!  FOR METHB=3 OR 4, BOTH TOTAL VOLUME AND VOLUME LOSS DUE TO TOP
!  DAMAGE ARE COMPUTED WITH THE LOG RULE.
!----------
LOGICAL LOGOK,LCONE,TKILL,BTKFLG
REAL SMDIA(20),GLOGLN(20)
REAL COFBVS(MAXSP),D2HBRK(MAXSP)
REAL VMAX,BARK,BBFV,D2H,H,D,TSIZE
REAL HTRUNC,TD,DIB,FC,SMDOLD,TLOG,XLOG,SMD,PLEFT,D1SQ,FACTOR
INTEGER ITHT,ISPC,NUMLOG,I,INC,ITD,LAST
REAL RDANUW
LOGICAL LDANUW
!
DATA D2HBRK/ MAXSP*0. /
DATA COFBVS/ MAXSP*0. /
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
RDANUW = VMAX
LDANUW = LCONE
!----------
!  INITIALIZE VOLUME ESTIMATE.
!----------
BBFV=0.0
!----------
!  TRANSFER TO STATEMENT 300 TO PROCESS WESTERN SIERRA LOG RULES.
!  (METHB=5)
!----------
IF(METHB(ISPC).EQ.5) GO TO 300
!----------
!  TRANSFER TO STATEMENT 100 TO PROCESS REGION 6 LOG RULES.
!  (METHB= 3 OR 4).
!----------
IF(METHB(ISPC).EQ.3 .OR. METHB(ISPC).EQ.4) GO TO 100
!----------
!  ASSIGN TRANSITION SIZE.
!----------
TSIZE=D
IF(IBTRAN(ISPC).GT.0) TSIZE=D2H
!
IF(TSIZE.GE.BTRAN(ISPC)) GO TO 20
!
BBFV = BFVEQS(1,ISPC) &
        + BFVEQS(2,ISPC)*D &
        + BFVEQS(3,ISPC)*D*H &
        + BFVEQS(4,ISPC)*D2H &
        + BFVEQS(5,ISPC)*D**BFVEQS(6,ISPC)*H**BFVEQS(7,ISPC)
GO TO 30
20 CONTINUE
BBFV = BFVEQL(1,ISPC) &
        + BFVEQL(2,ISPC)*D &
        + BFVEQL(3,ISPC)*D*H &
        + BFVEQL(4,ISPC)*D2H &
        + BFVEQL(5,ISPC)*D**BFVEQL(6,ISPC)*H**BFVEQL(7,ISPC)
!----------
!  THE FOLLOWING PIECE OF FOOLISHNESS (J.E.B.) IS REQUIRED
!  BY NATIONAL FOREST SCALING AND CRUISING RULES.  BE CAREFUL IF
!  YOU BUY A CORRAL POLE SALE BASED ON A SCRIBNER CRUISE VOLUME.
!----------
30 CONTINUE
IF(BBFV.LT.10.0 .AND. BBFV.NE.0.) BBFV=10.0
!----------
!  SET TOPKILL FLAG AND RETURN.
!----------
BTKFLG = .TRUE.
RETURN
!
!
!
!----------
!  METHB = 3 OR 4:  VOLUME COMPUTED USING ONE OF THE REGION 6 LOG
!  RULES.  MINIMUM DBH FOR LOG RULE IS 4 INCHES.
!----------
100 CONTINUE
IF (D.LT. BFMIND(ISPC)) RETURN
!----------
!  LOAD HTRUNC AND H FOR TOP DAMAGED TREES.
!----------
HTRUNC=0.0
IF(TKILL) HTRUNC=ITHT/100.0
!----------
!  CALL **FORMCL** TO DETERMINE FORM CLASS
!----------
TD=BFTOPD(ISPC)*BARK
DIB=D*BARK
CALL FORMCL(ISPC,IFOR,D,FC)
!----------
!  CALL **RXDIBS** TO COMPUTE NUMBER OF 16FT LOGS AND EACH SMALL-
!  END DIB
!----------
CALL RXDIBS(D,FC,H,TD,SMDIA,GLOGLN,NUMLOG,JOSTND)
!----------
!  INITIALIZE:
!     TLOG=CUMULATIVE LENGTH OF LOGS ALREADY PROCESSED.
!     LOGOK=SET TO FALSE WHEN LOG CONTAINING BROKEN TOP IS PROCESSED.
!----------
SMDOLD=DIB
TLOG=0.0
LOGOK=.TRUE.
IF(METHB(ISPC).EQ.4) GO TO 200
!----------
!  REGION 6 EAST SIDE VOLUME (16 FOOT LOGS).  BRANCH TO STATEMENT 200
!  FOR WESTSIDE CALCULATIONS (32 FOOT LOGS).
!----------
DO 110 I = 1,NUMLOG
!----------
!  EXIT LOOP IF LAST LOG INCLUDED A BROKEN TOP.
!----------
IF(.NOT.LOGOK) GO TO 120
XLOG=GLOGLN(I)
SMD=SMDIA(I)
!----------
!  SET FLAG AND ADJUST THE TOP DIAMETER AND LOG LENGTH IF THIS LOG
!  CONTAINS A DEAD TOP.
!----------
IF(TKILL .AND. (TLOG+XLOG).GT.HTRUNC) THEN
  PLEFT=(HTRUNC-TLOG)/XLOG
  IF(PLEFT.LE.0.0) GO TO 120
  XLOG=HTRUNC-TLOG
  D1SQ=SMDOLD*SMDOLD
  SMD=SQRT(D1SQ-PLEFT*(D1SQ-SMD*SMD))
  LOGOK=.FALSE.
ENDIF
CALL SCALEF(SMD,XLOG,FACTOR,JOSTND)
TLOG=TLOG+XLOG
BBFV=BBFV+XLOG*FACTOR
SMDOLD=SMD
110 CONTINUE
120 CONTINUE
RETURN
!
!
!
!----------
!  REGION 6 WESTSIDE VOLUME.  32 FOOT LOGS; PROCESS EVERY OTHER LOG.
!----------
200 CONTINUE
I=0
INC=2
205 CONTINUE
I=I+INC
!----------
!  EXIT LOOP IF LAST LOG INCLUDED A BROKEN TOP.
!----------
IF(.NOT.LOGOK) GO TO 220
IF(INC .EQ. 2) THEN
  XLOG=GLOGLN(I)+GLOGLN(I-1)
ELSE
  XLOG=GLOGLN(I)
ENDIF
SMD=SMDIA(I)
!----------
!  SET FLAG AND ADJUST THE TOP DIAMETER AND LOG LENGTH IF THIS LOG
!  CONTAINS A DEAD TOP.
!----------
IF(TKILL .AND. (TLOG+XLOG).GT.HTRUNC) THEN
  PLEFT=(HTRUNC-TLOG)/XLOG
  IF(PLEFT.LE.0.0) GO TO 220
  XLOG=HTRUNC-TLOG
  D1SQ=SMDOLD*SMDOLD
  SMD=SQRT(D1SQ-PLEFT*(D1SQ-SMD*SMD))
  LOGOK=.FALSE.
ENDIF
CALL SCALEF(SMD,XLOG,FACTOR,JOSTND)
TLOG=TLOG+XLOG
BBFV=BBFV+XLOG*FACTOR
SMDOLD=SMD
IF(I .LT. NUMLOG) THEN
  LAST = NUMLOG - I
  IF(LAST .EQ. 1) INC=1
  GO TO 205
ENDIF
220 CONTINUE
RETURN
!----------
!  WESTERN SIERRA LOG RULES.
!----------
300 CONTINUE
ITD=INT(BFTOPD(ISPC)+0.5)
IF(ITD.GT.100) ITD=100
CALL LOGS(D,H,ITD,BFMIND(ISPC),ISPC,BFSTMP(ISPC),BBFV)
BTKFLG = .TRUE.
RETURN
!
END
