SUBROUTINE CROWN
IMPLICIT NONE
!----------
! CR $Id$
!----------
!  THIS SUBROUTINE IS USED TO DUB MISSING CROWN RATIOS AND
!  COMPUTE CROWN RATIO CHANGES.
!  THIS ROUTINE IS CALLED FROM **CRATET** TO DUB
!  MISSING VALUES, AND BY **TREGRO** TO COMPUTE CHANGE DURING
!  REGULAR CYCLING.  ENTRY **CRCONS** IS CALLED BY **RCON** TO
!  LOAD MODEL CONSTANTS THAT ARE SITE DEPENDENT AND NEED ONLY
!  BE RESOLVED ONCE.  PROCESSING OF
!  CROWN CHANGE FOR SMALL TREES IS CONTROLLED BY **REGENT**.
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE  'ARRAYS.f90'
!
!
INCLUDE  'COEFFS.f90'
!
!
INCLUDE  'CONTRL.f90'
!
!
INCLUDE  'GGCOM.f90'
!
!
INCLUDE  'OUTCOM.f90'
!
!
INCLUDE  'PLOT.f90'
!
!
INCLUDE  'PDEN.f90'
!
!
INCLUDE  'VARCOM.f90'
!
!
!OMMONS
!
REAL CRNMLT(MAXSP),DLOW(MAXSP),DHI(MAXSP),CRNEW(MAXTRE),PRM(5)
INTEGER ICFLG(MAXSP),MYACTS(1)
INTEGER NTODO,I,NP,IACTK,IDATE,IDT,ISPCC,IGRP,IULIM,IG,IGSP,ISPC
INTEGER I1,I2,I3,ICLS,ICRI,JJ
REAL D,H,PCTI,TBAU,HF,DF,BRATIO,CR,CHG,PDIFPY,CRLN,CRMAX,HN,HD,CL
DATA MYACTS/81/
LOGICAL DEBUG
!-----------
!  SEE IF WE NEED TO DO SOME DEBUG.
!-----------
CALL DBCHK (DEBUG,'CROWN',5,ICYC)
IF(DEBUG) WRITE(JOSTND,3)ICYC
3 FORMAT(' ENTERING SUBROUTINE CROWN CYCLE =',I5)
!----------
! INITIALIZE CROWN VARIABLES TO BEGINNING OF CYCLE VALUES.
!----------
CALL BADIST(DEBUG)
IF(LSTART)THEN
  DO 10 JJ=1,MAXTRE
    CRNEW(JJ)=0.0
10   CONTINUE
ENDIF
!----------
!  DUB CROWNS ON DEAD TREES IF NO LIVE TREES IN INVENTORY
!----------
IF((ITRN.LE.0).AND.(IREC2.LT.MAXTP1))GO TO 74
!----------
! IF THERE ARE NO TREE RECORDS, THEN RETURN
!----------
IF(ITRN.EQ.0)THEN
  RETURN
ELSEIF(TPROB.LE.0.0)THEN
  DO I=1,ITRN
  ICR(I)=ABS(ICR(I))
  ENDDO
  RETURN
ENDIF
!-----------
!  PROCESS CRNMULT KEYWORD.
!-----------
CALL OPFIND(1,MYACTS,NTODO)
IF(NTODO .EQ. 0)GO TO 25
DO 24 I=1,NTODO
CALL OPGET(I,5,IDATE,IACTK,NP,PRM)
IDT=IDATE
CALL OPDONE(I,IDT)
ISPCC=INT(PRM(1))
!----------
!  ISPCC<0 CHANGE FOR ALL SPECIES IN THE SPECIES GROUP
!  ISPCC=0 CHANGE FOR ALL SPEICES
!  ISPCC>0 CHANGE THE INDICATED SPECIES
!----------
IF(ISPCC .LT. 0)THEN
  IGRP = -ISPCC
  IULIM = ISPGRP(IGRP,1)+1
  DO 21 IG=2,IULIM
  IGSP = ISPGRP(IGRP,IG)
  IF(PRM(2) .GE. 0.0)CRNMLT(IGSP)=PRM(2)
  IF(PRM(3) .GT. 0.0)DLOW(IGSP)=PRM(3)
  IF(PRM(4) .GT. 0.0)DHI(IGSP)=PRM(4)
  IF(PRM(5) .GT. 0.0)ICFLG(IGSP)=1
21   CONTINUE
ELSEIF(ISPCC .EQ. 0)THEN
  DO 22 ISPCC=1,MAXSP
  IF(PRM(2) .GE. 0.0)CRNMLT(ISPCC)=PRM(2)
  IF(PRM(3) .GT. 0.0)DLOW(ISPCC)=PRM(3)
  IF(PRM(4) .GT. 0.0)DHI(ISPCC)=PRM(4)
  IF(PRM(5) .GT. 0.0)ICFLG(ISPCC)=1
22   CONTINUE
ELSE
  IF(PRM(2) .GE. 0.0)CRNMLT(ISPCC)=PRM(2)
  IF(PRM(3) .GT. 0.0)DLOW(ISPCC)=PRM(3)
  IF(PRM(4) .GT. 0.0)DHI(ISPCC)=PRM(4)
  IF(PRM(5) .GT. 0.0)ICFLG(ISPCC)=1
ENDIF
24 CONTINUE
25 CONTINUE
IF(DEBUG)WRITE(JOSTND,9024)ICYC,CRNMLT
9024 FORMAT(/' IN CROWN 9024 ICYC,CRNMLT= ', &
    I5/((1X,11F6.2)/))
!----------
!  ENTER THE LOOP FOR SPECIES DEPENDENT VARIABLES
!----------
DO 70 ISPC=1,MAXSP
I1 = ISCT(ISPC,1)
IF(I1 .EQ. 0) GO TO 70
I2 = ISCT(ISPC,2)
DO 60 I3=I1,I2
I = IND1(I3)
!----------
!  IF THIS IS THE INITIAL ENTRY TO 'CROWN' AND THE TREE IN QUESTION
!  HAS A CROWN RATIO ASCRIBED TO IT, THE WHOLE PROCESS IS BYPASSED.
!----------
IF(LSTART .AND. ICR(I).GT.0)GOTO 60
!----------
!  IF ICR(I) IS NEGATIVE, CROWN RATIO CHANGE WAS COMPUTED IN A
!  PEST DYNAMICS EXTENSION.  SWITCH THE SIGN ON ICR(I) AND BYPASS
!  CHANGE CALCULATIONS.
!----------
IF (LSTART) GOTO 40
IF (ICR(I).GE.0) GO TO 40
ICR(I)=-ICR(I)
IF (DEBUG) WRITE (JOSTND,35) I,ICR(I)
35 FORMAT (' ICR(',I4,') WAS CALCULATED ELSEWHERE AND IS ',I4)
GOTO 60
40 CONTINUE
D=DBH(I)
H=HT(I)
PCTI = PCT(I)
ICLS = INT(D+1.0)
IF(ICLS .GT. 41) ICLS=41
TBAU = BAU(ICLS)
HF = H + HTG(I)
DF = D + DG(I)/BRATIO(ISP(I),DBH(I),HF)
IF(DF .LT. D) DF=D
!----------
!   CALL GEMCR TO CALCULATE CROWN RATIO.
!----------
CALL GEMCR(IMODTY,ISPC,CR,TBAU,BA,HF,DF,H,RELDEN,PCTI)
CRNEW(I) = CR*100.
!----------
!  COMPUTE THE CHANGE IN CROWN RATIO
!  CALC THE DIFFERENCE BETWEEN THE MODEL AND THE OLD(OBS)
!  LIMIT CHANGE TO 1% PER YEAR
!----------
IF(LSTART .OR. ICR(I).EQ.0) GO TO 9052
CHG=CRNEW(I) - ICR(I)
PDIFPY=CHG/REAL(ICR(I))/FINT
IF(PDIFPY.GT.0.01)CHG=REAL(ICR(I))*(0.01)*FINT
IF(PDIFPY.LT.-0.01)CHG=REAL(ICR(I))*(-0.01)*FINT
IF(DEBUG)WRITE(JOSTND,9020)I,CRNEW(I),ICR(I),PDIFPY,CHG
9020 FORMAT(/' IN CROWN 9020 I,CRNEW,ICR,PDIFPY,CHG =', &
   I5,F10.3,I5,3F10.3)
IF(DBH(I) .GE. DLOW(ISPC) .AND. DBH(I) .LE. DHI(ISPC))THEN
  CRNEW(I) = REAL(ICR(I)) + CHG * CRNMLT(ISPC)
ELSE
  CRNEW(I) = REAL(ICR(I)) + CHG
ENDIF
9052 ICRI = INT(CRNEW(I)+0.5)
IF(LSTART .OR. ICR(I).EQ.0)THEN
  IF(DBH(I).GE.DLOW(ISPC) .AND. DBH(I).LE.DHI(ISPC)) &
     ICRI = INT(REAL(ICRI) * CRNMLT(ISPC))
ENDIF
!----------
! CALC CROWN LENGTH NOW
!----------
IF(LSTART .OR. ICR(I).EQ.0)GO TO 55
CRLN=HT(I)*REAL(ICR(I))/100.
!----------
! CALC CROWN LENGTH MAX POSSIBLE IF ALL HTG GOES TO NEW CROWN
!----------
CRMAX=(CRLN+HTG(I))/(HT(I)+HTG(I))*100.0
IF(DEBUG)WRITE(JOSTND,9004)CRMAX,CRLN,ICRI,I,CRNEW(I),CHG
9004 FORMAT(' CRMAX=',F10.2,' CRLN=',F10.2, &
   ' ICRI=',I10,' I=',I5,' CRNEW=',F10.2,' CHG=',F10.3)
!----------
! IF NEW CROWN EXCEEDS MAX POSSIBLE LIMIT IT TO MAX POSSIBLE
!----------
IF(ICRI.GT.CRMAX) ICRI=INT(CRMAX+0.5)
IF(ICRI.LT.10 .AND. CRNMLT(ISPC).EQ.1.0)ICRI=INT(CRMAX+0.5)
!----------
!  REDUCE CROWNS OF TREES  FLAGGED AS TOP-KILLED ON INVENTORY
!----------
55 IF (.NOT.LSTART .OR. ITRUNC(I).EQ.0) GO TO 59
HN=REAL(NORMHT(I))/100.0
HD=HN-REAL(ITRUNC(I))/100.0
CL=(REAL(ICRI)/100.)*HN-HD
ICRI=INT((CL*100./HN)+.5)
IF(DEBUG)WRITE(JOSTND,9030)I,ITRUNC(I),NORMHT(I),HN,HD,ICRI,CL
9030 FORMAT(' IN CROWN 9030 I,ITRUNC,NORMHT,HN,HD,ICRI,CL = ', &
    3I5,2F10.3,I5,F10.3)
!----------
!  BALANCING ACT BETWEEN TWO CROWN MODELS OCCURS HERE
!  END OF CROWN RATIO CALCULATION LOOP.  BOUND CR ESTIMATE AND FILL
!  THE ICR VECTOR.
!----------
59 CONTINUE
IF(ICRI.GT.95) ICRI=95
IF (ICRI .LT. 10 .AND. CRNMLT(ISPC).EQ.1) ICRI=10
IF(ICRI.LT.1)ICRI=1
ICR(I)= ICRI
60 CONTINUE
IF(LSTART .AND. ICFLG(ISPC).EQ.1)THEN
  CRNMLT(ISPC)=1.0
  ICFLG(ISPC)=0
ENDIF
70 CONTINUE
74 CONTINUE
!----------
!  DUB MISSING CROWNS ON CYCLE 0 DEAD TREES.
!----------
IF(IREC2 .GT. MAXTRE) GO TO 80
DO 79 I=IREC2,MAXTRE
IF(ICR(I) .GT. 0) GO TO 79
ISPC=ISP(I)
D=DBH(I)
H=HT(I)
PCTI=PCT(I)
ICLS=INT(D+1.0)
IF(ICLS .GT. 41)ICLS=41
TBAU = BAU(ICLS)
CALL GEMCR(IMODTY,ISPC,CR,TBAU,BA,H,D,H,RELDEN,PCTI)
ICRI=INT(CR*100.)
IF(ITRUNC(I).EQ.0) GO TO 78
HN=REAL(NORMHT(I))/100.0
HD=HN-REAL(ITRUNC(I))/100.0
CL=(REAL(ICRI)/100.)*HN-HD
ICRI=INT((CL*100./HN)+.5)
78 CONTINUE
IF(ICRI.GT.95) ICRI=95
IF (ICRI .LT. 10) ICRI=10
ICR(I)= ICRI
79 CONTINUE
!
80 CONTINUE
IF(DEBUG)WRITE(JOSTND,9010)ITRN,(ICR(JJ),JJ=1,ITRN)
9010 FORMAT(' LEAVING CROWN 9010 ITRN,ICR= ',I10,/, &
    43(1H ,32I4,/))
IF(DEBUG)WRITE(JOSTND,90)ICYC
90 FORMAT(' LEAVING SUBROUTINE CROWN CYCLE =',I5)
RETURN
ENTRY CRCONS
!----------
!  ENTRY POINT FOR LOADING CROWN RATIO MODEL COEFFICIENTS
!----------
DATA CRNMLT/MAXSP*1.0/
DATA ICFLG/MAXSP*0/
DATA DLOW/MAXSP*0.0/
DATA DHI/MAXSP*99.0/
RETURN
END
