BLOCK DATA CUBRDS
IMPLICIT NONE
!----------
! CR $Id$
!----------
!  DEFAULT PARAMETERS FOR THE CUBIC AND BOARD FOOT VOLUME EQUATIONS.
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'VOLSTD.f90'
!
!
!OMMONS
!----------
!  SPECIES ORDER:
!   1=AF,  2=CB,  3=DF,  4=GF,  5=WF,  6=MH,  7=RC,  8=WL,  9=BC, 10=LM,
!  11=LP, 12=PI, 13=PP, 14=WB, 15=SW, 16=UJ, 17=BS, 18=ES, 19=WS, 20=AS,
!  21=NC, 22=PW, 23=GO, 24=AW, 25=EM, 26=BK, 27=SO, 28=PB, 29=AJ, 30=RM,
!  31=OJ, 32=ER, 33=PM, 34=PD, 35=AZ, 36=CI, 37=OS, 38=OH
!
!  SPECIES EXPANSION:
!  UJ,AJ,RM,OJ,ER USE CR JU
!  NC,PW USE CR CO
!  GO,AW,EM,BK,SO USE CR OA
!  PB USES CR AS
!  PM,PD,AZ USE CR PI
!  CI USES CR PP
!----------
!  COEFFICIENTS FOR CUBIC FOOT VOLUME FOR TREES THAT ARE SMALLER THAN
!  THE TRANSITION SIZE. 1 ROW PER SPECIES, EACH ROW HAS 7 COEFFS.
!----------
DATA CFVEQS/ 266*0.0 /
!----------
!  COEFFICIENTS FOR CUBIC FOOT VOLUME FOR TREES THAT ARE LARGER THAN
!  THE TRANSITION SIZE. 1 ROW PER SPECIES, EACH ROW HAS 7 COEFFS.
!----------
DATA CFVEQL/ 266*0.0 /
!----------
!  FLAG IDENTIFYING THE SIZE TRANSITION VARIABLE; 0=D, 1=D2H
!  1 PER SPECIES.
!----------
DATA ICTRAN/ 38*0 /
!----------
!  TRANSITION SIZE.  TREES OF LARGER SIZE (D OR D2H) WILL COEFFICIENTS
!  FOR LARGER SIZE TREES.  1 PER SPECIES.
!----------
DATA CTRAN/ 38*0.0 /
!----------
!  COEFFICIENTS FOR BOARD FOOT VOLUME FOR TREES THAT ARE SMALLER THAN
!  THE TRANSITION SIZE. 1 ROW PER SPECIES, 7 COEFFS PER ROW.
!----------
DATA BFVEQS/ 266*0.0 /
!----------
!  COEFFICIENTS FOR BOARD FOOT VOLUME FOR TREES THAT ARE LARGER THAN
!  THE TRANSITION SIZE. 1 ROW PER SPECIES, 7 COEFFS PER ROW.
!----------
DATA BFVEQL/ 266*0.0 /
!----------
!  FLAG IDENTIFYING THE SIZE TRANSITION VARIABLE; 0=D, 1=D2H
!  1 PER SPECIES.
!----------
DATA IBTRAN/ 38*0 /
!----------
!  TRANSITION SIZE.  TREES OF LARGER SIZE (D OR D2H) WILL USE
!  COEFFICIENTS FOR LARGER SIZE TREES.  1 PER SPECIES.
!----------
DATA BTRAN/ 38*0.0 /
END
