SUBROUTINE REGENT(LESTB,ITRNIN)
IMPLICIT NONE
!----------
! CR $Id$
!----------
!  THIS SUBROUTINE COMPUTES HEIGHT AND DIAMETER INCREMENTS FOR
!  SMALL TREES. HEIGHT INCREMENT IS A FUNCTION OF SITE INDEX,
!  TOP HEIGHT, AND STAND CROWN COMPETITION FACTOR.  DIAMETER IS
!  ASSIGNED FROM A HEIGHT-DIAMETER FUNCTION; INCREMENT IS COMPUTED
!  BY SUBTRACTION.
!  THIS ROUTINE IS CALLED FROM **CRATET** DURING CALIBRATION AND
!  FROM **TREGRO** DURING CYCLING.  ENTRY **REGCON** IS CALLED FROM
!  **RCON** TO LOAD MODEL PARAMETERS THAT NEED ONLY BE RESOLVED ONCE.
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'CALCOM.f90'
!
!
INCLUDE 'COEFFS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'OUTCOM.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'HTCAL.f90'
!
!
INCLUDE 'MULTCM.f90'
!
!
INCLUDE 'ESTCOR.f90'
!
!
INCLUDE 'PDEN.f90'
!
!
INCLUDE 'VARCOM.f90'
!
!
INCLUDE 'GGCOM.f90'
!
!
!OMMONS
!----------
!  DIMENSIONS FOR INTERNAL VARIABLES:
!
!   CORTEM -- A TEMPORARY ARRAY FOR PRINTING CORRECTION TERMS.
!   NUMCAL -- A TEMPORARY ARRAY FOR PRINTING NUMBER OF HEIGHT
!             INCREMENT OBSERVATIONS BY SPECIES.
!    RHCON -- CONSTANT FOR THE HEIGHT INCREMENT MODEL.  ZERO FOR ALL
!             SPECIES IN THIS VARIANT
!     XMAX -- UPPER END OF THE RANGE OF DIAMETERS OVER WHICH HEIGHT
!             INCREMENT PREDICTIONS FROM SMALL AND LARGE TREE MODELS
!             ARE AVERAGED.
!     XMIN -- LOWER END OF THE RANGE OF DIAMETERS OVER WHICH HEIGHT
!             INCREMENT PREDICTIONS FROM THE SMALL AND LARGE TREE
!             ARE AVERAGED.
!    HTADJ -- SPECIES SPECIFIC ADJUSTMENT FACTOR TO POTENTIAL
!             HEIGHT CALCULATON
!----------
EXTERNAL RANN
LOGICAL DEBUG,LESTB,LSKIPH
REAL CORTEM(MAXSP),XMAX(MAXSP),XMIN(MAXSP),AB(9),DGMAX(MAXSP)
REAL DIAM(MAXSP),HTADJ(MAXSP)
INTEGER NUMCAL(MAXSP),MPCC(MAXSP),IVFLAG
!
REAL D,H,BARK,RAN,HTGR,ZZRAN
REAL XWT,HK,REGYR,FNT,SCALE
REAL SCALE2,XRHGRO,XRDGRO,CON,XMX,XMN
REAL BRATIO,BACHLO,DK,DKK,DDS,HTNEW,SCALE3,CORNEW,SNP
REAL SNX,SNY,EDH,P,TERM,CCF,AVHT,X,PCTRED,BKPT,SI,RELSI,RSIMOD
REAL POTHTG,CR,AG1,HITE1,HITE2,AG2,VIGOR,BX,AX,H2,DGMX
INTEGER J,IPCCF
INTEGER ITRNIN,ISPC,I1,I2,I3,I,K,L,N,IREFI,KOUT,ISPEC,KK
CHARACTER SPEC*2
!----------
!  SPECIES ORDER:
!   1=AF,  2=CB,  3=DF,  4=GF,  5=WF,  6=MH,  7=RC,  8=WL,  9=BC, 10=LM,
!  11=LP, 12=PI, 13=PP, 14=WB, 15=SW, 16=UJ, 17=BS, 18=ES, 19=WS, 20=AS,
!  21=NC, 22=PW, 23=GO, 24=AW, 25=EM, 26=BK, 27=SO, 28=PB, 29=AJ, 30=RM,
!  31=OJ, 32=ER, 33=PM, 34=PD, 35=AZ, 36=CI, 37=OS, 38=OH
!
!  SPECIES EXPANSION:
!  UJ,AJ,RM,OJ,ER USE CR JU
!  NC,PW USE CR CO
!  GO,AW,EM,BK,SO USE CR OA
!  PB USES CR AS
!  PM,PD,AZ USE CR PI
!  CI USES CR PP
!----------
!  DATA STATEMENTS.
!----------
DATA DGMAX/ &
    3.6, 3.6, 2.4, 3.6, 3.6, 3.0, 3.0, 3.0, 2.0, 2.8, &
    3.5, 2.0, 2.8, 2.8, 3.5, 2.0, 3.6, 3.6, 3.6, 2.5, &
    2.5, 2.5, 2.0, 2.0, 2.0, 2.0, 2.0, 2.5, 2.0, 2.0, &
    2.0, 2.0, 2.0, 2.0, 2.0, 2.8, 2.8, 2.5/
DATA XMAX / &
    2.0, 2.0, 2.0, 5.0, 2.0, 4.0,  5.,  5.,199., 4.0, &
    2.0,199., 2.0, 5.0, 2.0,199., 2.0, 2.0, 2.0, 2.0, &
    2.0, 2.0,199.,199.,199.,199.,199., 2.0,199.,199., &
   199.,199.,199.,199.,199., 2.0, 2.0, 2.0/
DATA XMIN/ &
    0.5, 0.5, 0.5, 2.0, 0.5, 2.0, 2.0, 2.0, 99., 0.5, &
    0.5, 99., 0.5, 2.0, 0.5, 99., 0.5, 0.5, 0.5, 0.5, &
    0.5, 0.5, 99., 99., 99., 99., 99., 0.5, 99., 99., &
    99., 99., 99., 99., 99., 0.5, 0.5, 0.5/
DATA REGYR/10.0/
DATA MPCC/ 2, 2, 1, 2, 2, 2, 1, 1, 4, 4, &
              3, 4, 4, 4, 4, 4, 5, 5, 5, 4, &
              4, 4, 4, 4, 4, 4, 4, 4, 4, 4, &
              4, 4, 4, 4, 4, 4, 4, 4/
DATA DIAM/ &
    0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.4, 0.4, &
    0.4, 0.4, 0.5, 0.4, 0.4, 0.3, 0.3, 0.3, 0.3, 0.2, &
    0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.2, 0.3, 0.3, &
    0.3, 0.3, 0.4, 0.4, 0.4, 0.5, 0.2, 0.2/
DATA AB/ &
    1.11436,-.011493,.43012E-4,-.72221E-7,.5607E-10,-.1641E-13,3*0./
DATA HTADJ/ &
    1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.10, 1.10, 1.00, 1.00, &
    1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, &
    1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, &
    1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00/
!-----------
!  CHECK FOR DEBUG.
!-----------
LSKIPH=.FALSE.
CALL DBCHK (DEBUG,'REGENT',6,ICYC)
IF(DEBUG) WRITE(JOSTND,9980)ICYC
9980 FORMAT('ENTERING SUBROUTINE REGENT  CYCLE =',I5)
!----------
!  IF THIS IS THE FIRST CALL TO REGENT, BRANCH TO STATEMENT 40 FOR
!  MODEL CALIBRATION.
!----------
IF(LSTART) GOTO 40
CALL MULTS (3,IY(ICYC),XRHMLT)
CALL MULTS(6,IY(ICYC),XRDMLT)
IF (ITRN.LE.0) GO TO 91
!----------
!  HEIGHT INCREMENT IS DERIVED FROM A HEIGHT-AGE CURVE AND IS NOMINALLY
!  BASED ON A 10-YR GROWTH PERIOD. THE VARIABLE SCALE IS USED TO CONVERT
!  HEIGHT INCREMENT PREDICTIONS TO A FINT-YEAR PERIOD.  DIAMETER
!  INCREMENT IS PREDICTED FROM CHANGE IN HEIGHT, AND IS SCALED TO A
!  10-YEAR PERIOD BY THE VARIABLE SCALE2.  DIAMETER INCREMENT
!  IS CONVERTED TO A FINT-YEAR BASIS IN **UPDATE**.
!----------
FNT=FINT
IF(LESTB) THEN
  IF(FINT.LE.5.0) THEN
    LSKIPH=.TRUE.
  ELSE
    FNT=FNT-5.0
  ENDIF
ENDIF
SCALE=FNT/REGYR
SCALE2=YR/FNT
!----------
!  IF CALLED FROM **ESTAB** INTERPOLATE MID-PERIOD CCF AND TOP HT
!  FROM VALUES AT START AND END OF PERIOD.
!----------
CCF=RELDEN
AVHT=AVH
IF(LESTB.AND.FNT.GT.0.0) THEN
  CCF=(5.0/FINT)*RELDEN +((FINT-5.0)/FINT)*ATCCF
  AVHT=(5.0/FINT)*AVH +((FINT-5.0)/FINT)*ATAVH
ENDIF
!---------
! COMPUTE DENSITY MODIFIER FROM CCF AND TOP HEIGHT.
!---------
X=AVHT*(CCF/100.0)
IF(X .GT. 300.0) X=300.0
PCTRED=AB(1) &
    + X*(AB(2) + X*(AB(3) + X*(AB(4) + X*(AB(5)+ X*AB(6)))))
IF(PCTRED .GT. 1.0) PCTRED = 1.0
IF(PCTRED .LT. 0.01) PCTRED = 0.01
IF(DEBUG) WRITE(JOSTND,9982) AVHT,CCF,X,PCTRED
9982 FORMAT('IN REGENT AVHT,CCF,X,PCTRED = ',4F10.4)
!----------
!  ENTER GROWTH PREDICTION LOOP.  PROCESS EACH SPECIES AS A GROUP;
!  LOAD CONSTANTS FOR NEXT SPECIES.
!----------
DO 30 ISPC=1,MAXSP
I1=ISCT(ISPC,1)
IF(I1.EQ.0) GO TO 30
I2=ISCT(ISPC,2)
BKPT=BREAK(ISPC)
XRHGRO=XRHMLT(ISPC)
XRDGRO=XRDMLT(ISPC)
CON=RHCON(ISPC) * EXP(HCOR(ISPC))
XMX=XMAX(ISPC)
XMN=XMIN(ISPC)
SI=SITEAR(ISPC)
IF(SI .GT. SITEHI(ISPC)) SI=SITEHI(ISPC)
IF(SI .LE. SITELO(ISPC)) SI=SITELO(ISPC) + 0.5
!----------
!  COMPUTE POTENTIAL GROWTH FROM SITE INDEX AND SPECIES.
!----------
RELSI=(SI-SITELO(ISPC))/(SITEHI(ISPC)-SITELO(ISPC))
RSIMOD = 0.5 * (1.0 + RELSI)
X=RELSI*100.0
J=MPCC(ISPC)
POTHTG = SITEAR(ISPC)/(15.0 - 4.0*RELSI) * HTADJ(ISPC)
!----------
IF(DEBUG) WRITE(JOSTND,9981) SI,RELSI,X,ISPC,J,POTHTG
9981 FORMAT('IN REGENT SI,RELSI,X,ISPC,J,POTHTG = ', &
   F7.2,F10.3,F10.4,2I6,F10.3)
!----------
!     PUT A CEILING ON DIAMETER GROWTH BASED ON OLIVER AND COCHRAN EMPR.
!     RJ 11/28/88
!----------
DGMX = DGMAX(ISPC) * SCALE
!----------
!  SET FLAG FOR VIGOR ADJUSTMENT
!----------
SELECT CASE(ISPC)
CASE(9,12,16,23:27,29:35)
  IVFLAG=1
CASE DEFAULT
  IVFLAG=0
END SELECT
!----------
!  PROCESS NEXT TREE RECORD.
!----------
DO 25 I3=I1,I2
I=IND1(I3)
D=DBH(I)
H=HT(I)
!----------
!  BYPASS INCREMENT CALCULATIONS IF CALLED FROM ESTAB AND THIS IS NOT A
!  NEWLY CREATED TREE.
!----------
IF(LESTB) THEN
  IF(I.LT.ITRNIN) GO TO 25
!----------
!  ASSIGN CROWN RATIO FOR NEWLY ESTABLISHED TREES.
!----------
  IPCCF=ITRE(I)
  CR = 0.89722 - 0.0000461*PCCF(IPCCF)
1   CONTINUE
  RAN = BACHLO(0.0,1.0,RANN)
  IF(RAN .LT. -1.0 .OR. RAN .GT. 1.0) GO TO 1
  CR = CR + 0.07985 * RAN
  IF(CR .GT. .90) CR = .90
  IF(CR .LT. .20) CR = .20
  ICR(I)=INT((CR*100.0)+0.5)
ENDIF
K=I
L=0
!----------
!     RETURN HERE TO PROCESS NEXT TRIPLE.
!----------
2 CONTINUE
!---------
! COMPUTE VIGOR MODIFIER FROM CROWN RATIO.
!---------
IF(D.GE.XMX) GO TO 25
H=HT(I)
BARK=BRATIO(ISPC,D,H)
IF(LSKIPH) THEN
  HTG(K)=0.0
  GO TO 4
ENDIF
!----------
! COMPUTE HT GROWTH AND AGE FOR ASPEN. EQN FROM WAYNE SHEPPARD RMS.
! ALSO USE FOR PAPER BIRCH
!----------
IF(ISPC.EQ.20 .OR. ISPC.EQ.28) THEN
  AG1=ABIRTH(I)
  IF(AG1.LT.5.)AG1=5.
  HITE1 = 26.9825 * AG1**1.1752
  AG2 = AG1+10.0
  HITE2 = 26.9825 * AG2**1.1752
  HTGR = (HITE2-HITE1)/(2.54*12.0) * RSIMOD * CON
!----------
! GROWTH RATES APPEAR HIGH, REDUCE BY 25 PERCENT. DIXON 8-27-92
!----------
  HTGR = HTGR * .75
  GO TO 3
ENDIF
X=FLOAT(ICR(I))/100.
VIGOR = (150.0 * (X**3.0)*EXP(-6.0*X))+0.3
IF(VIGOR .GT. 1.0)VIGOR=1.0
!----------
!  VIGOR ADJUSTMENT TO DRASTIC FOR PINYON, JUNIPER, OAK, BRISTLECONE
!  CUT IT BY TWO-THIRDS
!----------
IF(IVFLAG .EQ. 1) VIGOR=1.-((1.-VIGOR)/3.)

HTGR=POTHTG*PCTRED*VIGOR*CON
IF(DEBUG) WRITE(JOSTND,*)'POTHTG,PCTRED,VIGOR,CON,X,HTGR= ', &
    POTHTG,PCTRED,VIGOR,CON,X,HTGR
3 CONTINUE
ZZRAN = 0.0
IF(DGSD.GE.1.0) ZZRAN=BACHLO(0.0,1.0,RANN)
IF((ZZRAN .GT. 0.5) .OR. (ZZRAN .LT. -2.0)) GO TO 3
IF(DEBUG)WRITE(JOSTND,9984) HTGR,ZZRAN,XRHGRO,SCALE,WK4(I)
9984 FORMAT('IN REGENT 9984 FORMAT',5(F10.4,2X))
HTGR = (HTGR +ZZRAN*0.2)*XRHGRO * SCALE * WK4(I)
!-------------
!     COMPUTE WEIGHTS FOR THE LARGE AND SMALL TREE HEIGHT INCREMENT
!     ESTIMATES.  IF DBH IS LESS THAN OR EQUAL TO XMN, THE LARGE TREE
!     PREDICTION IS IGNORED (XWT=0.0).
!----------
XWT=(D-XMN)/(XMX-XMN)
IF(D.LE.XMN .OR. LESTB) XWT = 0.0
!----------
!     COMPUTE WEIGHTED HEIGHT INCREMENT FOR NEXT TRIPLE.
!----------
IF(DEBUG)WRITE(JOSTND,9985)XWT,HTGR,HTG(K),I,K
9985 FORMAT('IN REGENT 9985 FORMAT',3(F10.4,2X),2I7)
HTG(K)=HTGR*(1.0-XWT) + XWT*HTG(K)
IF(HTG(K) .LT. .1) HTG(K) = .1
!----------
! CHECK FOR SIZE CAP COMPLIANCE.
!----------
IF((H+HTG(K)).GT.SIZCAP(ISPC,4))THEN
  HTG(K)=SIZCAP(ISPC,4)-H
  IF(HTG(K) .LT. 0.1) HTG(K)=0.1
ENDIF
!
4 CONTINUE
!----------
!     ASSIGN DBH AND COMPUTE DBH INCREMENT FOR TREES WITH DBH LESS
!     THAN BREAKPOINT (COMPUTE 10-YEAR DBH INCREMENT REGARDLESS OF
!     PROJECTION PERIOD LENGTH).
!----------
IF(D.GE.BKPT) GO TO 23
HK=H + HTG(K)
IF(HK .LE. 4.5) THEN
  DG(K)=0.0
  DBH(K)=D+0.001*HK
ELSE
!
!  PONDEROSA PINE, CHIHUAHUA PINE
!
  IF(ISPC.EQ.13 .OR. ISPC.EQ.36) THEN
    DK=(HK-8.31485+.59200*7.)/3.03659
    IF(DK .LT. 0.1) DK=0.1
    DKK=(H-8.31485+.59200*7.)/3.03659
    IF(DKK .LT. 0.1) DKK=0.1
    IF(H .LT. 4.5) DKK=D
!
!  THE FOLLOWING FOR PINYON, JUNIPER & OAK DEVELOPED BY DIXON
!  ALSO USED FOR BRISTLECONE
!
  ELSEIF(IVFLAG .EQ. 1) THEN
    DK=(HK-4.5)*10./(SITEAR(ISPC)-4.5)
    IF(DK .LT. 0.1) DK=0.1
    DKK=(H-4.5)*10./(SITEAR(ISPC)-4.5)
    IF(DKK .LT. 0.1) DKK=0.1
    IF(H .LT. 4.5) DKK=D
!
!  ALL OTHER SPECIES
!
  ELSE
    BX=HT2(ISPC)
    IF(IABFLG(ISPC).EQ.1) THEN
      AX=HT1(ISPC)
    ELSE
      AX=AA(ISPC)
    ENDIF
    DK=(BX/(ALOG(HK-4.5)-AX))-1.0
    IF(DK .LT. 0.1) DK=0.1
    IF(H .LE. 4.5) THEN
      DKK=D
    ELSE
      DKK=(BX/(ALOG(H-4.5)-AX))-1.0
    ENDIF
    IF(DEBUG)WRITE(JOSTND,9986) AX,BX,ISPC,HK,BARK, &
                                   XRDGRO,DK,DKK
9986     FORMAT('IN REGENT 9986 FORMAT AX,BX,ISPC,HK', &
       ' BARK,XRDGRO,DK,DKK= '/T12, F10.3,2X,F10.3,2X,I5,2X,5F10.3)
  ENDIF
!----------
!         IF CALLED FROM **ESTAB** ASSIGN DIAMETER
!----------
  IF(LESTB) THEN
    DBH(K)=DK
    IF(DBH(K).LT.DIAM(ISPC)) DBH(K)=DIAM(ISPC)
    DBH(K)=DBH(K)+0.001*HK
    DG(K)=DBH(K)
  ELSE
!----------
!         COMPUTE DIAMETER INCREMENT BY SUBTRACTION, APPLY USER
!         SUPPLIED MULTIPLIERS, AND CHECK TO SEE IF COMPUTED VALUE
!         IS WITHIN BOUNDS.
!----------
    IF(DK.LT.0.0 .OR. DKK.LT.0.0)THEN
      DG(K)=HTG(K)*0.2*BARK*XRDGRO
      DK=D+DG(K)
    ELSE
      DG(K)=(DK-DKK)*BARK*XRDGRO
    ENDIF
    IF(DG(K) .LT. 0.0) DG(K)=0.0
    IF (DG(K) .GT. DGMX) DG(K)=DGMX
!----------
!         SCALE DIAMETER INCREMENT TO 10-YR ESTIMATE.
!         SCALE ADJUSTMENT IS ON GROWTH IN DDS RATHER THAN INCHES
!         OF DG TO BE CONSISTENT WITH GRADD.
!----------
    DDS = DG(K)*(2.0*BARK*D + DG(K))*SCALE2
    DG(K) = SQRT((D*BARK)**2.0 + DDS) - BARK*D
  ENDIF
  IF((DBH(K)+DG(K)).LT.DIAM(ISPC))THEN
    DG(K)=DIAM(ISPC)-DBH(K)
  ENDIF
ENDIF
!----------
!  CHECK FOR TREE SIZE CAP COMPLIANCE
!----------
CALL DGBND(ISPC,DBH(K),DG(K))
!
23 CONTINUE
!----------
!  RETURN TO PROCESS NEXT TRIPLE IF TRIPLING.  OTHERWISE,
!  PRINT DEBUG AND RETURN TO PROCESS NEXT TREE.
!----------
IF(LESTB .OR. .NOT.LTRIP .OR. L.GE.2) GO TO 22
L=L+1
K=ITRN+2*I-2+L
GO TO 2
!----------
!  END OF GROWTH PREDICTION LOOP.  PRINT DEBUG INFO IF DESIRED.
!----------
22 CONTINUE
IF(DEBUG)THEN
HTNEW=HT(I)+HTG(I)
WRITE(JOSTND,9987) I,ISPC,HT(I),HTG(I),HTNEW,DBH(I),DG(I)
9987 FORMAT('IN REGENT, I=',I4,',  ISPC=',I3,'  CUR HT=',F7.2, &
          ',  HT INC=',F7.4,',  NEW HT=',F7.2,',  CUR DBH=',F10.5, &
          ',  DBH INC=',F7.4)
ENDIF
25 CONTINUE
30 CONTINUE
GO TO 91
!----------
!  SMALL TREE HEIGHT CALIBRATION SECTION.
!----------
40 CONTINUE
DO 45 ISPC=1,MAXSP
HCOR(ISPC)=0.0
CORTEM(ISPC)=1.0
NUMCAL(ISPC)=0
45 CONTINUE
IF (ITRN.LE.0) GO TO 91
IF(IFINTH .EQ. 0)  GOTO 95
SCALE3 = REGYR / FINTH
!---------
! COMPUTE DENSITY MODIFIER FROM CCF AND TOP HEIGHT.
!---------
X=AVH*(RELDEN/100.0)
IF(X .GT. 300.0) X=300.0
PCTRED=AB(1) &
    + X*(AB(2) + X*(AB(3) + X*(AB(4) + X*(AB(5)+ X*AB(6)))))
IF(PCTRED .GT. 1.0) PCTRED = 1.0
IF(PCTRED .LT. 0.01) PCTRED = 0.01
IF(DEBUG)WRITE(JOSTND,9989)AVH,RELDEN,X,PCTRED
9989 FORMAT('IN REGENT AVH,RELDEN,X,PCTRED = ',4F10.4)
DO 100 ISPC=1,MAXSP
!----------
!  BEGIN PROCESSING TREE LIST IN SPECIES ORDER.  DO NOT CALCULATE
!  CORRECTION TERMS IF THERE ARE NO TREES FOR THIS SPECIES.
!----------
CORNEW=1.0
I1=ISCT(ISPC,1)
IF(I1.EQ.0 .OR. .NOT. LHTCAL(ISPC)) GO TO 100
N=0
SNP=0.0
SNX=0.0
SNY=0.0
I2=ISCT(ISPC,2)
IREFI=IREF(ISPC)
SI=SITEAR(ISPC)
IF(SI .GT. SITEHI(ISPC)) SI=SITEHI(ISPC)
IF(SI .LE. SITELO(ISPC)) SI=SITELO(ISPC) + 0.5
!----------
!  COMPUTE POTENTIAL HEIGHT GROWTH AS A FUNCTION OF SI AND SPECIES.
!----------
RELSI=(SI-SITELO(ISPC))/(SITEHI(ISPC)-SITELO(ISPC))
RSIMOD = 0.5 * (1.0 + RELSI)
X=RELSI*100.0
J=MPCC(ISPC)
POTHTG = SITEAR(ISPC)/(15.0 - 4.0*RELSI) * HTADJ(ISPC)
!----------
IF(DEBUG)WRITE(JOSTND,9988)SI,RELSI,X,ISPC,J,POTHTG
9988 FORMAT('IN REGENT SI,RELSI,X,ISPC,J,POTHTG = ', &
   F7.2,F10.3,F10.4,2I6,F10.3)
!----------
!  SET FLAG FOR VIGOR ADJUSTMENT
!----------
SELECT CASE(ISPC)
CASE(9,12,16,23:27,29:35)
  IVFLAG=1
CASE DEFAULT
  IVFLAG=0
END SELECT
!----------
!  BEGIN TREE LOOP WITHIN SPECIES.  IF MEASURED HEIGHT INCREMENT IS
!  LESS THAN OR EQUAL TO ZERO, OR DBH IS GREATER THAN 5.0,
!  THE RECORD WILL BE EXCLUDED FROM THE CALIBRATION.
!----------
DO 60 I3=I1,I2
I=IND1(I3)
H=HT(I)
!----------
!  DIA GT 3 INCHES INCLUDED IN OVERALL MEAN
!----------
IF(IHTG.LT.2) H=H-HTG(I)
IF(DBH(I).GE.5.0 .OR. H.LT.0.01) GO TO 60
!----------
!  COMPUTE VIGOR MODIFIER FROM CROWN RATIO.
!----------
X=FLOAT(ICR(I))/100.
VIGOR = (150.0 * (X**3.0)*EXP(-6.0*X))+0.3
IF(VIGOR .GT. 1.0)VIGOR=1.0
!----------
!  VIGOR ADJUSTMENT TO DRASTIC FOR PINYON, JUNIPER, OAK, BRISTLECONE
!  CUT IT BY TWO-THIRDS
!----------
IF(IVFLAG .EQ.1) VIGOR=1.-((1.-VIGOR)/3.)
EDH=POTHTG*PCTRED*VIGOR*RHCON(ISPC)
!----------
! COMPUTE ASPEN HTG FOR CALIBRATION. EQNS FROM WAYNE SHEPPARD RMS.
! ALSO USED FOR PAPER BIRCH
!---------
IF(ISPC.EQ.20 .OR. ISPC.EQ.28) THEN
  AG1 = (H*12.0*2.54/26.9825)**0.8509
  AG2 = AG1 + 10.0
  H2  = (26.9825*AG2**1.1752)/(2.54*12.0)
  EDH = (H2-H) * RSIMOD * RHCON(ISPC)
!----------
! GROWTH RATES APPEAR HIGH, REDUCE BY 25 PERCENT. DIXON 8-27-92.
!----------
  EDH=EDH*.75
  IF(EDH .LT. 0.0) EDH=0.0
ENDIF
IF(DEBUG)WRITE(JOSTND,9990) X,VIGOR,EDH
9990 FORMAT('IN REGENT X,VIGOR,EDH = ',3F10.4)
P=PROB(I)
IF(HTG(I).LT.0.001) GO TO 60
TERM=HTG(I) * SCALE3
SNP=SNP+P
SNX=SNX+EDH*P
SNY=SNY+TERM*P
N=N+1
!----------
!  PRINT DEBUG INFO IF DESIRED.
!----------
IF(DEBUG)WRITE(JOSTND,9991) NPLT,I,ISPC,H,DBH(I),ICR(I), &
    PCT(I),ATCCF,RHCON(ISPC),EDH,TERM
9991 FORMAT('NPLT=',A26,',  I=',I5,',  ISPC=',I3,',  H=',F6.1, &
    ',  DBH=',F5.1,',  ICR',I5,',  PCT=',F6.1,',  RELDEN=', &
    F6.1 / 12X,'RHCON=',F10.3,',  EDH=',F10.3,', TERM=',F10.3)
!----------
!  END OF TREE LOOP WITHIN SPECIES.
!----------
60 CONTINUE
IF(DEBUG) WRITE(JOSTND,9992) ISPC,SNP,SNX,SNY
9992 FORMAT(/'SUMS FOR SPECIES ',I2,':  SNP=',F10.2, &
    ';  SNX=',F10.2,';  SNY=',F10.2)
!----------
!  COMPUTE CALIBRATION TERMS.  CALIBRATION TERMS ARE NOT COMPUTED
!  IF THERE WERE FEWER THAN NCALHT (DEFAULT=5) HEIGHT INCREMENT
!  OBSERVATIONS FOR A SPECIES.
!----------
IF(N.LT.NCALHT) GO TO 80
!----------
!  CALCULATE MEANS FOR THE POPULATION AND FOR THE SAMPLE ON THE
!  NATURAL SCALE.
!----------
SNX=SNX/SNP
SNY=SNY/SNP
!----------
!  CALCULATE RATIO ESTIMATOR.
!----------
CORNEW = SNY/SNX
IF(CORNEW.LE.0.0) CORNEW=1.0E-4
HCOR(ISPC)=ALOG(CORNEW)
!----------
!  TRAP CALIBRATION VALUES OUTSIDE 2.5 STANDARD DEVIATIONS FROM THE
!  MEAN. IF C IS THE CALIBRATION TERM, WITH A DEFAULT OF 1.0, THEN
!  LN(C) HAS A MEAN OF 0.  -2.5 < LN(C) < 2.5 IMPLIES
!  0.0821 < C < 12.1825
!----------
IF(CORNEW.LT.0.0821 .OR. CORNEW.GT.12.1825) THEN
  CALL ERRGRO(.TRUE.,27)
  WRITE(JOSTND,9194)ISPC,JSP(ISPC),CORNEW
9194   FORMAT(T28,'SMALL TREE HTG: SPECIES = ',I2,' (',A3, &
     ') CALCULATED CALIBRATION VALUE = ',F8.2)
  CORNEW=1.0
  HCOR(ISPC)=0.0
ENDIF
80 CONTINUE
CORTEM(IREFI) = CORNEW
NUMCAL(IREFI) = N
100 CONTINUE
!----------
!  END OF CALIBRATION LOOP.  PRINT CALIBRATION STATISTICS AND RETURN
!----------
WRITE(JOSTND,9993) (NUMCAL(I),I=1,NUMSP)
9993 FORMAT(/'NUMBER OF RECORDS AVAILABLE FOR SCALING'/ &
          'THE SMALL TREE HEIGHT INCREMENT MODEL', &
           ((T48,11(I4,2X)/)))
95 CONTINUE
WRITE(JOSTND,9994) (CORTEM(I),I=1,NUMSP)
9994 FORMAT(/'INITIAL SCALE FACTORS FOR THE SMALL TREE'/ &
         'HEIGHT INCREMENT MODEL', &
          ((T48,11(F5.2,1X)/)))
!----------
! OUTPUT CALIBRATION TO DATABASE.
!----------
CALL DBSCALIB(2,CORTEM,NUMCAL,CORTEM) ! LAST ARG IGNORED
!----------
! OUTPUT CALIBRATION TERMS IF CALBSTAT KEYWORD WAS PRESENT.
!----------
IF(JOCALB .GT. 0) THEN
  KOUT=0
  DO 207 K=1,MAXSP
  IF(CORTEM(K).NE.1.0 .OR. NUMCAL(K).GE.NCALHT) THEN
    SPEC=NSP(MAXSP,1)(1:2)
    ISPEC=MAXSP
    DO 203 KK=1,MAXSP
    IF(K .NE. IREF(KK)) GO TO 203
    ISPEC=KK
    SPEC=NSP(KK,1)(1:2)
    GO TO 2031
203     CONTINUE
2031     WRITE(JOCALB,204)ISPEC,SPEC,NUMCAL(K),CORTEM(K)
204     FORMAT(' CAL: SH',1X,I2,1X,A2,1X,I4,1X,F6.3)
    KOUT = KOUT + 1
  ENDIF
207   CONTINUE
  IF(KOUT .EQ. 0)WRITE(JOCALB,209)
209   FORMAT(' NO SH VALUES COMPUTED')
  WRITE(JOCALB,210)
210   FORMAT(' CALBSTAT END')
ENDIF
91 IF(DEBUG)WRITE(JOSTND,9995)ICYC
9995 FORMAT('LEAVING SUBROUTINE REGENT  CYCLE =',I5)
RETURN
ENTRY REGCON
!----------
!  ENTRY POINT FOR LOADING OF REGENERATION GROWTH MODEL
!  CONSTANTS  THAT REQUIRE ONE-TIME RESOLUTION.
!---------
DO 90 ISPC=1,MAXSP
RHCON(ISPC) = 1.0
IF(LRCOR2 .AND. RCOR2(ISPC).GT.0.0) &
     RHCON(ISPC)=RCOR2(ISPC)
90 CONTINUE
RETURN
END
