SUBROUTINE VARPUT (WK3,IPNT,ILIMIT,REALS,LOGICS,INTS)
IMPLICIT NONE
!----------
! CR $Id$
!----------
!
!     WRITE THE VARIANT SPECIFIC VARIABLES.
!
!     PART OF THE PARALLEL PROCESSING EXTENSION TO PROGNOSIS.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'GGCOM.f90'
!
!
!OMMONS
!
!     NOTE: THE ACTUAL STORAGE LIMIT FOR INTS, LOGICS, AND REALS
!     IS MAXTRE (SEE PRGPRM).
!
INTEGER ILIMIT,IPNT,MXL,MXI,MXR
PARAMETER (MXL=1,MXI=1,MXR=5)
LOGICAL LOGICS(*)
REAL WK3(MAXTRE)
INTEGER INTS(*)
REAL REALS(*)
LOGICAL LDANUW
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
LDANUW = LOGICS(1)
!----------
!
!     STORE THE INTEGER SCALARS IN THE ARRAY INTS
!
INTS ( 1) =  IGFOR
CALL IFWRIT (WK3, IPNT, ILIMIT, INTS, MXI, 2)
!
!     WRITE THE INTEGER ARRAYS
!
!     STORE THE LOGICAL SCALARS.
!
!**   CALL LFWRIT (WK3, IPNT, ILIMIT, LOGICS, MXL, 2)
!
!     STORE THE REAL SCALARS IN THE ARRAY REALS.
!
REALS( 1) =  AGERNG
REALS( 2) =  SEEDS
REALS( 3) =  TPAT
REALS( 4) =  DSTAG
REALS( 5) =  BAINIT
CALL BFWRIT (WK3, IPNT, ILIMIT, REALS, MXR, 2)
!
!     WRITE THE REAL ARRAYS
!
CALL BFWRIT (WK3, IPNT, ILIMIT, BCLAS,  MAXSP*41, 2)
CALL BFWRIT (WK3, IPNT, ILIMIT, TBA,    MAXSP,    2)
CALL BFWRIT (WK3, IPNT, ILIMIT, BAU,    41,       2)
CALL BFWRIT (WK3, IPNT, ILIMIT, BARK1,  MAXSP,    2)
CALL BFWRIT (WK3, IPNT, ILIMIT, BARK2,  MAXSP,    2)
CALL BFWRIT (WK3, IPNT, ILIMIT, DBHMAX, MAXSP,    2)
CALL BFWRIT (WK3, IPNT, ILIMIT, TCLAS,  MAXSP*41, 2)
CALL BFWRIT (WK3, IPNT, ILIMIT, BREAK,  MAXSP,    2)
CALL BFWRIT (WK3, IPNT, ILIMIT, SITELO, MAXSP,    2)
CALL BFWRIT (WK3, IPNT, ILIMIT, SITEHI, MAXSP,    2)
!
RETURN
END

SUBROUTINE VARCHPUT (CBUFF, IPNT, LNCBUF)
IMPLICIT NONE
!----------
!     Put variant-specific character data
!----------

INCLUDE 'PRGPRM.f90'

INTEGER LNCBUF
CHARACTER CBUFF(LNCBUF)
INTEGER IPNT
INTEGER IDANUW
CHARACTER CDANUW
! Stub for variants which need to get/put character data
! See /bc/varget.f and /bc/varput.f for examples of VARCHGET and VARCHPUT
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
IDANUW = IPNT
CDANUW = CBUFF(1)
!
RETURN
END
