SUBROUTINE DBSEVM (ITODO,IACTK,IDT,JOSTND)
IMPLICIT NONE
!----------
! DBS $Id$
!----------
!     PURPOSE: TO RUN SCHEDULED DBS COMMANDS
!
!     AUTH: D. GAMMEL -- RMRS -- MOSCOW MAY 2003
!           NL CROOKSTON -- RMRS -- MOSCOW
!
!
!OMMONS
!
!
INCLUDE 'DBSCOM.f90'
!
!
!OMMONS
!
CHARACTER*2000 SQLCMD
INTEGER ITODO,IACTK,IDT,IRC,KODE,JOSTND
CALL OPGETC (ITODO,SQLCMD)

IF (SQLCMD.EQ.' ') RETURN
!
!     PREPROCESS THE COMMAND STRING.
!
IRC=1
KODE=0
IF (IACTK.EQ.101) THEN          ! 101 IS SQLIN
  !SPECIFY TRUE FOR SCHEDULED
  IF(ConnHndlIn.EQ.-1) CALL DBSOPEN(DSNIN,EnvHndlIn, &
                               ConnHndlIn,DBMSIN,0,.FALSE.,KODE)
!       CHECK TO SEE IF CONNECTION WAS SUCCESSFUL
  IF (KODE.EQ.1) THEN
    WRITE (JOSTND,100)TRIM(DSNIN)
100     FORMAT(T12,'DBS ERROR: INPUT CONNECTION FAILED FOR DSN: ',A)
    RETURN
  ENDIF
  CALL DBSEXECSQL(SQLCMD,ConnHndlIn,.TRUE.,IRC)
ELSE IF (IACTK.EQ.102) THEN     ! 102 IS SQLOUT
  !SPECIFY TRUE FOR SCHEDULED
  IF(ConnHndlOut.EQ.-1) CALL DBSOPEN(DSNOUT,EnvHndlOut, &
                           ConnHndlOut,DBMSOUT,0,.FALSE.,KODE)
!       CHECK TO SEE IF CONNECTION WAS SUCCESSFUL
  IF (KODE.EQ.1) THEN
    WRITE (JOSTND,200)TRIM(DSNOUT)
200     FORMAT(T12,'DBS ERROR: OUTPUT CONNECTION FAILED FOR DSN: ',A)
    RETURN
  ENDIF
  CALL DBSEXECSQL(SQLCMD,ConnHndlOut,.TRUE.,IRC)
ENDIF
IF (IRC.EQ.0) CALL OPDONE (ITODO,IDT)
RETURN
END
