SUBROUTINE BFVOL(ISPC,D,H,D2H,BBFV,TKILL,LCONE,BARK,VMAX,ITHT, &
                    BTKFLG)
IMPLICIT NONE
!----------
! WS $Id$
!----------
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'COEFFS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'OUTCOM.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'VOLSTD.f90'
!
!
!OMMONS
!
!  ************** BOARD FOOT MERCHANTABILITY SPECIFICATIONS ********
!
!  BFVOL CALCULATES BOARD FOOT VOLUME OF ANY TREE LARGER THAN A MINIMUM
!  DBH SPECIFIED BY THE USER.  MINIMUM DBH CAN VARY BY SPECIES,
!  BUT CANNOT BE LESS THAN 2 INCHES.  MINIMUM MERCHANTABLE DBH IS
!  SET WITH THE BFVOLUME KEYWORD.  FOR METHB = 1-4 MERCHANTABLE
!  TOP DIAMETER CAN BE SET TO ANY VALUE BETWEEN 2 IN. AND MINIMUM DBH.
!  MINIMUM DBH AND TOP DIAMETER ARE ASSUMED TO BE MEASURED OUTSIDE
!  BARK--IF DIB IS DESIRED, ALLOW FOR DOUBLE BARK THICKNESS IN
!  SPECIFICATIONS.
!
!  VOLUME CAN BE COMPUTED BY FORMULA (METHB=1 OR 2) OR BY APPLYING THE
!  REGION 6 LOG RULES (METHB=3 OR 4).
!
!  FOR METHB=1 KEMP'S EQUATIONS ARE USED.  KEMP'S EQUATIONS IMPLY
!  SPECIFIC MERCHANTABILITY STANDARDS WHICH ARE:
!  STANDARDS (9" MINIMUM DBH, 8" MINIMUM TOP DIAMETER, AND 1' STUMP).
!  VOLUME ABOVE THE 8" TOP IS IGNORED.
!
!  ALL PARAMETERS IN THE KEMP EQUATION FORM CAN BE REPLACED BY THE
!  USER WITH THE BFVOLEQU KEYWORD.  IF A USER ENTERS THEIR OWN EQUATION
!  IT IS ASSUMED TO APPLY FROM THE STUMP TO THE MERCH TOP.
!
!  DEFAULT COEFFICIENTS FOR THE KEMP EQUATIONS ARE LOADED IN BLKDAT.
!  VARIANTS OTHER THAN NORTH IDAHO MAY HAVE DEFAULT COEFFICIENTS FOR
!  THE KEMP EQUATION FORM, BUT THEY AREN'T KEMP'S EQUATIONS. IN THIS
!  CASE THE KEMP MERCHANTABILITY STANDARDS STATED ABOVE DO NOT APPLY.
!
!  VOLUME LOSS DUE TO TOP DAMAGE (TKILL=.TRUE.) IS ESTIMATED WITH A
!  BEHRE HYPERBOLA TAPER MODEL, WITH PARAMETERS ESTIMATED FROM TOTAL
!  CUBIC FOOT VOLUME, HEIGHT AND DIAMETER.
!
!  FOR METHB=3 OR 4, BOTH TOTAL VOLUME AND VOLUME LOSS DUE TO TOP
!  DAMAGE ARE COMPUTED WITH THE LOG RULE.
!----------
LOGICAL LOGOK,LCONE,TKILL,BTKFLG
INTEGER ITHT,ISPC,ID,ITD,IVTD,NUMLOG,I,INC,LAST
REAL SMDIA(20),GLOGLN(20)
REAL COFBVS(MAXSP),HDRATM(100),D2HBRK(MAXSP)
REAL VMAX,BARK,BBFV,D2H,H,D,TSIZE,VT,HDRATA,DTOPK,HTRUNC,TD,DIB
REAL FC,SMDOLD,TLOG,XLOG,SMD,PLEFT,D1SQ,FACTOR
REAL RDANUW
LOGICAL LDANUW
!----------
!     SPECIES LIST FOR WESTERN SIERRAS VARIANT.
!
!     1 = SUGAR PINE (SP)                   PINUS LAMBERTIANA
!     2 = DOUGLAS-FIR (DF)                  PSEUDOTSUGA MENZIESII
!     3 = WHITE FIR (WF)                    ABIES CONCOLOR
!     4 = GIANT SEQUOIA (GS)                SEQUOIADENDRON GIGANTEAUM
!     5 = INCENSE CEDAR (IC)                LIBOCEDRUS DECURRENS
!     6 = JEFFREY PINE (JP)                 PINUS JEFFREYI
!     7 = CALIFORNIA RED FIR (RF)           ABIES MAGNIFICA
!     8 = PONDEROSA PINE (PP)               PINUS PONDEROSA
!     9 = LODGEPOLE PINE (LP)               PINUS CONTORTA
!    10 = WHITEBARK PINE (WB)               PINUS ALBICAULIS
!    11 = WESTERN WHITE PINE (WP)           PINUS MONTICOLA
!    12 = SINGLELEAF PINYON (PM)            PINUS MONOPHYLLA
!    13 = PACIFIC SILVER FIR (SF)           ABIES AMABILIS
!    14 = KNOBCONE PINE (KP)                PINUS ATTENUATA
!    15 = FOXTAIL PINE (FP)                 PINUS BALFOURIANA
!    16 = COULTER PINE (CP)                 PINUS COULTERI
!    17 = LIMBER PINE (LM)                  PINUS FLEXILIS
!    18 = MONTEREY PINE (MP)                PINUS RADIATA
!    19 = GRAY PINE (GP)                    PINUS SABINIANA
!         (OR CALIFORNIA FOOTHILL PINE)
!    20 = WASHOE PINE (WE)                  PINUS WASHOENSIS
!    21 = GREAT BASIN BRISTLECONE PINE (GB) PINUS LONGAEVA
!    22 = BIGCONE DOUGLAS-FIR (BD)          PSEUDOTSUGA MACROCARPA
!    23 = REDWOOD (RW)                      SEQUOIA SEMPERVIRENS
!    24 = MOUNTAIN HEMLOCK (MH)             TSUGA MERTENSIANA
!    25 = WESTERN JUNIPER (WJ)              JUNIPERUS OCIDENTALIS
!    26 = UTAH JUNIPER (UJ)                 JUNIPERUS OSTEOSPERMA
!    27 = CALIFORNIA JUNIPER (CJ)           JUNIPERUS CALIFORNICA
!    28 = CALIFORNIA LIVE OAK (LO)          QUERCUS AGRIFOLIA
!    29 = CANYON LIVE OAK (CY)              QUERCUS CHRYSOLEPSIS
!    30 = BLUE OAK (BL)                     QUERCUS DOUGLASII
!    31 = CALIFORNIA BLACK OAK (BO)         QUERQUS KELLOGGII
!    32 = VALLEY OAK (VO)                   QUERCUS LOBATA
!         (OR CALIFORNIA WHITE OAK)
!    33 = INTERIOR LIVE OAK (IO)            QUERCUS WISLIZENI
!    34 = TANOAK (TO)                       LITHOCARPUS DENSIFLORUS
!    35 = GIANT CHINQUAPIN (GC)             CHRYSOLEPIS CHRYSOPHYLLA
!    36 = QUAKING ASPEN (AS)                POPULUS TREMULOIDES
!    37 = CALIFORNIA-LAUREL (CL)            UMBELLULARIA CALIFORNICA
!    38 = PACIFIC MADRONE (MA)              ARBUTUS MENZIESII
!    39 = PACIFIC DOGWOOD (DG)              CORNUS NUTTALLII
!    40 = BIGLEAF MAPLE (BM)                ACER MACROPHYLLUM
!    41 = CURLLEAF MOUNTAIN-MAHOGANY (MC)   CERCOCARPUS LEDIFOLIUS
!    42 = OTHER SOFTWOODS (OS)
!    43 = OTHER HARDWOODS (OH)
!
!  SURROGATE EQUATION ASSIGNMENT:
!
!    FROM EXISTING WS EQUATIONS --
!      USE 1(SP) FOR 11(WP) AND 24(MH)
!      USE 2(DF) FOR 22(BD)
!      USE 3(WF) FOR 13(SF)
!      USE 4(GS) FOR 23(RW)
!      USE 8(PP) FOR 18(MP)
!      USE 34(TO) FOR 35(GC), 36(AS), 37(CL), 38(MA), AND 39(DG)
!      USE 31(BO) FOR 28(LO), 29(CY), 30(BL), 32(VO), 33(IO), 40(BM), AND
!                     43(OH)
!
!    FROM CA VARIANT --
!      USE CA11(KP) FOR 12(PM), 14(KP), 15(FP), 16(CP), 17(LM), 19(GP), 20(WE),
!                       25(WJ), 26(WJ), AND 27(CJ)
!      USE CA12(LP) FOR 9(LP) AND 10(WB)
!
!    FROM SO VARIANT --
!      USE SO30(MC) FOR 41(MC)
!
!    FROM UT VARIANT --
!      USE UT17(GB) FOR 21(GB)
!----------
!  DATA STATEMENTS
!  OS COEFFICIENTS FOR LP, WB, KP, FP, CP, LM, GP, WE, WJ, UJ, AND CJ
!  OH COEFFICIENTS USED FOR MC
!  USERS SHOULD BE SETTING THEIR OWN VALUES IF USING OPTIONS 2 OR 7
!----------
DATA D2HBRK/ &
      19231.8,  15763.5,  10016.7,  14883.9,  29922.0, &
       6024.9,  19425.9,  14034.0,  16917.1,  16917.1, &
      19231.8,  16917.1,  10016.7,  16917.1,  16917.1, &
      16917.1,  16917.1,  14034.0,  16917.1,  16917.1, &
       4567.8,  15763.5,  14883.9,  19231.8,  16917.1, &
      16917.1,  16917.1,   4567.8,   4567.8,   4567.8, &
       4567.8,   4567.8,   4567.8,  14883.9,  14883.9, &
      14883.9,  14883.9,  14883.9,  14883.9,   4567.8, &
      14883.9,  16917.1,   4567.8/
!
DATA HDRATM/ &
     10.0, 10.0, 9.0, 8.0, 7.8, 7.65, 7.5, 7.25, 7.0, 6.75, &
      6.5, 6.25, 18*6.0, 10*5.5, 10*5.0, 10*4.5, 10*4.0, &
     10*3.5, 10*3.0, 10*2.5/
!
DATA COFBVS/ &
     0.008423, 0.008423, 0.009523, 0.009523, 0.008421, &
     0.009523, 0.009523, 0.008423,  0.01031,  0.01031, &
     0.008423,  0.01031, 0.009523,  0.01031,  0.01031, &
      0.01031,  0.01031, 0.008423,  0.01031,  0.01031, &
      0.01031, 0.008423, 0.009523, 0.008423,  0.01031, &
      0.01031,  0.01031,  0.01031,  0.01031,  0.01031, &
      0.01031,  0.01031,  0.01031, 0.009523, 0.009523, &
     0.009523, 0.009523, 0.009523, 0.009523,  0.01031, &
     0.009523,  0.01031,  0.01031/
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
RDANUW = VMAX
LDANUW = LCONE
!
!----------
!  INITIALIZE VOLUME ESTIMATE.
!----------
BBFV=0.0
!----------
!  TRANSFER TO STATEMENT 300 TO PROCESS WESTERN SIERRA LOG RULES.
!  (METHB=5)
!----------
IF(METHB(ISPC).EQ.5) GO TO 300
!----------
!  TRANSFER TO STATEMENT 100 TO PROCESS REGION 6 LOG RULES.
!  (METHB= 3 OR 4).
!----------
IF(METHB(ISPC).EQ.3 .OR. METHB(ISPC).EQ.4) GO TO 100
!----------
!  ASSIGN TRANSITION SIZE.
!----------
TSIZE=D
IF(IBTRAN(ISPC).GT.0) TSIZE=D2H
!
!
!
!--------------------------------------------------
!  THIS SECTION OF CODE ONLY APPLIES TO CERTAIN VARIANTS.
!
VT=0.0
!
!  BYPASS ALLEN EQUATIONS FOR METHB = 2 OR 7 (USER DEFINED).
!
IF(METHB(ISPC).EQ.2 .OR. METHB(ISPC).EQ.7) GO TO 15
HDRATA=H/D
ID=INT(D-0.5)
IF(ID.GT.100) ID = 100
ITD=INT(BFTOPD(ISPC)-0.5)
IF(ITD.GT.100) ITD = 100
IF(D2H.GT.D2HBRK(ISPC)) GO TO 10
!
!  D2H LESS THAN D2H BREAKPOINT: COMPUTE TOP AND STEM VOLUME WITH
!  ALLEN-ADAMS-PRAUSA EQUATIONS.
!
VT=-COFBVS(ISPC)*(BFTOPD(ISPC)**3*HDRATM(ITD)-80.0)* &
         SQRT(HDRATA/HDRATM(ID))- &
         (BFTOPD(ISPC)**2-4.0)*0.12153
BBFV=COFBVS(ISPC)*D2H+VT
GO TO 30
!
!  D2H GREATER THAN D2H BREAKPOINT:  COMPUTE TOP VOLUME WITH ALLEN-
!  ADAMS-PRAUSA EQUATIONS AND STEM VOLUME WITH KEMP EQUATIONS.
!
10 DTOPK=0.4*D
IF(DTOPK.LT.4.0) DTOPK=4.0
IF(DTOPK.GT.8.0) DTOPK=8.0
IVTD=INT(DTOPK-0.5)
VT=COFBVS(ISPC)*SQRT(HDRATA/HDRATM(ID))*(DTOPK**3*HDRATM(IVTD) &
        -BFTOPD(ISPC)**3*HDRATM(ITD)) - &
        (DTOPK**2-BFTOPD(ISPC)**2)*0.12153
15 CONTINUE
!--------------------------------------------------
!
!
IF(TSIZE.GE.BTRAN(ISPC)) GO TO 20
!
BBFV = VT + BFVEQS(1,ISPC) &
        + BFVEQS(2,ISPC)*D &
        + BFVEQS(3,ISPC)*D*H &
        + BFVEQS(4,ISPC)*D2H &
        + BFVEQS(5,ISPC)*D**BFVEQS(6,ISPC)*H**BFVEQS(7,ISPC)
GO TO 30
20 CONTINUE
BBFV = VT + BFVEQL(1,ISPC) &
        + BFVEQL(2,ISPC)*D &
        + BFVEQL(3,ISPC)*D*H &
        + BFVEQL(4,ISPC)*D2H &
        + BFVEQL(5,ISPC)*D**BFVEQL(6,ISPC)*H**BFVEQL(7,ISPC)
!----------
!  THE FOLLOWING PIECE OF FOOLISHNESS (J.E.B.) IS REQUIRED
!  BY NATIONAL FOREST SCALING AND CRUISING RULES.  BE CAREFUL IF
!  YOU BUY A CORRAL POLE SALE BASED ON A SCRIBNER CRUISE VOLUME.
!----------
30 CONTINUE
IF(BBFV.LT.10.0) BBFV=10.0
!----------
!  SET TOPKILL FLAG AND RETURN.
!----------
BTKFLG = .TRUE.
RETURN
!
!
!
!----------
!  METHB = 3 OR 4:  VOLUME COMPUTED USING ONE OF THE REGION 6 LOG
!  RULES.  MINIMUM DBH FOR LOG RULE IS 4 INCHES.
!----------
100 CONTINUE
IF (D.LT. BFMIND(ISPC)) RETURN
!----------
!  LOAD HTRUNC AND H FOR TOP DAMAGED TREES.
!----------
HTRUNC=0.0
IF(TKILL) HTRUNC=ITHT/100.0
!----------
!  CALL **FORMCL** TO DETERMINE FORM CLASS
!----------
TD=BFTOPD(ISPC)*BARK
DIB=D*BARK
CALL FORMCL(ISPC,IFOR,D,FC)
!----------
!  CALL **RXDIBS** TO COMPUTE NUMBER OF 16FT LOGS AND EACH SMALL-
!  END DIB
!----------
CALL RXDIBS(D,FC,H,TD,SMDIA,GLOGLN,NUMLOG,JOSTND)
!----------
!  INITIALIZE:
!     TLOG=CUMULATIVE LENGTH OF LOGS ALREADY PROCESSED.
!     LOGOK=SET TO FALSE WHEN LOG CONTAINING BROKEN TOP IS PROCESSED.
!----------
SMDOLD=DIB
TLOG=0.0
LOGOK=.TRUE.
IF(METHB(ISPC).EQ.4) GO TO 200
!----------
!  REGION 6 EAST SIDE VOLUME (16 FOOT LOGS).  BRANCH TO STATEMENT 200
!  FOR WESTSIDE CALCULATIONS (32 FOOT LOGS).
!----------
DO 110 I = 1,NUMLOG
!----------
!  EXIT LOOP IF LAST LOG INCLUDED A BROKEN TOP.
!----------
IF(.NOT.LOGOK) GO TO 120
XLOG=GLOGLN(I)
SMD=SMDIA(I)
!----------
!  SET FLAG AND ADJUST THE TOP DIAMETER AND LOG LENGTH IF THIS LOG
!  CONTAINS A DEAD TOP.
!----------
IF(TKILL .AND. (TLOG+XLOG).GT.HTRUNC) THEN
  PLEFT=(HTRUNC-TLOG)/XLOG
  IF(PLEFT.LE.0.0) GO TO 120
  XLOG=HTRUNC-TLOG
  D1SQ=SMDOLD*SMDOLD
  SMD=SQRT(D1SQ-PLEFT*(D1SQ-SMD*SMD))
  LOGOK=.FALSE.
ENDIF
CALL SCALEF(SMD,XLOG,FACTOR,JOSTND)
TLOG=TLOG+XLOG
BBFV=BBFV+XLOG*FACTOR
SMDOLD=SMD
110 CONTINUE
120 CONTINUE
RETURN
!
!
!
!----------
!  REGION 6 WESTSIDE VOLUME.  32 FOOT LOGS; PROCESS EVERY OTHER LOG.
!----------
200 CONTINUE
I=0
INC=2
205 CONTINUE
I=I+INC
!----------
!  EXIT LOOP IF LAST LOG INCLUDED A BROKEN TOP.
!----------
IF(.NOT.LOGOK) GO TO 220
IF(INC .EQ. 2) THEN
  XLOG=GLOGLN(I)+GLOGLN(I-1)
ELSE
  XLOG=GLOGLN(I)
ENDIF
SMD=SMDIA(I)
!----------
!  SET FLAG AND ADJUST THE TOP DIAMETER AND LOG LENGTH IF THIS LOG
!  CONTAINS A DEAD TOP.
!----------
IF(TKILL .AND. (TLOG+XLOG).GT.HTRUNC) THEN
  PLEFT=(HTRUNC-TLOG)/XLOG
  IF(PLEFT.LE.0.0) GO TO 220
  XLOG=HTRUNC-TLOG
  D1SQ=SMDOLD*SMDOLD
  SMD=SQRT(D1SQ-PLEFT*(D1SQ-SMD*SMD))
  LOGOK=.FALSE.
ENDIF
CALL SCALEF(SMD,XLOG,FACTOR,JOSTND)
TLOG=TLOG+XLOG
BBFV=BBFV+XLOG*FACTOR
SMDOLD=SMD
IF(I .LT. NUMLOG) THEN
  LAST = NUMLOG - I
  IF(LAST .EQ. 1) INC=1
  GO TO 205
ENDIF
220 CONTINUE
RETURN
!----------
!  WESTERN SIERRA LOG RULES.
!----------
300 CONTINUE
ITD=INT(BFTOPD(ISPC)+0.5)
IF(ITD.GT.100) ITD=100
CALL LOGS(D,H,ITD,BFMIND(ISPC),ISPC,BFSTMP(ISPC),BBFV)
BTKFLG = .TRUE.
RETURN
!
END
