FUNCTION BRATIO(IS,D,H)
IMPLICIT NONE
!----------
! WS $Id$
!----------
!
! FUNCTION TO COMPUTE BARK RATIOS AS A FUNCTION OF DIAMETER AND SPECIES.
! REPLACES ARRAY BKRAT IN BASE MODEL.
!----------
!     SPECIES LIST FOR WESTERN SIERRAS VARIANT.
!
!     1 = SUGAR PINE (SP)                   PINUS LAMBERTIANA
!     2 = DOUGLAS-FIR (DF)                  PSEUDOTSUGA MENZIESII
!     3 = WHITE FIR (WF)                    ABIES CONCOLOR
!     4 = GIANT SEQUOIA (GS)                SEQUOIADENDRON GIGANTEAUM
!     5 = INCENSE CEDAR (IC)                LIBOCEDRUS DECURRENS
!     6 = JEFFREY PINE (JP)                 PINUS JEFFREYI
!     7 = CALIFORNIA RED FIR (RF)           ABIES MAGNIFICA
!     8 = PONDEROSA PINE (PP)               PINUS PONDEROSA
!     9 = LODGEPOLE PINE (LP)               PINUS CONTORTA
!    10 = WHITEBARK PINE (WB)               PINUS ALBICAULIS
!    11 = WESTERN WHITE PINE (WP)           PINUS MONTICOLA
!    12 = SINGLELEAF PINYON (PM)            PINUS MONOPHYLLA
!    13 = PACIFIC SILVER FIR (SF)           ABIES AMABILIS
!    14 = KNOBCONE PINE (KP)                PINUS ATTENUATA
!    15 = FOXTAIL PINE (FP)                 PINUS BALFOURIANA
!    16 = COULTER PINE (CP)                 PINUS COULTERI
!    17 = LIMBER PINE (LM)                  PINUS FLEXILIS
!    18 = MONTEREY PINE (MP)                PINUS RADIATA
!    19 = GRAY PINE (GP)                    PINUS SABINIANA
!         (OR CALIFORNIA FOOTHILL PINE)
!    20 = WASHOE PINE (WE)                  PINUS WASHOENSIS
!    21 = GREAT BASIN BRISTLECONE PINE (GB) PINUS LONGAEVA
!    22 = BIGCONE DOUGLAS-FIR (BD)          PSEUDOTSUGA MACROCARPA
!    23 = REDWOOD (RW)                      SEQUOIA SEMPERVIRENS
!    24 = MOUNTAIN HEMLOCK (MH)             TSUGA MERTENSIANA
!    25 = WESTERN JUNIPER (WJ)              JUNIPERUS OCIDENTALIS
!    26 = UTAH JUNIPER (UJ)                 JUNIPERUS OSTEOSPERMA
!    27 = CALIFORNIA JUNIPER (CJ)           JUNIPERUS CALIFORNICA
!    28 = CALIFORNIA LIVE OAK (LO)          QUERCUS AGRIFOLIA
!    29 = CANYON LIVE OAK (CY)              QUERCUS CHRYSOLEPSIS
!    30 = BLUE OAK (BL)                     QUERCUS DOUGLASII
!    31 = CALIFORNIA BLACK OAK (BO)         QUERQUS KELLOGGII
!    32 = VALLEY OAK (VO)                   QUERCUS LOBATA
!         (OR CALIFORNIA WHITE OAK)
!    33 = INTERIOR LIVE OAK (IO)            QUERCUS WISLIZENI
!    34 = TANOAK (TO)                       LITHOCARPUS DENSIFLORUS
!    35 = GIANT CHINQUAPIN (GC)             CHRYSOLEPIS CHRYSOPHYLLA
!    36 = QUAKING ASPEN (AS)                POPULUS TREMULOIDES
!    37 = CALIFORNIA-LAUREL (CL)            UMBELLULARIA CALIFORNICA
!    38 = PACIFIC MADRONE (MA)              ARBUTUS MENZIESII
!    39 = PACIFIC DOGWOOD (DG)              CORNUS NUTTALLII
!    40 = BIGLEAF MAPLE (BM)                ACER MACROPHYLLUM
!    41 = CURLLEAF MOUNTAIN-MAHOGANY (MC)   CERCOCARPUS LEDIFOLIUS
!    42 = OTHER SOFTWOODS (OS)
!    43 = OTHER HARDWOODS (OH)
!
!  SURROGATE EQUATION ASSIGNMENT:
!
!    FROM EXISTING WS EQUATIONS --
!      USE 1(SP) FOR 11(WP) AND 24(MH)
!      USE 2(DF) FOR 22(BD)
!      USE 3(WF) FOR 13(SF)
!      USE 8(PP) FOR 18(MP)
!      USE 34(TO) FOR 35(GC), 36(AS), 37(CL), 38(MA), AND 39(DG)
!      USE 31(BO) FOR 28(LO), 29(CY), 30(BL), 32(VO), 33(IO), 40(BM), AND
!                     43(OH)
!
!    FROM CA VARIANT --
!      USE CA11(KP) FOR 12(PM), 14(KP), 15(FP), 16(CP), 17(LM), 19(GP), 20(WE),
!                       25(WJ), 26(WJ), AND 27(CJ)
!      USE CA12(LP) FOR 9(LP) AND 10(WB)
!
!    FROM SO VARIANT --
!      USE SO30(MC) FOR 41(MC)
!
!    FROM UT VARIANT --
!      USE UT17(GB) FOR 21(GB)
!
!    GS AND RW USE RELATIONSHIPS FROM CASTLE 2019
!----------
REAL BARK1(43),BARK2(43),H,D,BRATIO,TEMD,DIB
INTEGER IMAP(43),IS,IEQN
REAL RDANUW
!
DATA BARK1/ &
    0.8863, 0.8839, 0.8911, 0.7012, 0.8374, &
    0.8967, 0.8911, 0.8967, 0.9000, 0.9000, &
    0.8863, 0.9329, 0.8911, 0.9329, 0.9329, &
    0.9329, 0.9329, 0.8967, 0.9329, 0.9329, &
    0.9625, 0.8839, 0.7012, 0.8863, 0.9329, &
    0.9329, 0.9329, 0.8374, 0.8374, 0.8374, &
    0.8374, 0.8374, 0.8374, 0.8374, 0.8374, &
    0.8374, 0.8374, 0.8374, 0.8374, 0.8374, &
    0.9000, 0.8967, 0.8374/
!
DATA BARK2/ &
        0.,     0.,     0., 1.04862,      0., &
        0.,     0.,     0.,      0.,     0., &
        0.,     0.,     0.,      0.,     0., &
        0.,     0.,     0.,      0.,     0., &
   -0.1141,     0., 1.04862,      0.,     0., &
        0.,     0.,     0.,      0.,     0., &
        0.,     0.,     0.,      0.,     0., &
        0.,     0.,     0.,      0.,     0., &
        0.,     0.,     0./
!
DATA IMAP/ 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, &
              1, 1, 1, 1, 1, 1, 1, 1, 1, 1, &
              2, 1, 3, 1, 1, 1, 1, 1, 1, 1, &
              1, 1, 1, 1, 1, 1, 1, 1, 1, 1, &
              1, 1, 1/
!----------
!  PI, JU, BS, AND OA USE EQUATIONS FROM CR MODEL TYPE 3-5
!  WB, LM, LP, OT USE EQUATIONS FROM CR VARIANT
!  ES USES THE EQUATION FROM THE CR VARIANT
!  PP USES THE EQUATION FROM THE CA VARIANT
!  WF AND AF USE THE CONSTANT RATIO FROM NI VARIANT
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
RDANUW = H
!
IEQN=IMAP(IS)
TEMD=D
IF(TEMD.LT.1.)TEMD=1.
!
IF(IEQN .EQ. 1) THEN
  BRATIO=BARK1(IS)
!
ELSEIF(IEQN .EQ. 2)THEN
  BRATIO=BARK1(IS)+BARK2(IS)*(1.0/TEMD)

! NEW GS/RW BARK RATIO RELATIONSHIP
ELSE
  DIB=BARK1(IS)*D**BARK2(IS)
  BRATIO=DIB/D
ENDIF

!  CONSTRAIN BRATIO PREDICTIONS FOR IEQN 2 AND IEQN 3
IF(IEQN .EQ. 2 .OR. IEQN .EQ. 3) THEN
  IF(BRATIO .GT. 0.99) BRATIO=0.99
  IF(BRATIO .LT. 0.80) BRATIO=0.80
ENDIF
!
RETURN
END
