SUBROUTINE CRATET
IMPLICIT NONE
!----------
! WS $Id$
!----------
!  THIS SUBROUTINE IS CALLED PRIOR TO PROJECTION.  IT HAS THE
!  FOLLOWING FUNCTIONS:
!
!    1)  CALL **RCON** TO LOAD SITE DEPENDENT MODEL COEFFICIENTS.
!    2)  REGRESSION TO ESTIMATE COEFFICIENTS OF LOCAL HEIGHT-
!        DIAMETER RELATIONSHIP.
!    3)  DUB IN MISSING HEIGHTS.
!    4)  CALL **DENSE** TO COMPUTE STAND DENSITY.
!    5)  SCALE CROWN RATIOS AND CALL **CROWN** TO DUB IN ANY MISSING
!        VALUES.
!    6)  DEFINE DG BASED ON CALIBRATION CONTROL PARAMETERS AND
!        CALL **DGDRIV** TO CALIBRATE DIAMETER GROWTH EQUATIONS.
!    7)  DELETE DEAD TREES FROM INPUT TREE LIST AND REALIGN IND1
!        AND ISCT.
!    8)  PRINT A TABLE DESCRIBING CONTROL PARAMETERS AND INPUT
!        VARIABLES.
!----------
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'COEFFS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'OUTCOM.f90'
!
!
INCLUDE 'HTCAL.f90'
!
!
INCLUDE 'VARCOM.f90'
!
!
!OMMONS
!
!----------
!  INTERNAL VARIABLES.
!
!      KNT2 -- USED TO STORE COUNTS FOR PRINTING IN CONTROL
!              SUMMARY TABLE.
!     SPCNT -- USED TO ACCUMULATE NUMBER OF TREES PER ACRE BY
!              SPECIES AND TREE CLASS FOR CALCULATION OF
!              INITIAL SPECIES-TREE CLASS COMPOSITION VECTOR.
!----------
LOGICAL DEBUG,MISSCR,TKILL
CHARACTER*4 UNDER
INTEGER IS,IM,I1,I2,I3,IPTR,ISPC,II,I,J,K1,K2,K3,K4,JJ,NH
INTEGER KNT2(MAXSP),KNT(MAXSP)
REAL SPCNT(MAXSP,3)
REAL D2,SITAGE,SITHT,AGMAX,HTMAX,HTMAX2
REAL A(6),B(6),C(6),D,H,AX,Q,SUMX,R5SI,SC,BX,XX,YY,XN
REAL AHATR5,BHATR5,CHATR5,HS,SIZE
!
DATA A/-17.7893,-17.2775,-16.5610,-15.4964,-12.4808,-14.7932/
DATA B/ 8.4685, 10.4642, 8.8542, 9.7091, 7.7915, 8.3094/
DATA C/ 7.6272, 6.2137, 7.3138, 6.4437, 7.1568, 6.9113/
!
!----------
!  INITIALIZE INTERNAL VARIABLES:
!----------
DATA UNDER/'----'/
!-----------
!     SPECIES LIST FOR WESTERN SIERRAS VARIANT.
!
!     1 = SUGAR PINE (SP)                   PINUS LAMBERTIANA
!     2 = DOUGLAS-FIR (DF)                  PSEUDOTSUGA MENZIESII
!     3 = WHITE FIR (WF)                    ABIES CONCOLOR
!     4 = GIANT SEQUOIA (GS)                SEQUOIADENDRON GIGANTEAUM
!     5 = INCENSE CEDAR (IC)                LIBOCEDRUS DECURRENS
!     6 = JEFFREY PINE (JP)                 PINUS JEFFREYI
!     7 = CALIFORNIA RED FIR (RF)           ABIES MAGNIFICA
!     8 = PONDEROSA PINE (PP)               PINUS PONDEROSA
!     9 = LODGEPOLE PINE (LP)               PINUS CONTORTA
!    10 = WHITEBARK PINE (WB)               PINUS ALBICAULIS
!    11 = WESTERN WHITE PINE (WP)           PINUS MONTICOLA
!    12 = SINGLELEAF PINYON (PM)            PINUS MONOPHYLLA
!    13 = PACIFIC SILVER FIR (SF)           ABIES AMABILIS
!    14 = KNOBCONE PINE (KP)                PINUS ATTENUATA
!    15 = FOXTAIL PINE (FP)                 PINUS BALFOURIANA
!    16 = COULTER PINE (CP)                 PINUS COULTERI
!    17 = LIMBER PINE (LM)                  PINUS FLEXILIS
!    18 = MONTEREY PINE (MP)                PINUS RADIATA
!    19 = GRAY PINE (GP)                    PINUS SABINIANA
!         (OR CALIFORNIA FOOTHILL PINE)
!    20 = WASHOE PINE (WE)                  PINUS WASHOENSIS
!    21 = GREAT BASIN BRISTLECONE PINE (GB) PINUS LONGAEVA
!    22 = BIGCONE DOUGLAS-FIR (BD)          PSEUDOTSUGA MACROCARPA
!    23 = REDWOOD (RW)                      SEQUOIA SEMPERVIRENS
!    24 = MOUNTAIN HEMLOCK (MH)             TSUGA MERTENSIANA
!    25 = WESTERN JUNIPER (WJ)              JUNIPERUS OCIDENTALIS
!    26 = UTAH JUNIPER (UJ)                 JUNIPERUS OSTEOSPERMA
!    27 = CALIFORNIA JUNIPER (CJ)           JUNIPERUS CALIFORNICA
!    28 = CALIFORNIA LIVE OAK (LO)          QUERCUS AGRIFOLIA
!    29 = CANYON LIVE OAK (CY)              QUERCUS CHRYSOLEPSIS
!    30 = BLUE OAK (BL)                     QUERCUS DOUGLASII
!    31 = CALIFORNIA BLACK OAK (BO)         QUERQUS KELLOGGII
!    32 = VALLEY OAK (VO)                   QUERCUS LOBATA
!         (OR CALIFORNIA WHITE OAK)
!    33 = INTERIOR LIVE OAK (IO)            QUERCUS WISLIZENI
!    34 = TANOAK (TO)                       LITHOCARPUS DENSIFLORUS
!    35 = GIANT CHINQUAPIN (GC)             CHRYSOLEPIS CHRYSOPHYLLA
!    36 = QUAKING ASPEN (AS)                POPULUS TREMULOIDES
!    37 = CALIFORNIA-LAUREL (CL)            UMBELLULARIA CALIFORNICA
!    38 = PACIFIC MADRONE (MA)              ARBUTUS MENZIESII
!    39 = PACIFIC DOGWOOD (DG)              CORNUS NUTTALLII
!    40 = BIGLEAF MAPLE (BM)                ACER MACROPHYLLUM
!    41 = CURLLEAF MOUNTAIN-MAHOGANY (MC)   CERCOCARPUS LEDIFOLIUS
!    42 = OTHER SOFTWOODS (OS)
!    43 = OTHER HARDWOODS (OH)
!
!  SURROGATE EQUATION ASSIGNMENT:
!
!    FROM EXISTING WS EQUATIONS --
!      USE 1(SP) FOR 11(WP) AND 24(MH)
!      USE 2(DF) FOR 22(BD)
!      USE 3(WF) FOR 13(SF)
!      USE 4(GS) FOR 23(RW)
!      USE 8(PP) FOR 18(MP)
!      USE 34(TO) FOR 35(GC), 36(AS), 37(CL), 38(MA), AND 39(DG)
!      USE 31(BO) FOR 28(LO), 29(CY), 30(BL), 32(VO), 33(IO), 40(BM), AND
!                     43(OH)
!
!    FROM CA VARIANT --
!      USE CA11(KP) FOR 12(PM), 14(KP), 15(FP), 16(CP), 17(LM), 19(GP), 20(WE),
!                       25(WJ), 26(WJ), AND 27(CJ)
!      USE CA12(LP) FOR 9(LP) AND 10(WB)
!
!    FROM SO VARIANT --
!      USE SO30(MC) FOR 41(MC)
!
!    FROM UT VARIANT --
!      USE UT17(GB) FOR 21(GB)
!----------
!  SEE IF WE NEED TO DO SOME DEBUG.
!-----------
CALL DBCHK (DEBUG,'CRATET',6,ICYC)
!-------
!  IF THERE ARE TREE RECORDS, BRANCH TO PREFORM CALIBRATION.
!-------
AX=0.
IF (ITRN.GT.0) GOTO 1
!----------
!   CALL MAICAL TO CALCULATE MAI
!----------
CALL MAICAL
CALL RCON
ONTREM(7)=0.
CALL DENSE
CALL DGDRIV
CALL REGENT(.FALSE.,1)
1 CONTINUE
DO 5 I=1,MAXSP
SPCNT(I,1)=0.0
SPCNT(I,2)=0.0
SPCNT(I,3)=0.0
IF (ISCT(I,1).EQ.0) GOTO 5
J=IREF(I)
IUSED(J)=NSP(I,1)
5 CONTINUE
IF((ITRN.LE.0).AND.(IREC2.GE.MAXTP1))GO TO 245
!----------
!  PRINT SPECIES LABELS AND NUMBER OF OBSERVATIONS IN CONTROL
!  TABLE.  THEN, RESET COUNTERS TO ZERO.
!----------
WRITE(JOSTND,'(//''CALIBRATION STATISTICS:''//)')
WRITE(JOSTND,9000) (IUSED(I), I=1,NUMSP)
9000 FORMAT ((T49,11(1X,A2,3X)/))
IF(NUMSP .LE. 11) THEN
  WRITE(JOSTND,9001) (UNDER, I=1,NUMSP)
ELSE
  WRITE(JOSTND,9001) (UNDER, I=1,11)
ENDIF
9001 FORMAT (T49,11(A4,2X))
WRITE(JOSTND,9002) (KOUNT(I), I=1,NUMSP)
9002 FORMAT(/,'NUMBER OF RECORDS PER SPECIES', &
           ((T49,11(I4,2X)/)))
DO 10 I=1,MAXSP
KNT(I)=0
KNT2(I)=0
10 CONTINUE
!----------
!   CALL MBACAL TO IDENTIFY SITE SPECIES
!----------
CALL MBACAL
!----------
!   CALL MAICAL TO CALCULATE MAI
!----------
CALL MAICAL
!----------
!  CALL **RCON** TO INITIALIZE SITE DEPENDENT MODEL COEFFICIENTS.
!----------
CALL RCON
!----------
!  CALL **RDPSRT** AND **DENSE** TO COMPUTE INITIAL STAND DENSITY
!  STATISTICS.  ONTREM(7) IS SET TO ZERO HERE TO ASSURE THAT RELDM1
!  WILL BE ASSIGNED IN **DENSE** IN THE FIRST CYCLE.
!----------
DO 15 I=1,ITRN
IND(I)=IND1(I)
15 CONTINUE
CALL RDPSRT(ITRN,DBH,IND,.FALSE.)
ONTREM(7)=0.0
!----------
!  PREPARE INPUT DATA FOR DIAMETER GROWTH MODEL CALIBRATION.  IF
!  IDG IS 1, CONVERT THE PAST DIAMETER MEASUREMENT CARRIED IN DG TO
!  DIAMETER GROWTH.  IF IDG IS 3, CONVERT THE CURRENT DIAMETER
!  MEASUREMENT CARRIED IN DG TO DIAMETER GROWTH.  ACTUAL DIAMETER
!  INCREMENT MEASUREMENTS WILL BE CORRECTED FOR BARK GROWTH IN
!  THE CALIBRATION ROUTINE. (THIS CODE WAS MOVED HERE SO THAT THE
!  BACKDATING ALGORITHM IN **DENSE**, INVOKED DURING CALIBRATION,
!  IS CORRECT.)
!----------
Q=1.0
IF(IDG.EQ.3) Q=-1.0
DO 230 II=1,ITRN
I=IND1(II)
IF(I.GE.IREC2) GO TO 230
IF(DG(I).LE.0.0) GO TO 220
IF(IDG.EQ.0.OR.IDG.EQ.2) GO TO 230
DG(I)=Q*(DBH(I)-DG(I))
GO TO 230
220 CONTINUE
DG(I)=-1.0
230 CONTINUE
!---------
!  SET LBKDEN TRUE IF DIAMETERS ARE TO BE BACKDATED FOR DENSITY
!  CALCULATIONS.  AFTER THIS CALL TO DENSE, INSURE LBKDEN=FALSE.
!---------
LBKDEN= IDG.LT.2
CALL DENSE
LBKDEN= .FALSE.
!----------
!  DELETE NON-PROJECTABLE RECORDS, AND REALIGN POINTERS TO THE
!  SPECIES ORDERED SORT.
!----------
IF(IREC2.EQ.MAXTP1) GO TO 60
DO 50 I=IREC2,MAXTRE
ISPC=ISP(I)
IPTR=IREF(ISPC)
IF(IMC(I).EQ.7)KNT(IPTR)=KNT(IPTR)+1
IF (DEBUG) WRITE(JOSTND,9003) I,IMC(I),ISPC
9003 FORMAT('IN CRATET: DEAD TREE RECORD:  I=',I4,',  IMC=',I2, &
          ',  SPECIES=',I2,' (9003 CRATET)')
IF(ITRN.GT.0)THEN
  I1=ISCT(ISPC,1)
  I2=ISCT(ISPC,2)
  DO 30 I3=I1,I2
  IF(IND1(I3).EQ.I) GO TO 40
30   CONTINUE
40   IND1(I3)=IND1(I2)
  ISCT(ISPC,2)=I2-1
  IF(ISCT(ISPC,2).GE.ISCT(ISPC,1)) GO TO 50
  ISCT(ISPC,1)=0
  ISCT(ISPC,2)=0
ENDIF
50 CONTINUE
!----------
!  WRITE CALIBRATION TABLE ENTRY FOR NON-PROJECTABLE RECORDS AND RESET
!  KNT ARRAY TO ZERO.
!----------
WRITE(JOSTND,9004) (KNT(I),I=1,NUMSP)
9004 FORMAT(/,'NUMBER OF RECORDS CODED AS RECENT MORTALITY', &
           ((T49,11(I4,2X)/)))
!---------
!  RESET TREE RECORD COUNTERS AND SAVE THE NUMBER OF SPECIES.
!----------
ITRN=IREC1
IF((ITRN.LE.0).AND.(IREC2.GE.MAXTP1))GOTO 245
IF(ITRN.LE.0)GOTO 60
ISPC=NUMSP
!---------
!  MAKE SURE THAT ALL THE SPECIES ORDER SORTS AND THE IND2 ARRAY
!  ARE IN THE PROPER ORDER. FIRST, SAVE THE SPECIES REFERENCES.
!---------
DO 51 I=1,MAXSP
KNT(I)=IREF(I)
51 CONTINUE
CALL SPESRT
!---------
!  IF THE NUMBER OF SPECIES HAS CHANGED, WE MUST REWRITE THE
!  COLUMN HEADINGS.
!---------
IF (ISPC.NE.NUMSP) THEN
   WRITE(JOSTND,52)
52    FORMAT (/'***** NOTE:  SPECIES HAVE BEEN DROPPED.')
   DO 55 I=1,MAXSP
   IF (ISCT(I,1).EQ.0) GOTO 55
   J=IREF(I)
   IUSED(J)=NSP(I,1)
55    CONTINUE
   WRITE(JOSTND,9000) (IUSED(I), I=1, NUMSP)
   WRITE(JOSTND,9001) (UNDER, I=1, NUMSP)
ELSE
!
!        RESET THE REFERENCES.
!
   DO 57 I=1,MAXSP
   IREF(I)=KNT(I)
57    CONTINUE
ENDIF
!----------
!  SORT REMAINING TREE RECORDS IN ORDER OF DESCENDING DIAMETER.
!  STORE POINTERS TO SORTED ORDER IN IND.
!----------
CALL RDPSRT(ITRN,DBH,IND,.TRUE.)
60 CONTINUE
DO 65 I=1,MAXSP
KNT(I)=0
65 CONTINUE
!----------
!  ENTER LOOP TO ADJUST HEIGHT-DBH MODEL FOR LOCAL CONDITIONS.  IF
!  THERE ARE 3 OR MORE TREES WITH MEASURED HEIGHTS FOR A GIVEN
!  SPECIES, ADJUST THE INTERCEPT (ASYMPTOTE) IN THE MODEL SO THAT
!  THE MEAN RESIDUAL FOR THE MEASURED TREES IS ZERO.
!  IF LHTDRG IS FALSE FOR A GIVEN SPECIES THEN ALL DUBBING IS DONE WITH
!  DEFAULT VALUES.
!----------
DO 150 ISPC=1,MAXSP
AA(ISPC)=0.
BB(ISPC)=0.
I1=ISCT(ISPC,1)
IF(I1.LE.0) GO TO 141
I2=ISCT(ISPC,2)
IPTR=IREF(ISPC)
SELECT CASE (ISPC)
CASE(9:10,12,14:17,19:20,25:27)
  SIZE = 5.0
CASE DEFAULT
  SIZE = 3.0
END SELECT
!----------
!  INITIALIZE SUMS FOR THIS SPECIES.
!----------
K1=0
K2=0
K3=0
K4=0
SUMX=0.0
!----------
!  DETERMINE SITE CLASS
!----------
R5SI=0.0
IF(SITEAR(ISPC).NE.0.0)R5SI=SITEAR(ISPC)
IF(R5SI.LE.45.0)SC=5.0
IF(R5SI.GT.45.0 .AND. R5SI.LE.55.0)SC=4.0
IF(R5SI.GT.55.0 .AND. R5SI.LE.70.0)SC=3.0
IF(R5SI.GT.70.0 .AND. R5SI.LE.85.0)SC=2.0
IF(R5SI.GT.85.0 .AND. R5SI.LE.100.0)SC=1.0
IF(R5SI.GT.100.0)SC=0.0
!----------
!  ENTER TREE LOOP WITHIN SPECIES.
!----------
DO 80 I3=I1,I2
I=IND1(I3)
H=HT(I)
NH=NORMHT(I)
D=DBH(I)
BX=HT2(ISPC)
!----------
!  BYPASS SUMS FOR TREES WITH MISSING HEIGHT OR TRUNCATED TOPS.
!----------
IF(H.LE.4.5 .OR. NH.LT.0 .OR. D.LT.SIZE) GO TO 70
K1=K1+1
XX = BX / (D + 1.)
YY = ALOG(H - 4.5)
SUMX= SUMX + YY - XX
GO TO 80
!----------
!  COUNT NUMBER OF MISSING HEIGHTS AND BROKEN OR DEAD TOPS.  LOAD THE
!  ARRAY IND2 WITH SUBSCRIPTS TO THE RECORDS WITH MISSING HEIGHTS.
!----------
70 CONTINUE
IF(NH.LT.0) K3=K3+1
IF(H.GT.0.0 .AND. NH.EQ.0) GO TO 80
K2=K2+1
IND2(K2)=I
!----------
!  END OF SUMMATION LOOP FOR THIS SPECIES.
!----------
!*** ONE LINE FIX FOR GROWTH METHOD 1 PROBLEM. DIXON 11-16-90.
IF(HT(I) .LE. 0.1) HTG(I)=0.0
80 CONTINUE
!----------
!  IF THERE ARE LESS THAN THREE OBSERVATIONS OR LHTDRG IS FALSE
!  THEN DUB HEIGHTS USING DEFAULT COEFFICIENTS FOR THIS SPECIES.
!----------
KNT(IPTR)=K3
IF(K1.LT.3 .OR. .NOT.LHTDRG(ISPC)) GO TO 100
XN=REAL(K1)
AA(ISPC) = SUMX/XN
IF(DEBUG)WRITE(JOSTND,*)'ISPC,AA,SUMX,XN= ', &
   ISPC,AA(ISPC),SUMX,XN
!----------
!  IF THE INTERCEPT IS NEGATIVE, USE THE DEFAULT VALUE.
!----------
IF(AA(ISPC).GE.0.0) THEN
  IABFLG(ISPC)=0
ENDIF
100 CONTINUE
AHATR5 = A(IFOR)
BHATR5 = B(IFOR)
CHATR5 = C(IFOR)
IF(DEBUG) WRITE(JOSTND,9114)AHATR5,BHATR5,CHATR5
9114 FORMAT('IN CRATET 9114 AHATR5,BHATR5,CHATR5 =',3F11.5)
!----------
!  DUB IN MISSING HEIGHTS.
!  A VALUE LESS THAN ZERO STORED IN 'HT' => THAT TREE WAS TOP KILLED.
!  CONSEQUENTLY, A VALUE OF 80% OF THE PREDICTED HEIGHT IS STORED AS
!  THE TRUNCATED HEIGHT.
!----------
AX=HT1(ISPC)
BX=HT2(ISPC)
IF(IABFLG(ISPC) .EQ. 0) AX=AA(ISPC)
IF(K2.EQ.0) GO TO 140
DO 130 JJ=1,K2
II=IND2(JJ)
D=DBH(II)
TKILL = NORMHT(II) .LT. 0
!
IF(D .LE. 0.1)THEN
  H=1.01
  GO TO 115
ENDIF
!
SELECT CASE(ISPC)
!----------
!  SPECIES USING EQUATIONS FROM THE CA VARIANT
!----------
CASE(4,9:10,12,14:17,19:20,23,25:27)
  H=EXP(AX+BX/(D+1.0))+4.5
  IF (DEBUG) WRITE(JOSTND,88) AX,BX,D,H
  IF(.NOT.LHTDRG(ISPC) .OR. &
        (LHTDRG(ISPC) .AND. IABFLG(ISPC).EQ.1))THEN
    CALL HTDBH (IFOR,ISPC,D,H,0)
    IF(DEBUG)WRITE(JOSTND,*)'INVENTORY EQN DUBBING IFOR,ISPC,D,', &
       'H= ',IFOR,ISPC,D,H
  ENDIF
!----------
!  LOGIC FOR SPECIES FROM SO VARIANT (SEPARATE EQS. FOR SMALL TREES)
!----------
CASE (41)
  IF(D .LT. 5.0) THEN
    H = 0.0994 + 4.9767*D
  ELSE
    H=EXP(AX+BX/(D+1.0))+4.5
  ENDIF
  IF (DEBUG) WRITE(JOSTND,88) AX,BX,D,H
  IF(.NOT.LHTDRG(ISPC) .OR. &
        (LHTDRG(ISPC) .AND. IABFLG(ISPC).EQ.1))THEN
    CALL HTDBH (IFOR,ISPC,D,H,0)
    IF(DEBUG)WRITE(JOSTND,*)'INVENTORY EQN DUBBING IFOR,ISPC,D,', &
       'H= ',IFOR,ISPC,D,H
  ENDIF
!----------
!  ALL OTHER SPECIES
!----------
CASE DEFAULT
  H=EXP(AX+BX/(D+1.0))+4.5
  IF (DEBUG) WRITE(JOSTND,88) AX,BX,D,H
88   FORMAT('CRATET DUBBED HEIGHT: AX,BX,D,H=',4F8.2)
!
END SELECT
!
!----------
! IF USING COMPUTED COEFFS OR NO SITE FOR THIS SPECIES, USE LOGISTIC FN.
!----------
IF(IABFLG(ISPC) .EQ. 0 .OR. R5SI .LE. 0.0) GO TO 119
!----------
! SPECIAL R5 HEIGHT DUBBING FUNCTION FOR LARGER TREES
!----------
IF(DBH(II).GT. 3.0)THEN
  SELECT CASE (ISPC)
  CASE(1:3,5:8,11,18,22,24,42)
    H = AHATR5 + BHATR5*SQRT(D) + CHATR5*SQRT(D)*SQRT(6.0-SC)
  END SELECT
ENDIF
IF(ISPC .EQ. 5) H = H * .76
!
119 CONTINUE
IF(H .LT. 4.5)H=4.5
115 CONTINUE
IF(TKILL) GO TO 120
HT(II)=H
K4=K4+1
GO TO 125
120 CONTINUE
NORMHT(II)=INT(H*100.0+0.5)
IF(ITRUNC(II).EQ.0) THEN
   IF(HT(II).GT.0.0) THEN
      ITRUNC(II)=INT(80.0*HT(II)+0.5)
   ELSE
      ITRUNC(II)=INT(80.0*H+0.5)
      HT(II)=H
   ENDIF
ELSE
   IF(HT(II).GT.0.0) THEN
      IF(HT(II).LT.(REAL(ITRUNC(II))*0.01)) &
          HT(II)=REAL(ITRUNC(II))*0.01
   ELSE
      HT(II)=REAL(ITRUNC(II))*0.01
   ENDIF
ENDIF
IF(REAL(NORMHT(II))*0.01.LT.HT(II)) NORMHT(II)=INT(HT(II)*100.0)
!----------
!  IF FOR SOME STRANGE REASON THE TRUNCATED HEIGHT IS GREATER THAN THE
!  NORMAL HEIGHT, RELY ON THE DATA--RESET HT TO BE EQUAL TO ITRUNC AND
!  SHUTOFF TRUNCATION LOGIC BY ASSIGNING NORMHT AND ITRUNC TO ZERO.
!----------
IF(NORMHT(II).LT.ITRUNC(II)) THEN
  HT(II)=REAL(ITRUNC(II))*0.01
  NORMHT(II)=0
  ITRUNC(II)=0
ENDIF
125 CONTINUE
130 CONTINUE
KNT2(IPTR)=K4
!----------
!  END OF SPECIES LOOP.  PRINT HEIGHT-DIAMETER COEFFICIENTS ON
!  DEBUG UNIT IF DESIRED.
!----------
140 CONTINUE
IF(DEBUG)THEN
WRITE(JOSTND,9005) ISPC,AX,BX,IABFLG(ISPC)
9005 FORMAT('HEIGHT-DIAMETER COEFFICIENTS FOR SPECIES ',I2, &
         ':  INTERCEPT=',F10.6,'  SLOPE=',F10.6,'  IABFLG(ISPC)=',I4, &
    ' (9005 CRATET)')
ENDIF
!----------
!  LOOP THROUGH DEAD TREES AND DUB MISSING HEIGHTS FOR THIS SPECIES.
!----------
141 CONTINUE
IF(IREC2 .GT. MAXTRE) GO TO 150
DO 145 II=IREC2,MAXTRE
IF(ISP(II).NE.ISPC) GO TO 145
AX=HT1(ISPC)
BX=HT2(ISPC)
IF(IABFLG(ISPC) .EQ. 0) AX=AA(ISPC)
D=DBH(II)
TKILL = NORMHT(II) .LT. 0
IF(HT(II).GT.0. .AND. TKILL) GO TO 142
IF(HT(II).GT.0.) GO TO 146
!
IF(D .LE. 0.1)THEN
  H=1.01
  GO TO 144
ENDIF
!
SELECT CASE(ISPC)
!----------
!  SPECIES USING EQUATIONS FROM THE CA VARIANT
!----------
CASE(4,9:10,12,14:17,19:20,23,25:27)
  H=EXP(AX+BX/(D+1.0))+4.5
  IF (DEBUG) WRITE(JOSTND,88) AX,BX,D,H
  IF(.NOT.LHTDRG(ISPC) .OR. &
        (LHTDRG(ISPC) .AND. IABFLG(ISPC).EQ.1))THEN
    CALL HTDBH (IFOR,ISPC,D,H,0)
    IF(DEBUG)WRITE(JOSTND,*)'INVENTORY EQN DUBBING IFOR,ISPC,D,', &
       'H= ',IFOR,ISPC,D,H
  ENDIF
!----------
!  LOGIC FOR SPECIES FROM SO VARIANT (SEPARATE EQS. FOR SMALL TREES)
!----------
CASE (41)
  IF(D .LT. 5.0) THEN
    H = 0.0994 + 4.9767*D
  ELSE
    H=EXP(AX+BX/(D+1.0))+4.5
  ENDIF
  IF (DEBUG) WRITE(JOSTND,88) AX,BX,D,H
  IF(.NOT.LHTDRG(ISPC) .OR. &
        (LHTDRG(ISPC) .AND. IABFLG(ISPC).EQ.1))THEN
    CALL HTDBH (IFOR,ISPC,D,H,0)
    IF(DEBUG)WRITE(JOSTND,*)'INVENTORY EQN DUBBING IFOR,ISPC,D,', &
       'H= ',IFOR,ISPC,D,H
  ENDIF
!----------
!  ALL OTHER SPECIES
!----------
CASE DEFAULT
  H=EXP(AX+BX/(D+1.0))+4.5
  IF (DEBUG) WRITE(JOSTND,88) AX,BX,D,H
!
END SELECT
!
!----------
! IF USING COMPUTED COEFFS OR NO SITE FOR THIS SPECIES, USE LOGISTIC FN.
!----------
IF(IABFLG(ISPC) .EQ. 0 .OR. R5SI .LE. 0.0) GO TO 143
!----------
! SPECIAL R5 HEIGHT DUBBING FUNCTION FOR LARGER TREES
!----------
IF(DBH(II).GT. 3.0)THEN
  SELECT CASE (ISPC)
  CASE(1:8,11,18,22,24,42)
    H = AHATR5 + BHATR5*SQRT(D) + CHATR5*SQRT(D)*SQRT(6.0-SC)
  END SELECT
ENDIF
IF(ISPC .EQ. 5) H = H * .76
!
143 CONTINUE
IF(H .LT. 4.5)H=4.5
144 CONTINUE
IF(TKILL) GO TO 142
HT(II)=H
GO TO 146
142 CONTINUE
IF(HT(II) .GT. 0.) THEN
  NORMHT(II)=INT(HT(II)*100.0+0.5)
ELSE
  NORMHT(II)=INT(H*100.0+0.5)
ENDIF
IF(ITRUNC(II).EQ.0) THEN
   IF(HT(II).GT.0.0) THEN
      ITRUNC(II)=INT(80.0*HT(II)+0.5)
   ELSE
      ITRUNC(II)=INT(80.0*H+0.5)
      HT(II)=H
   ENDIF
ELSE
   IF(HT(II).GT.0.0) THEN
      IF(HT(II).LT.(REAL(ITRUNC(II))*0.01)) &
          HT(II)=REAL(ITRUNC(II))*0.01
   ELSE
      HT(II)=REAL(ITRUNC(II))*0.01
   ENDIF
ENDIF
IF(REAL(NORMHT(II))*0.01.LT.HT(II)) NORMHT(II)=INT(HT(II)*100.0)
!----------
!  IF FOR SOME STRANGE REASON THE TRUNCATED HEIGHT IS GREATER THAN THE
!  NORMAL HEIGHT, RELY ON THE DATA--RESET HT TO BE EQUAL TO ITRUNC AND
!  SHUTOFF TRUNCATION LOGIC BY ASSIGNING NORMHT AND ITRUNC TO ZERO.
!----------
IF(NORMHT(II).LT.ITRUNC(II)) THEN
  HT(II)=REAL(ITRUNC(II))*0.01
  NORMHT(II)=0
  ITRUNC(II)=0
ENDIF
!----------
!   CALL FIRE SNAG MODEL TO ADD THE DEAD TREES TO THE
!   SNAG LIST; DEFLATE PROB(II), WHICH WAS TEMPORARILY
!   ADJUSTED TO ALLOW BACKDATING FOR CALIBRATION PURPOSES,
!   IN **NOTRE**
!----------
146 CONTINUE
IF (TKILL) THEN
  HS = REAL(ITRUNC(II)) * 0.01
ELSE
  HS = HT(II)
ENDIF
CALL FMSSEE (II,ISPC,D,HS, &
     (PROB(II)/(FINT/FINTM)),3,.FALSE.,JOSTND)
!
145 CONTINUE
!----------
150 CONTINUE
!----------
!  END OF HEIGHT DUBBING SEGMENT.  PRINT CONTROL TABLE ENTRIES FOR
!  USEABLE HEIGHTS AND MISSING HEIGHTS, AND REINITIALIZE COUNTERS.
!----------
WRITE(JOSTND,9006) (KNT2(I),I=1,NUMSP)
9006 FORMAT(/,'NUMBER OF RECORDS WITH MISSING HEIGHTS', &
          T49,11(I4,2X))
WRITE(JOSTND,9007) (KNT(I),I=1,NUMSP)
9007 FORMAT(/,'NUMBER OF RECORDS WITH BROKEN OR DEAD TOPS', &
          T49,11(I4,2X))
DO 160 I=1,MAXSP
KNT(I)=0
KNT2(I)=0
160 CONTINUE
!----------
!  CHECK FOR MISSING CROWNS ON LIVE TREES.
!  SAVE PCT IN OLDPCT TO RETAIN AN OLD PCTILE VALUE.
!----------
MISSCR = .FALSE.
DO 190 I=1,ITRN
OLDPCT(I)= PCT(I)
IF(ICR(I).LE.0)THEN
  MISSCR = .TRUE.
  ISPC=ISP(I)
  IPTR=IREF(ISPC)
  KNT2(IPTR)=KNT2(IPTR)+1
ENDIF
IF(ITRE(I).LE.0) ITRE(I) = 9999
190 CONTINUE
!----------
!  CHECK FOR MISSING CROWNS ON CYCLE 0 DEAD TREES.
!----------
IF(IREC2 .GT. MAXTRE) GO TO 192
DO 191 I=IREC2,MAXTRE
IF(ICR(I).LE.0)MISSCR=.TRUE.
191 CONTINUE
192 CONTINUE
!----------
!  CALL **CROWN** IF ANY CROWN RATIOS ARE MISSING.
!----------
IF(MISSCR)CALL CROWN
!----------
!  PRINT CONTROL TABLE ENTRY FOR MISSING CROWN RATIOS; RESET COUNTERS.
!----------
WRITE(JOSTND,9008) (KNT2(I),I=1,NUMSP)
9008 FORMAT(/,'NUMBER OF RECORDS WITH MISSING CROWN RATIOS', &
          T49,11(I4,2X))
DO 200 I=1,MAXSP
KNT2(I)=0
200 CONTINUE
!----------
! CALL AVHT40 TO CALCULATE AVERAGE HEIGHT. THIS CALL IS NEEDED
! BECAUSE REGENT USES AVH IN CALCULATION.
!----------
CALL AVHT40
!----------
!  CALL DGDRIV TO CALIBRATE DIAMETER GROWTH EQUATIONS.
!----------
IF(DEBUG)WRITE(JOSTND,*)'CALL DGDRIV FROM CRATET SECOND TIME'
CALL DGDRIV
!----------
!  PREPARE INPUT DATA FOR HEIGHT GROWTH MODEL CALIBRATION; IT'S DONE
!  THE SAME AS THE DIAMETER GROWTH MODEL SEEN ABOVE.
!----------
IF(IHTG.EQ.0 .OR. IHTG.EQ.2) GOTO 236
Q = 1.
IF(IHTG.EQ.3) Q = -1.
DO 233 I=1,ITRN
IF(HTG(I).LE.0.) GOTO 233
HTG(I) = Q * (HT(I)-HTG(I))
IF(HT(I) .LE. 0.0) HTG(I)=0.0
233 CONTINUE
236 CONTINUE
!----------
!  ESTIMATE MISSING TOTAL TREE AGES
!----------
IF(DEBUG)WRITE(JOSTND,*)'IN CRATET, CALLING FINDAG'
DO I=1,ITRN
IF(ABIRTH(I) .LE. 0.)THEN
  SITAGE = 0.0
  SITHT = 0.0
  AGMAX = 0.0
  HTMAX = 0.0
  HTMAX2 = 0.0
  ISPC = ISP(I)
  D = DBH(I)
  H = HT(I)
  D2 = 0.0
  CALL FINDAG(I,ISPC,D,D2,H,SITAGE,SITHT,AGMAX,HTMAX,HTMAX2, &
                 DEBUG)
  IF(SITAGE .GT. 0.)ABIRTH(I)=SITAGE
ENDIF
ENDDO
!----------
!  CALL REGENT TO CALIBRATE THE SMALL TREE HEIGHT INCREMENT MODEL.
!----------
CALL REGENT(.FALSE.,1)
!----------
!  LOAD SPCNT WITH NUMBER OF TREES PER ACRE BY SPECIES AND TREE
!  CLASS.
!----------
DO 240 I=1,ITRN
IS=ISP(I)
IM=IMC(I)
SPCNT(IS,IM)=SPCNT(IS,IM)+PROB(I)
240 CONTINUE
!----------
!  COMPUTE DISTRIBUTION OF TREES PER ACRE AND SPECIES-TREE CLASS
!  COMPOSITION BY TREES PER ACRE.
!----------
245 CONTINUE
CALL PCTILE(ITRN,IND,PROB,WK3,ONTCUR(7))
CALL DIST(ITRN,ONTCUR,WK3)
CALL COMP(OSPCT,IOSPCT,SPCNT)
IF (ITRN.LE.0) GO TO 500
!----------
!  CALL **DENSE** TO CALCULATE STAND DENSITY STATISTICS FOR
!  INITIAL INVENTORY.
!----------
IF(DEBUG) WRITE(JOSTND,9013) ICYC
9013 FORMAT('CALLING DENSE, CYCLE=',I2)
CALL DENSE
!----------
! COUNT AND PRINT NUMBER OF MISTLETOE RECORDS
!----------
CALL MISCNT(KNT)
WRITE(JOSTND,248) (KNT(I),I=1,NUMSP)
248 FORMAT(/,'NUMBER OF RECORDS WITH MISTLETOE',T49,11(I4,2X))
!----------
!  CALL **SDICHK** TO SEE IF INITIAL STAND SDI IS ABOVE THE SPECIFIED
!  MAXIMUM SDI.  RESET MAXIMUM SDI IF THIS IS THE CASE.
!----------
CALL SDICHK
!
500 CONTINUE
IF(DEBUG)WRITE(JOSTND,510)ICYC
510 FORMAT('LEAVING SUBROUTINE CRATET  CYCLE =',I5)
!
RETURN
END
