SUBROUTINE DUNN (SS)
IMPLICIT NONE
!----------
! WS $Id$
!----------
! THIS SUBROUTINE PROCESSES THE DUNNING CODE INFORMATION THAT WAS
! ENTERED BY KEYWORD.
!
! WHEN A DUNNING CODE IS ENTERED (IE ANY OF THE SITEAR VALUES BETWEEN
! 0 AND 7)  THEN SITE VALUES FOR ALL SPECIES ARE AUTOMATICALLY SET.  IF
! ANY SITEAR VALUES ARE BETWEEN 8 AND 10 THIS IS AN ERROR AND THE
! DEFAULT VALUE SPECIFIED IN GRINIT IS MAINTAINED. THIS ROUTINE IS
! CALLED FROM INITRE.
!----------
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
!OMMONS
!
!----------
INTEGER IST,ISPC,I
REAL ADJFAC(MAXSP),DUNN50(8),XST2(8),SS,DU50,DUNN99(8),DU99
!----------
!     SPECIES LIST FOR WESTERN SIERRAS VARIANT.
!
!     1 = SUGAR PINE (SP)                   PINUS LAMBERTIANA
!     2 = DOUGLAS-FIR (DF)                  PSEUDOTSUGA MENZIESII
!     3 = WHITE FIR (WF)                    ABIES CONCOLOR
!     4 = GIANT SEQUOIA (GS)                SEQUOIADENDRON GIGANTEAUM
!     5 = INCENSE CEDAR (IC)                LIBOCEDRUS DECURRENS
!     6 = JEFFREY PINE (JP)                 PINUS JEFFREYI
!     7 = CALIFORNIA RED FIR (RF)           ABIES MAGNIFICA
!     8 = PONDEROSA PINE (PP)               PINUS PONDEROSA
!     9 = LODGEPOLE PINE (LP)               PINUS CONTORTA
!    10 = WHITEBARK PINE (WB)               PINUS ALBICAULIS
!    11 = WESTERN WHITE PINE (WP)           PINUS MONTICOLA
!    12 = SINGLELEAF PINYON (PM)            PINUS MONOPHYLLA
!    13 = PACIFIC SILVER FIR (SF)           ABIES AMABILIS
!    14 = KNOBCONE PINE (KP)                PINUS ATTENUATA
!    15 = FOXTAIL PINE (FP)                 PINUS BALFOURIANA
!    16 = COULTER PINE (CP)                 PINUS COULTERI
!    17 = LIMBER PINE (LM)                  PINUS FLEXILIS
!    18 = MONTEREY PINE (MP)                PINUS RADIATA
!    19 = GRAY PINE (GP)                    PINUS SABINIANA
!         (OR CALIFORNIA FOOTHILL PINE)
!    20 = WASHOE PINE (WE)                  PINUS WASHOENSIS
!    21 = GREAT BASIN BRISTLECONE PINE (GB) PINUS LONGAEVA
!    22 = BIGCONE DOUGLAS-FIR (BD)          PSEUDOTSUGA MACROCARPA
!    23 = REDWOOD (RW)                      SEQUOIA SEMPERVIRENS
!    24 = MOUNTAIN HEMLOCK (MH)             TSUGA MERTENSIANA
!    25 = WESTERN JUNIPER (WJ)              JUNIPERUS OCIDENTALIS
!    26 = UTAH JUNIPER (UJ)                 JUNIPERUS OSTEOSPERMA
!    27 = CALIFORNIA JUNIPER (CJ)           JUNIPERUS CALIFORNICA
!    28 = CALIFORNIA LIVE OAK (LO)          QUERCUS AGRIFOLIA
!    29 = CANYON LIVE OAK (CY)              QUERCUS CHRYSOLEPSIS
!    30 = BLUE OAK (BL)                     QUERCUS DOUGLASII
!    31 = CALIFORNIA BLACK OAK (BO)         QUERQUS KELLOGGII
!    32 = VALLEY OAK (VO)                   QUERCUS LOBATA
!         (OR CALIFORNIA WHITE OAK)
!    33 = INTERIOR LIVE OAK (IO)            QUERCUS WISLIZENI
!    34 = TANOAK (TO)                       LITHOCARPUS DENSIFLORUS
!    35 = GIANT CHINQUAPIN (GC)             CHRYSOLEPIS CHRYSOPHYLLA
!    36 = QUAKING ASPEN (AS)                POPULUS TREMULOIDES
!    37 = CALIFORNIA-LAUREL (CL)            UMBELLULARIA CALIFORNICA
!    38 = PACIFIC MADRONE (MA)              ARBUTUS MENZIESII
!    39 = PACIFIC DOGWOOD (DG)              CORNUS NUTTALLII
!    40 = BIGLEAF MAPLE (BM)                ACER MACROPHYLLUM
!    41 = CURLLEAF MOUNTAIN-MAHOGANY (MC)   CERCOCARPUS LEDIFOLIUS
!    42 = OTHER SOFTWOODS (OS)
!    43 = OTHER HARDWOODS (OH)
!
!  SURROGATE EQUATION ASSIGNMENT:
!
!    FROM EXISTING WS EQUATIONS --
!      USE 1(SP) FOR 11(WP) AND 24(MH)
!      USE 2(DF) FOR 22(BD)
!      USE 3(WF) FOR 13(SF)
!      USE 4(GS) FOR 23(RW)
!      USE 8(PP) FOR 18(MP)
!      USE 34(TO) FOR 35(GC), 36(AS), 37(CL), 38(MA), AND 39(DG)
!      USE 31(BO) FOR 28(LO), 29(CY), 30(BL), 32(VO), 33(IO), 40(BM), AND
!                     43(OH)
!
!    FROM CA VARIANT --
!      USE CA11(KP) FOR 12(PM), 14(KP), 15(FP), 16(CP), 17(LM), 19(GP), 20(WE),
!                       25(WJ), 26(WJ), AND 27(CJ)
!      USE CA12(LP) FOR 9(LP) AND 10(WB)
!
!    FROM SO VARIANT --
!      USE SO30(MC) FOR 41(MC)
!
!    FROM UT VARIANT --
!      USE UT17(GB) FOR 21(GB)
!----------
!  DATA STATEMENTS
!----------
DATA ADJFAC/ &
    0.90, 1.00, 1.00, 1.00, 0.76, 1.00, 1.00, 1.00, 0.90, 0.90, &
    0.90, 1.00, 1.00, 0.90, 0.90, 0.90, 0.90, 1.00, 0.90, 0.90, &
    0.00, 1.00, 1.00, 0.90, 0.90, 0.90, 0.90, 0.60, 0.45, 0.45, &
    1.00, 0.60, 0.50, 0.60, 0.50, 0.75, 0.55, 0.60, 0.50, 0.50, &
    1.00, 0.90, 0.57/
!
DATA DUNN50/ 106.,  90.,  75.,  56.,  49.,  39.,  31.,  23./
DATA DUNN99/ 140., 121., 102.,  81.,  67.,  54.,  44.,  36./
!----------
!
IST=INT(SS+1.0)
DU50=DUNN50(IST)
DU99=DUNN99(IST)
!----------
!   SET SITE INDEX VALUES BASED ON DUNNING VALUES ENTERED.
!----------
DO 20 ISPC=1,MAXSP
!
SELECT CASE (ISPC)
!----------
!  SPECIES FROM UTAH VARIANT 21=GB
!  EQUATION DERIVED FROM TAKING THE GB SITE RANGE 20-60 AND EQUATING
!  THOSE ENDPOINTS TO THE DUNNING 100-YEAR 36 AND 140, RESPECTIVELY.
!  THEN DERIVING A STRAIGHT LINE ADJUSTMENT RELATIONSHIP BETWEEN THOSE
!  TWO POINTS WITH GB SITE RANGE ON THE Y-AXIS AND DUNNING SITE RANGE
!  ON THE X-AXIS.
!----------
CASE (21)
  SITEAR(ISPC) = 20.0 + 0.3846*(DU99-36.0)
!----------
!  SPECIES FROM SO VARIANT 41=MC
!----------
CASE (41)
  SITEAR(ISPC) = DU99 * ADJFAC(ISPC)
!----------
!  ALL OTHER SPECIES
!----------
CASE DEFAULT
  SITEAR(ISPC) = DU50 * ADJFAC(ISPC)
!
END SELECT
!
20 CONTINUE
!
RETURN
!
!
!----------
!   WS FIRE MODEL NEEDS SITE INDICES FOR DUNNING CODES.
!----------
ENTRY GETDUNN(XST2)
DO I=1,8
XST2(I) = DUNN50(I)
ENDDO
RETURN
!
END
