SUBROUTINE ESSUBH (I,HHT,EMSQR,DILATE,DELAY,EL,IHTSER, &
     GENTIM,TRAGE)
IMPLICIT NONE
!----------
! WS $Id$
!----------
!
!     ASSIGNS HEIGHTS TO SUBSEQUENT AND PLANTED TREE RECORDS
!     CREATED BY THE ESTABLISHMENT MODEL.
!
!
!     COMING INTO ESSUBH, TRAGE IS THE AGE OF THE TREE AS SPECIFIED ON
!     THE PLANT OR NATURAL KEYWORD.  LEAVING ESSUBH, TRAGE IS THE NUMBER
!     BETWEEN PLANTING (OR NATURAL REGENERATION) AND THE END OF THE
!     CYCLE.  AGE IS TREE AGE UP TO THE TIME REGENT WILL BEGIN GROWING
!     THE TREE.
!----------
!  COMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ESPARM.f90'
!
!
INCLUDE 'ESCOMN.f90'
!
!
INCLUDE 'PLOT.f90'
!
!OMMONS
!----------
!   DECLARATIONS
!----------
INTEGER I,N,IHTSER,ITIME
REAL    EMSQR,DILATE,EL,HHT,DELAY,GENTIM,TRAGE,AGE,SI
REAL RDANUW
INTEGER IDANUW
!----------
!     SPECIES LIST FOR WESTERN SIERRAS VARIANT.
!
!     1 = SUGAR PINE (SP)                   PINUS LAMBERTIANA
!     2 = DOUGLAS-FIR (DF)                  PSEUDOTSUGA MENZIESII
!     3 = WHITE FIR (WF)                    ABIES CONCOLOR
!     4 = GIANT SEQUOIA (GS)                SEQUOIADENDRON GIGANTEAUM
!     5 = INCENSE CEDAR (IC)                LIBOCEDRUS DECURRENS
!     6 = JEFFREY PINE (JP)                 PINUS JEFFREYI
!     7 = CALIFORNIA RED FIR (RF)           ABIES MAGNIFICA
!     8 = PONDEROSA PINE (PP)               PINUS PONDEROSA
!     9 = LODGEPOLE PINE (LP)               PINUS CONTORTA
!    10 = WHITEBARK PINE (WB)               PINUS ALBICAULIS
!    11 = WESTERN WHITE PINE (WP)           PINUS MONTICOLA
!    12 = SINGLELEAF PINYON (PM)            PINUS MONOPHYLLA
!    13 = PACIFIC SILVER FIR (SF)           ABIES AMABILIS
!    14 = KNOBCONE PINE (KP)                PINUS ATTENUATA
!    15 = FOXTAIL PINE (FP)                 PINUS BALFOURIANA
!    16 = COULTER PINE (CP)                 PINUS COULTERI
!    17 = LIMBER PINE (LM)                  PINUS FLEXILIS
!    18 = MONTEREY PINE (MP)                PINUS RADIATA
!    19 = GRAY PINE (GP)                    PINUS SABINIANA
!         (OR CALIFORNIA FOOTHILL PINE)
!    20 = WASHOE PINE (WE)                  PINUS WASHOENSIS
!    21 = GREAT BASIN BRISTLECONE PINE (GB) PINUS LONGAEVA
!    22 = BIGCONE DOUGLAS-FIR (BD)          PSEUDOTSUGA MACROCARPA
!    23 = REDWOOD (RW)                      SEQUOIA SEMPERVIRENS
!    24 = MOUNTAIN HEMLOCK (MH)             TSUGA MERTENSIANA
!    25 = WESTERN JUNIPER (WJ)              JUNIPERUS OCIDENTALIS
!    26 = UTAH JUNIPER (UJ)                 JUNIPERUS OSTEOSPERMA
!    27 = CALIFORNIA JUNIPER (CJ)           JUNIPERUS CALIFORNICA
!    28 = CALIFORNIA LIVE OAK (LO)          QUERCUS AGRIFOLIA
!    29 = CANYON LIVE OAK (CY)              QUERCUS CHRYSOLEPSIS
!    30 = BLUE OAK (BL)                     QUERCUS DOUGLASII
!    31 = CALIFORNIA BLACK OAK (BO)         QUERQUS KELLOGGII
!    32 = VALLEY OAK (VO)                   QUERCUS LOBATA
!         (OR CALIFORNIA WHITE OAK)
!    33 = INTERIOR LIVE OAK (IO)            QUERCUS WISLIZENI
!    34 = TANOAK (TO)                       LITHOCARPUS DENSIFLORUS
!    35 = GIANT CHINQUAPIN (GC)             CHRYSOLEPIS CHRYSOPHYLLA
!    36 = QUAKING ASPEN (AS)                POPULUS TREMULOIDES
!    37 = CALIFORNIA-LAUREL (CL)            UMBELLULARIA CALIFORNICA
!    38 = PACIFIC MADRONE (MA)              ARBUTUS MENZIESII
!    39 = PACIFIC DOGWOOD (DG)              CORNUS NUTTALLII
!    40 = BIGLEAF MAPLE (BM)                ACER MACROPHYLLUM
!    41 = CURLLEAF MOUNTAIN-MAHOGANY (MC)   CERCOCARPUS LEDIFOLIUS
!    42 = OTHER SOFTWOODS (OS)
!    43 = OTHER HARDWOODS (OH)
!
!  SURROGATE EQUATION ASSIGNMENT:
!
!    FROM EXISTING WS EQUATIONS --
!      USE 1(SP) FOR 11(WP) AND 24(MH)
!      USE 2(DF) FOR 22(BD)
!      USE 3(WF) FOR 13(SF)
!      USE 4(GS) FOR 23(RW)
!      USE 8(PP) FOR 18(MP)
!      USE 34(TO) FOR 35(GC), 36(AS), 37(CL), 38(MA), AND 39(DG)
!      USE 31(BO) FOR 28(LO), 29(CY), 30(BL), 32(VO), 33(IO), 40(BM), AND
!                     43(OH)
!
!    FROM CA VARIANT --
!      USE CA11(KP) FOR 12(PM), 14(KP), 15(FP), 16(CP), 17(LM), 19(GP), 20(WE),
!                       25(WJ), 26(WJ), AND 27(CJ)
!      USE CA12(LP) FOR 9(LP) AND 10(WB)
!
!    FROM SO VARIANT --
!      USE SO30(MC) FOR 41(MC)
!
!    FROM UT VARIANT --
!      USE UT17(GB) FOR 21(GB)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
RDANUW = DILATE
RDANUW = EL
RDANUW = EMSQR
IDANUW = IHTSER
!
!----------
N=INT(DELAY+0.5)
IF(N.LT.-3) N=-3
DELAY=FLOAT(N)
ITIME=INT(TIME+0.5)
IF(N.GT.ITIME) DELAY=TIME
AGE=TIME-DELAY-GENTIM+TRAGE
IF(AGE.LT.1.0) AGE=1.0
TRAGE=TIME-DELAY
!
SI= SITEAR(I)
!
SELECT CASE (I)
!----------
!  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 42=OS
!----------
CASE (42)
  HHT = 1.0
!----------
!  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 1=SP, 11=WP, 24=MH
!----------
CASE (1,11,24)
  HHT = 2.0
!----------
!  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 2=DF, 22=BD
!----------
CASE (2,22)
  HHT = 1.0
!----------
!  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 3=WF, 13=SF
!----------
CASE (3,13)
  HHT = 2.0
!----------
!  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 4=GS, 23=RW
!----------
CASE (4,23)
  HHT = 2.0
!----------
!  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 5=IC
!----------
CASE (5)
  HHT = 2.0
!----------
!  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 28=LO, 29=CY, 30=BL, 31=BO,
!----------                              32=VO, 33=IO, 40=BM, 43=OH
CASE (28:33,40,43)
  HHT = 7.0
!----------
!  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 6=JP
!----------
CASE (6)
  HHT = 0.8
!----------
!  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 7=RF
!----------
CASE (7)
  HHT = 5.0
!----------
!  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 8=PP, 18=MP
!----------
CASE (8,18)
  HHT = 4.0
!----------
!  FROM THE CA VARIANT
!  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 9=LP, 10=WB
!----------
CASE (9,10)
  HHT = 3.0
!----------
!  FROM THE CA VARIANT
!  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 12=PM, 14=KP, 15=FP, 16=CP, 17=LM,
!                                 19=GP, 20=WE, 25=WJ, 26=UJ, 27=CJ
!----------
CASE (12,14:17,19:20,25:27)
  HHT = 3.0
!----------
!  FROM THE UT VARIANT
!  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 21=GB
!----------
CASE (21)
  HHT = 0.5
!----------
!  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 34=TO, 35=GC, 36=AS, 37=CL,
!                                        38=MA, 39=DG
!----------
CASE (34:39)
  HHT = 7.0
!----------
!  FROM THE SO VARIANT
!  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 41=MC
!----------
CASE (41)
  HHT = ((1.47043 + 0.23317*SI)/(31.56252 - 0.05586*SI))*AGE
!
END SELECT
!
RETURN
END
!**END OF CODE SEGMENT
