SUBROUTINE SITSET
IMPLICIT NONE
!----------
! WS $Id$
!----------
! THIS SUBROUTINE LOADS THE SITEAR ARRAY WITH A SITE INDEX FOR EACH
! SPECIES WHICH WAS NOT ASSIGNED A SITE INDEX BY KEYWORD.
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'VOLSTD.f90'
!
!
!OMMONS
!----------
LOGICAL DEBUG
CHARACTER FORST*2,DIST*2,PROD*2,VAR*2,VOLEQ*11
INTEGER ISPC,I,INTFOR,IREGN,J,JJ,K,IFIASP, ERRFLAG
REAL SIAGE(MAXSP),SI(MAXSP),SDICON(MAXSP),AG,SINDX,TEMSI
!----------
!     SPECIES LIST FOR WESTERN SIERRAS VARIANT.
!
!     1 = SUGAR PINE (SP)                   PINUS LAMBERTIANA
!     2 = DOUGLAS-FIR (DF)                  PSEUDOTSUGA MENZIESII
!     3 = WHITE FIR (WF)                    ABIES CONCOLOR
!     4 = GIANT SEQUOIA (GS)                SEQUOIADENDRON GIGANTEAUM
!     5 = INCENSE CEDAR (IC)                LIBOCEDRUS DECURRENS
!     6 = JEFFREY PINE (JP)                 PINUS JEFFREYI
!     7 = CALIFORNIA RED FIR (RF)           ABIES MAGNIFICA
!     8 = PONDEROSA PINE (PP)               PINUS PONDEROSA
!     9 = LODGEPOLE PINE (LP)               PINUS CONTORTA
!    10 = WHITEBARK PINE (WB)               PINUS ALBICAULIS
!    11 = WESTERN WHITE PINE (WP)           PINUS MONTICOLA
!    12 = SINGLELEAF PINYON (PM)            PINUS MONOPHYLLA
!    13 = PACIFIC SILVER FIR (SF)           ABIES AMABILIS
!    14 = KNOBCONE PINE (KP)                PINUS ATTENUATA
!    15 = FOXTAIL PINE (FP)                 PINUS BALFOURIANA
!    16 = COULTER PINE (CP)                 PINUS COULTERI
!    17 = LIMBER PINE (LM)                  PINUS FLEXILIS
!    18 = MONTEREY PINE (MP)                PINUS RADIATA
!    19 = GRAY PINE (GP)                    PINUS SABINIANA
!         (OR CALIFORNIA FOOTHILL PINE)
!    20 = WASHOE PINE (WE)                  PINUS WASHOENSIS
!    21 = GREAT BASIN BRISTLECONE PINE (GB) PINUS LONGAEVA
!    22 = BIGCONE DOUGLAS-FIR (BD)          PSEUDOTSUGA MACROCARPA
!    23 = REDWOOD (RW)                      SEQUOIA SEMPERVIRENS
!    24 = MOUNTAIN HEMLOCK (MH)             TSUGA MERTENSIANA
!    25 = WESTERN JUNIPER (WJ)              JUNIPERUS OCIDENTALIS
!    26 = UTAH JUNIPER (UJ)                 JUNIPERUS OSTEOSPERMA
!    27 = CALIFORNIA JUNIPER (CJ)           JUNIPERUS CALIFORNICA
!    28 = CALIFORNIA LIVE OAK (LO)          QUERCUS AGRIFOLIA
!    29 = CANYON LIVE OAK (CY)              QUERCUS CHRYSOLEPSIS
!    30 = BLUE OAK (BL)                     QUERCUS DOUGLASII
!    31 = CALIFORNIA BLACK OAK (BO)         QUERQUS KELLOGGII
!    32 = VALLEY OAK (VO)                   QUERCUS LOBATA
!         (OR CALIFORNIA WHITE OAK)
!    33 = INTERIOR LIVE OAK (IO)            QUERCUS WISLIZENI
!    34 = TANOAK (TO)                       LITHOCARPUS DENSIFLORUS
!    35 = GIANT CHINQUAPIN (GC)             CHRYSOLEPIS CHRYSOPHYLLA
!    36 = QUAKING ASPEN (AS)                POPULUS TREMULOIDES
!    37 = CALIFORNIA-LAUREL (CL)            UMBELLULARIA CALIFORNICA
!    38 = PACIFIC MADRONE (MA)              ARBUTUS MENZIESII
!    39 = PACIFIC DOGWOOD (DG)              CORNUS NUTTALLII
!    40 = BIGLEAF MAPLE (BM)                ACER MACROPHYLLUM
!    41 = CURLLEAF MOUNTAIN-MAHOGANY (MC)   CERCOCARPUS LEDIFOLIUS
!    42 = OTHER SOFTWOODS (OS)
!    43 = OTHER HARDWOODS (OH)
!
!  SURROGATE EQUATION ASSIGNMENT:
!
!    FROM EXISTING WS EQUATIONS --
!      USE 1(SP) FOR 11(WP) AND 24(MH)
!      USE 2(DF) FOR 22(BD)
!      USE 3(WF) FOR 13(SF)
!      USE 4(GS) FOR 23(RW)
!      USE 8(PP) FOR 18(MP)
!      USE 34(TO) FOR 35(GC), 36(AS), 37(CL), 38(MA), AND 39(DG)
!      USE 31(BO) FOR 28(LO), 29(CY), 30(BL), 32(VO), 33(IO), 40(BM), AND
!                     43(OH)
!
!    FROM CA VARIANT --
!      USE CA11(KP) FOR 12(PM), 14(KP), 15(FP), 16(CP), 17(LM), 19(GP), 20(WE),
!                       25(WJ), 26(WJ), AND 27(CJ)
!      USE CA12(LP) FOR 9(LP) AND 10(WB)
!
!    FROM SO VARIANT --
!      USE SO30(MC) FOR 41(MC)
!
!    FROM UT VARIANT --
!      USE UT17(GB) FOR 21(GB)
!----------
DATA SDICON/ &
    561., 570., 800., 1052., 576., 365., 1000., 365., 679., 621., &
    272., 358., 790., 679., 409., 365., 409., 365., 214., 365., &
    409., 570., 1052., 687., 272., 497., 272., 667., 667., 214., &
    406., 440., 667., 785., 785., 562., 406., 515., 406., 629., &
    501., 365., 406./
!-----------
!  SEE IF WE NEED TO DO SOME DEBUG.
!-----------
CALL DBCHK (DEBUG,'SITSET',6,ICYC)
!
IF(ISISP .LE. 0) ISISP=8
IF(SITEAR(ISISP) .LE. 0.0) SITEAR(ISISP)=100.
!----------
! TRANSLATE THE SITES AND KEEP
!----------
CALL SICHG(ISISP,SITEAR(ISISP),SIAGE)
!----------
! SI IS A VECTOR X MAXSP GIVING EQUIVALENT SITES FOR EACH SPECIES
!----------
IF (DEBUG) WRITE(JOSTND,9003)ISISP,SITEAR(ISISP),SIAGE
9003 FORMAT('SITE SPECIES ',I5,' SITE INDEX ',F10.1, &
     (/,4X,10F6.1))
!
DO 25 ISPC=1,MAXSP
AG=SIAGE(ISPC)
SINDX=SITEAR(ISISP)
!
CALL HTCALC(IFOR,SINDX,ISISP,AG,SI(ISPC),JOSTND,DEBUG)
!
25 CONTINUE
IF (DEBUG) WRITE(JOSTND,9025) SINDX,ISISP,SI
9025 FORMAT('SINDX ',F10.2,'SITE SP ',I5/' TRANSLATED SITES ', &
   (/,10F6.1))
!----------
! IF SITEAR() HAS NOT BEEN SET WITH SITECODE KEYWORD, LOAD
! IT WITH SITE VALUES TRANSLATED FROM SITE INDEX OF SITE SPECIES.
!
! FOR GB USE SITE RANGE OF 20-60; FROM TOM MARTIN R4
! FOR MC USE SITE RANGE OF 5-23; FROM JEPSON MANUAL
! THEN TAKE THE SAME PROPORTION OF THE RANGE AS THE RED FIR SITE INDEX IS TO
! THE RANGE 10-134 (WHICH IS THE DOLPH RED FIR RANGE IN THE SO VARIANT).
!----------
DO 30 I=1,MAXSP
IF(SITEAR(I) .EQ. 0.0) THEN
  SELECT CASE (I)
  CASE(21)
    TEMSI=SI(7)
    IF(TEMSI .LT. 10.0)TEMSI=10.0
    IF(TEMSI .GT. 134.0)TEMSI=134.0
    SITEAR(I)=20.0+(TEMSI-10.0)/(134.0-10.0) &
       *(60.0-20.0)
  CASE(41)
    TEMSI=SI(7)
    IF(TEMSI .LT. 10.0)TEMSI=10.0
    IF(TEMSI .GT. 134.0)TEMSI=134.0
    SITEAR(I)=5.0+(TEMSI-10.0)/(134.0-10.0) &
       *(23.0-5.0)
  CASE DEFAULT
    SITEAR(I)=SI(I)
  END SELECT
ENDIF
30 CONTINUE
!----------
! LOAD THE SDIDEF ARRAY
!----------
DO 40 I=1,MAXSP
  IF(SDIDEF(I) .GT. 0.0) GO TO 40
  IF(BAMAX .GT. 0.) THEN
    SDIDEF(I)=BAMAX/(0.5454154*(PMSDIU/100.))
  ELSE
    SDIDEF(I) = SDICON(I)
  ENDIF
40 CONTINUE
!
DO 92 I=1,15
J=(I-1)*10 + 1
JJ=J+9
IF(JJ.GT.MAXSP)JJ=MAXSP
WRITE(JOSTND,90)(NSP(K,1)(1:2),K=J,JJ)
90 FORMAT(/'SPECIES ',5X,10(A2,6X))
WRITE(JOSTND,91)(NINT(SDIDEF(K)),K=J,JJ )
91 FORMAT('SDI MAX ',   10I8.0)
IF(JJ .EQ. MAXSP)GO TO 93
92 CONTINUE
93 CONTINUE
!----------
!  LOAD VOLUME EQUATION ARRAYS FOR ALL SPECIES
!----------
INTFOR = KODFOR - (KODFOR/100)*100
WRITE(FORST,'(I2)')INTFOR
IF(INTFOR.LT.10)FORST(1:1)='0'
IREGN = KODFOR/100
DIST='  '
PROD='  '
VAR='WS'
!
IF (LFIANVB) CALL NVB_REGION_CHECK
DO ISPC=1,MAXSP
READ(FIAJSP(ISPC),'(I4)')IFIASP
VOLEQ='           '
IF(((METHC(ISPC).EQ.6).OR.(METHC(ISPC).EQ.9)).AND. &
        (VEQNNC(ISPC).EQ.'           '))THEN
  CALL VOLEQDEF(VAR,IREGN,FORST,DIST,IFIASP,PROD,VOLEQ,ERRFLAG)
  VEQNNC(ISPC)=VOLEQ
ELSE IF (METHC(ISPC).EQ.10) THEN
  CALL NVBEQDEF(IFIASP,VOLEQ)
  VEQNNC(ISPC)=VOLEQ
ENDIF
IF(((METHB(ISPC).EQ.6).OR.(METHB(ISPC).EQ.9)).AND. &
        (VEQNNB(ISPC).EQ.'           '))THEN
  VOLEQ='           '
  CALL VOLEQDEF(VAR,IREGN,FORST,DIST,IFIASP,PROD,VOLEQ,ERRFLAG)
  VEQNNB(ISPC)=VOLEQ
ENDIF
ENDDO
!----------
!  IF FIA CODES WERE IN INPUT DATA, WRITE TRANSLATION TABLE
!---------
IF(LFIA) THEN
  CALL FIAHEAD(JOSTND)
  WRITE(JOSTND,211) (NSP(I,1)(1:2),FIAJSP(I),I=1,MAXSP)
211   FORMAT ((T12,8(A3,'=',A6,:,'; '),A,'=',A6))
ENDIF
!----------
!  WRITE VOLUME EQUATION NUMBER TABLE
!----------
CALL VOLEQHEAD(JOSTND)
WRITE(JOSTND,230)(NSP(J,1)(1:2),VEQNNC(J),VEQNNB(J),J=1,MAXSP)
230 FORMAT(4(2X,A2,4X,A11,1X,A10,1X))
!
RETURN
END
