SUBROUTINE DISPLY
IMPLICIT NONE
!----------
! METRIC-BASE $Id$
!----------
!  **DISPLY** PRINTS STAND AND TREE STATISTICS AT THE BEGINNING
!  OF THE PROJECTION, AND AT THE END OF EACH CYCLE.  ESTIMATES
!  STAND AGE IF MISSING FROM THE STNDINFO KEYWORD
!----------
!OMMONS
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'OUTCOM.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'ECON.f90'
!
!
INCLUDE 'SCREEN.f90'
!
!
INCLUDE 'SUMTAB.f90'
!
!
INCLUDE 'VARCOM.f90'
!
!
INCLUDE 'METRIC.f90'
!
!
!OMMONS
!
!----------
!  DIMENSIONS FOR INTERNAL VARIABLES (USED AS OUTPUT LABELS):
!----------
INTEGER IRT,JYR,I,IOAGE,IKNT,IXF,IFIA,ISWT,J,JSDI,ISNOFT
INTEGER IRTNCD
REAL DUM1,SUMAGE,AGEKNT,SDIBCTMP,SDIACTMP
CHARACTER*9 AT1,AT2,AT3,AT4
CHARACTER*10 STD(3)
!----------
!  DATA STATEMENTS:
!----------
DATA AT1/'REMOVAL  '/,AT2/'VOLUME:  '/,AT3/ &
    'RESIDUAL '/,AT4/'ACCRETION'/
!----------
!  IF ICL6 IS NEGATIVE,  PROJECTION IS COMPLETE AND WE NEED ONLY TO
!  PRINT THE FINAL LINE FOR  THE SAMPLE TREE OUTPUT  (DISPLAYING
!  STAND ATTRIBUTES FOLLOWING THINNING), AND THE FINAL LINE OF THE
!  SUMMARY OUTPUT.   BRANCH TO STATEMENT 34.
!----------
IF (.NOT.LSTART.OR.ITABLE(2).EQ.1) GO TO 10
IRT = 0
WRITE (JOTREE) IRT,NPLT,MGMID
10 CONTINUE
IF(ICL6.LT.0) GO TO 34
!----------
!  ASSIGN JYR.
!----------
JYR=IY(ICYC+1)
!----------
!   IF USER HAS SPECIFIED KEYWORDS THAT ALTER VOLUME EQUATION PARAMETERS
!   (IE VOLUMME BFVOLUME,ETC) THEN PRINT LABEL THAT INDICATES USER
!   SPECIFIED STANDARDS. THESE LABLES ARE VARIANT SPECIFIC
!----------
IF ((VARACD .EQ. 'CS') .OR. (VARACD .EQ. 'LS') .OR. &
       (VARACD .EQ. 'NE') .OR. (VARACD .EQ. 'SN')) THEN
!
   IF (LCVOLS) THEN
      STD(1)='USER MERCH'
      STD(2)='SAWLG'
   ELSE
      STD(1)='MERCH'
      STD(2)='SAWLG'
   ENDIF
!
   IF (LBVOLS) THEN
      STD(3)='USER SAWLG'
   ELSE
      STD(3)='SAWLG'
   ENDIF
!
ELSEIF ((VARACD .EQ. 'ON')) THEN
!
   IF (LCVOLS) THEN
      STD(1)='GTV'
      STD(2)='GMV'
   ELSE
      STD(1)='GTV'
      STD(2)='GMV'
   ENDIF
!
   IF (LBVOLS) THEN
      STD(3)='NMV'
   ELSE
      STD(3)='NMV'
   ENDIF
!
ELSE
!
  IF (LCVOLS) THEN
     STD(1)='USER TOTAL'
     STD(2)='USER MERCH'
  ELSE
     STD(1)='TOTAL'
     STD(2)='MERCH'
  ENDIF
!
  IF (LBVOLS) THEN
     STD(3)='USER MERCH'
  ELSE
     STD(3)='MERCH'
  ENDIF
ENDIF
!----------
!  WRITE REMOVAL STATISTICS.  BYPASS IF LSTART IS TRUE OR NUMBER
!  OF TREES REMOVED WAS LESS THAN OR EQUAL TO ZERO.
!  SKIP PRINTING OF STAND COMPOSITION TABLE IF NOT WANTED.
!----------
IF (ITABLE(1) .EQ. 1) GO TO 32
IF(LSTART) GO TO 30
IF(ONTREM(7).LE.0.0) GO TO 20
WRITE(JOSTND,9003)
9003 FORMAT(/)
WRITE(JOSTND,9004) AT1, &
                      (ONTREM(I)*INtoCM,I=1,6), &
                      ONTREM(7)/ACRtoHA, &
                      (OSPTT(I),IOSPTT(I),I=1,4)
9004 FORMAT(6X,A9,3X,5F7.1,F8.1,F9.0,' TREES   ', &
          3(F5.0,'% ',A3,','),F5.0,'% ',A3)
!
SELECT CASE (VARACD)
  CASE ('BC')
    WRITE(JOSTND,9008) AT2, &
                      STD(1), &
                      (OCVREM(I)*INtoCM,I=1,6), &
                      OCVREM(7)*FT3pACRtoM3pHA, &
                      (OSPTV(I),IOSPTV(I),I=1,4), &
                      STD(2), &
                      (OMCREM(I)*INtoCM,I=1,6), &
                      OMCREM(7)*FT3pACRtoM3pHA, &
                      (OSPMR(I),IOSPTV(I),I=1,4)
  CASE DEFAULT
    WRITE(JOSTND,9005) AT2, &
                      STD(1), &
                      (OCVREM(I)*INtoCM,I=1,6), &
                      OCVREM(7)*FT3pACRtoM3pHA, &
                      (OSPTV(I),IOSPTV(I),I=1,4), &
                      STD(2), &
                      (OMCREM(I)*INtoCM,I=1,6), &
                      OMCREM(7)*FT3pACRtoM3pHA, &
                      (OSPMR(I),IOSPTV(I),I=1,4), &
                      STD(3), &
                      (OBFREM(I)*INtoCM,I=1,6), &
                      OMCREM(7)*FT3pACRtoM3pHA
END SELECT
9005 FORMAT(6X,A9/8X,A10,5F7.1,F8.1,F9.0,' CU M    ', &
          3(F5.0,'% ',A3,','),F5.0,'% ',A3/ &
         8X,A10,5F7.1,F8.1,F9.0,' CU M    ', &
          3(F5.0,'% ',A3,','),F5.0,'% ',A3/ &
         8X,A10,5F7.1,F8.1,F9.0,' CU M    ', &
          3(F5.0,'% ',A3,','),F5.0,'% ',A3)
9008 FORMAT(6X,A9/8X,A10,5F7.1,F8.1,F9.0,' CU M    ', &
          3(F5.0,'% ',A3,','),F5.0,'% ',A3/ &
         8X,A10,5F7.1,F8.1,F9.0,' CU M    ', &
          3(F5.0,'% ',A3,','),F5.0,'% ',A3)
!
WRITE(JOSTND,9003)
WRITE(JOSTND,9004) AT3, &
                      (ONTRES(I)*INtoCM,I=1,6), &
                      ONTRES(7)/ACRtoHA, &
                      (OSPRT(I),IOSPRT(I),I=1,4)
!----------
!  WRITE ACCRETION AND MORTALITY STATISTICS.  BYPASSED IF LSTART
!  IS TRUE. IF MORTALITY FUNCTIONS HAVE BEEN MODIFIED BY CERTAIN
!  KEYWORDS THEN CHANGE LABEL FROM 'MORTALITY' TO 'USER MORT'.
!----------
20 CONTINUE
WRITE(JOSTND,9003)
WRITE(JOSTND,9006) AT4, &
                      (OACC(I)*INtoCM,I=1,6), &
                       OACC(7)*FT3pACRtoM3pHA, &
                      (OSPAC(I),IOSPAC(I),I=1,4)
!
IF (LMORT) THEN
  WRITE(JOSTND,9006) 'USER MORT', &
                        (OMORT(I)*INtoCM,I=1,6), &
                        OMORT(7)*FT3pACRtoM3pHA, &
                        (OSPMO(I),IOSPMO(I),I=1,4)
ELSE
  WRITE(JOSTND,9006) 'MORTALITY', &
                        (OMORT(I)*INtoCM,I=1,6), &
                        OMORT(7)*FT3pACRtoM3pHA, &
                        (OSPMO(I),IOSPMO(I),I=1,4)
ENDIF
9006 FORMAT(6X,A9,3X,5F7.1,F8.1,F9.0,' CU M/YR ', &
          3(F5.0,'% ',A3,','),F5.0,'% ',A3)
!----------
!  WRITE CURRENT STAND STATISTICS.
!----------
30 CONTINUE
WRITE(JOSTND,9003)
WRITE(JOSTND,9007) JYR, &
                      (ONTCUR(I)*INtoCM,I=1,6), &
                      ONTCUR(7)/ACRtoHA, &
                      (OSPCT(I),IOSPCT(I),I=1,4)
9007 FORMAT(/I4,'  TREES',T19,5F7.1,F8.1,F9.0,' TREES   ', &
          3(F5.0,'% ',A3,','),F5.0,'% ',A3)
!
SELECT CASE (VARACD)
  CASE ('BC')
    WRITE(JOSTND,9008) AT2, &
                      STD(1), &
                      (OCVCUR(I)*INtoCM,I=1,6), &
                      OCVCUR(7)*FT3pACRtoM3pHA, &
                      (OSPCV(I),IOSPCV(I),I=1,4), &
                      STD(2), &
                      (OMCCUR(I)*INtoCM,I=1,6), &
                      OMCCUR(7)*FT3pACRtoM3pHA, &
                      (OSPMC(I),IOSPMC(I),I=1,4)
  CASE DEFAULT
    WRITE(JOSTND,9005) AT2, &
                      STD(1), &
                      (OCVCUR(I)*INtoCM,I=1,6), &
                      OCVCUR(7)*FT3pACRtoM3pHA, &
                      (OSPCV(I),IOSPCV(I),I=1,4), &
                      STD(2), &
                      (OMCCUR(I)*INtoCM,I=1,6), &
                      OMCCUR(7)*FT3pACRtoM3pHA, &
                      (OSPMC(I),IOSPMC(I),I=1,4), &
                      STD(3), &
                      (OBFCUR(I)*INtoCM,I=1,6), &
                      OBFCUR(7)*FT3pACRtoM3pHA, &
                      (OSPBV(I),IOSPBV(I),I=1,4)
END SELECT
32 CONTINUE
!----------
!  WRITE OUTPUT FOR SAMPLE TREES.  FIRST, OUTPUT STAND CONDITIONS
!  FOR PREVIOUS CYCLE.  BYPASS IF LSTART IS TRUE. ALSO SKIP TREE
!  DATA IF TABLE IS NOT DESIRED.
!----------
IF(LSTART) GO TO 39
34 CONTINUE
IOAGE=IAGE+IY(ICYC)-IY(1)
IF (ITABLE(2) .EQ. 1) GO TO 41
!----------
!  GO TO STATEMENT 35 AND WRITE BOTH PRE AND POST THINNING STATISTICS
!  IF THINNING OCCURRED IN PREVIOUS CYCLE.
!----------
IF(LZEIDE)THEN
  JSDI=INT(SDIBC2 + 0.5)
ELSE
  JSDI=INT(SDIBC + 0.5)
ENDIF
IF(ONTREM(7).GT.0.0) GO TO 35
IRT=1
WRITE(JOTREE) IRT, &
                 IOAGE, &
                 ORMSQD*INtoCM, &
                 OLDTPA/ACRtoHA, &
                 OLDBA*FT2pACRtoM2pHA, &
                 OLDAVH*FTtoM, &
                 RELDM1, &
                 JSDI/ACRtoHA
GO TO 36
35 CONTINUE
IRT=2
WRITE(JOTREE) IRT, &
                 IOAGE, &
                 ORMSQD*INtoCM, &
                 OLDTPA/ACRtoHA, &
                 OLDBA*FT2pACRtoM2pHA, &
                 OLDAVH*FTtoM, &
                 RELDM1, &
                 JSDI/ACRtoHA
IRT=3
JSDI=INT(SDIAC + 0.5)
IF(LZEIDE)THEN
  JSDI=INT(SDIAC2 + 0.5)
ELSE
  JSDI=INT(SDIAC + 0.5)
ENDIF
WRITE(JOTREE) IRT, &
                 ATAVD*INtoCM, &
                 ATTPA/ACRtoHA, &
                 ATBA*FT2pACRtoM2pHA, &
                 ATAVH*FTtoM, &
                 ATCCF, &
                 JSDI/ACRtoHA
36 CONTINUE
!----------
!  IF ICL6.LT.0 BRANCH TO STMT. 90 TO LOAD LAST LINE OF SUMMARY OUTPUT
!----------
IF(ICL6.LT.0) GO TO 90
!----------
!  WRITE YEAR  AND PERIOD LENGTH.
!----------
39 CONTINUE
IF(ITABLE(2).EQ.1)GO TO 41
!-------
!  IF SAMPLE TREES WERE RESELECTED THIS CYCLE (IFST=99), THEN SET
!  SIGN OF YEAR NEGETIVE.
!-------
I=JYR
IF (IFST.EQ.0) GOTO 40
IFST=0
IF (LSTART) GOTO 40
I=-I
40 CONTINUE
IRT=4
WRITE(JOTREE) IRT,I,IFINT
!----------
!  WRITE EXAMPLE TREE DATA.
!----------
IRT=5
WRITE(JOTREE) IRT, &
                 IONSP, &
                 DBHIO*INtoCM, &
                 HTIO*FTtoM, &
                 IOICR, &
                 DGIO*INtoCM, &
                 PCTIO, &
                 PRBIO/ACRtoHA
41 CONTINUE
!----------
!  LOAD THE ARRAY CONTAINING SUMMARY DATA.
!----------
IKNT=ICYC+1
!----------
!  CALCULATE FOREST TYPE (IFORTP), SIZE CLASS (ISZCL),
!  AND STOCKING CLASS (ISTCL)
!----------
DUM1=0.
IXF=2
ISNOFT=IFORTP
CALL FORTYP(IXF,DUM1)
!----------
!  ESTIMATE STAND AGE FROM SIZE CLASS AND ABIRTH
!  IF IT WAS MISSING FROM THE INPUT DATA, SET IT FROM THIS ESTIMATE..
!----------
IF(LSTART)THEN
!----------
!  INITIALIZE THE SUM OF REMOVALS
!---------
  TRTPA   = 0.
  TRTCUFT = 0.
  TRMCUFT = 0.
  TRBDFT  = 0.
  SUMAGE=0.
  AGEKNT=0.
!*        WRITE(JOSTND,*)' IAGE,ISZCL,ITRN= ',IAGE,ISZCL,ITRN
  IF(ISZCL.EQ.0 .OR. ISZCL.GT.3)THEN
    ICAGE=0
    GO TO 42
  ELSEIF(ISZCL .EQ. 3) THEN
    DO I=1,ITRN
    IF(DBH(I).LT.5.)THEN
      SUMAGE=SUMAGE+ABIRTH(I)*PROB(I)
      AGEKNT=AGEKNT+PROB(I)
!*            WRITE(JOSTND,*)' I,D,AGE,PROB,SUMAGE,AGEKNT= ',
!*     &      I,DBH(I),ABIRTH(I),PROB(I),SUMAGE,AGEKNT
    ENDIF
    ENDDO
  ELSEIF(ISZCL .EQ. 2) THEN
    DO I=1,ITRN
    IF(FIAJSP(ISP(I))(1:1).EQ.'-')THEN
      IFIA=998
    ELSE
      READ(FIAJSP(ISP(I)),'(I4)') IFIA
    ENDIF
    IF((IFIA.LT.300. .AND. DBH(I).GE.5. .AND. DBH(I).LT.9.) .OR. &
          (IFIA.GE.300. .AND. DBH(I).GE.5. .AND. DBH(I).LT.11.))THEN
      SUMAGE=SUMAGE+ABIRTH(I)*PROB(I)
      AGEKNT=AGEKNT+PROB(I)
!*            WRITE(JOSTND,*)' I,IFIA,D,AGE,PROB,SUMAGE,AGEKNT= ',
!*     &      I,IFIA,DBH(I),ABIRTH(I),PROB(I),SUMAGE,AGEKNT
    ENDIF
    ENDDO
  ELSE
    DO I=1,ITRN
    IF(FIAJSP(ISP(I))(1:1).EQ.'-')THEN
      IFIA=998
    ELSE
      READ(FIAJSP(ISP(I)),'(I4)') IFIA
    ENDIF
    IF((IFIA.LT.300. .AND. DBH(I).GE.9.) .OR. &
          (IFIA.GE.300. .AND. DBH(I).GE.11.))THEN
      SUMAGE=SUMAGE+ABIRTH(I)*PROB(I)
      AGEKNT=AGEKNT+PROB(I)
!*            WRITE(JOSTND,*)' I,IFIA,D,AGE,PROB,SUMAGE,AGEKNT= ',
!*     &      I,IFIA,DBH(I),ABIRTH(I),PROB(I),SUMAGE,AGEKNT
    ENDIF
    ENDDO
  ENDIF
  IF(AGEKNT.GT.0.)THEN
!*        WRITE(JOSTND,*)' AGEKNT= ',AGEKNT
    ICAGE=IFIX(SUMAGE/AGEKNT)
  ELSE
    ICAGE=0
  ENDIF
!*        WRITE(JOSTND,*)' SUMAGE,AGEKNT,ICAGE= ',SUMAGE,AGEKNT,ICAGE
!----------
!  REMOVE THE COMMENT CHARACTERS (C**) IN THE FOLLOWING STATEMENT
!  TO ENABLE REPORTING THE INITIAL STAND AGE, AGECMP, (IF 0 IN STDINFO
!  KEYWORD) IN THE SUMMARY STATISTICS TABLE.  DO **NOT** USE FOR THE
!  FOLLOWING VARIANTS, AK, CI, IE, KT, NI, TT, UT, WS,
!  WHICH DO NOT CONSISTENTLY USE SITE CURVES FOR HEIGHT GROWTH.
!----------
!**        IF(IAGE .EQ. 0)IAGE=ICAGE
ENDIF
42 CONTINUE
!
IOSUM(01,IKNT)=IY(IKNT)
IOSUM(03,IKNT)=INT(ONTCUR(7)/GROSPC+0.5)
IOSUM(04,IKNT)=INT(OCVCUR(7)/GROSPC+0.5)
IOSUM(05,IKNT)=INT(OMCCUR(7)/GROSPC+0.5)
IOSUM(06,IKNT)=INT(OBFCUR(7)/GROSPC+0.5)
!
IOSUM(18,IKNT)=IFORTP
IOSUM(19,IKNT)=ISZCL
IOSUM(20,IKNT)=ISTCL
!----------
!  IF LSTART IS TRUE,  DONT LOAD REMOVAL AND GROWTH STATISTICS.
!----------
IF(LSTART) GOTO 100
!----------
!  ENTER HERE TO LOAD FINAL LINE OF SUMMARY OUTPUT.
!----------
90 CONTINUE
IKNT=ICYC
IOSUM(02,IKNT)=IOAGE
IF (ONTREM(7).LE.0.0) GOTO 91
IOSUM(03,IKNT)=INT(OLDTPA/GROSPC+.5)
IOSUM(11,IKNT)=INT(ATBA/GROSPC+0.5)
IOSUM(12,IKNT)=INT(ATCCF/GROSPC+0.5)
IOSUM(13,IKNT)=INT(ATAVH+0.5)
QDBHAT(IKNT)=ATAVD
SDIACTMP=SDIAC
IF(LZEIDE)SDIACTMP=SDIAC2
ISDIAT(IKNT)=INT(SDIACTMP/GROSPC+0.5)
GOTO 92
91 CONTINUE
IOSUM(11,IKNT)=INT(OLDBA/GROSPC+0.5)
IOSUM(12,IKNT)=INT(RELDM1/GROSPC+0.5)
IOSUM(13,IKNT)=INT(OLDAVH+0.5)
QDBHAT(IKNT)=ORMSQD
SDIBCTMP=SDIBC
IF(LZEIDE)SDIBCTMP=SDIBC2
ISDIAT(IKNT)=INT(SDIBCTMP/GROSPC+0.5)
92 CONTINUE
SDIBCTMP=SDIBC
IF(LZEIDE)SDIBCTMP=SDIBC2
ISDI(IKNT)=INT(SDIBCTMP/GROSPC+0.5)
IOSUM(07,IKNT)=INT(ONTREM(7)/GROSPC+0.5)
IOSUM(08,IKNT)=INT(OCVREM(7)/GROSPC+0.5)
IOSUM(09,IKNT)=INT(OMCREM(7)/GROSPC+0.5)
IOSUM(10,IKNT)=INT(OBFREM(7)/GROSPC+0.5)
!----------
!  SUM THE REMOVALS
!---------
IF (IKNT.LE.NCYC) THEN
  TRTPA   = TRTPA   + ONTREM(7)
  TRTCUFT = TRTCUFT + OCVREM(7)
  TRMCUFT = TRMCUFT + OMCREM(7)
  TRBDFT  = TRBDFT  + OBFREM(7)
ENDIF
IOSUM(14,IKNT)=IFINT
IOSUM(15,IKNT)=INT(OACC(7)/GROSPC+0.5)
IOSUM(16,IKNT)=INT(OMORT(7)/GROSPC+0.5)
QSDBT(IKNT)=ORMSQD
IOLDBA(IKNT)=INT(OLDBA/GROSPC+0.5)
IBTCCF(IKNT)=INT(RELDM1/GROSPC+0.5)
IBTAVH(IKNT)=INT(OLDAVH+0.5)
IF (SAMWT .GE. .99999) ISWT = IFIX(SAMWT+.0001)
IF (SAMWT .LT. .99999) ISWT = IFIX(SAMWT*100000.+.5)
IOSUM(17,IKNT)=ISWT
100 CONTINUE
IF (ICL6 .GT. 0) GO TO 150
!----------
!  PRINT THE EXAMPLE TREE RECORD AND STAND ATTRIBUTE TABLE.
!  IF NOT DESIRED THEN SKIP.
!----------
IF (ITABLE(2) .EQ. 1) GO TO 125
!----------
!  WRITE AN END OF FILE MARK ON SUMMARY TREE SCRATCH FILE.
!----------
ENDFILE JOTREE
CALL PRTEXM (JOTREE,JOSTND,ITITLE)
CALL fvsGetRtnCode(IRTNCD)
IF (IRTNCD.NE.0) RETURN
125 CONTINUE
!----------
!  PRINT THE SUMMARY OUTPUT
!----------
DO 130 I=7,10
IOSUM(I,IKNT)=0
130 CONTINUE
DO 140 I=14,16
IOSUM(I,IKNT)=0
140 CONTINUE
!----------
!  LOAD FINAL MAI VALUE
!----------
IF(MAIFLG .EQ. 0)THEN
  IF(IOSUM(2,IKNT).GT.0.)THEN
    IF ((VARACD .EQ. 'CS') .OR. (VARACD .EQ. 'LS') .OR. &
           (VARACD .EQ. 'NE') .OR. (VARACD .EQ. 'SN') .OR. &
           (VARACD .EQ. 'ON')) THEN
      BCYMAI(IKNT)=(IOSUM(4,IKNT)+TOTREM)/IOSUM(2,IKNT)
    ELSE
      BCYMAI(IKNT)=(IOSUM(5,IKNT)+TOTREM)/IOSUM(2,IKNT)
    ENDIF
  ELSE
    BCYMAI(IKNT)=0.
  ENDIF
ELSE
  BCYMAI(IKNT)=0.
ENDIF
!----------
!     CALL **ECEND** TO OUTPUT LAST LINES OF ECONOMIC OUTPUT
!----------
IF (LECON) CALL ECEND
I=0
IF (LSUMRY) I=JOSUM
!---------
!     SKIP PRINTING OF SUMMARY OUTPUT IF NOT DESIRED.
!---------
J=JOSTND
IF (ITABLE(3).EQ.1) J=0
CALL GROHED (JOSTND)
CALL LBSPLW (JOSTND)
CALL SUMOUT (IOSUM,20,0,JOSTND,J,I,IKNT,MGMID,NPLT,SAMWT, &
   ITITLE,IPTINV)
CALL OPLIST (.FALSE.,NPLT,MGMID,ITITLE)
!----------
!     CALL ECLBL TO OUTPUT ECONOMIC LABEL INFORMATION.
!----------
IF (LECON) CALL ECLBL
150 CONTINUE
IF (LSTART.AND.LSCRN) CALL SUMHED
IF ((.NOT.LSTART).AND.LSCRN) &
     WRITE (JOSCRN,170) IOSUM(1,IKNT), &
       NINT(IOSUM(3,IKNT)/ACRtoHA), &
       NINT(IOLDBA(IKNT)*FT2pACRtoM2pHA), &
       NINT(ISDI(IKNT)/ACRtoHA), &
       NINT(IBTAVH(IKNT)*FTtoM), &
       QSDBT(IKNT)*INtoCM, &
       NINT(IOSUM(4,IKNT)*FT3pACRtoM3pHA), &
       NINT(IOSUM(7,IKNT)/ACRtoHA), &
       NINT(IOSUM(8,IKNT)*FT3pACRtoM3pHA ), &
       NINT(IOSUM(9,IKNT)*FT3pACRtoM3pHA), &
       NINT(IOSUM(11,IKNT)*FT2pACRtoM2pHA), &
       NINT(ISDIAT(IKNT)/ACRtoHA), &
       NINT(IOSUM(13,IKNT)*FTtoM), &
       QDBHAT(IKNT)*INtoCM, &
       NINT(IOSUM(15,IKNT)*FT3pACRtoM3pHA), &
       NINT(IOSUM(16,IKNT)*FT3pACRtoM3pHA)
170 FORMAT (I4,I6,3I4,F5.1,4I6,3I4,F5.1,I4,I4)
IF (.NOT.LSTART) CALL DBSSUMRY2
RETURN
END
