SUBROUTINE BADIST(DEBUG)
IMPLICIT NONE
!----------
! ACD $Id$
!----------
!
! COMMONS
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'TWIGCOM.f90'
!
! COMMONS
!----------
LOGICAL DEBUG
!
INTEGER I,J,ICLS
REAL TDBH,TREEBA
!
!----------
!  INITIALIZE VARIABLES.
!----------
DO  5 J=1,50
EBAU(J) = 0.0
5 CONTINUE
!----------
!  COMPUTE BA BY DBH CLASS, BA BY SPECIES, AND BA BY DBH CLASS BY
!  SPECIES.
!----------
DO 100 I=1,ITRN
ICLS = IFIX(DBH(I) + 1.0)
IF(ICLS .GT. 50) ICLS = 50
TDBH = DBH(I)
IF(TDBH .LT. 1.0) TDBH=1.0
TREEBA = 0.0054542 * TDBH * TDBH * PROB(I)
EBAU(ICLS) = EBAU(ICLS) + TREEBA
100 CONTINUE
DO 150 I=49,1,-1
150   EBAU(I)=EBAU(I+1)+EBAU(I)
RETURN
END
