SUBROUTINE FINDAG(I,ISPC,D1,D2,H,SITAGE,SITHT,AGMAX,HTMAX1,HTMAX2, &
                     DEBUG)
IMPLICIT NONE
!----------
! ACD $Id$
!----------
!  THIS ROUTINE FINDS EFFECTIVE TREE AGE
!  CALLED FROM **COMCUP
!  CALLED FROM **CRATET
!----------
!  COMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'PLOT.f90'
!
!  COMMONS
!----------
!  DECLARATIONS
!----------
LOGICAL DEBUG
INTEGER I,ISPC,MODE0,IVAR
REAL D1,D2,SITAGE,SITHT,AGMAX,HTMAX1,HTMAX2
REAL HTG1,H,YRS,HTMAX,AGET
!
HTG1=0.
!----------
!   CALL HTCALC TO CALCULATE AGE BASED ON INITIAL TREE HEIGHT
!----------
MODE0= 0
IVAR=3
YRS=10.
CALL HTCALC (MODE0,IVAR,ISPC,SITEAR(ISPC),YRS,H,AGET,HTMAX, &
                HTG1,JOSTND,DEBUG)
!----------
!  IF H >= HTMAX THEN CALCULATE AGE BASED ON HTMAX - 1. FT.
!  THE FORMULA FOR AGE IS UNSTABLE FOR HEIGHTS >= HTMAX.
!----------
IF (HTMAX-H.LE.1.) THEN
  H = HTMAX - 1.1
  CALL HTCALC (MODE0,IVAR,ISPC,SITEAR(ISPC),YRS,H,AGET,HTMAX, &
                  HTG1,JOSTND,DEBUG)
ENDIF
!
SITAGE = AGET
!
  IF(DEBUG)WRITE(JOSTND,91200)I,ISPC,AGET,H
91200   FORMAT(' FINDAG - I,ISPC,AGE,H ',2I5,2F10.2)
!
IF(DEBUG)WRITE(JOSTND,50)
50 FORMAT(' LEAVING SUBROUTINE FINDAG')
!
RETURN
END
!**END OF CODE SEGMENT
