!ODE SEGMENT BMPRM
!----------
! WWPB $Id$
!----------
!
!     PARAMETERS FOR THE PINE BEETLE MODEL ARE:
!
INTEGER   MXDWHC,MXDWPC,MXDWHZ,MXDWSZ,MXDWAG,MXSPTT
INTEGER   NPBSP, NSCL, NUMRV
REAL      PIE, V2T

PARAMETER (MXDWHC=2)
PARAMETER (MXDWPC=3)
PARAMETER (MXDWHZ=3)
PARAMETER (MXDWSZ=2)
PARAMETER (MXDWAG=5)
PARAMETER (MXSPTT=5)
PARAMETER (NPBSP=4)
PARAMETER (NUMRV=9)
PARAMETER (NSCL=10)
PARAMETER (PIE=3.14159)
PARAMETER (V2T=0.01)


!     MXDWHC= THE MAX NUMBER OF CATEGORIES FOR HOST DEAD WOODY
!             POOLS FOR IPS (1=STANDING; 2=DEAD)
!     MXDWPC= THE MAX NUMBER OF CATEGORIES FOR DEAD WOODY
!             POOLS
!     MXDWHZ= THE MAX NUMBER OF DEAD WOODY HOST SIZE CLASSES (HOST ONLY)
!     MXDWSZ= THE MAX NUMBER OF DOWNED DEAD POOL SIZE CLASSES (1=<3",2=>3")
!             (STANDING SWP HAS MXDWHZ+1 SIZE CLASSES)
!     MXDWAG= THE MAX NUMBER OF DEAD WOODY POOL AGE CLASSES
!     MXSPTT= THE MAXIMUM NUMBER OF "SPECIAL TREE" TYPES FOR EACH PB
!     NUMRV:  Number of pieces (DVs) that go into calculating an overall RV
!     NPBSP=  THE NUMBER OF PINE BEETLE SPECIE(S) TYPES SIMULATED
!     NSCL=   THE NUMBER OF DBH SIZE CLASSES CONSIDERED BY PINE BEETLE
!             MODEL
!     PIE=    THE VALUE OF PI
!     V2T=    CONVERSION FROM CUBIC FT TO TONS: .01=20/2000

!-----END SEGMENT
