SUBROUTINE BMRANN(SEL)
!----------
! WWPB $Id$
!----------
!
!     THIS RANDOM NUMBER GENERATOR WAS MODIFIED FROM THE ALGORTHM
!     FOUND IN IN THE IMSL LIBRARY VOL 1 EDITION 4 TO 5,
!     DEC. 1, 1975, AND CAN BE FOUND IN THE FOLLOWING REFERENCES:
!
!     LEWIS, P.A.W., GOODMAN, A.S., AND MILLER, J.M. PSUEDO-RANDOM
!     NUMBER GENERATOR FOR THE SYSTEM/360, IBM SYSTEMS JOURNAL, NO. 2,
!     1969.
!
!     LEARMONTH, G.P. AND LEWIS, P.A.W., NAVAL POSTGRADUATE SCHOOL
!     RANDOM NUMBER GENERATOR PACKAGE LLRANDOM, NPS55LW73061A, NAVAL
!     POSTGRADUATE SCHOOL, MONTEREY, CALIFORNIA, JUNE, 1973.
!
!     LEARMONTH, G.P., AND LEWIS, P.A.W., STATISTICAL TESTS OF SOME
!     WIDELY USED AND RECENTLY PROPOSED UNIFORM RANDOM NUMBER
!     GENERATORS. NPS55LW73111A, NAVAL POSTGRADUATE SCHOOL, MONTEREY
!     CALIFORNIA, NOV. 1973.
!
!     THE CODE WAS WRITTEN BY N.L. CROOKSTON, FORESTRY SCIENCES LAB,
!     OCT 1982, FROM THE ALGORITHM PUBLISHED IN THE IMSL MANUAL AND
!     TESTED BY COMPAIRING THE FIRST 10000 DRAWS FORM THIS VERSION AND
!     AND THE GENERATOR 'GGUBS' IN THE 1981 EDITION OF IMSL.
!

INCLUDE 'BMRCOM.f90'

LOGICAL LSET
REAL    SEL, SEED
!
BMS1=DMOD(16807D0*BMS0,2147483647D0)
SEL=BMS1/2147483648D0
BMS0=BMS1
RETURN
!
!     YOU MAY RESEED THE GENERATOR BY SUPPLYING AN ODD NUMBER OF TYPE
!     REAL WITH LSET=TRUE; IF LSET=FALSE, A CALL TO MDRNST WILL
!     CAUSE THE RANDOM NUMBER GENERATOR TO START OVER.
!
ENTRY BMRNSD (LSET,SEED)
!
IF (LSET) GOTO 10
SEED=BMSS
BMS0=SEED
GOTO 20
10 CONTINUE
IF (AMOD(SEED,2.0).EQ.0.) SEED=SEED+1
BMSS=SEED
BMS0=SEED
20 CONTINUE
!
RETURN
END
