SUBROUTINE ESSUBH (I,HHT,EMSQR,DILATE,DELAY,ELEV,IHTSER,GENTIM, &
                      TRAGE)
IMPLICIT NONE
!----------
! EC $Id$
!----------
!     ASSIGNS HEIGHTS TO SUBSEQUENT AND PLANTED TREE RECORDS
!     CREATED BY THE ESTABLISHMENT MODEL.
!     COMING INTO ESSUBH, TRAGE IS THE AGE OF THE TREE AS SPECIFIED ON
!     THE PLANT OR NATURAL KEYWORD.  LEAVING ESSUBH, TRAGE IS THE NUMBER
!     BETWEEN PLANTING (OR NATURAL REGENERATION) AND THE END OF THE
!     CYCLE.  AGE IS TREE AGE UP TO THE TIME REGENT WILL BEGIN GROWING
!     THE TREE.
!
!     CALLED FROM **ESTAB
!     CALLS **SMHTGF
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'ESPARM.f90'
!
!
INCLUDE 'ESCOMN.f90'
!
!OMMONS
!----------
LOGICAL DEBUG
INTEGER I,IHTSER,N,MODE0,ITIME
REAL    AGE,EMSQR,DILATE,DELAY,ELEV,GENTIM,H,HHT,TRAGE
REAL RDANUW
INTEGER IDANUW
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
RDANUW = DILATE
RDANUW = ELEV
RDANUW = EMSQR
IDANUW = IHTSER
!
!----------
CALL DBCHK (DEBUG,'ESSUBH',6,ICYC)
IF(DEBUG) &
   WRITE(JOSTND,*)' ENTERING ESSUBH - ICYC, TRAGE= ',ICYC,TRAGE
!
N=INT(DELAY+0.5)
IF(N.LT.-3) N=-3
DELAY=REAL(N)
ITIME=INT(TIME+0.5)
IF(N.GT.ITIME) DELAY=TIME
AGE=TIME-DELAY-GENTIM+TRAGE
IF(AGE.LT.1.0) AGE=1.0
TRAGE=TIME-DELAY
!----------
!  CALL SMHTGF TO CALCULATE SEEDLING HEIGHT AT AGE "AGE".
!----------
MODE0=0
CALL SMHTGF (MODE0,ICYC,I,H,AGE,HHT,JOSTND,DEBUG)
!
IF(DEBUG) THEN
WRITE(JOSTND,*)' LEAVE ESSUBH -ICYC,I,AGE,TRAGE,TIME,DELAY,HHT= ', &
   ICYC,I,AGE,TRAGE,TIME,DELAY,HHT
ENDIF
!
RETURN
END
