SUBROUTINE SITSET
IMPLICIT NONE
!----------
! EC $Id$
!----------
! THIS SUBROUTINE LOADS THE SITEAR ARRAY WITH A SITE INDEX FOR EACH
! SPECIES, GIVEN A SITE INDEX AND SITE SPECIES, AND LOADS THE SDIDEF
! ARRAY WITH SDI MAXIMUMS FOR SPECIES WHICH WERE NOT ASSIGNED A VALUE
! USING THE SDIMAX KEYWORD.
!----------
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'VARCOM.f90'
!
!
INCLUDE 'VOLSTD.f90'
!
!
!OMMONS
!----------
LOGICAL DEBUG
CHARACTER*4 ASPEC
CHARACTER FORST*2,DIST*2,PROD*2,VAR*2,VOLEQ*11
INTEGER IFIASP, ERRFLAG
INTEGER NSISET,NSDSET,I,JSISP,INDEX,KNTECO,NTOHI,ISEQ,NUM
INTEGER ISFLAG,ITOHI,ISPC,K,INTFOR,IREGN,J,JJ
REAL FORMAX,RSI,RSDI,AG,SINDX,SI
REAL SIAGE(MAXSP),SDICON(MAXSP)
!----------
!  SPECIES LIST FOR EAST CASCADES VARIANT.
!
!   1 = WESTERN WHITE PINE      (WP)    PINUS MONTICOLA
!   2 = WESTERN LARCH           (WL)    LARIX OCCIDENTALIS
!   3 = DOUGLAS-FIR             (DF)    PSEUDOTSUGA MENZIESII
!   4 = PACIFIC SILVER FIR      (SF)    ABIES AMABILIS
!   5 = WESTERN REDCEDAR        (RC)    THUJA PLICATA
!   6 = GRAND FIR               (GF)    ABIES GRANDIS
!   7 = LODGEPOLE PINE          (LP)    PINUS CONTORTA
!   8 = ENGELMANN SPRUCE        (ES)    PICEA ENGELMANNII
!   9 = SUBALPINE FIR           (AF)    ABIES LASIOCARPA
!  10 = PONDEROSA PINE          (PP)    PINUS PONDEROSA
!  11 = WESTERN HEMLOCK         (WH)    TSUGA HETEROPHYLLA
!  12 = MOUNTAIN HEMLOCK        (MH)    TSUGA MERTENSIANA
!  13 = PACIFIC YEW             (PY)    TAXUS BREVIFOLIA
!  14 = WHITEBARK PINE          (WB)    PINUS ALBICAULIS
!  15 = NOBLE FIR               (NF)    ABIES PROCERA
!  16 = WHITE FIR               (WF)    ABIES CONCOLOR
!  17 = SUBALPINE LARCH         (LL)    LARIX LYALLII
!  18 = ALASKA CEDAR            (YC)    CALLITROPSIS NOOTKATENSIS
!  19 = WESTERN JUNIPER         (WJ)    JUNIPERUS OCCIDENTALIS
!  20 = BIGLEAF MAPLE           (BM)    ACER MACROPHYLLUM
!  21 = VINE MAPLE              (VN)    ACER CIRCINATUM
!  22 = RED ALDER               (RA)    ALNUS RUBRA
!  23 = PAPER BIRCH             (PB)    BETULA PAPYRIFERA
!  24 = GIANT CHINQUAPIN        (GC)    CHRYSOLEPIS CHRYSOPHYLLA
!  25 = PACIFIC DOGWOOD         (DG)    CORNUS NUTTALLII
!  26 = QUAKING ASPEN           (AS)    POPULUS TREMULOIDES
!  27 = BLACK COTTONWOOD        (CW)    POPULUS BALSAMIFERA var. TRICHOCARPA
!  28 = OREGON WHITE OAK        (WO)    QUERCUS GARRYANA
!  29 = CHERRY AND PLUM SPECIES (PL)    PRUNUS sp.
!  30 = WILLOW SPECIES          (WI)    SALIX sp.
!  31 = OTHER SOFTWOODS         (OS)
!  32 = OTHER HARDWOODS         (OH)
!
!  SURROGATE EQUATION ASSIGNMENT:
!
!  FROM THE EC VARIANT:
!      USE 6(GF) FOR 16(WF)
!      USE OLD 11(OT) FOR NEW 12(MH) AND 31(OS)
!
!  FROM THE WC VARIANT:
!      USE 19(WH) FOR 11(WH)
!      USE 33(PY) FOR 13(PY)
!      USE 31(WB) FOR 14(WB)
!      USE  7(NF) FOR 15(NF)
!      USE 30(LL) FOR 17(LL)
!      USE  8(YC) FOR 18(YC)
!      USE 29(WJ) FOR 19(WJ)
!      USE 21(BM) FOR 20(BM) AND 21(VN)
!      USE 22(RA) FOR 22(RA)
!      USE 24(PB) FOR 23(PB)
!      USE 25(GC) FOR 24(GC)
!      USE 34(DG) FOR 25(DG)
!      USE 26(AS) FOR 26(AS) AND 32(OH)
!      USE 27(CW) FOR 27(CW)
!      USE 28(WO) FOR 28(WO)
!      USE 36(CH) FOR 29(PL)
!      USE 37(WI) FOR 30(WI)
!----------
!  DATA STATEMENTS
!----------
DATA SDICON/ &
    645., 648., 766., 766., 766., 766., 674., 766., 700., 645., &
    900., 766., 900., 900., 900., 766., 900., 900., 900., 900., &
    900., 900., 900., 900., 900., 900., 900., 900., 900., 900., &
    766., 900./
!
DATA FORMAX/900./
!-----------
!  SEE IF WE NEED TO DO SOME DEBUG.
!-----------
CALL DBCHK (DEBUG,'SITSET',6,ICYC)
!----------
!  DETERMINE HOW MANY SITE VALUES AND SDI VALUES WERE SET VIA KEYWORD.
!----------
NSISET=0
NSDSET=0
DO 5 I=1,MAXSP
IF(SITEAR(I) .GT. 0.) NSISET=NSISET+1
IF(SDIDEF(I) .GT. 0.) NSDSET=NSDSET+1
5 CONTINUE
IF(DEBUG)WRITE(JOSTND,*)'ENTERING SITSET, SITE VALUES SET = ', &
   NSISET,'  SDI VALUES SET = ',NSDSET
!----------
!  SET SITE SPECIES AND SITE INDEX IF NOT SET BY KEYWORD.
!  ALSO SET SDI DEFAULTS
!
!     REGION 6 FOREST --- CALL **ECOCLS** WITH THE ECOCLASS CODE,
!     AND GET BACK THE DEFAULT SITE SPECIES, ALL SITE INDICIES,
!     AND DEFAULT SDI MAXIMUMS ASSOCIATED WITH THE ECOCLASS
!----------
JSISP=0
INDEX=0
KNTECO=0
NTOHI=0
10 CALL ECOCLS (PCOM,ASPEC,RSDI,RSI,ISFLAG,NUM,INDEX,ISEQ)
KNTECO=KNTECO+1
IF(DEBUG)WRITE(JOSTND,*)'AFTER ECOCLS,PCOM,ASPEC,RSDI,RSI,', &
   'ISFLAG,NUM,INDEX,ISEQ = ',PCOM,ASPEC,RSDI,RSI,ISFLAG, &
   NUM,INDEX,ISEQ
!----------
! IF DEFAULT SDI IS OUT OF BOUNDS, RESET IT.
!----------
ITOHI=0
IF(RSDI .GT. FORMAX)THEN
  RSDI=FORMAX
  ITOHI=1
ENDIF
!
IF(ISEQ .EQ. 0) GO TO 25
IF(JSISP.EQ.0 .AND. ISFLAG.EQ.1) JSISP=ISEQ
IF(ISISP.LE.0 .AND. ISFLAG.EQ.1) ISISP=ISEQ
IF(SITEAR(ISEQ).LE.0. .AND. NSISET.EQ.0) SITEAR(ISEQ)=RSI
IF(SDIDEF(ISEQ) .LE. 0.) THEN
  SDIDEF(ISEQ)=RSDI
  IF(ITOHI .GT. 0) NTOHI=NTOHI+1
ENDIF
IF(ISISP.GT.0 .AND. ISFLAG.EQ.1) THEN
  IF(SDIDEF(ISISP) .LE. 0.) THEN
    SDIDEF(ISISP)=RSDI
    IF(ITOHI .GT. 0) NTOHI=NTOHI+1
  ENDIF
ENDIF
25   CONTINUE
  IF(NUM.GT.1 .AND. KNTECO.LT.NUM) THEN
    INDEX=INDEX+1
    GO TO 10
  ENDIF
!----------
!  ON THE CHANCE THAT A SITE SPECIES WAS NOT ENCOUNTERED IN **ECOCLS**
!  PROVIDE A REGION 6 GLOBAL DEFAULT.
!----------
  IF(ISISP .LE. 0) ISISP = 10
  IF(SITEAR(ISISP) .LE. 0.0) SITEAR(ISISP) = 70.
!----------
! TRANSLATE SITE INDEX TO A REFERENCE AGE FOR EACH SPECIES.
!----------
CALL SICHG(ISISP,SITEAR(ISISP),SIAGE)
!----------
! IF SITEAR  HAS NOT BEEN SET WITH SITECODE KEYWORD, LOAD
! IT WITH SITE VALUES CALCULATED HERE.
!----------
DO 30 ISPC=1,MAXSP
IF(DEBUG)WRITE(JOSTND,*)'IN SITSET ISISP,ISPC,SITEAR =', &
   ISISP,ISPC,SITEAR(ISISP)
IF(SITEAR(ISPC) .GT. 0.0) GO TO 30
AG=SIAGE(ISPC)
SINDX=SITEAR(ISISP)
!
SELECT CASE (ISPC)
!
!----------
! LOGIC FOR SPECIES FROM THE EC VARIANT
!----------
CASE(1:10,12,16,31)
!
  CALL HTCALC(SINDX,ISISP,AG,SI,JOSTND,DEBUG)
!----------
! CHANGE THE SITE INDEX OF MH AND OS TO METRIC
!----------
  IF((ISPC.EQ.12 .AND. ISISP.NE.12) .OR. &
        (ISPC.EQ.31 .AND. ISISP.NE.31)) THEN
    SI=SI/3.281
    IF(SI .GT. 28.)SI=28.
  ENDIF
!
!----------
! LOGIC FOR SPECIES FROM THE WC VARIANT
!----------
CASE(11,13:15,17:30,32)
  SI = 0.
  IF(DEBUG)WRITE(JOSTND,*)'CALLING HTCALC SINDX,ISISP,AG,SI=', &
     SINDX,ISISP,AG,SI
  CALL HTCALC(SINDX,ISISP,AG,SI,JOSTND,DEBUG)
  IF(DEBUG)WRITE(JOSTND,*)'RETURN FROM HTCALC,SINDX,ISISP,AG,SI=' &
     ,SINDX,ISISP,AG,SI
!----------
! MISC. HARDWOODS USE CURTIS SI CURVE CREATED FOR DF. THE
! FOLLOWING EQUATIONS ARE USED TO REDUCE THEIR GROWTH UNTIL
! SI CURVES ARE FOUND FOR THESE SPECIES. 4/26/01 EES.
!----------
IF(ISPC.EQ.13 .AND. ISISP.NE.13)SI=SI*.25
IF(ISPC.EQ.14 .AND. ISISP.NE.14)SI=SI*.70
IF(ISPC.EQ.19 .AND. ISISP.NE.19)SI=SI*.23
IF(ISPC.EQ.20 .AND. ISISP.NE.20)SI=SI*.75
IF(ISPC.EQ.21 .AND. ISISP.NE.21)SI=SI*.75
IF(ISPC.EQ.23 .AND. ISISP.NE.23)SI=SI*1.5
IF(ISPC.EQ.24 .AND. ISISP.NE.24)SI=SI*.70
IF(ISPC.EQ.25 .AND. ISISP.NE.25)SI=SI*.60
IF(ISPC.EQ.26 .AND. ISISP.NE.26)SI=SI*.75
IF(ISPC.EQ.27 .AND. ISISP.NE.27)SI=SI*.85
IF(ISPC.EQ.29 .AND. ISISP.NE.29)SI=SI*.50
IF(ISPC.EQ.30 .AND. ISISP.NE.30)SI=SI*.50
IF(ISPC.EQ.32 .AND. ISISP.NE.32)SI=SI*.75
!----------
! FOR WHITE OAK USE METHOD DERIVED BY GOULD TO GET ESTIMATE OF MAXIMUM
! HEIGHT (THINK OF AS A BASE AGE 300) FROM DF, FROM KING CURVE (BASE AGE 50).
!----------
IF(ISPC.EQ.28 .AND. ISISP.NE.28)SI=114.2*(1-EXP(-0.0266*SI))**2.26
!
END SELECT
!
SITEAR(ISPC) = SI
!
30 CONTINUE
!----------
! LOAD THE SDIDEF ARRAY
!----------
K=ISISP
IF(SDIDEF(K) .LE. 0.) K=JSISP
DO 80 I=1,MAXSP
  IF(SDIDEF(I) .GT. 0.0) GO TO 80
  SELECT CASE (I)
  CASE(1:10,12,16,31)
    IF(BAMAX .GT. 0.) THEN
      SDIDEF(I)=BAMAX/(0.5454154*(PMSDIU/100.))
    ELSE
      SDIDEF(I)=SDIDEF(K) * (SDICON(I)/SDICON(K))
    ENDIF
    IF(SDIDEF(I) .GT. FORMAX)THEN
      SDIDEF(I)=FORMAX
      NTOHI=NTOHI+1
    ENDIF
  CASE(11,13:15,17:30,32)
    SDIDEF(I) = SDIDEF(K)
  END SELECT
80 CONTINUE
IF(BAMAX.LE.0) BAMAX=SDIDEF(K)*(PMSDIU/100.)*0.54542
!
DO 92 I=1,15
J=(I-1)*10 + 1
JJ=J+9
IF(JJ.GT.MAXSP)JJ=MAXSP
WRITE(JOSTND,90)(NSP(K,1)(1:2),K=J,JJ)
90 FORMAT(/'SPECIES ',5X,10(A2,6X))
WRITE(JOSTND,91)(NINT(SDIDEF(K)),K=J,JJ )
91 FORMAT('SDI MAX ',   10I8.0)
IF(JJ .EQ. MAXSP)GO TO 93
92 CONTINUE
93 CONTINUE
IF(NTOHI .GT. 0)WRITE(JOSTND,102)FORMAX
102 FORMAT(/'*NOTE -- AT LEAST ONE DEFAULT MAXIMUM SDI EXCEEDED THE FO &
   REST DEFAULT MAXIMUM. FOREST DEFAULT MAXIMUM OF ',F5.0,' USED.',/ &
   ,'          YOU MAY NEED TO SPECIFICALLY RESET VALUES FOR THESE SP &
   ECIES USING THE SDIMAX KEYWORD.')
!----------
!  LOAD VOLUME EQUATION ARRAYS FOR ALL SPECIES
!----------
INTFOR = KODFOR - (KODFOR/100)*100
WRITE(FORST,'(I2)')INTFOR
IF(INTFOR.LT.10)FORST(1:1)='0'
IREGN = KODFOR/100
DIST='  '
PROD='  '
VAR='EC'
!
IF (LFIANVB) CALL NVB_REGION_CHECK
DO ISPC=1,MAXSP
READ(FIAJSP(ISPC),'(I3)')IFIASP
VOLEQ='           '
IF(((METHC(ISPC).EQ.6).OR.(METHC(ISPC).EQ.9)).AND. &
        (VEQNNC(ISPC).EQ.'           '))THEN
  CALL VOLEQDEF(VAR,IREGN,FORST,DIST,IFIASP,PROD,VOLEQ,ERRFLAG)
  VEQNNC(ISPC)=VOLEQ
ELSE IF(METHC(ISPC).EQ.10)THEN
  CALL NVBEQDEF(IFIASP, VOLEQ)
  VEQNNC(ISPC) = VOLEQ
ENDIF
IF(VEQNNC(ISPC)(11:11) .EQ. CHAR(0)) VEQNNC(ISPC)(11:11) = " "
IF(((METHB(ISPC).EQ.6).OR.(METHB(ISPC).EQ.9)).AND. &
        (VEQNNB(ISPC).EQ.'           '))THEN
  VOLEQ='           '
  CALL VOLEQDEF(VAR,IREGN,FORST,DIST,IFIASP,PROD,VOLEQ,ERRFLAG)
  VEQNNB(ISPC)=VOLEQ
ENDIF
ENDDO
!----------
!  IF FIA CODES WERE IN INPUT DATA, WRITE TRANSLATION TABLE
!---------
IF(LFIA) THEN
  CALL FIAHEAD(JOSTND)
  WRITE(JOSTND,211) (NSP(I,1)(1:2),FIAJSP(I),I=1,MAXSP)
211   FORMAT ((T12,8(A3,'=',A6,:,'; '),A,'=',A6))
ENDIF
!----------
!  WRITE VOLUME EQUATION NUMBER TABLE
!----------
CALL VOLEQHEAD(JOSTND)
WRITE(JOSTND,230)(NSP(J,1)(1:2),VEQNNC(J),VEQNNB(J),J=1,MAXSP)
230 FORMAT(4(2X,A2,4X,A11,1X,A10,1X))
!
RETURN
END
