SUBROUTINE REVISE (VAR,REV)
IMPLICIT NONE
!----------
! CANADA-BC
!----------
!
!  THIS ROUTINE PROVIDES THE LATEST REVISION DATE FOR EACH VARIANT
!  WHICH GETS PRINTED IN THE MAIN HEADER ON THE OUTPUT.
!  CALLED FROM GROHED, FILOPN, SUMHED, SUMOUT, ECVOLS, PRTRLS,
!  AND DGDRIV.
!----------
CHARACTER VAR*2,REV*10

!---------------------------
! LS -> ONTARIO
!---------------------------
!
VAR=VAR
REV="20221118"
RETURN
END
