SUBROUTINE RGNTHW(LESTB,ITRNIN)
IMPLICIT NONE
!----------
! CANADA-ON $Id$
!----------
!  ROUTINE NOT USED IN ON VARIANT; PRESERVED FOR COMPATIBILTIY WITH OLD CALLS

LOGICAL LESTB
INTEGER ITRNIN

RETURN
END
