SUBROUTINE FINDAG(I,ISPC,D1,D2,H,SITAGE,SITHT,AGMAX,HTMAX1,HTMAX2, &
                     DEBUG)
IMPLICIT NONE
!----------
! CA $Id$
!----------
!  THIS ROUTINE FINDS EFFECTIVE TREE AGE BASED ON INPUT VARIABLE(S)
!  CALLED FROM ***COMCUP
!  CALLED FROM ***CRATET
!  CALLED FROM ***HTGF
!  CALLS ***HTCALC
!----------
!  COMMONS
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'PLOT.f90'
!
!OMMONS
!----------
!  LOCAL VARIABLE DEFINITIONS:
!----------
!  INCRNG = HAS A VALUE OF 1 WHEN THE SITE CURVE HAS BEEN MONOTONICALLY
!           INCREASING IN PREVIOUS ITERATIONS.
!   OLDHG = HEIGHT GUESS FROM PREVIOUS ITERATION.
!----------
!  DECLARATIONS
!----------
INTEGER I,ISPC,INCRNG
LOGICAL DEBUG
REAL AGEMAX(MAXSP),AGMAX,AG,DIFF,H,HGUESS,SINDX,TOLER
REAL SITAGE,SITHT,D1,D2,HTMAX1,HTMAX2
REAL RDANUW,OLDHG
!----------
!  DATA STATEMENTS
!----------
DATA AGEMAX/ MAXSP*200. /
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
RDANUW = D1
RDANUW = D2
RDANUW = HTMAX1
RDANUW = HTMAX2
!----------
!  INITIALIZATIONS
!----------
TOLER=2.0
SINDX = SITEAR(ISPC)
AGMAX=AGEMAX(ISPC)
IF(IFOR .LE. 5) AGMAX=400.
AG = 2.0
!----------
! R5 USE DUNNING/LEVITAN SITE CURVE.
! R6 USE **HTCALC** SITE CURVES.
! SPECIES DIFFERENCES ARE ARE ACCOUNTED FOR BY THE SPECIES
! SPECIFIC SITE INDEX VALUES WHICH ARE SET AFTER KEYWORD PROCESSING.
!----------
INCRNG = 0
HGUESS = 0.
75 CONTINUE
OLDHG = HGUESS
!
CALL HTCALC(IFOR,SINDX,ISPC,AG,HGUESS,JOSTND,DEBUG)
!
IF(DEBUG)WRITE(JOSTND,91200)I,IFOR,AG,HGUESS,H
91200 FORMAT(' IN GUESS AN AGE--I,IFOR,AGE,HGUESS,H ',2I5,3F10.2)
!----------
!  AVOID NEGATIVE PREDICTED HEIGHTS AT SMALL AGES FROM SOME SI CURVES
!  GED 4/20/18
!----------
IF(HGUESS .LT. 1.)GO TO 175
!
DIFF=ABS(HGUESS-H)
IF(DIFF .LE. TOLER .OR. H .LT. HGUESS)THEN
  SITAGE = AG
  SITHT = HGUESS
  IF(DEBUG)THEN
    WRITE(JOSTND, *)' DIFF,TOLER,H,HGUESS,AG,SITAGE,SITHT= ', &
       DIFF,TOLER,H,HGUESS,AG,SITAGE,SITHT
  ENDIF
  GO TO 30
END IF
!----------
!  SOME SITE CURVES DECREASE AT THE START BEFORE INCREASING. IF DECREASING,
!  KEEP GOING; IF SITE CURVE WAS INCREASING, BUT NOW HAS FLATTENED OFF, STOP
!  THE ITERATION GED 04/19/18
!----------
DIFF = (HGUESS-OLDHG)
IF(OLDHG.NE.0.0 .AND. DIFF.GE.0.05) INCRNG=1
IF(DEBUG)WRITE(JOSTND,*)' IN FINDAG OLDHG,DIFF,INCRNG= ', &
   OLDHG,DIFF,INCRNG
IF(INCRNG.EQ.1 .AND. DIFF .LT. 0.05)THEN
  SITAGE = AG
  SITHT = HGUESS
  IF(DEBUG)THEN
    WRITE(JOSTND, *)' SITE CURVE FLAT OLDHG,AG,HGUESS,SITAGE,', &
       'SITHT= ',OLDHG,AG,HGUESS,SITAGE,SITHT
  ENDIF
  GO TO 30
END IF
!
175 CONTINUE
AG = AG + 2.
!
IF(AG .GT. AGMAX) THEN
!----------
!  H IS TOO GREAT AND MAX AGE IS EXCEEDED
!----------
  SITAGE = AGMAX
  SITHT = H
  GO TO 30
ELSE
  GO TO 75
ENDIF
!
30 CONTINUE
IF(DEBUG)WRITE(JOSTND,50)I,SITAGE,SITHT
50 FORMAT(' LEAVING SUBROUTINE FINDAG  I,SITAGE,SITHT =', &
   I5,2F10.3)
!
RETURN
END
!**END OF CODE SEGMENT
