SUBROUTINE SMHTGF(NSPC,D,H,CR,BA,BAL,SI,HTGR,RELHT,DEBUG,JOSTND)
IMPLICIT NONE
!----------
! CA $Id$
!----------
! THIS SUBROUTINE COMPUTES THE HEIGHT GROWTH FOR SMALL TREES (HTGR)
! IN REAL SCALE.  THIS ROUTINE IS CALLED FROM REGENT.
!
! THE FOUR SMALL TREE HEIGHT GROWTH EQUATIONS ARE THOSE FIT FOR THE
! WESSIN FVS VARIANT FOR PINES, FIRS, BLACK OAK, AND TANOAK. A MAPPING
! FUNCTION IS USED TO MAP SPECIES IN THIS VARIANT TO ONE OF THE FOUR
! EQUATIONS.  THE EQUATIONS UNDERESTIMATED HEIGHT GROWTH IN THE WESSIN
! VARIANT, SO AN ADJUSTMENT FACTOR IS USED TO MAKE THE ESTIMATES MORE
! REALISTIC AND MORE INDIVIDUALISTIC.
!
! SPECIES ORDER IN CA VARIANT:
!  1=PC  2=IC  3=RC  4=WF  5=RF  6=SH  7=DF  8=WH  9=MH 10=WB
! 11=KP 12=LP 13=CP 14=LM 15=JP 16=SP 17=WP 18=PP 19=MP 20=GP
! 21=JU 22=BR 23=GS 24=PY 25=OS 26=LO 27=CY 28=BL 29=EO 30=WO
! 31=BO 32=VO 33=IO 34=BM 35=BU 36=RA 37=MA 38=GC 39=DG 40=FL
! 41=WN 42=TO 43=SY 44=AS 45=CW 46=WI 47=CN 48=CL 49=OH 50=RW
!----------
!    1 = CHLA     PORT ORFORD CEDAR         CHAMAECYPARIS LAWSONIANA
!    2 = LIDE     INCENSE CEDAR             LIBOCEDRUS DECURRENS
!    3 = THPL     WESTERN REDCEDAR          THUJA PLICATA
!
!    4 = ABCO     WHITE FIR                 ABIES CONCOLOR
!    5 = ABMA     CALIFORNIA RED FIR        ABIES MAGNIFICA (MAGNIFICA)
!    6 = ABSH     SHASTA RED FIR            ABIES MAGNIFICA (SHASTENSIS)
!    7 = PSME     DOUGLAS-FIR               PSEUDOTSUGA MENZIESII
!
!    8 = TSHE     WESTERN HEMLOCK           TSUGA HETEROPHYLLA
!    9 = TSME     MOUNTAIN HEMLOCK          TSUGA MERTENSIANA
!
!   10 = PIAL     WHITEBARK PINE            PINUS ALBICAULIS
!   11 = PIAT     KNOBCONE PINE             PINUS ATTENUATA
!   12 = PICO     LODGEPOLE PINE            PINUS CONTORTA
!   13 = PICO3    COULTER PINE              PINUS COULTERI
!   14 = PIFL2    LIMBER PINE               PINUS FLEXILIS (FLEXILIS)
!   15 = PIJE     JEFFREY PINE              PINUS JEFFREYI
!   16 = PILA     SUGAR PINE                PINUS LAMBERTIANA
!   17 = PIMO3    WESTERN WHITE PINE        PINUS MONTICOLA
!   18 = PIPO     PONDEROSA PINE            PINUS PONDEROSA
!   19 = PIRA2    MONTEREY PINE             PINUS RADIATA
!   20 = PISA2    GRAY PINE                 PINUS SABINIANA
!
!   21 = JUOC     WESTERN JUNIPER           JUNIPERUS OCCIDENTALIS
!   22 = PIBR     BREWER SPRUCE             PICEA BREWERIANA
!   23 = SEGI2    GIANT SEQUOIA             SEQUOIADENDRON GIGANTIUM
!   24 = TABR2    PACIFIC YEW               TAXUS BREVIFOLIA
!
!   25 =          OTHER SOFTWOODS
!
!   26 = QUAG     COAST LIVE OAK            QUERCUS AGRIFOLIA
!   27 = QUCH2    CANYON LIVE OAK           QUERCUS CHRYSOLEPSIS
!   28 = QUDO     BLUE OAK                  QUERCUS DOUGLASII
!   29 = QUEN     ENGELMANN OAK             QUERCUS ENGELMANNI
!   30 = QUGA4    OREGON WHITE OAK          QUERCUS GARRYANA
!   31 = QUKE     CALIFORNIA BLACK OAK      QUERCUS KELLOGGII
!   32 = QULO     VALLEY WHITE OAK          QUERCUS LOBATA
!   33 = QUWI2    INTERIOR LIVE OAK         QUERCUS WISLIZENII
!
!   34 = ACMA3    BIGLEAF MAPLE             ACER MACROPHYLLUM
!   35 = AECA     CALIFORNIA BUCKEYE        AESCULUS CALIFORNICA
!   36 = ALRU2    RED ALDER                 ALNUS RUBRA
!   37 = ARME     PACIFIC MADRONE           ARBUTUS MENZIESII
!   38 = CHCHC4   GIANT CHINQUAPIN          CHRYSOLEPIS CHRYSOPHYLLA
!   39 = CONU4    PACIFIC DOGWOOD           CORNUS NUTTALLII
!   40 = FRLA     OREGON ASH                FRAXINUS LATIFOLIA
!   41 = JU__     WALNUT                    JUGLANS sp.
!   42 = LIDE3    TANOAK                    LITHOCARPUS DENSIFLORUS
!   43 = PLRA     CALIFORNIA SYCAMORE       PLATANUS RACEMOSA
!   44 = POTR5    QUAKING ASPEN             POPULUS TREMULOIDES
!   45 = POBAT    BLACK COTTONWOOD          POPULUS TRICHOCARPA
!   46 = SA__     WILLOW                    SALIX sp.
!   47 = TOCA     CALIFORNIA NUTMEG         TORREYA CALIFORNICA
!   48 = UMCA     CALIFORNIA LAUREL         UMBELLULARIA CALIFORNICA
!
!   49 =          OTHER HARDWOODS
!   50 =          COAST REDWOOD             SEQUIOA SEMPERVIRENS
!----------
! INTERNAL VARIABLES
LOGICAL DEBUG
REAL SPADJF(50),RELHT,HTGR,SI,BAL,BA,CR,D,FACTOR,TEMBAL
REAL AGE1,AGE2,HTMAX,H2,H1,H
REAL DOMHTGR,CRMOD,RHMOD,SMHMOD
INTEGER MAPSP(50),JOSTND,NSPC
REAL RDANUW
!----------
!  DATA STATEMENTS
!----------
DATA SPADJF / &
    1.0, 1.0, 0.9, 1.1, 1.1, 1.1, 1.1, 0.8, 0.9, 0.9, &
    1.0, 1.0, 1.0, 1.0, 1.0, 1.1, 1.1, 1.0, 1.1, 0.9, &
    1.0, 0.9, 1.0, 0.8, 1.0, 1.1, 0.9, 1.1, 1.1, 1.0, &
    1.1, 1.0, 1.1, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, &
    1.1, 1.0, 1.1, 1.2, 1.2, 1.1, 0.8, 1.0, 1.0, 1.0 /
!
DATA MAPSP / &
    2, 2, 2, 2, 2, 2, 2, 2, 2, 1, &
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, &
    1, 2, 5, 2, 1, 3, 3, 3, 3, 3, &
    3, 3, 3, 4, 3, 3, 4, 3, 4, 3, &
    3, 4, 3, 3, 3, 3, 2, 4, 3, 5 /
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
RDANUW = BA
RDANUW = D
!----------
!  COMPUTE ADJUSTMENT FACTOR BASED ON SPECIES AND SITE INDEX
!----------
FACTOR = SPADJF(NSPC) * (.80+0.004*(SI-50.))
!
TEMBAL=BAL
IF(TEMBAL .LT. 5.0) TEMBAL=5.0
GO TO (100,200,300,400,500) MAPSP(NSPC)
!
!----------
!   PINES
!----------
100 CONTINUE
HTGR = EXP(0.7452 - 0.003271*BAL - 0.1632*CR + 0.0217*CR*CR &
        + 0.00536*SI) * FACTOR * 1.75
GO TO 600
!
!----------
!  FIRS - INCLUDING DOUGLAS FIR
!  EQUATION FOR DOMINANT HEIGHT GROWTH (DOMHTGR) DERIVED FROM THE
!  FOLLOWING:  CURVES FOR DOMINANT-HEIGHT-GROWTH FOR DOUGLAS-FIR IN
!  SOUTHWEST OREGON (FIG.2, P.9; RES. BULL. 59, FEB 1987; BY HANN AND
!  SCRIVANI;  DOMINANT-HEIGHT-GROWTH AND SITE-INDEX EQUATIONS....IN
!  SOUTHWEST OREGON.)  BASE RELATIONSHIP FIT FROM THESE CURVES IS
!  POT'L. HT. GR. = CHANGE IN HT. / CHANGE IN AGE (TIME).  THE CURVES
!  IN FIG. 2 ARE STRAIGHT LINES FROM AGEBH=0 TO AGEBH=20 AND SO CAN BE
!  DESCRIBED AS SIMPLE LINEAR EQUATIONS WHOSE SLOPE DEPENDS ON SITE
!  INDEX.  THE ADDITIONAL COMPLEXITY RESULTS FROM CHANGING THE CURVES
!  FROM AGE, BREAST HT. TO AGE, TOTAL TREE, USED HERE IN FVS.  WHEN
!  HEIGHT GROWTH IS SOLVED FOR AS THE DEPENDENT VARIABLE, THE RESULTING
!  EQUATION IS THAT FOR DOMHTGR BELOW.
!  THE SMALL HEIGHT GROWTH MODIFIER (SMHMOD) IS BASED ON THE RITCHIE &
!  HANN WORK (FOR.ECOL.&MGMT. 1986. 15:135-145).  THE ORIGINAL COEFF.
!  (1.117148) IS CHANGED TO 1.016605 TO MAKE THE SMALL TREE HEIGHTS
!  CLOSE TO THE SITE INDEX CURVE.  THE MODIFIER HAS TWO PARTS, ONE
!  (CRMOD) FOR TREE VIGOR USING CROWN RATIO AS A SURROGATE; OTHER
!  (RHMOD) FOR COMPETITION FROM NEIGHBORING TREES USING RELATIVE TREE
!  HEIGHT AS A SURROGATE.
!----------
200 CONTINUE
DOMHTGR= 5*(2.2227 + 0.4314*SI)/(29.0 - 0.05*SI)
CR= CR/10.
CRMOD=(1.0-EXP(-4.26558*CR))
RHMOD=(EXP(2.54119*(RELHT**0.250537-1.0)))
SMHMOD= 1.016605*CRMOD*RHMOD
HTGR= DOMHTGR*SMHMOD
IF (DEBUG) WRITE (JOSTND,9900) DOMHTGR, SMHMOD, HTGR, SI,CR,RELHT
9900 FORMAT(' DEBUG-SMHTGF--9900--',3F10.4, 2F6.1,F7.4)
GO TO 600
!
!----------
!  BLACKOAK
!----------
300 CONTINUE
HTGR = EXP(3.817 - 0.7829*ALOG(TEMBAL)) * FACTOR
GO TO 600

!----------
!  TANOAK
!----------
400 CONTINUE
HTGR = EXP(3.385 - 0.5898*ALOG(TEMBAL)) * FACTOR
GO TO 600
!----------
!  COAST REDWOOD
!----------
500 CONTINUE
HTMAX=(2.242202*SI)
IF(HTMAX-H.LE.1.) THEN
  HTGR = 0.0

!  CALCULATE CURRENT AGE AND AGE 5 YEARS HENCE
ELSE
  AGE1 = 1/-0.010742* &
            LOG(1-((H)/2.242202/SI)**(1/0.919076))
  AGE2 = AGE1 + 5

! ESTIMATE H1 BASED ON AGE1 AND H2 BASED ON AGE2
  H1 = 2.242202*SI*(1-EXP(-0.010742*AGE1))**0.919076
  H2 = 2.242202*SI*(1-EXP(-0.010742*AGE2))**0.919076

! COMPUTE HEIGHT INCREMENT BASED ON SUBTRACTION OF H2 AND H1
  HTGR = H2 - H1

! DEBUG
  IF(DEBUG)WRITE(JOSTND,*) "RW DEBUG"," H=", H, ' AGE1=', AGE1, &
    " AGE2=", AGE2, " H1=", H1, " H2=", H2," SI=", SI, &
    " HTGR=", HTGR
ENDIF

!----------
!  SET LOWER BOUND ON HEIGHT INCREMENT
!----------
600 CONTINUE
IF(HTGR .LT. 0.1) HTGR = 0.1
RETURN
END
