SUBROUTINE MPBGO(L)
IMPLICIT NONE
!----------
! LPMPB $Id$
!----------
!
!
!     L     = TRUE WHEN THE MOUNTAIN PINE BEETLE MODEL IS TO BE CALLED
!
!     EVENTS CONTROLED BY THIS ROUTINE:
!
!     1) DECIDES IF AN OUTBREAK WILL TAKE PLACE DURING THIS CYCLE
!     2) SETS NUMBER OF CLASSES TO NUMBER 'MIN0(POSSABLE,REQUESTED)'
!
! Revision History:
!   02/26/88 Last noted revision date.
!   08/06/01 Lance R. David (FHTET)
!     Initialization of logical variable L.
!   07/02/10 Lance R. David (FMSC)
!     Added IMPLICIT NONE.
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'MPBCOM.f90'
!
!
!OMMONS
!
LOGICAL L,NOERR
INTEGER I, MYACTS(1), NTODO
REAL  PROTBK, X

DATA MYACTS /555/

L = .FALSE.

IF (.NOT.LMPB1) RETURN
NACLAS = 0
PRBMPB(ICYC) = 0.0
IF (LEPI) PRBMPB(ICYC) = EPIPRB
!
IF (DEBUIN) THEN
   WRITE (JOMPB,10) ICYC,MPBON,MPBYR,WORKIN
10    FORMAT (/,'IN MPBGO:  ICYC= ',I5,' MPBON= ',I4,' MPBYR= ',I5/ &
              '  WORKIN= ',40L2)
   WRITE (JOMPB,15) (IY(I),I=1,NCYC)
15    FORMAT ('IY =',T10,20I5,/,T10,20I5)
ENDIF
!
!     CALL THE EVENT MONITOR TO 'UNSET' THE PREVIOUS MPB MORTALITY.
!
CALL EVUST4 (4)
!
!     CALL MPBER TO SEE IF MINIMUM CONDITIONS MET FOR OUTBREAK.
!
CALL MPBER (NOERR)
L=NOERR
!
!     CALL OPFIND TO DETERMINE IF OUTBREAK SCHEDULED BY USER THIS CYCLE
!
CALL OPFIND (1,MYACTS,NTODO)
!
!     IF MINIMUM CONDITIONS MET BRANCH TO STMT 100 FOR POSSIBLE
!     OUTBREAK.
!
IF (L) GO TO 100
!
!     CONDITIONS NOT MET FOR OUTBREAK. NONE WILL OCCUR. IF NO OUTBREAK
!     OCCURS BUT USER ASKED FOR ONE WRITE ERROR MESSAGE.
!
IF ( NTODO .GT. 0) WRITE (JOMPB,95)
95 FORMAT (/,'********   WARNING:  A REQUESTED MOUNTAIN', &
           ' PINE BEETLE OUTBREAK CAN NOT BE SIMULATED.')
!
!     WRITE REQUESTED GRAPHIC OUTPUT IF A OUTBREAK WAS IN PROGRESS.
!
IF ( MPBYR .GT. 0 .AND. MPBGRF) CALL MPLOTW
RETURN
100 CONTINUE
!
!     AN OUTBREAK CAN  BE CONTINUED OR SIMULATED.
!     SET NUMBER OF ACTUAL CLASSES. ALSO CALL OPDONE TO SIGNAL OPTION
!     DONE.
!
IF (NTODO .GT. 0) CALL OPDONE (1,IY(ICYC))
NACLAS = MIN0 (ILP,NCLASS)
IF ( LEPI ) GO TO 110
!
!     CALCULATE THE PROBABILITY OF AN OUTBREAK
!
CALL MPOTPR ( PROTBK )
!
!     SCALE THE PROBABILITY AND SAVE IT FOR FUTURE PRINTING
!
PRBMPB(ICYC) = PROTBK*PRBSCL
110 CONTINUE
PROTBK=PRBMPB(ICYC)
!
!     STORE THE PROBABILITY OF OUTBREAK IN THE EVENT MONITOR.
!
CALL EVSET4 (6,PROTBK)
!
!     MINIMUM CONDITIONS MET FOR OUTBREAK. NOW OUTBREAK WILL
!     OCCUR IF THIS IS THE YEAR THE OUTBREAK HAS BEEN SCHEDULED
!     OR IF IT IS ALREADY IN PROGRESS.
!
IF (NTODO .GT. 0 .OR. MPBYR .GT. 0) THEN
   L=.TRUE.
   WORKIN(ICYC)=.TRUE.
ELSE
!
!        AT THIS POINT, NTODO AND MPBYR ARE BOTH ZERO.
!        NO OUTBREAK WILL OCCUR UNLSSS THE RANSTART KEYWORD WAS
!        WAS SPECIFIED.
!
   IF (LRANST) THEN
      CALL MPRANN (X)
      IF (X.LT.PROTBK) THEN
!
!              AN OUTBREAK IS OCCURING.  SCHEDULE THE ACTIVITY,
!              AND RETURN L AS TRUE.
!
         L=.TRUE.
         WORKIN(ICYC)=.TRUE.

         CALL OPADD (IY(ICYC),MYACTS(1),IY(ICYC),0,WK6,I)
      ELSE
         L=.FALSE.
         WORKIN(ICYC) = .FALSE.
      ENDIF
   ELSE
      L=.FALSE.
      WORKIN(ICYC) = .FALSE.
   ENDIF
ENDIF
!
IF (DEBUIN) THEN
   WRITE (JOMPB,225) CNTLP,ILP,NACLAS,NCLASS
225    FORMAT (/,'DUMP OF CONTROLING VARIABLES:',/ &
              T14,'TREES/ACRE  NUMBER OF TREE  NUMBER OF CLASSES', &
              /,T29,'RECORDS      ACTUAL    REQUESTED'/ &
              'LODGEPOLE:   ',F10.3,I11,2I13)
!
   WRITE (JOMPB,250) L
250    FORMAT (/,'T=SIMULATION WILL GO; F=NO GO   " ',L1,' "')
ENDIF
!
!     IF AN OUTBREAK IS TO BE SIMULATED;
!     THEN: SAVE PAST DIAMETER GROWTH ESTIMATES.
!
IF (L) CALL MPSVDG
RETURN
END
