BLOCK DATA MPBLKD
IMPLICIT NONE
!----------
! LPMPB $Id$
!----------
!
!     MOUNTAIN PINE BEETLE --
!     SEE MPBCUP OR MPBMOD FOR VARIABLE DISCRIPTIONS.
!
! Revision History
!   04/14/10 LANCE DAVID (FMSC)
!     CREATED THIS TETON VARIANT VERSION TO ACCOMODATE THE 18 SPECIES
!     NOW REPRESENTED. SURROGATE SPECIES ASSIGNMENTS ARE BASED ON
!     THOSE MADE IN THE CENTRAL ROCKIES AND UTAH VARIANTS.
!   07/02/10 Lance R. David (FMSC)
!     Added IMPLICIT NONE.
!   08/22/14 Lance R. David (FMSC)
!     Function name was used as variable name.
!     changed variable INT to INCRS
!----------------------------------------------------------------------
!
!OMMONS

INCLUDE 'PRGPRM.f90'

INCLUDE 'MPBCOM.f90'

DATA  JOMPB  / 7 /

DATA IPLTNO/ 1 /,IMPROB/ 1 /,NATR/ 2 /, KEYMPB/ 2,3,6*0,1 /, &
        INCRS/ 10 /

!     SPECIES LIST FOR TETON VARIANT. ***** 18 species *****
!
!  vv---- MPB surface area calculation surrogate specie (surfce.f)
!  !!
!  !!  SPECIES LIST FOR UT VARIANT.
!  !!  ------FVS UT VARIANT-------
!  !!   # CD COMMON NAME            SCIENTIFIC NAME
!  !!  -- -- ---------------------  ---------------------
!  WP   1 WB WHITEBARK PINE         PINUS ALBICAULIS
!  WL   2 LM LIMBER PINE            PINUS FLEXILIS
!  DF   3 DF DOUGLAS-FIR            PSEUDOTSUGA MENZIESII
!  WL   4 PM SINLELEAF PINYON       PINUS MONOPHYLLA
!  WP   5 BS BLUE SPRUCE            PICEA PUNGENS
!  WL   6 AS QUAKING ASPEN          POPULUS TREMULOIDES
!  LP   7 LP LODGEPOLE PINE         PINUS CONTORTA
!  WP   8 ES ENGLEMANN SPRUCE       PICEA ENGELMANNII
!  DF   9 AF SUBALPINE FIR          ABIES LASIOCARPA
!  PP  10 PP PONDEROSA PINE         PINUS PONDEROSA
!  WL  11 UJ UTAH JUNIPER           JUNIPERUS OSTEOSPERMA
!  WL  12 RM ROCKY MOUNTAIN JUNIPER JUNIPERUS SCOPULORUM
!  DF  13 BI BIGTOOTH MAPLE         ACER GRANDIDENTATUM
!  DF  14 MM ROCK MOUNTAIN MAPLE    ACER GLABRUM
!  DF  15 NC NARROWLEAF COTTONWOOD  POPULUS ANGUSTIFOLIA
!  DF  16 MC CURLLEAF MOUNTAIN-     CERCOCARPUS LEDIFOLIUS
!            MAHOGANY
!  WL  17 OS OTHER SOFTWOODS
!  DF  18 OH OTHER HARDWOODS
!
!     LPMPB SPECIES INDICES FOR TT LIST ABOVE

DATA IDXWP,IDXWL,IDXDF,IDXLP,IDXPP/1,2,3,7,10/

!     ASSIGN LPMPB SURROGATE SPECIES FOR CALCULATIONS IN SURFCE.F
!
!     TT 18 SPECIES LIST
!                  WB LM DF PM BS AS LP ES AF PP   -- TT 18 species
DATA MPBSPM / 1, 2, 3, 2, 1, 3, 7, 1, 3,10, &
                 2, 2, 2, 2, 3, 3, 2, 3/
END
