BLOCK DATA MPBLKD
IMPLICIT NONE
!----------
! LPMPB $Id$
!----------
!
!     MOUNTAIN PINE BEETLE --
!     SEE MPBCUP OR MPBMOD FOR VARIABLE DISCRIPTIONS.
!
! Revision History
!   10/04/11 LANCE DAVID (FMSC)
!     CREATED THIS CENTRAL IDAHO VARIANT VERSION TO ACCOMODATE THE
!     19 SPECIES NOW REPRESENTED. SURROGATE SPECIES ASSIGNMENTS FOR
!     SURFACE AREA CALCULATIONS WERE MADE BASED ON PREVIOUS ASSIGNMENTS
!     IN NEARBY VARIANTS (ORIGINAL CI, TT, UT, SO, IE) VARIANTS.
!   08/22/14 Lance R. David (FMSC)
!     Function name was used as variable name.
!     changed variable INT to INCRS
!----------------------------------------------------------------------
!
!OMMONS

INCLUDE 'PRGPRM.f90'

INCLUDE 'MPBCOM.f90'

DATA  JOMPB  / 7 /

DATA IPLTNO/ 1 /,IMPROB/ 1 /,NATR/ 2 /, KEYMPB/ 2,3,6*0,1 /, &
        INCRS/ 10 /

!     SPECIES LIST FOR CENTRAL IDAHO VARIANT. ***** 19 species *****
!
!  vv---- MPB surface area calculation surrogate specie (surfce.f)
!  !!
!  !!  SPECIES LIST FOR UT VARIANT.
!  !!  ------FVS UT VARIANT-------
!  !!   # CD COMMON NAME            SCIENTIFIC NAME
!  !!  -- -- ---------------------  ---------------------
!  WP   1 WP WESTERN WHITE PINE     PINUS MONTICOLA
!  WL   2 WL WESTERN LARCH          LARIX OCCIDENTALIS
!  DF   3 DF DOUGLAS-FIR            PSEUDOTSUGA MENZIESII
!  DF   4 GF GRAND FIR              ABIES GRANDIS
!  DF   5 WH WESTERN HEMLOCK        TSUGA HETEROPHYLLA
!  WL   6 RC WESTERN REDCEDAR       THUJA PLICATA
!  LP   7 LP LODGEPOLE PINE         PINUS CONTORTA
!  WP   8 ES ENGLEMANN SPRUCE       PICEA ENGELMANNII
!  DF   9 AF SUBALPINE FIR          ABIES LASIOCARPA
!  PP  10 PP PONDEROSA PINE         PINUS PONDEROSA
!  WP  11 WB WHITEBARK PINE         PINUS ALBICAULIS
!  WL  12 PY PACIFIC YEW            TAXUS BREVIFOLIA
!  WL  13 AS QUAKING ASPEN          POPULUS TREMULOIDES
!  WL  14 WJ WESTERN JUNIPER        JUNIPERUS OCCIDENTALIS
!  DF  15 MC CURLLEAF MOUNTAIN-     CERCOCARPUS LEDIFOLIUS
!            MAHOGANY
!  WL  16 LM LIMBER PINE            PINUS FLEXILIS
!  DF  17 CW BLACK COTTONWOOD       POPULUS BALSAMIFERA VAR. TRICHOCARPA
!  WL  18 OS OTHER SOFTWOODS
!  DF  19 OH OTHER HARDWOODS
!
!
!     LPMPB SPECIES INDICES FOR TT LIST ABOVE

DATA IDXWP,IDXWL,IDXDF,IDXLP,IDXPP/1,2,3,7,10/

!     ASSIGN LPMPB SURROGATE SPECIES FOR CALCULATIONS IN SURFCE.F
!
!     CI 19 SPECIES LIST
!                  WP WL DF GF WH RC LP ES AF PP   -- CI 19 species
DATA MPBSPM / 1, 2, 3, 3, 3, 3, 7, 1, 3,10, &
                 1, 2, 2, 2, 3, 2, 3, 2, 3/
END

