BLOCK DATA MPBLKD
IMPLICIT NONE
!----------
! LPMPB $Id$
!----------
!
!     MOUNTAIN PINE BEETLE --
!     SEE MPBCUP OR MPBMOD FOR VARIABLE DISCRIPTIONS.
!
! Revision History
!   07/06/00 LANCE DAVID (FHTET)
!     CREATED THIS UTAH VARIANT VERSION TO ACCOMODATE THE 14 SPECIES
!     NOW REPRESENTED. SURROGATE SPECIES ASSIGNMENTS ARE BASED ON
!     THOSE MADE IN THE NORTHERN IDAHO AND CENTRAL ROCKIES VARIANTS.
!   08/21/09 LANCE DAVID (FMSC)
!     Utah variant expanded to 24 species.
!   07/02/10 Lance R. David (FMSC)
!     Added IMPLICIT NONE.
!   08/22/14 Lance R. David (FMSC)
!     Function name was used as variable name.
!     changed variable INT to INCRS
!----------------------------------------------------------------------
!
!OMMONS

INCLUDE 'PRGPRM.f90'

INCLUDE 'MPBCOM.f90'

DATA  JOMPB  / 7 /

DATA IPLTNO/ 1 /,IMPROB/ 1 /,NATR/ 2 /, KEYMPB/ 2,3,6*0,1 /, &
        INCRS/ 10 /

!     SPECIES LIST FOR UTAH VARIANT. ***** 24 species *****
!
!  vv---- MPB surface area calculation surrogate specie (surfce.f)
!  !!
!  !!  SPECIES LIST FOR UT VARIANT.
!  !!  ------FVS UT VARIANT-------
!  !!   # CD COMMON NAME            SCIENTIFIC NAME
!  !!  -- -- ---------------------  ---------------------
!  WP   1 WB WHITEBARK PINE         PINUS ALBICAULIS
!  WL   2 LM LIMBER PINE            PINUS FLEXILIS
!  DF   3 DF DOUGLAS-FIR            PSEUDOTSUGA MENZIESII
!  DF   4 WF WHITE FIR              ABIES CONCOLOR
!  WP   5 BS BLUE SPRUCE            PICEA PUNGENS
!  WL   6 AS QUAKING ASPEN          POPULUS TREMULOIDES
!  LP   7 LP LODGEPOLE PINE         PINUS CONTORTA
!  WP   8 ES ENGLEMANN SPRUCE       PICEA ENGELMANNII
!  DF   9 AF SUBALPINE FIR          ABIES LASIOCARPA
!  PP  10 PP PONDEROSA PINE         PINUS PONDEROSA
!  WL  11 PI COMMON PINYON          PINUS EDULIS
!  WL  12 WJ WESTERN JUNIPER        JUNIPERUS OCCIDENTALIS
!  DF  13 GO GAMBEL OAK             QUERCUS sp.
!  WL  14 PM SINLELEAF PINYON       PINUS MONOPHYLLA
!  WL  15 RM ROCKY MOUNTAIN JUNIPER JUNIPERUS SCOPULORUM
!  WL  16 UJ UTAH JUNIPER           JUNIPERUS OSTEOSPERMA
!  WL  17 GB BRISTLECONE PINE       PINUS LOGAEVA
!            (Great Basin)
!  DF  18 NC NARROWLEAF COTTONWOOD  POPULUS ANGUSTIFOLIA
!  DF  19 FC FREMONT COTTONWOOD     POPULUS FREMONTII
!  DF  20 MC CURLLEAF MOUNTAIN-     CERCOCARPUS LEDIFOLIUS
!            MAHOGANY
!  DF  21 BI BIGTOOTH MAPLE         ACER GRANDIDENTATUM
!  DF  22 BE BOX ELDER              ACER NEGUNDO
!  WL  23 OS OTHER SOFTWOODS
!  DF  24 OH OTHER HARDWOODS
!
!     LPMPB SPECIES INDICES FOR UT LIST ABOVE

DATA IDXWP,IDXWL,IDXDF,IDXLP,IDXPP/1,2,3,7,10/

!     ASSIGN LPMPB SURROGATE SPECIES FOR CALCULATIONS IN SURFCE.F
!
!     UT 24 SPECIES LIST
!                  WB LM DF WF BS AS LP ES AF PP PI WJ
DATA MPBSPM / 1, 2, 3, 3, 1, 3, 7, 1, 3,10, 2, 2, &
                 3, 2, 2, 2, 2, 3, 3, 3, 3, 3, 2, 3/
END
