BLOCK DATA MPBLKD
IMPLICIT NONE
!----------
! LPMPB $Id$
!----------
!
!     MOUNTAIN PINE BEETLE --
!     SEE MPBCUP OR MPBMOD FOR VARIABLE DISCRIPTIONS.
!
! Revision History
!   08/08/03 LANCE DAVID (FHTET)
!     CREATED THIS INLAND EMPIRE VARIANT VERSION TO ACCOMODATE
!     THE 23 SPECIES REPRESENTED. SURROGATE SPECIES ASSIGNMENTS
!     ARE BASED ON THOSE MADE IN THE NORTHERN IDAHO AND CENTRAL
!     ROCKIES VARIANTS.
!   07/02/10 Lance R. David (FMSC)
!     Added IMPLICIT NONE.
!   08/22/14 Lance R. David (FMSC)
!     Function name was used as variable name.
!     changed variable INT to INCRS
!----------------------------------------------------------------------
!
!OMMONS

INCLUDE 'PRGPRM.f90'

INCLUDE 'MPBCOM.f90'

DATA  JOMPB  / 7 /

DATA IPLTNO/ 1 /,IMPROB/ 1 /,NATR/ 2 /, KEYMPB/ 2,3,6*0,1 /, &
        INCRS/ 10 /

!----------
!     SPECIES LIST FOR INLAND EMPIRE 23 SPECIES VARIANT.
!
!     1 = WESTERN WHITE PINE (WP)        PINUS MONTICOLA
!     2 = WESTERN LARCH (WL)             LARIX OCCIDENTALIS
!     3 = DOUGLAS-FIR (DF)               PSEUDOTSUGA MENZIESII
!     4 = GRAND FIR (GF)                 ABIES GRANDIS
!     5 = WESTERN HEMLOCK (WH)           TSUGA HETEROPHYLLA
!     6 = WESTERN REDCEDAR (RC)          THUJA PLICATA
!     7 = LODGEPOLE PINE (LP)            PINUS CONTORTA
!     8 = ENGLEMAN SPRUCE (ES)           PICEA ENGELMANNII
!     9 = SUBALPINE FIR (AF)             ABIES LASIOCARPA
!    10 = PONDEROSA PINE (PP)            PINUS PONDEROSA
!    11 = MOUNTAIN HEMLOCK (MH)          TSUGA MERTENSIANA
!    12 = WHITEBARK PINE (WB)            PINUS ALBICAULIS
!    13 = LIMBER PINE (LM)               PINUS FLEXILIS
!    14 = SUBALPINE LARCH (LL)           LARIX LYALLII
!    15 = PINYON PINE (PI)               PINUS MONOPHYLLA
!    16 = WESTERN JUNIPER (JU)           JUNIPERUS OCCIDENTALIS
!    17 = PACIFIC YEW (PY)               TAXUS BREVIFOLIA
!    18 = QUAKING ASPEN (AS)             POPULUS TREMULOIDES
!    19 = COTTONWOOD (CO)                POPULUS SPP.
!    20 = MOUNTAIN MAPLE (MM)            ACER GLABRUM
!    21 = PAPER BIRCH (PB)               BETULA PAPYRIFERA
!    22 = OTHER HARDWOODS (OH)
!    23 = OTHER SOFTWOODS (OS)
!----------
!
!     LPMPB SPECIES INDICES FOR IE SPECIES LIST ABOVE

DATA IDXWP,IDXWL,IDXDF,IDXLP,IDXPP/1,2,3,7,10/

!     ASSIGN LPMPB SURROGATE SPECIES FOR CALCULATIONS IN SURFCE.F
!
!     IE SP LIST:  WP,WL,DF,GF,WH,RC,LP,ES,AF,PP,MH,WB,LM,
DATA MPBSPM / 1, 2, 3, 3, 3, 3, 7, 1, 3,10, 2, 1, 2, &
                 2, 2, 2, 2, 3, 3, 3, 3, 3, 2/

END
