SUBROUTINE PTARY(IPLTNO,XAXIS,SAV)
IMPLICIT NONE
!----------
! LPMPB $Id$
!----------
!
!     LIBRARY ROUTINE TO SPOOL PLOT OUTPUT
!
!     THIS ROUTINE MAY BE USED TO SAVE AN ARRAY OF UP
!     TO TEN VARIABLES TO BE PLOTTED.
!
!     THE ACTUAL NUMBER OF VARIABLES USED IS DETERMINED
!     BY IPTVAR(IPLTNO) AS DEFINED BY THE INITIAL
!     CALL(S) TO PTGRP.
!
! Revision History
!   02/16/88 Last noted revision date.
!   07/02/10 Lance R. David (FMSC)
!     Added IMPLICIT NONE.
!----------
!
!OMMONS
!
!
INCLUDE 'PT.f90'
!
!
!OMMONS

INTEGER I, ILUN, IPLTNO, J, N
REAL  SAV(10), XAXIS

!             BLOCK OF 10 PLOT VARIABLES TO BE SPOOLED
!
!        UPDATE MAX AND MIN
N = IPTVAR(IPLTNO)
DO 20 J=1,N
IF(SAV(J) .GT. PTMAX(IPLTNO,J)) PTMAX(IPLTNO,J)=SAV(J)
IF(SAV(J) .LT. PTMIN(IPLTNO,J)) PTMIN(IPLTNO,J)=SAV(J)
20 CONTINUE
!
IPTSPL(IPLTNO)=IPTSPL(IPLTNO)+1
ILUN=19+IPLTNO
WRITE(ILUN) XAXIS,(SAV(I),I=1,10)
!
RETURN
END
