SUBROUTINE SITERANGE(IWHO,IS,SILOW,SIHIGH)
IMPLICIT NONE
!----------
! BM $Id$
!----------
!
! SUBROUTINE TO RETURN THE SITE INDEX RANGE FOR A SPECIES.
!
! THIS SUBROUTINE IS CALLED FROM **HTGF**,**REGENT**, AND **SITSET**.
!----------
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
!OMMONS
!
!----------
!  VARIABLE DEFINITIONS:
!----------
!      IS -- FVS SPECIES INDEX NUMBER
!    IWHO -- 1 IF CALLED FROM SUBROUTINE **SITSET**
!            2 IF CALLED FROM SUBROUTINE **REGENT**
!            3 IF CALLED FROM SUBROUTINE **HTGF**
!  SITEHI -- UPPER SITE INDEX VALUES
!  SITELO -- LOWER SITE INDEX VALUES
!----------
!  VARIABLE DECLARATIONS:
!----------
!
INTEGER IS,IWHO
!
REAL SIHIGH,SILOW
!
REAL SITEHI(MAXSP),SITELO(MAXSP)
!
!----------
!  DATA STATEMENTS
!
!  SPECIES ORDER:
!   1=WP,  2=WL,  3=DF,  4=GF,  5=MH,  6=WJ,  7=LP,  8=ES,
!   9=AF, 10=PP, 11=WB, 12=LM, 13=PY, 14=YC, 15=AS, 16=CW,
!  17=OS, 18=OH
!
!  SPECIES EXPANSION:
!  WJ USES SO JU (ORIGINALLY FROM UT VARIANT; REALLY PP FROM CR VARIANT)
!  WB USES SO WB (ORIGINALLY FROM TT VARIANT)
!  LM USES UT LM
!  PY USES SO PY (ORIGINALLY FROM WC VARIANT)
!  YC USES WC YC
!  AS USES SO AS (ORIGINALLY FROM UT VARIANT)
!  CW USES SO CW (ORIGINALLY FROM WC VARIANT)
!  OS USES BM PP BARK COEFFICIENT
!  OH USES SO OH (ORIGINALLY FROM WC VARIANT)
!----------
!  THESE VALUES SHOULD BE BASED ON THE BASE-AGE OF THE SITE CURVE
!  BEING USED FOR THAT SPECIES.
!----------
DATA SITELO/ &
     20.,  50.,  50.,  50.,  15.,   5.,  30.,  40.,  50.,  70., &
     20.,  20.,   5.,  50.,  30.,  10.,  70.,   5./
!
DATA SITEHI/ &
     80., 110., 110., 110.,  30.,  40.,  70., 120., 150., 140., &
     65.,  50.,  75., 110.,  66., 191., 140., 125./
!----------
SELECT CASE (IWHO)
!
!  CALLED FROM SUBROUTINES **SITSET** AND **REGENT**
!
  CASE (1,2,3)
    SILOW = SITELO(IS)
    SIHIGH = SITEHI(IS)
!
!  SPACE FOR ADDITIONAL CALLS
!
  CASE DEFAULT
    SILOW = 0.
    SIHIGH = 999.
!
END SELECT
!
RETURN
END
