SUBROUTINE FINDAG(I,ISPC,D1,D2,H,SITAGE,SITHT,AGMAX,HTMAX1,HTMAX2, &
                     DEBUG)
IMPLICIT NONE
!----------
! EM $Id$
!----------
!  THIS ROUTINE SETS EFFECTIVE TREE AGE BASED ON INPUT VARIABLE(S)
!  SUCH AS TREE HEIGHT.  IN EM, AGE IS CALCULATED FOR THE ORIGINAL
!  SPECIES WB, WL, DF, LP, ES, AF, PP, AND OS, ALSO THE ADDED SPECIES
!  AS AND PB
!  CALLED FROM **CRATET
!  CALLED FROM **COMCUP
!----------
!  COMMONS
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'PLOT.f90'
!
!----------
LOGICAL DEBUG
INTEGER I,ISPC
REAL H,SI100,SI50,PHTG
REAL D1,D2,SITAGE,SITHT,AGMAX,HTMAX1,HTMAX2
REAL RDANUW
!----------
!  SPECIES ORDER:
!   1=WB,  2=WL,  3=DF,  4=LM,  5=LL,  6=RM,  7=LP,  8=ES,
!   9=AF, 10=PP, 11=GA, 12=AS, 13=CW, 14=BA, 15=PW, 16=NC,
!  17=PB, 18=OS, 19=OH
!
!  SPECIES EXPANSION
!  LM USES IE LM (ORIGINALLY FROM TT VARIANT)
!  LL USES IE AF (ORIGINALLY FROM NI VARIANT)
!  RM USES IE JU (ORIGINALLY FROM UT VARIANT)
!  AS,PB USE IE AS (ORIGINALLY FROM UT VARIANT)
!  GA,CW,BA,PW,NC,OH USE IE CO (ORIGINALLY FROM CR VARIANT)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
RDANUW = AGMAX
RDANUW = D1
RDANUW = D2
RDANUW = HTMAX1
RDANUW = HTMAX2
RDANUW = SITAGE
RDANUW = SITHT
!
!----------
!
IF(DEBUG)WRITE(JOSTND,*)' ENTERING FINDAG'
IF(DEBUG)WRITE(JOSTND,91201)SITEAR
91201 FORMAT(' SITEAR =',10(11F10.4,/' ',8X))
!----------
!  AT THIS POINT PRODUCE A SITE INDEX FOR THE SPECIES
!   SPECIES   BASE YR   REF
!     WB       100      ALEXANDER TACKLE AND DAHMS REDUCED TO .75
!     DF        50      MONSERUD
!     LP       100      ALEXANDER TACKLE AND DAHMS
!     AF       100      ALEXANDER
!     ES       100      ALEXANDER
!     PP       100      MEYER  BULL 630
!      ALL OTHERS PRODUCE A HTG OF 0.0
!
! THIS MAY REQUIRE AN EARLIER CONVERSION TO A 50 YR BASE STD INDEX
! PRODUCED FROM PFISTER HABS OF MONTANA
! THEN 50YR BASE = 1.0096 + .6279*SI100
!----------
SI100 = 0.0
SI50  = 0.0
IF(ISPC .EQ. 3) THEN
  SI50 = 1.0096 + 0.6279 * SITEAR(ISISP)
  IF(ISISP .EQ. 3)SI50 = SITEAR(ISISP)
ENDIF
IF(ISPC .EQ. 1 .OR. (ISPC.GE.7 .AND. ISPC.LE.10)) THEN
 SI100 = SITEAR(ISISP)
  IF(ISISP .EQ. 3) SI100 = (SITEAR(ISISP) - 1.0096) / 0.6279
ENDIF
IF((ISPC .EQ. 2) .OR. (ISPC .EQ. 18)) SI100= SITEAR(ISPC)
!----------
!  CALL  POTHTG TO CALCULATE EFFECTIVE TREE AGE
!  THE ABIRTH ARRAY IS SET IN POTHTG
!----------
CALL POTHTG(I,ISPC,H,SI50,SI100,PHTG,DEBUG)
!
IF(DEBUG)WRITE(JOSTND,91200)I,ISPC, SI100, H, DBH(I), ABIRTH(I)
91200 FORMAT(' IN FINDAG--I,ISPC, SI100, H, DBH, ABIRTH= ',2I5,4F10.2)
!
IF(DEBUG)WRITE(JOSTND,50)ICYC
50 FORMAT(' LEAVING SUBROUTINE FINDAG  CYCLE =',I5)
!
RETURN
END
!**END OF CODE SEGMENT
