SUBROUTINE FORKOD
IMPLICIT NONE
!----------
! EM $Id$
!----------
!
!     TRANSLATES FOREST CODE INTO A SUBSCRIPT, IFOR, AND IF
!     KODFOR IS ZERO, THE ROUTINE RETURNS THE DEFAULT CODE.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
!OMMONS
!
!----------
!  NATIONAL FORESTS:
!  102 = BEAVERHEAD
!  108 = CUSTER
!  109 = DEERLODGE
!  111 = GALLATIN
!  112 = HELENA
!  115 = LEWIS AND CLARK
!  ------------------------
!  RESERVATION PSUEDO CODES:
!  7101 = CHEYENNE RIVER RESERVATION     (MAPPED TO 108 CUSTER)
!  7102 = FORT BERTHOLD RESERVATION      (MAPPED TO 108 CUSTER)
!  7103 = SPIRIT LAKE RESERVATION        (MAPPED TO 108 CUSTER)
!  7107 = LAKE TRAVERSE RESERVATION      (MAPPED TO 108 CUSTER)
!  7108 = STANDING ROCK RESERVATION      (MAPPED TO 108 CUSTER)
!  7109 = TURTLE MT. OFF-RES. TRUST LAND (MAPPED TO 108 CUSTER)
!  7301 = BLACKFEET INDIAN RESERVATION   (MAPPED TO 115 LEWIS & CLARK)
!  7302 = CROW RESERVATION               (MAPPED TO 108 CUSTER)
!  7303 = FORT BELKNAP V                 (MAPPED TO 115 LEWIS & CLARK)
!  7304 = FORT PECK INDIAN RESERVATION   (MAPPED TO 115 LEWIS & CLARK)
!  7305 = NORTHERN CHEYENNE INDIAN RES.  (MAPPED TO 108 CUSTER)
!  7307 = ROCKY BOY'S RESERVATION        (MAPPED TO 115 LEWIS & CLARK)
!  ------------------------
!
!  FOR THE GEOGRAPHIC LOCATOR (NI KFOR VALUE):
!  MAP THE HELENA, AND LEWIS AND CLARK, TO THE LOLO NF
!  MAP ALL THE OTHERS TO THE BITTERROOT NF
!----------
INTEGER JFOR(11),KFOR(11),NUMFOR,I
LOGICAL USEIGL, FORFOUND
!----------
!  SPECIES ORDER:
!   1=WB,  2=WL,  3=DF,  4=LM,  5=LL,  6=RM,  7=LP,  8=ES,
!   9=AF, 10=PP, 11=GA, 12=AS, 13=CW, 14=BA, 15=PW, 16=NC,
!  17=PB, 18=OS, 19=OH
!
!  SPECIES EXPANSION
!  LM USES IE LM (ORIGINALLY FROM TT VARIANT)
!  LL USES IE AF (ORIGINALLY FROM NI VARIANT)
!  RM USES IE JU (ORIGINALLY FROM UT VARIANT)
!  AS,PB USE IE AS (ORIGINALLY FROM UT VARIANT)
!  GA,CW,BA,PW,NC,OH USE IE CO (ORIGINALLY FROM CR VARIANT)
!----------
DATA JFOR/102,108,109,111,112,115,5*0/, NUMFOR /6/
DATA KFOR/1,1,1,1,1,1,5*1 /

USEIGL = .TRUE.
FORFOUND = .FALSE.


SELECT CASE (KODFOR)

!       CROSSWALK FOR RESERVATION PSUEDO CODES & LOCATION CODE
  CASE (7101)
    WRITE(JOSTND,61)
61     FORMAT(/,'********',T12,'CHEYENNE RIVER RESERVATION ', &
       '(7101) BEING MAPPED TO CUSTER NF (108) FOR FURTHER ', &
       'PROCESSING.')
    IFOR = 2
  CASE (7102)
    WRITE(JOSTND,62)
62     FORMAT(/,'********',T12,'FORT BERTHOLD RESERVATION (7102)', &
       ' BEING MAPPED TO CUSTER NF (108) FOR FURTHER PROCESSING.')
    IFOR = 2
  CASE (7103)
    WRITE(JOSTND,63)
63     FORMAT(/,'********',T12,'SPIRIT LAKE RESERVATION (7103) ', &
       'BEING MAPPED TO CUSTER NF (108) FOR FURTHER PROCESSING.')
    IFOR = 2
  CASE (7107)
    WRITE(JOSTND,64)
64     FORMAT(/,'********',T12,'LAKE TRAVERSE RESERVATION (7107)', &
       ' BEING MAPPED TO CUSTER NF (108) FOR FURTHER PROCESSING.')
    IFOR = 2
  CASE (7108)
    WRITE(JOSTND,65)
65     FORMAT(/,'********',T12,'STANDING ROCK RESERVATION (7108)', &
       ' BEING MAPPED TO CUSTER NF (108) FOR FURTHER PROCESSING.')
    IFOR = 2
  CASE (7109)
    WRITE(JOSTND,66)
66     FORMAT(/,'********',T12,'TURTLE MOUNTAIN OFF-RES. LAND ', &
       '(7109) BEING MAPPED TO CUSTER NF (108) FOR FURTHER ', &
       'PROCESSING.')
    IFOR = 2
  CASE (7301)
    WRITE(JOSTND,67)
67     FORMAT(/,'********',T12,'BLACKFEET INDIAN RESERVATION ', &
       '(7301) BEING MAPPED TO LEWIS AND CLARK NF (115) FOR ', &
       'FURTHER PROCESSING.')
    IFOR = 6
  CASE (7302)
    WRITE(JOSTND,68)
68     FORMAT(/,'********',T12,'CROW RESERVATION (7302) BEING ', &
       'MAPPED TO CUSTER NF (108) FOR FURTHER PROCESSING.')
     IFOR = 2
  CASE (7303)
    WRITE(JOSTND,69)
69     FORMAT(/,'********',T12,'FORT BELKNAP RESERVATION (7303) ', &
       'BEING MAPPED TO LEWIS AND CLARK NF (115) FOR FURTHER ', &
       'PROCESSING.')
    IFOR = 6
  CASE (7304)
    WRITE(JOSTND,70)
70     FORMAT(/,'********',T12,'FORT PECK INDIAN RESERVATION ', &
       '(7304) BEING MAPPED TO LEWIS AND CLARK NF (115) FOR ', &
       'FURTHER PROCESSING.')
    IFOR = 6
  CASE (7305)
    WRITE(JOSTND,71)
71     FORMAT(/,'********',T12,'NORTHERN CHEYENNE INDIAN ', &
       'RESERVATION (7305) BEING MAPPED TO CUSTER NF (108) FOR ', &
       'FURTHER PROCESSING.')
    IFOR = 2
  CASE (7307)
    WRITE(JOSTND,72)
72     FORMAT(/,'********',T12,'ROCKY BOY''S RESERVATION (7307) ', &
       'BEING MAPPED TO LEWIS AND CLARK NF (115) FOR FURTHER ', &
       'PROCESSING.')
    IFOR = 6
!       END CROSSWALK FOR RESERVATION PSUEDO CODES & LOCATION CODE


  CASE DEFAULT

!         CONFIRMS THAT KODFOR IS AN ACCEPTED FVS LOCATION CODE
!         FOR THIS VARIANT FOUND IN DATA ARRAY JFOR
    DO 10 I=1,NUMFOR
      IF (KODFOR .EQ. JFOR(I)) THEN
        IFOR = I
        FORFOUND = .TRUE.
        EXIT
      ENDIF
10     CONTINUE

!         LOCATION CODE ERROR TRAP
    IF (.NOT. FORFOUND) THEN
      CALL ERRGRO (.TRUE.,3)
      WRITE(JOSTND,11) JFOR(IFOR)
11       FORMAT(/,'********',T12,'FOREST CODE USED IN THIS ', &
         'PROJECTION IS',I4)
      USEIGL = .FALSE.
    ENDIF

END SELECT


!     FOREST MAPPING CORRECTION {NOT USED IN THIS VARIANT}
!     SELECT CASE (IFOR)
!     END SELECT
!     IF(IFOR .EQ. 6) IFOR = 3  THIS WAS COMMENTED OUT


!     SET THE IGL VARIABLE ONLY IF DEFAULT FOREST IS USED
!     GEOGRAPHIC LOCATION CODE: 1=NORTH, 2=CENTRAL, 3=SOUTH
!     USED TO SET SOME EQUATIONS IN REGENERATION AND PERHAPS
!     HEIGHT-DIAMETER IN DIFFERENT VARIANTS.
IF (USEIGL) IGL = KFOR(IFOR)

KODFOR=JFOR(IFOR)
RETURN
END



