SUBROUTINE HABTYP (KARD2,ARRAY2)
IMPLICIT NONE
!----------
! EM $Id$
!----------
!
!     TRANSLATES HABITAT-TYPE CODE INTO A SUBSCRIPT, IEMTYP, AND IF
!     KODTYP IS ZERO, THE ROUTINE RETURNS THE DEFAULT CODE.
!     MAPS HABITAT-TYPE SUBSCRIPT INTO A SUBSCRIPT (ITYPE) REPRESENTING
!     ONE OF THE ORIGINAL 30 NI-VARIANT HABITAT TYPES
!
!     IEMTYP - SUBSCRIPT USED IN **SITSET
!     ITYPE  - SUBSCRIPT USED IN **ESTAB
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'EMCOM.f90'
!
!OMMONS
!----------
REAL ARRAY2
CHARACTER*10 KARD2
INTEGER NIHMAP(118),J
LOGICAL LPVCOD,LPVREF,LPVXXX
REAL RDANUW
!----------
!  SPECIES ORDER:
!   1=WB,  2=WL,  3=DF,  4=LM,  5=LL,  6=RM,  7=LP,  8=ES,
!   9=AF, 10=PP, 11=GA, 12=AS, 13=CW, 14=BA, 15=PW, 16=NC,
!  17=PB, 18=OS, 19=OH
!
!  SPECIES EXPANSION
!  LM USES IE LM (ORIGINALLY FROM TT VARIANT)
!  LL USES IE AF (ORIGINALLY FROM NI VARIANT)
!  RM USES IE JU (ORIGINALLY FROM UT VARIANT)
!  AS,PB USE IE AS (ORIGINALLY FROM UT VARIANT)
!  GA,CW,BA,PW,NC,OH USE IE CO (ORIGINALLY FROM CR VARIANT)
!----------
!  DATA STATEMENTS
!----------
DATA NIHMAP/ &
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, &
    1, 1, 1, 1, 1, 2, 2, 2, 2, 2, &
    2, 2, 4, 1, 1, 1, 1, 3, 4, 4, &
    4, 5, 5, 5, 5, 6, 6, 6, 6, 7, &
    7, 7, 7, 7, 8, 8, 8, 8, 9, 9, &
    9, 8, 8, 9, 7, 7,10,10, 4,11, &
    20,29,29,11,11,12,18,19,19,19, &
    21,21,20,20,20,20,20,20,20,20, &
    21,21,21,21,22,22,24,24,24,27, &
    25,26,27,27,27,27,22,24,24,27, &
    24,27,27,27,28,29,28,28,29,29, &
    29,27, 9,20,21,27,24,30/
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
RDANUW = ARRAY2
!
LPVREF=.FALSE.
LPVCOD=.FALSE.
LPVXXX=.FALSE.
!----------
!  IF REFERENCE CODE IS NON-ZERO THEN MAP PV CODE/REF. CODE TO
!  FVS HABITAT TYPE/ECOCLASS CODE IN THE KODTYP VARIABLE.
!  THEN PROCESS KODTYP CODE (KODTYP IS PASSED BACK TO HABTYP
!  THROUGH COMMON)
!----------
!  The below ADJSUTL is used to add a leading zero to KODTYPs
!  (PV Code) that are two or less digits. For example, 18
!  would become 018
KARD2=ADJUSTL(KARD2)
IF(LEN_TRIM(KARD2).LE.2)THEN
  IF((ICHAR(KARD2(1:1)).GE.48).AND. &
        (ICHAR(KARD2(1:1)).LE.57).AND. &
        (ICHAR(KARD2(2:2)).GE.48).AND. &
        (ICHAR(KARD2(2:2)).LE.57))THEN
     KARD2='0'//KARD2(1:3)
  ENDIF
ENDIF
!
IF(CPVREF.NE.'          ') THEN
  CALL PVREF1(KARD2,LPVCOD,LPVREF)
  IF((LPVCOD.AND.LPVREF).AND. &
     (KODTYP.LE.0))THEN
    CALL ERRGRO(.TRUE.,34)
    LPVXXX=.TRUE.
    GOTO 21
  ELSEIF((.NOT.LPVCOD).AND.(.NOT.LPVREF))THEN
    CALL ERRGRO(.TRUE.,33)
    CALL ERRGRO(.TRUE.,32)
    LPVXXX=.TRUE.
    GOTO 21
  ELSEIF((.NOT.LPVREF).AND.LPVCOD)THEN
    CALL ERRGRO(.TRUE.,32)
    LPVXXX=.TRUE.
    GOTO 21
  ELSEIF((.NOT.LPVCOD).AND.LPVREF)THEN
    CALL ERRGRO(.TRUE.,33)
    LPVXXX=.TRUE.
    GOTO 21
  ENDIF
ENDIF
!
IF (KODTYP .EQ. 0) GOTO 21
IF (KODTYP.EQ.0 .OR. KODTYP.LT.JTYPE(1)) GOTO 21
!
DO 20 J=1,118
IF(KODTYP .LT. JTYPE(J)) GO TO 100
20 CONTINUE
21 CONTINUE
IF(.NOT.LPVXXX)CALL ERRGRO(.TRUE.,14)
IEMTYP=ITYPE
KODTYP= JTYPE(IEMTYP)
ITYPE=NIHMAP(IEMTYP)
IF(LSTART)WRITE(JOSTND,23) KODTYP
23 FORMAT(/,T12,'HABITAT TYPE CODE USED IN THIS PROJECTION IS',I4)
RETURN
100 CONTINUE
IEMTYP=J-1
IF(IEMTYP.LT.1)IEMTYP=1
KODTYP= JTYPE(IEMTYP)
ITYPE=NIHMAP(IEMTYP)
IF(LSTART)WRITE(JOSTND,30)KODTYP
30 FORMAT(/,T12,'HABITAT TYPE MAPPED TO',I4,' FOR THIS PROJECTION.')
RETURN
END
