SUBROUTINE LOGS(DBH,HT,IBCD,BDMIN,ISP,STMP,BV)
IMPLICIT NONE
!----------
! EM $Id$
!----------
!  REGION 5 BOARD FOOT VOLUME MODELS.
!  BY K.STUMPF, ADAPTED BY B.KRUMLAND, P.J.DAUGHERTY
!  NOT FOR USE IN REGION 1, SO JUST SET BV TO ZERO AND RETURN
!----------
!
REAL DBH,HT,BDMIN,STMP,BV
INTEGER IBCD,ISP
REAL RDANUW
INTEGER IDANUW
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
RDANUW = BDMIN
RDANUW = DBH
RDANUW = HT
IDANUW = IBCD
IDANUW = ISP
RDANUW = STMP
!
!
BV=0.
RETURN
END
