SUBROUTINE DFBDRV
IMPLICIT NONE
!----------
! DFB $Id$
!----------
!
!  THIS SUBROUTINE CALLS THE DFB MODEL SUBROUTINES THAT CAUSE THE
!  DOUGLAS-FIR MORTALITY.
!
!  CALLED BY :
!     GRADD   [PROGNOSIS]
!
!  CALLS :
!     DFBDBH  (SUBROUTINE)   [DFB]
!     DFBMOD  (SUBROUTINE)   [DFB]
!     DFBMRT  (SUBROUTINE)   [DFB]
!
!  COMMON BLOCK VARIABLES USED :
!     DEBUIN (DFBCOM)  INPUT
!     JODFB  (DFBCOM)  INPUT
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'DFBCOM.f90'
!
!
!OMMONS
!
IF (DEBUIN) WRITE (JODFB,*) ' ** ENTERING SUBROUTINE DFBDRV'

!
!     INITIALIZE START VALUES.
!
CALL DFBDBH

!
!     CALCULATE THE NUMBER OF TREES TO KILL.
!
CALL DFBMOD

!
!     PASS THE MORTALITY BACK TO PROGNOSIS.
!
CALL DFBMRT

IF (DEBUIN) WRITE (JODFB,*) ' ** LEAVING SUBROUTINE DFBDRV'

RETURN
END
