SUBROUTINE DFBER (NOER)
IMPLICIT NONE
!----------
! DFB $Id$
!----------
!
!  TESTS TO MAKE SURE MINIMUM CONDITIONS ARE MET FOR AN OUTBREAK TO
!  OCCUR.  CALCULATES BASAL AREA FOR DOUGLAS-FIR.
!
!  CALLED BY :
!     DFBGO  [DFB]
!
!  CALLS :
!     NONE
!
!  PARAMETERS :
!     NOER   - SET TO .TRUE. WHEN MINIMUM CONDITIONS MET FOR AN
!              OUTBREAK.
!
!  LOCAL VARIABLES :
!     BADF   - BASAL AREA FOR EACH DOUGLAS-FIR RECORD.
!     D      - DBH FOR TREE RECORD (SET TO DBH(TREE #)).
!     I      - INDEX FOR TREE RECORD (SET TO IND1(TREE PTR)).
!     II     - COUNTER INDEX.
!     I1,I2  - INDEXES FOR THE ARRAY IND1.  I1 IS THE STARTING
!              INDEX FOR A SPECIES IN ARRAY IND1 (DF = IDFSPC).
!              I2 IS THE ENDING INDEX FOR A SPECIES IN ARRAY IND1
!              (DF = IDFSPC).
!     P      - PROB FOR TREE RECORD (SET TO PROB(TREE #)).
!     TDF45  - NUMBER OF DOUGLAS-FIR (TREES/ACRE) THAT HAVE A DBH >= 4.5
!              INCHES.
!     BADF45 - BASAL AREA FOR ALL DOUGLAS-FIR TREES WITH DBH >= 4.5
!              INCHES.
!
!  COMMON BLOCK VARIABLES USED :
!     A45DBH - (DFBCOM)  OUTPUT
!     BA     - (PLOT)    INPUT
!     BA9    - (DFBCOM)  OUTPUT
!     BADF9  - (DFBCOM)  OUTPUT
!     DBH    - (ARRAYS)  INPUT
!     DEBUIN - (DFBCOM)  INPUT
!     IDFSPC - (DFBCOM)  INPUT
!     IND1   - (ARRAYS)  INPUT
!     ISCT   - (CONTRL)  INPUT
!     ITRN   - (CONTRL)  INPUT
!     JODFB  - (DFBCOM)  INPUT
!     PBADF4 - (DFBCOM)  OUTPUT
!     PROB   - (ARRAYS)  INPUT
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'DFBCOM.f90'
!
!
!OMMONS
!
LOGICAL NOER

INTEGER I, II, I1, I2

REAL BADF, BADF45, TDF45, D, P

IF (DEBUIN) WRITE (JODFB,*) ' ** ENTERING SUBROUTINE DFBER'

!.... INITIALIZE VARIABLES.

NOER   = .TRUE.
BADF45 = 0.0
BADF9  = 0.0
A45DBH = 0.0
TDF45  = 0.0
PBADF4 = 0.0
BA9    = 0.0

!.... CALCULATE THE BASAL AREA FOR ALL TREES IN THE STAND WITH A DBH
!.... GREATER THEN OR EQUAL TO 9.0 INCHES.

DO 100 II = 1,ITRN
   IF (DBH(II) .GE. 9.0) THEN
      BA9 = BA9 + 0.005454154 * DBH(II) * DBH(II) * PROB(II)
   ENDIF
100 CONTINUE

!.... CALCULATE THE BASAL AREA, AVERAGE DBH VALUES, AND TREES/ACRE FOR
!.... DIFFERENT SIZE GROUPS IN DOUGLAS-FIR.

I1 = ISCT(IDFSPC,1)
IF (I1 .EQ. 0) GOTO 300
I2 = ISCT(IDFSPC,2)

DO 200 II = I1, I2
   I = IND1(II)
   P = PROB(I)
   D = DBH(I)
   BADF =  0.005454154 * D * D * P

   IF (D .GE. 4.5) THEN
      TDF45 = TDF45 + P
      A45DBH = A45DBH + D * P
      BADF45 = BADF45 + BADF
   ENDIF

   IF (D .GE. 9.0) THEN
      BADF9 = BADF9 + BADF
   ENDIF
200 CONTINUE

!.... NOT ENOUGH DF FOR OUTBREAK TO OCCUR.  GO TO THE END.

IF (TDF45 .LT. 1.0) GOTO 300

!.... PROPORTION BASAL AREA IN DF GREATER THEN 4.5 INCHES

PBADF4 = BADF45 / BA

!.... AVERAGE DBH FOR DOUGLAS-FIR TREES WITH A DBH >= 4.5 INCHES.

A45DBH = A45DBH  / TDF45
GOTO 400

300 CONTINUE

!.... SET FLAG TO SAY NO OUTBREAK WILL OCCUR.

NOER = .FALSE.

400 CONTINUE
IF (DEBUIN) WRITE (JODFB,*) ' ** LEAVING SUBROUTINE DFBER'

RETURN
END
