SUBROUTINE DFBINV
IMPLICIT NONE
!----------
! DFB $Id$
!----------
!
!  COUNTS THE TREES/ACRE OF DOUGLAS-FIR READ IN AS KILLED BY DFB.
!
!  CALLED BY :
!     MAIN     [PROGNOSIS]
!
!  CALLS :
!     NONE
!
!  LOCAL VARIABLES :
!     I      - INDEX TO RECENTLY ATTACKED TREES.
!     II     - COUNTER.
!
!  COMMON BLOCK VARIABLES USED :
!     IPT    - (DFBCOM)  INPUT
!     LINV   - (DFBCOM)  INPUT
!     NDAMS  - (DFBCOM)  INPUT
!     PREKLL - (DFBCOM)  OUTPUT
!     PROB   - (ARRAYS)  INPUT
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'DFBCOM.f90'
!
!
!OMMONS
!

INTEGER I, II

!.... COUNT THE TREES/ACRE KILLED BY DFB AND READ IN THROUGH DAMAGE
!.... CODES IN THE TREE LIST DATA.

IF (NDAMS .GT. 0 .AND. LINV) THEN
   PREKLL = 0.0
   DO 100 II = 1,NDAMS
      I = IPT(II)
      PREKLL = PREKLL + PROB(I)
100    CONTINUE
ENDIF

RETURN
END
