SUBROUTINE DFBMOD
IMPLICIT NONE
!----------
! DFB $Id$
!----------
!
!  THIS ROUTINE CALCULATES THE PROJECTED NUMBER OF DOUGLAS-FIR TREES TO
!  KILL IN THE CURRENT DFB OUTBREAK.
!
!  CALLED BY :
!     DFBDRV  [DFB]
!
!  CALLS :
!     BACHLO (FUNCTION)   [PROGNOSIS]
!     DFBRAN (FUNCTION)   [DFB]        - CALLED THROUGH BACHLO.
!
!  LOCAL VARIABLES :
!     NUMYRS - LENGTH OF OUTBREAK.
!     DFBRAN - NAME OF RANDOM NUMBER GENERATOR ROUTINE CALLED BY BACHLO.
!
!  COMMON BLOCK VARIABLES USED :
!     BA9    - (DFBCOM)  INPUT
!     BADF9  - (DFBCOM)  INPUT
!     DEBUIN - (DFBCOM)  INPUT
!     DFKILL - (DFBCOM)  OUTPUT
!     EXPCTD - (DFBCOM)  INPUT
!     EXSTDV - (DFBCOM)  INPUT
!     ICYC   - (CONTRL)  INPUT
!     IFINT  - (PL0T)    INPUT
!     ILENTH - (DFBCOM)  INPUT
!     IYOUT  - (DFBCOM)  INPUT
!     JODFB  - (DFBCOM)  INPUT
!     LINPRG - (DFBCOM)  INPUT
!     OKILL  - (DFBCOM)  INPUT
!     PERDD  - (DFBCOM)  INPUT
!     PREKLL - (DFBCOM)  INPUT
!     START  - (DFBCOM)  INPUT
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'DFBCOM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
!OMMONS
!
INTEGER NUMYRS
REAL    BACHLO
EXTERNAL DFBRAN

!
!     SET NUMYRS TO THE LENGTH OF OUTBREAK IN YEARS.
!
IF (ILENTH .GT. IFINT) THEN
   NUMYRS = IFINT
ELSE
   NUMYRS = ILENTH
ENDIF

IF (NUMYRS .GT. 10)  NUMYRS = 10

IF (LINPRG .AND. ICYC .EQ. 1) THEN
!
!        OUTBREAK IN PROGRESS. USE USER ENTERED VALUES.
!
   NUMYRS = NUMYRS - IYOUT
   IF (IYOUT .GT. 4.0) THEN
!
!           OUTBREAK TO LONG TO USE THIS FUNCTION.  OUTBREAK ASSUMED TO
!           BE OVER.
!
      DFKILL = 0.0
   ELSEIF (PREKLL .LE. 0.0) THEN
!
!           USER DID NOT ENTER ANY MORTALITY VALUES.  CALCULATE
!           HOW MANY TREES SHOULD BE KILLED TO FINISH A 4 YEAR OUTBREAK.
!           IF DFKILL IS LESS THEN ZERO THEN RECALCULATE WITH NEW RANDOM
!           NUMBER.
!
100       CONTINUE
         DFKILL = BACHLO(EXPCTD,EXSTDV,DFBRAN) * (BADF9 / BA9) * &
                     4.0 * (1.0 - PERDD(IYOUT))
      IF (DFKILL .LT. 0.0) GOTO 100

   ELSE
!
!           USER ENTERED MORTALITY VALUES.
!           CALCULATE HOW MANY MORE TO KILL.
!
      DFKILL = PREKLL / PERDD(IYOUT) - PREKLL
   ENDIF
ELSE
!
!        CALCULATE NUMBER OF DF TO KILL IF NEW OUTBREAK.
!        IF DFKILL IS LESS THEN ZERO THEN RECALCULATE WITH NEW RANDOM
!        NUMBER.
!
200    CONTINUE
      DFKILL = BACHLO(EXPCTD,EXSTDV,DFBRAN) * (BADF9 / BA9) * &
                  NUMYRS + OKILL
   IF (DFKILL .LT. 0.0) GOTO 200
ENDIF

400 CONTINUE

IF (DEBUIN) WRITE (JODFB,*) ' ** LEAVING SUBROUTINE DFBMOD'

RETURN
END
