SUBROUTINE DFBOUT
IMPLICIT NONE
!----------
! DFB $Id$
!----------
!
!  WRITES DFB OUTBREAK SUMMARY AND COPIES THE DFBB OUTPUT TABLES TO
!  THE MAIN PROGNOSIS OUTPUT FILE.
!
!  CALLED BY :
!     MAIN   [PROGNOSIS]
!
!  CALLS :
!     DFBHED  (SUBROUTINE)  [DFB]
!
!  LOCAL VARIABLES :
!     DSTRNG - CHARACTER STRING USED TO READ THE DFB OUTPUT FILE AND
!              WRITE IT TO THE PROGNOSIS OUTPUT FILE.
!     I      - COUNTER INDEX.
!     NO     - THE WORD 'NO'.
!     OUTBRK - SET TO 'YES' OR 'NO' DEPENDING ON IF THERE WAS AN
!              OUTBREAK OR NOT.
!     YES    - THE WORD 'YES'.
!
!  COMMON BLOCK VARIABLES USED :
!     IDFBYR - (DFBCOM)  INPUT
!     IY     - (CONTRL)  INPUT
!     JODFB  - (DFBCOM)  INPUT
!     JOSTND - (CONTRL)  INPUT
!     LDFBON - (DFBCOM)  INPUT
!     NCYC   - (CONTRL)  INPUT
!     PRBDFB - (DFBCOM)  INPUT
!     WORKIN - (DFBCOM)  INPUT
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'DFBCOM.f90'
!
!
!OMMONS
!

INTEGER I

CHARACTER*133 DSTRNG
CHARACTER*3   OUTBRK
CHARACTER*3   YES
CHARACTER*2   NO

DATA YES /'YES'/, NO /'NO'/

IF (.NOT. LDFBON) RETURN

!
!     WRITE OUT TABLE HEADER.
!
CALL DFBHED
WRITE (JODFB,100)
100 FORMAT (22('-'),' DOUGLAS-FIR BEETLE ACTIVITY SUMMARY ', &
           23('-'),//,'-------- CYCLE --------',8X,'YEAR OF',11X, &
           'CONDITIONAL',10X,'WAS THERE AN',/,'NUMBER',12X,'YEARS', &
           5X,'REGIONAL DFB',8X,'PROBABILITY',10X,'OUTBREAK IN',/, &
           31X,'OUTBREAK',7X,'OF STAND OUTBREAK',7X,'THIS STAND',/, &
           82('-'),/)

!
!     PRINT OUT SUMMARY OUTBREAK TABLE.
!
DO 200 I=1,NCYC
   OUTBRK = NO
   IF (WORKIN(I)) OUTBRK = YES
   IF (IDFBYR(I) .EQ. 0) WRITE (JODFB,300) I, IY(I), IY(I+1), &
                           PRBDFB(I), OUTBRK
   IF (IDFBYR(I) .NE. 0) WRITE (JODFB,400) I, IY(I), IY(I+1), &
                           IDFBYR(I), PRBDFB(I), OUTBRK
200 CONTINUE

300 FORMAT(I3,9X,I4,' - ',I4,T48,F10.3,T75,A3)
400 FORMAT(I3,9X,I4,' - ',I4,10X,I4,T48,F10.3,T75,A3)

!
!     THE REST OF THE SUBROUTINE COPIES THE DOUGLAS-FIR BEETLE
!     OUTPUT TO THE MAIN PROGNOSIS PRINT FILE (JOSTND).
!
IF (JODFB .EQ. JOSTND) RETURN
REWIND JODFB

500 CONTINUE
READ (JODFB,600,END=1000) DSTRNG
WRITE (JOSTND,600) DSTRNG
GOTO 500

600 FORMAT(A133)

1000 CONTINUE
REWIND JODFB

RETURN
END
