SUBROUTINE DFBTAB(CFTVOL)
IMPLICIT NONE
!----------
! DFB $Id$
!----------
!
!  PRINTS OUT THE DOUGLAS-FIR BEETLE SUMMARY TABLE.
!
!  CALLED BY :
!     DFBMRT [DFB]
!
!  CALLS :
!     DFBIND  (SUBROUTINE)  [DFB]
!
!  PARAMETERS :
!     CFTVOL - ARRAY THAT HOLDS THE CUBIC FOOT VOLUME LOST DUE TO DFB
!              FOR EACH DBH CLASS.
!
!  LOCAL VARIABLES :
!     DCLASS - ARRAY THAT HOLDS THE DIAMETER CLASS HEADINGS THAT ARE
!              TO BE PRINTED IN THE SUMMARY TABLE.
!     I      - INDEX,  COUNTER.
!     TDEAD  - HOLDS THE TOTAL NUMBER OF DOUGLAS-FIR KILLED BY THE DFB
!              (TREES/ACRE).
!     TLIVE  - HOLDS THE TOTAL NUMBER OF LIVE DOUGLAS-FIR (TREES/ACRE).
!     DCNDX  - THE DBH CLASS OF THE CURRENT TREE RECORD.
!     TTOTL  - HOLDS THE TOTAL NUMBER OF LIVE TREES (TREES/ACRE).
!     TVOL   - HOLDS THE TOTAL CUBIC FOOT VOLUME LOST DUE TO THE DFB.
!     TOTGRN - ARRAY THAT HOLDS THE TOTAL LIVE TREES/ACRE FOR EACH DBH
!              CLASS IN THE STAND.
!
!  COMMON BLOCK VARIABLES USED :
!     DBH    - (ARRAYS)  INPUT
!     DEADDF - (DFBCOM)  INPUT
!     DFKILL - (DFBCOM)  INPUT
!     ICYC   - (CONTRL)  INPUT
!     ITRN   - (CONTRL)  INPUT
!     IY     - (CONTRL)  INPUT
!     IYOUT  - (DFBCOM)  INPUT
!     JODFB  - (DFBCOM)  INPUT
!     JODFBX - (DFBCOM)  INPUT
!     LINPRG - (DFBCOM)  INPUT/OUTPUT
!     LINV   - (DFBCOM)  INPUT/OUTPUT
!     LIVEDF - (DFBCOM)  INPUT
!     PREKLL - (DFBCOM)  INPUT
!     PROB   - (ARRAYS)  INPUT
!
!OMMONS
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'DFBCOM.f90'
!
!OMMONS
!

INTEGER I, DCNDX

REAL    TOTGRN(20), CFTVOL(20), TDEAD, TLIVE, TTOTL, TVOL

CHARACTER*8 DCLASS(20)

DATA DCLASS / ' 1 -  3',' 3 -  5',' 5 -  7',' 7 -  9',' 9 - 11', &
                 '11 - 13','13 - 15','15 - 17','17 - 19','19 - 21', &
                 '21 - 23','23 - 25','25 - 27','27 - 29','29 - 31', &
                 '31 - 33','33 - 35','35 - 37','37 - 39','39 - 40+' /

!
!     INITIALIZE TOTGRN
!
DO 100 I = 1,20
   TOTGRN(I) = 0.0
100 CONTINUE

!
!     BREAK PROGNOSIS PROB ARRAY INTO DBH CLASSES.
!
DO 250 I = 1, ITRN
   CALL DFBIND (DBH(I), DCNDX)
   TOTGRN(DCNDX) = TOTGRN(DCNDX) + PROB(I)
250 CONTINUE

!
!     PRINT DOUGLAS-FIR BEETLE SUMMARY TABLE HEADERS.
!
WRITE (JODFB,500)
WRITE (JODFB,510)

IF (LINV .AND. LINPRG .AND. ICYC .EQ. 1) &
      WRITE (JODFB,515) INT(PREKLL), IYOUT
!
!     TURN OFF OUTBREAK IN PROGRESS.
!
LINV   = .FALSE.
LINPRG = .FALSE.

!
!     PRINT TABLE HEADERS.
!
WRITE (JODFB,520) IY(ICYC)
WRITE (JODFB,525) DFKILL
WRITE (JODFB,*)
WRITE (JODFB,530)

500 FORMAT (//,'             DOUGLAS-FIR BEETLE MORTALITY')
510 FORMAT (1X,'---------------------------------------------------', &
           '-------')
515 FORMAT (1X,I4,' TREES WERE READ IN AS DEAD AFTER ',I1,' YEAR(S) ', &
          'OF DFB MORTALITY.')
520 FORMAT (1X,'YEAR OF THE OUTBREAK             : ',I5)
525 FORMAT (1X,'PROJECTED MORTALITY (TREES/ACRE) : ',F5.1)
530 FORMAT (1X,'             TOTAL         DF          DF     ', &
           '     DF    ',/, &
           1X,'           TREES/ACRE  TREES/ACRE  TREES/ACRE ', &
           ' CU/FT VOL ',/, &
           1X,'DBH CLASS    ALIVE       ALIVE       KILLED   ', &
           '    LOST   ',/, &
           1X,'---------  ----------  ----------  ---------- ', &
           ' ----------')

!
!     IF USER WANTS POST PROCESSOR OUTPUT THEN PRINT THE YEAR TO THE
!     POST PROCESSOR FILE.
!
IF (JODFBX .GT. 0) WRITE (JODFBX,540) IY(ICYC)
540 FORMAT (I4)

!
!     INITIALIZE THE VARIABLES THAT KEEP THE TOTALS.
!
TLIVE = 0.0
TDEAD = 0.0
TTOTL = 0.0
TVOL  = 0.0

!
!     PRINT OUT SUMMARY TABLE INFORMATION AND CALCULATE TOTALS.
!
DO 600 I = 1,20
   TOTGRN(I) = TOTGRN(I) - DEADDF(I)
   WRITE (JODFB,700) DCLASS(I), TOTGRN(I), LIVEDF(I), &
                        DEADDF(I), CFTVOL(I)
!
!        PRINT POST PROCESSOR OUTPUT IF USER USED DFBECHO KEYWORD.
!
   IF (JODFBX .GT. 0) WRITE (JODFBX,700) DCLASS(I), &
         TOTGRN(I), LIVEDF(I), DEADDF(I), CFTVOL(I)
   TLIVE = TLIVE + LIVEDF(I)
   TDEAD = TDEAD + DEADDF(I)
   TTOTL = TTOTL + TOTGRN(I)
   TVOL  = TVOL  + CFTVOL(I)
600 CONTINUE

!
!     PRINT OUT THE SUMMARY TABLE TOTALS.
!
WRITE (JODFB,710)
WRITE (JODFB,720) TTOTL, TLIVE, TDEAD, TVOL

!
!     PRINT SUMMARY TOTALS TO POST PROCESSOR OUTPUT IF USER USED
!     DFBECHO KEYWORD.
!
IF (JODFBX .GT. 0) THEN
   WRITE (JODFBX,710)
   WRITE (JODFBX,720) TTOTL, TLIVE, TDEAD, TVOL
   WRITE (JODFBX,*)
ENDIF

700 FORMAT (3X,A8,3X,F6.1,6X,F6.1,6X,F6.1,5X,F7.1)
710 FORMAT (2X,'           ----------  ----------  ---------- ', &
           ' ----------')
720 FORMAT (14X,F6.1,6X,F6.1,6X,F6.1,5X,F7.1)


1000 CONTINUE
RETURN
END
