SUBROUTINE FINDAG(I,ISPC,D1,D2,H,SITAGE,SITHT,AGMAX1,HTMAX1, &
                     HTMAX2,DEBUG)
IMPLICIT NONE
!----------
! SO $Id$
!----------
!  THIS ROUTINE FINDS EFFECTIVE TREE AGE BASED ON INPUT VARIABLE(S)
!  CALLED FROM **COMCUP
!  CALLED FROM **CRATET
!  CALLED FROM **HTGF
!----------
!
!  COMMONS
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'PLOT.f90'
!
!OMMONS
!
!----------
!  LOCAL VARIABLE DEFINITIONS:
!----------
!  INCRNG = HAS A VALUE OF 1 WHEN THE SITE CURVE HAS BEEN MONOTONICALLY
!           INCREASING IN PREVIOUS ITERATIONS.
!   OLDHG = HEIGHT GUESS FROM PREVIOUS ITERATION.
!----------
!  DECLARATIONS
!----------
LOGICAL DEBUG
INTEGER I,ISPC,INCRNG
REAL AGMAX(MAXSP),HTMAX(MAXSP)
REAL AG,DIFF,H,HGUESS,SINDX,TOLER
REAL SITAGE,SITHT,AGMAX1,HTMAX1,HTMAX2,D1,D2
REAL RDANUW,OLDHG
!----------
!  DATA STATEMENTS
!----------
DATA AGMAX/ &
    500., 400., 900., 450., 650., 650., 350., 400., 500., 900., &
    900., 350., 350., 400., 400., 400., 400., 550., 550., 350., &
    350., 100., 100., 100., 100.,  50., 250.,  50.,  75.,  50., &
     50., 400., 100./
!
DATA HTMAX/ &
    165., 160., 180., 180., 150., 150., 130., 165., 180., 175., &
     80., 165., 120., 165., 165.,  85., 175., 165., 165.,  50., &
     50., 100., 100.,  75., 125.,  30.,  75.,  30.,  30.,  20, &
     25., 165., 100./
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
RDANUW = D1
RDANUW = D2
RDANUW = HTMAX2
!----------
!  INITIALIZATIONS
!----------
TOLER=2.0
SINDX = SITEAR(ISPC)
AGMAX1 = AGMAX(ISPC)
IF(IFOR.GT.3 .AND. IFOR.LT.10) AGMAX1=400.
HTMAX1 = HTMAX(ISPC)
AG = 2.0
!----------
! THE FOLLOWING LINES ARE AN RJ FIX 7-28-88
!----------
IF(ISPC.EQ.2 .OR. ISPC.EQ.10) AG=(98.38*EXP(SINDX*(-0.0422)))+1.0
IF(AG .LT. 2.0)AG = 2.0
IF(ISPC .EQ. 3)AG=18.0
!----------
!  CRATET CALLS FINDAG AT THE BEGINING OF THE SIMULATION TO
!  CALCULATE THE AGE OF INCOMING TREES.  AT THIS POINT ABIRTH(I)=0.
!  THE AGE OF INCOMING TREES HAVING H>=HTMAX1 IS CALCULATED BY
!  ASSUMING A GROWTH RATE OF 0.10FT/YEAR FOR THE INTERVAL H-HTMAX1.
!  TREES REACHING HTMAX1 DURING THE SIMULATION ARE IDENTIFIED IN HTGF.
!----------
IF(H .GE. HTMAX1) THEN
  SITAGE = AGMAX1 + (H - HTMAX1)/0.10
  SITHT = H
  IF(DEBUG)WRITE(JOSTND,*)' ISPC,AGMAX1,H,HTMAX1= ',ISPC, &
     AGMAX1,H,HTMAX1
  GO TO 30
ENDIF
!----------
!  DEAL WITH SPECIES THAT DON'T NEED ITEATION HERE:
!
!  COMPUTE HT GROWTH AND AGE FOR ASPEN. EQN FROM WAYNE SHEPPARD RMRS.
!----------
IF(ISPC.EQ.24)THEN
  SITAGE = (H*2.54*12.0/26.9825)**(1.0/1.1752)
  SITHT = H
  GO TO 30
!----------
!  WESTERN JUNIPER
!  WHITEBARK PINE
!----------
ELSEIF(ISPC.EQ.11 .OR. ISPC.EQ.16) THEN
  SITAGE = 0.
  SITHT = H
  GO TO 30
ENDIF
!
INCRNG = 0
HGUESS = 0.
75 CONTINUE
OLDHG = HGUESS
!
IF(DEBUG)WRITE(JOSTND,*)' IN FINDAG, CALLING HTCALC'
CALL HTCALC(IFOR,SINDX,ISPC,AG,HGUESS,JOSTND,DEBUG)
!
IF(DEBUG)WRITE(JOSTND,91200)I,IFOR,ISPC,AG,HGUESS,H
91200   FORMAT(' FINDAG I,IFOR,ISPC,AG,HGUESS,H ',3I5,3F10.2)
!----------
!  AVOID NEGATIVE PREDICTED HEIGHTS AT SMALL AGES FROM SOME SI CURVES
!  GED 4/20/18
!----------
IF(HGUESS .LT. 1.)GO TO 175
!
DIFF = ABS(HGUESS-H)
IF(DIFF .LE. TOLER .OR. H .LT. HGUESS)THEN
  SITAGE = AG
  SITHT = HGUESS
  IF(DEBUG)THEN
    WRITE(JOSTND, *)' DIFF,TOLER,H,HGUESS,AG,SITAGE,SITHT= ', &
       DIFF,TOLER,H,HGUESS,AG,SITAGE,SITHT
  ENDIF
  GO TO 30
END IF
!----------
!  SOME SITE CURVES DECREASE AT THE START BEFORE INCREASING. IF DECREASING,
!  KEEP GOING; IF SITE CURVE WAS INCREASING, BUT NOW HAS FLATTENED OFF, STOP
!  THE ITERATION GED 04/19/18
!----------
DIFF = (HGUESS-OLDHG)
IF(OLDHG.NE.0.0 .AND. DIFF.GE.0.05) INCRNG=1
IF(DEBUG)WRITE(JOSTND,*)' IN FINDAG OLDHG,DIFF,INCRNG= ', &
   OLDHG,DIFF,INCRNG
IF(INCRNG.EQ.1 .AND. DIFF .LT. 0.05)THEN
  SITAGE = AG
  SITHT = HGUESS
  IF(DEBUG)THEN
    WRITE(JOSTND, *)' SITE CURVE FLAT OLDHG,AG,HGUESS,SITAGE,', &
       'SITHT= ',OLDHG,AG,HGUESS,SITAGE,SITHT
  ENDIF
  GO TO 30
END IF
!
175 CONTINUE
AG = AG + 2.
!
IF(AG .GT. AGMAX1) THEN
!----------
!  H IS TOO GREAT AND MAX AGE IS EXCEEDED
!----------
  SITAGE = AGMAX1
  SITHT = H
  GO TO 30
ELSE
  GO TO 75
ENDIF
!
30 CONTINUE
IF(DEBUG)WRITE(JOSTND,50)I,SITAGE,SITHT,AGMAX1,HTMAX1
50 FORMAT(' LEAVING SUBROUTINE FINDAG  I,SITAGE,SITHT,AGMAX1,', &
   'HTMAX1 = ',I5,4F10.3)
!
RETURN
END
!**END OF CODE SEGMENT
