SUBROUTINE FORKOD
IMPLICIT NONE
!----------
! SO $Id$
!----------
!
!     TRANSLATES FOREST CODE INTO A SUBSCRIPT, IFOR, AND IF
!     KODFOR IS ZERO, THE ROUTINE RETURNS THE DEFAULT CODE.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
!OMMONS
!
!  ------------------------
!  NATIONAL FORESTS:
!  601 = DESCHUTES
!  602 = FREMONT
!  620 = WINEMA
!  505 = KLAMATH
!  506 = LASSEN
!  509 = MODOC
!  511 = PLUMAS
!  701 = INDUSTRY LANDS
!  702 = INDUSTRY LANDS
!         **702 is new code introduced to eliminate
!           REDUNDANCY ACROSS VARIANTS. 702 WILL BE
!           MAPPED TO 701 FOR PROCESSING
!  514 = SHASTA-TRINITY (MAPPED TO KLAMATH)
!  799 = WARM SPRINGS INDIAN RESERVATION
!  ------------------------
!  RESERVATION PSUEDO CODES:
!  7711 = FORT MCDERMITT RESERVATION  (MAPPED TO 602 FREMONT)
!  7836 = FORT BIDWELL RESERVATION    (MAPPED TO 509 MODOC)
!  7838 = SUSANVILLE INDIAN RANCHERIA (MAPPED TO 506 LASSEN)
!  7844 = CEDARVILLE RANCHERIA        (MAPPED TO 509 MODOC)
!  ------------------------
INTEGER JFOR(11),KFOR(11),NUMFOR,I
LOGICAL USEIGL, FORFOUND
DATA JFOR/601,602,620,505,506,509,511,701,514,799, &
             702/
DATA NUMFOR /11/
DATA KFOR/11*1/

USEIGL = .TRUE.
FORFOUND = .FALSE.


SELECT CASE (KODFOR)
!       CROSSWALK FOR RESERVATION PSUEDO CODES & LOCATION CODE
  CASE (7711)
    WRITE(JOSTND,61)
61     FORMAT(/,'********',T12,'FORT MCDERMITT RESERVATION (7711) ', &
       'BEING MAPPED TO FREMONT (602) FOR FURTHER PROCESSING.')
    IFOR = 2
  CASE (7836)
    WRITE(JOSTND,62)
62     FORMAT(/,'********',T12,'FORT BIDWELL RESERVATION (7836) ', &
       'BEING MAPPED TO MODOC (509) FOR FURTHER PROCESSING.')
    IFOR = 6
  CASE (7838)
    WRITE(JOSTND,63)
63     FORMAT(/,'********',T12,'SUSANVILLE INDIAN RANCHERIA (7838) ', &
       'BEING MAPPED TO LASSEN (506) FOR FURTHER PROCESSING.')
    IFOR = 5
  CASE (7844)
    WRITE(JOSTND,64)
64     FORMAT(/,'********',T12,'CEDARVILLE RANCHERIA (7844) BEING ', &
       'MAPPED TO MODOC (509) FOR FURTHER PROCESSING.')
    IFOR = 6
!       END CROSSWALK FOR RESERVATION PSUEDO CODES & LOCATION CODE

  CASE DEFAULT

!         CONFIRMS THAT KODFOR IS AN ACCEPTED FVS LOCATION CODE
!         FOR THIS VARIANT FOUND IN DATA ARRAY JFOR
    DO 10 I=1,NUMFOR
      IF (KODFOR .EQ. JFOR(I)) THEN
        IFOR = I
        FORFOUND = .TRUE.
        EXIT
      ENDIF
10     CONTINUE

!         LOCATION CODE ERROR TRAP
    IF (.NOT. FORFOUND) THEN
      CALL ERRGRO (.TRUE.,3)
      WRITE(JOSTND,11) JFOR(IFOR)
11       FORMAT(/,'********',T12,'FOREST CODE USED IN THIS ', &
         'PROJECTION IS',I4)
      USEIGL = .FALSE.
    ENDIF

END SELECT


!     FOREST MAPPING CORRECTION
SELECT CASE (IFOR)
  CASE (9)
    WRITE(JOSTND,21)
21     FORMAT(/,'********',T12,'SHASTA NF (514) BEING MAPPED TO ', &
       'KLAMATH (505) FOR FURTHER PROCESSING.')
    IFOR = 4
  CASE (11)
    WRITE(JOSTND,22)
22     FORMAT(/,'********',T12,'INDUSTRY LANDS (702) IS BEING ', &
       'MAPPED TO (701) FOR FURTHER PROCESSING.')
    IFOR = 8
END SELECT

!     SET THE IGL VARIABLE ONLY IF DEFAULT FOREST IS USED
!     GEOGRAPHIC LOCATION CODE: 1=NORTH, 2=CENTRAL, 3=SOUTH
!     USED TO SET SOME EQUATIONS IN REGENERATION AND PERHAPS
!     HEIGHT-DIAMETER IN DIFFERENT VARIANTS.
IF (USEIGL) IGL = KFOR(IFOR)

KODFOR=JFOR(IFOR)
RETURN
END
