SUBROUTINE GROHED (IUNIT)
IMPLICIT NONE
!----------
! SO $Id$
!----------
!     WRITES HEADER FOR BASE MODEL PORTION OF PROGNOSIS SYSTEM
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'INCLUDESVN.f90'
!
!OMMONS
!----------
INTEGER IUNIT
CHARACTER DAT*10,TIM*8,REV*10,SVN*8
!----------
!     CALL REVISE TO GET THE LATEST REVISION DATE FOR THIS VARIANT.
!----------
CALL REVISE (VARACD,REV)
!
!     CALL THE DATE AND TIME ROUTINE FOR THE HEADING.
!
CALL GRDTIM (DAT,TIM)
!
WRITE (IUNIT,40) SVN,REV,DAT,TIM
40 FORMAT (//T6,'FOREST VEGETATION SIMULATOR', &
     5X,'VERSION ',A,' -- S. CEN. OREGON/N.E. CALIF. PROGNOSIS', &
     T97,'RV:',A,T112,A,2X,A)
RETURN
END
