!ODE SEGMENT CRCOEF
!----------
! AK-COMMON $Id$
!----------
!
!     COEFFICIENTS USED TO PREDICT CROWN RATIO IN AK VARIANT
!     USED IN CROWN.F AND DUBSCR.F SUBROUTINES
!
REAL CRINT(MAXSP),CRHDR(MAXSP),CRRD(MAXSP),CRDQMD(MAXSP)
REAL CRNMLT(MAXSP),DHI(MAXSP),DLOW(MAXSP)
INTEGER ICFLG(MAXSP)
!
COMMON /CRCOM/ CRINT,CRHDR,CRRD,CRDQMD, &
                  CRNMLT,DHI,DLOW,ICFLG
!----------
!  DEFINITIONS OF VARIABLES IN 'CRCOM' COMMON BLOCK:
!----------
!     CRINT  -- SPECIES-SPECIFIC INTERCEPT COEFFICIENTS
!     CRHDR  -- SPECIES-SPECIFIC HEIGHT DIAMETER COEFFICIENTS
!     CRRD   -- SPECIES-SPECIFIC RELATIVE DENSITY COEFFICIENTS (ZEIDE SDI/ SDIMAX)
!     CRDQMD -- RELATIVE DIAMETER COEFFICIENT (COMMON ACROSS ALL SPECIES - DBH/QMD)
!     CRMLT  -- ARRAY CONTAING CROWN RATIO MULTIPLIERS
!     DHI    -- ARRAY CONTAINING UPPER DIAMETER LIMIT FOR CRNMULT KEYWORD
!     DLO    -- ARRAY CONTAINING LOWER DIAMETER LIMIT FOR CRNMULT KEYWORD
!     ICFLG  -- ARRAY CONTAINING CRNMULT KEYWORD INDICATOR FLAGS
!
!-----END SEGMENT
