!.... Code segment FMOPCM.
!----------
! FIRE-BASE-COMMON $Id$
!----------
!  **FMOPCM  FIRE-
!----------
!-----------------------------------------------------------------------
!  PURPOSE:
!     COMMON BLOCK VARIABLES NEEDED FOR THE OPTION PROCESSOR
!-----------------------------------------------------------------------
!
!COMMON BLOCK FMOPCM:
!     ACTNUM:  THE "MAGIC" NUMBER INDENTIFYING THE REQUESTED OPTION (MYACT)
!     NUMPRM:  THE NUMBER OF PARAMETERS STORED IN THE GIVEN OPTION
!     OPTON:   IS THE OPTION ON IN THE STAND?, & FOR WHAT PARAMETERS
!     PARMS:   THE STORED PARAMETERS FOR EACH RENDITION OF A GIVEN OPTION
!              (THAT YEAR)
!

!     VARIABLE DECLARATIONS

INTEGER  ACTNUM(MAXOPT)
INTEGER  NUMPRM(MAXOPT)
INTEGER  OPTON(MAXOPT,MXSTND)
REAL     PARMS(MAXOPT,7,MXSTND)

COMMON /FMOPCM/ ACTNUM,NUMPRM, OPTON, PARMS

!.... End segment.
