!ODE SEGMENT FMSNGL
!----------
! FIRE-BASE-COMMON $Id$
!----------
!  **FMSNGL FIRE
!----------
!
!     PARAMETERS WHICH ARE IN THE PPE VERSION, NOT IN THE SINGLE-
!     STAND VERSION, BUT WHICH ARE NEEDED BY THE MODEL (TO REDUCE
!     THE AMOUNT OF CODE THAT IS CHANGED).
!
INTEGER MXSTND
INTEGER NOSTND

PARAMETER (MXSTND=1)
PARAMETER (NOSTND=1)

!
!
!-----END SEGMENT
