SUBROUTINE DGBND (ISPC,DBH,DDG)
IMPLICIT NONE
!----------
! IE $Id$
!----------
!  THIS SUBROUTINE IS INSURES THAT A MAXIMUM VALUE FOR DIAMETER
!  GROWTH IS NOT EXCEEDED.
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
!OMMONS
!
!----------
! CHECK FOR SIZE CAP COMPLIANCE.
INTEGER ISPC
REAL DDG,DBH
!----------
IF((DBH+DDG).GT.SIZCAP(ISPC,1) .AND. SIZCAP(ISPC,3).LT.1.5)THEN
  DDG=SIZCAP(ISPC,1)-DBH
  IF(DDG .LT. 0.01) DDG=0.01
ENDIF
!
RETURN
END
