SUBROUTINE DUNN (SS)
IMPLICIT NONE
!----------
! IE $Id$
!----------
!
!     THIS SUBROUTINE PROCESSES THE DUNNING SITE CODE INFORMATION
!     ENTERED ON THE SITECODE KEYWORD. FOR INLAND EMPIRE VARIANT
!     THIS SUBROUTINE IS A DUMMY.
!
!OMMONS
!
!
REAL SS
REAL RDANUW
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
RDANUW = SS
!
RETURN
END
