SUBROUTINE FINDAG(I,ISPC,D1,D2,H,SITAGE,SITHT,AGMAX,HTMAX1,HTMAX2, &
                     DEBUG)
IMPLICIT NONE
!----------
! IE $Id$
!----------
!  THIS ROUTINE SET EFFECTIVE TREE AGE BASED ON INPUT VARIABLE(S)
!  SUCH AS TREE HEIGHT.  IN IE, AGE IS CALCULATED FOR AS,MM,AND PB
!  CALLED FROM **CRATET
!  CALLED FROM **COMCUP
!
!  COMMONS
!
INCLUDE 'PRGPRM.f90'
!
INCLUDE 'CONTRL.f90'
!
!  COMMONS
!----------
LOGICAL DEBUG
INTEGER I,ISPC
REAL D1,D2,H,SITAGE,SITHT,AGMAX,HTMAX1,HTMAX2
REAL RDANUW
INTEGER IDANUW
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
RDANUW = AGMAX
RDANUW = D1
RDANUW = D2
RDANUW = HTMAX1
RDANUW = HTMAX2
IDANUW = ISPC
!
!---------
!  COMPUTE AGE FOR ASPEN. THIS EQUATION IS ALSO USED FOR MM AND PB.
!  EQUATION FORMULATED BY
!  WAYNE SHEPPERD, ROCKY MTN FOREST EXP STATION, FT COLLINS, CO.
!----------
SITAGE = (H*2.54*12.0/26.9825)**(1.0/1.1752)
!
IF(DEBUG)WRITE(JOSTND,50)I,SITAGE,SITHT
50 FORMAT(' LEAVING SUBROUTINE FINDAG I,SITAGE,SITHT =',I5,2F10.3)
!
RETURN
END
