SUBROUTINE MAICAL
IMPLICIT NONE
!----------
! IE $Id$
!----------
!  THIS SUBROUTINE CALCULATES THE MAI FOR THE STAND. IT IS CALLED
!  FROM CRATET.
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE  'CONTRL.f90'
!
!
INCLUDE  'PLOT.f90'
!
!
!OMMONS
!
!----------
!
LOGICAL DEBUG
INTEGER ISPNUM(MAXSP),ISICD,IERR
REAL SSSI,ADJMAI
!----------
!  INITIALIZE INTERNAL VARIABLES:
!----------
DATA ISPNUM/119,073,202,017,263,242,108,093,019,122,264, &
               101,101,101,101,101,101,746,740,746,375,998, &
               101/
!
!
!-----------
!  SEE IF WE NEED TO DO SOME DEBUG.
!-----------
CALL DBCHK (DEBUG,'MAICAL',6,ICYC)
!
IF(DEBUG) WRITE(JOSTND,3)ICYC,ISISP,SITEAR(ISISP)
3 FORMAT(' ENTERING SUBROUTINE MAICAL  CYCLE =',I5,1X,I3, &
           F6.2)
!-------
!   RMAI IS FUNCTION TO CALCULATE ADJUSTED MAI.
!-------
IF (ISISP .EQ. 0) ISISP=3
SSSI=SITEAR(ISISP)
IF (SSSI .EQ. 0.) SSSI=140.
ISICD=ISPNUM(ISISP)
RMAI=ADJMAI(ISICD,SSSI,10.0,IERR)
IF(RMAI .GT. 128.0)RMAI=128.0
IF(DEBUG) WRITE(JOSTND,10)ICYC,RMAI
10 FORMAT(' LEAVING SUBROUTINE MAICAL  CYCLE =',I5,5X,'RMAI =',F10.3)
!
RETURN
END
