SUBROUTINE RCON
IMPLICIT NONE
!----------
! IE $Id$
!----------
!  MOST OF THE MODELS IN THE PROGNOSIS PROGRAM CONTAIN TERMS
!  FOR VARIABLES SUCH AS HABITAT TYPE, SLOPE, ASPECT, ELEVATION,
!  AND GEOGRAPHIC LOCATION (FOREST) THAT ARE CONSTANT FOR THE
!  DURATION OF ANY STAND PROJECTION.  THIS SUBROUTINE IS CALLED
!  BY **CRATET** BEFORE MODEL CALIBRATION TO EVALUATE THE ABOVE
!  EFFECTS FOR THE SPECIFIED CONDITIONS.  THESE EFFECTS ARE THEN
!  LOADED INTO VECTORS THAT ARE SUBSCRIPTED BY SPECIES.
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'COEFFS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
!OMMONS
!
LOGICAL DEBUG
!-----------
!  CHECK FOR DEBUG.
!-----------
CALL DBCHK (DEBUG,'RCON',4,ICYC)
!----------
!  CALL SPECIAL ENTRIES WITHIN GROWTH MODELS TO LOAD SITE
!  DEPENDENT COEFFICIENTS.
!----------
CALL DGCONS
CALL HTCONS
CALL REGCON
CALL MORCON
CALL CRCONS
!----------
!  PRINT DEBUG INFO IF REQUESTED.
!----------
IF(.NOT.DEBUG) RETURN
WRITE(JOSTND,9001)
WRITE(JOSTND,9002) 'DGCON',DGCON
WRITE(JOSTND,9002) 'ATTEN',ATTEN
WRITE(JOSTND,9002) 'HTCON',HTCON
WRITE(JOSTND,9002) 'RHCON',RHCON
WRITE(JOSTND,9002) 'CRCON',CRCON
9001 FORMAT(/,' DEBUG TABLE SHOWING VALUES OF MODEL CONSTANTS', &
          ' BY SPECIES')
9002 FORMAT(1X,A,4X,((T11,11F10.4)))
WRITE(JOSTND,9003) H2COF,HDGCOF
9003 FORMAT(/' H2COF=',F10.4,',  HDGCOF=',F10.4)
RETURN
END
