SUBROUTINE BFVOL(ISPC,D,H,D2H,BBFV,TKILL,LCONE,BARK,VMAX,ITHT, &
                    BTKFLG)
IMPLICIT NONE
!----------
! LS $Id$
!----------
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'COEFFS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'OUTCOM.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'VOLSTD.f90'
!
!
!OMMONS
!
!  ************** BOARD FOOT MERCHANTABILITY SPECIFICATIONS ********
!
!  BFVOL CALCULATES BOARD FOOT VOLUME OF ANY TREE LARGER THAN A MINIMUM
!  DBH SPECIFIED BY THE USER.  MINIMUM DBH CAN VARY BY SPECIES,
!  BUT CANNOT BE LESS THAN 2 INCHES.  MINIMUM MERCHANTABLE DBH IS
!  SET WITH THE BFVOLUME KEYWORD.  FOR METHB = 1-4 MERCHANTABLE
!  TOP DIAMETER CAN BE SET TO ANY VALUE BETWEEN 2 IN. AND MINIMUM DBH.
!  MINIMUM DBH AND TOP DIAMETER ARE ASSUMED TO BE MEASURED OUTSIDE
!  BARK--IF DIB IS DESIRED, ALLOW FOR DOUBLE BARK THICKNESS IN
!  SPECIFICATIONS.
!
!  ALL PARAMETERS IN THE KEMP EQUATION FORM CAN BE REPLACED BY THE
!  USER WITH THE BFVOLEQU KEYWORD.  IF A USER ENTERS THEIR OWN EQUATION
!  IT IS ASSUMED TO APPLY FROM THE STUMP TO THE MERCH TOP.
!
!  VOLUME LOSS DUE TO TOP DAMAGE (TKILL=.TRUE.) IS ESTIMATED WITH A
!  BEHRE HYPERBOLA TAPER MODEL, WITH PARAMETERS ESTIMATED FROM TOTAL
!  CUBIC FOOT VOLUME, HEIGHT AND DIAMETER.
!----------
!
LOGICAL LCONE,TKILL,BTKFLG
REAL VMAX,BARK,BBFV,D2H,H,D,TSIZE
INTEGER ITHT,ISPC
REAL RDANUW
LOGICAL LDANUW
INTEGER IDANUW
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
RDANUW = BARK
RDANUW = VMAX
IDANUW = ITHT
LDANUW = LCONE
LDANUW = TKILL
!
!----------
!  INITIALIZE VOLUME ESTIMATE.
!----------
BBFV=0.0
!----------
!  TRANSFER TO STATEMENT 300 TO PROCESS WESTERN SIERRA LOG RULES.
!  (METHB=5)
!----------
IF(METHB(ISPC).EQ.5) GO TO 300
!----------
!  TRANSFER TO STATEMENT 100 TO PROCESS REGION 6 LOG RULES.
!  (METHB= 3 OR 4).
!----------
IF(METHB(ISPC).EQ.3 .OR. METHB(ISPC).EQ.4) GO TO 100
!----------
!  ASSIGN TRANSITION SIZE.
!----------
TSIZE=D
IF(IBTRAN(ISPC).GT.0) TSIZE=D2H
!
IF(TSIZE.GE.BTRAN(ISPC)) GO TO 20
!
BBFV = BFVEQS(1,ISPC) &
        + BFVEQS(2,ISPC)*D &
        + BFVEQS(3,ISPC)*D*H &
        + BFVEQS(4,ISPC)*D2H &
        + BFVEQS(5,ISPC)*D**BFVEQS(6,ISPC)*H**BFVEQS(7,ISPC)
GO TO 30
20 CONTINUE
BBFV = BFVEQL(1,ISPC) &
        + BFVEQL(2,ISPC)*D &
        + BFVEQL(3,ISPC)*D*H &
        + BFVEQL(4,ISPC)*D2H &
        + BFVEQL(5,ISPC)*D**BFVEQL(6,ISPC)*H**BFVEQL(7,ISPC)
!----------
!  THE FOLLOWING PIECE OF FOOLISHNESS (J.E.B.) IS REQUIRED
!  BY NATIONAL FOREST SCALING AND CRUISING RULES.  BE CAREFUL IF
!  YOU BUY A CORRAL POLE SALE BASED ON A SCRIBNER CRUISE VOLUME.
!----------
30 CONTINUE
IF(BBFV.LT.10.0 .AND. BBFV.NE.0.) BBFV=10.0
!----------
!  SET TOPKILL FLAG AND RETURN.
!----------
BTKFLG = .TRUE.
RETURN
!
!
!
!----------
!  METHB = 3 OR 4:  VOLUME COMPUTED USING ONE OF THE REGION 6 LOG
!  RULES.  MINIMUM DBH FOR LOG RULE IS 4 INCHES.
!  NOT APPLICABLE TO EASTERN VARIANTS, SO RETURN 0 VOLUME
!----------
100 CONTINUE
RETURN
!----------
!  WESTERN SIERRA LOG RULES.
!  NOT APPLICABLE TO EASTERN VARIANTS, SO RETURN 0 VOLUME
!----------
300 CONTINUE
RETURN
!
END
