SUBROUTINE CFVOL(ISPC,D,HZ,D2H,VN,VM,VMAX,TKILL,LCONE,BARK,ITHT, &
                    CTKFLG)
IMPLICIT NONE
!----------
! LS $Id$
!----------
! THIS ROUTINE CALCULATES CUBIC FOOT VOLUME USING A
! USER DEFINED EQUATION.
!----------
!OMMONS
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'COEFFS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'OUTCOM.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'VOLSTD.f90'
!
!
!OMMONS
!----------
!  DIMENSION STATEMENT FOR INTERNAL ARRAYS.
!----------
LOGICAL TKILL,LCONE,CTKFLG,BTKFLG,DEBUG,DONE
INTEGER ITHT,ISPC,IHT1,IHT2
REAL BARK,VMAX,VM,VN,D2H,HZ,D,H,TSIZE,TOPDOB,BFTDOB,SINDX,HM1
REAL HM2,TOTCU,SAWCU
INTEGER IDANUW
LOGICAL LDANUW
!----------
!  DEFINE VARIABLES
!    DONE = LOGICAL OPERATOR TO SIGNIFY ALL VOLUMES HAVE BEEN COMPUTED
!     HM1 = MERCH HEIGHT TO SAWLOG TOP
!     HM2 = MERCH HEIGHT TO PULPWOOD TOP
!    IHT1 = # OF SAWLOG 8' BOLTS
!    IHT2 = # OF PULPWOOD 8' BOLTS
!   TOTCU = CUBIC FOOT VOLUME TO THE PULPWOOD TOP
!   SAWCU = CUBIC FOOT VOLUME TO THE SAWLOG TOP
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
IDANUW = ITHT
LDANUW = LCONE
LDANUW = TKILL
!
!----------
!  CHECK FOR DEBUG
!----------
CALL DBCHK(DEBUG,'CFVOL',5,ICYC)
IF(DEBUG)WRITE(JOSTND,*)'IN CFVOL, ICYC= ',ICYC
!----------
! FIRST COMPUTE VMAX BASED ON TOTAL HEIGHT
!----------
H=HZ
TSIZE=D
IF(ICTRAN(ISPC).GT.0) TSIZE=D2H
IF(TSIZE.LT.CTRAN(ISPC)) THEN
  VMAX = CFVEQS(1,ISPC) &
       +CFVEQS(2,ISPC)*D &
       +CFVEQS(3,ISPC)*D*H &
       +CFVEQS(4,ISPC)*D*D*H &
       +CFVEQS(5,ISPC)*D**CFVEQS(6,ISPC)*H**CFVEQS(7,ISPC)
  ELSE
    VMAX = CFVEQL(1,ISPC) &
       +CFVEQL(2,ISPC)*D &
       +CFVEQL(3,ISPC)*D*H &
       +CFVEQL(4,ISPC)*D*D*H &
       +CFVEQL(5,ISPC)*D**CFVEQL(6,ISPC)*H**CFVEQL(7,ISPC)
  ENDIF
  IF(VMAX .LT. 0.) VMAX = 0.
!----------
!  METHC = 1: VOLUME COMPUTED USING REGRESSION MODEL WITH EITHER DEFAULT
!  (SEE **CUBRDS**) OR USER SUPPLIED PARAMETERS (SEE CFVOLEQ KEYWORD).
!
!  **NBOLT** IS CALLED TO COMPUTE NUMBER OF 8' BOLTS TO SPECIFIED PULPWOOD
!  AND SAWLOG TOPS.  THE NUMBER OF BOLTS IS THEN MULTIPLIED BY 8.333 TO
!  GET THE MERCHANTABLE BOLE HEIGHT FOR THIS EQUATION.
!----------
DONE=.FALSE.
TOPDOB=TOPD(ISPC)/BARK
BFTDOB=BFTOPD(ISPC)/BARK
SINDX=SITEAR(ISPC)
!
IF(DEBUG)WRITE(JOSTND,*) &
   ' TOPDOB= ',TOPDOB,' BFTDOB=',BFTDOB,' BRATIO=',BARK
!----------
!  CALL NBOLT TO COMPUTE THE TOTAL NUMBER OF 8' BOLTS TO A SPECIFIED
!  PULPWOOD AND SAWTIMBER TOP DIAMETER.
!----------
CALL NBOLT(ISPC,H,D,DBHMIN,BFMIND,SINDX,TOPDOB,BFTDOB, &
              JOSTND,DEBUG,IHT1,IHT2)
HM1=FLOAT(IHT1)*8.333333
HM2=FLOAT(IHT2)*8.333333
!----------
!  COMPUTE TOTAL MERCH CUBIC AND SAWLOG CUBIC VOLUMES
!
!  CASES 1-3 ASSUME THE MINIMUM SAWTIMBER DBH IS GREATER THAN THE
!  MINIMUM PULPWOOD DBH
!----------
IF(DEBUG)WRITE(JOSTND,*)' D,DBHMIN,BFMIND,IHT1,IHT2,HM1,HM2= ', &
   D,DBHMIN(ISPC),BFMIND(ISPC),IHT1,IHT2,HM1,HM2
!
IF(D.LT.DBHMIN(ISPC) .OR. IHT2.LE.0)THEN
!
!  CASE 1: TREE DOES NOT MEET PULPWOOD SPECS
!
  TOTCU=0.
!----------
!  TREE DBH IS GREATER THAN PULPWOOD MIN DBH
!  FIRST CASE ASSUMES DEFAULT SAWTIMBER DBH IS GREATER THAN DEFAULT PULPWOOD
!----------
ELSEIF(D.LT.BFMIND(ISPC).OR. IHT1.LE.0)THEN
!
!  CASE 2: TREE ONLY HAS PULPWOOD
!
  H=HM2
  TSIZE=D
  IF(ICTRAN(ISPC).GT.0) TSIZE=D2H
  IF(TSIZE.LT.CTRAN(ISPC)) THEN
    TOTCU=CFVEQS(1,ISPC) &
       +CFVEQS(2,ISPC)*D &
       +CFVEQS(3,ISPC)*D*H &
       +CFVEQS(4,ISPC)*D*D*H &
       +CFVEQS(5,ISPC)*D**CFVEQS(6,ISPC)*H**CFVEQS(7,ISPC)
  ELSE
    TOTCU=CFVEQL(1,ISPC) &
       +CFVEQL(2,ISPC)*D &
       +CFVEQL(3,ISPC)*D*H &
       +CFVEQL(4,ISPC)*D*D*H &
       +CFVEQL(5,ISPC)*D**CFVEQL(6,ISPC)*H**CFVEQL(7,ISPC)
  ENDIF
  IF(TOTCU .LT. 0.) TOTCU = 0.
!
  SAWCU=0.0
  DONE=.TRUE.
ELSE
!
!  CASE 3: TREE HAS PULPWOOD AND SAWTIMBER
!
  H=HM2
  TSIZE=D
  IF(ICTRAN(ISPC).GT.0) TSIZE=D2H
  IF(TSIZE.LT.CTRAN(ISPC)) THEN
    TOTCU=CFVEQS(1,ISPC) &
       +CFVEQS(2,ISPC)*D &
       +CFVEQS(3,ISPC)*D*H &
       +CFVEQS(4,ISPC)*D*D*H &
       +CFVEQS(5,ISPC)*D**CFVEQS(6,ISPC)*H**CFVEQS(7,ISPC)
  ELSE
    TOTCU=CFVEQL(1,ISPC) &
       +CFVEQL(2,ISPC)*D &
       +CFVEQL(3,ISPC)*D*H &
       +CFVEQL(4,ISPC)*D*D*H &
       +CFVEQL(5,ISPC)*D**CFVEQL(6,ISPC)*H**CFVEQL(7,ISPC)
  ENDIF
  IF(TOTCU .LT. 0.) TOTCU = 0.
!
  H=HM1
  TSIZE=D
  IF(ICTRAN(ISPC).GT.0) TSIZE=D2H
  IF(TSIZE.LT.CTRAN(ISPC)) THEN
    SAWCU=CFVEQS(1,ISPC) &
       +CFVEQS(2,ISPC)*D &
       +CFVEQS(3,ISPC)*D*H &
       +CFVEQS(4,ISPC)*D*D*H &
       +CFVEQS(5,ISPC)*D**CFVEQS(6,ISPC)*H**CFVEQS(7,ISPC)
  ELSE
    SAWCU=CFVEQL(1,ISPC) &
       +CFVEQL(2,ISPC)*D &
       +CFVEQL(3,ISPC)*D*H &
       +CFVEQL(4,ISPC)*D*D*H &
       +CFVEQL(5,ISPC)*D**CFVEQL(6,ISPC)*H**CFVEQL(7,ISPC)
  ENDIF
  IF(SAWCU .LT. 0.) SAWCU = 0.
  DONE=.TRUE.
ENDIF
IF (DONE)GOTO 50
!
!--STRANGE CASE IF SAWTIMBER MIN DBH IS LESS THAN PULPWOOD MIN DBH
!
IF(D .LT. BFMIND(ISPC))THEN
!
!  CASE 4: STRANGE CASE SPECS MET AND TREE DOES NOT MEET SAWTIMBER SPECS
!
  SAWCU=0.0
ELSE
!
!  CASE 5: STRANGE CASE SPECS MET AND TREE ONLY HAS SAWTIMBER
!
  H=HM1
  TSIZE=D
  IF(ICTRAN(ISPC).GT.0) TSIZE=D2H
  IF(TSIZE.LT.CTRAN(ISPC)) THEN
    SAWCU=CFVEQS(1,ISPC) &
       +CFVEQS(2,ISPC)*D &
       +CFVEQS(3,ISPC)*D*H &
       +CFVEQS(4,ISPC)*D*D*H &
       +CFVEQS(5,ISPC)*D**CFVEQS(6,ISPC)*H**CFVEQS(7,ISPC)
  ELSE
    SAWCU=CFVEQL(1,ISPC) &
       +CFVEQL(2,ISPC)*D &
       +CFVEQL(3,ISPC)*D*H &
       +CFVEQL(4,ISPC)*D*D*H &
       +CFVEQL(5,ISPC)*D**CFVEQL(6,ISPC)*H**CFVEQL(7,ISPC)
  ENDIF
  IF(SAWCU .LT. 0.) SAWCU = 0.
 ENDIF
!----------
!  SET RETURN VALUES.
!----------
50 CONTINUE
IF(DEBUG)WRITE(JOSTND,*)' TOTCU=',TOTCU,' SAWCU=',SAWCU
VN=TOTCU
VM=SAWCU
CTKFLG = .TRUE.
BTKFLG = .TRUE.
IF(VN.LE.0.)THEN
  VN=0.
  CTKFLG = .FALSE.
ENDIF
IF(VM.LE.0.)THEN
  VM=0.
  BTKFLG = .FALSE.
ENDIF
!
IF(DEBUG)WRITE(JOSTND,*)' RETURNING VN,VMAX,VM,CTKFLG,BTKFLG= ', &
    VN,VMAX,VM,CTKFLG,BTKFLG
!
RETURN
!
END
