SUBROUTINE CUTSTK
IMPLICIT NONE
!----------
! LS $Id$
!----------
!  THIS SUBROUTINE CONTAINS ENTRY POINTS FOR CALCULATING STOCKING
!  LEVELS FOR VARIOUS THINNING OPTIONS.
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
!OMMONS
!----------
LOGICAL LINCL
REAL BASP(6),A1(6),A2(6),A3(6)
INTEGER JJSP(MAXSP)
REAL TPRED(6)
INTEGER I,IISPG,JPNUM,JSPCUT,JTYP,IC,IGRP,IULIM,IG
REAL STTPA,HU,HL,CSTOCK,D,H,TPA,FSTOCK,TOTBA,DU,DL
DATA A1/-.1433,-.3430,-.5453,-.0935,-.2996,-.1869/
DATA A2/7.1389,10.7172,16.222,5.6206,14.5479,10.5087/
DATA A3/34.3018,43.0417,46.0012,80.2369,75.4377,103.2119/
!----------
!  PUT SPECIES IN ONE OF 6 STOCKING CATEGORIES
!
!  SPECIES GROUP 1 - NORTHERN HARDWOODS
!  SPECIES GROUP 2 - UPLAND AND RED OAK
!  SPECIES GROUP 3 - ASPEN AND PAPER BIRCH
!  SPECIES GROUP 4 - JACK PINE
!  SPECIES GROUP 5 - WHITE AND BLACK SPRUCE
!  SPECIES GROUP 6 - RED AND WHITE PINE
!----------
DATA JJSP/2*4,3*6,6*5,1,2*6,2*1,3,12*1,7*2,3*1,4*3,5*2,20*3/
!
!----------
!  ENTRY AUTSTK CALCULATES NORMAL STOCKING FOR AUTOMATIC THINS.
!
!  VARIABLE DEFINITIONS:
!  A1,A2,A3  COEFFICIENTS TO PREDICT TPA BY STOCKING CATEGORY
!  TPRED     TREES PER ACRE FOR THE STAND AT 100% STOCKING-
!            BY STOCKING CATEGORY.
!  STTPA     NUMBER OF TREES PER ACRE PREDICTED FOR THE NEW STAND AT
!            100% STOCKING--INCLUDES ALL SIX STOCKING CATEGORIES
!-----------
ENTRY AUTSTK (FSTOCK)
DO 10 I=1,6
BASP(I) = 0.0
TPRED(I) = 0.0
10 CONTINUE
TOTBA = 0.0
!----------
!  DETERMINE TOTAL NUMBER OF TREES PER ACRE IN EACH SPECIES GROUP
!----------
DO 20 I=1,ITRN
IISPG = JJSP(ISP(I))
BASP(IISPG) = BASP(IISPG) + .0054542*DBH(I)*DBH(I)*PROB(I)
20 CONTINUE
!----------
!  RECALCULATE STOCKING PERCENT FOR LIVE TREES ONLY (ISTATUS = 1).
!----------
DO 30 I=1,6
IF(BASP(I) .EQ. 0.0) THEN
  TPRED(I)= 1.0
  GO TO 30
ENDIF
TOTBA=BASP(I)+TOTBA
!----------
!  CALCULATE PREDICTED TREES PER ACRE FOR EACH SPECIES GROUP
!----------
TPRED(I) =(A1(I)*RMSQD*RMSQD+A2(I)*RMSQD+A3(I))/ &
                   (.0054542*RMSQD*RMSQD)
30 CONTINUE
!----------
!  WEIGHT PREDICTED TPA FOR EACH STOCKING CATEGORY BY PERCENT BA IN
!  EACH STOCKING CATEGORY
!----------
STTPA = (BASP(1)*TPRED(1)+BASP(2)*TPRED(2)+BASP(3)*TPRED(3) &
              +BASP(4)*TPRED(4)+BASP(5)*TPRED(5)+ &
               BASP(6)*TPRED(6))/TOTBA
FSTOCK = STTPA
RETURN
!
!-----------
!  ENTRY CLSSTK COMPUTES BA OR TPA STOCKING IN A SPECIFIED
!  DBH/HT/SPECIES CLASS.
!
!  CSTOCK = CLASS STOCKING
!  JTYP   = 1 IF STOCKING IS IN TPA,  2 IF STOCKING IS IN BA
!  JSPCUT = SPECIES WHICH WILL BE CUT
!  LINCL  = LOGICAL VARIABLE USED TO INCLUDE SPECIES OR NOT.
!  DL,DU  = LOWER AND UPPER DIAMETER LIMITS RESPECTIVELY (GE,LT)
!  HL,HU  = LOWER AND UPPER HEIGHT LIMITS RESPECTIVELY (GE,LT)
!  JPNUM = POINT NUMBER (IN FVS SEQUENCE FORMAT), 0 = ALL POINTS
!----------
ENTRY CLSSTK (CSTOCK,JTYP,JSPCUT,DL,DU,HL,HU,JPNUM)
CSTOCK=0.0
DO 100 IC=1,ITRN
IF(JPNUM.GT.0 .AND. ITRE(IC).NE.JPNUM)GO TO 100
!
LINCL = .FALSE.
IF((JSPCUT.EQ.0 .OR. JSPCUT.EQ.ISP(IC)).AND. &
       .NOT.LEAVESP(ISP(IC)))THEN
  LINCL = .TRUE.
ELSEIF(JSPCUT.LT.0)THEN
  IGRP = -JSPCUT
  IULIM = ISPGRP(IGRP,1)+1
  DO 60 IG=2,IULIM
  IF((ISP(IC) .EQ. ISPGRP(IGRP,IG)).AND..NOT.LEAVESP(ISP(IC)))THEN
    LINCL = .TRUE.
    GO TO 61
  ENDIF
60   CONTINUE
ENDIF
61 CONTINUE
!
IF (LINCL) THEN
  D=DBH(IC)
  H=HT(IC)
  TPA=WK4(IC)
  IF(JPNUM.GT.0)TPA=TPA*(PI-FLOAT(NONSTK))
  IF(D.LT.DL .OR. D.GE.DU) GO TO 100
  IF(H.LT.HL .OR. H.GE.HU) GO TO 100
  IF(JTYP.EQ.1) THEN
    CSTOCK=CSTOCK + TPA
  ELSE
    CSTOCK=CSTOCK + TPA*(D*D*0.005454154)
  ENDIF
ENDIF
100 CONTINUE
RETURN
!
END
