SUBROUTINE FMCFMD (IYR, FMD)
IMPLICIT NONE
!----------
! FIRE-EM $Id$
!----------
!     SINGLE-STAND VERSION
!     CALLED FROM: FMBURN
!  PURPOSE:
!     THIS SUBROUTINE RETURNS TWO TYPES OF INFORMATION: THE FUEL MODEL
!     THAT WOULD BE USED IF THE STATIC FUEL MODEL OPTION IS SELECTED
!     (STORED AS IFMD(1), WITH A WEIGTH OF FWT(1)=1.0 AND THE CLOSEST
!     THE CLOSEST FUEL MODELS (UP TO 4) AND THEIR WEIGHTINGS FOR USE
!     BY THE DYNAMIC FUEL MODEL
!----------
!
!  CALL LIST DEFINITIONS:
!     FMD:     FUEL MODEL NUMBER
!
!  COMMON BLOCK VARIABLES AND PARAMETERS:
!     SMALL:   SMALL FUELS FROM DYNAMIC FUEL MODEL
!     LARGE:   LARGE FUELS FROM DYNAMIC FUEL MODEL
!
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'FMPARM.f90'
!
!
INCLUDE 'FMFCOM.f90'
!
!
INCLUDE 'FMCOM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
!OMMONS
!----------
!  VARIABLE DECLARATIONS
!----------
INTEGER ICLSS
PARAMETER(ICLSS = 14)
!
INTEGER  FMD
INTEGER  M1, M2
INTEGER  IPTR(ICLSS), ITYP(ICLSS)
REAL     WT1(4), X(2), Y(2), ALGSLP, AFWT
REAL     XPTS(ICLSS,2)
REAL     EQWT(ICLSS)
LOGICAL  DEBUG
INTEGER  IYR,I,J
!----------
!     FIXED VALUES FOR INTERPOLATION FUNCTION
!----------
DATA     Y / 0.0, 1.0 /
!----------
!     THESE ARE THE INTEGER TAGS ASSOCIATED WITH EACH FIRE MODEL
!     CLASS. THEY ARE RETURNED WITH THE WEIGHT
!----------
DATA IPTR / 1,2,3,4,5,6,7,8,9,10,11,12,13,14 /
!----------
!     THESE ARE 0 FOR REGULAR LINES, -1 FOR HORIZONTAL AND 1 FOR
!     VERTICAL LINES. IF ANY OF THE LINES DEFINED BY XPTS() ARE OF
!     AN UNUSUAL VARIETY, THIS MUST BE ENTERED HERE SO THAT
!     SPECIAL LOGIC CAN BE INVOKED.  IN THIS CASE, ALL THE LINE
!     SEGMENTS HAVE A |SLOPE| THAT IS > 0 AND LESS THAN INIF.
!----------
DATA ITYP / ICLSS * 0 /
!----------
!     XPTS: FIRST COLUMN ARE THE SMALL FUEL VALUES FOR EACH FIRE MODEL
!     WHEN LARGE FUEL= 0 (I.E. THE X-INTERCEPT OF THE LINE). SECOND
!     COLUMN CONTAINS THE LARGE FUEL VALUE FOR EACH FIRE MODEL WHEN
!     SMALL FUEL=0 (I.E. THE Y-INTERCEPT OF THE LINE).
!----------
DATA ((XPTS(I,J), J=1,2), I=1,ICLSS) / &
      5., 15., &  ! FMD   1
      5., 15., &  ! FMD   2
      5., 15., &  ! FMD   3
      5., 15., &  ! FMD   4
      5., 15., &  ! FMD   5
      5., 15., &  ! FMD   6
      5., 15., &  ! FMD   7
      5., 15., &  ! FMD   8
      5., 15., &  ! FMD   9
     15., 30., &  ! FMD  10 ! shares with 11
     15., 30., &  ! FMD  11
     30., 60., &  ! FMD  12 ! shares with 14
     45.,100., &  ! FMD  13
     30., 60./   ! FMD  14
!----------
!     INITIALLY SET ALL MODELS OFF; NO TWO CANDIDATE MODELS ARE COLINEAR (EXCEPT FOR
!     FM1 AND FM2) AND COLINEARITY WEIGHTS ARE ZERO. IF TWO CANDIDATE MODELS ARE
!     COLINEAR, THE WEIGHTS MUST BE SET, AND MUST SUM TO 1, WRT EACH OTHER
!----------
DO I = 1,ICLSS
  EQWT(I) = 0.0
ENDDO
!----------
!     BEGIN ROUTINE
!----------
CALL DBCHK (DEBUG,'FMCFMD',6,ICYC)

IF (DEBUG) WRITE(JOSTND,1) ICYC,IYR,LUSRFM
1 FORMAT(' FMCFMD CYCLE= ',I2,' IYR=',I5,' LUSRFM=',L5)
!----------
!     IF USER-SPECIFIED FM DEFINITIONS, THEN WE ARE DONE.
!----------
IF (LUSRFM) RETURN
!
IF (DEBUG) WRITE(JOSTND,7) ICYC,IYR,HARVYR,LDYNFM,PERCOV,FMKOD, &
              SMALL,LARGE
7 FORMAT(' FMCFMD CYCLE= ',I2,' IYR=',I5,' HARVYR=',I5, &
          ' LDYNFM=',L2,' PERCOV=',F7.2,' FMKOD=',I4, &
          ' SMALL=',F7.2,' LARGE=',F7.2)
!----------
!     FIRST, WE NEED TO SEE WHICH FUEL MODELS ARE ACTIVE AND TO IDENTIFY THE
!     ONE THAT WOULD BE USED IN THE STATIC SITUATION (FOR OUTPUT PURPOSES).
!     THE AMOUNT OF SMALL AND LARGE FUEL PRESENT CAN MODIFY THE CHOICE OF
!     MODEL AS CAN THE HABITAT TYPE OR WHEN THE LAST HARVEST ACTIVITY WAS
!     DONE. FROM FAX FROM ELIZABETH REINHARDT
!----------
DO I = 1,4
  WT1(I) = 0.0
ENDDO
!
CALL EMMD(M1,M2)  ! GET FIRE MODELS **FMCBA**
!
X(1) = 30.0
X(2) = 50.0
J = 2
!
WT1(J)   = ALGSLP(PERCOV,X,Y,2)
WT1(J-1) = 1.0 - WT1(J)
!
EQWT(M1) = EQWT(M1) + WT1(1)
EQWT(M2) = EQWT(M2) + WT1(2)
!----------
!     END OF DETAILED LOW FUEL MODEL SELECTION
!
!     DURING THE 5 YEARS AFTER AN ENTRY, AND ASSUMING THAT SMALL+LARGE
!     ACTIVIVITY FUELS HAVE JUMPED BY 10%, THEN MODEL 11 AND 14 ARE
!     CANDIDATE MODELS, SHARING WITH 10 AND 12 RESPECTIVELY. THE
!     WEIGHT OF THE SHARED RELATIONSHIP DECLINES FROM PURE 11 INITIALLY,
!     TO PURE 10 AFTER THE PERIOD EXPIRES. SIMILARLY, COMPUTE WEIGHT FOR
!     MODEL 14 ACTIVITY FUELS, SHARED WITH CURRENT MODEL 12. THE
!     RELATIONSHIP CHANGES IN THE SAME WAS AS THE 10/11 FUELS.
!----------
AFWT = MAX(0.0, 1.0 - (IYR - HARVYR) / 5.0)
IF (SLCHNG .GE. SLCRIT .OR. LATFUEL) THEN
  LATFUEL  = .TRUE.
  EQWT(11) = AFWT
  EQWT(14) = AFWT
  IF (AFWT .LE. 0.0) LATFUEL = .FALSE.
ENDIF
IF (.NOT. LATFUEL) AFWT = 0.0
!----------
!     MODELS 10,12,13 ARE ALWAYS CANDIDATE MODELS FOR NATURAL FUELS
!     OTHER MODELS ARE ALSO CANDIDATES, DEPENDING ON COVER TYPE, ETC
!----------
EQWT(10) = 1.0 - AFWT
EQWT(12) = 1.0 - AFWT
EQWT(13) = 1.0
!----------
!     CALL FMDYN TO RESOLVE WEIGHTS, SORT THE WEIGHTED FUEL MODELS
!     FROM THE HIGHEST TO LOWEST, SET FMD (USING THE HIGHEST WEIGHT)
!----------
CALL FMDYN(SMALL,LARGE,ITYP,XPTS,EQWT,IPTR,ICLSS,LDYNFM,FMD)
!
IF (DEBUG) WRITE (JOSTND,8) FMD
8 FORMAT (' FMCFMD, FMD=',I4)
!
RETURN
END
