SUBROUTINE BFVOL(ISPC,D,H,D2H,BBFV,TKILL,LCONE,BARK,VMAX,ITHT, &
                    BTKFLG)
IMPLICIT NONE
!----------
! CI $Id$
!----------
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'COEFFS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'OUTCOM.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'VOLSTD.f90'
!
!
!OMMONS
!----------
!  ************** BOARD FOOT MERCHANTABILITY SPECIFICATIONS ********
!
!  BFVOL CALCULATES BOARD FOOT VOLUME OF ANY TREE LARGER THAN A MINIMUM
!  DBH SPECIFIED BY THE USER.  MINIMUM DBH CAN VARY BY SPECIES,
!  BUT CANNOT BE LESS THAN 2 INCHES.  MINIMUM MERCHANTABLE DBH IS
!  SET WITH THE BFVOLUME KEYWORD.  FOR METHB = 1-4 MERCHANTABLE
!  TOP DIAMETER CAN BE SET TO ANY VALUE BETWEEN 2 IN. AND MINIMUM DBH.
!  MINIMUM DBH AND TOP DIAMETER ARE ASSUMED TO BE MEASURED OUTSIDE
!  BARK--IF DIB IS DESIRED, ALLOW FOR DOUBLE BARK THICKNESS IN
!  SPECIFICATIONS.
!
!  VOLUME CAN BE COMPUTED BY FORMULA (METHB=1 OR 2) OR BY APPLYING THE
!  REGION 6 LOG RULES (METHB=3 OR 4).
!
!  FOR METHB=1 KEMP'S EQUATIONS ARE USED.  KEMP'S EQUATIONS IMPLY
!  SPECIFIC MERCHANTABILITY STANDARDS WHICH ARE:
!  STANDARDS (9" MINIMUM DBH, 8" MINIMUM TOP DIAMETER, AND 1' STUMP).
!  VOLUME ABOVE THE 8" TOP IS IGNORED.
!
!  ALL PARAMETERS IN THE KEMP EQUATION FORM CAN BE REPLACED BY THE
!  USER WITH THE BFVOLEQU KEYWORD.  IF A USER ENTERS THEIR OWN EQUATION
!  IT IS ASSUMED TO APPLY FROM THE STUMP TO THE MERCH TOP.
!
!  DEFAULT COEFFICIENTS FOR THE KEMP EQUATIONS ARE LOADED IN BLKDAT.
!  VARIANTS OTHER THAN NORTH IDAHO MAY HAVE DEFAULT COEFFICIENTS FOR
!  THE KEMP EQUATION FORM, BUT THEY AREN'T KEMP'S EQUATIONS. IN THIS
!  CASE THE KEMP MERCHANTABILITY STANDARDS STATED ABOVE DO NOT APPLY.
!
!  VOLUME LOSS DUE TO TOP DAMAGE (TKILL=.TRUE.) IS ESTIMATED WITH A
!  BEHRE HYPERBOLA TAPER MODEL, WITH PARAMETERS ESTIMATED FROM TOTAL
!  CUBIC FOOT VOLUME, HEIGHT AND DIAMETER.
!
!  FOR METHB=3 OR 4, BOTH TOTAL VOLUME AND VOLUME LOSS DUE TO TOP
!  DAMAGE ARE COMPUTED WITH THE LOG RULE.
!----------
LOGICAL LOGOK,LCONE,TKILL,BTKFLG
INTEGER ITHT,ISPC,ID,ITD,IVTD,NUMLOG,I,INC,LAST
REAL SMDIA(20),GLOGLN(20)
REAL COFBVS(MAXSP),HDRATM(100),D2HBRK(MAXSP)
REAL VMAX,BARK,BBFV,D2H,H,D,TSIZE,VT,HDRATA,DTOPK,HTRUNC,TD,DIB
REAL FC,SMDOLD,TLOG,XLOG,SMD,PLEFT,D1SQ,FACTOR
REAL RDANUW
LOGICAL LDANUW
!----------
!     SPECIES LIST FOR CENTRAL IDAHO VARIANT.
!
!     1 = WESTERN WHITE PINE (WP)          PINUS MONTICOLA
!     2 = WESTERN LARCH (WL)               LARIX OCCIDENTALIS
!     3 = DOUGLAS-FIR (DF)                 PSEUDOTSUGA MENZIESII
!     4 = GRAND FIR (GF)                   ABIES GRANDIS
!     5 = WESTERN HEMLOCK (WH)             TSUGA HETEROPHYLLA
!     6 = WESTERN REDCEDAR (RC)            THUJA PLICATA
!     7 = LODGEPOLE PINE (LP)              PINUS CONTORTA
!     8 = ENGLEMANN SPRUCE (ES)            PICEA ENGELMANNII
!     9 = SUBALPINE FIR (AF)               ABIES LASIOCARPA
!    10 = PONDEROSA PINE (PP)              PINUS PONDEROSA
!    11 = WHITEBARK PINE (WB)              PINUS ALBICAULIS
!    12 = PACIFIC YEW (PY)                 TAXUS BREVIFOLIA
!    13 = QUAKING ASPEN (AS)               POPULUS TREMULOIDES
!    14 = WESTERN JUNIPER (WJ)             JUNIPERUS OCCIDENTALIS
!    15 = CURLLEAF MOUNTAIN-MAHOGANY (MC)  CERCOCARPUS LEDIFOLIUS
!    16 = LIMBER PINE (LM)                 PINUS FLEXILIS
!    17 = BLACK COTTONWOOD (CW)            POPULUS BALSAMIFERA VAR. TRICHOCARPA
!    18 = OTHER SOFTWOODS (OS)
!    19 = OTHER HARDWOODS (OH)
!
!  SURROGATE EQUATION ASSIGNMENT:
!
!  FROM THE IE VARIANT:
!      USE 17(PY) FOR 12(PY)             (IE17 IS REALLY TT2=LM)
!      USE 18(AS) FOR 13(AS)             (IE18 IS REALLY UT6=AS)
!      USE 13(LM) FOR 11(WB) AND 16(LM)  (IE13 IS REALLY TT2=LM)
!      USE 19(CO) FOR 17(CW) AND 19(OH)  (IE19 IS REALLY CR38=OH)
!
!  FROM THE UT VARIANT:
!      USE 12(WJ) FOR 14(WJ)
!      USE 20(MC) FOR 15(MC)             (UT20 = SO30=MC, WHICH IS
!                                                  REALLY WC39=OT)
!----------
!  DATA STATEMENTS
!----------
DATA D2HBRK/ &
     16917.1, 19231.8, 15763.5, 10016.7, 14883.9, &
     29922.0,  4567.8,  6024.9, 19425.9, 14034.0, &
     14883.9, 14883.9, 14883.9, 14883.9, 14883.9, &
     14883.9, 14883.9, 14883.9, 14883.9/
!
DATA COFBVS/ &
     0.01031, 0.008423, 0.008423, 0.009523, 0.009523, &
    0.008421,  0.01031, 0.009523, 0.009523, 0.008423, &
    0.009523, 0.009523, 0.009523, 0.009523, 0.009523, &
    0.009523, 0.009523, 0.009523, 0.009523/
!
DATA HDRATM/ &
     10.0, 10.0, 9.0, 8.0, 7.8, 7.65, 7.5, 7.25, 7.0, 6.75, &
      6.5, 6.25, 18*6.0, 10*5.5, 10*5.0, 10*4.5, 10*4.0, &
     10*3.5, 10*3.0, 10*2.5/
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
RDANUW = VMAX
LDANUW = LCONE
!
!----------
!  INITIALIZE VOLUME ESTIMATE.
!----------
BBFV=0.0
!----------
!  TRANSFER TO STATEMENT 300 TO PROCESS WESTERN SIERRA LOG RULES.
!  (METHB=5)
!----------
IF(METHB(ISPC).EQ.5) GO TO 300
!----------
!  TRANSFER TO STATEMENT 100 TO PROCESS REGION 6 LOG RULES.
!  (METHB= 3 OR 4).
!----------
IF(METHB(ISPC).EQ.3 .OR. METHB(ISPC).EQ.4) GO TO 100
!----------
!  ASSIGN TRANSITION SIZE.
!----------
TSIZE=D
IF(IBTRAN(ISPC).GT.0) TSIZE=D2H
!
!
!
!--------------------------------------------------
!  BYPASS ALLEN EQUATIONS FOR METHB = 2 OR 7 (USER DEFINED).
!
VT=0.0
IF(METHB(ISPC).EQ.2 .OR. METHB(ISPC).EQ.7) GO TO 15
HDRATA=H/D
ID=INT(D-0.5)
IF(ID.GT.100) ID = 100
ITD=INT(BFTOPD(ISPC)-0.5)
IF(ITD.GT.100) ITD = 100
IF(D2H.GT.D2HBRK(ISPC)) GO TO 10
!
!  D2H LESS THAN D2H BREAKPOINT: COMPUTE TOP AND STEM VOLUME WITH
!  ALLEN-ADAMS-PRAUSA EQUATIONS.
!
VT=-COFBVS(ISPC)*(BFTOPD(ISPC)**3*HDRATM(ITD)-80.0)* &
       SQRT(HDRATA/HDRATM(ID))- &
       (BFTOPD(ISPC)**2-4.0)*0.12153
BBFV=COFBVS(ISPC)*D2H+VT
GO TO 30
!
!  D2H GREATER THAN D2H BREAKPOINT:  COMPUTE TOP VOLUME WITH ALLEN-
!  ADAMS-PRAUSA EQUATIONS AND STEM VOLUME WITH KEMP EQUATIONS.
!
10 DTOPK=0.4*D
IF(DTOPK.LT.4.0) DTOPK=4.0
IF(DTOPK.GT.8.0) DTOPK=8.0
IVTD=INT(DTOPK-0.5)
VT=COFBVS(ISPC)*SQRT(HDRATA/HDRATM(ID))*(DTOPK**3*HDRATM(IVTD) &
      -BFTOPD(ISPC)**3*HDRATM(ITD)) - &
      (DTOPK**2-BFTOPD(ISPC)**2)*0.12153
15 CONTINUE
!----------
!
!
IF(TSIZE.GE.BTRAN(ISPC)) GO TO 20
!
BBFV = VT + BFVEQS(1,ISPC) &
        + BFVEQS(2,ISPC)*D &
        + BFVEQS(3,ISPC)*D*H &
        + BFVEQS(4,ISPC)*D2H &
        + BFVEQS(5,ISPC)*D**BFVEQS(6,ISPC)*H**BFVEQS(7,ISPC)
GO TO 30
20 CONTINUE
BBFV = VT + BFVEQL(1,ISPC) &
        + BFVEQL(2,ISPC)*D &
        + BFVEQL(3,ISPC)*D*H &
        + BFVEQL(4,ISPC)*D2H &
        + BFVEQL(5,ISPC)*D**BFVEQL(6,ISPC)*H**BFVEQL(7,ISPC)
!----------
!  THE FOLLOWING PIECE OF FOOLISHNESS (J.E.B.) IS REQUIRED
!  BY NATIONAL FOREST SCALING AND CRUISING RULES.  BE CAREFUL IF
!  YOU BUY A CORRAL POLE SALE BASED ON A SCRIBNER CRUISE VOLUME.
!----------
30 CONTINUE
IF(BBFV.LT.10.0) BBFV=10.0
!----------
!  SET TOPKILL FLAG AND RETURN.
!----------
BTKFLG = .TRUE.
RETURN
!
!
!
!----------
!  METHB = 3 OR 4:  VOLUME COMPUTED USING ONE OF THE REGION 6 LOG
!  RULES.  MINIMUM DBH FOR LOG RULE IS 4 INCHES.
!----------
100 CONTINUE
IF (D.LT. BFMIND(ISPC)) RETURN
!----------
!  LOAD HTRUNC AND H FOR TOP DAMAGED TREES.
!----------
HTRUNC=0.0
IF(TKILL) HTRUNC=ITHT/100.0
!----------
!  CALL **FORMCL** TO DETERMINE FORM CLASS
!----------
TD=BFTOPD(ISPC)*BARK
DIB=D*BARK
CALL FORMCL(ISPC,IFOR,D,FC)
!----------
!  CALL **RXDIBS** TO COMPUTE NUMBER OF 16FT LOGS AND EACH SMALL-
!  END DIB
!----------
CALL RXDIBS(D,FC,H,TD,SMDIA,GLOGLN,NUMLOG,JOSTND)
!----------
!  INITIALIZE:
!     TLOG=CUMULATIVE LENGTH OF LOGS ALREADY PROCESSED.
!     LOGOK=SET TO FALSE WHEN LOG CONTAINING BROKEN TOP IS PROCESSED.
!----------
SMDOLD=DIB
TLOG=0.0
LOGOK=.TRUE.
IF(METHB(ISPC).EQ.4) GO TO 200
!----------
!  REGION 6 EAST SIDE VOLUME (16 FOOT LOGS).  BRANCH TO STATEMENT 200
!  FOR WESTSIDE CALCULATIONS (32 FOOT LOGS).
!----------
DO 110 I = 1,NUMLOG
!----------
!  EXIT LOOP IF LAST LOG INCLUDED A BROKEN TOP.
!----------
IF(.NOT.LOGOK) GO TO 120
XLOG=GLOGLN(I)
SMD=SMDIA(I)
!----------
!  SET FLAG AND ADJUST THE TOP DIAMETER AND LOG LENGTH IF THIS LOG
!  CONTAINS A DEAD TOP.
!----------
IF(TKILL .AND. (TLOG+XLOG).GT.HTRUNC) THEN
  PLEFT=(HTRUNC-TLOG)/XLOG
  IF(PLEFT.LE.0.0) GO TO 120
  XLOG=HTRUNC-TLOG
  D1SQ=SMDOLD*SMDOLD
  SMD=SQRT(D1SQ-PLEFT*(D1SQ-SMD*SMD))
  LOGOK=.FALSE.
ENDIF
CALL SCALEF(SMD,XLOG,FACTOR,JOSTND)
TLOG=TLOG+XLOG
BBFV=BBFV+XLOG*FACTOR
SMDOLD=SMD
110 CONTINUE
120 CONTINUE
RETURN
!
!
!
!----------
!  REGION 6 WESTSIDE VOLUME.  32 FOOT LOGS; PROCESS EVERY OTHER LOG.
!----------
200 CONTINUE
I=0
INC=2
205 CONTINUE
I=I+INC
!----------
!  EXIT LOOP IF LAST LOG INCLUDED A BROKEN TOP.
!----------
IF(.NOT.LOGOK) GO TO 220
IF(INC .EQ. 2) THEN
  XLOG=GLOGLN(I)+GLOGLN(I-1)
ELSE
  XLOG=GLOGLN(I)
ENDIF
SMD=SMDIA(I)
!----------
!  SET FLAG AND ADJUST THE TOP DIAMETER AND LOG LENGTH IF THIS LOG
!  CONTAINS A DEAD TOP.
!----------
IF(TKILL .AND. (TLOG+XLOG).GT.HTRUNC) THEN
  PLEFT=(HTRUNC-TLOG)/XLOG
  IF(PLEFT.LE.0.0) GO TO 220
  XLOG=HTRUNC-TLOG
  D1SQ=SMDOLD*SMDOLD
  SMD=SQRT(D1SQ-PLEFT*(D1SQ-SMD*SMD))
  LOGOK=.FALSE.
ENDIF
CALL SCALEF(SMD,XLOG,FACTOR,JOSTND)
TLOG=TLOG+XLOG
BBFV=BBFV+XLOG*FACTOR
SMDOLD=SMD
IF(I .LT. NUMLOG) THEN
  LAST = NUMLOG - I
  IF(LAST .EQ. 1) INC=1
  GO TO 205
ENDIF
220 CONTINUE
RETURN
!----------
!  WESTERN SIERRA LOG RULES.
!----------
300 CONTINUE
ITD=INT(BFTOPD(ISPC)+0.5)
IF(ITD.GT.100) ITD=100
CALL LOGS(D,H,ITD,BFMIND(ISPC),ISPC,BFSTMP(ISPC),BBFV)
BTKFLG = .TRUE.
RETURN
!
END
