SUBROUTINE ESINIT
IMPLICIT NONE
!----------
! CI $Id$
!----------
!     CALLED FROM INITRE, ONLY ONCE, TO INITIALIZE REGEN. MODEL.
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'ESPARM.f90'
!
!
INCLUDE 'ESCOMN.f90'
!
!
INCLUDE 'ESHAP.f90'
!
!
INCLUDE 'ESHAP2.f90'
!
!
INCLUDE 'ESRNCM.f90'
!
!
INCLUDE 'ESWSBW.f90'
!
!
!OMMONS
!----------
EQUIVALENCE (NSTK,SUMPRB)
LOGICAL LTEMP,LKECHO
CHARACTER*256 CNAME
INTEGER NSTK,I,KODE,JSTND
REAL X
!----------
!     SPECIES LIST FOR CENTRAL IDAHO VARIANT.
!
!     1 = WESTERN WHITE PINE (WP)          PINUS MONTICOLA
!     2 = WESTERN LARCH (WL)               LARIX OCCIDENTALIS
!     3 = DOUGLAS-FIR (DF)                 PSEUDOTSUGA MENZIESII
!     4 = GRAND FIR (GF)                   ABIES GRANDIS
!     5 = WESTERN HEMLOCK (WH)             TSUGA HETEROPHYLLA
!     6 = WESTERN REDCEDAR (RC)            THUJA PLICATA
!     7 = LODGEPOLE PINE (LP)              PINUS CONTORTA
!     8 = ENGLEMANN SPRUCE (ES)            PICEA ENGELMANNII
!     9 = SUBALPINE FIR (AF)               ABIES LASIOCARPA
!    10 = PONDEROSA PINE (PP)              PINUS PONDEROSA
!    11 = WHITEBARK PINE (WB)              PINUS ALBICAULIS
!    12 = PACIFIC YEW (PY)                 TAXUS BREVIFOLIA
!    13 = QUAKING ASPEN (AS)               POPULUS TREMULOIDES
!    14 = WESTERN JUNIPER (WJ)             JUNIPERUS OCCIDENTALIS
!    15 = CURLLEAF MOUNTAIN-MAHOGANY (MC)  CERCOCARPUS LEDIFOLIUS
!    16 = LIMBER PINE (LM)                 PINUS FLEXILIS
!    17 = BLACK COTTONWOOD (CW)            POPULUS BALSAMIFERA VAR. TRICHOCARPA
!    18 = OTHER SOFTWOODS (OS)
!    19 = OTHER HARDWOODS (OH)
!----------
DO 10 I=1,MAXSP
HTADJ(I)=0.0
XESMLT(I)=1.0
10 CONTINUE
ITRNRM=0
NSTK=0
NBWHST=0
STOADJ=0.0
CONFID=5.0
LINGRW=.FALSE.
LAUTAL=.FALSE.
LSPRUT=.TRUE.
IPRINT=1
INADV=0
LOAD=0
IBLK=0
MINREP=50
KDTOLD=-99
IPINFO=0
NTALLY=0
IDSDAT=-9999
IYRLRM=-9999
XTES=0.0
THRES1=0.10
THRES2=0.30
CALL ESRNSD (.FALSE.,X)
NPTIDS=0
INQUIRE (UNIT=JOREGT,OPENED=LTEMP)
IF(.NOT.LTEMP) THEN
  CNAME=TRIM(KWDFIL)//'_RegenRpt.txt'
!        CALL MYOPEN (JOREGT,CNAME,4,133, 0,1,1,0,KODE)
  CALL MYOPEN (JOREGT,CNAME,1,133, 0,1,1,0,KODE)
  IF(KODE.GT.0) WRITE(*,'('' OPEN FAILED FOR '',I4)') JOREGT
ENDIF
RETURN
!
!
!----------
!     CALLED FROM INITRE WHEN NOTREES KEYWORD IS ENTERED.
!----------
ENTRY ESEZCR (JSTND,LKECHO)
INADV=1
IF(LKECHO)WRITE(JSTND,30)
30 FORMAT(T12,'(EZCRUISE OPTION IN REGENERATION ESTABLISHMENT ', &
     'MODEL IS AUTOMATICALLY INVOKED.)'  )
!
RETURN
END
