SUBROUTINE FORKOD
IMPLICIT NONE
!----------
!  **FORKOD--CI   DATE OF LAST REVISION:  06/20/11
!----------
!
!     TRANSLATES FOREST CODE INTO A SUBSCRIPT, IFOR, AND IF
!     KODFOR IS ZERO, THE ROUTINE RETURNS THE DEFAULT CODE.
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
!OMMONS
!
!  ------------------------
!  NATIONAL FORESTS:
!  117 = NEZ PERCE
!  402 = BOISE
!  406 = CHALLIS
!  412 = PAYETTE
!  413 = SALMON
!  414 = SAWTOOTH
!  ------------------------
!  RESERVATION PSUEDO CODES:
!  7721 = DUCK VALLEY RESERVATION   (MAPPED TO 402 BOISE)
!  8107 = FORT HALL RESERVATION     (MAPPED TO 414 SAWTOOTH)
!  ------------------------
INTEGER JFOR(6),KFOR(6),NUMFOR,I
LOGICAL USEIGL, FORFOUND
!  ------------------------
!  DATA STATEMENTS
!  ------------------------
DATA JFOR/117,402,406,412,413,414/, NUMFOR /6/
DATA KFOR/1,2,2,3,2,2 /

USEIGL = .TRUE.
FORFOUND = .FALSE.


SELECT CASE (KODFOR)

!       CROSSWALK FOR RESERVATION PSUEDO CODES & LOCATION CODE
  CASE (7721)
    WRITE(JOSTND,70)
70     FORMAT(/,'********',T12,'DUCK VALLEY RESERVATION (7721) ', &
       'BEING MAPPED TO BOISE NF (402) FOR FURTHER PROCESSING.')
    IFOR = 3
  CASE (8107)
    WRITE(JOSTND,72)
72     FORMAT(/,'********',T12,'FORT HALL RESERVATION (8107) ', &
       'BEING MAPPED TO SAWTOOTH NF (414) FOR FURTHER PROCESSING.')
    IFOR = 3
!       END CROSSWALK FOR RESERVATION PSUEDO CODES & LOCATION CODE

  CASE DEFAULT

!         CONFIRMS THAT KODFOR IS AN ACCEPTED FVS LOCATION CODE
!         FOR THIS VARIANT FOUND IN DATA ARRAY JFOR
    DO 10 I=1,NUMFOR
      IF (KODFOR .EQ. JFOR(I)) THEN
        IFOR = I
        FORFOUND = .TRUE.
        EXIT
      ENDIF
10     CONTINUE

!         LOCATION CODE ERROR TRAP
    IF (.NOT. FORFOUND) THEN
      CALL ERRGRO (.TRUE.,3)
      WRITE(JOSTND,11) JFOR(IFOR)
11       FORMAT(/,'********',T12,'FOREST CODE USED IN THIS ', &
         'PROJECTION IS',I4)
      USEIGL = .FALSE.
    ENDIF

END SELECT

!     FOREST MAPPING CORRECTION {NONE FOR THIS VARIANT}
!     SELECT CASE (IFOR)
!     END SELECT


!     SET THE IGL VARIABLE ONLY IF DEFAULT FOREST IS USED
!     GEOGRAPHIC LOCATION CODE: 1=NORTH, 2=CENTRAL, 3=SOUTH
!     USED TO SET SOME EQUATIONS IN REGENERATION AND PERHAPS
!     HEIGHT-DIAMETER IN DIFFERENT VARIANTS.
IF (USEIGL) IGL = KFOR(IFOR)

KODFOR=JFOR(IFOR)
RETURN
END
