SUBROUTINE SITSET
IMPLICIT NONE
!----------
! CI $Id$
!----------
!  THIS SUBROUTINE IS USED TO SET SIMULATION CONTROLLING VALUES
!  THAT HAVE NOT BEEN SET USING THE KEYWORDS --- SDIMAX, BAMAX.
!
!  IT IS ALSO USED TO SET DEFAULTS WHICH ARE DEPENDENT ON FOREST CODE
!  WITHIN A VARIANT.
!----------
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'CICOM.f90'
!
!
INCLUDE 'VOLSTD.f90'
!
!
!OMMONS
!----------
CHARACTER FORST*2,DIST*2,PROD*2,VAR*2,VOLEQ*11
INTEGER IFIASP,ERRFLAG,ISPC,I,INTFOR,IREGN,J,JJ,K
REAL BAMAXA(130),SLO,SHI,TEM,SLOSSP,SHISSP
REAL R4SDI(MAXSP)
!----------
!     SPECIES LIST FOR CENTRAL IDAHO VARIANT.
!
!     1 = WESTERN WHITE PINE (WP)          PINUS MONTICOLA
!     2 = WESTERN LARCH (WL)               LARIX OCCIDENTALIS
!     3 = DOUGLAS-FIR (DF)                 PSEUDOTSUGA MENZIESII
!     4 = GRAND FIR (GF)                   ABIES GRANDIS
!     5 = WESTERN HEMLOCK (WH)             TSUGA HETEROPHYLLA
!     6 = WESTERN REDCEDAR (RC)            THUJA PLICATA
!     7 = LODGEPOLE PINE (LP)              PINUS CONTORTA
!     8 = ENGLEMANN SPRUCE (ES)            PICEA ENGELMANNII
!     9 = SUBALPINE FIR (AF)               ABIES LASIOCARPA
!    10 = PONDEROSA PINE (PP)              PINUS PONDEROSA
!    11 = WHITEBARK PINE (WB)              PINUS ALBICAULIS
!    12 = PACIFIC YEW (PY)                 TAXUS BREVIFOLIA
!    13 = QUAKING ASPEN (AS)               POPULUS TREMULOIDES
!    14 = WESTERN JUNIPER (WJ)             JUNIPERUS OCCIDENTALIS
!    15 = CURLLEAF MOUNTAIN-MAHOGANY (MC)  CERCOCARPUS LEDIFOLIUS
!    16 = LIMBER PINE (LM)                 PINUS FLEXILIS
!    17 = BLACK COTTONWOOD (CW)            POPULUS BALSAMIFERA VAR. TRICHOCARPA
!    18 = OTHER SOFTWOODS (OS)
!    19 = OTHER HARDWOODS (OH)
!
!  SURROGATE EQUATION ASSIGNMENT:
!
!  FROM THE IE VARIANT:
!      USE 17(PY) FOR 12(PY)             (IE17 IS REALLY TT2=LM)
!      USE 18(AS) FOR 13(AS)             (IE18 IS REALLY UT6=AS)
!      USE 13(LM) FOR 11(WB) AND 16(LM)  (IE13 IS REALLY TT2=LM)
!      USE 19(CO) FOR 17(CW) AND 19(OH)  (IE19 IS REALLY CR38=OH)
!
!  FROM THE UT VARIANT:
!      USE 12(WJ) FOR 14(WJ)
!      USE 20(MC) FOR 15(MC)             (UT20 = SO30=MC, WHICH IS
!                                                  REALLY WC39=OT)
!----------
!  DATA STATEMENTS
!----------
DATA BAMAXA/ &
     7*100., 130., 3*95., 220., 213., 140., 175., 154., 137., &
     122., 152., 100., 2*220., 233., 220., 175., 250., 2*190., &
     226., 140., 200., 210., 140., 160., 200., 160., 200., 160., &
     180., 160., 4*200., 160., 225., 2*160., 2*170., 215., 210., &
     225., 210., 220., 300., 225., 350., 280., 225., 280., 342., &
     200., 230., 282., 350., 280., 300., 280., 150., 253., 2*242., &
     250., 275., 225., 300., 220., 270., 220., 2*225., 2*250., &
     150., 230., 140., 175., 240., 140., 210., 200., 250., 230., &
     200., 170., 200., 170., 160., 230., 220., 160., 2*200., 2*180., &
     190., 120., 140., 156., 120., 210., 140., 160., 214., 130., &
     154., 120., 300., 2*130., 200., 100., 75., 2*100., 110., &
     3*150./
DATA R4SDI/ &
     529.,423.,570.,562.,682.,762.,679.,620.,602.,446.,621., &
     576.,562.,272.,501.,409.,452.,409.,452./
!----------
! IF SITEAR(I) HAS NOT BEEN SET WITH SITECODE KEYWORD, LOAD IT
! WITH DEFAULT SITE VALUES.
!----------
TEM = 50.
IF(ISISP .GT. 0)THEN
  IF(SITEAR(ISISP) .GT. 0.0) TEM = SITEAR(ISISP)
ENDIF
IF(ISISP .EQ. 0) ISISP = 3
!----------
!  GET THE APPROPRIATE SITE INDEX RANGE VALUES FOR THE SITE SPECIES.
!----------
  SLOSSP = 0.
  SHISSP = 999.
  CALL SITERANGE (1,ISISP,SLOSSP,SHISSP)
!
DO 10 I=1,MAXSP
IF(TEM .LT. SLOSSP)TEM=SLOSSP
!----------
!  GET THE APPROPRIATE SITE INDEX RANGE VALUES FOR THIS SPECIES.
!----------
  SLO = 0.
  SHI = 999.
  CALL SITERANGE (1,I,SLO,SHI)
!
IF(SITEAR(I) .LE. 0.0) SITEAR(I) = SLO + &
    (TEM-SLOSSP)/(SHISSP-SLOSSP) &
    *(SHI-SLO)
10 CONTINUE
!----------
!  SET METHB & METHC DEFAULTS.  DEFAULTS ARE INITIALIZED TO 999 IN
!  **GRINIT**.  IF THEY HAVE A DIFFERENT VALUE NOW, THEY WERE CHANGED
!  BY KEYWORD IN INITRE. ONLY CHANGE THOSE NOT SET BY KEYWORD.
!
!  NEZ PERCE (IFOR=1) IS A REGION 1 FOREST. ALL OTHERS FORESTS IN THIS
!  VARIANT ARE IN REGION 4.
!----------
DO 50 ISPC=1,MAXSP
IF(IFOR.EQ.1)THEN
  IF(METHB(ISPC).EQ.999)METHB(ISPC)=6
  IF(METHC(ISPC).EQ.999)METHC(ISPC)=6
ELSE
  IF(METHB(ISPC).EQ.999)METHB(ISPC)=6
  IF(METHC(ISPC).EQ.999)METHC(ISPC)=6
ENDIF
50 CONTINUE
!----------
!  SET SDIDEF AND BAMAX VALUES WHICH HAVE NOT BEEN SET BY KEYWORD.
!  If a user sets BAMAX, then set the SDI maximums by species with this equation:
!     SDIDEF(I)=BAMAX/(0.5454154*(PMSDIU/100.))
!  If a user hasn�t set BAMAX, then set SDI maximums based on region.
!  If in R1 (ifor eq 1), then set the SDI maximums by species based on habitat type:
!          BAMAX=BAMAXA(ICINDX)
!          SDIDEF(I)=BAMAX/(0.5454154*(PMSDIU/100.))
!  Or
!          SDIDEF(I)= BAMAXA(ICINDX)/(0.5454154*(PMSDIU/100.))
!
!  If in R4, then set SDI maximums by species based on R4SDI values and
!     change the calculation method to zeide if not set by the user:
!         IF(CALCSDI.EQ.' ')LZEIDE = .TRUE.
!          SDIDEF(I) = R4SDI(I)
!----------
IF(CALCSDI.EQ.' ' .AND. IFOR .LT. 2) LZEIDE = .FALSE.
IF (BAMAX .GT. 0.0) THEN
  DO I=1,MAXSP
    IF(SDIDEF(I).LE.0.) &
         SDIDEF(I)=BAMAX/(0.5454154*(PMSDIU/100.))
  ENDDO
ELSE
  BAMAX=BAMAXA(ICINDX)
  DO I=1,MAXSP
    IF(IFOR .LT. 2) THEN
      IF(SDIDEF(I).LE.0.) &
           SDIDEF(I)=BAMAX/(0.5454154*(PMSDIU/100.))
    ELSE
      IF(SDIDEF(I).LE.0.) SDIDEF(I)=R4SDI(I)
    ENDIF
  ENDDO
ENDIF
!
DO 92 I=1,15
J=(I-1)*10 + 1
JJ=J+9
IF(JJ.GT.MAXSP)JJ=MAXSP
WRITE(JOSTND,90)(NSP(K,1)(1:2),K=J,JJ)
90 FORMAT(/'SPECIES ',5X,10(A2,6X))
WRITE(JOSTND,91)(NINT(SDIDEF(K)),K=J,JJ )
91 FORMAT('SDI MAX ',   10I8.0)
IF(JJ .EQ. MAXSP)GO TO 93
92 CONTINUE
93 CONTINUE
!----------
!  LOAD VOLUME EQUATION ARRAYS FOR ALL SPECIES
!----------
INTFOR = KODFOR - (KODFOR/100)*100
WRITE(FORST,'(I2)')INTFOR
IF(INTFOR.LT.10)FORST(1:1)='0'
IREGN = KODFOR/100
DIST='  '
PROD='  '
VAR='CI'
!
IF (LFIANVB) CALL NVB_REGION_CHECK
DO ISPC=1,MAXSP
READ(FIAJSP(ISPC),'(I4)')IFIASP
VOLEQ='           '
IF(((METHC(ISPC).EQ.6).OR.(METHC(ISPC).EQ.9)).AND. &
        (VEQNNC(ISPC).EQ.'           '))THEN
  CALL VOLEQDEF(VAR,IREGN,FORST,DIST,IFIASP,PROD,VOLEQ,ERRFLAG)
  VEQNNC(ISPC)=VOLEQ
ELSE IF (METHC(ISPC).EQ.10 .AND. VEQNNC(ISPC).EQ.'          ')THEN
  CALL NVBEQDEF(IFIASP, VOLEQ)
  VEQNNC(ISPC)=VOLEQ
ENDIF
IF(((METHB(ISPC).EQ.6).OR.(METHB(ISPC).EQ.9)).AND. &
        (VEQNNB(ISPC).EQ.'           '))THEN
  VOLEQ='           '
  CALL VOLEQDEF(VAR,IREGN,FORST,DIST,IFIASP,PROD,VOLEQ,ERRFLAG)
  VEQNNB(ISPC)=VOLEQ
ENDIF
ENDDO
!----------
!  IF FIA CODES WERE IN INPUT DATA, WRITE TRANSLATION TABLE
!---------
IF(LFIA) THEN
  CALL FIAHEAD(JOSTND)
  WRITE(JOSTND,211) (NSP(I,1)(1:2),FIAJSP(I),I=1,MAXSP)
211   FORMAT ((T12,8(A3,'=',A6,:,'; '),A,'=',A6))
ENDIF
!----------
!  WRITE VOLUME EQUATION NUMBER TABLE
!----------
CALL VOLEQHEAD(JOSTND)
WRITE(JOSTND,230)(NSP(J,1)(1:2),VEQNNC(J),VEQNNB(J),J=1,MAXSP)
230 FORMAT(4(2X,A2,4X,A11,1X,A10,1X))
!
RETURN
END
