!ODE SEGMENT CALCOM
!----------
! COMMON $Id$
!----------
!
INTEGER ICRHAB,IRHHAB,ISPCCF,ISPDSQ,ISPFOR,ISPHAB,NCALHT
!
REAL    FNMIN,HGHCH,POTEN,REGCH
!
REAL    GMULT(2),REIN(2)
!
COMMON / CALCOM /  FNMIN,GMULT,HGHCH,ICRHAB,IRHHAB,ISPCCF,ISPDSQ, &
                      ISPFOR,ISPHAB,NCALHT,POTEN,REGCH,REIN
!
!----------
!  DEFINITIONS OF VARIABLES IN 'CALCOM' COMMON BLOCK:
!----------
!
!    FNMIN  -- MINIMUM DIA. GROWTH OBSERVATIONS PER SPECIES TO
!              CALIBRATE LARGE TREE DIAMETER INCREMENT MODEL FOR
!              LOCAL CONDITIONS - USED IN DGDRIV ROUTINES
!     GMULT --
!     HGHCH --
!    ICRHAB --
!    IRHHAB --
!    ISPCCF --
!    ISPDSQ --
!    ISPFOR --
!    ISPHAB --
!    NCALHT -- MINIMUM NUMBER OF HEIGHT GROWHT OBSERVATIONS TO
!              CALIBRATE THE SMALL TREE HEIGHT INCREMENT MODEL FOR
!              LOCAL CONDITIONS - USED IN REGENT ROUTINES
!     POTEN --
!     REGCG --
!      REIN --
!
!-----END SEGMENT
