!ODE SEGMENT ESCOM2
!----------
! COMMON $Id$
!----------
!  THIS COMMON BLOCK IS ONLY USED IN VARIANTS WITH THE FULL REGEN/ESTAB
!  MODEL.
!  BE SURE TO INCLUDE ESPARM BEFORE ESCOM2.
!  USED IN ESADVH, ESBLKD, ESDLAY, ESGENT, ESNSPE, ESPADV, ESPREP, ESPSUB,
!  ESPXCS, ESSUBH, ESTAB, ESTIME, ESTOCK, ESTPP, & ESUCKR.
!----------
!
REAL    CHAB(16,10),CPRE(4,10),DHAB(16,10),DPRE(4,10), &
           FHAB(16,10),FPRE(4,10),PADV(MAXSP),PSUB(MAXSP), &
           PXCS(MAXSP),SPEHAB(5,4),XPREP(4,5)
!
COMMON /ESCOM2/ CHAB,CPRE,DHAB,DPRE,FHAB,FPRE,PADV,PSUB,PXCS, &
                   SPEHAB,XPREP
!
!----------
!  VARIABLE DEFINITIONS:
!----------
!    CHAB --
!    CPRE --
!    DHAB --
!    DPRE --
!    FHAB --
!    FPRE --
!    PADV --
!    PSUB --
!    PXCS --
!  SPEHAB --
!   XPREP --
!
!-----END SEGMENT
