!ODE SEGMENT ESHAP
!----------
! COMMON $Id$
!----------
!     COMMON AREA TO BE USED WITH ALL REGENERATION MODEL VARIANTS.
!     BE SURE TO INCLUDE PRGPRM.F77 BEFORE ESHAP.
!     USED IN ESCPRS, ESFLTR, ESIN, ESINIT, ESNUTR, ESOUT, ESBLKD,
!     ESPLT1, ESPLT2, ESTAB, ESPADV, ESPSUB, ESPXCS, ESUCKR, & ESTUMP.
!----------
!
LOGICAL LAUTAL,LINGRW,LSPRUT
!
INTEGER IBLK,IDSDAT,IFO,IHTYPE,INADV,IPINFO,IPRINT,ITRNRM,IYRLRM
INTEGER JOREGT,KDTOLD,LOAD,METH,MINREP,MODE,NPTIDS,NTALLY
!
INTEGER IALN(3),IHABT(16),IPHAB(MAXPLT),IPHYS(MAXPLT)
INTEGER IPPREP(MAXPLT),IPTIDS(MAXPLT)
!
REAL    CONFID,ESA,ESB,ESDRAW,OLDTIM,PBURN,PMECH,STOADJ
REAL    THRES1,THRES2,XTES,ZBURN,ZMECH
!
REAL    HTADJ(MAXSP),PASP(MAXPLT),PSLO(MAXPLT),SUMPRE(5)
REAL    XESMLT(MAXSP)
!
COMMON /ESHAP/ CONFID,ESA,ESB,ESDRAW,HTADJ,IALN,IBLK,IDSDAT,IFO, &
                  IHABT,IHTYPE,INADV,IPHAB,IPHYS,IPINFO,IPPREP, &
                  IPRINT,IPTIDS,ITRNRM,IYRLRM,JOREGT,KDTOLD,LAUTAL, &
                  LINGRW,LOAD,LSPRUT,METH,MINREP,MODE,NPTIDS,NTALLY, &
                  OLDTIM,PASP,PBURN,PMECH,PSLO,STOADJ,SUMPRE,THRES1, &
                  THRES2,XESMLT,XTES,ZBURN,ZMECH
!
!----------
!  VARIABLE DEFINITIONS:
!----------
!     CONFID -- CURRENTLY USED TO SET THE NUMBER OF EXCESS TREES PER
!               SPECIES PASSED TO THE PROGNOSIS MODEL.
!        ESA -- PROBABILITY OF STOCKING BASED ON REGENERATION INVENTORY,
!                USED FOR CALIBRATION OF ESTABLISHMENT MODEL
!        ESB --
!     ESDRAW --
!      HTADJ -- ADJUSTMENT VALUE FOR TREE HEIGHTS, BY SPECIES.
!       IALN -- 0 IF NO SITE PREP IS ENTERED, 1 IF SITE PREP VIA
!               BURNPREP OR MECHPREP KEYWORD IS USED
!       IBLK --
!     IDSDAT -- DATE OF DISTURBANCE.
!        IFO --
!      IHABT -- SUMMARY AND COUNT OF PLOT HABITAT TYPE
!     IHTYPE --
!      INADV -- WE ASSUME ADVANCE REGENERATION WAS INVENTORIED UNLESS
!               'INADV' IS SET TO 1.  IF INADV=1, THE MODEL WILL ADD
!               THE EXPECTED ADVANCE COMPONENT.
!      IPHAB -- PLOT HABITAT TYPE CODE.
!      IPHYS -- PLOT PHYSIOGRAPHIC POSITION.  DEFAULT IS MID-SLOPE.
!     IPINFO --
!     IPPREP -- PLOT SITE PREP.  TO USE VECTOR, 'LOAD' MUST EQUAL 1.
!     IPRINT -- CONTROLS PRINTING OF ESTABLISHMENT SUMMARIES. 0=NOTHING
!               PRINTED. 1=STAND SUMMARY.
!     IPTIDS -- INVENTORY POINT ID FROM BASE MODEL
!     ITRNRM -- NUMBER OF TREE RECORDS TO SPROUT IN ESUCKR.
!     IYRLRM -- THE YEAR OF LAST REMOVAL...SET IN ESNUTR.
!     JOREGT -- OUTPUT UNIT FOR REGEN SUMMARY.  DEFINED IN ESINIT.
!     KDTOLD --
!     LAUTAL -- TRUE IF AUTO-TALLIES ARE BEING INCLUDED.
!     LINGRW -- TRUE IF AUTO-INGROWTH IS BEING SIMULATED, FALSE IF NOT.
!       LOAD -- A 0/1 VARIABLE TO INDICATE WHETHER TO USE SITE PREP
!               FROM AN INVENTORY AS INPUT BY 'IPPREP'.  1= USE THE
!               VECTOR IPPREP FROM PLOTINFO KEYWORD OR TREEDATA CARDS
!     LSPRUT -- TRUE IF SPROUTING LOGIC IS ON, FALSE IF OFF.
!       METH --
!     MINREP -- NUMBER OF REGENERATION INVENTORY PLOTS TO PROJECT
!       MODE --
!     NPTIDS -- TOTAL NUMBER OF POINT IDS IN BASE MODEL
!     NTALLY -- THE CURRENT TALLY NUMBER.
!     OLDTIM --
!       PASP -- PLOT ASPECT IN RADIANS.  DEFAULT IS STAND ASPECT.
!      PBURN -- PROPORTION OF PLOT RECEIVING BURN SITE PREPARATION
!      PMECH -- PROPORTION OF PLOT RECEIVING MECHANICAL SITE PREPARATION
!       PSLO -- PLOT SLOPE RATIO.  DEFAULT IS STAND SLOPE.
!     STOADJ -- MULTIPLIER FOR THE PROBABILITY OF STOCKING.
!     SUMPRE -- SITE PREPARATION METHOD?
!     THRES1 -- LOWER THRESHOLD OF REMOVALS THAT TRIGGERS ONE TALLY.
!     THRES2 -- UPPER THRESHOLD OF REMOVALS THAT TRIGGERS A TALLY
!               SEQUENCE.  BOTH THRES1 & THRES2 ARE RATIOS.
!     XESMLT --
!       XTES -- RATIO OF REMOVALS AS CALCULATED IN ESNUTR.
!      ZBURN -- DATE OF BURN SITE PREP.
!      ZMECH -- DATE OF MECHANICAL SITE PREP.
!
!-----END SEGMENT
