!ODE SEGMENT ESHAP2
!----------
! COMMON $Id$
!----------
!     BE SURE TO INCLUDE PRGPRM.F77 BEFORE ESHAP2.
!     USED IN ESCPRS, ESFLTR, ESIN, ESINIT, ESNUTR, ESOUT, ESBLKD,
!     ESPLT1, ESPLT2, ESTAB, ESPADV, ESPSUB, ESPXCS, ESUCKR, & ESTUMP.
!----------
!
INTEGER NSTORE(MAXPLT)
!
REAL    ESB1(MAXPLT),PLPROB(MAXPLT),PNN(MAXPLT),PROB1(MAXPLT), &
           SUMPRB,XSTORE(MAXPLT)
!
COMMON /ESHAP2/ ESB1,NSTORE,PLPROB,PNN,PROB1,SUMPRB,XSTORE
!
!----------
!  VARIABLE DEFINITIONS:
!----------
!    ESB1 --
!  NSTORE --
!  PLPROB --
!     PNN --
!   PROB1 --
!  SUMPRB --
!  XSTORE --
!
!-----END SEGMENT
