!ODE SEGMENT GGCOM
!----------
! COMMON $Id$
!----------
!  THIS COMMON BLOCK CONTAINS VARIABLES UNIQUE TO THE
!  VARIANT DERIVED FROM THE GENGYM G&Y MODEL.
!----------
!
INTEGER IGFOR
!
REAL    AGERNG,BAINIT,DSTAG,SEEDS,TPAT
!
REAL    BARK1(MAXSP),BARK2(MAXSP),BAU(41),BCLAS(MAXSP,41), &
           BREAK(MAXSP),DBHMAX(MAXSP),SITEHI(MAXSP),SITELO(MAXSP), &
           TBA(MAXSP),TCLAS(MAXSP,41)
!
COMMON /GGCOM/ AGERNG,BAINIT,BARK1,BARK2,BAU,BCLAS,BREAK,DBHMAX, &
                  DSTAG,IGFOR,SEEDS,SITEHI,SITELO,TBA,TCLAS,TPAT
!
!----------
!  VARIABLE DEFINITIONS:
!----------
!     AGERNG -- RANGE IN AGES BETWEEN THE LARGEST DBH TREE AND THE
!               SMALLEST DBH TREE WHICH IS > 4.5' IN HEIGHT. USED
!               TO DETERMINE WHETHER A STAND IS EVEN-AGED OR UEA.
!     BAINIT -- INITIAL BASAL AREA OF STAND.
!      BARK1 -- COEFFICIENTS FOR BARK RATIO EQUATIONS IN BRATIO.
!      BARK2 --
!        BAU -- TOTAL BASAL AREA ABOVE THE SUBJECT DBH CLASS.
!      BCLAS -- BASAL AREA BY SPECIES BY FULL INCH DIAMETER CLASS.
!               0" CLASS BA COMPUTED AS IF TREES ARE 1.0" DBH.
!      BREAK -- BREAKPOINT DBH BETWEEN LARGE & SMALL TREES.
!     DBHMAX -- MAXIMUM DIAMETERS USED IN GEMDG.
!      DSTAG -- STAGNATION MULTIPLIER WHICH REDUCES GROWTH AND
!               MORTALITY UNDER STAGNATED STAND CONDITIONS.
!      IGFOR -- NUMBER OF R2 FORESTS + 1 FOR A PARTICULAR MODEL TYPE.
!               USED TO INDICATE R2 FORESTS VS R3 FOREST FOR VOLUME
!      SEEDS -- TREES/ACRE IN SEEDLINGS (TREES < 4.5' IN HEIGHT).
!     SITEHI -- UPPER END OF THE VALID SITE INDEX RANGE FOR A SPECIES.
!     SITELO -- LOWER END OF THE VALID SITE INDEX RANGE FOR A SPECIES.
!        TBA -- TOTAL BASAL AREA BY SPECIES.
!      TCLAS -- TREES PER ACRE BY SPECIES BY DIAMETER CLASS.
!       TPAT -- TOTAL TREES PER ACRE
!
!-----END SEGMENT
