!ODE SEGMENT HVDNCM
!----------
! COMMON $Id$
!----------
!
LOGICAL LNEDNG
!
REAL    AXXBA,AXXCCF,AXXHT,HXSIZE
!
REAL    HVDAHT(MXSTND,2),HVDBA(MXSTND,2),HVDCCF(MXSTND,2)
!
COMMON /HVDNCM/ AXXBA,AXXCCF,AXXHT,HVDAHT,HVDBA,HVDCCF, &
                   HXSIZE,LNEDNG
!
!----------
!  VARIABLE DEFINITIONS:
!----------
!     AXXBA =AVERAGE BASAL AREA OVER ALL UNITS, GIVING EQUAL WEIGHT.
!     AXXCCF=AVERAGE CCF OVER ALL UNITS, GIVING EQUAL WEIGHT.
!     AXXHT =AVERAGE TOP HEIGHT OVER ALL UNITS, GIVING EQUAL WEIGHT.
!     HVDAHT=TOP HEIGHT UNDER NOT SELECTED AND SELECTED.
!     HVDBA =BASAL AREA UNDER NOT SELECTED AND SELECTED.
!     HVDCCF=CCF UNDER NOT SELECTED AND SELECTED.
!     HXSIZE=SIZE OF ALL HEXAGONS IN ACRES, DEFAULT SET IN HVINIT.
!     LNEDNG=NEIGHBORING DENSITY EFFECTS OPTION SWITCH, GLOBAL LEVEL.
!
!-----END SEGMENT
