!ODE SEGMENT PDEN
!----------
! COMMON $Id$
!----------
!
REAL OLDFNT,REGNBK
!
REAL BAAA(MAXPLT),OVER(MAXSP,MAXPLT),PCCF(MAXPLT),PTPA(MAXPLT)
REAL PRDA(MAXPLT),PTPAA(MAXPLT)
!
COMMON /PDEN/ BAAA,OLDFNT,OVER,PCCF,PTPA,PTPAA,PRDA,REGNBK
!
!----------
!  VARIABLE DEFINITIONS:
!----------
!  OLDFNT =
!    PCCF = POINT CCF, LOADED IN **DENSE**.
!    PTPA = POINT TPA, LOADED IN **DENSE**.
!    BAAA = POINT BASAL AREA > REGNBK, LOADED IN **DENSE**.
!    OVER = POINT BASAL AREA BY SPECIES > REGNBK, LOADED
!           IN **DENSE**.
!   PTPAA = POINT TPA > REGNBK, LOADED IN **DENSE**.
!    PRDA = POINT RELATIVE DENSITY (ZEIDE/SDIMAX)> REGNBK,
!           LOADED IN **DENSE**.
!  REGNBK = BREAK DBH BETWEEN UNDERSTORY AND OVERSTORY TREES.
!           SET IN BLKDAT, USED DENSE, ESTAB, ESFLTR.
!
!-----END SEGMENT
