!ODE SEGMENT PLOT
!----------
! COMMON $Id$
!----------
!
CHARACTER*4 MGMID, ECOREG
CHARACTER*10 CPVREF
CHARACTER*26 NPLT
CHARACTER*40 DBCN
!
CHARACTER*4 FIAJSP(MAXSP),JSP(MAXSP),NSP(MAXSP,3)
CHARACTER*6 PLNJSP(MAXSP)
!
INTEGER IAGE,IASPEC,ICAGE,ICNTY,IFINT,IFOR,IFORTP,IGL,IIFORTP, &
           IMODTY, &
           IPHREG,IPTINV,ISISP,ISLOP,ISMALL,ISTATE,ISTCL,ISZCL, &
           ITYPE,JSPINDEF,KODFOR,KODTYP,MANAGD,NONSTK,NSITET, &
           ISTDORG
!
INTEGER IPVEC(MAXPLT),JSPIN(MAXSP),JTYPE(122)
!
REAL    ASPECT,ATAVD,ATAVH,ATBA,ATCCF,ATSDIX,ATTPA,AVH,BA,BAF, &
           BRK,BTSDIX,COVMLT,COVYR,ELEV,FINT,FPA,GROSPC,OLDAVH,OLDBA, &
           OLDTPA,ORMSQD,PI,PMSDIL,PMSDIU,RELDEN,RELDM1,RMAI,RMSQD, &
           SAMWT,SDIAC,SDIAC2,SDIBC,SDIBC2,SDIMAX,SLOPE,STNDSI, &
           TFPA,TLAT,TLONG,TPROB,VMLT,VMLTYR
!
REAL    BARANK(MAXSP),RELDSP(MAXSP),SDIDEF(MAXSP),SITEAR(MAXSP), &
           SITETR(MAXSTR,6)
!
COMMON /PLTCHR/ CPVREF,DBCN,ECOREG,FIAJSP,JSP,MGMID,NPLT,NSP, &
                   PLNJSP
!
COMMON /PLOT/ ASPECT,ATAVD,ATAVH,ATBA,ATCCF,ATSDIX,ATTPA,AVH,BA, &
                 BAF,BARANK,BRK,BTSDIX,COVMLT,COVYR,ELEV,FINT,FPA, &
                 GROSPC,IAGE,IASPEC,ICAGE,ICNTY,IFINT,IFOR,IFORTP, &
                 IGL,IIFORTP,IMODTY,IPHREG,IPTINV,IPVEC,ISISP,ISLOP, &
                 ISMALL, &
                 ISTATE,ISTCL,ISZCL,ITYPE,JSPIN,JSPINDEF,JTYPE, &
                 KODFOR,KODTYP,MANAGD,NONSTK,NSITET,OLDAVH,OLDBA, &
                 OLDTPA,ORMSQD,PI,PMSDIL,PMSDIU,RELDEN,RELDM1,RELDSP, &
                 RMAI,RMSQD,SAMWT,SDIAC,SDIAC2,SDIBC,SDIBC2,SDIDEF, &
                 SDIMAX,SITEAR,SITETR,SLOPE,STNDSI,TFPA,TLAT,TLONG, &
                 TPROB,VMLT,VMLTYR,ISTDORG
!
!----------
!  VARIABLE DEFINITIONS:
!----------
!
!    ASPECT -- STAND ASPECT; READ IN DEGREES, CONVERTED TO RADIANS.
!     ATAVD -- QUADRATIC MEAN STAND DBH. AFTER THINNING. SAVED IN
!              GRINCR AFTER CALLING DENSE.
!     ATAVH -- AVERAGE HEIGHT OF DOMINATES AFTER THINNING.
!              SAVED IN GRINCR AFTER CALL TO DENSE.
!      ATBA -- BASAL AREA AFTER THINNING.
!              SAVED IN GRINCR AFTER CALL TO DENSE.
!     ATCCF -- CROWN COMPETITION FACTOR AFTER THINNING.
!    ATSDIX -- MAXIMUM SDI AFTER  TREATMENT
!     ATTPA -- TREES PER ACRE AFTER THINNING.
!              SAVED IN GRINCR AFTER CALL TO DENSE.
!       AVH -- CURRENT AVERAGE STAND HEIGHT. CALCULATED IN **DENSE**.
!        BA -- CURRENT STAND BASAL AREA.  CALCULATED IN **DENSE**.
!       BAF -- BASAL AREA FACTOR USED IN INVENTORY.  DEFAULTED
!              TO 40 IN **BLOCK DATA**, BUT CAN BE ALTERED BY
!              KEYWORD.
!    BARANK -- SPECIES RANKING BY AMOUNT OF BASAL AREA.
!       BRK -- MINIMUM DIAMETER OF TREES MEASURED ON VARIABLE PLOT.
!              SET TO 5 IN **INITRE**, BUT CAN BE RESET BY
!              KEYWORD.
!    BTSDIX -- MAXIMUM SDI BEFORE TREATMENT
!    COVMLT -- SUM OF SERIAL CORRELATIONS BETWEEN BETWEEN TWO PERIODS
!              OF LENGTH I AND J.
!     COVYR -- COVMLT(YR,YR).
!    CPVREV -- POTENTIAL VEGETATION REFERENCE CODE USED IN **HABTYP**
!      DBCN -- DATABASE CONTROL NUMBER, USED BY THE DATABASE EXTENSION
!              FOR DATA SOURCE IDENTIFICATION AT THE STAND LEVEL.
!    ECOREG -- BAILEY'S ECOLOGICAL REGION / PROVENCE USED IN
!              FIA VBC EQUATION DEFINITION (ADDED MARCH 2024)
!      ELEV -- STAND ELEVATION IN HUNDREDS OF FEET.
!    FIAJSP -- FIA SPECIES CODES CORRESPONDING TO SPECIES IN JSP.
!      FINT -- FLOATING POINT REPRESENTATION OF LENGTH OF CURRENT
!              CYCLE.  INITIALIZED IN **INITRE**,UPDATED IN **DISPLY**
!       FPA -- INVERSE OF THE AREA OF THE FIXED PLOT IN ACRES.
!              SET TO 300 IN **INITRE**, BUT CAN BE RESET BY
!              KEYWORD.
!    GROSPC -- MULTIPLIER WHICH INFLATES CROWN COMPETITION FACTOR
!              TO COMPENSATE FOR NON-STOCKABLE POINTS.  COMPUTED
!              IN **INITRE**.
!      IAGE -- ORIGINAL STAND AGE -- SHOULD NEVER BE UPDATED.
!    IASPEC -- INPUT STAND ASPECT IN DEGREES.
!     ICAGE -- ORIGINAL STAND AGE COMPUTED FROM SIZE CLASS & TREE HT
!     ICNTY -- FIA COUNTY CODE
!     IFINT -- FIXED POINT REPRESENTATION OF CURRENT CYCLE LENGTH.
!              LOADED IN **MAIN**.
!      IFOR -- SUBSCRIPT TO REGION ONE FOREST IDENTIFICATION CODE.
!    IFORTP -- FOREST TYPE FOR THOSE VARIANTS THAT USE IT
!              FIELD 3 OF MODTYPE KEYWORD
!       IGL -- GEOGRAPHIC LOCATION CODE: 1=NORTH, 2=CENTRAL,
!              3=SOUTH.  LOADED IN INITRE DEPENDING ON VALUE OF
!              IFOR, USED IN REGENT.
!   IIFORTP -- INVENTORY FORTEST TYPE INPUT OR CALCULATED THAT CAN BE
!              USED IF CURRENT CALCULATED FORTEST TYPE BECOMES UNDEFINED.
!              ADDED FOR 2020 AK VARIANT ESTABLISHMENT MODEL.
!    IMODTY -- MODEL TYPE FOR THOSE VARIANTS THAT USE IT
!              FIELD 1 OF MODTYPE KEYWORD
!    IPHREG -- PHYSIOGRAPHIC REGION FOR THOSE VARIANTS THAT USE IT
!              FIELD 2 OF MODTYPE KEYWORD
!    IPTINV -- SAME AS PI (POINTS INVENTORIED) (EXCEPT IT IS AN INTEGER)
!     IPVEC -- SUB-PLOT IDENTIFICATION VECTOR.
!     ISISP -- SITE SPECIES IE SPECIES OF MAXIMUM BASAL AREA. SPECIFIED
!              BY KEYWORD OR CALCULATED IN MBACAL.
!     ISLOP -- INPUT STAND SLOPE NOT DECODED.
!    ISMALL -- NUMBER OF TREE RECORDS LESS THAN 3.0 INCHES DBH.
!              COMPUTED IN **HTGF**.  SUBSCRIPTS TO THESE RECORDS
!              ARE STORED IN IND2.
!    ISTATE -- FIA STATE CODE
!    ISTCL  -- STOCKING CLASS CALCULATED IN STKVAL
!   ISTDORG -- INTEGER REPRESENTATION OF STAND ORIGIN CODE
!              0 = STAND OF NATURAL ORIGIN
!              1 = PLANTATION
!    ISZCL  -- SIZE CLASS CALCULATED IN STKVAL
!     ITYPE -- INPUT STAND HABITAT TYPE CODE.  CONVERTED TO
!              SUBSCRIPT IN **INITRE**.
!       JSP -- VALID SPECIES CODES.  LOADED IN **BLOCK DATA**.
!              CHANGABLE BY KEYWORD.
!     JSPIN -- SET IN **INTREE**,**SPCTRN**,**ESTAB**, - CARRIES INPUT
!              SPECIES CODE FORMAT: 1=ALPHA CODE,2=FIA CODE,3=PLANTS CODE
!              DEFAULT SET IN **INTRE**, **SPCTRN**
!  JSPINDEF -- DEFAULT SPECIES CODE FORMAT SET IN **INTREE** OR
!              **SPCTRN**
!     JTYPE -- VALID HABITAT TYPE CODES.  LOADED IN **BLOCK DATA**.
!    KODFOR -- USER FOREST CODE INTERPRETED IN FORCOD ROUTINE
!    KODTYP -- HABITAT TYPE CODE AS CLASSIFIED IN HABTYP
!    MANAGD -- VARIABLE INDICATING WHETHER STAND IS CONSIDERED A
!              MANAGED STAND (0=UNMANAGED, 1=MANAGED)
!     MGMID -- THE RUN MANAGEMENT ID. SET BY KEYWORD.
!    NONSTK -- NUMBER OF NON-STOCKABLE POINTS INVENTORIED. SET
!              AND USED IN **INITRE**.
!      NPLT -- STAND IDENTIFICATION CODE.  INPUT BY KEYWORD CARD.
!    NSITET -- NUMBER OF SITE TREES READ IN THE INPUT DATA.
!       NSP -- VALID SPECIES-TREE CLASS CODES.  LOADED IN
!              **BLOCK DATA**.
!    OLDAVH -- AVERAGE DOM HEIGHT AT END OF LAST CYCLE.
!     OLDBA -- THE BASAL AREA PER ACRE AT THE END OF THE LAST CYCLE
!    OLDTPA -- THE TREES PER ACRE AT THE END OF THE LAST CYCLE
!    ORMSQD -- QUADRATIC MEAN DBH AT END OF LAST CYCLE.
!        PI -- NUMBER OF POINTS INVENTORIED.  SET IN **INITRE**.
!    PLNJSP -- PLANTS SPECIES SYMBOLS CORRESPONDING TO SPECIES IN JSP.
!    PMSDIL -- PERCENT VALUE OF MAX SDI WHERE DENSITY RELATED MORTALITY
!              IS INVOKED.
!    PMSDIU -- PERCENT VALUE OF MAX SDI AT WHICH STAND REACHES MAXIMUM
!              DENSITY.
!    RELDEN -- CURRENT CROWN COMPETITION FACTOR FOR THE STAND.
!              COMPUTED IN **DENSE**.
!    RELDM1 -- CROWN COMPETITION FACTOR FOR STAND IN PREVIOUS CYCLE.
!              COMPUTED IN **DENSE**.
!    RELDSP -- CONTRIBUTION TO CROWN COMPETITION FACTOR OF EACH
!              SPECIES.  COMPUTED IN **DENSE**.
!      RMAI -- ADJUSTED MEAN ANNUAL INCREMENT FOR THE STAND
!     RMSQD -- STAND QUADRATIC MEAN DIAMETER.  CALCULATED IN
!              **DENSE**
!     SAMWT -- STAND SAMPLING WEIGHT. USED ONLY TO PASS THE SAMPLING
!              WEIGHT FOR THE STAND TO THE NEXT STEPS IN ANY ANALYSIS
!              VIA THE SUMMARY OUTPUT. SEE GROPTS & DISPLY FOR DETAILS.
!     SDIAC -- STAND DENSITY INDEX FOLLOWING CUTTING
!    SDIAC2 -- ZEIDE STAND DENSITY INDEX FOLLOWING CUTTING
!     SDIBC -- STAND DENSITY INDEX BEFORE CUTTING
!    SDIBC2 -- ZEIDE STAND DENSITY INDEX BEFORE CUTTING
!    SDIDEF -- MAXIMUM STAND DENSITY INDEX FOR INDICATED SPECIES.
!    SDIMAX -- MAXIMUM STAND DENSITY INDEX FOR THE STAND.
!    SITEAR -- SITE INDEX VALUES BY SPECIES FOR LARGE AND SMALL TREES.
!    SITETR -- TREE INFORMATION FOR CALCULATING SITE INDEX:
!              1 = SPECIES
!              2 = DBH
!              3 = HEIGHT
!              4 = AGE
!              5 = TOTAL AGE OR BREAST HEIGHT AGE
!              6 = ON PLOT / OFF PLOT SITE TREE
!     SLOPE -- STAND SLOPE PERCENT SCALED TO THE RANGE 0-1.
!    STNDSI -- INITIAL SITE INDEX OF THE SITE SPECIES FOR THE STAND;
!              INITIALLY SET IN INITRE; POSSIBLY RESET IN GRINCR.
!      TFPA -- SUM OF THE AREA OF A SET OF FIXED AREA PLOTS
!              WHICH ARE TO BE COMBINED AND RUN AS A SINGLE
!              STAND.  NORMALLY SET TO ZERO.
!      TLAT -- INPUT STAND LATITUDE.
!     TLONG -- INPUT STAND LONGITUDE.
!     TPROB -- TOTAL NUMBER OF TREES PER ACRE.
!      VMLT -- SUM OF SERIAL CORRELATIONS WITHIN A PERIOD OF LENGTH I
!    VMLTYR -- VMLT(YR)
!
!-----END SEGMENT
