!ODE SEGMENT SVDATA
!----------
! COMMON $Id$
!----------
!     COMMON AREA FOR STAND VISULIZATION (SV) DATA.
!----------
!
INTEGER MXSVOB
PARAMETER (MXSVOB=15000)
!
INTEGER ICOLIDX,IDPLOTS,IGRID,IMETRIC,IMORTCNT,IPLGEM,IRPOLES, &
           ISVINV,JSVOUT,JSVPIC,NIMAGE,NSVOBJ
!
INTEGER IOBJTP(MXSVOB),IS2F(MXSVOB)
!
REAL    SVMSAVE(MAXTRE),X1R1S(MAXPLT),X2R2S(MAXPLT),XSLOC(MXSVOB), &
           Y1A1S(MAXPLT),Y2A2S(MAXPLT),YSLOC(MXSVOB)
!
COMMON /SVDATA/ ICOLIDX,IDPLOTS,IGRID,IMETRIC,IMORTCNT,IOBJTP, &
                   IPLGEM,IRPOLES,IS2F,ISVINV,JSVOUT,JSVPIC,NIMAGE, &
                   NSVOBJ,SVMSAVE,X1R1S,X2R2S,XSLOC,Y1A1S,Y2A2S,YSLOC
!
!----------
!  VARIABLE DEFINITIONS:
!----------
!     ICOLIDX=THE COLOR INDEX VALUE, SEE SVGRND FOR DEFINITIONS.
!     IDPLOTS= CONTROLS DRAWING PLOT BOUNDARIES, 0=NONE, 1=DRAW THEM.
!     IGRID = THE GRID RESOLUTION FOR THE GROUND FILES (ZERO=NONE MADE).
!     IMETRIC= CONTROLS SENDING METRIC OR IMPERIAL INFO TO SVS,
!              0= NO (CLASSIC IMPERIAL), 1=YES (METRIC)
!     IMORTCNT= STORES THE COUNT OF TIMES SVMORT HAS BEEN CALLED THIS CYCLE.
!     IOBJTP= A VECTOR THAT DEFINES THE KINDS OF OBJECTS WHERE
!             0 = THE SLOT IS OPEN
!             1 = AN FVS TREE, SVS TREE CLASS WILL BE 99 (LIVE)
!             2 = A SNAG RECORD
!             3 = A TREE THAT WILL BE REMOVED AT THE END OF THE
!                 SVOUT.  CURRENTLY A TREE THAT WILL BE REMOVED
!                 AFTER YARDING.
!             4 = CWD OBJECT (EXCLUSIVE OF FALLEN SNAGS)
!             5 = A SNAG THAT WILL BE REMOVED AT THE END OF SVOUT.
!                 CURRENTLY USED TO FLAG SALVAGED SNAGS.
!             IOBJTP CANNOT BE A NEGATIVE VALUE, AS BEING NEGATIVE
!             IS USED TO STORE INFORMATION FOR A SHORT TIME
!     IPLGEM= PLOT GEOMETRY CODE, WHERE
!            0 = SQUARE ACRE, IGNORE POINT IDENTIFICATIONS
!            1 = A SUBDIVIDED SQUARE ACRE
!            2 = ROUND PLOTS, IGNORE PLOT IDENTIFICATIONS
!            3 = A SUBDIVIDED ROUND ACRE
!     IRPOLES= CONTROLS DRAWING SCALE POLES, 0=NONE, 1=DRAW THEM.
!     IS2F  = IF IOBJTP=1,IS2F POINTS TO TREE RECORD.
!             IF IOBJTP=2,IS2F POINTS TO A SNAG RECORD.
!             IF IOBJTP=4,IS2F POINTS TO A CWD RECORD.
!             IF ZERO, THEN THE OBJECT IS ONE OF THE OBJ TYPES,
!             BUT IT IS NOT REGISTERED WITH A ATTRIBUTE LIST.
!     ISVINV= MAX OF ITRE() OR IPTINV, WHICH EVER IS GREATER
!     JSVOUT= 0 IF NOT USING SV, OTHERWISE IT IS THE FILE NUMBER
!             USED TO WRITE THE .svs FILES.
!     JSVPIC= FILE NUMBER USED TO WRITE THE INDEX FILE.
!     NIMAGE= IMAGE SEQUENCE NUMBER.
!     NSVOBJ= THE NUMBER OF OBJECTS DEFINED.
!     SVMSAVE= STORAGE LIST FOR PREVIOUSLY PROCESSED MORTALITY
!     X1R1S,X2R2S,Y1A1S,Y2A2S = MAX,MIN COORDINATES FOR RECTANGULAR
!             PLOTS AND MAX, MIN RADII AND ANGLES FOR CIRCULAR PLOTS
!     XSLOC = A VECTOR OF X LOCATIONS
!     YSLOC = A VECTOR OF Y LOCATIONS
!
!-----END SEGMENT
