SUBROUTINE CFVOL(ISPC,D,H,D2H,VN,VM,VMAX,TKILL,LCONE,BARK,ITHT, &
                    CTKFLG)
IMPLICIT NONE
!----------
! CANADA-BC $Id$
!----------
! THIS ROUTINE CALCULATES TOTAL CUBIC FOOT VOLUME USING A NUMBER OF
! DIFFERENT METHODS.
!----------
!OMMONS
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
!OMMONS
!----------
!  DIMENSION STATEMENT FOR INTERNAL ARRAYS.
!----------
LOGICAL TKILL,LCONE,CTKFLG
INTEGER ISPC,ITHT,FIZ

REAL D,H,D2H,VN,VM,VMAX,BARK,VOLT,VOLM
REAL HTRUNC

DATA FIZ /2/
!----------
!  INITIALIZE VOLUME ESTIMATES.
!----------
VN=0.0
VM=0.0
VMAX=0.0
!----------
!  METHC=4 -- COMPUTE VOLUMES BASED ON KOZAK'S TAPER FUNCTIONS. IF HEIGHT IS LESS THAN
!             4.5 FT OR DBH IS LESS THAN MINIMUM, OR DBH IS LESS THAN TOP DIAMETER
!             THEN THE TREE IS COMPLETELY IGNORED IN MERCHANTABILITY CALCULATIONS. ALL
!             TREES ARE USED FOR TOTAL VOLUME CALCULATIONS.
!----------

  HTRUNC = FLOAT(ITHT)
  IF (HTRUNC .GT. 0.0) HTRUNC = HTRUNC / 100.0
  IF (HTRUNC .EQ. 0.0) HTRUNC = H
  IF (H .GE. 4.5) THEN
!
!         This needs to be updated to use Kozak's 2002 refit; also to calculate log
!         volumes by BEC zone; which the new LOG(...) subroutine uses.
!
    CALL MIN(ISPC,IAGE,FIZ,D,H,STMP(ISPC),TOPD(ISPC), &
                HTRUNC,VOLT,VOLM)
    IF (D .GE. DBHMIN(ISPC) .AND. D .GE. TOPD(ISPC)) THEN
      VN = VOLT
      VM = VOLM
    ELSE
      VN = VOLT
      VM = 0.0
    ENDIF
  ENDIF
  RETURN

RETURN
END
