SUBROUTINE NATCRZ (IWHO)
IMPLICIT NONE
!----------
! CANADA-BC $Id$
!----------
!
!     CREATE A FILE FOR PROCESSING THROUGH THE NATIONAL CRUISE SYSTEM
!     VOLUME ROUTINE
!
!     IWHO=1 IF CALLED FROM MAIN, IWHO=2 IF CALLED FROM CUTS
!     **THIS VERSION IS A STUB: NATCRZ NOTE USED IN BC**
!
INTEGER IWHO
RETURN
END
