SUBROUTINE ESMSGS (JOREGT)
IMPLICIT NONE
!----------
! STRP $Id$
!----------
!
!     CALLED FROM ESIN TO PRINT HABITAT TYPE GROUPS FOR THE
!     REGENERATION ESTABLISHMENT MODEL.
!
!
INTEGER JOREGT
!
WRITE(JOREGT,100)
100 FORMAT('HABITAT TYPE GROUPS USED IN THE REGENERATION', &
     ' ESTABLISHMENT MODEL',//,'GROUP   HABITAT TYPES',/, &
     '-----   ',34('-'),/)
RETURN
END
