SUBROUTINE ESTUMP (JSSP,DBH,PREM,JPLOT,ISHAG)
IMPLICIT NONE
!----------
! STRP $Id$
!----------
!  STORE INFORMATION FOR STUMP SPROUT SUBROUTINE.
!
!  STRP AND ESTB VERSIONS ARE IDENTICAL; IF YOU UPDATE ONE,
!  UPDATE BOTH.
!----------
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'ESPARM.f90'
!
!
INCLUDE 'ESHOOT.f90'
!
!
INCLUDE 'ESHAP.f90'
!
!
INCLUDE 'ESCOMN.f90'
!
!
!OMMONS
!----------
INTEGER JPLOT,JSSP,ISSP,IDBH,ISHAG,INDXAS
INTEGER*4 MDBH,IPLT,MSP,ISHI,I,MNAGDF,IBEST
REAL PREM,DBH,DBHEND
!----------
!  DATA STATEMENTS
!----------
DATA MDBH/10000000/,MSP/10000/
!----------
!  DETERMINE IF THIS IS A SPROUTING SPECIES
!----------
DO 10 I=1,NSPSPE
IF(JSSP.EQ.ISPSPE(I)) GO TO 11
10 CONTINUE
GO TO 900
11 CONTINUE
ISSP=I
!----------
!  DETERMINE DIAMETER CLASS OF THE TREE BEING CUT.
!----------
DO 100 I=1,NDBHCL-1
DBHEND=(DBHMID(I)+DBHMID(I+1))/2.0
IF(DBH.GT.DBHEND) GO TO 100
IDBH=I
GO TO 110
100 CONTINUE
IDBH=NDBHCL
110 CONTINUE
IPLT=JPLOT
IF(IPLT.GT.9999) IPLT=9999
ISHI = IDBH*MDBH + ISSP*MSP + IPLT
!----------
!  IF THERE IS ROOM IN THE LIST, THEN CREATE A NEW STUMP RECORD.
!----------
ITRNRM=ITRNRM+1
!----------
!  ISHOOT() IS A NUMBER COMPOSED OF DDDSSSPPPP, WHERE DDD = DBH CLASS,
!  SSS = SPECIES, AND PPPP = PLOT.  DECODED IN **ESUCKR**.
!  PRBREM() CONTAINS AMOUNT OF PROB REMOVED IN CUTTING TREE RECORD.
!----------
IF (ITRNRM.LE.MAXTRE) THEN
   DSTUMP(ITRNRM) = DBH
   ISHOOT(ITRNRM) = ISHI
   PRBREM(ITRNRM) = PREM
   JSHAGE(ITRNRM) = ISHAG
ELSE
   ITRNRM = MAXTRE
!----------
!  THE LIST IS FULL. FIND AN EXISTING RECORD THAT MATCHES AS BEST
!  IT CAN AND ADD THE PROB TO THAT RECORD. IF NO MATCH IS FOUND,
!  THEN IGNORE THE STUMP.
!----------
   MNAGDF = 9999
   IBEST  = 0
!
   DO I=1,ITRNRM
      IF (ISHI.EQ.ISHOOT(I)) THEN
         IF (ABS(ISHAG-JSHAGE(I)).LT.MNAGDF) THEN
            IBEST = I
            MNAGDF = ABS(ISHAG-JSHAGE(I))
         ENDIF
      ENDIF
      IF (MNAGDF.EQ.0) EXIT
   ENDDO
!
   IF (IBEST.GT.0) PRBREM(IBEST) = PRBREM(IBEST)+PREM
ENDIF
!
900 CONTINUE
!----------
!  DETERMINE IF QUAKING ASPEN WAS CUT; IF SO, ACCUMULATE BA AND TPA
!  OF ASPEN THAT WAS REMOVED FOR ESTIMATION OF NUMBER OF ASPEN SPROUTS
!  IN SUBROUTINE **ESUCKR**.
!----------
CALL ESASID(VARACD,INDXAS)
IF(JSSP .EQ. INDXAS)THEN
  ASTPAR = ASTPAR + PREM
  ASBAR = ASBAR + 0.0054542*PREM*DBH**2.
ENDIF
!
RETURN
END
