SUBROUTINE RPTWTR (NCYC2,IONER)
IMPLICIT NONE
!----------
! METRIC-PPBASE $Id$
!----------
!
!     PRINTS THE STAND COMPOSITION, AND SAMPLE TREE-STAND ATTRIBUTE
!     TABLES.
!
!     NOTE THAT THIS IS A REWRITE OF DISPLY, AND A POOR ONE AT THAT.
!
!     PART OF THE PARALLEL PROCESSING EXTENSION OF PROGNOSIS SYSTEM.
!     N.L. CROOKSTON--FORESTRY SCIENCES LAB, MOSCOW, ID--FEB 1982.
!
!     NCYC2 = CYCLE NUMBER.
!     IONER = A LIST OF POINTERS TO THE ELEMENTS THAT MAKE UP THE
!             OUTPUT FOR THE REPORT.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'PPEPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'OUTCOM.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'PPCNTL.f90'
!
!
INCLUDE 'METRIC.f90'
!
!
!OMMONS
!
!     STORAGE ALLOCATION:
!
INTEGER NCYC2,IC2,IPLACE,IOAGE,JYR,IRT,I,JSDI
INTEGER IONER(*)
!
REAL         ALL(15000),
INTEGER      ISNUMS(3000),ICYCS(3000),
INTEGER      LOCS(3000),IELTS(3000),IPTS(3000)
EQUIVALENCE (ALL(1),BFV(1)),(ALL(1),ISNUMS(1)), &
               (ALL(3001 ),ICYCS(1)), &
               (ALL(6001 ),LOCS (1)), &
               (ALL(9001 ),IELTS(1)), &
               (ALL(12001),IPTS (1))
!
!----------
!  DIMENSIONS FOR INTERNAL VARIABLES (USED AS OUTPUT LABELS):
!----------
CHARACTER*9 AT1,AT2,AT3,AT4
CHARACTER*10 STD(3)
!----------
!  DATA STATEMENTS:
!----------
DATA AT1/'REMOVAL  '/,AT2/'VOLUME:  '/,AT3/ &
    'RESIDUAL '/,AT4/'ACCRETION'/
!----------
!
!     IF OUTPUT IS CURRENTLY BEING PRINTED IN THE KEYWORD TABLE; THEN:
!     CLOSE THE KEYWRD TABLE IF OTHER MAJOR TABLES WILL BE PRINTED;
!     OTHERWISE LEAVE IT OPEN FOR MORE KEYWORDS.
!     NOTE: LFLAG=TRUE IF A NEW KEYWORD-TABLE HEADING IS NEEDED, AND
!     FALSE IF THE CURRENT OUTPUT IS PART OF THE KEYWORD TABLE.
!
IF (LFLAG) GOTO 20
IF (.NOT.(LSMPT.OR.LSNDCP)) GOTO 20
!
!     CLOSE KEYWORD TABLE AND INDECATE A NEW ONE WILL BE NEEDED.
!
WRITE (JOPPRT,10)
10 FORMAT (1X,130('-'))
LFLAG=.TRUE.
20 CONTINUE
!
!     CREATE THE REQUESTED REPORTS...LOOP THRU ALL CYCLES, INCLUDING
!     THE 'BEGINNING' AND 'ENDING' OUTPUTS.
!
DO 200 IC2=1,NCYC2
IPLACE=IONER(IC2)
IPTELS=IELTS(IPLACE)
IPLACE=LOCS(IPLACE)
!
IF (PDEBUG) WRITE (JOPPRT,25) IPLACE,IPTELS
25 FORMAT (/' RPTWTR CALLING GETPRT, IPLACE=',I5,'; IPTELS=',I5)
CALL GETPRT(IPLACE,JYR,IOAGE)
!
!     GETPRT SETS THE NECESSARY VARIABLES WHICH CONTROL WHICH WRITE
!     STMTS WILL BE USED BY THIS ROUTINE.  THE USER CONTROLS THE
!     VALUES OF LSNDCP, LSMPT, AND LCHEAPO, USING KEYWORDS.
!
IF (PDEBUG) WRITE (JOPPRT,26) LFLAG,LSTART,LSNDCP,LSMPT,ICL6
26 FORMAT (/' IN RPTWTR: LFLAG=',L2,'; LSTART=',L2,'; LSNDCP=',L2, &
           '; LSMPT=',L2,'; ICL6=',I5)
!
!     IF WE ARE AT THE 'BEGINNING' OUTPUT AND THE STAND COMPOSTION
!     TABLE HAS BEEN REQUESTED, THEN WRITE A HEADING.
!
IF (LSTART.AND.LSNDCP) &
       CALL GHEADS (NPLT,MGMID,JOPPRT,0,ITITLE)
!
!     IF EXAMPLE TREE/STAND ATTRIBUTE TABLE IS REQUESTED; THEN: WRITE
!     HEADER RECORD TO THE SCRATCH FILE.
!
IF (.NOT.LSTART .OR. .NOT.LSMPT) GOTO 30
IRT = 0
WRITE (JOTREE) IRT,NPLT,MGMID
30 CONTINUE
!----------
!   IF USER HAS SPECIFIED KEYWORDS THAT ALTER VOLUME EQUATION PARAMETERS
!   (IE VOLUMME BFVOLUME,ETC) THEN PRINT LABEL THAT INDICATES USER
!   SPECIFIED STANDARDS.
!----------
IF (LCVOLS) THEN
   STD(1)='USER TOTAL'
   STD(2)='USER MERCH'
ELSE
   STD(1)='TOTAL'
   STD(2)='MERCH'
ENDIF
!
IF (LBVOLS) THEN
   STD(3)='USER MERCH'
ELSE
   STD(3)='MERCH'
ENDIF
!
IF(ICL6.LT.0) GOTO 70
!
!     WRITE REMOVAL STATISTICS.  BYPASS IF LSTART IS TRUE OR NUMBER
!     OF TREES REMOVED WAS LESS THAN OR EQUAL TO ZERO.
!
IF (.NOT.LSNDCP) GOTO 60
IF(LSTART) GOTO 50
IF(ONTREM(7).LE.0.0) GOTO 40
WRITE (JOPPRT,9003)
9003 FORMAT(/)
WRITE(JOPPRT,9004) AT1,(ONTREM(I)*INtoCM,I=1,6), &
     ONTREM(7)/ACRtoHA,(OSPTT(I),IOSPTT(I),I=1,4)
9004 FORMAT(7X,A9,3X,5F7.1,F8.1,F9.0,' TREES   ', &
          3(F5.0,'% ',A3,','),F5.0,'% ',A3)
WRITE(JOSTND,9005) AT2,STD(1),(OCVREM(I)*INtoCM,I=1,6), &
     OCVREM(7)*FT3pACRtoM3pHA,(OSPTV(I),IOSPTV(I),I=1,4), &
     STD(2),(OMCREM(I)*INtoCM,I=1,6),OMCREM(7)*FT3pACRtoM3pHA
!
9005 FORMAT(7X,A9/9X,A10,5F7.1,F8.1,F9.0,' CU M    ', &
     3(F5.0,'% ',A3,','),F5.0,'% ',A3/ &
     9X,A10,5F7.1,F8.1,F9.0,' CU M    ', &
     3(F5.0,'% ',A3,','),F5.0,'% ',A3)
WRITE(JOSTND,9003)
WRITE(JOSTND,9004) AT3,(ONTRES(I)*INtoCM,I=1,6), &
     ONTRES(7)/ACRtoHA,(OSPRT(I),IOSPRT(I),I=1,4)
!
!     WRITE ACCRETION AND MORTALITY STATISTICS.  BYPASSED IF LSTART
!     IS TRUE.
!
40 CONTINUE
WRITE (JOPPRT,9003)
WRITE (JOPPRT,9006) AT4,(OACC(I)*INtoCM,I=1,6), &
     OACC(7)*FT3pACRtoM3pHA,(OSPAC(I),IOSPAC(I),I=1,4)
IF (LMORT) THEN
  WRITE(JOSTND,9006) 'USER MORT',(OMORT(I)*INtoCM,I=1,6), &
       OMORT(7)*FT3pACRtoM3pHA,(OSPMO(I),IOSPMO(I),I=1,4)
ELSE
  WRITE(JOSTND,9006) 'MORTALITY',(OMORT(I)*INtoCM,I=1,6), &
       OMORT(7)*FT3pACRtoM3pHA,(OSPMO(I),IOSPMO(I),I=1,4)
ENDIF
9006 FORMAT(7X,A9,3X,5F7.1,F8.1,F9.0,' CU M/YR ', &
          3(F5.0,'% ',A3,','),F5.0,'% ',A3)

!
!     WRITE CURRENT STAND STATISTICS.
!
50 CONTINUE
WRITE (JOPPRT,9003)
WRITE (JOPPRT,9007) JYR,(ONTCUR(I)*INtoCM,I=1,6), &
     ONTCUR(7)/ACRtoHA,(OSPCT(I),IOSPCT(I),I=1,4)
9007 FORMAT(/,1X,I4,'  TREES',T20,5F7.1,F8.1,F9.0,' TREES   ', &
          3(F5.0,'% ',A3,','),F5.0,'% ',A3)
WRITE(JOSTND,9005) AT2,STD(1),(OCVCUR(I),I=1,6), &
     OCVCUR(7)*FT3pACRtoM3pHA,(OSPCV(I),IOSPCV(I),I=1,4), &
     STD(2),(OMCCUR(I),I=1,6),OMCCUR(7)*FT3pACRtoM3pHA, &
     (OSPMC(I),IOSPMC(I),I=1,4)
60 CONTINUE
!
!     WRITE OUTPUT FOR SAMPLE TREES.  FIRST, OUTPUT STAND CONDITIONS
!     FOR PREVIOUS CYCLE.  BYPASS IF LSTART IS TRUE.
!
IF(LSTART) GOTO 100
70 CONTINUE
!
!     BYPASS WRITTING OF SAMPLE TREE DATA IF THE TABLE HAS BEEN
!     SURPRESSED BY THE USER.
!
IF (.NOT.LSMPT) GOTO 90
!
!     GOTO STATEMENT 80 AND WRITE BOTH PRE AND POST THINNING STATISTICS
!     IF THINNING OCCURRED IN PREVIOUS CYCLE.
!
JSDI=SDIBC + 0.5
IF(ONTREM(7).GT.0.0) GOTO 80
IRT=1
WRITE(JOTREE) IRT,IOAGE,ORMSQD*INtoCM,OLDTPA/ACRtoHA, &
     OLDBA*FT2pACRtoM2pHA,OLDAVH*FTtoM,RELDM1,JSDI
GOTO 90
80 CONTINUE
IRT=2
WRITE(JOTREE) IRT,IOAGE,ORMSQD*INtoCM,OLDTPA/ACRtoHA, &
     OLDBA*FT2pACRtoM2pHA,OLDAVH*FTtoM,RELDM1,JSDI
IRT=3
JSDI=SDIAC + 0.5
WRITE(JOTREE) IRT,ATAVD*INtoCM,ATTPA/ACRtoHA, &
     ATBA*FT2pACRtoM2pHA,ATAVH*FTtoM,ATCCF,JSDI
90 CONTINUE
!
!     IF THIS IS THE LAST OF THE OUTPUT, SKIP TO ECON DATA.
!
IF(ICL6.LT.0) GOTO 120
!
!     WRITE YEAR AND PERIOD LENGTH.
!
100 CONTINUE
IF (.NOT.LSMPT) GOTO 120

I=JYR
IF (IFST.NE.0) I=-I
IRT=4
WRITE(JOTREE) IRT,I,IFINT
!
!     WRITE EXAMPLE TREE DATA.
!
IRT=5
WRITE(JOTREE) IRT,IONSP,DBHIO*INtoCM,HTIO*FTtoM,IOICR, &
     DGIO*INtoCM,PCTIO,PRBIO
120 CONTINUE
130 CONTINUE
200 CONTINUE
IF (ICL6 .GT. 0) GO TO 150
!
!     PRINT THE EXAMPLE TREE RECORD AND STAND ATTRIBUTE TABLE.
!
IF (LSMPT) CALL PRTEXM (JOTREE,JOSTND,ITITLE)
150 CONTINUE
RETURN
END
