  SUBROUTINE FVSVOL
  USE MRULES_MOD
  IMPLICIT NONE
!----------
! VVOLUME $Id$
!----------
!
!  THIS SUBROUTINE CALLS THE VOLINIT ROUTINE TO ACCESS THE
!  THE NATIONAL CRUISE SYSTEM VOLUME LIBRARY FOR METHB OR METHC
!  EQUAL TO 5 (GEVORKIANTZ) OR 6. IT ALSO CONTAINS ENTRY POINTS
!  AT THE END FOR OTHER VARIANT-SPECIFIC SPECIAL VOLUME
!  CALCULATION METHODZ (METHB OR METHC = 8)
!----------
!OMMONS
!
INCLUDE 'PRGPRM.f90'
INCLUDE 'ARRAYS.f90'
INCLUDE 'COEFFS.f90'
INCLUDE 'CONTRL.f90'
INCLUDE 'PLOT.f90'
INCLUDE 'VOLSTD.f90'

COMMON/FVSVOLCOM/IREGN,FORST,VOLEQ,MTOPP,MTOPS,PROD
!
!OMMONS
!----------
CHARACTER*1 BFTOP,CFTOP,CTYPE,HTTYPE,LIVEDEAD
CHARACTER*2 FORST,PROD
CHARACTER*4 CONSPEC,FIASP
CHARACTER*11 EQNC,EQNB,VOLEQ
INTEGER CUTFLG,BFPFLG,CUPFLG,CDPFLG,SPFLG
INTEGER IT,ITRNC,ISPC,INTFOR,IERR,IZERO,FIASPCD
INTEGER I1,IREGN,IFC
INTEGER I,II,I3,I7,I15,I20,I21,I01,I02
INTEGER ITD,BADUM,SIDUM,HTTDUM,IDIST,TLOGS
INTEGER HTLOG,HTREF
REAL VMAX,BFMAX,BARK,BRATIO,H,D,BBF,BBFV,BV,VM,VN,VVN
REAL FC,DBTBH,TVOL1,TVOL2,TVOL4,TVOL7,TDIBB,TDIBC
REAL NOLOGP,NOLOGS
REAL BOLHT(21),LOGLEN(20),TVOL(15)
REAL HT1PRD,HT2PRD,MTOPP,MTOPS,STUMP,TOPDIAM
REAL XTOPD,HTC1,HTC2
REAL DRCOB,UPSHT1,UPSHT2,UPSD1,UPSD2,AVGZ1,AVGZ2,RCULL,PCULL
REAL TCF,MCF,SCF,CLMSTOP,RCRATIO,BRKHT
LOGICAL TKILL,CTKFLG,BTKFLG,LCONE,DEBUG
!----- New Variables added for 03/2023 Version of NVEL
INTEGER CRATIO,DECAY,MRULFLG,BRKTD,WDSTMS,PDECAY
REAL    BIODRY(15), BIOGRN(15), BIODRYIN(15)
TYPE(MERCHRULES)::MERRLS

!----------
!  NATIONAL CRUISE SYSTEM ROUTINES (METHOD = 6)
!----------
ENTRY NATCRS (TCF,MCF,SCF,BBFV,ISPC,D,H,TKILL, &
                 CRATIO,BARK,ITRNC,VMAX,BFMAX, &
                 RCULL,DECAY,WDSTMS,BIODRYIN, &
                 LIVEDEAD,CTKFLG,BTKFLG,IT)
!-----------
!  SEE IF WE NEED TO DO SOME DEBUG.
!-----------

MRULFLG = 0
BRKHT   = 0
BRKTD   = 0
TCF     = 0
MCF     = 0
SCF     = 0
BBFV    = 0
CLMSTOP = 0
PCULL   = 0
PDECAY  = 0
IREGN   = 0
VMAX    = 0
BFMAX   = 0
RCRATIO = FLOAT(CRATIO)
IF(LFIANVB) THEN
  PCULL  = RCULL
  PDECAY = DECAY
ENDIF
IDIST   = 1
VOLEQ   = VEQNNC(ISPC)
CALL FORMCL(ISPC,IFOR,D,FC)
IFC=IFIX(FC)
READ(FIAJSP(ISPC), '(I4)')FIASPCD
IF ((LFIANVB .OR. VOLEQ(1:3) .EQ. "NVB") .AND. &
        TKILL .AND. LIVEDEAD .EQ. 'L') THEN
  BRKHT = FLOAT(ITRNC)/100
ENDIF

IF(KODFOR.GT.10000)THEN
  IREGN = KODFOR/10000
  INTFOR=KODFOR/100-IREGN*100
ELSE
  IREGN = KODFOR/100
  INTFOR = KODFOR - (KODFOR/100)*100
ENDIF

IF(VARACD.EQ.'PN' .OR. VARACD.EQ.'OP')THEN
  IF(IREGN.EQ.8)THEN
    IREGN=6
    INTFOR=9
  ENDIF
ELSEIF(VARACD.EQ.'NC')THEN
  IF(IREGN.EQ.8)THEN
    IREGN=5
    INTFOR=10
  ENDIF
ELSEIF(VARACD.EQ.'SO')THEN
  IF(IREGN.EQ.7)THEN
    SELECT CASE (KODFOR)
    CASE (701)
      IREGN=5
      INTFOR=5
    CASE (799)
      IREGN=6
      INTFOR=1
    END SELECT
  ENDIF
ENDIF

IF(LFIANVB) THEN
  SELECT CASE (FIASPCD)
    CASE (62,  63,  65,  66, 69, 106, 133, 134, &
             143, 321, 322, 475, 803, 810, 814, 843)
      IFC = WDSTMS
      SELECT CASE (ISTATE)
        CASE (4)
          IREGN = 3
        CASE (16, 32)
          IREGN = 4
        CASE (6)
          IREGN = 5
        CASE (41, 53)
          IREGN = 6
        END SELECT
  END SELECT
END IF

CALL DBCHK (DEBUG,'FVSVOL',6,ICYC)
IF(DEBUG) WRITE(JOSTND,3)ICYC,IFOR
3 FORMAT(' ENTERING SUBROUTINE FVSVOL CYCLE,IFOR =',I5,i4)
IF(DEBUG)WRITE(JOSTND,*)' ENTERING NATCRS ISPC,D,H,TKILL,BARK,', &
   'ITRNC,CTKFLG,BTKFLG,IT= ',ISPC,D,H,TKILL,BARK,ITRNC,CTKFLG, &
    BTKFLG,IT

IF(VARACD.EQ.'SN')IDIST=KODFOR-(KODFOR/100)*100

WRITE(FORST,'(I2)')INTFOR
IF(INTFOR.LT.10)FORST(1:1)='0'
WRITE(FIASP,('(A)'))JSP(ISPC)
HTTYPE='F'
IERR=0
DBTBH = D*(1-BARK)
IF(DEBUG)WRITE(JOSTND,*)' INTFOR, IREGN= ',INTFOR, IREGN
DO 100 IZERO=1,15
TVOL(IZERO)=0.
BIODRY(IZERO)=0.
BIODRYIN(IZERO)=0.
BIOGRN(IZERO)=0.
100 CONTINUE
!
!  REGION 9 INPUTS OUTSIDE-BARK TOP DIAMETERS TO VOLINIT
!  REGION 8 DOES NOT CARE, TOP DIAMETERS ARE HARD WIRED
!  WESTERN VARIANTS INPUT INSIDE-BARK TOP DIAMETERS
!  MTOPP (primary product - CuFt, Sawlog)
!  MTOPS (secondary product - Cuft, Pulpwood)
!
IF((IREGN.EQ.8).OR.(IREGN.EQ.9).OR.LFIANVB)THEN
  MTOPP=SCFTOPD(ISPC)
  MTOPS=TOPD(ISPC)
ELSE
  MTOPS=TOPD(ISPC)*BARK
ENDIF
!----------
!  CALL TO VOLUME INTERFACE - VOLINIT - CUBIC VOLUMES
!  INITIALIZE CONSTANT ARGUMENTS, AND VARIABLES
!----------
IF(DEBUG) WRITE(JOSTND,*) &
     'IREGN,ISPC,D,BFMIND,DBHMIN,MTOPP,MTOPS = ', &
     IREGN,ISPC,D,BFMIND(ISPC),DBHMIN(ISPC),MTOPP,MTOPS

VOLEQ=VEQNNC(ISPC)
STUMP=STMP(ISPC)
PROD='02'

!     Setting top diameter spec for calculating height to diameter for
!     Merch CuFt.
!     Region 5 uses inside bark diameter,
!     Region 9 computes a saw timber CuFt, VOL(4),
!     other regions need top diameter set at secondary product for this
!     step of process. That is why TOPDIAM for Region 9 is set to MTOPP
!     here which is the saw timber spec instead of typical CuFt spec, MTOPS.
!
IF(.NOT.LFIANVB .AND. IREGN.EQ.5) THEN
  TOPDIAM=TOPD(ISPC)*BARK
ELSE
  TOPDIAM=MTOPS
ENDIF

DBTBH = D*(1-BARK)

IF((LFIANVB .OR. IREGN.EQ.9 .OR. IREGN.EQ.8) &
       .AND. D.GE.SCFMIND(ISPC))THEN
  STUMP=SCFSTMP(ISPC)
  TOPDIAM=MTOPP
  PROD='01'
ENDIF
!
!       Tree DBH meets min merch for Pulp/CuFT only
!

!      I1=0     ! no longer in use a.o. 10/28/2022 to prevent address space pollution
I3=3      ! second dimension of LOGDIA(,x) array
I7=7      ! first dimension of LOGVOL(x,) array
I15=15    ! Dimension of VOL(x) array
I20=20    ! second dimension of LOGVOL(,x) array, dimension of LOGLEN(x)
I21=21    ! first dimension of LOGDIA(x,) array, dimension of BOLHT(x)

!     Initialize independant volinit variables to prevent shared address space
HTLOG = 0 ! Replaces I1 in position 11 of volinit call
HTREF = 0 ! Replaces I1 in position 18 of volinit call

DRCOB = 0.  ! Replaces X1 in position 08 of volinit call
UPSHT1 = 0. ! Replaces X1 in position 14 of volinit call
UPSHT2 = 0. ! Replaces X1 in position 15 of volinit call
UPSD1 = 0.  ! Replaces X1 in position 16 of volinit call
UPSD2 = 0.  ! Replaces X1 in position 17 of volinit call
AVGZ1 = 0.  ! Replaces X1 in position 19 of volinit call
AVGZ2 = 0.  ! Replaces X1 in position 20 of volinit call

!     INITIALIZE ARRAYS LOADED BY VOLUME ROUTINES (NVEL)
!     DIMENSIONS BASED ON VARIABLES SET DIRECTLY ABOVE
DO I=1,I21
  DO II=1,I3
    LOGDIA(I,II)=0.0
  ENDDO
  BOLHT(I)=0.0
ENDDO
DO I=1,I20
  DO II=1,I7
    LOGVOL(II,I)=0.0
  ENDDO
  LOGLEN(I)=0.0
ENDDO

!----------
!  CONSTANT CHARACTER ARGUMENTS
!----------
CTYPE=CFCTYPE
!----------
!  PRODUCT FLAGS
!----------
!  TOAL CUBIC
CUTFLG=1
!  BF
BFPFLG=0
IF((IREGN.EQ.9 .OR. IREGN.EQ.8) .AND. &
       (D.GE.BFMIND(ISPC)) .AND. &
       (VEQNNB(ISPC) .EQ. VEQNNC (ISPC)) .AND. &
       (BFMIND(ISPC) .EQ. SCFMIND(ISPC)) .AND. &
       (BFSTMP(ISPC) .EQ. SCFSTMP(ISPC)) .AND. &
       (BFTOPD(ISPC) .EQ. SCFTOPD(ISPC))) BFPFLG=1
!  MERCH CUBIC
CUPFLG=1
!  CORDWOOD
CDPFLG=0
!  SECONDARY PRODUCT
SPFLG=0
IF((LFIANVB .OR. IREGN.EQ.9 .OR. IREGN.EQ.8) .AND. &
       D.GE.SCFMIND(ISPC)) SPFLG=1

TLOGS = 0
NOLOGP = 0.
NOLOGS = 0.
HT1PRD=0.
HT2PRD=0.
IERR=0
SIDUM=0
BADUM=0
HTTDUM=0
CONSPEC='    '

IF(DEBUG)WRITE(JOSTND,*) &
    'CALLING VOLINIT CF ISPC,IREGN,FORST,VOLEQ = ', &
                         ISPC,IREGN,FORST,VOLEQ
IF(DEBUG)WRITE(JOSTND,*) &
    '  TOPDIAM,MTOPS,STUMP,D,DRCOB,HTTYPE,H,I1 = ', &
       TOPDIAM,MTOPS,STUMP,D,DRCOB,HTTYPE,H,I1
IF(DEBUG)WRITE(JOSTND,*)'  HT1PRD,HT2PRD,IFC,DBTBH,BARK = ', &
                              HT1PRD,HT2PRD,IFC,DBTBH,BARK
IF(DEBUG)WRITE(JOSTND,*)'  CUTFLG,BFPFLG,CUPFLG,CDPFLG,SPFLG = ', &
                              CUTFLG,BFPFLG,CUPFLG,CDPFLG,SPFLG
IF(DEBUG)WRITE(JOSTND,*) &
    '  CONSPEC=',CONSPEC,' PROD=',PROD,' HTTDUM=',HTTDUM, &
    ' LIVEDEAD=',LIVEDEAD,' BADUM=',BADUM,' SIDUM= ',SIDUM
IF(DEBUG)WRITE(JOSTND,*)'  CTYPE,IERR,IDIST = ', &
                              CTYPE,IERR,IDIST

!     It does not appear that the secondary product top diameter MTOPS,
!     5th argument, functions. So it is used in primary product position on
!     this call to compute the height to merch cubic top diameter. Region 5
!     is a special case and so TOPDIAM is set above.

CALL VOLINITNVB(IREGN,FORST,VOLEQ,TOPDIAM,MTOPS,STUMP,D, &
      DRCOB,HTTYPE,H,HTLOG,HT1PRD,HT2PRD,UPSHT1,UPSHT2,UPSD1,UPSD2, &
      HTREF,AVGZ1,AVGZ2,IFC,DBTBH,BARK*100,RCRATIO,PCULL,PDECAY, &
      TVOL,LOGVOL,LOGDIA,LOGLEN,BOLHT,TLOGS,NOLOGP,NOLOGS,CUTFLG, &
      BFPFLG,CUPFLG,CDPFLG,SPFLG,CONSPEC,PROD,HTTDUM,LIVEDEAD, &
      BADUM,SIDUM,CTYPE,IERR,IDIST,BRKHT,BRKTD,FIASPCD,BIODRY, &
      BIOGRN,MRULFLG,MERRLS,CLMSTOP)
!
IF(DEBUG)WRITE(JOSTND,*) &
    'AFTER VOLINIT CF IERR,PROD,HT1PRD,HT2PRD = ', &
                      IERR,PROD,HT1PRD,HT2PRD
IF(DEBUG)WRITE(JOSTND,*)'   TVOL = ',TVOL
IF(DEBUG)WRITE(JOSTND,*)'   LOGVOL= ',LOGVOL
IF(DEBUG)WRITE(JOSTND,*)'   LOGDIA= ',LOGDIA
IF(DEBUG)WRITE(JOSTND,*)'   LOGLEN= ',LOGLEN
IF(DEBUG)WRITE(JOSTND,*)'   BOLHT,TLOGS,NOLOGP,NOLOGS= ', &
                               BOLHT,TLOGS,NOLOGP,NOLOGS

!----------
!  STORE CALCULATED MERCH CUBIC HEIGHT
!                               West     East
!  Primary product (HT1PRD):    BdFt     Sawlog
!  Secondary Product (HT2PRD):  CuFt     Pulpwood
!
!  While working on this routine 5/24/2017, using default volume equation
!  assignments, Region 9 (Variants CS, LS, NE) is the only one that
!  returns value in HT2PRD, others are captured from HT1PRD with the
!  merch CuFt top diameter set for primary product (volinit 4th argument).
!----------
!  Old R8, pulpwood process no longer needed, need to store pulp ht here
!    -DW August 2022
!----------

IF(IT.GT.0 .AND. D.GE.DBHMIN(ISPC)) THEN
  HT2TD(IT,2)=MAX(HT1PRD, HT2PRD)
  IF (BFPFLG.EQ.1) HT2TD(IT,1)=HT1PRD

!     Region 8 requires at least 10 feet of product from the tree
!     for the tree volume to be included.
  IF(IREGN.EQ.8 .AND. PROD.EQ.'01' .AND. HT1PRD.LT.10.)THEN
    TVOL(4)=0.
    TVOL(2)=0.
    ENDIF
  ENDIF

IF(LFIANVB) BIODRYIN = BIODRY



!----------
!  END OF CF SECTION
!----------

!  IF THE BF VOLUME EQUATION IS DIFFERENT THAN THE CF VOLUME EQ OR
!  THE TOP DIAMETER SPECIFICATION FOR THE CUFT AND BDFT PRODUCTS
!  ARE DIFFERENT, THEN STORE CUBIC VOLUMES AND CALL  VOLINIT AGAIN
!  TO CALCULATE BF VOLUMES ONLY
!----------
IF(BFPFLG.EQ.0 .AND. D.GE.BFMIND(ISPC))THEN
  TVOL1=TVOL(1)
  TVOL4=TVOL(4)
  TVOL7=TVOL(7)
  VOLEQ=VEQNNB(ISPC)

!       Region 8 Clark equation needs saw timber top diameter spec
!       inserted into equation identification.
!        IF(IREGN.EQ.8 .AND. VOLEQ(4:6).EQ.'CLK')THEN
!          WRITE(BFTOP,'(I1)')NINT(BFTOPD(ISPC))
!          VOLEQ(3:3)=BFTOP
!        ENDIF
  DO IZERO=1,15
  TVOL(IZERO)=0.
  ENDDO

  STUMP=BFSTMP(ISPC)
  IF(IREGN.EQ.8 .OR. IREGN.EQ.9) THEN
    MTOPP=BFTOPD(ISPC)
  ELSE
    MTOPP=BFTOPD(ISPC)*BARK
  END IF
  PROD='01'
!       I1=0 ! no longer in use a.o. 10/28/2022 to prevent address space pollution
  I3=3
  I7=7
  I15=15
  I20=20
  I21=21

!     Initialize independant volinit variables to prevent shared address space
HTLOG = 0 ! Replaces I1 in position 11 of volinit call
HTREF = 0 ! Replaces I1 in position 18 of volinit call

DRCOB = 0.  ! Replaces X1 in position 08 of volinit call
UPSHT1 = 0. ! Replaces X1 in position 14 of volinit call
UPSHT2 = 0. ! Replaces X1 in position 15 of volinit call
UPSD1 = 0.  ! Replaces X1 in position 16 of volinit call
UPSD2 = 0.  ! Replaces X1 in position 17 of volinit call
AVGZ1 = 0.  ! Replaces X1 in position 19 of volinit call
AVGZ2 = 0.  ! Replaces X1 in position 20 of volinit call
!----------
!  CONSTANT CHARACTER ARGUMENTS
!----------
  CTYPE=BFCTYPE
!----------
!  PRODUCT FLAGS
!----------
!  TOAL CUBIC
  CUTFLG=1
!  BF
  BFPFLG=1
!  MERCH CUBIC
  CUPFLG=1
!  CORDWOOD
  CDPFLG=0
!  SECONDARY PRODUCT
  SPFLG=0
!  CONSTANTS
  TLOGS = 0
  NOLOGP = 0.
  NOLOGS = 0.
  IF((IREGN.NE.8) &
        .AND.(VOLEQ(4:6).NE.'DVE'))THEN
    HT1PRD=0.
    HT2PRD=0.
  ENDIF
  IF((IREGN.EQ.8).AND.(VOLEQ(4:6).EQ.'CLK'))THEN
    HT1PRD=0.
    HT2PRD=0.
  ENDIF
  IERR    = 0
  SIDUM   = 0
  BADUM   = 0
  HTTDUM  = 0
  CONSPEC = '   '
  HT1PRD  = 0.
  HT2PRD  = 0.
  PCULL   = 0
  PDECAY  = 0
!----------
!  GET FORM CLASS FOR THIS TREE.
!----------
  CALL FORMCL(ISPC,IFOR,D,FC)
  IFC=IFIX(FC)

DBTBH = D*(1-BARK)

IF(DEBUG)WRITE(JOSTND,*) &
    'CALLING VOLINIT BF ISPC,IREGN,FORST,VOLEQ = ', &
                         ISPC,IREGN,FORST,VOLEQ
IF(DEBUG)WRITE(JOSTND,*) &
    '  MTOPP,MTOPS,STUMP,D,DRCOB,HTTYPE,H,I1 = ', &
       MTOPP,MTOPS,STUMP,D,DRCOB,HTTYPE,H,I1
IF(DEBUG)WRITE(JOSTND,*)'  HT1PRD,HT2PRD,IFC,DBTBH,BARK = ', &
                              HT1PRD,HT2PRD,IFC,DBTBH,BARK
IF(DEBUG)WRITE(JOSTND,*)'  CUTFLG,BFPFLG,CUPFLG,CDPFLG,SPFLG = ', &
                              CUTFLG,BFPFLG,CUPFLG,CDPFLG,SPFLG
IF(DEBUG)WRITE(JOSTND,*) &
    '  CONSPEC=',CONSPEC,' PROD=',PROD,' HTTDUM=',HTTDUM, &
    ' LIVEDEAD=',LIVEDEAD,' BADUM=',BADUM,' SIDUM= ',SIDUM
IF(DEBUG)WRITE(JOSTND,*)'  CTYPE,IERR,IDIST = ', &
                              CTYPE,IERR,IDIST

  CALL VOLINITNVB(IREGN,FORST,VOLEQ,MTOPP,MTOPS,STUMP,D, &
      DRCOB,HTTYPE,H,HTLOG,HT1PRD,HT2PRD,UPSHT1,UPSHT2,UPSD1,UPSD2, &
      HTREF,AVGZ1,AVGZ2,IFC,DBTBH,BARK*100,RCRATIO,PCULL,PDECAY, &
      TVOL,LOGVOL,LOGDIA,LOGLEN,BOLHT,TLOGS,NOLOGP,NOLOGS,CUTFLG, &
      BFPFLG,CUPFLG,CDPFLG,SPFLG,CONSPEC,PROD,HTTDUM,LIVEDEAD, &
      BADUM,SIDUM,CTYPE,IERR,IDIST,BRKHT,BRKTD,FIASPCD,BIODRY, &
      BIOGRN,MRULFLG,MERRLS,CLMSTOP)

IF(DEBUG)WRITE(JOSTND,*) &
    'AFTER VOLINIT BF IERR,PROD,HT1PRD,HT2PRD= ', &
                      IERR,PROD,HT1PRD,HT2PRD
IF(DEBUG)WRITE(JOSTND,*)'   TVOL = ',TVOL
IF(DEBUG)WRITE(JOSTND,*)'   LOGVOL= ',LOGVOL
IF(DEBUG)WRITE(JOSTND,*)'   LOGDIA= ',LOGDIA
IF(DEBUG)WRITE(JOSTND,*)'   LOGLEN= ',LOGLEN
IF(DEBUG)WRITE(JOSTND,*)'   BOLHT,TLOGS,NOLOGP,NOLOGS= ', &
                               BOLHT,TLOGS,NOLOGP,NOLOGS

  IF(D.GE.BFMIND(ISPC))THEN
    IF(IT.GT.0)HT2TD(IT,1)=HT1PRD
  ELSE
    IF(IT.GT.0)HT2TD(IT,1)=0.0
    TVOL(2)=0.0
  ENDIF
!
!  WHEN THERE IS NO CF VOL. EQ. NO. (E.G. CF METHC=2 OR 3, AND CFVOL
!  OR OCFVOL IS CALLED FROM VOLS, MUST SET VMAX SO TRUNCATED VOLUMES
!  ARE CALCULATED
!
  BFMAX  =TVOL(1)
  TVOL(1)=TVOL1
  TVOL(4)=TVOL4
  TVOL(7)=TVOL7
  IF((IREGN.EQ.8).AND.(HT1PRD.LT.10.))THEN
    TVOL(4)=0.
    TVOL(2)=0.
  ENDIF
ENDIF                   ! END OF BF SECTION
500 CONTINUE
!----------
!  SET RETURN VALUES.
!----------
  TCF=TVOL(1)
  IF(TCF.LT.0.)TCF=0.
  VMAX=TCF
  IF(BFMAX.EQ.0) BFMAX=VMAX
  IF(D .GE. DBHMIN(ISPC)) MCF=TVOL(4) + TVOL(7)
  IF(MCF.LT.0.)MCF=0.
  IF((IREGN.EQ.8 .OR. IREGN.EQ.9 .OR. LFIANVB) &
        .AND. (D .GE. SCFMIND(ISPC)))THEN
    SCF = TVOL(4)
  ENDIF

IF(D.LT.BFMIND(ISPC))THEN
  BBFV=0.
ELSE
  IF(METHB(ISPC).EQ.9) THEN
    BBFV=TVOL(10)
  ELSE
    BBFV=TVOL(2)
  ENDIF
  IF(BBFV.LT.0.)BBFV=0.
ENDIF
IF(DEBUG)WRITE(JOSTND,*)'  IN FVSVOL D, VN, VM, VMAX, BBFV = ', &
                               D, VN, VM, VMAX, BBFV
CTKFLG = .TRUE.
BTKFLG = .TRUE.
RETURN
!
!
!----------
!  ENTER ANY OTHER CUBIC HERE
!----------
ENTRY OCFVOL (VN,VM,ISPC,D,H,TKILL,BARK,ITRNC,VMAX,LCONE, &
                 CTKFLG,IT)
CALL DBCHK (DEBUG,'FVSVOL',6,ICYC)
IF(DEBUG) WRITE(JOSTND,13)ICYC,IFOR
13 FORMAT(' ENTERING FVSVOL-OCFVOL CYCLE,IFOR =',I5,I4)
IF(DEBUG)WRITE(JOSTND,*)'  ARGUMENTS: VN,VM, &
   ISPC,D,H,TKILL,BARK,ITRNC,VMAX,LCONE,CTKFLG,IT'
IF(DEBUG)WRITE(JOSTND,*)'  OCFVOL IN:  ', &
    VN,VM,ISPC,D,H,TKILL,BARK,ITRNC,VMAX,LCONE,CTKFLG,IT

VVN=0.0
BBF=0.0
!
SELECT CASE (VARACD)
  CASE ('AK')
    CALL FVSBRUCEDEMARS(VN,VM,VMAX,D,H,ISPC,BARK,LCONE,CTKFLG)
!
  CASE ('CR')
    CALL FVSHANNBARE(VN,VM,VMAX,ISPC,D,H,CTKFLG)
!
  CASE ('NC')
    CALL FVSSIERRALOG(VN,VM,VMAX,ISPC,D,H,BARK,LCONE,CTKFLG)
!
  CASE ('CS','LS','NE')
    VN=0.
    VM=0.
    IF (IMC(IT) .GE. 3 .OR. D .LT. DBHMIN(ISPC))GOTO 600
    CALL TWIGCF(ISPC,H,D,VN,VM,IT)
600     CONTINUE
!
  CASE DEFAULT
    VN=0.
    VMAX=0.
    VM=0.
    CTKFLG = .FALSE.
!
END SELECT
!----------
!  SET RETURN VALUES HERE
!----------
CTKFLG = .TRUE.
IF(VN.LE.0.)THEN
  VN=0.
  CTKFLG = .FALSE.
ENDIF
IF(VM.LE.0.)THEN
  VM=0.
ENDIF
VMAX=VN
IF(DEBUG)WRITE(JOSTND,*)'  OCFVOL OUT: ', &
    VN,VM,ISPC,D,H,TKILL,BARK,ITRNC,VMAX,LCONE,CTKFLG,IT
RETURN
!
!
!----------
!  ENTER ANY OTHER BOARD HERE.
!----------
ENTRY OBFVOL (BBFV,ISPC,D,H,TKILL,BARK,ITRNC,VMAX,LCONE, &
                 BTKFLG,IT)
CALL DBCHK (DEBUG,'FVSVOL',6,ICYC)
IF(DEBUG) WRITE(JOSTND,23)ICYC,IFOR
23 FORMAT(' ENTERING FVSVOL-OBFVOL CYCLE,IFOR =',I5,I4)
IF(DEBUG)WRITE(JOSTND,*)'  ARGUMENTS: ', &
   'BBFV,ISPC,D,H,TKILL,BARK,ITRNC,VMAX,LCONE,BTKFLG,IT'
IF(DEBUG)WRITE(JOSTND,*)'  OBFVOL IN:  ', &
    BBFV,ISPC,D,H,TKILL,BARK,ITRNC,VMAX,LCONE,BTKFLG,IT
!
SELECT CASE (VARACD)
  CASE ('AK')
    VVN=0.0
    BBF=0.0
    IF(D .GE. 9.0 .AND. H .GT. 40.0) &
       CALL FVSOLDGRO(ISPC,VVN,D,H,BBF)
    BBFV=BBF
!
  CASE ('CR')
    CALL HANNBAREBF(BBFV,ISPC,D,H,VMAX,BTKFLG)
!
  CASE ('NC')
    ITD=INT(BFTOPD(ISPC)+0.5)
    IF(ITD.GT.100) ITD = 100
    CALL LOGS(D,H,ITD,ITD,DBHMIN(ISPC),BFMIND(ISPC),ISPC, &
               BFSTMP(ISPC),BV,JOSTND)
    BBFV=BV
!
  CASE ('CS','LS','NE')
    BBFV=0.
    IF(D .LT. BFMIND(ISPC) .OR. IMC(IT) .GT. 1)GOTO 700
    CALL TWIGBF(ISPC,H,D,VMAX,BBFV)
700     CONTINUE
!
  CASE DEFAULT
    BBFV=0.
!
END SELECT
!
BTKFLG = .TRUE.
IF(BBFV .LE. 0.) THEN
  BBFV=0.
  BTKFLG=.FALSE.
ENDIF
IF(DEBUG)WRITE(JOSTND,*)'  OBFVOL OUT: ', &
    BBFV,ISPC,D,H,TKILL,BARK,ITRNC,VMAX,LCONE,BTKFLG,IT
RETURN
!
!
!----------
!  ENTRY POINT FOR SENDING VOLUME EQN NUMBER TO THE FVS-TO-NATCRZ ROUTINE
!----------
ENTRY GETEQN(ISPC,D,H,EQNC,EQNB,TDIBC,TDIBB)
CALL DBCHK (DEBUG,'FVSVOL',6,ICYC)
IF(DEBUG) WRITE(JOSTND,33)ICYC,IFOR
33 FORMAT(' ENTERING FVSVOL-GETEQN CYCLE,IFOR =',I5,I4)
IF(DEBUG)WRITE(JOSTND,*)'  ARGUMENTS: ', &
   'ISPC,D,H,EQNC,EQNB,TDIBC,TDIBB'
IF(DEBUG)WRITE(JOSTND,*)'  GETEQN IN:  ', &
    ISPC,D,H,EQNC,EQNB,TDIBC,TDIBB

EQNC=VEQNNC(ISPC)
EQNB=VEQNNB(ISPC)
TDIBC=TOPD(ISPC)*BRATIO(ISPC,D,H)
TDIBB=BFTOPD(ISPC)*BRATIO(ISPC,D,H)

IF(DEBUG)WRITE(JOSTND,*)'  GETEQN OUT: ', &
    ISPC,D,H,EQNC,EQNB,TDIBC,TDIBB
RETURN

END
