SUBROUTINE ESSPRT(VAR,ISPC,NSPT,PREM,DSTMP)
IMPLICIT NONE
!----------
! VESTB $Id$
!----------
!  THIS SUBROUTINE CONTAINS ENTRY POINTS TO HANDLE COMPUTATIONS FOR
!  VARIOUS STUMP SPROUTING FUNCTIONS WHICH VARY BY VARIANT AND
!  SPECIES.
!
!  VARIANTS USING THE ESTB VERSION: AK, CI, EM, IE, KT, NI
!----------
!
!OMMONS
!
!  NO COMMON BLOCKS ARE CURRENTLY NEEDED.
!
!OMMONS
!----------
!  DEFINITIONS
!
!     PREM -- NUMBER OF SPROUTS PER SPROUT RECORD
!    DSTMP -- DIAMETER OF PARENT TREE
!----------
!----------
CHARACTER VAR*2
INTEGER IAG,INDXAS,ISHAG,ISPC,NMSPRC,NSPT
REAL ASTPAR,ASBAR,HTSPRT,PREM,RSHAG,SI,SPA,TREES,DSTMP
INTEGER IDANUW
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
IDANUW = NSPT
!----------
!  VARIANT AND SPECIES SPECIFIC RULES FOR DETERMINING TPA A SPROUT
!  RECORD WILL REPRESENT. ASPEN IS HANDLED SEPERATELY IN ENTRY ASSPTN
!  PREM = TPA OF PARENT TREE OF SPROUT RECORD
!----------
SELECT CASE (VAR)
!
CASE('AK')
  SELECT CASE(ISPC)
    CASE(14,15)
      IF(DSTMP.LT.25.9)THEN
        PREM = PREM * ((99.9999-3.8462 * DSTMP)/100)
      ELSE
        PREM = 0.
      ENDIF
    CASE(16,17)
      IF(DSTMP.LT.6.0)THEN
        PREM = PREM * 0.92
      ELSE IF(DSTMP.GE.6.0.AND.DSTMP.LT.9.0)THEN
        PREM = PREM * (-0.13333 * DSTMP + 1.70)
      ELSE
        PREM = PREM * 0.50
      ENDIF
    CASE(18,20)
      IF(DSTMP.LT.6.25)THEN
        PREM = PREM * 0.39
      ELSE IF(DSTMP.GE.6.25.AND.DSTMP.LT.8.75)THEN
        PREM = PREM * 0.32
      ELSE
        PREM = PREM * 0.25
      ENDIF
    CASE(21,22)
      PREM = PREM * 0.90
    CASE DEFAULT
      PREM = PREM * 1.
  END SELECT
!
CASE('IE')
  SELECT CASE(ISPC)
    CASE(17)
      PREM = PREM * 0.40
    CASE(19)
      PREM = PREM * 0.90
    CASE(20,21)
      PREM = PREM * 0.70
    CASE DEFAULT
      PREM = PREM * 1.
    END SELECT
!
CASE('CI')
  SELECT CASE(ISPC)
    CASE(12)
      PREM = PREM * 0.40
    CASE(17)
      PREM = PREM * 0.90
    CASE DEFAULT
      PREM = PREM * 1.
  END SELECT
!
CASE('EM')
  SELECT CASE(ISPC)
    CASE(11)
      IF(DSTMP.LE.12.0)THEN
        PREM = PREM * 0.80
      ELSE
        PREM = PREM * 0.50
      ENDIF
    CASE(13,15)
      PREM = PREM * 0.90
    CASE(14)
      IF(DSTMP.LE.25.0)THEN
        PREM = PREM * 0.80
      ELSE
        PREM = PREM * 0.50
      ENDIF
    CASE(16)
      PREM = PREM * 0.80
    CASE(17)
      PREM = PREM * 0.70
  END SELECT
!----------
!  ALL OTHER VARIANTS & SPECIES
!----------
CASE DEFAULT
  PREM = PREM * 1.
!
END SELECT
RETURN
!
!
ENTRY ESASID(VAR,INDXAS)
!----------
!  THIS SUBROUTINE DETERMINES IF QUAKING ASPEN IS IN THIS VARIANT;
!  IF SO, RETURN THE FVS SPECIES INDEX FOR ASPEN IN THIS VARIANT;
!  OTHERWISE RETURN 9999.
!----------
!  DEFINITIONS
!
!   INDXAS -- QUAKING ASPEN SPECIES NUMBER
!----------
SELECT CASE (VAR)
!
CASE('AK')
  INDXAS = 19
!
CASE('CI')
  INDXAS = 13
!
CASE('EM')
  INDXAS = 12
!
CASE('IE')
  INDXAS = 18
!
CASE DEFAULT
  INDXAS = 9999
!
END SELECT
RETURN
!
!
ENTRY NSPREC (VAR,ISPC,NMSPRC,DSTMP)
!----------
!  THIS SUBROUTINE DETERMINES THE NUMBER OF SPROUT RECORDS TO CREATE.
!----------
!  DEFINITIONS
!
!   NMSPRC -- NUMBER OF SPROUT RECORDS TO CREATE
!    DSTMP -- DIAMETER OF PARENT TREE
!----------
SELECT CASE (VAR)
!----------
!  SET TO 1 FOR: CI - PACIFIC YEW (12)
!                IE - PACIFIC YEW (17)
!
!  OTHERWISE SET TO 2
!
!----------
CASE('AK')
  SELECT CASE (ISPC)
  CASE(18,20)
    IF(DSTMP.LT.5.0)THEN
      NMSPRC = 1
    ELSE IF(DSTMP.GE.5.0.AND.DSTMP.LT.10.0)THEN
      NMSPRC = NINT(-1.0 + 0.4 * DSTMP)
    ELSE
      NMSPRC = 3
    ENDIF
  CASE(19)
    NMSPRC = 2
  CASE DEFAULT
    NMSPRC = 1
  END SELECT
!
CASE('CI')
  SELECT CASE (ISPC)
  CASE(12)
    NMSPRC = 1
  CASE(13)
    NMSPRC = 2
  CASE(17)
    IF(DSTMP.LT.5.0)THEN
      NMSPRC = 1
    ELSE IF(DSTMP.GE.5.0.AND.DSTMP.LT.10.0)THEN
      NMSPRC = NINT(-1.0 + 0.4 * DSTMP)
    ELSE
      NMSPRC = 3
    ENDIF
  CASE DEFAULT
    NMSPRC = 1
  END SELECT
!
CASE('EM')
  SELECT CASE (ISPC)
  CASE(12)
    NMSPRC = 2
  CASE(13:16)
    IF(DSTMP.LT.5.0)THEN
      NMSPRC = 1
    ELSE IF(DSTMP.GE.5.0.AND.DSTMP.LT.10.0)THEN
      NMSPRC = NINT(-1.0 + 0.4 * DSTMP)
    ELSE
      NMSPRC = 3
    ENDIF
  CASE DEFAULT
    NMSPRC = 1
  END SELECT
!
CASE('IE')
  SELECT CASE (ISPC)
  CASE(18)
    NMSPRC = 2
  CASE(19)
    IF(DSTMP.LT.5.0)THEN
      NMSPRC = 1
    ELSE IF(DSTMP.GE.5.0.AND.DSTMP.LT.10.0)THEN
      NMSPRC = NINT(-1.0 + 0.4 * DSTMP)
    ELSE
      NMSPRC = 3
    ENDIF
  CASE DEFAULT
    NMSPRC = 1
  END SELECT
!----------
!  ALL OTHER VARIANTS & SPECIES
!----------
CASE DEFAULT
    NMSPRC = 2
!
END SELECT
!
RETURN
!
!
ENTRY ASSPTN (ISHAG,ASBAR,ASTPAR,PREM,TREES)
!----------
!  THIS SUBROUTINE DETERMINES THE NUMBER OF QUAKING ASPEN SPROUTS
!  PER ACRE (SPA) BASED ON POLYNOMIAL FORMULA FROM CROUCH DATA SET,
!  MODIFIED BY PROPORTION OF ASPEN BA CUT BY CHAD KEYSER (FMSC).
!----------
!  DEFINITIONS
!
!    RSHAG -- AGE OF SPROUT RECORD
!      SPA -- POTENTIAL TREES PER ACRE OF ASPEN SPROUTS
!    ASBAR -- ASPEN BASAL AREA HARVESTED (198 IS AVERAGE FOR STOCKED
!               STANDS IN INPUT DATASET)
!   ASTPAR -- TOTAL REMOVED ASPEN TREES PER ACRE
!    TREES -- TREES PER ACRE REPRESENTED BY SPROUT RECORD
!----------
RSHAG=FLOAT(ISHAG)
SPA = 40100.45 - 3574.02*RSHAG**2.0 + 554.02*RSHAG**3.0 &
         - 3.5208*RSHAG**5.0 + 0.011797*RSHAG**7.0
IF(SPA .LT. 2608.)SPA=2608.
IF(SPA .GT. 30125.)SPA=30125.
SPA = SPA * ASBAR/198.
TREES =(PREM/(ASTPAR*2.))*SPA
!
RETURN
!
!
ENTRY SPRTHT (VAR,ISPC,SI,IAG,HTSPRT)
!----------
!  THIS SUBROUTINE DETERMINES SPROUT HEIGHT BY VARIANT AND SPECIES.
!
!  EQUATION IS HT = (0.1 + SI/BASEAGE)*AGE
!
!  DEFAULT EQUATION, HTSPRT = 0.5 + 0.5*IAG, IS THE ORIGINAL EQUATION
!  FROM NI REGEN/ESTAB
!----------
!  DEFINITIONS
!
!    HTSPRT -- HEIGHT OF SPROUT RECORD
!----------
SELECT CASE (VAR)
!----------
! AK: ALASKA
!     SPROUTING SPECIES: 14=AD, 15=RA, 16=PB, 17=AB, 18=BA, 19=AS,
!     20=CW, 21=WI, 22=SU
!----------
CASE('AK')
  SELECT CASE (ISPC)
  CASE(14:22)
    HTSPRT = (0.1 + SI/100.)*IAG
  CASE DEFAULT
    HTSPRT = 0.5 + 0.5*IAG
  END SELECT
!----------
! CI: CENTRAL IDAHO
!     SPROUTING SPECIES: 12=PY, 13=AS, 17=CW
!----------
CASE('CI')
  SELECT CASE (ISPC)
  CASE(13)
    HTSPRT = (0.1 + SI/80.)*IAG
  CASE(12,17)
    HTSPRT = (0.1 + SI/100.)*IAG
  CASE DEFAULT
    HTSPRT = 0.5 + 0.5*IAG
  END SELECT
!----------
! EM: EASTERN MONTANA
!     SPROUTING SPECIES: 11=GA, 12=AS, 13=CW, 14=BA, 15=PW, 16=NC, 17=PB
!----------
CASE('EM')
  SELECT CASE (ISPC)
  CASE(12,17)
    HTSPRT = (0.1 + SI/80.)*IAG
  CASE(11,13:16)
    HTSPRT = (0.1 + SI/100.)*IAG
  CASE DEFAULT
    HTSPRT = 0.5 + 0.5*IAG
  END SELECT
!----------
! IE: INLAND EMPIRE
!     SPROUTING SPECIES: 17=PY, 18=AS, 19=CO, 20=MM, 21=PB
!----------
CASE('IE')
  SELECT CASE (ISPC)
  CASE(18)
    HTSPRT = (0.1 + SI/80.)*IAG
  CASE(17,19:21)
    HTSPRT = (0.1 + SI/100.)*IAG
  CASE DEFAULT
    HTSPRT = 0.5 + 0.5*IAG
  END SELECT
!----------
! KT: KOOTENAI, KANIKSU, TALLY LAKE RD OF THE FLATHEAD
! NI: NORTHERN IDAHO
!     SPROUTING SPECIES: NONE
!----------
CASE('KT','NI')
  SELECT CASE (ISPC)
  CASE DEFAULT
    HTSPRT = 0.5 + 0.5*IAG
  END SELECT
!----------
! XX: LEFTOVERS
!----------
CASE DEFAULT
    HTSPRT = 0.5 + 0.5*IAG
!
END SELECT
!
RETURN
!
!
END



