!ODE SEGMENT DBSCOM
!----------
!  DBSQLITE $Id$
!----------

INTEGER ISUMARY,ICOMPUTE,ITREELIST,IPOTFIRE,IFUELS,ITREEIN
INTEGER ICUTLIST,IDM1,IDM2,IDM3,IDM5,IDM6,IFUELC,IBURN,IMORTF
INTEGER ISSUM,ISDET,ISTRCLAS,IBMMAIN,IBMBKP,IBMTREE,IBMVOL
INTEGER IDBSECON,ISPOUT6,ISPOUT17,IDWDVOL,IDWDCOV,IATRTLIST
INTEGER IRD1,IRD2,IRD3
INTEGER ISPOUT21,ISPOUT23,ISPOUT30,ISPOUT31,ICLIM
INTEGER I_CMPU,IADDCMPU,ICMRPT,ICHRPT,ICANPR
INTEGER IOUTDBREF,IINDBREF,ICALIB,ISTATS1,ISTATS2
INTEGER IREG1,IREG2,IREG3,IREG4,IREG5,IPOTFIREC
INTEGER IVBCSUM,IVBCTRELST,IVBCCUTLST,IVBCATRLST

integer irgin

REAL RTREEDATA(25)
CHARACTER(LEN=256) DSNOUT,DSNIN,KEYFNAME
INTEGER LENSTRINGS(3)
CHARACTER(LEN=36) CASEID

COMMON / DBSCHR / DSNOUT,DSNIN,KEYFNAME,CASEID
COMMON / DBSCOM / &
          IATRTLIST,ISPOUT6,ISPOUT17,ISPOUT21,ISPOUT23, &
          ISPOUT30,ISPOUT31,ISUMARY,ICOMPUTE,ITREELIST,IPOTFIRE, &
          IFUELS,ITREEIN,LENSTRINGS, &
          IDM1,IDM2,IDM3,IDM5,IDM6,RTREEDATA, &
          IRD1,IRD2,IRD3,IOUTDBREF,IINDBREF, &
          ICUTLIST,I_CMPU,IADDCMPU,ICMRPT,ICHRPT,ICLIM, &
          IFUELC,IBURN,IMORTF,ISSUM,ISDET, &
          ISTRCLAS,IDWDVOL, IDWDCOV, ICALIB, &
          IBMMAIN,IBMTREE,IBMVOL,IDBSECON,IBMBKP, ICANPR, irgin, &
          ISTATS1,ISTATS2,IREG1,IREG2,IREG3,IREG4,IREG5,IPOTFIREC, &
          IVBCSUM,IVBCTRELST,IVBCCUTLST,IVBCATRLST
!
!     ICASE= THE UNIQUE DATABASE CASE NUMBER FOR KEEPING TRACK OF
!             OF THE SEPERATE RUNS INSIDE THE DATABASE
!     ISUMARY = SWITCH CONTROLING CREATION OF THE SUMMARY TABLE
!     ICOMPUTE= SWITCH CONTROLING CREATION OF THE COMPUTE TABLE
!     ICALIB  = SWITCH CONTROLING CREATION OF THE CALIBRATION TABLE
!     ITREELIST=SWITCH CONTROLING CREATION OF THE TREE LIST TABLE
!     ICUTLIST= SWITCH CONTROLING CREATION OF THE CUTS LIST TABLE
!    IATRTLIST= SWITCH CONTROLING CREATION OF THE AFTER TREATMENT TREE LIST TABLE
!    LENSTRINGS=THE DEFINED LENGTH OF THE DBSIN AND DBSOUT STRINGS, ONLY USED
!               IN THE PUT/GET ROUTINES.
!     ITREEIN = SWITCH CONTROLING CREATION OF THE TREE DATA TABLE
!     IRGIN   = SWITCH CONTROLING CREATION OF THE REGENERATION DATA TABLE
!     IPOTFIRE= SWITCH CONTROLING CREATION OF THE FIRE MODEL POTFIRE TABLE
!     IPOTFIREC= SWITCH CONTROLING CREATION OF THE FIRE MODEL POTFIRE TABLE CONDITIONS HEADER
!     IFUELS  = SWITCH CONTROLING CREATION OF THE FIRE MODEL ALL FUELS TABLE
!     ICMRPT  = SWITCH CONTROLING CREATION OF THE THE C-REPORT TABLE
!     ICHRPT  = SWITCH CONTROLING CREATION OF THE THE C-HARVEST TABLE
!     ICMRPT  = SWITCH CONTROLING CREATION OF THE CARBON MAIN REPORT TABLE
!     ICHRPT  = SWITCH CONTROLING CREATION OF THE CARBON HARVEST REPORT TABLE
!     IDM1    = SWITCH CONTROLING CREATION OF THE DM MODEL TABLE 1
!     IDM3    = SWITCH CONTROLING CREATION OF THE DM MODEL TABLE 2
!     IDM3    = SWITCH CONTROLING CREATION OF THE DM MODEL TABLE 3
!     IDM5    = SWITCH CONTROLING CREATION OF THE DM MODEL TABLE 5
!     IDM6    = SWITCH CONTROLING CREATION OF THE DM MODEL TABLE 6
!     IRD1    = SWITCH CONTROLING CREATION OF THE RD TABLE 1 - Disease Summary
!     IRD2    = SWITCH CONTROLING CREATION OF THE RD TABLE 2 - Disease Detail
!     IRD3    = SWITCH CONTROLING CREATION OF THE RD TABLE 3 - Bark Beetle Mortality
!     IFUELC  = SWITCH CONTROLING CREATION OF THE FUEL CONSUMPTION TABLE
!     IBURN   = SWITCH CONTROLING CREATION OF THE BURN CONDITIONS TABLE
!     IMORTF  = SWITCH CONTROLING CREATION OF THE MORTALITY TABLE
!     ISSUM   = SWITCH CONTROLING CREATION OF THE SNAG SUMMARY TABLE
!     ISDET   = SWITCH CONTROLING CREATION OF THE DETAILED SNAG TABLE
!     ISTRCLAS= SWITCH CONTROLING CREATION OF THE STRUCTURE CLASS REPORT
!     ICANPR  = SWITCH CONTROLING CREATION OF THE CANOPY FUELS PROFILE TABLE
!     ICLIM   = SWITCH CONTROLING CREATION OF THE CLIMATE-FVS TABLE
!     IDWDVOL = SWITCH CONTROLING CREATION OF THE DOWN WOOD VOLUME TABLE
!     IDWDCOV = SWITCH CONTROLING CREATION OF THE DOWN WOOD COVER TABLE
!     ISTATS1 = SWITCH CONTROLING CREATION OF THE INVENTORY STATS SPECIES SUMMARY TABLE
!     ISTATS2 = SWITCH CONTROLING CREATION OF THE INVENTORY STATS STAND ATTRIBUTES TABLE
!     IREG1   = SWITCH CONTROLING CREATION OF THE REGENERATION SPROUTS TABLE
!     IREG2   = SWITCH CONTROLING CREATION OF THE REGENERATION SITE PREP TABLE
!     IREG3   = SWITCH CONTROLING CREATION OF THE REGENERATION PLOT HABITAT/FOREST TYPE TABLE
!     IREG4   = SWITCH CONTROLING CREATION OF THE REGENERATION TALLY TABLE
!     IREG5   = SWITCH CONTROLING CREATION OF THE REGENERATION INGROWTH TABLE
!     IBMMAIN = FLAG INDICATING WHETHER OR NOT STD OUTPUT IS TO BE
!               SUPPRESSED,(1=STD OUTPUT + DB; 2=DB ONLY) FOR THE
!               MAIN WWPBM OUTPUT FILE
!     IBMTREE = FLAG FOR THE WWPBM DETAILED TREExSIZE CLASS OUTPUT TBL
!     IBMBKP  = FLAG FOR THE WWPBM DETAILED BKP OUTPUT TBL
!     IBMVOL  = FLAG FOR THE WWPBM DETAILED VOLUME OUTPUT TBL
!     IDBSECOM = SWITCH CONTROLING CREATION OF THE ECON SUMMARY TABLE
!     ISPOUT6 = SWITCH FOR KEYWORD CONTROL OF SPECIES CODES OUTPUT FORMAT
!               TREELIST TABLE, OPTION 6
!     ISPOUT17= SWITCH FOR KEYWORD CONTROL OF SPECIES CODES OUTPUT FORMAT
!               CUTLIST TABLE, OPTION 17
!     ISPOUT21= SWITCH FOR KEYWORD CONTROL OF SPECIES CODES OUTPUT FORMAT
!               FFE MORTREP TABLE, OPTION 21
!     ISPOUT23= SWITCH FOR KEYWORD CONTROL OF SPECIES CODES OUTPUT FORMAT
!               FFE SNAGOUT TABLE, OPTION 23
!     ISPOUT30= SWITCH FOR KEYWORD CONTROL OF SPECIES CODES OUTPUT FORMAT
!               ECONHARV TABLE, OPTION 30
!     ISPOUT31= SWITCH FOR KEYWORD CONTROL OF SPECIES CODES OUTPUT FORMAT
!               AFTER TREATMENT TREE LIST (ATRTLIST) TABLE, OPTION 31
!     KEYFNAME= THE KEYWORD FILE NAME WITH SUFFIX MODIFIED TO FIT WITHIN
!               THE DECLARED LENGTH...USED IN THE FVS_CASES TABLE.
!     I_CMPU  = FLAG, SET TO 1 TO ALLOW UNDSCORE COMPUTES TO BE OUTPUT TO THE
!               DATABASE (SUCH AS:_name) DEFAULT IS 0
!     IADDCMPU= FLAG, SET TO 1 IF YOU DO NOT WANT TO ADD NEW COMPUTE COLUMNS TO
!               AN EXISTING TABLE IN THE DATABASE
!
!     **TREEDATA VARIABLES USED FOR BINDING TO THE DATABASE. NEEDED
!       BECAUSE DBSTREESIN LOSES SCOPE AFTER EACH TREE RECORD IS READ IN
!     CTMP      = TEMPORARY STRING USED IN DBSTREESIN (AVAILABLE FOR OTHER USES)
!     RTREEDATA = FLOAT TREEDATA ARRAY FOR TREESIN INFORMATION
!     IVBCSUM   = SWITCH FOR FIAVBC SUMMARY TABLE
!     IVBCTRELST= SWITCH FOR FIAVBC TREELIST TABLE
!     IVBCCUTLST= SWITCH FOR FIAVBC CUTLIST
!     IVBCATRLST= SWITCH FOR FIAVBC AFTER TREATMENT LIST
!-----END SEGMENT
