SUBROUTINE DBSCMPU
IMPLICIT NONE
!
! DBSQLITE $Id$
!
!     PURPOSE: TO POPULATE A DATABASE WITH THE COMPUTE TABLE
!              INFORMATION
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'OPCOM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'KEYCOM.f90'
!
!
INCLUDE 'DBSCOM.f90'
!
!
INCLUDE 'PLOT.f90'
   $ ATTRIBUTES DLLIMPORT :: FSQL3_ADDCOLIFABSENT &
   $ ATTRIBUTES DLLIMPORT :: FSQL3_BIND_DOUBLE &
   $ ATTRIBUTES DLLIMPORT :: FSQL3_BIND_INT &
   $ ATTRIBUTES DLLIMPORT :: FSQL3_BIND_TEXT &
   $ ATTRIBUTES DLLIMPORT :: FSQL3_CLOSE &
   $ ATTRIBUTES DLLIMPORT :: FSQL3_COLCNT &
   $ ATTRIBUTES DLLIMPORT :: FSQL3_COLDOUBLE &
   $ ATTRIBUTES DLLIMPORT :: FSQL3_COLINT &
   $ ATTRIBUTES DLLIMPORT :: FSQL3_COLISNULL &
   $ ATTRIBUTES DLLIMPORT :: FSQL3_COLNAME &
   $ ATTRIBUTES DLLIMPORT :: FSQL3_COLREAL &
   $ ATTRIBUTES DLLIMPORT :: FSQL3_COLTEXT &
   $ ATTRIBUTES DLLIMPORT :: FSQL3_COLTYPE &
   $ ATTRIBUTES DLLIMPORT :: FSQL3_ERRMSG &
   $ ATTRIBUTES DLLIMPORT :: FSQL3_EXEC &
   $ ATTRIBUTES DLLIMPORT :: FSQL3_FINALIZE &
   $ ATTRIBUTES DLLIMPORT :: FSQL3_OPEN &
   $ ATTRIBUTES DLLIMPORT :: FSQL3_PREPARE &
   $ ATTRIBUTES DLLIMPORT :: FSQL3_RESET &
   $ ATTRIBUTES DLLIMPORT :: FSQL3_STEP &
   $ ATTRIBUTES DLLIMPORT :: FSQL3_TABLEEXISTS &
   _WIN64) &
   $ ATTRIBUTES ALIAS:'_FSQL3_ADDCOLIFABSENT' :: FSQL3_ADDCOLIFABSENT &
   $ ATTRIBUTES ALIAS:'_FSQL3_BIND_DOUBLE'    :: FSQL3_BIND_DOUBLE &
   $ ATTRIBUTES ALIAS:'_FSQL3_BIND_INT'       :: FSQL3_BIND_INT &
   $ ATTRIBUTES ALIAS:'_FSQL3_BIND_TEXT'      :: FSQL3_BIND_TEXT &
   $ ATTRIBUTES ALIAS:'_FSQL3_CLOSE'          :: FSQL3_CLOSE &
   $ ATTRIBUTES ALIAS:'_FSQL3_COLCNT'         :: FSQL3_COLCNT &
   $ ATTRIBUTES ALIAS:'_FSQL3_COLDOUBLE'      :: FSQL3_COLDOUBLE &
   $ ATTRIBUTES ALIAS:'_FSQL3_COLINT'         :: FSQL3_COLINT &
   $ ATTRIBUTES ALIAS:'_FSQL3_COLISNULL'      :: FSQL3_COLISNULL &
   $ ATTRIBUTES ALIAS:'_FSQL3_COLNAME'        :: FSQL3_COLNAME &
   $ ATTRIBUTES ALIAS:'_FSQL3_COLREAL'        :: FSQL3_COLREAL &
   $ ATTRIBUTES ALIAS:'_FSQL3_COLTEXT'        :: FSQL3_COLTEXT &
   $ ATTRIBUTES ALIAS:'_FSQL3_COLTYPE'        :: FSQL3_COLTYPE &
   $ ATTRIBUTES ALIAS:'_FSQL3_ERRMSG'         :: FSQL3_ERRMSG &
   $ ATTRIBUTES ALIAS:'_FSQL3_EXEC'           :: FSQL3_EXEC &
   $ ATTRIBUTES ALIAS:'_FSQL3_FINALIZE'       :: FSQL3_FINALIZE &
   $ ATTRIBUTES ALIAS:'_FSQL3_OPEN'           :: FSQL3_OPEN &
   $ ATTRIBUTES ALIAS:'_FSQL3_PREPARE'        :: FSQL3_PREPARE &
   $ ATTRIBUTES ALIAS:'_FSQL3_RESET'          :: FSQL3_RESET &
   $ ATTRIBUTES ALIAS:'_FSQL3_STEP'           :: FSQL3_STEP &
   $ ATTRIBUTES ALIAS:'_FSQL3_TABLEEXISTS'    :: FSQL3_TABLEEXISTS
!
!OMMONS
!
INTEGER MXLEN
PARAMETER(MXLEN=10000)
CHARACTER(LEN=MXLEN) SQLStmt
CHARACTER(LEN=8),DIMENSION(MXTST5)::KWINSRT
DOUBLE PRECISION,DIMENSION(MXTST5)::CURVAL
LOGICAL LDUPKW
INTEGER I,II,IX,I3,iRet,THISYR,ICY,NSRTNUM

INTEGER fsql3_tableexists,fsql3_exec,fsql3_addcolifabsent
!
!     IF COMPUTE IS NOT TURNED ON OR THE NUMBER OF VARIABLES IS 0
!     THEN RETURN
!
IF(ICOMPUTE.EQ.0.OR.ITST5.EQ.0) RETURN
!
!     Do we need the table, or all all variables with a _
!
II=0
DO I=1,ITST5
    IF(.NOT.(CTSTV5(I)(1:1).EQ.'_'.AND.I_CMPU.LT.1)) THEN
      II=1
      EXIT
    ENDIF
ENDDO
IF (II.EQ.0) RETURN
!
!     CALL DBSCASE TO MAKE SURE WE HAVE AN UP TO DATE CASEID
!
CALL DBSCASE(1)
!
!     CHECK TO SEE IF THE COMPUTE TABLE EXISTS IN DATBASE
!     IF IT DOES NOT THEN WE NEED TO CREATE IT
!
iRet = fsql3_exec (IoutDBref,"Begin;"//Char(0))
iRet = fsql3_tableexists(IoutDBref,"FVS_Compute"//CHAR(0))
IF(iRet.EQ.0) THEN
  SQLStmt='CREATE TABLE FVS_Compute('// &
                'CaseID text not null,'// &
                'StandID text not null,'// &
                'Year int null'
  DO I=1,ITST5
    IF(.NOT.(CTSTV5(I)(1:1).EQ.'_'.AND.I_CMPU.LT.1)) THEN
      SQLStmt=TRIM(SQLStmt)//', '// &
                 TRIM(CTSTV5(I))//' real null'
    ENDIF
  ENDDO
  iRet = fsql3_exec(IoutDBref,TRIM(SQLStmt)//');'//CHAR(0))
  IF (iRet .NE. 0) THEN
    ICOMPUTE = 0
    RETURN
  ENDIF
ELSE
!
!       MAKE SURE ALL THE NEEDED COLUMNS EXIST
!
  DO I=1,ITST5
    IF(.NOT.(CTSTV5(I)(1:1).EQ.'_'.AND.I_CMPU.LT.1)) THEN
    iRet = fsql3_addcolifabsent(IoutDBref, &
            "FVS_Compute"//CHAR(0), &
            TRIM(CTSTV5(I))//CHAR(0), "real"//CHAR(0))
    ENDIF
  ENDDO
ENDIF
!
!     BUILD AND RUN THE INSERT COMMANDS
!
DO ICY=1,NCYC
!
!     Make a list of variables and correspoinding values
!     for the current cycle
!
  NSRTNUM = 0
  THISYR = -1
  DO II=IMGPTS(ICY,1),IMGPTS(ICY,2)
    I=IOPSRT(II)
    IF(IACT(I,1).EQ.33 .AND. IACT(I,4).GT.0) THEN
      IF(THISYR.EQ.-1) THISYR = IACT(I,4)
      IF(IACT(I,4).NE.THISYR) THEN
        IF(NSRTNUM.GT.0) THEN

!             Build and run an insert query

          CALL INSERTCMPU(IoutDBref,KWINSRT,CURVAL,THISYR, &
                             NPLT,CASEID,NSRTNUM)

        ENDIF
        NSRTNUM = 0
        THISYR = IACT(I,4)
      ENDIF
      IX=IFIX(PARMS(IACT(I,2)+1))
      IF (IX.GT.500) IX=IX-500
!
!           CHECK TO SEE IF WE WANT TO SKIP UNDERSCORE COMPUTES
!
      IF(CTSTV5(IX)(1:1).EQ.'_'.AND.I_CMPU.LT.1) CYCLE
      IF (NSRTNUM.EQ.0) THEN
        KWINSRT(1) = CTSTV5(IX)
        CURVAL(1)=PARMS(IACT(I,2))
        NSRTNUM = 1
      ELSE
        LDUPKW =.FALSE.
        DO I3=1,NSRTNUM
          IF(TRIM(KWINSRT(I3)).EQ.TRIM(CTSTV5(IX))) THEN
            CURVAL(I3)=PARMS(IACT(I,2))
            LDUPKW =.TRUE.
            EXIT
          ENDIF
        ENDDO
        IF(.NOT.LDUPKW) THEN
          NSRTNUM = NSRTNUM + 1
          KWINSRT(NSRTNUM)=CTSTV5(IX)
          CURVAL(NSRTNUM)=PARMS(IACT(I,2))
        ENDIF
      ENDIF
    ENDIF
  ENDDO

!       More to insert?

  IF(NSRTNUM.GT.0) &
         CALL INSERTCMPU(IoutDBref,KWINSRT,CURVAL,THISYR,NPLT,CASEID, &
                         NSRTNUM)
ENDDO
iRet = fsql3_exec (IoutDBref,"Commit;"//Char(0))
RETURN
END

SUBROUTINE INSERTCMPU(IoutDBref,KWINSRT,CURVAL,THISYR,STANDID, &
                         CASEID,NSRTNUM)
IMPLICIT NONE
!
!     INPUT: KWINSRT - THE ARRAY OF COMPUTE VARS TO INSERT
!            CURVAL  - THE ARRAY OF VALUES ASSOCIATED W/ THE VARS
!            NSRTNUM - THE NUMBER OF COMPUTE VARS TO INSERT
!
INTEGER I,THISYR,IoutDBref,IRT,NSRTNUM
CHARACTER(LEN=8) KWINSRT(NSRTNUM)
DOUBLE PRECISION CURVAL(NSRTNUM)
CHARACTER(LEN=26) STANDID
CHARACTER(LEN=36) CASEID
CHARACTER(LEN=5000) SQLStmt
CHARACTER(LEN=500)  VALS
INTEGER fsql3_prepare,fsql3_bind_int,fsql3_bind_double, &
           fsql3_finalize,fsql3_errmsg,fsql3_step

SQLStmt=" "
VALS=" "
IF(NSRTNUM.EQ.0) RETURN
DO I=1,NSRTNUM
  SQLStmt = TRIM(SQLStmt) // "," // TRIM(KWINSRT(I))
  VALS    = TRIM(VALS)    // ",?"
ENDDO

SQLStmt = "insert into FVS_Compute (CaseID,StandID,Year" // &
      trim(SQLStmt) // ") values ('" // CASEID // "','" // &
      TRIM(STANDID) // "',?" // TRIM(VALS) // ");" // CHAR(0)
IRT = fsql3_prepare(IoutDBref,SQLStmt)
IF (IRT>0) THEN
  IRT = fsql3_errmsg(IoutDBref,VALS, 200)
  PRINT *,"dbscmpu prepare error: ",TRIM(VALS)
endif
IRT = fsql3_bind_int(IoutDBref, 1, THISYR)
DO I=1,NSRTNUM
  IRT = fsql3_bind_double(IoutDBref,I+1,CURVAL(I))
ENDDO
IRT = fsql3_step(IoutDBref)
IF (IRT>0) THEN
  IRT = fsql3_errmsg(IoutDBref,VALS,200)
  PRINT *,"dbscmpu step error: ",TRIM(VALS)
endif
IRT = fsql3_finalize(IoutDBref)
IF (IRT>0) THEN
  IRT = fsql3_errmsg(IoutDBref,VALS,200)
  PRINT *,"dbscmpu finalize error: ",TRIM(VALS)
endif
RETURN
END
