SUBROUTINE DBSPRS(TOKEN,SOURCE,DELIMSTR)
IMPLICIT NONE
!
! DBSQLITE $Id$
!
!     PURPOSE: TO SIMPLY RETURN THE FIRST TOKEN FROM THE SOURCE PASSED
!     IN USING THE DELIMSTR AS THE DELIMITER
!
!     THE ROUTINE ALSO CHANGES SOURCE, SO THAT SUBSEQUENT CALLS SKIP
!     THE TOKEN.
!
!     OUTPUT: TOKEN    - THE TOKENIZED VALUE
!             SOURCE   - THE SOURCE STRING WHICH IS TOKENIZED
!             DELIMSTR - THE DELIMITER THAT THE STRING IS TOKENIZED ON
!

CHARACTER(LEN=*) SOURCE,TOKEN,DELIMSTR
CHARACTER*1000 SAVESTR
INTEGER ISTART,ILEN,IDLEN,IBEGPOS,IENDPOS

TOKEN=' '
ISTART = 1
SAVESTR = SOURCE

IBEGPOS = ISTART
ILEN = LEN(SAVESTR)
IDLEN = LEN(DELIMSTR)
5 CONTINUE
IF (IBEGPOS .LT. ILEN) THEN
  IF (INDEX(DELIMSTR,SAVESTR(IBEGPOS:IBEGPOS+IDLEN-1)).NE.0) THEN
    IBEGPOS = IBEGPOS + 1
    GOTO 5
  ENDIF
ENDIF
IENDPOS = IBEGPOS
10 CONTINUE
IF ((IENDPOS .LE. ILEN)) THEN
  IF (INDEX(DELIMSTR,SAVESTR(IENDPOS:IENDPOS+IDLEN-1)).EQ.0) THEN
    IENDPOS = IENDPOS + 1
    GOTO 10
  ENDIF
ENDIF
TOKEN = SAVESTR(IBEGPOS:IENDPOS-1)
SOURCE = SAVESTR(IENDPOS+IDLEN:)
ISTART = IENDPOS

END
