SUBROUTINE FINDAG(I,ISPC,D1,D2,H,SITAGE,SITHT,AGMAX,HTMAX1,HTMAX2, &
                     DEBUG)
IMPLICIT NONE
!----------
! KT $Id$
!----------
!  IN THE NI VARIANT, FINDAG IS A DUMMY ROUTINE THAT RETURNS WITHOUT
!  EXECUTING ANY COMPUTATIONS.  IN OTHER VARIANTS THIS ROUTINE
!  MAY SET EFFECTIVE TREE AGE BASED ON INPUT VARIABLE(S)
!  SUCH AS TREE HEIGHT.
!  CALLED FROM **COMCUP
!  CALLED FROM **CRATET
!
!  COMMONS
!
INCLUDE 'PRGPRM.f90'
!
INCLUDE 'CONTRL.f90'
!
!----------
LOGICAL DEBUG
INTEGER I,ISPC
REAL D1,D2,H,SITAGE,SITHT,AGMAX,HTMAX1,HTMAX2
REAL RDANUW
INTEGER IDANUW
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
RDANUW = AGMAX
RDANUW = D1
RDANUW = D2
RDANUW = H
RDANUW = HTMAX1
RDANUW = HTMAX2
IDANUW = ISPC
!
IF(DEBUG)WRITE(JOSTND,50)I,SITAGE,SITHT
50 FORMAT(' LEAVING SUBROUTINE FINDAG  I,SITAGE,SITHT =',I5,2F10.3)
!
RETURN
END
!**END OF CODE SEGMENT
