SUBROUTINE MAICAL
IMPLICIT NONE
!----------
! KT $Id$
!----------
!  THIS SUBROUTINE CALCULATES THE MAI FOR THE STAND. IT IS CALLED
!  FROM CRATET. FOR INLAND EMPIRE THIS ROUTINE IS A DUMMY.
!----------
!
RETURN
END
