SUBROUTINE CVBCAL(HTINDX)
IMPLICIT NONE
!----------
! COVR $Id$
!----------
!  THIS SUBROUTINE IS CALLED BY **CVBROW** TO COMPUTE CORRECTION
!  FACTORS FOR THE UNDERSTORY SHRUB PREDICTIONS. IT IS ONLY CALLED
!  ONCE DURING THE SIMULATION AT THE START OF THE PROJECTION.
!
!  VARIABLE DEFINITIONS:
!----------
!       ** COMPUTED CORRECTION FACTORS **
!
!-- BHTCF(31) -- SHRUB HEIGHT CORRECTION FACTORS
!-- BPCCF(31) -- SHRUB COVER CORRECTION FACTORS
!-- XCV(31), XPB(31), XSH(31) -- COVER, PROB., AND HEIGHT
!             PREDICTIONS FOR CYCLE # 0, BEFORE CALIBRATION
!----------
!       ** CALIBRATION BY LAYER **
!
!-- AVGBHT(3), AVGBPC(3) -- OBSERVED AVERAGE HEIGHT AND COVER VALUES
!             OF UP TO 3 SHRUB LAYERS INPUT ON THE SHRBLAYR KEYWORD
!             RECORD.  SORTED BY HEIGHT IN **CVIN**:
!             AVGBHT(1) = AVERAGE HEIGHT OF TALLEST SHRUB LAYER,
!             AVGBHT(3) = AVERAGE HEIGHT OF LOWEST SHRUB LAYER
!-- HTAVG(3), CVAVG(3) -- PREDICTED AVERAGE HEIGHT AND COVER
!             VALUES FOR SHRUB LAYERS COMPUTED BY **CVBCAL**
!-- HTFRAC(3), CVFRAC(3) -- RATIO OF OBSERVED/PREDICTED (AVGBHT/HTAVG)
!             HEIGHT OR COVER VALUES BY LAYERS, OR, CORRECTION
!             FACTORS BY LAYER
!-- HTINDX(31) -- SPECIES SUBSCRIPTS SORTED BY DECREASING HEIGHT
!-- IHT(3,2) -- INDEXES HTINDX(31) BY SHRUB LAYER
!-- ILAYR(31) -- LAYER NUMBER WHICH EACH SHRUB SPECIES IS ASSIGNED TO
!-- LCAL1 --  .TRUE. IF CALIBRATION METHOD #1 IS BEING USED
!             (CALIBRATION BY SHRUB LAYER: SHRBLAYR CARD)
!-- NKLASS -- NUMBER OF OBSERVED SHRUB LAYERS (UP TO THREE),
!             IDENTIFIED ON SHRBLAYR KEYWORD CARD
!-- SUMCVR -- TOTAL OBSERVED COVER, EQUAL TO THE SUM OF THE COVER
!             VALUES FOR SHRUB LAYERS INPUT ON THE SHRBLAYR CARD
!-- TOTLCV(MAXCY1,2) -- TOTAL PREDICTED COVER BEFORE CALIBRATION,
!             WEIGHTED BY PB(I), COMPUTED BY **CVBROW** IN CYCLE # 0
!-- RELPC(3) -- RATIO OF OBSERVED COVER VALUES BY LAYER TO TOTAL
!               (AVGBPC(I)/SUMCVR)
!-- SUMHT(3), SUMCV(3), NEXTSP, LASTSP, CUMULI, RCUMPC, DIFF1, DIFF2 --
!             VARIABLES USED TO FIND HEIGHT CLASSES
!----------
!       ** CALIBRATION BY SPECIES **
!
!-- SHRBHT(31), SHRBPC(31) -- OBSERVED HEIGHT AND COVER VALUES
!             FOR SPECIES READ FROM THE SHRUBHT KEYWORD CARD
!-- LCAL2 --  .TRUE. IF CALIBRATION METHOD #2 IS BEING USED
!             (CALIBRATION BY SPECIES: SHRUBHT & SHRUBPC CARDS)
!
!-----------------------------------------------------------------------
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'CVCOM.f90'
!
!OMMONS
!
LOGICAL DEBUG
INTEGER HTINDX(31)
REAL RELPC(3)
REAL SUMCV(3),SUMHT(3)
INTEGER IHT(3,2)
INTEGER ISPI,I,NEXTSP,J,K,I1,I2,LASTSP
REAL CUMULI,RCUMPC,DIFF1,DIFF2
!----------
!  CHECK FOR DEBUG.
!----------
CALL DBCHK(DEBUG,'CVBCAL',6,ICYC)
IF (DEBUG) WRITE (JOSTND,9000) ICYC
9000 FORMAT ('**CALLING CVBCAL, CYCLE = ', I3)
!----------
!  SAVE THE UNCALIBRATED PREDICTIONS FOR CYCLE # 0 IN THE ARRAYS XCV,
!  XPB, AND XSH.
!----------
DO 10 ISPI=1,31
XCV(ISPI) = PBCV(ISPI)
XPB(ISPI) = PB(ISPI)
XSH(ISPI) = SH(ISPI)
10 CONTINUE
!----------
!  BRANCH TO DESIRED CALIBRATION TECHNIQUE:
! ---------
IF (LCAL2) GO TO 200
!===============  CALIBRATION METHOD # 1: BY SHRUB LAYER ===============
!  COMPUTE THE RATIO OF OBSERVED PERCENT COVER BY HEIGHT LAYER
!  TO THE TOTAL.
!
!  BECAUSE OF NUMERICAL PROBLEMS IN COMPARING RCUMPC WITH
!  RELPC(I), ADD A LITTLE TO RELPC(I).
!----------
DO 30 I=1,NKLASS
RELPC(I) = 0.00001 + AVGBPC(I)/SUMCVR
30 CONTINUE
!
IF (DEBUG) WRITE (JOSTND,7000) (AVGBPC(I),I=1,NKLASS),SUMCVR, &
                    (RELPC(I),I=1,NKLASS)
7000 FORMAT (7F10.5//)
!----------
!  PROGRESS DOWN THROUGH THE SHRUB SPECIES FROM TALLEST TO SHORTEST
!  (BASED ON FIRST CYCLE HEIGHT PREDICTIONS), AND ACCUMULATE THE
!  INDIVIDUAL SHRUB COVER VALUES (WEIGHTED BY PROBABILITY OF
!  OCCURRENCE). WHEN THIS VALUE ACCOUNTS FOR THE SAME PROPORTION
!  OF TOTAL PREDICTED SHRUB COVER AS INPUT SHRUB LAYER ONE
!  DOES OF THE TOTAL INPUT SHRUB COVER -- STOP; GROUP THOSE
!  SPECIES DOWN TO THE CURRENT SPECIES INTO HEIGHT CLASS ONE.
!  ZERO OUT THE SHRUB COVER CUMULATOR AND CONTINUE ON DOWN THE SPECIES
!  LIST UNTIL "NKLASS" GROUPS HAVE BEEN IDENTIFIED IN THE SAME MANNER.
!  ALL SPECIES MUST BE PLACED INTO A GROUP.
!----------
NEXTSP = 1
DO 100 I=1,NKLASS
IF (NEXTSP .GT. 31) GO TO 130
IHT(I,1) = NEXTSP
CUMULI = 0.0
RCUMPC = 0.0
!----------
!  IF THIS IS THE LAST GROUP: THROW ALL THE REMAINING SPECIES INTO IT.
!----------
IF ( I .EQ. NKLASS ) GO TO 110
DO 70 J=NEXTSP,31
K = HTINDX(J)
DIFF1 = ABS( RCUMPC - RELPC(I) )
CUMULI = CUMULI + PBCV(K)
RCUMPC = CUMULI/TOTLCV(1,1)
DIFF2 = ABS( RCUMPC - RELPC(I) )
!
IF (DEBUG) WRITE (JOSTND,7009) I,J,K,PBCV(K), &
                    CUMULI,RCUMPC,TOTLCV(1,1),RELPC(I),DIFF1,DIFF2
7009 FORMAT ('70 CONTINUE : I, J, K',3I5,9F10.5)
!
IF (RELPC(I) .EQ. 0.0) GO TO 80
IF ( RCUMPC .LE. RELPC(I) ) GO TO 70
!----------
!  PREDICTED COVER RATIO (RCUMPC) HAS JUST EXCEEDED THE OBSERVED
!  COVER RATIO FOR THE CURRENT ILAYER. CHOOSE WHETHER TO KEEP THE LAST
!  SPECIES COVER VALUE IN THE CUMULATED TOTAL DEPENDING ON IF THE
!  MATCH WAS CLOSER PRIOR TO ADDING IN THE LAST SPECIES:
!           IF ( DIFF1 .LE. DIFF2 ) DROP THE LAST SPECIES
!----------
IF ( DIFF1 .LE. DIFF2 ) GO TO 80
GO TO 90
70 CONTINUE
80 CONTINUE
!----------
!  DROP THE LAST SPECIES
!----------
CUMULI = CUMULI - PBCV(K)
IF (DEBUG) WRITE (JOSTND,7010) I,J,K,PBCV(K), &
                    CUMULI,RCUMPC, TOTLCV(1,1),RELPC(I),DIFF1,DIFF2
7010 FORMAT ('80 DROP     : I, J, K',3I5,9F10.5)
LASTSP = J-1
NEXTSP = J
IHT(I,2) = LASTSP
GO TO 100
90 CONTINUE
!----------
!  KEEP THE LAST SPECIES
!----------
IF (DEBUG) WRITE (JOSTND,7011) I,J,K,PBCV(K), &
                     CUMULI,RCUMPC,TOTLCV(1,1),RELPC(I),DIFF1,DIFF2
7011 FORMAT ('90 KEEP     : I, J, K',3I5,9F10.5)
LASTSP = J
NEXTSP = J + 1
IHT(I,2) = LASTSP
100 CONTINUE
110 CONTINUE
DO 120 J=NEXTSP,31
K = HTINDX(J)
CUMULI = CUMULI + PBCV(K)
IF (DEBUG) WRITE (JOSTND,7012) I,J,K,PBCV(K), &
                   CUMULI
7012 FORMAT ('120 THE REST: I, J, K',3I5,4F10.5)
120 CONTINUE
IHT(NKLASS,2) = 31
130 CONTINUE
IF (DEBUG) WRITE (JOSTND,7013) I,NEXTSP,LASTSP
7013 FORMAT ('130 CONTINUE : I,NEXTSP,LASTSP',3I5)
!----------
!  USING THE CLASS POINTERS DEFINED ABOVE, COMPUTE THE AVERAGE
!  PREDICTED SHRUB HEIGHT AND PERCENT COVER IN EACH HEIGHT CLASS.
!----------
DO 150 I=1,NKLASS
IF (AVGBPC(I) .LE. 0.0) GO TO 150
SUMCV(I) = 0.0
SUMHT(I) = 0.0
CVAVG(I) = 0.0
HTAVG(I) = 0.0
CVFRAC(I) = 0.0
HTFRAC(I) = 0.0
I1 = IHT(I,1)
I2 = IHT(I,2)
IF (DEBUG) WRITE (JOSTND,7014) I1,I2
7014 FORMAT ('150 CONTINUE : I1,I2',2I5)
   IF (I2.LT.I1) GO TO 150
DO 140 J=I1,I2
   K = HTINDX(J)
   ILAYR(K) = I
   SUMCV(I) = SUMCV(I) + PBCV(K)
   SUMHT(I) = SUMHT(I) + SH(K)
140 CONTINUE
   CVAVG(I) = SUMCV(I)
   HTAVG(I) = SUMHT(I)/((I2-I1)+1)
150 CONTINUE
IF (DEBUG) WRITE (JOSTND,7000) (CVAVG(I),I=1,NKLASS), &
                    (HTAVG(I),I=1,NKLASS)
!----------
!  COMPUTE THE RATIO OF OBSERVED VALUES TO PREDICTED VALUES FOR AVERAGE
!  SHRUB HEIGHT AND AVERAGE PERCENT COVER IN EACH OF THE HEIGHT LAYERS.
!  ASSIGN CORRECTION FACTORS BASED ON THE RATIOS ABOVE.
!----------
DO 180 I=1,NKLASS
IF (AVGBPC(I) .LE. 0.0) GO TO 180
IF (CVAVG(I).GT.0.0) CVFRAC(I) = AVGBPC(I)/CVAVG(I)
IF (HTAVG(I).GT.0.0) HTFRAC(I) = AVGBHT(I)/HTAVG(I)
I1 = IHT(I,1)
I2 = IHT(I,2)
IF (I2.LT.I1) GO TO 180
DO 170 J=I1,I2
K = HTINDX(J)
BHTCF(K) = HTFRAC(I)
BPCCF(K) = CVFRAC(I)
170 CONTINUE
180 CONTINUE
RETURN
200 CONTINUE
!
!============ CALIBRATION METHOD #2: BY INDIVIDUAL SPECIES ============
!  COMPUTE RATIOS FOR (MEASURED HEIGHT/PREDICTED HEIGHT), AND
!  (MEASURED % COVER/PREDICTED % COVER).
!----------
!       OBSERVED          PROB      CORRECTION FACTORS
!  --------------------------------------------------------------
!  SHRBHT(I)  SHRBPC(I)   PB(I)     BHTCF(I)  BPCCF(I)
!  ---------  ---------   -----     --------  --------
!     < 0.      < 0.      SAME         1.0       1.0
!     < 0.        0.      0.0          0.0       0.0
!     < 0.      > 0.      1.0          1.0    INPUT/PRED
!
!       0.      < 0.      SAME         0.0       0.0
!       0.        0.      0.0          0.0       0.0
!       0.      > 0.      1.0          0.0    INPUT/PRED
!
!     > 0.      < 0.      SAME     INPUT/PRED    1.0
!     > 0.        0.      0.0          0.0       0.0
!     > 0.      > 0.      1.0      INPUT/PRED INPUT/PRED
!
!  IF OBSERVED SHRBPC(I) > 0, THEN PB(I) IS RESET TO 1.0
!  IF OBSERVED SHRBPC(I) = 0, THEN PB(I) IS RESET TO 0.0
!
!----------
DO 300 ISPI = 1,31
IF (SHRBPC(ISPI) .GE. 0.0) GO TO 230
IF (SHRBHT(ISPI) .LT. 0.0) GO TO 300
IF (SHRBHT(ISPI) .GT. 0.0) GO TO 210
BPCCF(ISPI) = 0.0
BHTCF(ISPI) = 0.0
GO TO 300
!
210 CONTINUE
BHTCF(ISPI) = SHRBHT(ISPI)/SH(ISPI)
GO TO 300
!
230 CONTINUE
IF (SHRBPC(ISPI) .GT. 0.0) GO TO 240
BPCCF(ISPI) = 0.0
BHTCF(ISPI) = 0.0
GO TO 300
!
240 CONTINUE
BPCCF(ISPI) = SHRBPC(ISPI)/PBCV(ISPI)
!
IF (SHRBHT(ISPI) .LT. 0.0) GO TO 300
IF (SHRBHT(ISPI) .GT. 0.0) GO TO 270
BHTCF(ISPI) = 0.0
GO TO 300
!
270 CONTINUE
BHTCF(ISPI) = SHRBHT(ISPI)/SH(ISPI)
300 CONTINUE
!
RETURN
END
