SUBROUTINE CVCLAS (LTHIN)
IMPLICIT NONE
!----------
! COVR $Id$
!----------
!  THIS SUBROUTINE IS CALLED BY **CVBROW** OR **CVCNOP** TO COMPUTE A
!  "SUCCESSIONAL STAGE" FOR THE STAND, AS DESCRIBED BY
!
!     S.R. PETERSON.  1982.  A PRELIMINARY SURVEY OF FOREST BIRD
!        COMMUNITIES IN NORTHERN IDAHO.  NORTHWEST SCIENCE 56(4):
!        287-298.
!
!     S.R. PETERSON. 1978.  FOREST MANAGEMENT AND BIRD COMMUNITIES
!        IN NORTHERN IDAHO.  PAC. DIV. AMER. ASSOC. ADV. SCI.,
!        59TH ANNUAL MEETING, JUNE 13-17, (ABSTRACT).
!
!  STAND CLASSIFICATION IS BASED ON:
!
!  -- SAGE -- TIME SINCE DISTURBANCE
!  -- RELDEN -- CROWN COMPETITION FACTOR
!  -- TOTLCV(41,2) -- PERCENT SHRUB COVER
!  -- AVH -- AVERAGE TREE HEIGHT
!  -- TALLSH -- AVERAGE "TALL SHRUB" HEIGHT
!  -- DIAM --"AVERAGE" TREE DIAMETER
!
!  THE LOGIC USED IN CLASSIFYING THE STAND INVOLVES A SELECTIVE
!  DEFINITION OF AVG. STAND DBH. ITS PURPOSE IS TO AVOID
!  USE OF THE RMSQD FOR THE STAND IN CASES WHERE THE STATISTIC
!  IS MISLEADING OR PROVIDES VERY LITTLE INFORMATION (SUCH
!  AS IN THE CASE OF A TWO-STORIED STAND.)
!
!  OTHER VARIABLE DEFINITIONS:
!
!  -- CRAX20(2) -- CROWN AREA IN TWO DENSEST 20' HEIGHT CLASSES
!  -- CRAREA -- TOTAL CROWN AREA
!  -- CRXHT(16) -- CROWN AREA BY HEIGHT CLASS, COMPUTED IN **CVSUM**
!  -- MTAG1, MTAG2 -- INDEX TO TWO DENSEST 20' HEIGHT CLASSES
!  -- ONE, TWO, THREE -- INDICES TO THREE DENSEST 10' HEIGHT CLASSES
!  -- INDX(16) -- INDEXES CROWN AREA SORTED BY DECREASING VALUE
!              WITHIN HEIGHT CLASSES
!  -- SD2XHT(16) -- SUM OF SQUARED DBH'S BY HEIGHT CLASS
!  -- TXHT(41,2,16) -- NUMBER OF TREES BY HEIGHT CLASS
!  -- ISTAGE(41,2) -- STAND SUCCESSIONAL STAGE CODE
!  -- STRUCT -- STAND STRUCTURE CODE
!
!  HEIGHT CLASS CODES: 1=0-10', 2=10-20',...   ...16=150' AND UP.
!----------
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'CVCOM.f90'
!
!OMMONS
!
!----------
! DIMENSION AND TYPE STATEMENTS FOR INTERNAL VARIABLES.
!----------
INTEGER STRUCT,ONE,TWO,THREE
INTEGER INDX(16)
LOGICAL LTHIN,DEBUG
REAL CRAX20(2)
INTEGER IP1,ITHN,I,ITEST,IPLUS1,MTAG1,MTAG2,MTAGP1
REAL HTRNGE,DIAM,TEST,TOP2,TOP3,DENX20
!----------
!  CHECK FOR DEBUG.
!----------
CALL DBCHK(DEBUG,'CVCLAS',6,ICYC)
!----------
!  DON'T COMPUTE SUCCESSIONAL STAGE IF SHRUB PREDICTIONS ARE
!  NOT AVAILABLE (BECAUSE TIME SINCE DISTURBANCE GT 40 YEARS).
!----------
IF (SAGE .GT. 40.) RETURN
!----------
! SET CYCLE AND THIN SUBSCRIPTS.
!----------
IP1 = ICYC + 1
ITHN = 1
IF (.NOT. LTHIN) GO TO 10
IP1 = ICYC
ITHN = 2
10 CONTINUE
!
IF (DEBUG) WRITE (JOSTND,8090) ICYC
8090 FORMAT (/ '**CALLING CVCLAS, ICYC= ',I2)
IF (DEBUG) WRITE (JOSTND,8091) IP1,ITHN,AVH,TALLSH
8091 FORMAT (/ 'IP1= ',I2,'  ITHN= ',I2,'  AVH= ',F10.4, &
             '  TALLSH= ',F10.4)
!======================================================================
!  ** COMPUTE SHRUB-DOMINATED SUCCESSIONAL STAGES **
!======================================================================
!----------
!   SUCCESSIONAL STAGE 1 -- RECENT DISTURBANCE
!----------
ISTAGE(IP1,ITHN) = 0
IF (SAGE .GT. 5.0) GO TO 250
IF ((RELDEN .GT. 30.0) .AND. (AVH .GT. 1.0)) GO TO 280
IF ((TALLSH .GT. 1.0) .OR. (TOTLCV(IP1,ITHN) .GT. 25.0)) GO TO 250
ISTAGE(IP1,ITHN) = 1
IF (DEBUG) WRITE (JOSTND,8092) ISTAGE(IP1,ITHN),SAGE,RELDEN, &
        AVH,TALLSH,TOTLCV(IP1,ITHN)
8092 FORMAT (/ 'ISTAGE(IP1,ITHN)= ',I2 / &
   'SAGE= ',F10.2,'  RELDEN= ',F10.2,'  AVH= ',F10.4, &
   '  TALLSH= ',F10.4,'  TOTLCV(IP1,ITHN)= ',F10.4)
RETURN
250 CONTINUE
!----------
!   SUCCESSIONAL STAGE 2 -- LOW SHRUB
!----------
IF ((RELDEN .GT. 30.0) .AND. (AVH .GT. 1.0)) GO TO 280
IF (TALLSH .GT. 2.5) GO TO 260
ISTAGE(IP1,ITHN) = 2
IF (DEBUG) WRITE (JOSTND,8092) ISTAGE(IP1,ITHN),SAGE,RELDEN, &
        AVH,TALLSH,TOTLCV(IP1,ITHN)
RETURN
260 CONTINUE
!----------
!   SUCCESSIONAL STAGE 3 -- MEDIUM SHRUB
!----------
IF (TALLSH .GT. 5.0) GO TO 270
ISTAGE(IP1,ITHN) = 3
IF (DEBUG) WRITE (JOSTND,8092) ISTAGE(IP1,ITHN),SAGE,RELDEN, &
        AVH,TALLSH,TOTLCV(IP1,ITHN)
RETURN
270 CONTINUE
!----------
!   SUCCESSIONAL STAGE 4 -- TALL SHRUB WITH NO CONIFERS
!----------
IF (TOTLCV(IP1,ITHN) .LT. 70.0) GO TO 280
ISTAGE(IP1,ITHN) = 4
IF (DEBUG) WRITE (JOSTND,8092) ISTAGE(IP1,ITHN),SAGE,RELDEN, &
        AVH,TALLSH,TOTLCV(IP1,ITHN)
RETURN
280 CONTINUE
!----------
!   SUCCESSIONAL STAGE 5 -- TALL SHRUB WITH FEW CONIFERS
!----------
IF ((TALLSH .LT. 5.0).AND.(TOTLCV(IP1,ITHN) .LT. 50.0)) GO TO 290
IF (AVH .GT. 5.0) GO TO 290
IF (RELDEN .GT. 50.0) GO TO 290
ISTAGE(IP1,ITHN) = 5
IF (DEBUG) WRITE (JOSTND,8092) ISTAGE(IP1,ITHN),SAGE,RELDEN, &
        AVH,TALLSH,TOTLCV(IP1,ITHN)
RETURN
290 CONTINUE
!----------
!   SUCCESSIONAL STAGE 6 -- TALL SHRUB WITH MOSTLY CONIFERS
!----------
IF ((TALLSH .LT. 5.0 ).AND.(TOTLCV(IP1,ITHN) .LT. 30.0)) GO TO 300
IF (RELDEN .GT. 100.0) GO TO 300
ISTAGE(IP1,ITHN) = 6
IF (DEBUG) WRITE (JOSTND,8092) ISTAGE(IP1,ITHN),SAGE,RELDEN, &
        AVH,TALLSH,TOTLCV(IP1,ITHN)
RETURN
300 CONTINUE
!======================================================================
!  ENTER CODE TO FIND STAND STRUCTURE AND DIAMETER FOR
!  TREE-DOMINATED STAGES.
!======================================================================
!------------------------------------------------------------
!  ** STRUCT = 1   :   STAND IS EVEN-AGED **
!------------------------------------------------------------
!  CALCULATE RANGE OF TREE HEIGHTS.
!  IF 30' OR LESS, STAND IS EVEN-AGED.
!  DIAM SET TO ROOT MEAN SQUARE OF STAND, OR TO OLD RMSQD
!  IF THINNING HAS JUST OCCURRED.
!----------
HTRNGE = HTMAX - HTMIN
IF (HTRNGE .GT. 30.0) GO TO 110
STRUCT = 1
DIAM = RMSQD
IF (LTHIN) DIAM = ORMSQD
GO TO 190
110 CONTINUE
!----------
!  SORT CROWN AREA 'CRXHT(16)' BY HEIGHT CLASS.
!  INDX(1) = SUBSCRIPT OF HEIGHT CLASS WITH GREATEST CROWN AREA
!  INDX(16) = SUBSCRIPT OF HEIGHT CLASS WITH LEAST CROWN AREA
!----------
CALL RDPSRT(16,CRXHT,INDX,.TRUE.)
ONE = INDX(1)
TWO = INDX(2)
THREE = INDX(3)
IF (DEBUG) WRITE (JOSTND,9000)ONE,TWO,THREE,(CRXHT(I),I=1,16)
9000 FORMAT ('ONE=',I2,'   TWO=',I2,'   THREE=',I2 / &
           'CRXHT(I)=',16F7.1)
!----------
!  IF THE DENSEST LAYER CONTAINS 50% OR MORE OF THE TOTAL CROWN AREA,
!  THE STAND IS EVEN-AGED.
!  SET DIAM TO THE RMSQD FOR THAT CLASS.
!----------
TEST = CRXHT(ONE)/CRAREA
IF (TEST .LT. 0.50) GO TO 120
STRUCT = 1
DIAM = SQRT(SD2XHT(ONE)/TXHT(IP1,ITHN,ONE))
IF (DEBUG) WRITE (JOSTND,9001) STRUCT,DIAM, &
        SD2XHT(ONE),TXHT(IP1,ITHN,ONE)
9001 FORMAT ('STRUCT=',I5,'  DIAM=',F10.1,'  SD2XHT=',F10.1, &
       '  TXHT=',F10.1/19X,F10.1,9X,F10.1/19X,F10.1,9X,F10.1)
GO TO 190
120 CONTINUE
!----------
!  IF THE TWO DENSEST LAYERS CONTAIN 70% OR MORE OF THE TOTAL
!  CROWN AREA, AND IF THIS IS SPREAD OVER 3 HEIGHT CLASSES OR LESS,
!  THE STAND IS EVEN-AGED.
!  SET DIAM TO THE RMSQD FOR THE TWO CLASSES.
!----------
TOP2 = CRXHT(ONE) + CRXHT(TWO)
TEST = TOP2/CRAREA
ITEST = MAX0(ONE,TWO) - MIN0(ONE,TWO)
IF ((TEST .LT. 0.70) .OR. (ITEST .GT. 2)) GO TO 130
STRUCT = 1
DIAM = SQRT((SD2XHT(ONE) + SD2XHT(TWO))/ &
        (TXHT(IP1,ITHN,ONE) + TXHT(IP1,ITHN,TWO)))
IF (DEBUG) WRITE (JOSTND,9001) STRUCT,DIAM, &
        SD2XHT(ONE),TXHT(IP1,ITHN,ONE), &
        SD2XHT(TWO),TXHT(IP1,ITHN,TWO)
GO TO 190
130 CONTINUE
!----------
!  IF THE 3 DENSEST LAYERS CONTAIN 90% OR MORE OF THE TOTAL CROWN AREA,
!  AND IF THE 3 LAYERS ARE CONSECUTIVE, THE STAND IS EVEN-AGED.
!  SET DIAM EQUAL TO THE RMSQD OF THE THREE CLASSES.
!----------
TOP3 = CRXHT(ONE) + CRXHT(TWO) + CRXHT(THREE)
TEST = TOP3/CRAREA
IF (TEST .LT. 0.90) GO TO 140
ITEST = MAX0(ONE,TWO,THREE) - MIN0(ONE,TWO,THREE)
IF (ITEST .GT. 2) GO TO 140
STRUCT = 1
DIAM = SQRT((SD2XHT(ONE) + SD2XHT(TWO) + SD2XHT(THREE))/ &
        (TXHT(IP1,ITHN,ONE)+TXHT(IP1,ITHN,TWO)+TXHT(IP1,ITHN,THREE)))
IF (DEBUG) WRITE (JOSTND,9001) STRUCT,DIAM, &
        SD2XHT(ONE),TXHT(IP1,ITHN,ONE), &
        SD2XHT(TWO),TXHT(IP1,ITHN,TWO), &
        SD2XHT(THREE),TXHT(IP1,ITHN,THREE)
GO TO 190
140 CONTINUE
!------------------------------------------------------------
!  ** STRUCT = 2   :   STAND IS TWO-STORIED **
!------------------------------------------------------------
!  STARTING AT THE BOTTOM, DETERMINE THE CROWN AREA CONTRIBUTED BY
!  EACH CONSECUTIVE 20' LAYER. SAVE THE MAXIMUM VALUE 'CRAX20(1)',
!  AND A TAG TO ITS LOCATION 'MTAG1'.
!----------
CRAX20(1) = 0.0
DO 150 I=1,15
IPLUS1 = I + 1
DENX20 = CRXHT(I) + CRXHT(IPLUS1)
IF (DENX20 .LT. CRAX20(1)) GO TO 150
CRAX20(1) = DENX20
MTAG1 = I
150 CONTINUE
!----------
!  FIND THE SECOND DENSEST 20' LAYER BY REPEATING THE ABOVE PROCESS.
!----------
CRAX20(2) = 0.0
ITEST = MTAG1 + 1
DO 160 I=1,15
IPLUS1 = I + 1
IF ((IPLUS1.EQ.MTAG1).OR.(I.EQ.MTAG1).OR.(I.EQ.ITEST)) GO TO 160
DENX20 = CRXHT(I) + CRXHT(IPLUS1)
IF (DENX20 .LT. CRAX20(2)) GO TO 160
CRAX20(2) = DENX20
MTAG2 = I
160 CONTINUE
!----------
!  IF THE TWO DENSEST 20' LAYERS ARE SEPARATED BY 20' OR MORE, THE
!  STAND IS TWO STORIED.
!  SET DIAM EQUAL TO THE RMSQD OF DENSEST LAYER ONLY.
!----------
ITEST = IABS(MTAG1 - MTAG2)
IF (ITEST .LT. 4) GO TO 170
MTAGP1 = MTAG1 + 1
STRUCT = 2
DIAM = SQRT((SD2XHT(MTAG1) + SD2XHT(MTAGP1))/ &
        (TXHT(IP1,ITHN,MTAG1) + TXHT(IP1,ITHN,MTAGP1)))
IF (DEBUG) WRITE(JOSTND,9004) STRUCT,DIAM,MTAG1, &
        SD2XHT(MTAG1),TXHT(IP1,ITHN,MTAG1), &
        STRUCT,DIAM,MTAGP1,SD2XHT(MTAGP1),TXHT(IP1,ITHN,MTAGP1)
9004 FORMAT ('STRUCT=',I5,'   DIAM=',F10.1,'  MTAG=',I3, &
         '   SD2XHT=',F10.1,'   TXHT=',F10.1)
GO TO 190
170 CONTINUE
!------------------------------------------------------------
!  ** STRUCT = 3   :   STAND IS ALL-AGED **
!------------------------------------------------------------
!  IF THE CROWN AREA IN 3 DENSEST LAYERS IS LESS THAN 50% OF TOTAL
!  CROWN AREA, THE STAND IS ALL-AGED.
!  SET DIAM EQUAL TO THE RMSQD OF 3 DENSEST 10' LAYERS.
!----------
IF (TEST .GE. 0.50) GO TO 180
STRUCT = 3
DIAM = SQRT((SD2XHT(ONE) + SD2XHT(TWO) + SD2XHT(THREE))/ &
        (TXHT(IP1,ITHN,ONE)+TXHT(IP1,ITHN,TWO)+TXHT(IP1,ITHN,THREE)))
IF (DEBUG) WRITE (JOSTND,9001) STRUCT,DIAM, &
        SD2XHT(ONE),TXHT(IP1,ITHN,ONE), &
        SD2XHT(TWO),TXHT(IP1,ITHN,TWO), &
        SD2XHT(THREE),TXHT(IP1,ITHN,THREE)
GO TO 190
180 CONTINUE
!----------
!  IF THE DENSEST LAYER CONTAINS LESS THAN 20% OF THE TOTAL CROWN
!  AREA, THE STAND IS ALL-AGED.
!  SET DIAM EQUAL TO THE RMSQD OF 3 DENSEST 10' LAYERS.
!----------
TEST = CRXHT(ONE)/CRAREA
IF (TEST .LT. 0.20) GO TO 185
STRUCT = 3
DIAM = SQRT((SD2XHT(ONE) + SD2XHT(TWO) + SD2XHT(THREE))/ &
        (TXHT(IP1,ITHN,ONE)+TXHT(IP1,ITHN,TWO)+TXHT(IP1,ITHN,THREE)))
IF (DEBUG) WRITE (JOSTND,9001) STRUCT,DIAM, &
        SD2XHT(ONE),TXHT(IP1,ITHN,ONE), &
        SD2XHT(TWO),TXHT(IP1,ITHN,TWO), &
        SD2XHT(THREE),TXHT(IP1,ITHN,THREE)
GO TO 190
185 CONTINUE
190 CONTINUE
!======================================================================
!  ** COMPUTE TREE-DOMINATED SUCCESSIONAL STAGES **
!======================================================================
!----------
!   SUCCESSIONAL STAGE 7 -- SAPLING TIMBER
!----------
IF (DIAM .GT. 4.0) GO TO 310
ISTAGE(IP1,ITHN) = 7
IF (DEBUG) WRITE (JOSTND,8093) ISTAGE(IP1,ITHN),DIAM
8093 FORMAT (/ 'ISTAGE(IP1,ITHN)= ',I2,'  DIAM= ',F10.3)
RETURN
310 CONTINUE
!----------
!   SUCCESSIONAL STAGE 8 -- POLE TIMBER
!----------
IF (DIAM .GT. 11.0) GO TO 320
ISTAGE(IP1,ITHN) = 8
IF (DEBUG) WRITE (JOSTND,8093) ISTAGE(IP1,ITHN),DIAM
RETURN
320 CONTINUE
!----------
!   SUCCESSIONAL STAGE 9 -- MATURE TIMBER
!----------
IF (DIAM .GT. 24.0) GO TO 330
ISTAGE(IP1,ITHN) = 9
IF (DEBUG) WRITE (JOSTND,8093) ISTAGE(IP1,ITHN),DIAM
RETURN
330 CONTINUE
!----------
!   SUCCESSIONAL STAGE 10 -- OLD-GROWTH TIMBER
!----------
ISTAGE(IP1,ITHN) = 10
IF (DEBUG) WRITE (JOSTND,8093) ISTAGE(IP1,ITHN),DIAM
RETURN
END
