SUBROUTINE CVCNOP (LTHIN)
IMPLICIT NONE
!----------
! COVR $Id$
!----------
!  **CVCNOP** CONTROLS THE CALLS TO THE CROWN WIDTH, CROWN SHAPE,
!  CROWN FOLIAGE BIOMASS, SUMMARY, AND CLASSIFICATION SUBPROGRAMS.
!----------
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'CVCOM.f90'
!
!OMMONS
!
LOGICAL LTHIN,DEBUG
!----------
!  CHECK FOR DEBUG.
!----------
CALL DBCHK(DEBUG,'CVCNOP',6,ICYC)
!
IF (.NOT. LCOV) RETURN
!
IF (LTHIN) LTHIND(ICYC) = .TRUE.
!----------
!  CALL **CVCW** TO COMPUTE CROWN WIDTH.
!----------
IF (DEBUG) WRITE (JOSTND,9000) ICYC
9000 FORMAT ('**CALLING CVCW, CYCLE =',I2)
CALL CVCW (LTHIN)
!----------
!  CALL **CVSHAP** TO COMPUTE CROWN SHAPE.
!----------
IF (.NOT.LCNOP) GO TO 10
IF (DEBUG) WRITE (JOSTND,9001) ICYC
9001 FORMAT ('**CALLING CVSHAP, CYCLE =',I2)
CALL CVSHAP (LTHIN)
!----------
!  CALL **CVCBMS** TO COMPUTE CROWN BIOMASS.
!----------
IF (DEBUG) WRITE (JOSTND,9002) ICYC
9002 FORMAT ('**CALLING CVCBMS, CYCLE =',I2)
CALL CVCBMS (LTHIN)
!----------
!  CALL **CVSUM** TO COMPUTE SUMS.
!----------
10 CONTINUE
IF (DEBUG) WRITE (JOSTND,9003) ICYC
9003 FORMAT ('**CALLING CVSUM, CYCLE =',I2)
CALL CVSUM (LTHIN)
!----------
!  CALL **CVCLAS** TO COMPUTE THE 'STAND SUCCESSIONAL STAGE' CODE.
!----------
IF (.NOT.LBROW) RETURN
IF (DEBUG) WRITE (JOSTND,9004) ICYC
9004 FORMAT ('**CALLING CVCLAS, CYCLE =',I2)
CALL CVCLAS(LTHIN)
RETURN
END
