SUBROUTINE CVCW (LTHIN)
IMPLICIT NONE
!----------
! COVR $Id$
!----------
!  COMPUTES CROWN WIDTH FOR INDIVIDUAL TREES.
!  ALSO COMPUTES SUM OF CROWN AREAS, CRAREA.
!
!  CROWN WIDTH RELATIONSHIPS ARE DOCUMENTED IN :
!  MOEUR,MELINDA. 1981. CROWN WIDTH AND FOLIAGE WEIGHT OF NORTHERN
!      ROCKY MOUNTAIN CONIFERS.  USDA FOR. SERV. RES. PAP. INT- 283.
!----------
!  VARIABLE DEFINITIONS
!----------
!  BH1(MAXSP)-- ARRAY OF COEFFICIENTS FOR HEIGHT TERM FOR CROWN
!             WIDTH FUNCTION FOR TREES LESS THAN 3.5 INCHES DBH
!  BINT2(MAXSP)- ARRAY OF INTERCEPTS FOR CROWN WIDTH FUNCTION
!             FOR TREES 3.5 INCHES AND LARGER
!  BH2(MAXSP)-- ARRAY OF COEFFICIENTS FOR HEIGHT TERM FOR TREES
!             .GE. 3.5 INCHES
!  BAREA   -- STAND BASAL AREA
!  CL      -- CROWN LENGTH
!  D       -- TREE DBH
!  H       -- TREE HEIGHT
!  TRECW(MAXTRE) PREDICTED CROWN WIDTH IN FEET
!  CRAREA -- SUM OF ALL CROWN PROJECTION AREAS (PI/4*TRECW*TRECW)
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'CVCOM.f90'
!
!OMMONS
LOGICAL LTHIN,DEBUG
INTEGER I,ISPI,IICR
REAL D,H,P
LOGICAL LDANUW
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
LDANUW = LTHIN
!----------
!  CHECK FOR DEBUG.
!----------
CALL DBCHK(DEBUG,'CVCW',4,ICYC)
IF (DEBUG) WRITE (JOSTND,9000) ICYC
9000 FORMAT (/'**CALLING CVCW, CYCLE = ',I2 / '        I      ISPI', &
    '         D         H        CL     BAREA     TRECW    CRAREA')
!----------
!  RETURN IF NOTREES OPTION IN EFFECT.
!----------
IF (ITRN .GT. 0) GO TO 5
IF (DEBUG) WRITE (JOSTND,9001) ITRN
9001 FORMAT ('ITRN =', I5,' : NOTREES : RETURN TO **CVCNOP**')
RETURN
5 CONTINUE
!----------
!  ENTER TREE LOOP
!----------
CRAREA = 0.0
!
DO 100 I = 1,ITRN
D = DBH(I)
H = HT(I)
ISPI = ISP(I)
IICR = ICR(I)
P = PROB(I)
TRECW(I) = CRWDTH(I)
!----------
!  COMPUTE SUM OF CROWN PROJECTION AREAS.
!----------
CRAREA = CRAREA + TRECW(I)*TRECW(I)*P
IF (DEBUG) WRITE (JOSTND,9002) I,ISPI,D,H,IICR, &
                   TRECW(I),CRAREA
9002 FORMAT (2I10,2F10.1,I10,2F10.1)
!
100 CONTINUE
!----------
!  COMPUTE TOTAL CROWN AREA.
!  CONSTANT = PI*TRECW/2*TRECW/2 = .785398
!----------
CRAREA = CRAREA*0.785398
RETURN
END
