SUBROUTINE CVSUM (LTHIN)
IMPLICIT NONE
!----------
! COVR $Id$
!----------
!  COMPUTES CROWN PROJECTION AREA, NUMBER OF TREES, AND SUMS OF
!  SQUARED DIAMETERS BY HEIGHT CLASS FOR SUBROUTINE **CVCLAS**.
!
!  COMPUTES PERCENT CANOPY CLOSURE, CROWN VOLUME, CROWN PROFILE AREA,
!  CROWN FOLIAGE BIOMASS BY HEIGHT CLASS, AND SUM OF DIAMETERS
!  FOR THE CANOPY OPTION.
!
!  COMPUTES SHRUB COVER BY HEIGHT FOR THE SHRUBS OPTION.
!  COMPUTES SHRUB-SMALL CONIFER COMPETITION VALUES BY HEIGHT.
!----------
!  DEFINITIONS OF VARIABLES NEEDED BY **CVCLAS**
!
!  HTMAX - HEIGHT OF TALLEST TREE IN STAND
!  HTMIN - HEIGHT OF SHORTEST TREE IN STAND
!  TALLSH - AVERAGE HEIGHT OF TALL SHRUBS, WEIGHTED BY PBCV(I)
!  CRXHT(16) - CROWN PROJECTION AREA OF TREES WHOSE TOTAL HEIGHTS FALL
!              IN HEIGHT CLASS
!  SD2XHT(16) - SUM OF SQUARED DIAMETERS OF TREES WHOSE HEIGHTS FALL IN
!               HEIGHT CLASS
!----------
!  DEFINITIONS OF VARIABLES NEEDED BY THE CANOPY OPTION.
!
!  PCXHT(MAXCY1,2,16) - PERCENT CANOPY CLOSURE CONTRIBUTED BY TREES
!                   WHOSE TOTAL HEIGHTS FALL IN HEIGHT CLASS
!  TPCTCV(MAXCY1,2) - TOTAL PERCENT CANOPY CLOSURE
!  TXHT(MAXCY1,2,16) - NUMBER OF TREES WHOSE HEIGHTS FALL IN HT CLASS
!  TRETOT(MAXCY1,2) - TOTAL NUMBER OF TREES
!  PROXHT(MAXCY1,2,16) - CROWN PROFILE AREA WITHIN HEIGHT CLASS
!  TPROAR(MAXCY1,2) - TOTAL CROWN PROFILE AREA
!  VOLXHT(MAXCY1,2,16) - CROWN VOLUME WITHIN HEIGHT CLASS
!  TCVOL(MAXCY1,2) - TOTAL CROWN VOLUME
!  CFBXHT(MAXCY1,2,16) - CROWN FOLIAGE BIOMASS WITHIN HEIGHT CLASS
!  TOTBMS(MAXCY1,2) - TOTAL CROWN FOLIAGE BIOMASS
!  SDIAM(MAXCY1,2) - SUM OF STEM DIAMETERS
!  STDHT(MAXCY1,2) - TOP HEIGHT (AVERAGE HEIGHT OF LARGEST 40
!                TREES PER ACRE BY DBH).
!  ICVAGE(MAXCY1,2)  - OVERSTORY AGE
!
!  ISHAP, ISHAPE(MAXTRE) - TREE CROWN SHAPE
!  LCNOP - LOGICAL FLAG FOR CANOPY OPTION
!  TRECW(MAXTRE) - TREE CROWN WIDTH
!  TRFBMS(MAXTRE) - TREE FOLIAGE BIOMASS
!  CAREA  - TOTAL CROWN PROFILE AREA, COMPUTED ANALYTICALLY
!  CVOLUM - TOTAL CROWN VOLUME, COMPUTED ANALYTICALLY
!  PROP - PROPORTION OF FRUSTRUM TO TOTAL VOLUME
!  HC   - HEIGHT OF CROWN  (CROWN LENGTH)
!  BASE - HEIGHT AT CROWN BASE (BOTTOM IF SHAPE CONE, PARABOLOID, OR
!         NEILOID; MID-CROWN IF SHAPE = SPHERE OR ELLIPSOID)
!  RAD  - CROWN RADIUS AT BASE
!
!  CROWN DIMENSIONS WITHIN HEIGHT CLASS;
!
!  BOT     - HEIGHT AT CROWN BOTTOM
!  TREVOL  - TREE CROWN VOLUME, COMPUTED AS SUM OF FRUST
!  TREAR   - TREE CROWN PROFILE AREA, COMPUTED AS SUM OF PAREA
!  ITOP    - INDEX TO HEIGHT CLASS CONTAINING CROWN TOP
!  IBOT    - INDEX TO HEIGHT CLASS CONTAINING CROWN BOTTOM
!  H1 - DISTANCE FROM BASE TO LOWER PLANE OF FRUSTRUM
!  H2 - THICKNESS OF FRUSTRUM
!  R1 - RADIUS OF LOWER PLANE OF FRUSTRUM
!  R2 - RADIUS OF UPPER PLANE OF FRUSTRUM
!  Y1 - LOWER LIMIT OF INTEGRATION
!  Y2 - UPPER LIMIT OF INTEGRATION
!  CNOP(1)  - HEIGHT AT LOWER LIMIT OF CROWN CLASS
!  CNOP(2)  - HEIGHT AT UPPER LIMIT OF CROWN CLASS
!  UPLIM    - HEIGHT AT UPPER PLANE OF CROWN FRUSTRUM
!  LOWLIM   - HEIGHT AT LOWER PLANE OF CROWN FRUSTRUM
!  FRUST    - VOLUME OF FRUSTRUM
!  PAREA    - PROFILE AREA OF FRUSTRUM
!----------
!  VARIABLES NEEDED BY THE SHRUBS OPTION.
!
!-- ASHT(MAXCY1,2) -- WEIGHTED AVERAGE HEIGHT OF ALL SPECIES,
!                     USING PBCV(I)
!-- CLOW(MAXCY1,2),CMED(MAXCY1,2),CTALL(MAXCY1,2) -- SUM OF SPECIES
!             COVER FOR LOW, MEDIUM, AND TALL HEIGHT CLASSES
!-- SCV(MAXCY1,2,12), SHT(MAXCY1,2,12), SPB(MAXCY1,2,12),
!   ISSP(MAXCY1,2,12) --
!             COVER, HEIGHT, PROB, AND SPECIES CODE OF 1ST 3 SPECIES,
!             PLUS 'OTHR', WITH GREATEST PREDICTED COVER (PBCV(I))
!             WITHIN LOW, MEDIUM, AND TALL HEIGHT CLASSES
!-- NUM(3), INC(3), PASS(12), OTHCOV, OTHHT, OTHPB, INDX(12), IGSP(3) -
!             USED TO SORT SHRUBS INTO 3 HEIGHT CLASSES BY GREATEST
!             PREDICTED COVER (PBCV(I))
!-- LSHOW, ISHOW(6), NSHOW -- LOGICAL FLAG, SUBSCRIPTS, AND NUMBER
!             OF USER-SELECTED SPECIES FOR DISPLAY
!-- CIND(MAXCY1,2,6), HIND(MAXCY1,2,6), PIND(MAXCY1,2,6),
!   INDSP(MAXCY1,2,6) --
!             COVER, HEIGHT, PROB, AND SPECIES CODE OF UP TO 6
!             USER-SELECTED SPECIES FOR DISPLAY
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'CVCOM.f90'
!
!
!OMMONS
!
REAL LOWLIM
LOGICAL LTHIN,DEBUG
INTEGER INDX(12)
REAL CNOP(2)
REAL SHTRHT(11)
INTEGER NUM(3),INC(3),IGSP(3)
REAL PASS(12)
INTEGER J1,IICR,ISHAP,IBOT,K,ITOP
REAL PROP,PAREA,FRUST,CONST,Z1,Z2,B1,CAREA,CVOLUM,Y2,Y1,R2,R1,H1
REAL H2,UPLIM,TREAR,TREVOL,RAD,BASE,BOT,HC
INTEGER ITHN,IP1,I,ISPI,IH,J,JP1,IG
REAL HEIGHT,SUMPB,TSHT,TSUMPB,HM1,OTHCOV,OTHHT,OTHPB

DATA NUM /7,12,12/
DATA INC /0,7,19/
DATA IGSP /0,4,8/
!
DATA SHTRHT/0.5,1.0,2.0,3.0,4.0,5.0,7.5,10.0,15.0,20.0,400./
!----------
!  CHECK FOR DEBUG.
!----------
CALL DBCHK(DEBUG,'CVSUM',5,ICYC)
!----------
! LTHIN = .TRUE. IF THINNING HAS OCCURRED.
!----------
ITHN = 1
IP1 = ICYC + 1
IF (LTHIN) ITHN = 2
IF (LTHIN) IP1 = ICYC
IF (DEBUG) WRITE (JOSTND,9000) ICYC
9000 FORMAT (/'**CALLING CVSUM, CYCLE = ',I2)
!======================================================================
!  ** COMPUTE SHRUB SUMMARY VALUES **
!======================================================================
!  SKIP THIS SECTION IF SHRUB CALCULATIONS NOT AVAILABLE.
!----------
IF (.NOT. LBROW) GO TO 150
IF (SAGE .GT. 40.) GO TO 150
!----------
!  COMPUTE VARIOUS SHRUB BY HEIGHT VALUES.
!----------
HEIGHT = 0.0
SUMPB = 0.0
TSHT = 0.0
TSUMPB = 0.0
DO 10 I = 1,11
SCOV(IP1,ITHN,I) = 0.0
TRSH(IP1,ITHN,I) = 0.0
10 CONTINUE
!
DO 80 ISPI = 1,31
!----------
!  1) ASHT(IP1,ITHN) - WEIGHTED AVERAGE HEIGHT OF SHRUBS
!  USING PBCV(ISPI).
!----------
SUMPB = SUMPB + PBCV(ISPI)
HEIGHT = HEIGHT + SH(ISPI)*PBCV(ISPI)
!----------
!  3) TALLSH - AVERAGE SHRUB HEIGHT FOR "TALL SHRUBS" (FROM PATTERSON
!  ET AL., FIELD GUIDE TO FOREST PLANTS OF NORTHERN IDAHO):
!  ACGL,ALSI,AMAL,CESA,CEVE,COST,HODI,PREM,PRVI,SALX,SAMB,SORB.
!----------
IF (ISPI .LT. 20) GO TO 70
TSUMPB = TSUMPB + PBCV(ISPI)
TSHT = TSHT + SH(ISPI)*PBCV(ISPI)
70 CONTINUE
!----------
!  4) CUMULATIVE SHRUB COVER FOR SHRUB-SMALL CONIFER COMPETITION
!  DISPLAY.
!----------
HM1 = -1.0
DO 75 IH = 1,11
HC = SHTRHT(IH)
IF ((SH(ISPI).GT.HM1).AND.(SH(ISPI).LE.HC)) &
      SCOV(IP1,ITHN,IH) = SCOV(IP1,ITHN,IH) + PBCV(ISPI)
HM1 = HC
75 CONTINUE
80 CONTINUE
!
!     IF THERE ARE NO SHRUBS OF A GIVEN CLASS, SET THE AVERAGE HEIGHT
!     TO ZERO
!
IF (SUMPB.LE.1E-4) THEN
   ASHT(IP1,ITHN) = 0.0
ELSE
   ASHT(IP1,ITHN) = HEIGHT/SUMPB
ENDIF
IF (TSUMPB.LE.1E-4) THEN
   TALLSH = 0.0
ELSE
   TALLSH = TSHT/TSUMPB
ENDIF
!
J = 11
DO 90 IH = 1,10
J = J - 1
JP1 = J + 1
SCOV(IP1,ITHN,J) = SCOV(IP1,ITHN,J) + SCOV(IP1,ITHN,JP1)
90 CONTINUE
!----------
!  ORDER SPECIES BY HIGHEST PREDICTED COVER VALUE.  SAVE THE FIRST
!  THREE FOR OUTPUT, AND DUMP EVERYTHING ELSE INTO AN 'OTHER'
!  CATEGORY.  DO FOR THREE HEIGHT CLASSES, 'LOW' SHRUBS, 'MEDIUM'
!  SHRUBS, AND 'TALL' SHRUBS.
!----------
! LOW:SPECIES 1-7    MED:SPECIES 8-19    TALL:SPECIES 20-31
!----------
DO 120 IG = 1,3
OTHCOV = 0.0
OTHHT = 0.0
OTHPB = 0.0
!
DO 100 I = 1,NUM(IG)
K = I + INC(IG)
PASS(I) = PBCV(K)
OTHCOV = OTHCOV + PBCV(K)
OTHHT = OTHHT + SH(K)*PBCV(K)
OTHPB = OTHPB + PB(K)
100 CONTINUE
IF (IG .EQ. 1) CLOW(IP1,ITHN) = OTHCOV
IF (IG .EQ. 2) CMED(IP1,ITHN) = OTHCOV
IF (IG .EQ. 3) CTALL(IP1,ITHN) = OTHCOV
!
CALL RDPSRT (NUM(IG),PASS,INDX,.TRUE.)
!
DO 110 I=1,3
K = INDX(I) + INC(IG)
OTHCOV = OTHCOV - PBCV(K)
OTHHT = OTHHT - SH(K)*PBCV(K)
OTHPB = OTHPB - PB(K)
J = I + IGSP(IG)
SCV(IP1,ITHN,J) = PBCV(K)
SPB(IP1,ITHN,J) = 100.*PB(K)
SHT(IP1,ITHN,J) = SH(K)
ISSP(IP1,ITHN,J) = K
110 CONTINUE
JP1 = J + 1
SCV(IP1,ITHN,JP1) = OTHCOV
IF (OTHCOV.LE.1E-4) THEN
   SHT(IP1,ITHN,JP1) = 0.0
ELSE
   SHT(IP1,ITHN,JP1) = OTHHT/OTHCOV
ENDIF
SPB(IP1,ITHN,JP1) = 100.*OTHPB
ISSP(IP1,ITHN,JP1) = 32
120 CONTINUE
!----------
!  LOAD USER-SELECTED SPECIES ARRAYS FOR DISPLAY.
!----------
IF (.NOT. LSHOW) GO TO 140
DO 130 I=1,NSHOW
J = ISHOW(I)
CIND(IP1,ITHN,I) = PBCV(J)
PIND(IP1,ITHN,I) = 100.*PB(J)
HIND(IP1,ITHN,I) = SH(J)
INDSP(IP1,ITHN,I) = J
130 CONTINUE
140 CONTINUE
!
150 CONTINUE
!=======================================================================
!
!  **COMPUTE TREE BY HEIGHT CLASS VALUES USED IN CANOPY OPTION
!  OR IN CVCLAS**
!
!----------
!  INITIALIZE VARIABLES FOR THE CURRENT CYCLE.
!----------
STDHT(IP1,ITHN) = AVH
ICVAGE(IP1) = IAGE + IY(IP1) - IY(1)
!
HTMAX = 0.0
HTMIN = 999.0
TPCTCV(IP1,ITHN) = 0.0
TPROAR(IP1,ITHN) = 0.0
TCVOL(IP1,ITHN) = 0.0
TOTBMS(IP1,ITHN) = 0.0
TRETOT(IP1,ITHN) = 0.0
SDIAM(IP1,ITHN) = 0.0
DO 50 J = 1,16
CRXHT(J) = 0.0
SD2XHT(J) = 0.0
TXHT(IP1,ITHN,J) = 0.0
PCXHT(IP1,ITHN,J) = 0.0
PROXHT(IP1,ITHN,J) = 0.0
VOLXHT(IP1,ITHN,J) = 0.0
CFBXHT(IP1,ITHN,J) = 0.0
50 CONTINUE
!----------
!  RETURN IF NOTREES OPTION IN EFFECT.
!----------
IF (ITRN .GT. 0) GO TO 60
HTMIN = 0.0
IF (DEBUG) WRITE (JOSTND,9001) ITRN
9001 FORMAT ('ITRN =', I5,' : NOTREES : RETURN TO **CVCNOP**')
RETURN
60 CONTINUE
!----------------------------------------------------------------------
!  ENTER TREE LOOP.
!----------------------------------------------------------------------
IF ((LCNOP).AND.(DEBUG)) WRITE (JOSTND,9010)
9010 FORMAT ('     I  J     FRUST    ', &
   'TREVOL   CVOLUM    PAREA    TREAR    CAREA    BASE   UPLIM', &
   '  LOWLIM      H1      H2      Y1      Y1  TRFBMS')
DO 300 I = 1,ITRN
!----------
!  COMPUTE SHRUB-SMALL CONIFER COMPETITION VALUES, IF SHRUBS ARE
!  AVAILABLE.
!----------
IF (.NOT. LBROW) GO TO 161
HM1 = -1.0
DO 160 IH = 1,11
HC = SHTRHT(IH)
IF ((HT(I).GT.HM1).AND.(HT(I).LE.HC)) &
        TRSH(IP1,ITHN,IH) = TRSH(IP1,ITHN,IH) + PROB(I)
HM1 = HC
160 CONTINUE
161 CONTINUE
!
IF (HT(I) .GT. HTMAX) HTMAX = HT(I)
IF (HT(I) .LT. HTMIN) HTMIN = HT(I)
!----------
!  COMPUTE HEIGHT CLASS OF TOP OF TREE.
!  CLASSES ARE 0-10', 10.01-20', ..., 140.01-150', 150'+
!----------
ITOP = IFIX(HT(I)/10.0001) + 1
IF (ITOP .GT. 16) ITOP = 16
!----------
!  COMPUTE CROWN PROJECTION, NUMBER OF TREES, AND SUM OF SQUARED
!  DIAMETERS BY HEIGHT CLASS NEEDED BY **CVCLAS**.
!  CONSTANT = PI*CW/2*CW/2 = .785398
!----------
CRXHT(ITOP) = CRXHT(ITOP) + .785398*TRECW(I)*TRECW(I)*PROB(I)
TXHT(IP1,ITHN,ITOP) = TXHT(IP1,ITHN,ITOP) + PROB(I)
SD2XHT(ITOP) = SD2XHT(ITOP) + DBH(I)*DBH(I)*PROB(I)
!-----------
!  SKIP THIS SECTION IF CANOPY OPTION IS NOT SPECIFIED.
!----------
IF (.NOT. LCNOP) GO TO 300
!----------
!  COMPUTE HEIGHT CLASS OF CROWN BOTTOM.
!----------
BOT = HT(I) - (HT(I)*ICR(I)/100.)
IBOT = IFIX (BOT/10.) + 1
!----------
!  COMPUTE DIMENSIONS USED IN HEIGHT CLASS CALCULATIONS.
!----------
ISHAP = ISHAPE(I)
IICR = ICR(I)
HC = FLOAT(IICR)*HT(I)/100.
BASE = BOT
IF ((ISHAP.EQ.1) .OR. (ISHAP.EQ.5)) BASE = BOT + HC/2.
RAD = TRECW(I)/2.
TREVOL = 0.0
TREAR = 0.0
!----------
!  SET INITIAL CANOPY HEIGHTS FOR CURRENT TREE.
!----------
CNOP(1) = 10.*IBOT-20.
CNOP(2) = CNOP(1) + 10.
!----------
!  ENTER HEIGHT CLASS LOOP WITHIN CURRENT TREE.  J1 IS USED TO
!  DECREMENT THE INDEX BY HEIGHT CLASS IF THE SHAPE IS NEILOID
!  (I.E. DO IT UPSIDE-DOWN).
!----------
J1 = ITOP + 1
DO 290 J = IBOT,ITOP
IF (ISHAP .NE. 3) J1 = J
IF (ISHAP .EQ. 3) J1 = J1 - 1
DO 230 K=1,2
CNOP(K) = CNOP(K) + 10.
230 CONTINUE
UPLIM = AMIN1(HT(I),CNOP(2))
IF (J.EQ. ITOP) UPLIM = HT(I)
LOWLIM = AMAX1(BOT,CNOP(1))
H1 = LOWLIM - BASE
H2 = UPLIM - LOWLIM
R1 = (1.-H1/HC)*RAD
R2 = (1.-(H1+H2)/HC)*RAD
Y1 = LOWLIM - BASE
Y2 = UPLIM - BASE
IF (Y1 .GE. HC) Y1 = HC
IF (Y2 .GE. HC) Y2 = HC
IF (Y1 .LT. -HC) Y1 = -HC
IF (Y2 .LT. -HC) Y2 = -HC
!----------
!  BRANCH ON SHAPE TO COMPUTE FRUSTRUM VOLUME AND PROFILE AREA.
!----------
GO TO (241,242,243,244,245),ISHAP
!----------
!  ISHAPE=1   SOLID FORM=SPHERE    PLANE FORM=CIRCLE
!----------
241 CONTINUE
CVOLUM = 2.09439*RAD*RAD*HC
CAREA = 1.57079*RAD*HC
IF (BASE.GE.LOWLIM) H1 = BASE - UPLIM
B1 = HC/2.
IF(Y1.GT.B1) Y1=B1
IF(Y1.LT.-B1) Y1=-B1
IF(Y2.GT.B1) Y2=B1
IF(Y2.LT.-B1) Y2=-B1
Z1=B1*B1-Y1*Y1
Z2=B1*B1-Y2*Y2
IF(Z1.LT.0.0) Z1=0.0
IF(Z2.LT.0.0) Z2=0.0
CONST = 1.04720*H2*RAD*RAD/(HC*HC)
FRUST = CONST*(3*HC*HC - 12*H1*H1 - 12*H1*H2 - 4*H2*H2)
PAREA = RAD/B1*(Y2*SQRT(Z2)+B1**2*ASIN(Y2/B1))- &
           RAD/B1*(Y1*SQRT(Z1)+B1**2*ASIN(Y1/B1))
GO TO 280
!----------
!  ISHAPE=2   SOLID FORM=CONE   PLANE FORM=TRIANGLE
!----------
242 CONTINUE
CVOLUM = 1.04719*RAD*RAD*HC
CAREA = RAD*HC
CONST = 1.04720*H2
FRUST = CONST*(R1*R1+R2*R2+R1*R2)
PAREA = (R1+R2)*H2
GO TO 280
!----------
!  ISHAPE=3   SOLID FORM=NEILOID   PLANE FORM=NEILOID
!----------
243 CONTINUE
CVOLUM = 1.57079*RAD*RAD*HC
CAREA = .33333*RAD*HC
FRUST = (3.14159*RAD*RAD*H2) - &
           (1.57079*H2*RAD**2/HC)*(2*HC-2*H1-H2)
PAREA = RAD*((Y2+.66667*HC*(1-Y2/HC)**1.5) - &
                (Y1+.66667*HC*(1-Y1/HC)**1.5))
GO TO 280
!----------
!  ISHAPE=4   SOLID FORM=PARABOLOID   PLANE FORM=PARABOLA
!----------
244 CONTINUE
CVOLUM = 1.57079*RAD*RAD*HC
CAREA = 1.33333*RAD*HC
FRUST = (1.57079*H2*RAD**2/HC)*(2*HC-2*H1-H2)
PAREA = -RAD*1.33333*HC*((1-(Y2/HC))**1.5 - (1-(Y1/HC))**1.5)
GO TO 280
!----------
!  ISHAPE=5   SOLID FORM=ELLIPSOID   PLANE FORM=ELLIPSE
!----------
245 CONTINUE
CVOLUM = 2.09439*RAD*RAD*HC
CAREA = 1.57079*RAD*HC
IF (BASE.GE.LOWLIM) H1 = BASE - UPLIM
B1 = HC/2.
IF(Y1.GT.B1) Y1=B1
IF(Y1.LT.-B1) Y1=-B1
IF(Y2.GT.B1) Y2=B1
IF(Y2.LT.-B1) Y2=-B1
Z1=B1*B1-Y1*Y1
Z2=B1*B1-Y2*Y2
IF(Z1.LT.0.0) Z1=0.0
IF(Z2.LT.0.0) Z2=0.0
CONST = 1.04720*H2*RAD*RAD/(HC*HC)
FRUST = CONST*(3*HC*HC - 12*H1*H1 - 12*H1*H2 - 4*H2*H2)
PAREA = RAD/B1*(Y2*SQRT(Z2)+B1**2*ASIN(Y2/B1))- &
           RAD/B1*(Y1*SQRT(Z1)+B1**2*ASIN(Y1/B1))
280 CONTINUE
!----------
!  COMPUTE TOTAL VOLUME, PROFILE AREA, AND PROPORTION OF
!  FRUSTRUM TO TOTAL.
!----------
TREVOL = TREVOL + FRUST
TREAR = TREAR + PAREA
PROP = FRUST/CVOLUM
!----------
!  COMPUTE PROFILE AREA, CROWN VOLUME, AND FOLIAGE BIOMASS WITHIN
!  HEIGHT CLASS.
!----------
PROXHT(IP1,ITHN,J1) = PROXHT(IP1,ITHN,J1) + PAREA*PROB(I)
VOLXHT(IP1,ITHN,J1) = VOLXHT(IP1,ITHN,J1) + FRUST*PROB(I)
CFBXHT(IP1,ITHN,J1) = CFBXHT(IP1,ITHN,J1) + &
                        TRFBMS(I)*PROP*PROB(I)
!
IF (DEBUG) WRITE (JOSTND,7000) I,J1,FRUST,TREVOL,CVOLUM, &
    PAREA,TREAR,CAREA,BASE,UPLIM,LOWLIM,H1,H2,Y1,Y2,TRFBMS(I)
7000 FORMAT (I6,I3,F7.2,5F10.2,8F8.2)
!----------
!  END LAYER LOOP
!----------
290 CONTINUE
!----------
!  COMPUTE SUM OF DIAMETERS
!----------
SDIAM(IP1,ITHN) = SDIAM(IP1,ITHN) + DBH(I)*PROB(I)/12.
!----------
!  END TREE LOOP
!----------
300 CONTINUE
!----------
!  COMPUTE TOTALS FOR CANOPY VALUES.
!----------
DO 350 J = 1,16
PCXHT(IP1,ITHN,J) = CRXHT(J)/435.6
TPCTCV(IP1,ITHN) = TPCTCV(IP1,ITHN) + PCXHT(IP1,ITHN,J)
!----------
!  ADJUST HEIGHT CLASS CANOPY COVER FOR CROWN OVERLAP
!----------
PCXHT(IP1,ITHN,J) = 100.*(1.-EXP(-.01*PCXHT(IP1,ITHN,J)))
TRETOT(IP1,ITHN) = TRETOT(IP1,ITHN) + TXHT(IP1,ITHN,J)
TPROAR(IP1,ITHN) = TPROAR(IP1,ITHN) + PROXHT(IP1,ITHN,J)
TCVOL(IP1,ITHN) = TCVOL(IP1,ITHN) + VOLXHT(IP1,ITHN,J)
TOTBMS(IP1,ITHN) = TOTBMS(IP1,ITHN) + CFBXHT(IP1,ITHN,J)
350 CONTINUE
!----------
!  ADJUST TOTAL CANOPY COVER FOR CROWN OVERLAP
!----------
TPCTCV(IP1,ITHN) = 100.*(1.-EXP(-.01*TPCTCV(IP1,ITHN)))
!----------
!  COMPUTE TREE TOTALS FOR SHRUB-SMALL CONIFER DISPLAY.
!----------
IF (.NOT. LBROW) GO TO 400
J = 11
DO 399 IH = 1,10
J = J - 1
JP1 = J + 1
TRSH(IP1,ITHN,J) = TRSH(IP1,ITHN,J) + TRSH(IP1,ITHN,JP1)
399 CONTINUE
400 CONTINUE
!=======================================================================
RETURN
END
