SUBROUTINE FMSNFT(IFFEFT)
IMPLICIT NONE
!----------
! FIRE-SN $Id$
!----------
!  SINGLE-STAND VERSION
!  CALLED FROM: FMCBA, FMCFMD
!  PURPOSE:
!     THIS SUBROUTINES CALCULATES A CATEGORICAL FOREST TYPE BASED ON
!     WORKSHOP INPUT.  THIS FOREST TYPE IS USED IN SETTING DEFAULT
!     SURFACE FUEL LEVELS AND IN THE FUEL MODEL LOGIC
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'FMPARM.f90'
!
!
INCLUDE 'FMCOM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
!OMMONS
!----------
!     LOCAL VARIABLE DECLARATIONS
!----------
INTEGER IFFEFT, I
REAL    PINEBA, NPINEBA, X
!----------
!  ROUTINE BEGINS.
!  DETERMINE FFE FOREST TYPE (1 OF 8 CATEGORIES) FROM FIA FOR. TYPE
!----------
IFFEFT = 0
SELECT CASE (IFORTP)
CASE (997, 504, 505, 510, 512, 515, 519, 520)
  IFFEFT = 1 ! hardwood
CASE (103, 104, 141, 142, 161:168, 996,401, 403:407, 409)
  PINEBA = 0
  NPINEBA = 0
  DO I = 1,ITRN
    X = FMPROB(I) * DBH(I) * DBH(I) * 0.0054542
    SELECT CASE (ISP(I))
      CASE (4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14)  ! pine
        PINEBA = PINEBA + X
      CASE DEFAULT        ! non-pine
        NPINEBA = NPINEBA + X
    END SELECT
  ENDDO
  IF ((PINEBA+NPINEBA) .GT. 0) THEN
    IF ((PINEBA/(PINEBA+NPINEBA)) .LE. 0.50) THEN
      IFFEFT = 2 ! hardwood/pine
    ELSEIF ((PINEBA/(PINEBA+NPINEBA)) .LE. 0.70) THEN
      IFFEFT = 3 ! pine/hardwood
    ELSE
      IFFEFT = 4 ! pine
    ENDIF
  ENDIF
  IF (IFORTP .EQ. 162) THEN
    IF ((ATAVH .GT. 50) .AND. (ISTCL .GE. 3)) THEN
      IFFEFT = 5 ! pine bluestem
    ENDIF
  ENDIF
CASE (501, 503)
  IF ((ATAVH .GT. 30) .AND. (ISTCL .GE. 3)) THEN
    IFFEFT = 6 ! oak savannah
  ELSE
    IFFEFT = 1 ! hardwood
  ENDIF
CASE (181, 402)
  IFFEFT = 7 ! eastern redcedar
CASE (602, 605, 701, 706, 708, 807)
  IFFEFT = 8 ! saint francis types
CASE (999)
  IFFEFT = 9 ! nonstocked
CASE DEFAULT
  IFFEFT = 1 ! hardwood
END SELECT
!
RETURN
END
