SUBROUTINE ESSUBH (I,HHT,EMSQR,DILATE,DELAY,ELEV,ISER,GENTIM, &
                      TRAGE)
IMPLICIT NONE
!----------
! TT $Id$
!----------
!
!     ASSIGNS HEIGHTS TO SUBSEQUENT AND PLANTED TREE RECORDS
!     CREATED BY THE ESTABLISHMENT MODEL.
!
!
!     COMING INTO ESSUBH, TRAGE IS THE AGE OF THE TREE AS SPECIFIED ON
!     THE PLANT OR NATURAL KEYWORD.  LEAVING ESSUBH, TRAGE IS THE NUMBER
!     BETWEEN PLANTING (OR NATURAL REGENERATION) AND THE END OF THE
!     CYCLE.  AGE IS TREE AGE UP TO THE TIME REGENT WILL BEGIN GROWING
!     THE TREE.
!     CALLED FORM **ESTAB
!----------
!  COMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ESPARM.f90'
!
!
INCLUDE 'ESCOMN.f90'
!
!  COMMONS
!----------
!  DECLARATIONS
!----------
INTEGER I,ISER,N,IAGE,ITIME
REAL    HHT,DELAY,DILATE,ELEV,EMSQR,GENTIM,TRAGE,AGE
REAL    UPRE(4),AGELN,BNORM,PN
INTEGER IDANUW
!----------
! SPECIES ORDER FOR TETONS VARIANT:
!
!  1=WB,  2=LM,  3=DF,  4=PM,  5=BS,  6=AS,  7=LP,  8=ES,  9=AF, 10=PP,
! 11=UJ, 12=RM, 13=BI, 14=MM, 15=NC, 16=MC, 17=OS, 18=OH
!
! VARIANT EXPANSION:
! BS USES ES EQUATIONS FROM TT
! PM USES PI (COMMON PINYON) EQUATIONS FROM UT
! PP USES PP EQUATIONS FROM CI
! UJ AND RM USE WJ (WESTERN JUNIPER) EQUATIONS FROM UT
! BI USES BM (BIGLEAF MAPLE) EQUATIONS FROM SO
! MM USES MM EQUATIONS FROM IE
! NC AND OH USE NC (NARROWLEAF COTTONWOOD) EQUATIONS FROM CR
! MC USES MC (CURL-LEAF MTN-MAHOGANY) EQUATIONS FROM SO
! OS USES OT (OTHER SP.) EQUATIONS FROM TT
!----------
!     FOR PONDEROSA PINE FROM THE CI VARIANT,
!     UPRE HOLDS COEFFICIENTS FOR SUBSEQUENT HEIGHTS BY PREP/SPECIES
!     SITE PREP--> NONE      MECH       BURN      ROAD
!
DATA UPRE/   0.0,   0.20729,   0.18491,  0.11864 /
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
IDANUW = ISER
!----------
N=INT(DELAY+0.5)
IF(N.LT.-3) N=-3
DELAY=FLOAT(N)
ITIME=INT(TIME+0.5)
IF(N.GT.ITIME) DELAY=TIME
AGE=TIME-DELAY-GENTIM+TRAGE
IF(AGE.LT.1.0) AGE=1.0
IAGE=INT(AGE+0.5)
AGELN=ALOG(AGE)
BNORM=BNORML(IAGE)
TRAGE=TIME-DELAY
!
SELECT CASE (I)
!----------
!     HEIGHT OF TALLEST SUBSEQUENT SPECIES 1 (WB)
!----------
CASE (1)
  HHT = 1.0
!----------
!     HEIGHT OF TALLEST SUBS. SPECIES 2 (LM)
!----------
CASE (2)
  HHT = 0.5
!----------
!     HEIGHT OF TALLEST SUBS. SPECIES 3 (DF)
!----------
CASE (3)
  HHT = 2.0
!----------
!     HEIGHT OF TALLEST SUBS. SPECIES 4 (PM)
!----------
CASE (4)
  HHT = 0.5
!----------
!     HEIGHT OF TALLEST SUBS. SPECIES 6 (AS)
!----------
CASE (6)
  HHT = 5.0
!----------
!     HEIGHT OF TALLEST SUBS. SPECIES 7 (LP)
!----------
CASE (7)
  HHT = 3.0
!----------
!     HEIGHT OF TALLEST SUBS. SPECIES 5 & 8 (BS, ES)
!----------
CASE (5,8)
  HHT = 1.5
!----------
!     HEIGHT OF TALLEST SUBS. SPECIES 9 (AF)
!----------
CASE (9)
  HHT = 0.75
!----------
!     HEIGHT OF TALLEST SUBS. SPECIES 10 (PP)
!     USE PSME/CARU, CAGE, AGSP, FEID, PHMA, ACGL, SYAL, SPBE, SYOR,
!     ARUV, MISC HABITAT TYPE CONSTANT.
!----------
CASE (10)
  PN= -1.99480 +1.53946*AGELN -0.00402*BAA -0.14710 &
       +UPRE(IPREP) -0.01155*ELEV
  HHT = EXP(PN +EMSQR*DILATE*BNORM*0.49076)
!----------
!     HEIGHT OF TALLEST SUBS. SPECIES 11 (UJ)
!----------
CASE (11)
  HHT = 0.5
!----------
!     HEIGHT OF TALLEST SUBS. SPECIES 12 (RM)
!----------
CASE (12)
  HHT = 0.5
!----------
!     HEIGHT OF TALLEST SUBS. SPECIES 13 (BI)
!----------
CASE (13)
  HHT = 1.0
!----------
!     HEIGHT OF TALLEST SUBS. SPECIES 14 (MM)
!----------
CASE (14)
  HHT = 5.0
!----------
!     HEIGHT OF TALLEST SUBS. SPECIES 15 (NC)
!----------
CASE (15)
  HHT = 10.0
!----------
!     HEIGHT OF TALLEST SUBS. SPECIES 16 (MC)
!----------
CASE (16)
  HHT = 1.0
!----------
!     HEIGHT OF TALLEST SUBS. SPECIES 17 (OS)
!----------
CASE (17)
  HHT = 1.0
!----------
!     HEIGHT OF TALLEST SUBS. SPECIES 18 (OH)
!----------
CASE (18)
  HHT = 10.0
!
END SELECT
!
RETURN
END
!**END OF CODE SEGMENT



