SUBROUTINE ALGEVL (LREG,MXL,XREG,MXX,IOPCD,MXCD,IYR1,IYRCUR, &
                      LDB,JOUT,IRC)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     CALLED FROM EVMON, OPEVAL, EVTSTV, EVAGRP, HVTHN1, HVHRV1,
!                 AND HVALOC.
!
!     EVALUATES EXPRESSIONS AS COMPILED BY ALGCMP
!
!     N.L.CROOKSTON - APR 87 - FORESTRY SCIENCES LAB - MOSCOW, ID
!
!     LREG  = WORK SPACE USED TO HOLD THE LOGICAL STACK...AND...
!             (LOOK OUT FOR THIS ONE:)... THE BOTTOM OF THIS ARRAY
!             HOLDS STATUS CODES FOR CORRESPONDING MEMBERS OF XREG.
!             IF XREG(1) IS DEFINED, LREG(MXL) IS FALSE...IF XREG(2)
!             IS DEFINED LREG(MXL-2+1) IS FALSE...AND TRUE IF
!             UNDEFINED.  THIS ALLOWS THE DECADE AND TIME FUNCTIONS
!             TO IGNORE THE FACT THAT SOME ARGUMENTS ARE UNDEFINED.
!             SORRY ABOUT THIS, I JUST COULD NOT RESIST AVOIDING THE
!             CREATION OF ANOTHER ARRAY.
!     MXL   = MAX LENGTH OF LREG.
!     XREG  = WORK SPACE USED TO HOLD THE REAL STACK.
!     MXX   = MAX LENGTH OF XREG.
!     IOPCD = OPERATION CODE IN POSTFIX LOGIC.
!     MXCD  = MAX LENGTH OF IOPCD.
!     IYR1  = FIRST YEAR OF THE SIMULATION (USED BY THE DECADE FUNC.)
!     IYRCUR= CURRENT YEAR OF THE SIMULATION (USED BY THE DECADE AND
!             TIME FUNCTIONS).
!     LDEB  = TRUE IF DEBUG OUTPUT IS REQUESTED.
!     JOUT  = DEBUG OUTPUT DATA SET REFERENCE NUMBER.
!     IRC   = RETURN CODES, WHERE:
!             0=THE ANSWER YOU WANT IS LREG(1) IF THE EXPRESSION
!               IS A LOGICAL EXPRESSION OR XREG(1) IF THE EXPRESSION
!               IS AN ALGEBRAIC EXPRESSION.  IF THE PARMS FUNCTION IS
!               EXECUTED, XREG(1) IS THE NUMBER OF ARGUMENTS TO THE
!               PARMS FUNCTION AND XREG(2 TO 1+XREG(1)) IS THE
!               LIST OF ARGUMENTS.
!             1=THE OP-CODE REFERENCED AN UNDEFINED VARIABLE.
!             2=THE OP-CODE CONTAINED AN UNDECIPHERABLE CODE (OR
!               DIVIDE BY ZERO).
!             3=THE RESULT OF RUNNING THE OP-CODE LEFT VARIABLES ON
!               ONE OR BOTH OF THE STACKS.
!             4=ONE OF THE STACKS OVERFLOWED OR UNDERFLOWED.
!
EXTERNAL RANN
LOGICAL LREG(MXL),LDB
REAL XREG(MXX)
INTEGER IOPCD(MXCD)
INTEGER IRC,JOUT,IYRCUR,IYR1,MXL,MXX,MXCD,ILSTK,IXSTK,IPC
INTEGER INSTR,I,J,NDC,K,N
REAL ALGSLP,X,BACHLO
!
!     NOTE: THIS ROUTINE USES RPN LOGIC TO EVALUATE LOGICAL
!     EXPRESSIONS. LREG IS AN ANALOG TO A LOGICAL STACK IN A COMPUTER,
!     AND XREG IS AN ANALOG TO A REAL STACK.  THEY ARE LOADED BY
!     INCREMENTING A STACK POINTER, AND PLACING THE NEW VALUE IN THE
!     STACK AT THE LOCATION POINTED TO BY THE POINTER.
!
!     INITIALIZE STACK POINTERS.
!
ILSTK=0
IXSTK=0
!
!     WRITE DEBUG OUTPUT...
!
IF (LDB) WRITE (JOUT,1) MXL,MXX,MXCD,IYR1,IYRCUR
1 FORMAT (/' IN ALGEVL: MXL=',I5,'; MXX=',I5,'; MXCD=',I5, &
            '; IYR1=',I5,'; IYRCUR=',I5)
!
!     START DOWN THRU THE INSTRUCTION LIST.  THE LAST INSTRUCTION
!     WILL BE A STOP INSTRUCTION, SO BRANCH TO EXIT THE LOOP IF
!     THE OPCODE IS ZERO.
!
!     LET IPC BE A PROGRAM COUNTER.
!
DO 1000 IPC=1,MXCD
!
!     LOAD THE INSTRUCTION.
!
INSTR=IOPCD(IPC)
!
!     PRINT DEBUG INFO.
!
IF (LDB) THEN
   IF (ILSTK.GT.0) WRITE (JOUT,11) (LREG(I),I=1,ILSTK)
11    FORMAT (' LREG=',((T8,20L3)))
   IF (IXSTK.GT.0) THEN
      WRITE (JOUT,12) (XREG(I),I=1,IXSTK)
      WRITE (JOUT,11) (LREG(MXL-I+1),I=1,IXSTK)
12       FORMAT (' XREG=',((T8,5E14.6)))
   ENDIF
   WRITE (JOUT,13) IPC,INSTR,ILSTK,IXSTK
13    FORMAT (' PROG COUNTER=',I6,'; INSTR= ',I5,'; ILSTK= ',I4, &
              '; IXSTK=',I4)
ENDIF
!
!     IF INSTRUCTION IS A ZERO (END-OF-COMPUTIONS), THEN: BRANCH
!     TO EXIT LOOP.
!
IF (INSTR.EQ.0) GOTO 1020
!
!     IF THE INSTRUCTION IS A NEGATIVE NUMBER, ITS VALUE IS A
!     SPECIES CODE OR A SPECIES GROUP CODE. IF IT IS BETWEEN
!     -1 AND -1000 IT IS A SPECIES CODE AND IT NEEDS TO BE CHANGED
!     TO A POSITIVE NUMBER. IF IT IS LESS THAN -1000 THEN ADD
!     1000 TO THE NUMBER SO THAT IT IS < -1.
!     THEN LOAD THE RESULT ONTO THE XREG.
!
IF (INSTR.LT.0) THEN
   IXSTK=IXSTK+1
   IF (IXSTK.GT.MXX .OR. ILSTK.GE.MXL-IXSTK+1) GOTO 2040
   IF ((INSTR.LT.-1000).AND.(INSTR.GT.-2000)) THEN
      INSTR = INSTR+1000
!
!  IF INSTR IS LT. -1000 AND GT -2000 THEN THE INSTRUCTION IS A
!  GROUP POINT  CODE
!
   ELSEIF(INSTR.LT.-2000)THEN
      INSTR=INSTR+2000
   ELSE
      INSTR = -INSTR
   ENDIF
   XREG(IXSTK)=FLOAT(INSTR)
   LREG(MXL-IXSTK+1)=.FALSE.
   GOTO 1000
ENDIF
!
!     IS THE INSTRUCTION LOGICAL OR BOOLEAN?
!
IF (INSTR.LE.9) GOTO 20
!
!     IS THE INSTRUCTION BINARY ARITHMETIC?
!
IF (INSTR.GT.10 .AND. INSTR.LE.15) GOTO 100
!
!     IS THE INSTRUCTION UNARY ARITHMETIC (INCLUDING FUNCTIONS
!     OF ONLY ONE ARGUMENT)?
!
IF (INSTR.LE.34) GOTO 70
!
!     IS THE INSTRUCTION A FUNCTION OF MORE THAN ONE ARGUMENT?
!
IF (INSTR.GT.10000) GOTO 300
!
!     THE INSTRUCTION LOAD OPERAND: 100 < INSTR < 10000
!
IF (INSTR.GT.100 .AND. INSTR.LT.10000) GOTO 200
GOTO 2020
20 CONTINUE
!
!     INSTRUCTION IS A LOGICAL OR BOOLEAN OPERATION.
!
!     RULES FOR LOGICAL/BOOLEAN OPERATIONS:
!     OPT CODE   NAME   PROGRAM OPERATION
!     --------   ----   ---------------------------------------------
!        1       NOT    SWITCH LREG(ILSTK)
!
!        2       AND    LOGICALLY AND LREG(ILSTK+1) AND LREG(ILSTK),
!        3        OR    LOGICALLY OR LREG(ILSTK+1) AND LREG(ILSTK),
!                       STORE RESULT IN LREG(ILSTK) AND POP THE STACK.
!
!        4        EQ
!        5        NE    INCREMENT ILSTK, COMPARE XREG(IXSTK) AND
!        6        GT    XREG(IXSTK+1), AND PUT THE RESULT IN
!        7        GE    LREG(ILSTK)
!        8        LT
!        9        LE
!
IF (INSTR.EQ.1) THEN
!
!        IF THE LOGICAL STACK IS ZERO, THEN: STACK UNDERFLOW.
!
   IF (ILSTK.EQ.0) GOTO 2040
   LREG(ILSTK)=.NOT.LREG(ILSTK)
   GOTO 1000
ENDIF
IF (INSTR.LE.3) THEN
!
!        IF THE LOGICAL STACK IS LE 1, THEN: STACK UNDERFLOW.
!
   IF (ILSTK.LE.1) GOTO 2040
   ILSTK=ILSTK-1
   IF (INSTR.EQ.2) THEN
      LREG(ILSTK)=LREG(ILSTK+1).AND.LREG(ILSTK)
   ELSE
      LREG(ILSTK)=LREG(ILSTK+1).OR.LREG(ILSTK)
   ENDIF
   GOTO 1000
ENDIF
!
!     INCREMENT THE LOGICAL STACK POINTER AND DECREMENT THE REAL
!     STACK POINTER.
!
IXSTK=IXSTK-2
IF (IXSTK.LT.0) GOTO 2040
ILSTK=ILSTK+1
IF (ILSTK.GT.MXL-IXSTK) GOTO 2040
!
!     IF EITHER OPERAND IS NOT DEFINED, BRANCH TO EXIT.
!
IF (LREG(MXL-IXSTK).OR.LREG(MXL-IXSTK-1)) GOTO 2010
!
!     DECODE THE INSTRUCTION AND BRANCH TO OPERATION.
!
I=INSTR-3
SELECT CASE (I)
CASE (1)
   LREG(ILSTK)=XREG(IXSTK+1).EQ.XREG(IXSTK+2)
CASE (2)
   LREG(ILSTK)=XREG(IXSTK+1).NE.XREG(IXSTK+2)
CASE (3)
   LREG(ILSTK)=XREG(IXSTK+1).GT.XREG(IXSTK+2)
CASE (4)
   LREG(ILSTK)=XREG(IXSTK+1).GE.XREG(IXSTK+2)
CASE (5)
   LREG(ILSTK)=XREG(IXSTK+1).LT.XREG(IXSTK+2)
CASE (6)
   LREG(ILSTK)=XREG(IXSTK+1).LE.XREG(IXSTK+2)
END SELECT
GOTO 1000
70 CONTINUE
!
!     UNARY OPERATIONS.
!     OPT CODE     OPERATION         OPT CODE    OPERATION
!     --------     -------------     --------    ----------
!        16        UNARY MINUS         22        SQRT
!        23        EXP                 24        ALOG
!        25        ALOG10              26        FRAC
!        27        INT                 28        SIN
!        29        COS                 30        TAN
!        31        ARCSIN              32        ARCCOS
!        33        ARCTAN              34        ABS
!
IF (INSTR.EQ.16) THEN
   J=1
ELSE
   J=INSTR-20
   IF (J.LT.2 .OR. J.GT.14) GOTO 2020
ENDIF
!
!     ARITHMETIC UPON AN UNDEFINED VARIABLE CREATES AN UNDEFINED
!     VARIABLE.
!
IF (LREG(MXL-IXSTK+1)) GOTO 1000
SELECT CASE (J)
CASE (1)
   XREG(IXSTK)=-XREG(IXSTK)
CASE (2)
   XREG(IXSTK)=SQRT(XREG(IXSTK))
CASE (3)
   XREG(IXSTK)=EXP(XREG(IXSTK))
CASE (4)
   XREG(IXSTK)=ALOG(XREG(IXSTK))
CASE (5)
   XREG(IXSTK)=ALOG10(XREG(IXSTK))
CASE (6)
   XREG(IXSTK)=XREG(IXSTK)-AINT(XREG(IXSTK))
CASE (7)
   XREG(IXSTK)=AINT(XREG(IXSTK))
CASE (8)
   XREG(IXSTK)=SIN(XREG(IXSTK))
CASE (9)
   XREG(IXSTK)=COS(XREG(IXSTK))
CASE (10)
   XREG(IXSTK)=TAN(XREG(IXSTK))
CASE (11)
   XREG(IXSTK)=ASIN(XREG(IXSTK))
CASE (12)
   XREG(IXSTK)=ACOS(XREG(IXSTK))
CASE (13)
   XREG(IXSTK)=ATAN(XREG(IXSTK))
CASE (14)
   XREG(IXSTK)=ABS(XREG(IXSTK))
END SELECT
GOTO 1000
100 CONTINUE
!
!     BINARY OPERATIONS ON THE XREG.
!     OPT CODE     OPERATION     OPT CODE   OPERATION
!     --------     -----------   --------   ---------
!        11        PLUS             12        MINUS
!        13        MULT             14        DIVIDE
!        15        RAISE TO A POWER.
!
!     DECREMENT THE STACK POINTER.
!
IXSTK=IXSTK-1
IF (IXSTK.LE.0) GOTO 2040
!
!     ARITHMETIC UPON UNDEFINED OPERANDS CREATES AN UNDEFINED
!     RESULT.
!
LREG(MXL-IXSTK+1)=LREG(MXL-IXSTK+1).OR.LREG(MXL-IXSTK)
IF (LREG(MXL-IXSTK+1)) THEN
   XREG(IXSTK)=0.0
   GOTO 1000
ENDIF
!
!     DECODE INSTRUCTION, AND BRANCH.
!
J=INSTR-10
SELECT CASE (J)
CASE (1)
   XREG(IXSTK)=XREG(IXSTK)+XREG(IXSTK+1)
CASE (2)
   XREG(IXSTK)=XREG(IXSTK)-XREG(IXSTK+1)
CASE (3)
   XREG(IXSTK)=XREG(IXSTK)*XREG(IXSTK+1)
CASE (4)
   IF (XREG(IXSTK+1).EQ.0.0) THEN
      LREG(MXL-IXSTK+1)=.TRUE.
   ELSE
      XREG(IXSTK)=XREG(IXSTK)/XREG(IXSTK+1)
   ENDIF
CASE (5)
   XREG(IXSTK)=XREG(IXSTK)**XREG(IXSTK+1)
END SELECT
GOTO 1000
200 CONTINUE
!
!     THE INSTRUCTION IS A LOAD XREG(IXSTK) INSTRUCTION.  INCREMENT
!     IXSTK AND LOAD THE VARIABLE INTO XREG(IXSTK).  MAKE SURE THERE
!     IS ROOM FOR THE NEW X AND ITS STATUS IN LREG.
!
IXSTK=IXSTK+1
IF (IXSTK.GT.MXX .OR. ILSTK.GE.MXL-IXSTK+1) GOTO 2040
CALL EVLDX (XREG(IXSTK),1,INSTR,IRC)
LREG(MXL-IXSTK+1)=.NOT.(IRC.EQ.0)
IF (IRC.EQ.2) GOTO 2020
GOTO 1000
300 CONTINUE
!
!     OPERATIONS ON MORE THAN ONE ARGUMENT.  NN = THE NUMBER
!     OF ARGUMENTS IN THE FUNCTION.
!
!     OPT CODE     OPERATION     OPT CODE   OPERATION
!     --------     -----------   --------   ---------
!      101NN       MOD            102NN       DECADE
!      103NN       TIME           104NN       SUMSTAT
!      105NN       DBHDIST        106NN       SPMCDBH
!      107NN       PARMS          108NN       LININT
!      109NN       MIN            110NN       MAX
!      111NN       BOUND          112NN       BCCFSP
!      113NN       ACCFSP         114NN       MININDEX
!      115NN       MAXINDEX       116NN       NORMAL
!      117NN       FUELLOAD       118NN       SNAGS
!      119NN       POTFLEN        120NN       INDEX
!      121NN       POTFMORT       122NN       FUELMODS
!      123NN       SALVVOL        124NN       POINTID
!      125NN       STRSTAT        126NN       POTFTYPE
!      127NN       POTSRATE       128NN       POTREINT
!      129NN       TREEBIO        130NN       CARBSTAT
!      131NN       HTDIST         132NN       HERBSHRB
!      133NN       DWDVAL         134NN       ACORNS
!      135NN       CLSPVIAB
!
!     LET I = THE OPT CODE, 1=MOD,2=DECADE,3=TIME,...
!         J = THE NUMBER OF OPERANDS = NN
!
I=(INSTR/100)-100
J=MOD(INSTR,100)
!
!     POP THE STACK J TIMES.  IXSTK NOW POINTS TO THE LOCATION
!     OF THE RESULT.  IF THE XREG STACK HAS FEWER THAN J ENTRIES,
!     STACK UNDERFLOW HAS OCCURRED.
!
IF (IXSTK-J.LT.0) GOTO 2040
IXSTK=IXSTK-J+1
!
!     BRANCH TO EXECUTE THE OPERATION.
!
GOTO (2020,301,302,303,340,340,340,350,360,370,370,380,340,340, &
      390,390,400,340,340,340,410,340,340,340,340,340,340,340,340, &
      340,340,340,340,340,340,340,2020),(I+1)
301 CONTINUE
!
!     IF EITHER ARGUMENT IS UNDEFINED, SO IS THE RESULT.
!
LREG(MXL-IXSTK+1)=LREG(MXL-IXSTK+1).OR.LREG(MXL-IXSTK)
IF (LREG(MXL-IXSTK+1)) GOTO 1000
!
!     PROTECT AGAINST DIVISION BY ZERO.
!
IF (XREG(IXSTK+1).EQ.0.0) THEN
   LREG(MXL-IXSTK+1)=.TRUE.
ELSE
   XREG(IXSTK)=AMOD(XREG(IXSTK),XREG(IXSTK+1))
ENDIF
GOTO 1000
!
!     COMPUTE THE DECADE FUNCTION.  THE RESULT CARRIES THE DEFINED
!     OR NOT DEFINED STATUS OF THE ARGUMENT THAT IS PICKED.  THUS
!     THE DECADE FUNCTION MAY BE A DEFINED FUNCTION OF SOME, BUT NOT
!     ALL, UNDEFINED ARGUMENTS.
!
302 CONTINUE
NDC=((IYRCUR-IYR1)/10)+1
IF (NDC.GT.J) NDC=J
LREG(MXL-IXSTK+1)=LREG(MXL-IXSTK-NDC+2)
IF (.NOT.LREG(MXL-IXSTK+1)) XREG(IXSTK)=XREG(IXSTK+NDC-1)
GOTO 1000
!
!     COMPUTE THE TIME FUNCTION.  THE TIME FUNCTION IS UNDEFINED IF
!     A CRITICAL YEAR LEVEL IS UNDEFINED OR IF THE CHOSEN ARGUMENT
!     CARRIES AN UNDEFINED STATUS.
!
303 CONTINUE
IF (J.LE.2) GOTO 320
DO 310 NDC=(IXSTK+1),(IXSTK+J-1),2
XREG(IXSTK)=XREG(NDC-1)
!
!     LET THE "DEFINED" STATUS OF THE ARGUMENT FOLLOW ON THE STACK.
!
LREG(MXL-IXSTK+1)=LREG(MXL-NDC+2)
!
!     IF THERE IS AN ARGUEMENT FOLLOWING THE YEAR, THEN THE YEAR
!     IS CRITICAL TO THE RESULT.  IF THE YEAR IS UNDEFINED, SET
!     THE DEFINED STATUS OF THE RESULT TO UNDEFINED AND EXIT.
!
IF (NDC+1.LE.(IXSTK+J-1)) THEN
   IF (LREG(MXL-NDC+1)) THEN
      LREG(MXL-IXSTK+1)=.TRUE.
      GOTO 320
   ENDIF
!
!        CHECK THE YEAR, IF THE CURRENT YEAR IS GE THE YEAR ON
!        THE STACK, THEN PICK THE NEXT ARGUMENT FOLLOWING THE DATE.
!
   IF (IYRCUR.GE.IFIX(XREG(NDC))) THEN
       XREG(IXSTK)=XREG(NDC+1)
       LREG(MXL-IXSTK+1)=LREG(MXL-NDC)
   ELSE
       GOTO 320
   ENDIF
ENDIF
310 CONTINUE
320 CONTINUE
GOTO 1000
!
!     DO THE SUMSTAT, DBHDIST, BCCFSP, ACCFSP, SPMCDBH, FUELLOAD,
!          SNAGS, POTFLEN, POTFMORT, FUELMODS, SALVVOL,
!          POINTID, STRSTAT, POTFTYPE, POTSRATE, POTREINT, TREEBIO,
!          HTDIST, HERBSHRB, DWDVAL AND ACORNS FUNCTIONS.
!     PROCESS CLSPVIAB
!
340 CONTINUE
!
!     ALL THE ARGUMENTS MUST BE DEFINED.
!
DO 345 NDC=(IXSTK+1),(IXSTK+J-1)
LREG(MXL-IXSTK+1)=LREG(MXL-NDC+2)
IF (LREG(MXL-IXSTK+1)) GOTO 1000
345 CONTINUE
!
CALL EVLDX (XREG(IXSTK),MXX-IXSTK+1,INSTR,IRC)
LREG(MXL-IXSTK+1)=.NOT.(IRC.EQ.0)
IF (IRC.EQ.2) GOTO 2020
GOTO 1000
!
!     DO THE PARMS FUNCTION.
!     LREG(1) IS TRUE IF ALL PARMS ARE DEFINED, FALSE OTHERWISE
!     XREG(1) IS THE NUMBER OF PARAMETERS
!     XREG(2) IS THE FIRST PARAMETER, LREG(2) IS TRUE IF XREG(2)
!                                     IS DEFINED, FALSE OTHERWISE
!     XREG(3) IS THE SECOND, LREG(3) IS TRUE IF XREG(3) IS DEFINED
!     XREG(N+1) IS THE NTH, LREG(N+1) IS TRUE IF XREG(N+1) IS DEFINED
!
!     THE NUMBER OF ARGUMENTS J SHOULD BE EQUAL TO THE NUMBER OF VALUES
!     ON THE XREG AND THE MAX SIZE OF LREG MUST BE 2*J+1 OR LARGER.
!
350 CONTINUE
IF (J+1.GT.MXX .OR. J*2+1.GT.MXL) GOTO 2040
LREG(1)=.TRUE.
K=MXL
DO 355 NDC=J+1,2,-1
XREG(NDC)=XREG(NDC-1)
LREG(NDC)=LREG(K)
K=K-1
LREG(1)=LREG(1).AND. .NOT.LREG(NDC)
355 CONTINUE
XREG(1)=J
LREG(MXL)=.NOT.LREG(1)
GOTO 1000
360 CONTINUE
!
!     EVALUATE THE LINEAR INTERPOLATION FUNCTION.
!
IF (J.GE.5 .AND. MOD(J-1,2).EQ.0) THEN
   DO 362 K=1,J
   IF (LREG(MXL-IXSTK+2-K)) GOTO 366
362    CONTINUE
   XREG(IXSTK)=ALGSLP(XREG(IXSTK),XREG(IXSTK+1), &
                         XREG(IXSTK+((J-1)/2)+1),(J-1)/2)
   LREG(MXL-IXSTK+1)=.FALSE.
   GOTO 1000
ENDIF
366 CONTINUE
LREG(MXL-IXSTK+1)=.TRUE.
XREG(IXSTK)=0.0
GOTO 1000
370 CONTINUE
!
!     COMPUTE THE MIN AND MAX FUNCTIONS.  IF THERE IS ONLY ONE ARG,
!     THE MIN OR MAX IS EQUAL TO THE ARG, SO SIMPLY BRANCH TO 1000.
!     USE THE FORTRAN MIN,MAX FUNCTIONS IN A PAIR-WISE MANNER.
!
IF (J.EQ.1) THEN
   IF (LREG(MXL-IXSTK+1)) GOTO 376
   GOTO 1000
ENDIF
DO 372 K=2,J
IF (LREG(MXL-IXSTK+2-K)) GOTO 376
IF (I.EQ.9) THEN
   XREG(IXSTK)=AMIN1(XREG(IXSTK),XREG(IXSTK+K-1))
ELSE
   XREG(IXSTK)=AMAX1(XREG(IXSTK),XREG(IXSTK+K-1))
ENDIF
372 CONTINUE
GOTO 1000
376 CONTINUE
LREG(MXL-IXSTK+1)=.TRUE.
XREG(IXSTK)=0.0
GOTO 1000
380 CONTINUE
!
!     COMPUTE THE BOUND FUNCTION
!
IF (J.NE.3) GOTO 2040
IF  (LREG(MXL-IXSTK+1).OR.LREG(MXL-IXSTK).OR.LREG(MXL-IXSTK-1) &
       .OR.XREG(IXSTK).GE.XREG(IXSTK+2)) GOTO 366
XREG(IXSTK)=AMIN1(AMAX1(XREG(IXSTK),XREG(IXSTK+1)),XREG(IXSTK+2))
GOTO 1000
390 CONTINUE
!
!     COMPUTE THE MININDEX AND MAXINDEX FUNCTIONS.
!
IF (J.EQ.1) THEN
   IF (LREG(MXL-IXSTK+1)) GOTO 396
   XREG(IXSTK)=1.0
   GOTO 1000
ENDIF
N=0
IF (I.EQ.14) THEN
   X=1E30
ELSE
   X=-1E30
ENDIF
DO 392 K=1,J
IF (LREG(MXL-IXSTK+2-K)) GOTO 396
IF (I.EQ.14) THEN
   IF (XREG(IXSTK+K-1).LT.X) THEN
      N=K
      X=XREG(IXSTK+K-1)
   ENDIF
ELSE
   IF (XREG(IXSTK+K-1).GT.X) THEN
      N=K
      X=XREG(IXSTK+K-1)
   ENDIF
ENDIF
392 CONTINUE
IF (N.EQ.0) GOTO 2040
XREG(IXSTK)=N
GOTO 1000
396 CONTINUE
LREG(MXL-IXSTK+1)=.TRUE.
XREG(IXSTK)=0.0
GOTO 1000
!
!     COMPUTE THE NORMAL FUNCTION.
!
400 CONTINUE
!
!     IF EITHER ARGUMENT IS UNDEFINED, SO IS THE RESULT...
!     AND THERE MUST BE EXACTLY 2 ARGUMENTS.
!
LREG(MXL-IXSTK+1)=(J.NE.2).OR.LREG(MXL-IXSTK+1).OR. &
                                 LREG(MXL-IXSTK)
IF (LREG(MXL-IXSTK+1)) GOTO 1000
XREG(IXSTK)=BACHLO(XREG(IXSTK), XREG(IXSTK+1), RANN)
GOTO 1000
!
!     COMPUTE THE INDEX FUNCTION.
!
410 CONTINUE
IF (J.LT.2) THEN
   LREG(MXL-IXSTK+1)=.TRUE.
   XREG(IXSTK)=0.0
   GOTO 1000
ENDIF

!     IF FIRST ARGUMENT IS UNDEFINED, THE FUNCTION IS UNDEFINED.

IF (LREG(MXL-IXSTK+1)) THEN
   XREG(IXSTK)=0.0
   GOTO 1000
ENDIF

!     K IS THE ARGUMENT WE WANT...BOUNDED TO THE NUMBER OF ARGUMENTS.

K = IFIX(XREG(IXSTK)+.5)
IF (K.LT.1) K=1
IF (K.GT.J-1) K=J-1

!     IF THE ARGUMENT WE WANT IS UNDEFINED, THEN THE RESULT IS UNDEFINED.

IF (LREG(MXL-IXSTK+1-K)) THEN
   LREG(MXL-IXSTK+1)=.TRUE.
   XREG(IXSTK)=0.0
   GOTO 1000
ENDIF

XREG(IXSTK) = XREG(IXSTK+K)
LREG(MXL-IXSTK+1)=.FALSE.
GOTO 1000
!
1000 CONTINUE
1020 CONTINUE
!
!     END OF COMPUTATIONS.
!
IF (ILSTK+IXSTK.EQ.1) THEN
   IRC=0
ELSE
   IRC=3
ENDIF
!
!     IF THE RESULT IS UNDEFINED, BRANCH TO CORRECT RETURN CODE.
!
IF (LREG(MXL)) GOTO 2010
RETURN
2010 CONTINUE
IRC=1
RETURN
2020 CONTINUE
IRC=2
RETURN
2040 CONTINUE
IRC=4
RETURN
END
