SUBROUTINE ALGSPP (CTOK,LEN,NUM,IRC)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     CALLED FROM ALGKEY
!
!     CONVERTS CTOK TO A SPECIES CODE LOAD OPERATION.
!
!     CTOK  = C*10 TOKEN FOUND IN AN EXPRESSION.
!     LEN   = THE LENGTH OF THE TOKEN.
!     NUM   = THE LOAD OP-CODE FOR THE SPECIES.
!     IRC   = RETURN CODE, 0=CTOK WAS FOUND, NUM IS DEFINED.
!             1=CTOK WAS NOT FOUND, NUM IS UNDEFINED.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
!OMMONS
!
CHARACTER*20 CTOK,CTEMP
INTEGER IRC,NUM,LEN,I
!
!     IF CTOK IS A 1 CHAR TOKEN, THEN RIGHT JUSTIFY.  OTHERWISE
!     SIMPLY LOAD CTOK INTO CTEMP.
!
CTEMP(1:20)=''
IF (LEN.EQ.1) THEN
   CTEMP(1:1)=' '
   CTEMP(2:2)=CTOK(1:1)
ELSE
   CTEMP=CTOK
ENDIF
!
!     SEARCH THROUGH SPECIES CODES.
!
DO 10 I=1,MAXSP
IF (CTEMP.EQ.NSP(I,1)(1:2)) THEN
   NUM=-I
   GOTO 100
ENDIF
10 CONTINUE
!
!     SEARCH TRHOUGH SPECIES GROUP CODES.
!
  DO 955 I=1,NSPGRP
  IF(CTOK(1:LEN).EQ.NAMGRP(I))THEN
    NUM=-(I+1000)
    IRC=0
    GOTO 100
  ENDIF
955   CONTINUE
!
IRC=1
RETURN
100 CONTINUE
IRC=0
RETURN
END
