SUBROUTINE AUTCOR (COV,VRNEXT)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!  PROCEDURE FOR CALCULATING EFFECT OF CYCLE LENGTH ON RANDOM COMPONENT OF
!  DIAMETER INCREMENT AND ITS AUTO-REGRESSIVE PROPERTIES.
!  PROCEDURE ASSUMES ANNUAL TREE RINGS ARE CHARACTERIZED BY ARMA(1,1)
!  TIME SERIES MODEL.  PERIODIC INCREMENT IS CONSIDERED TO BE DISTRIBUTED
!  AS THE SUM OF IFINT RANDOM VALUES WITH VARIANCE-COVARIANCE MATRIX
!  DEFINED BY THE SERIAL CORRELATION FUNCTION OF THE ARMA(1,1) MODEL.
!----------
!OMMON
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'COEFFS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'PDEN.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
!OMMON
!
!----------
INTEGER I,NEW,NOLD,NLIM,L,NBIG,NSML
REAL DT,T,COVAR,VAR,COV,VRNEXT
!----------
IF ( .NOT.LSTART ) GO TO 100
!----------
!  INITIALIZE SERIAL CORRELATION FUNCTION FROM ARMA(1,1) PARAMETERS.
!----------
BJRHO(1) = ( 1.-BJPHI*BJTHET)*(BJPHI-BJTHET)/ &
          (1.+BJTHET*(BJTHET-2.*BJPHI))
DO 50 I = 2, 40
  BJRHO(I) = BJRHO(I-1)*BJPHI
50 CONTINUE
!----------
!  PRECOMPUTE VARIANCE AND COVARIANCE MULTIPLIERS FOR "YR" YEARS.
!----------
NEW = INT(YR)
NOLD = INT(YR)
GO TO 105
100 CONTINUE
NEW = IFINT
NOLD = INT(OLDFNT)
!----------
!  CALCULATE VARIANCE MULTIPLIER FOR CURRENT CYCLE.
!----------
105 CONTINUE
NLIM = NEW - 1
VAR = 0.0
DO 110 I = 1,NLIM
  VAR = VAR + BJRHO(I)*( NEW - I )
110 CONTINUE
VAR = NEW + 2.*VAR
VRNEXT = VAR
!----------
!  CALCULATE MULTIPLIER FOR COVARIANCE BETWEEN CURRENT AND PRECEDING
!  CYCLES.
!----------
COVAR = 0.0
L = NEW + NOLD -1
IF ( L .GT. 40 )  L = 40
!----------
!  PREPARE TO LOOP OVER LARGER DIMENSION OF COVARIANCE MATRIX.
!----------
NBIG = NEW
NSML = NOLD
IF ( NEW .GT. NOLD ) GO  TO 120
NBIG = NOLD
NSML = NEW
120 CONTINUE
T = 0.
DT = 1.
DO 130 I = 1,L
T = T + DT
COVAR = COVAR + BJRHO(I)*T
IF ( I .EQ. NSML ) DT=0.0
IF ( I .EQ. NBIG ) DT = -1.
130 CONTINUE
COV = COVAR
RETURN
END
