SUBROUTINE BASDAM(ITREE,ICODES)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!  SUBROUTINE TO PROCESS THE SPECIAL TREE STATUS CODES, AND
!  PERCENT DEFECT CODES.
!----------
!
!     ITREE  = TREE POINTER FOR LIVE TREES.
!     ICODES = DAMAGE CODES ARRAY.
!              25 = PERCENT DEFECT CODE FOR BOTH MERCH CF AND BF
!              26 = PERCENT DEFECT CODE FOR MERCH CUBIC FOOT VOLUME
!              27 = PERCENT DEFECT CODE FOR MERCH BOARD FOOT VOLUME
!              28 = SITE TREE CODE; PROCESSED IN INTREE
!              55 = SPECIAL STATUS CODE
!
!    DEFECT() VALUES ARE CODED 11223344, WHERE
!       11 = INPUT MC DEFECT PERCENT
!       22 = INPUT BF DEFECT PERCENT
!       33 = MC DEFECT % USED FOR A GIVEN CYCLE
!       44 = BF DEFECT % USED FOR A GIVEN CYCLE
!
!  COMMONS
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
!  COMMONS
!----------
INTEGER ICODES(6),ITREE,J,ITEMP
!----------
!  INITIALIZE BASE MODEL DEFECT AND SPECIAL STATUS VECTORS.
!----------
ISPECL(ITREE)=0
DEFECT(ITREE)=0
!----------
!  PROCESS CODES.
!----------
DO 100 J=1,5,2
   IF(ICODES(J).EQ.25 .OR. ICODES(J).EQ.26) THEN
      ITEMP=ICODES(J+1)
      IF(ITEMP .GT. 99) ITEMP = 99
      IF(ITEMP .LT.  0) ITEMP = 0
      DEFECT(ITREE) = DEFECT(ITREE) + ITEMP*1000000
   ENDIF
   IF(ICODES(J).EQ.25 .OR. ICODES(J).EQ.27) THEN
      ITEMP=ICODES(J+1)
      IF(ITEMP .GT. 99) ITEMP = 99
      IF(ITEMP .LT.  0) ITEMP = 0
      DEFECT(ITREE) = DEFECT(ITREE) + ITEMP*10000
   ENDIF
   IF(ICODES(J).EQ.55) THEN
      ISPECL(ITREE)=ICODES(J+1)
      IF(ISPECL(ITREE).GT.99) ISPECL(ITREE)=99
      IF(ISPECL(ITREE).LT.0) ISPECL(ITREE)=0
   ENDIF
100 CONTINUE
RETURN
END
