SUBROUTINE BEHPRM (VMAX,D,H,BARK,LCONE)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!  SUBROUTINE TO COMPUTE THE TREE SPECIFIC PARAMETERS FOR THE
!  BEHRE HYPERBOLA   (I.E. AHAT, BHAT, LCONE)
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'COEFFS.f90'
!
!
!OMMONS
!
LOGICAL LCONE
REAL BARK,H,D,VMAX
!
LCONE=.FALSE.
!----------
!  BHAT IS INITIALIZED WITH VALUE OF CYLINDRICAL FORM FACTOR.
!----------
BHAT = VMAX / (.00545415*D*D*BARK*BARK*H)
IF(BHAT.GT.0.95) BHAT = 0.95
!----------
!     AHAT = AN ESTIMATE OF THE BEHRE TAPER CURVE PARAMETER 'A'
!----------
AHAT = .44277 - .99167/BHAT - 1.43237*ALOG(BHAT) &
          + 1.68581*SQRT(BHAT) - .13611*BHAT*BHAT
IF(ABS(AHAT) .LT. 0.05) THEN
  LCONE=.TRUE.
  IF(AHAT.LT. 0.) THEN
    AHAT = -0.05
  ELSE
    AHAT = 0.05
  ENDIF
ENDIF
BHAT = 1.-AHAT
IF (BHAT .LT. 0.0001) BHAT=0.0001
RETURN
END
