SUBROUTINE BFTOPK(ISPC,D,H,BBFV,LCONE,BARK,VMAX,ITHT)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!    THIS SUBROUTINE CORRECTS BOARD FOOT VOLUMES FOR DEAD/DAMAGED
!    TOPS.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'COEFFS.f90'
!
!
INCLUDE 'VOLSTD.f90'
!
!
!OMMONS
!
LOGICAL LCONE
INTEGER ITHT,ISPC
REAL VMAX,BARK,BBFV,H,D,HTRUNC,PHT,DTRUNC,HTMRCH,STUMP
REAL VOLTK,BEHRE,VOLM
!----------
!  SET PARAMETERS FOR BEHRE HYPERBOLA.
!----------
IF(BBFV .LE. 0.) GO TO 100
CALL BEHPRM (VMAX,D,H,BARK,LCONE)
!----------
!  COMPUTE TOTAL BOARD FOOT VOLUME LOSS DUE TO TOPKILL.
!  HEIGHT AND DIAMETER AT THE POINT OF TRUNCATION ARE EXPRESSED
!  AS RATIOS OF "NORMAL" HEIGHT AND DBH (PHT AND DTRUNC,
!  RESPECTIVELY).
!----------
HTRUNC = ITHT / 100.0
PHT = 1. - (HTRUNC/H)
DTRUNC = PHT / (AHAT*PHT + BHAT)
!----------
!  IF THE TOP IS DAMAGED AND THE DIAMETER AT THE POINT OF
!  TRUNCATION IS GREATER THAN THE MERCHANTABLE TOP DIAMETER,
!  CORRECT BOARD FOOT VOLUME ESTIMATE.
!----------
IF(DTRUNC .GT. BFTOPD(ISPC)/D) THEN
!----------
!     HTMRCH = RATIO OF MERCH. HT (HEIGHT WHERE D=BFTOPD) TO TOTAL
!     HEIGHT.
!----------
  HTMRCH = ((BHAT*BFTOPD(ISPC))/D)/(1. - (AHAT*BFTOPD(ISPC)/D))
!----------
!     ADJUST THE STUMP HEIGHT.
!----------
  STUMP=1.0-BFSTMP(ISPC)/H
  VOLTK=BEHRE(PHT,STUMP)
!----------
!     CORRECT FOR THE TRUNCATED TOP IN THE BFV ESTIMATE
!----------
  IF (LCONE) THEN
    VOLM = STUMP**3-HTMRCH**3.
    VOLTK = STUMP**3. - PHT**3.
    BBFV = BBFV*VOLTK/VOLM
  ELSE
    BBFV = (BBFV*VOLTK) / BEHRE(HTMRCH,STUMP)
  ENDIF
ENDIF
100 CONTINUE
RETURN
END
