!ODE SEGMENT CALDEN
!----------
! COMMON $Id$
!----------
!
REAL TPACRE
!
REAL BAAINV(MAXPLT),TPAAINV(MAXPLT)
!
COMMON /CALDEN/ BAAINV,TPACRE,TPAAINV
!
!----------
!  DEFINITIONS OF VARIABLES IN 'CALDEN' COMMON BLOCK:
!----------
!  TPACRE  -- INVENTORY TREES PER ACRE IN STAND, SET IN ESFLTR.F
!  BAAINV  -- INVENTORY BASAL AREA PER ACRE PER PLOT >= REGNBK,
!             SET IN ESFLTR.F
!  TPAAINV -- INVENTORY TREES PER ACRE PER PLOT >= REGNBK,
!             SET IN ESFLTR.F
!-----END SEGMENT
