!ODE SEGMENT COEFFS
!----------
! COMMON $Id$
!----------
!
INTEGER IORDER(MAXSP)
!
REAL    AHAT,BHAT,BJPHI,BJTHET,H2COF,HDGCOF
!
REAL    ATTEN(MAXSP),BFDEFT(9,MAXSP),BFLA0(MAXSP),BFLA1(MAXSP), &
           BJRHO(40),BKRAT(MAXSP),CFDEFT(9,MAXSP),CFLA0(MAXSP), &
           CFLA1(MAXSP),COR(MAXSP),COR2(MAXSP),CRCON(MAXSP), &
           DGCCF(MAXSP),DGCON(MAXSP),DGDSQ(MAXSP),DIFH(MAXSP), &
           FL(MAXSP),FM(MAXSP),FU(MAXSP),HT1(MAXSP),HT2(MAXSP), &
           HTCON(MAXSP),RHCON(MAXSP),SIGMA(MAXSP),SIGMAR(MAXSP), &
           SMCON(MAXSP),VARDG(MAXSP),WCI(MAXSP)
!
COMMON /COEFFS/ AHAT,ATTEN,BFDEFT,BFLA0,BFLA1,BHAT,BJPHI,BJRHO, &
                   BJTHET,BKRAT,CFDEFT,CFLA0,CFLA1,COR,COR2,CRCON, &
                   DGCCF,DGCON,DGDSQ,DIFH,FL,FM,FU,H2COF,HDGCOF, &
                   HT1,HT2,HTCON,IORDER,RHCON,SIGMA,SIGMAR,SMCON, &
                   VARDG,WCI
!
!----------
!  DEFINITIONS OF VARIABLES IN 'COEFFS' COMMON BLOCK:
!  (THIS COMMON IS FOR MODEL COEFFICIENTS WHICH ARE HABITAT
!  AND SITE DEPENDENT.  RDH AND RDSC ARE LOADED IN **BLOCK DATA**;
!  COR, COR2, AND CORTEM ARE LOADED BY INPUT AND CALIBRATION;
!  IORDER IS LOADED IN **INITRE**; OTHER VARIABLES ARE LOADED IN
!  **RCON**.  ARRAYS ARE SUBSCRIPTED BY SPECIES.)
!----------
!
!      AHAT -- AN ESTIMATE OF THE BEHRE TAPER CURVE PARAMETER 'A'.
!     ATTEN -- NUMBER OF OBSERVATIONS ON WHICH THE DIAMETER
!              INCREMENT MODEL FOR EACH SPECIES IS BASED.  THIS
!              IS USED TO WEIGHT THE CALCULATED CORRECTION TERM.
!    BFDEFT -- ARRAY HOLDING THE PERCENTAGE OF BOARD FOOT VOLUME DEFECT
!              FOR SPECIFIED DIAMETER CLASSES. KEYWORD MODIFIED.
!     BFLA0 -- CONSTANT TERMS FOR BOARD FOOT FORM-DEFECT CORRECTION
!              EQUATIONS.
!     BFLA1 -- COEFFICIENTS FOR LINEAR TERMS IN BOARD FOOT FORM-
!              DEFECT CORRECTION EQUATIONS.
!      BHAT -- AN ESTIMATE OF THE BEHRE TAPER CURVE PARAMETER 'B'.
!    BJPHI  -- MOVING-AVERAGE PARAMETER IN BOX-JENKINS ARMA MODEL.
!    BJRHO  -- SERIAL CORRELATION AT LAG=J YEARS OF ARMA MODEL WITH
!              PARAMETERS BJTHET AND BJPHI.
!    BJTHET -- AUTO-REGRESSIVE PARM IN BOX-JENKINS ARMA(1,1) MODEL.
!     BKRAT -- RATIO OF DBH INSIDE BARK TO BAH OUTSIDE BARK BY
!              SPECIES. INITIALIZED IN BLKDATA.
!    CFDEFT -- ARRAY HOLDING THE PERCENTAGE OF CUBIC VOLUME DEFECT FOR
!              SPECIFIED DIAMETER CLASSES. DEFAULTS CAN BE KEYWORD
!              MODIFIED.
!     CFLA0 -- COEFFICIENTS FOR LINEAR TERMS IN CUBIC FOOT FORM-
!              DEFECT CORRECTION EQUATIONS.
!     CFLA1 -- COEFFICIENTS FOR QUADRATIC TERMS IN CUBIC FOOT FORM-
!              DEFECT CORRECTION EQUATIONS.
!       COR -- DIAMETER GROWTH MODEL CORRECTION TERMS.  COMPUTED IN
!              **DGDRIV**.   STORED IN ADDITIVE FORM.
!      COR2 -- USED TO STORE VALUES OF CORRECTION TERMS ON INPUT.
!              STORED IN MULTIPLICATIVE FORM.  READ BY KEYWORD
!              CONTROL.
!     CRCON -- CONSTANT TERMS FOR CROWN RATIO MODELS.  COMBINE
!              HABITAT TYPE, SLOPE, ASPECT, AND ELEVATION EFFECTS.
!     DGCCF --
!     DGCON -- CONSTANT TERMS FOR DIAMETER GROWTH MODELS. COMBINE
!              HABITAT TYPE, SLOPE, ASPECT, AND ELEVATION EFFECTS.
!     DGDSQ --
!      DIFH -- ATTUNATION VECTOR FOR REGENT HEIGHT GROWTH MODEL.
!        FL -- MULTIPLIER FOR DECELERATED DIAMETER GROWTH ESTIMATE
!              WHEN RECORD TRIPLING.  COMPUTED BY SPECIES IN DGDRIV
!              DURING RECORD CALIBRATION.
!        FM -- MULTIPLIER MOR MIDDLE DIAMETER GROWTH ESTIMATE WHEN
!              RECORD TRIPLING.  COMPUTED BY SPECIES IN DGDRIV DURING
!              CALIBRATION.
!        FU -- MULTIPLIER FOR ACCELERATED DIAMETER GROWTH ESTIMATE
!              WHEN RECORD TRIPLING.  COMPUTED BY SPECIES IN DGDRIV
!              DURING CALIBRATION.
!     H2COF -- COEFFICIENT FOR HEIGHT SQUARED TERM IN HEIGHT
!              INCREMENT MODEL.  DEPENDENT ON HABITAT TYPE.
!    HDGCOF -- COEFFICIENTS FOR DIAMETER GROWTH TERMS IN HEIGHT
!              INCREMENT MODELS.  DEPENDENT ON HABITAT TYPE.
!       HT1 -- DEFAULT COEFICIENTS FOR HEIGHT DIAMETER RELATIONSHIP
!       HT2    SUBSCRIPTED BY SPECIES. THESE COEFFICIENTS ARE USED IN
!              CRATET FOR CALIBRATING HEIGHT-DIAMETER EQUATIONS.
!     HTCON -- CONSTANT TERMS IN HEIGHT GROWTH MODEL.  DEPENDENT
!              ON HABITAT TYPE.
!    IORDER -- THINNING SELECTION PRIORITIES.  DEFAULT VALUES ARE
!              HABITAT DEPENDENT, BUT CAN BE REPLACED BY KEYWORD
!              CONTROL.  DEFINED IN **INITRE**
!       RDH -- COEFFICIENTS FOR HEIGHT TERMS IN SMALL TREE HEIGHT-
!              DIAMETER EQUATIONS.
!      RDSC -- CONSTANT TERMS IN SMALL TREE HEIGHT-DIAMETER EQUATIONS.
!     RHCON -- CONSTANT TERMS FOR SMALL TREE HEIGHT GROWTH EQUATIONS.
!              COMBINE HABITAT TYPE, SLOPE, ASPECT, AND ELEVATION
!              EFFECTS.
!     SIGMA -- POOLED VARIANCE ESTIMATE FOR THE DIAMETER GROWTH
!              MODEL.  COMPUTED IN DGDRIV DURING CALIBRATION.
!    SIGMAR -- REGRESSION ESTIMATES OF THE STANDARD ERRORS FOR THE
!              IMBEDDED MODELS. LOADED IN DGCONS AND USED IN DGDRIV.
!     SMCON -- CONSTANT TERMS FOR DIAMETER GROWTH MODELS FOR TREES < 10.
!              COMBINES HABITAT TYPE, SLOPE, ASPECT, AND ELEVATION EFFECTS.
!       WCI -- USED INITIALLY TO STORE BAYESIAN GROWTH SAMPLE TREE
!              WEIGHTS FOR DIAMETER GROWTH MODEL CALIBRATION.  THERE-
!              AFTER STORED ASYMPTOTE FOR CORRECTION TERM ATTENTUATION.
!              COMPUTED BY SPECIES IN FIRST CYCLE IN DGDRIV.
!     VARDG --
!
!----------
!     CCF COEFFICIENTS ARE LOADED IN RCON.
!     CCF COEFFICIENTS FOR TREES THAT ARE GREATER THAN 10.0 IN. DBH:
!
!      RD1 -- CONSTANT TERM IN CROWN COMPETITION FACTOR EQUATION,
!             SUBSCRIPTED BY SPECIES
!
!      RD2 -- COEFFICIENT FOR SUM OF DIAMETERS TERM IN CROWN
!             COMPETITION FACTOR EQUATION,SUBSCRIPTED BY
!             SPECIES
!
!      RD3 -- COEFFICIENT FOR SUM OF DIAMETER SQUARED TERM IN
!             CROWN COMPETITION EQUATION, SUBSCRIPTED BY SPECIES
!
!     CCF COEFFICIENTS FOR TREES THAT ARE LESS THAN 10.0 IN. DBH:
!
!      RDA -- MULTIPLIER.
!
!      RDB -- EXPONENT.  CCF(I) = EXP( RDA*DBH**RDB )
!
!-----END SEGMENT
