SUBROUTINE COMP(CMP,ICMP,ATTR)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!  THIS SUBROUTINE COMPUTES THE PERCENTAGE OF A GIVEN STAND
!  ATTRIBUTE IN EACH SPECIES-TREE CLASS.  IT THEN LOADS CMP
!  WITH THE FOUR LARGEST CLASSES AND LOADS ICMP WITH
!  CORRESPONDING SPECIES-TREE CLASS LABELS.
!----------
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
!OMMONS
!
INTEGER MXSP3
PARAMETER (MXSP3=MAXSP*3)
INTEGER J,I1,I2,I,ISPC,JMC,K
REAL WORK1(MXSP3),WORK2(MXSP3),ATTR(MAXSP,3),CMP(4),TTT
!
!----------
!  TYPE DECLARATIONS FOR INTERNAL VARIABLES.
!----------
CHARACTER*3 ICMP(4),NS
INTEGER IDS(MXSP3)
!----------
!  DATA STATEMENTS AND INITIALIZATIONS.
!----------
DATA NS/'---'/
IF (ITRN.LE.0) GOTO 30
J=0
DO I1=1,MAXSP
  DO I2=1,3
    J=J+1
    WORK1(J)=ATTR(I1,I2)
  ENDDO
ENDDO
!----------
!  SORT THE ATTRIBUTE ARRAY IN DESCENDING ORDER.
!----------
CALL RDPSRT(MXSP3,WORK1,IDS,.TRUE.)
!----------
!  COMPUTE THE PERCENTAGE OF THE ATTRIBUTE IN EACH SPECIES-TREE
!  CLASS.
!----------
CALL PCTILE(MXSP3,IDS,WORK1,WORK2,TTT)
!----------
!  FIND INDEX FOR SPECIES-TREE CLASS AND LOAD CMP AND ICMP.
!  ISPC REFERENCES SPECIES, AND JMC REFERENCES TREE CLASS.
!----------
DO 20 I=1,4
J=IDS(I)
ISPC=(J+2)/3
JMC=MOD(J,3)
IF(JMC.EQ.0) JMC=3
K=IDS(I+1)
CMP(I)=WORK2(J)-WORK2(K)
ICMP(I)=NSP(ISPC,JMC)(1:3)
IF(CMP(I).LE.0.0) ICMP(I)=NS
20 CONTINUE
RETURN
30 CONTINUE
!-------
!  BRANCH HERE IF THERE ARE NO TREE RECORDS
!-------
DO 40 I=1,4
CMP(I)=0.
ICMP(I)=NS
40 CONTINUE
RETURN
END
