SUBROUTINE CWIDTH
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!  THIS SUBROUTINE COMPUTES A CROWN WIDTH FOR EACH TREE RECORD USING
!  EITHER USER-DEFINED EQUATIONS OR DEFAULT EQUATIONS. IT ALSO
!  PROCESSES CROWN WIDTH MODIFIERS ENTERED VIA THE FIXCW KEYWORD.
!  THIS ROUTINE IS CALLED FROM **MAIN** TO LOAD THE INITIAL CROWN
!  WIDTHS, AND FROM **UPDATE** TO LOAD THE END-OF-CYCLE VALUES.
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'CWDCOM.f90'
!
!
!OMMONS
!----------
!  DEFINITIONS:
!
!        I -- TREE SUBSCRIPT.
!        D -- TREE DIAMETER.
!        P -- NUMBER OF TREES PER ACRE REPRESENTED BY A TREE.
!----------
LOGICAL DEBUG,LINCL
REAL PRM(5)
INTEGER MYACTS(1)
INTEGER IG,IULIM,IGRP,ISPCC,IDATE,IACTK,NP,ITODO,NTODO,IWHO,IICR
INTEGER ISPC,I
REAL P,D,H,CR,CW
!----------
!  DATA STATEMENTS.
!  ACTIVITY 90 = FIXCW
!----------
DATA MYACTS/90/
!-----------
!  CHECK FOR DEBUG.
!-----------
CALL DBCHK (DEBUG,'CWIDTH',6,ICYC)
IF(DEBUG)WRITE(JOSTND,*)' ENTERING CWIDTH ICYC,ITRN= ',ICYC,ITRN
!---------
!  IF THERE ARE NO TREE RECORDS, SIMPLY PROCESS THE FIXCW REQUESTS.
!---------
IF (ITRN.LE.0) GOTO 100
!----------
!  START LOOP TO ESTIMATE CROWN WIDTH.  TREES ARE PROCESSED
!  ONE AT A TIME WITHIN A SPECIES.
!----------
DO 50 I=1,ITRN
ISPC=ISP(I)
P=PROB(I)
D=DBH(I)
H=HT(I)
CR=FLOAT(ICR(I))
IICR=ICR(I)
CRWDTH(I)=0.0
IF(LSPCWE(ISPC))THEN
  IF(D .LT. CWTDBH(ISPC))THEN
    CW=CWDS0(ISPC)+CWDS1(ISPC)*DBH(I)+ &
          CWDS2(ISPC)*(DBH(I)**CWDS3(ISPC))
  ELSE
    CW=CWDL0(ISPC)+CWDL1(ISPC)*DBH(I)+ &
          CWDL2(ISPC)*(DBH(I)**CWDL3(ISPC))
  ENDIF
ELSE
  IWHO=0
  CALL CWCALC(ISPC,P,D,H,CR,IICR,CW,IWHO,JOSTND)
ENDIF
CRWDTH(I)=CW
IF(DEBUG)WRITE(JOSTND,*)' LIVE: I,ISPC,D,CR,CW= ', &
   I,ISPC,D,CR,CW
50 CONTINUE
!
100 CONTINUE
!----------
!  ESTIMATE CROWN WIDTH ON CYCLE 0 DEAD TREES
!  PROB IS NOT USED IN ESTIMATION OF CROWN WIDTH SO DON'T
!  WORRY ABOUT INFLATION OF DEAD-TREE PROB HERE.
!----------
IF(IREC2.GT.MAXTRE) GO TO 200
DO 150 I=IREC2,MAXTRE
ISPC=ISP(I)
P=PROB(I)
D=DBH(I)
H=HT(I)
CR=FLOAT(ICR(I))
CRWDTH(I)=0.0
IF(LSPCWE(ISPC))THEN
  IF(D .LT. CWTDBH(ISPC))THEN
    CW=CWDS0(ISPC)+CWDS1(ISPC)*DBH(I)+ &
          CWDS2(ISPC)*(DBH(I)**CWDS3(ISPC))
  ELSE
    CW=CWDL0(ISPC)+CWDL1(ISPC)*DBH(I)+ &
          CWDL2(ISPC)*(DBH(I)**CWDL3(ISPC))
  ENDIF
ELSE
  IWHO=0
  CALL CWCALC(ISPC,P,D,H,CR,IICR,CW,IWHO,JOSTND)
ENDIF
CRWDTH(I)=CW
IF(DEBUG)WRITE(JOSTND,*)' DEAD: I,ISPC,D,H,CW= ', &
   I,ISPC,D,H,CW
150 CONTINUE
200 CONTINUE
!----------
! PROCESS THE FIXCW OPTIONS.
!----------
CALL OPFIND (1,MYACTS(1),NTODO)
IF(DEBUG)WRITE(JOSTND,*)' PROCESSING FIXCW, NTODO= ',NTODO
IF (NTODO.GT.0) THEN
   DO 300 ITODO=1,NTODO
   CALL OPGET (ITODO,4,IDATE,IACTK,NP,PRM)
   IF(DEBUG)WRITE(JOSTND,*)' ITODO,IDATE,IACTK,NP,PRM= ', &
      ITODO,IDATE,IACTK,NP,PRM
   IF (IACTK.LT.0) GOTO 300
   IF(ICYC.GT.0)CALL OPDONE(ITODO,IY(ICYC))
   ISPCC=IFIX(PRM(1))
   IF(PRM(2) .LT. 0.) PRM(2)=0.
   IF(PRM(3) .LT. 0.) PRM(3)=0.
   IF(PRM(4) .LE. 0.) PRM(4)=999.
   IF(DEBUG)WRITE(JOSTND,*)' FIXCW: ISPCC,MULT,DBHLO,DBHHI= ', &
      ISPCC,PRM(2),PRM(3),PRM(4)
   IF (ITRN.GT.0) THEN
      DO 290 I=1,ITRN
      LINCL = .FALSE.
      IF(ISPCC.EQ.0 .OR. ISPCC.EQ.ISP(I))THEN
        LINCL = .TRUE.
      ELSEIF(ISPCC.LT.0)THEN
        IGRP = -ISPCC
        IULIM = ISPGRP(IGRP,1)+1
        DO 210 IG=2,IULIM
        IF(ISP(I) .EQ. ISPGRP(IGRP,IG))THEN
          LINCL = .TRUE.
          GO TO 215
        ENDIF
210         CONTINUE
      ENDIF
215       CONTINUE
      IF(LINCL .AND. &
           (PRM(3).LE.DBH(I) .AND. DBH(I).LT.PRM(4))) THEN
        CRWDTH(I)=CRWDTH(I)*PRM(2)
        IF(CRWDTH(I).GT. 99.9)CRWDTH(I)=99.9
        IF(DEBUG)WRITE(JOSTND,*)' LIVE: I,ISPCC,ISP,DBH,CRWDTH= ', &
           I,ISPCC,ISP(I),DBH(I),CRWDTH(I)
      ENDIF
290       CONTINUE
   ENDIF
   IF(IREC2.GT.MAXTRE)GO TO 295
   DO 293 I=IREC2,MAXTRE
      LINCL = .FALSE.
      IF(ISPCC.EQ.0 .OR. ISPCC.EQ.ISP(I))THEN
        LINCL = .TRUE.
      ELSEIF(ISPCC.LT.0)THEN
        IGRP = -ISPCC
        IULIM = ISPGRP(IGRP,1)+1
        DO 220 IG=2,IULIM
        IF(ISP(I) .EQ. ISPGRP(IGRP,IG))THEN
          LINCL = .TRUE.
          GO TO 225
        ENDIF
220         CONTINUE
      ENDIF
225       CONTINUE
   IF (LINCL .AND. &
            (PRM(3).LE.DBH(I) .AND. DBH(I).LT.PRM(4))) THEN
         CRWDTH(I)=CRWDTH(I)*PRM(2)
        IF(CRWDTH(I).GT. 99.9)CRWDTH(I)=99.9
        IF(DEBUG)WRITE(JOSTND,*)' DEAD: I,ISPCC,ISP,DBH,CRWDTH= ', &
           I,ISPCC,ISP(I),DBH(I),CRWDTH(I)
      ENDIF
293    CONTINUE
295    CONTINUE
300    CONTINUE
ENDIF
!
IF(DEBUG)WRITE(JOSTND,*)' LEAVING CWIDTH ICYC= ',ICYC
RETURN
END
