SUBROUTINE DAMCDS (II,ICODES)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     II    = TREE POINTER FOR LIVE TREES
!     ICODES= DISEASE AND DAMAGE CODES ARRAY
!
!----------
!
!OMMONS
!
INCLUDE 'PRGPRM.f90'
INCLUDE 'ARRAYS.f90'
INTEGER   I,II
INTEGER ICODES(6)

!----------
!  CALL SUBROUTINE TO PROCESS DAMAGE CODES FOR BASE MODEL (SPECIAL
!  TREE STATUS CODES, PERCENT DEFECT).
!----------
CALL BASDAM (II,ICODES)

!----------
!  STORE DAMAGE CODES FOR LATER PEST EXTENSION PROCESSING.
!----------
DO I = 1,6
  DAMSEV(I,II) = ICODES(I)
END DO

RETURN
END
