SUBROUTINE DAMPRO
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!  THIS SUBROUTINE CONTROLS THE PROCESSING DAMAGE AND SEVERITY CODES
!  STORED WHILE READING THE INPUT TREE RECORDS. DAMAGE CODE PROCESSING
!  ROUTINES OF EXTENSIONS THAT UTILIZE DAMAGE AND SEVERITY CODES ARE
!  CALLED HERE (PREVIOUSLY THEY WERE CALLED FROM SUBROUTINE INTRE).
!  CREATED: 07/06/2007 LANCE R. DAVID
!
!----------
!
!OMMONS
!
INCLUDE 'PRGPRM.f90'
INCLUDE 'ARRAYS.f90'
INCLUDE 'CONTRL.f90'

INTEGER I1,I2,II,I
INTEGER ICODES(6)

CONTINUE

!      WRITE(JOSTND,*) ' IN DAMPRO: IRECRD=',IRECRD,' ITRN=',ITRN,
!     > ' IREC1=',IREC1,' IREC2=',IREC2

!     Set looping indices to process live tree records.
!     Indices for dead trees will be set and processed next.

I1 = 1
I2 = IREC1

100 CONTINUE
!      WRITE(JOSTND,*) ' IN DAMPRO: I1=',I1,' I2=',I2

DO II = I1, I2
  DO I = 1,6
    ICODES(I) = DAMSEV(I,II)
  END DO
!       DAMAGE CODE 54 IS USED TO SET ACADIAN FORM AND RISK CODE
  DO I = 1,5,2
    IF (ICODES(I).EQ.54) ISPECL(II)=ICODES(I+1)
  ENDDO

!        WRITE(JOSTND,*) 'IN DAMPRO: ICODES(I) =    ',(ICODES(I),I=1,6),
!     &  ' IDTREE, ISP, DBH =',IDTREE(II),ISP(II),DBH(II),
!     &  ' IMC = ',IMC(II)

  CALL MISDAM (II,ICODES)
  CALL RDDAM  (II,ICODES)
  CALL TMDAM  (II,ICODES)
  CALL MPBDAM (II,ICODES)
  CALL DFBDAM (II,ICODES)
  CALL BRDAM  (II,ICODES)
  CALL BMDAM  (II,ICODES)
END DO

!     If dead trees are present, set indices and process.

IF (I1 .EQ. 1 .AND. IREC2 .NE. (MAXTRE + 1)) THEN
  I1 = IREC2
  I2 = MAXTRE
  GO TO 100
ENDIF

!     write(JOSTND,*) 'EXIT ROUTINE DAMPRO'

RETURN
END
