SUBROUTINE DGSCOR (SSIG,FRM,RHO,RHOCP,IT)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!  THIS SUBROUTINE CALCULATES THE ERROR IN DIAMETER GROWTH PREDICTION
!  THAT WILL BE CARRIED OVER INTO THE NEXT CYCLE.
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
!OMMONS
EXTERNAL RANN
!
INTEGER IT
REAL RHOCP,RHO,FRM,SSIG,BACHLO,DDS
!
!----------
!   IF NOT TRIPLING, ASSIGN DIAMETER GROWTH FROM A NORMAL
!   DISTRIBUTION ABOUT PREDICTED LN(DDS). DISTRIBUTION IS BOUNDED
!   TO + OR - DGSD STANDARD DEVIATIONS.
!----------
FRM=0.0
IF (DGSD .LT. 1.0) GO TO 25
20 CONTINUE
FRM=BACHLO(0.0,SSIG,RANN)
FRM=FRM*RHOCP+RHO*OLDRN(IT)
IF(ABS(FRM).GT.DGSD*SSIG) GO TO 20
25 CONTINUE
DDS=WK2(IT)
IF(DDS.GT.5.0) THEN
  FRM=0.0
ELSE
  IF(DDS.GT.4.) FRM=(DDS-4.)*FRM
ENDIF
OLDRN(IT)=FRM
FRM=EXP(FRM)
RETURN
END
