SUBROUTINE ECOPLS (KEYWRD,IDISP,PARMS,J1,J2)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!  THIS SUBROUTINE IS CALLED ONCE PER PROJECTION.
!  IT OUTPUTS THE KEYWORD, DATE AND NECESSARY PARAMETERS FOR THE
!  VARIOUS PROGNOSIS MODEL OPTIONS AND/OR EXTENSIONS WHICH ARE
!  RECOGNIZED BY THE ECONOMIC ANALYSIS PROGRAM CHEAPO
!----------
!
!     KEYWRD = CHARACTER*8 KEYWORD.
!     IDISP  = ACTIVITY DISPOSITION CODE WHERE:
!              -1 = DELETED
!               0 = NOT DONE
!              >0 = THE DATE ACTIVITY WAS DONE.
!     PARMS  = THE PARAMETER ARRAY.
!     J1     = IF ZERO THEN THERE ARE NO PARAMETERS FOR THE ACTIVITY.
!              OTHERWISE THE LOCATION OF THE FIRST PARAMETER
!     J2     = THE LOCATION OF THE LAST PARAMETER FOR THE ACTIVITY.
!
!OMMONS
!
!
INCLUDE 'ECON.f90'
!
!
!OMMONS
!
INTEGER J1,J2,IDISP,ITBSZ,I,JTWO,J
PARAMETER (ITBSZ=7)
REAL  PARMS(*)
CHARACTER*8  TABLE(ITBSZ),KEYWRD
!
DATA  TABLE/'MECHPREP','BURNPREP','PLANT   ','NPV2    ', &
               'NPV3    ','CHEMICAL','PRUNE   '/
!
IF (.NOT.LECON) RETURN
!
!----------
!   IF THE KEYWORD IS IN THE TABLE OUTPUT THE NECESSARY INFORMATION
!----------
DO 200 I=1,ITBSZ
IF( TABLE(I) .NE. KEYWRD ) GO TO 200
IF( IDISP .LE. 0 ) RETURN
!----------
!   THERE IS ONLY ROOM TO OUTPUT UP TO SIX(6) PARAMETERS.
!----------
IF (J1.GT.0 .AND. J2.GE.J1) THEN
   JTWO=J2
   IF( J2-J1 .GT. 5 ) JTWO=J1+5
   WRITE(JOSUME,100) KEYWRD,IDISP,(PARMS(J),J=J1,JTWO)
ELSE
   WRITE(JOSUME,100) KEYWRD,IDISP
ENDIF
100 FORMAT (A8,I6,6F10.2)
RETURN
200 CONTINUE
RETURN
END
