SUBROUTINE EVAGE (IDTE)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     CALLED FROM EVMON, AGES THE EVENTS WHICH HAVE ALREADY OCCURED
!     AND RESETS THEM AS VIABLE FOR REOCCURANCE.
!
!     EVENT MONITOR ROUTINE - NL CROOKSTON - AUG 1982 - MOSCOW, ID
!
!     IDTE  = POSTING DATE
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'OPCOM.f90'
!
!
!OMMONS
!
INTEGER IDTE,ISTRT,NEVA,NE,IEN,I1,I
!
!     IF THERE ARE NO EVENTS, THEN: RETURN.
!
IF (IEVT.LE.1) RETURN
ISTRT=1
NEVA=IEVA-1
!
!     DO FOR ALL EVENTS
!
NE=IEVT-1
DO 20 IEN=1,NE
!
!     IF THE EVENT HASN'T HAPPENED (CODE=-1); THEN: SKIP
!
IF (IEVNTS(IEN,2).EQ.-1) GOTO 20
!
!     IF THE EVENT HAS AGED, SET THE CODE TO -1 AND RESET THE
!     CORRESPONDING ACTIVITIY GROUP SCHEDULING STATUS CODE(S).
!
IF (IEVNTS(IEN,2)+IEVNTS(IEN,3).GT.IDTE) GOTO 20
IEVNTS(IEN,2)=-1
I1=ISTRT
DO 10 I=I1,NEVA
ISTRT=I
IF (IEVACT(I,1).LT.IEN) GOTO 10
IF (IEVACT(I,1).GT.IEN) GOTO 20
!
!     DO NOT RESET THE SCHEDULING STATUS CODE IF IT IS CURRENTLY SET
!     AT -1, WHICH INDECATES AN ATTEMPT TO SCHEDULE FAILED.
!
IF (IEVACT(I,2).GT.-1) IEVACT(I,2)=0
10 CONTINUE
20 CONTINUE
RETURN
END
