SUBROUTINE EVALNK (JOSTND,IEN,IALNK)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     CALLED FROM EVMON:  FOR A GIVEN EVENT, IEN, FINDS A
!     POINTER, IALNK, TO THE FIRST ACTIVITY GROUP (ROW IN IEVACT)
!     THAT CORRESPONDS TO THE EVENT.
!
!     EVENT MONITOR ROUTINE - NL CROOKSTON - JAN 1987 - MOSCOW, ID
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'OPCOM.f90'
!
!
!OMMONS
!
INTEGER IALNK,IEN,JOSTND,N,I
!
!     FIND THE EVENT IN THE EVENT/ACTIVITY LINKAGE ARRAY.
!
N=IEVA-1
DO 10 I=IEN,N
IALNK=I
IF (IEVACT(IALNK,1).EQ.IEN) GOTO 20
10 CONTINUE
!
!     IF THE LOOP EXITS, THE PROGRAM CAN'T LINK THE EVENT TO AN
!     ACTIVITY GROUP.
!
WRITE (JOSTND,11) IEVA,IEN,(IEVACT(I,1),I=1,N)
11 FORMAT (/' IEVA,IEN,IEVACT(1 TO IEVA-1,1)='/10(1X,15I6))
CALL ERRGRO (.TRUE.,18)
IALNK=0
20 CONTINUE
RETURN
END
