SUBROUTINE EVMON (IPH,IPPCL)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     CALLED FROM TREGRO.
!     TASKS:
!     1) AGES EVENTS.
!     2) MAINTAINS TEST VARIABLE TABLES.
!     3) DETERMINES WHICH EVENTS OCCUR.
!     4) POSTS THE DATE EVENTS OCCUR.
!     5) SCHEDULES THE ACTIVITIES WHICH ARE TO FOLLOW AN EVENT.
!
!     EVENT MONITOR ROUTINE - NL CROOKSTON - AUG 1982 - MOSCOW, ID
!     MAJOR REWRITE IN JAN 1987 - NL CROOKSTON - MOSCOW.
!
!     IPH   = THE PROJECTION PHASE NUMBER...USED TO SET IPHASE.
!     IPPCL = FLAG CONTROLLING ACTIVITY GROUP PROCESSING.
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'OPCOM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
!OMMONS
!
!     MAE   = LENGTH OF MAELNK.
!     MAELNK= LIST OF ACTIVITY GROUPS THAT ARE ASSOCIATED WITH
!             AN EVENT THAT HAS MORE THAN ONE ACTIVITY GROUP
!             ASSOCIATED WITH IT.
!             (1,.)= POINTS TO THE ENTRY IN IEVACT, AGLSET, & LENAGL
!             (2,.)= POINTS TO THE ENTRY IN IEVNTS
!
!     IEVLST= A LIST OF EVENTS THAT OCCURRED THIS CYCLE.
!             (1,.)= THE EVENT NUMBER (A ROW IN IEVNTS)
!             (2,.)= FIRST ACTIVITY GROUP (A ROW IN IEVACT)
!             (3,.)= NUMBER OF ACTIVITY GROUPS (ROWS IN IEVACT)
!
INTEGER IPPCL,IPH,MXPASS,MAELNK(2,MAXEVT),IEVLST(3,MAXEVT)
INTEGER IALNK,NGRPS,I,J1,J2,J,IDEL,INOCC,JEVNT,II,NSCHDS
INTEGER KODE,LENWRK,ISCHDS,NOCCRD,IEN,IRC,ACTF,CCCT,MAE,IPASS
PARAMETER (MXPASS=50)
LOGICAL LDEB,LDEB2
!
!     SEE IF WE NEED WRITE DEBUG.
!
CALL DBCHK (LDEB,'EVMON',5,ICYC)
!
IPHASE=IPH
!
!     WRITE DEBUG OUTPUT, IF DESIRED.
!
IF (LDEB) WRITE (JOSTND,5) IEVT,IPHASE,ICYC
5 FORMAT (/' IN EVMON, IEVT=',I5,'; IPHASE=',I3,'; ICYC=',I3)
CALL DBCHK (LDEB2,'ALGEVL',6,ICYC)
!
!     LOAD TEST VARIABLE TABLES
!
IF (LEVUSE) CALL EVTSTV (0)
MAE=0
!
!     IF NO EVENT MONITORING IS REQUESTED; THEN: RETURN.
!
IF (IEVT.LE.1) GOTO 300
!
!     IF THIS IS A PHASE 2 CALL OR IF FIRST CYCLE; THEN: SKIP EVENT
!     AGEING.
!
IF (.NOT.(IPHASE.GT.1 .OR. ICYC.EQ.1)) CALL EVAGE (IY(ICYC))
!
!     LOOP THRU ALL OF THE EVENTS AND FIND OUT WHICH ONES OCCURRED.
!     LET NOCCRD BE THE NUMBER OF EVENTS THAT OCCURRED.
!
IPASS=0
6 CONTINUE
NOCCRD=0
DO 20 IEN=1,(IEVT-1)
!
!     IF THE EVENT STATUS CODE INDICATES THAT THE EVENT HAS ALREADY
!     OCCURRED, THEN SKIP THIS EVENT.
!

IF (IEVNTS(IEN,2).GT.-1) GOTO 20
!
!     EVALUATE THE EXPRESSION.
!
CALL ALGEVL (LREG,MXLREG,XREG,MXXREG,IEVCOD(IEVNTS(IEN,1)), &
        MAXCOD-IEVNTS(IEN,1)+1,IY(1),IY(ICYC),LDEB2,JOSTND,IRC)
!
IF (IRC.GT.1) CALL ERRGRO (.TRUE.,21)
IF (LDEB) WRITE (JOSTND,10) IEN,IEVNTS(IEN,1),LREG(1),IRC
10 FORMAT (' IN EVMON: IEN=',I3,' IEVNTS(IEN,1)=',I5, &
           ' LREG(1),IRC=',L2,I4)
!
!     IF THE EVENT HAPPENED, LREG(1) BE TRUE AND THE RETURN CODE
!     WILL BE ZERO.
!
IF (LREG(1) .AND. IRC.EQ.0) THEN
!
!        CALL EVPOST TO POST THE EVENT AND COUNT THE NUMBER OF
!        ACTIVITY GROUPS THAT FOLLOW THE EVENT.
!
   CALL EVPOST (JOSTND,IEN,IY(ICYC),NGRPS,IALNK)
!
!        BUILD AN ENTRY IN IEVLST
!
   NOCCRD=NOCCRD+1
   IEVLST(1,NOCCRD)=IEN
   IEVLST(2,NOCCRD)=IALNK
   IEVLST(3,NOCCRD)=NGRPS
!
!        WRITE DEBUG, IF REQUESTED.
!
   IF (LDEB) WRITE (JOSTND,15) NOCCRD,IEN,IALNK,NGRPS
15    FORMAT (' IN EVMON: NOCCRD,IEN,IALNK,NGRPS=',4I5)
ENDIF
20 CONTINUE
IF (LDEB) WRITE (JOSTND,'(/'' IN EVMON: NOCCRD='',I5)') NOCCRD
!
!     IF NO EVENTS OCCURRED, THEN BRANCH TO EXIT.
!
IF (NOCCRD.EQ.0) GOTO 300
!
!     COUNT UP THE NUMBER OF ACTIVITY GROUPS THAT FOLLOW EVENTS THAT
!     HAVE MORE THAN ONE ACTIVITY GROUP ASSOCIATED WITH THEM.
!
DO 40 I=1,NOCCRD
IF (IEVLST(3,I).GT.1) THEN
   J1=IEVLST(2,I)
   J2=IEVLST(3,I)+J1-1
   DO 30 J=J1,J2
   MAE=MAE+1
   MAELNK(1,MAE)=J
   MAELNK(2,MAE)=IEVLST(1,I)
30    CONTINUE
ENDIF
40 CONTINUE
!
!     WRITE SOME DEBUG.
!
IF (LDEB) WRITE (JOSTND,'(/'' IN EVMON: NOCCRD,MAE= '',2I5)') &
                   NOCCRD,MAE
!
!     IF THERE ARE NONE, THEN BRANCH PAST LOGIC THAT ATTEMPTS TO
!     DELETE THEM.
!
IF (MAE.LE.0) GOTO 100
!
!     WRITE SOME MORE DEBUG.
!
IF (LDEB) WRITE (JOSTND,50) (I,MAELNK(1,I),MAELNK(2,I),I=1,MAE)
50 FORMAT (' IN EVMON(50): MAELNK(1&2,',I3,')= ',2I5)
!
!     IF LABEL PROCESSING IS BEING USED, TRIM THE LIST USING THE
!     LABEL LOGIC.
!
IF (LBSETS) THEN
   IF (LDEB) WRITE (JOSTND,60)  LENSLS,SLSET(1:LENSLS), &
         (I,MAELNK(1,I),MAELNK(2,I),AGLSET(MAELNK(1,I)) &
         (1:LENAGL(MAELNK(1,I))),I=1,MAE)
60    FORMAT (' IN EVMON, BEFORE LBTRIM, LENSLS=',I4,' SLSET= '/T12, &
             A/((T12,'MAELNK(1:2,',I2,')= ',2I5,' AGLSET='/,T12,A)))
   CALL LBTRIM (MAE,MAELNK)
!
!        IF ALL OF THE ACTIVITY GROUPS HAVE BEEN DELETED, THEN
!        BRANCH PAST THE OPSAME CHECK.
!
   IF (MAE.LE.0) GOTO 100
   IF (LDEB) WRITE (JOSTND,70) (I,MAELNK(1,I), &
                                     MAELNK(2,I),I=1,MAE)
70    FORMAT (' IN EVMON(70): MAELNK(1:2,',I2,')= ',2I5)
ENDIF
!
!     TRIM THE LIST FURTHER BY DELETING DUPLICATE GROUPS OF ACTIVITIES
!
CALL OPSAME (MAE,MAELNK,JOSTND,LDEB)
!
100 CONTINUE
!
!     IF IPPCL IS EQUAL TO 2,
!     THEN GO THROUGH THE LIST OF EVENTS THAT HAVE MORE THAN
!     ONE ACTIVITY GROUP.  IF THE EVENT IS NO LONGER LISTED
!     IN MAELNK, THEN DELETE THE ENTRY IN IEVLST. IF THE EVENT
!     IS IN MAELNK, SET THE ENTRY IN IEVLST TO THE FIRST
!     ACTIVITY GROUP AND SET THE NUMBER OF GROUPS TO ONE.
!
IF (IPPCL.EQ.2) THEN
   IDEL=0
   DO 140 INOCC=1,NOCCRD
   IF (IEVLST(3,INOCC).EQ.1) GOTO 140
   JEVNT=IEVLST(1,INOCC)
   J1=0
   IF (MAE.EQ.0) GOTO 130
   DO 120 II=1,MAE
   IF (MAELNK(2,INOCC).EQ.JEVNT) THEN
      J1=II
      GOTO 130
   ENDIF
120    CONTINUE
130    CONTINUE
   IF (J1.EQ.0) THEN
      IDEL=IDEL+1
      IEVLST(1,INOCC)=0
   ELSE
!
!           SET THE ACTIVITY CODE NEGITIVE THEREBY SIGNALING THAT
!           LABEL PROCESSING, ETC, FOR THIS OPTION IS DONE.
!
      IEVLST(2,INOCC)=-MAELNK(1,J1)
      IEVLST(3,INOCC)=1
   ENDIF
140    CONTINUE
!
!        DELETE ENTRIES IN IEVLST, IF NECESSARY
!
   IF (IDEL.GT.0) THEN
      IF (IDEL.EQ.NOCCRD) THEN
         NOCCRD=0
      ELSE
         IDEL=NOCCRD+1
         DO 160 INOCC=1,NOCCRD
         IF (IEVLST(1,INOCC).EQ.0) THEN
            IDEL=IDEL-1
            DO 150 J1=1,3
            IEVLST(J1,INOCC)=IEVLST(J1,IDEL)
150             CONTINUE
         ENDIF
160          CONTINUE
         NOCCRD=IDEL
      ENDIF
   ENDIF
ENDIF
!
!     INITIALIZE THE NUMBER OF ACTIVITY GROUPS THAT HAVE BEEN
!     SCHEDULED AND LOOP THRU ALL OF THE EVENTS THAT OCCURRED.
!
NSCHDS=0
IF (NOCCRD.EQ.0) GOTO 210
DO 200 INOCC=1,NOCCRD
IF (LDEB) WRITE (JOSTND,170) INOCC,(IEVLST(I,INOCC),I=1,3)
170 FORMAT (' IN EVMON: IEVLST(1:3,',I3,')= ',3I4)
!
!     IF THE ACTIVITY GROUP NUMBER IN IEVLST IS NEG, SET IT POSITIVE
!     AND BRANCH TO SCHEDULE ACTIVITIES
!
IF (IEVLST(2,INOCC).LT.0) THEN
   IEVLST(2,INOCC)=-IEVLST(2,INOCC)
   IALNK=IEVLST(2,INOCC)
   GOTO 190
ENDIF
IALNK=IEVLST(2,INOCC)
!
!     IF LABEL PROCESSING IS TURNED ON, THEN PROCESS LABELS TO
!     DETERMINE IF THE ACTIVITIES WILL BE SCHEDULED.
!
IF (LBSETS) THEN
   IF (LDEB) WRITE (JOSTND,'(/'' IN EVMON: LENSLS='',I5, &
                       '' SLSET= '',A)') LENSLS,SLSET(:LENSLS)
!
!        IF THE ACTIVITY GROUP LABEL WAS SET (LENAGL>-1), THEN
!        COMPUTE THE INTERSECTION OF THE ACTIVITY GROUP LABEL AND THE
!        STAND LABEL.
!
   IF (LENAGL(IALNK).GT.-1) THEN
      IF (LDEB) WRITE (JOSTND,180) IALNK, &
                         AGLSET(IALNK)(1:LENAGL(IALNK))
180       FORMAT (' IN EVMON: IALNK=',I3,' AGLSET=',A)
      CALL LBINTR (LENAGL(IALNK),AGLSET(IALNK),LENSLS,SLSET, &
                      LENWRK,WKSTR1,KODE)
!
!           IF THE RESULT IS THE NULL SET, DO NOT SCHEDULE THE
!           ACTIVITY GROUP.
!
      IF (LENWRK.EQ.0) GOTO 200
    ENDIF
ENDIF
190 CONTINUE
!
!     SCHEDULE THE ACTIVITY GROUP.
!
CALL OPSCHD (IY(ICYC),IEVACT(IALNK,4),IEVACT(IALNK,5), &
                ISCHDS,KODE)
IF (LDEB) WRITE (JOSTND,195) ICYC,IY(ICYC),IALNK,IEVACT(IALNK,4), &
             IEVACT(IALNK,5),ISCHDS,KODE
195 FORMAT (/' IN EVMON: ICYC=',I3,' IY(ICYC)=',I5,' IALNK=',I5, &
            ' IEVACT(IALNK,4:5)=',2I5,' ISCHDS=',I4,' KODE=',I3)

IF (KODE.GE.2) THEN
!
!        FLAG THE ACTIVITY GROUP THAT AN ATTEMPT TO SCHEDULE HAS
!        FAILED, AND DELETE THE EVENT.
!
   IEVACT(IALNK,2)=-1
   IEVNTS(IEVLST(1,INOCC),3)=-1
   CALL ERRGRO (.TRUE.,18)
   GOTO 210
ENDIF
!
!     SET THE SCHEDULING CODE FOR THIS ACTIVITY GROUP
!
IEVACT(IALNK,2)=2
!
!     COUNT THE NUMBER OF ALTERNATIVES ACTUALLY SCHEDULED.
!
NSCHDS=NSCHDS+ISCHDS
200 CONTINUE
210 CONTINUE
IF (LDEB) WRITE (JOSTND,'(/'' IN EVMON: NSCHDS='',I5)') NSCHDS
!
!     IF ONE OR MORE ACTIVITIES WERE SCHEDULED, INCORPORATE THEM INTO
!     THE ACTIVITY ARRAYS AND RECALL EVTSTV TO RECOMPUTE USER DEFINED
!     VARIABLES.
!
IF (NSCHDS.GT.0) THEN
   CALL OPINCR (IY,ICYC,NCYC)
   CALL EVTSTV (1)
   IPASS = IPASS+1
   IF (LDEB) WRITE (JOSTND,'('' IN EVMON: IPASS='',I5)') IPASS
   IF (IPASS.LE.MXPASS) GOTO 6
ENDIF
!
300 CONTINUE
!
!     IF CCADJ IS CONDITIONALLY SCHEDULED, CALL SSTAGE FROM HERE
!
!     Commented out as this causes replicate records written to
!     associated DB output table, FVS_StrClass table. LD - 2/21/2023
!      CCCT=0
!      DO ACTF=1,MAXACT
!        IF((IACT(ACTF,1).EQ.444))THEN
!          CCCT=CCCT+1
!        ENDIF
!      END DO
!      IF(CCCT.GE.1)CALL SSTAGE(1,ICYC,.TRUE.)

RETURN
END
