SUBROUTINE EVTACT
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     ESTABLISHES THE LINKAGE BETWEEN AN EVENT, REFERENCED BY THE MOST
!     RECENTLY ASSIGNED INTERNAL EVENT NUMBER (IENV), AND A GROUP OF
!     ACTIVITIES.
!
!     EVENT MONITOR ROUTINE - NL CROOKSTON - AUG 1982 - MOSCOW, ID
!     MODIFIED TO ADD LABEL PROCESSING IN JAN 1987
!
!     ENTRY   DESCRIPTION
!     -----   ----------------------------------------------------------
!     EVTHEN  CALLED WHEN THE THEN KEYWORD IS SPECIFIED, THE OPTION
!             ACTIVITY KEYWORDS WHICH FOLLOW ARE LINKED TO AN EVENT
!             NUMBER AND STORED FOR FUTURE SCHEDULING.
!     EVALSO  CALLED WHEN ALSOTRY KEYWORD IS SPECIFIED.
!             CLOSES OFF
!             A PREVIOUS ENTRY IN IEVACT, ESTABLISHES NEW ENTRY IN
!             IEVACT, AND ACCOMPLISHES SOME ERROR CHECKING.
!     EVEND   CALLED WHEN ENDIF IS SPECIFIED, CLOSES OFF PREVIOUS
!             ENTRY IN IEVACT, RETURN ACTIVITY STORAGE MODE TO NORMAL.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'OPCOM.f90'
!
!
!OMMONS
!
LOGICAL LNOTBK(12),DEBUG,LKECHO
CHARACTER KEYWRD*8,KARD(12)*10,RECORD*80
REAL ARRAY(12)
INTEGER IPRMPT,IRECNT,IREAD,JOSTND,ICEX,J,K,I,IAMP,IRC,IRTNCD
EQUIVALENCE (RECORD,WKSTR3)
!
ENTRY EVALSO (DEBUG,JOSTND,IREAD,IRECNT,KEYWRD,ARRAY,LNOTBK, &
                 KARD,IPRMPT)
!
!     IF LOPEVN IS FALSE, THE ALSOTRY KEYWORD HAS BEEN SPECIFIED
!     WITHOUT SPECIFYING AN EVENT AND A THEN KEYWORD, AND IS THEREFORE
!     ILLEGAL.
!
IF (.NOT.LOPEVN) THEN
   CALL KEYDMP (JOSTND,IRECNT,KEYWRD,ARRAY,KARD)
   CALL ERRGRO (.TRUE.,16)
   RETURN
ENDIF
!
!     CLOSE OFF THE LAST ENTRY IN IEVACT, THE EVENT/ACTIVITY LINKAGE
!     ARRAY.  IF NO ACTIVITIES HAVE BEEN SPECIFIED, THE ACTIVITY GROUP
!     IS TERMED A NULL ALTERNATIVE; THEN: SET THE POINTERS TO ZERO.
!
IF (IEVACT(IEVA,4).LE.IEPT) THEN
   IEVACT(IEVA,4)=0
   IEVACT(IEVA,5)=0
ELSE
!
!        ELSE: SET THE SECOND POINTER EQUAL TO THE LAST ACTIVITY ENTRY
!        (NOTE THAT IEPT IS DECREMENTED AS ACTIVITIES ARE ENTERED).
!
   IEVACT(IEVA,5)=IEPT+1
ENDIF
!
!     INCREMENT IEVA, SO THAT IT POINTS TO THE NEXT AVAILABLE ROW
!     IN IEVACT
!
IEVA=IEVA+1
GOTO 5
!
!
ENTRY EVTHEN (DEBUG,JOSTND,IREAD,IRECNT,KEYWRD,ARRAY,LNOTBK, &
                 KARD,IPRMPT,LKECHO)
!
!     IF LOPEVN IS TRUE AND THE LEG COUNT IS ZERO, THIS THEN IS LEGAL
!     AS IT FOLLOWS AN IF AND NOT ANOTHER THEN OR ALSOTRY.
!
IF (.NOT.LOPEVN .OR. ILGNUM.GT.0) THEN
   CALL KEYDMP (JOSTND,IRECNT,KEYWRD,ARRAY,KARD)
   CALL ERRGRO (.TRUE.,16)
   RETURN
ENDIF
5 CONTINUE
!
!     VERIFY THAT THERE IS ROOM IN IEVACT TO STORE THE ACTIVITIY GROUP.
!
IF (IEVA.GT.MAXEVA) THEN
   CALL KEYDMP (JOSTND,IRECNT,KEYWRD,ARRAY,KARD)
   CALL ERRGRO (.TRUE.,17)
   RETURN
ENDIF
!
!     INCREMENT THE BRANCH LEG COUNTER.
!
ILGNUM=ILGNUM+1
!
!     IF THERE ARE OVER 9 ACTIVITY GROUPS, ISSUE ERROR MSG
!
IF (ILGNUM.GT.9) CALL ERRGRO (.TRUE.,22)
!
!     ESTABLISH AN ENTRY IN IEVACT.
!
IEVACT(IEVA,1)=IEVT
IEVACT(IEVA,2)=0
IEVACT(IEVA,3)=ILGNUM
IEVACT(IEVA,4)=IEPT
!
!     WRITE INITIAL KEYWORD MESSAGE.
!
IF(LKECHO)WRITE(JOSTND,6) KEYWRD
6 FORMAT (/A8,'   ACTIVITIES WHICH FOLLOW WILL NOT BE ', &
           'SCHEDULED UNTIL THE EVENT HAPPENS (WHEN THE ', &
           'LOGICAL EXPRESSION IS TRUE).')
!
!     PROCESS THE BRANCH WEIGHT MULTIPLIER CODED ON THE KEYWORD.
!
!     IF IPRMPT IS ZERO, CHECK ARRAY(1)...IF NOT BLANK STORE IT AS
!     THE MULTIPLIER AND WRITE OUT A MESSAGE.
!
IF (IPRMPT.EQ.0) THEN
   IF (LNOTBK(1)) THEN
      IF (IMPL.LE.ITOPRM) THEN
         PARMS(IMPL)=ARRAY(1)
         IEVACT(IEVA,6)=IMPL
         IMPL=IMPL+1
         IF(LKECHO) &
            WRITE(JOSTND,'(T12,''BRANCH WEIGHT MULTIPLIER = '', &
                   F12.5)') ARRAY(1)
      ELSE
         IEVACT(IEVA,6)=0
         CALL ERRGRO (.TRUE.,10)
         WRITE (JOSTND,'(T12,''MULTIPLIER IGNORED.'')')
      ENDIF
   ENDIF
ELSE
!
!        MOVE THE EXPRESSION INTO CEXPRS.
!
   ICEX=0
   DO J=IPRMPT,7
     DO K=1,10
     ICEX=ICEX+1
     CEXPRS(ICEX)=KARD(J)(K:K)
     CALL UPCASE(CEXPRS(ICEX))
     ENDDO
   ENDDO
!
!        WRITE THE FIRST LINE.
!
   WRITE (JOSTND,20) (CEXPRS(I),I=1,ICEX)
20    FORMAT (T12,'MULTIPLIER= ',70A1)
!
!        LOOK FOR AN AMPERSAND
!
   IAMP=0
   DO 30 I=1,ICEX
   IF (CEXPRS(I).EQ.'&') THEN
      IAMP=I
      GOTO 35
   ENDIF
30    CONTINUE
35    CONTINUE
!
!        IF THERE IS AN AMPERSAND, READ ANOTHER RECORD, ADD IT TO CEXPRS
!
   IF (IAMP.GT.0) THEN
      ICEX=IAMP
      READ (IREAD,'(A)',END=200) RECORD
      DO 40 I=80,1,-1
      IF (RECORD(I:I).EQ.' ') GOTO 40
      J=I
      GOTO 45
40       CONTINUE
      J=1
45       CONTINUE
      IRECNT=IRECNT+1
      IAMP=0
      DO 50 I=1,J
      CALL UPCASE (RECORD(I:I))
      CEXPRS(ICEX)=RECORD(I:I)
      IF (CEXPRS(ICEX).EQ.'&') THEN
         IAMP=ICEX
         GOTO 55
      ENDIF
      ICEX=ICEX+1
      IF (ICEX.GT.MXEXPR) THEN
         WRITE (JOSTND,'(T12,A)') RECORD
         CALL ERRGRO (.TRUE.,4)
         IEVACT(IEVA,6)=-I
         RETURN
      ENDIF
50       CONTINUE
      ICEX=ICEX-1
55       CONTINUE
      WRITE (JOSTND,'(T12,A)') RECORD
      GOTO 35
   ENDIF
!
!        TRIM OFF TRAILING BLANKS.
!
   K=ICEX
   DO 60 I=K,1,-1
   IF (CEXPRS(I).EQ.' ') GOTO 60
   ICEX=I
   GOTO 65
60    CONTINUE
65    CONTINUE
!
!        STORE THE LOCATION OF THE OPCODE IN KODE.
!
   I=ICOD
!
!        COMPILE THE EXPRESSION.
!
   CALL ALGCMP(IRC,.FALSE.,CEXPRS,ICEX,JOSTND,DEBUG,1000, &
         IPTODO,MXPTDO,IEVCOD,ICOD,MAXCOD,PARMS,IMPL,ITOPRM,MAXPRM)
!
!        IF THE RETURN CODE FROM THE COMPILATION IS NON ZERO, ISSUE
!        AN ERROR MESSAGE AND SET THE BRANCH MULT CODE TO ZERO.
!
   IF (IRC.GT.0) THEN
      IEVACT(IEVA,6)=0
      CALL ERRGRO (.TRUE.,12)
   ELSE
!
!        STORE LOCATION OF THE OPERATION CODE (SET THE POINTER NEG).
!
      IEVACT(IEVA,6)=-I
   ENDIF
ENDIF
RETURN
200 CONTINUE
CALL ERRGRO(.FALSE.,2)
CALL fvsGetRtnCode(IRTNCD)
IF (IRTNCD.NE.0) RETURN

RETURN
!
!
ENTRY EVEND (DEBUG,JOSTND,IRECNT,KEYWRD,ARRAY,LNOTBK,KARD, &
                IPRMPT,LKECHO)
!
!     SET THE ACTIVITY STORAGE MODE TO NORMAL,
!     CLOSE THE EVENT ACTIVITY GROUP LINKAGE ARRAY, AND
!     INCREMENT THE INTERNAL EVENT NUMBER.
!     IF THE ACTIVITY STORAGE MODE IS NORMAL, THEN THE ENDIF WAS IN
!     THE INCORRECT SEQUENCE.
!
IF (.NOT.LOPEVN .OR. ILGNUM.LE.0) THEN
!
!        IF IPRMPT IS LE -1, CALL WAS MADE WHEN A PROCESS KEYWORD
!        WAS DETECTED. SUPPRESS WRITING AN ERROR MESSAGE.
!
   IF (IPRMPT.LE.-1) RETURN
   CALL KEYDMP (JOSTND,IRECNT,KEYWRD,ARRAY,KARD)
   CALL ERRGRO (.TRUE.,16)
ELSE
   LOPEVN=.FALSE.
   ILGNUM=0
   IEVT=IEVT+1
   IF (IEVACT(IEVA,4).LE.IEPT) THEN
      IEVACT(IEVA,4)=0
      IEVACT(IEVA,5)=0
   ELSE
      IEVACT(IEVA,5)=IEPT+1
   ENDIF
   IEVA=IEVA+1
   IF(LKECHO)WRITE(JOSTND,300) KEYWRD
300    FORMAT (/A8,'   ACTIVITIES WHICH FOLLOW WILL BE SCHEDULED.')
ENDIF
END
