SUBROUTINE EVUSRV (RECORD,KEYWRD,ARRAY,LNOTBK,IREAD,JOSTND, &
                      LDEBUG,IRECNT)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     CALLED FROM INITRE.  READS, COMPILES, AND STORES USER
!     DEFINED VARIABLES.  CALLS ALGCMP TO COMPILE THEM.
!
!     EVENT MONITOR ROUTINE - N.L. CROOKSTON  - APRIL 1987
!     FORESTRY SCIENCES LABORATORY - MOSCOW, ID 83843
!
!     RECORD= CHARACTER STRING.
!     ARRAY = ARRAY OF PARAMETERS
!     LNOTBK= TRUE IF CORRESPONDING PARM FIELD IS NOT BLANK.
!     IREAD = READER DATA SET REFERENCE NUMBER.
!     JOSTND= OUTPUT DATA SET REFERENCE NUMBER.
!     LDEBUG= DEBUG OUTPUT IS REQUESTED.
!     IRECNT= RECORD COUNTER.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'OPCOM.f90'
!
!
!OMMONS
!
INTEGER IRECNT,JOSTND,IREAD,IDT,IRC,LCLFT,LENCEX,IRCKEY,IKEY
INTEGER IRTNCD
REAL ARRAY(12)
LOGICAL LDEBUG,LNOTBK(12)
CHARACTER CLEFT*20,RECORD*(*),KEYWRD*8
!
!     SET UP THE DEFAULT DATE FOR SCHEDULING THE COMPUTATIONS AND
!     WRITE THE MESSAGE:
!
IDT=1
IF (LNOTBK(1)) IDT=IFIX(ARRAY(1))
WRITE (JOSTND,4031) KEYWRD,IDT
4031 FORMAT (/A8,'   DATE/CYCLE=',I5,'; DEFINE THE FOLLOWING:'/)
!
!     READ THE EXPRESSION AND PLACE IT INTO THE CEXPRS ARRAY.
!
10 CONTINUE
CALL ALGEXP (CEXPRS,LENCEX,MXEXPR,CLEFT,LCLFT,RECORD,IRECNT, &
                IREAD,JOSTND,IRC)
CALL fvsGetRtnCode(IRTNCD)
IF (IRTNCD.NE.0) RETURN
!
!     RETURN CODES, IRC: 0=OK,1='END  ' WAS FOUND. OTHER ERRORS ARE
!     HANDLED INTERNALLY.
!
IF (IRC.EQ.1) GOTO 30
!
!     FIND OUT IF THE LEFT HAND TOKEN (USER DEFINED VARIABLE) IS A
!     RESERVED KEYWORD (AN EVENT MONITOR VARIABLE OR A LEVEL
!     USER DEFINED VARIABLE).
!
CALL ALGKEY (CLEFT,LCLFT,IKEY,IRCKEY)
IF(IRCKEY.NE.0) THEN
   CALL EVMKV(CLEFT)
   CALL ALGKEY (CLEFT,LCLFT,IKEY,IRCKEY)
ENDIF
!
!     IF IRCKEY IS ZERO AND IF IKEY IS LESS THAN 500 OR OVER 599, IT IS
!     RESERVED...ISSUE AN ERROR MESSAGE AND BRANCH TO PROCESS ANOTHER.
!
IF (IRCKEY.EQ.0) THEN
   IF (IKEY.LT.500 .OR. IKEY.GT.500+MXTST5) THEN
      CALL ERRGRO (.TRUE.,15)
      GOTO 10
   ENDIF
ENDIF
!
!     IF IRCKEY IS NOT ZERO, THEN THE VARIABLE NAME CAN NOT BE
!     DEFINED. ISSUE ERROR MSG AND BRANCH TO PROCESS NEXT EXPRESSION.
!
IF (IRCKEY.EQ.1) THEN
   CALL ERRGRO (.TRUE.,10)
   CALL ERRGRO (.TRUE.,12)
   WRITE (JOSTND,*) 'ISSUED IN EVUSRV CANNOT DEFINE VARIABLE'
   GOTO 10
ENDIF
!
!     CALL ALGCMP TO COMPILE THE EXPRESSION.  SAVE THE STARTING
!     LOCATION OF THE OPCODE IN ARRAY(4)...(THIRD PARMS FOR THE OP).
!
ARRAY(4)=FLOAT(ICOD)
CALL ALGCMP (IRC,.FALSE.,CEXPRS,LENCEX,JOSTND,LDEBUG,1000, &
      IPTODO,MXPTDO,IEVCOD,ICOD,MAXCOD,PARMS,IMPL,ITOPRM,MAXPRM)
!
!     IF WE GET A NON-ZERO RETURN CODE, ISSUE A GENERAL PURPOSE
!     ERROR MESSAGE AND BRANCH TO PROCESS THE NEXT EXPRESSION.
!
IF (IRC.GT.0) THEN
   CALL ERRGRO (.TRUE.,12)
   GOTO 10
ENDIF
!
!     CALL OPNEW TO ADD THE OPTION TO THE ACTIVITY SCHEDULE...
!     (THE FIRST PARAMETER WILL BE 0.0).
!
ARRAY(2)=0.0
ARRAY(3)=FLOAT(IKEY)
CALL OPNEW (IRC,IDT,33,3,ARRAY(2))
!
!     IF THE RETURN CODE IS GT 0, A WARNING MSG WAS ISSUED VIA ERRGRO.
!
IF (IRC.GT.0) GOTO 10
!
!     PROCESS THE NEXT EXPRESSION.
!
GOTO 10
30 CONTINUE
RETURN
END
