SUBROUTINE EXBM
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     EXTERNAL REFERENCES FOR THE Westwide Pine Beetle model
!
!----------
!
INTEGER I3(6),JOPPRT,IRECNT,IREAD,I2,I1,KEY,IOUT,I
!
!
CHARACTER*8 NOBM,KEYWRD
LOGICAL     LACTV,LKECHO,LTEE
REAL R1(*),XBM1,XBM2
REAL RDANUW
INTEGER IDANUW
!
DATA NOBM/'**NO BM '/
!----------
! BMSDIT CALLED FROM PPMAIN.
!----------
ENTRY BMSDIT
RETURN
!----------
! BMKILL CALLED FROM PPMAIN
!----------
ENTRY BMKILL
RETURN
!----------
! BMSETP CALLED FROM ALSTD1
!----------
ENTRY BMSETP
RETURN
!----------
! BMDRV CALLED FROM ALSTD2
!----------
ENTRY BMDRV
RETURN
!----------
! BMPPIN CALLED FROM PPIN
!----------
ENTRY BMPPIN(IREAD,IRECNT,JOPPRT)
  WRITE(JOPPRT,10) IRECNT,NOBM
  CALL ERRGRO (.TRUE.,11)
10   FORMAT (/1X,A8,'RECORD: ', I6, A8)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IREAD
RETURN
!----------
! BMSLSH CALLED FROM CUTS
!----------
ENTRY BMSLSH (I1,XBM1,XBM2,I2)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I1
  IDANUW = I2
  RDANUW = XBM1
  RDANUW = XBM2
RETURN
!----------
! BMTRIP CALLED FROM TRIPLE
!----------
ENTRY BMTRIP (I1,I2,XBM1)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I1
  IDANUW = I2
  RDANUW = XBM1
RETURN
!----------
! BMKEY CALLED FROM OPLIST
!----------
ENTRY BMKEY (KEY,KEYWRD)
  KEYWRD=NOBM
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = KEY
RETURN
!----------
! BMPPPT CALLED FROM PUTSTD
!----------
ENTRY BMPPPT (I1,I2)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I1
  IDANUW = I2
RETURN
!----------
! BMPPGT CALLED FROM GETSTD
!----------
ENTRY BMPPGT (I1,I2)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I1
  IDANUW = I2
RETURN
!----------
! BMDAM  CALLED FROM DAMCDS
!----------
ENTRY BMDAM (I1,I3)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I1
  IDANUW = I3(1)
RETURN
!
!----------
! BMIN  CALLED FROM INITRE
!----------
ENTRY BMIN(LKECHO)
  IF(LKECHO)WRITE(JOPPRT,20) IRECNT,NOBM
20   FORMAT (/1X,A8,'RECORD: ', I6, A8)
  CALL ERRGRO (.TRUE.,11)
RETURN
!----------
! BMLNKD  CALLED FROM DBSIN
!----------
ENTRY BMLNKD(LACTV)
  LACTV = .FALSE.
RETURN
!-----------
! BMDBS--CALLED FROM DBSIN
!
ENTRY BMDBS(I,IOUT)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I
  IDANUW = IOUT
RETURN
!-----------
! RRATV CALLED FROM GETSTD AND PUTSTD
!-----------
ENTRY RRATV(LACTV,LTEE)
  LACTV=.FALSE.
  LTEE=.FALSE.
RETURN
!-----------
! RRPPPT CALLED FROM PUTSTD
!-----------
ENTRY RRPPPT(R1,I1,I2)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I1
  IDANUW = I2
  RDANUW = R1(1)
RETURN
!-----------
! RRPPGT CALLED FROM GETSTD
!-----------
ENTRY RRPPGT(R1,I1,I2)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I1
  IDANUW = I2
  RDANUW = R1(1)
RETURN
!-----------
END
