SUBROUTINE EXBRUS
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     ENTRY POINTS FOR PROGNOSIS EXTERNAL REFERENCES TO
!     THE WHITE PINE BLISTER RUST MODEL SUBROUTINES WHEN
!     WHITE PINE BLISTER RUST IS NOT INCLUDED.
!
!
!
LOGICAL LNOTBK(12),LKECHO
CHARACTER*8 KEYWRD,NOBR
REAL ARRAY(12),PROB(*),WEIGHT,TIME
INTEGER IND(*),IND1(*)
INTEGER I3(6),NCLAS,I1,I2,KEY,IREC,IVAC,I,ITFN
REAL RDANUW
INTEGER IDANUW
CHARACTER*8 CDANUW
LOGICAL LDANUW
!
DATA NOBR/'*NO BRUS'/
!
!----------
!  ENTRY BRCMPR   CALLED FROM COMPRS
!----------
ENTRY BRCMPR (NCLAS,PROB,IND,IND1)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = NCLAS
  RDANUW = PROB(1)
  IDANUW = IND(1)
  IDANUW = IND1(1)
RETURN
!
!----------
!  ENTRY BRDAM   CALLED FROM DAMCDS
!----------
ENTRY BRDAM (I1, I3)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I1
  IDANUW = I3(1)
RETURN
!
!----------
!  ENTRY BRESTB   CALLED FROM ESTAB
!----------
ENTRY BRESTB (TIME, I1, I2)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = TIME
  IDANUW = I1
  IDANUW = I2
RETURN
!
!----------
!  ENTRY BRTREG   CALLED FROM GRADD
!----------
ENTRY BRTREG
RETURN
!
!----------
!  ENTRY BRINIT   CALLED FROM INITRE
!----------
ENTRY BRINIT
RETURN
!
!----------
!  ENTRY BRIN
!----------
ENTRY BRIN (KEYWRD,ARRAY,LNOTBK,LKECHO)
  CALL ERRGRO (.TRUE.,11)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = ARRAY(1)
  CDANUW(1:8) = KEYWRD(1:8)
  LDANUW = LNOTBK(1)
  LDANUW = LKECHO
RETURN
!
!----------
!  ENTRY BRSETP   CALLED FROM MAIN
!----------
ENTRY BRSETP
RETURN
!
!----------
!  ENTRY BRPR
!----------
ENTRY BRPR
RETURN
!
!----------
!  ENTRY BRROUT
!----------
ENTRY BRROUT
RETURN
!
!----------
!  ENTRY BRKEY    CALLED FROM OPLIST
!----------
ENTRY BRKEY (KEY,KEYWRD)
  KEYWRD=NOBR
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = KEY
RETURN
!
!----------
!  ENTRY BRTDEL    CALLED FROM TREDEL
!----------
ENTRY BRTDEL (IVAC,IREC)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IVAC
  IDANUW = IREC
RETURN
!
!----------
!  ENTRY BRSOR    CALLED FROM TRESOR
!----------
ENTRY BRSOR
RETURN
!
!----------
!  ENTRY BRTRIP   CALLED FROM TRIPLE
!----------
ENTRY BRTRIP (ITFN,I,WEIGHT)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = ITFN
  IDANUW = I
  RDANUW = WEIGHT
RETURN
!
END
