SUBROUTINE EXCLIM
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     EXTRA EXTERNAL REFERENCES FOR CLIMATE EXTENSION CALLS
!
!OMMONS
!
INCLUDE 'PRGPRM.f90'
!
!OMMONS
!
LOGICAL DEBUG,LKECHO,L
INTEGER KEY,IPNT,ILIMIT,ISP,IRC
CHARACTER*8 KEYWRD,NOCLIM
REAL SDIDEF(MAXSP),XMAX,TREEMULT(MAXTRE),WK3(MAXTRE),VIA
REAL RDANUW
INTEGER IDANUW
LOGICAL LDANUW
!
DATA NOCLIM/'*NO CLIM'/
!
!----------
!  ENTRY CLINIT
!----------
ENTRY CLINIT
RETURN
!
!----------
!  ENTRY CLACTV
!----------
ENTRY CLACTV (L)
  L=.FALSE.
RETURN
!
!----------
!  ENTRY CLSETACTV
!----------
ENTRY CLSETACTV (L)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  LDANUW = L
RETURN
!
!----------
!  ENTRY CLPUT
!----------
ENTRY CLPUT (WK3,IPNT,ILIMIT)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = WK3(1)
  IDANUW = IPNT
  IDANUW = ILIMIT
RETURN
!
!----------
!  ENTRY CLGET
!----------
ENTRY CLGET (WK3,IPNT,ILIMIT)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = WK3(1)
  IDANUW = IPNT
  IDANUW = ILIMIT
RETURN
!
!----------
!  ENTRY CLIN
!----------
ENTRY CLIN  (DEBUG,LKECHO)
  CALL ERRGRO (.TRUE.,11)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  LDANUW = DEBUG
  LDANUW = LKECHO
RETURN
!
!----------
!  ENTRY CLKEY
!----------
ENTRY CLKEY(KEY,KEYWRD)
  KEYWRD=NOCLIM
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = KEY
RETURN
!
!----------
!  ENTRY CLGMULT
!----------
ENTRY CLGMULT(TREEMULT)
  TREEMULT=1.
RETURN
!
!----------
!  ENTRY CLMORTS
!----------
ENTRY CLMORTS
RETURN
!
!----------
!  ENTRY CLMAXDEN
!----------
ENTRY CLMAXDEN (SDIDEF,XMAX)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = SDIDEF(1)
  RDANUW = XMAX
RETURN
!
!----------
!  ENTRY CLAUESTB
!----------
ENTRY CLAUESTB
RETURN
!
!----------
!  ENTRY CLSPVIAB
!----------
ENTRY CLSPVIAB (ISP,VIA,IRC)
  IRC=1
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = VIA
  IDANUW = ISP
RETURN
!
!
END
