SUBROUTINE EXCOV
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!  EXTRA EXTERNAL REFERENCES FOR CVCNOP AND CVBROW CALLS.
!----------
REAL ARRAY(12)
REAL XDUM(*)
INTEGER KEY,I,J,JJ,II
LOGICAL LTHIN,LACTV,LNOTBK(12),LKECHO
CHARACTER*8 KEYWRD,NOCOV
REAL RDANUW
INTEGER IDANUW
CHARACTER*8 CDANUW
LOGICAL LDANUW
!
DATA NOCOV/'*NO COVR'/
!
!----------
!  ENTRY CVINIT
!----------
ENTRY CVINIT
RETURN
!
!----------
!  ENTRY CVIN
!----------
ENTRY CVIN (KEYWRD,ARRAY,LNOTBK,LKECHO)
  CALL ERRGRO (.TRUE.,11)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  CDANUW = KEYWRD
  RDANUW = ARRAY(1)
  LDANUW = LNOTBK(1)
  LDANUW = LKECHO
RETURN
!
!----------
!  ENTRY CVGO
!----------
ENTRY CVGO (LACTV)
  LACTV=.FALSE.
RETURN
!
!----------
!  ENTRY CVCNOP
!----------
ENTRY CVCNOP(LTHIN)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  LDANUW = LTHIN
RETURN
!
!----------
!  ENTRY CVBROW
!----------
ENTRY CVBROW(LTHIN)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  LDANUW = LTHIN
RETURN
!
!----------
!  ENTRY CVOUT
!----------
ENTRY CVOUT
RETURN
!
!----------
!  ENTRY CVKEY
!----------
ENTRY CVKEY(KEY,KEYWRD)
  KEYWRD=NOCOV
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = KEY
RETURN
!
!     REFERENCES FOR THE PARALLEL PROCESSING SYSTEM.
!
!----------
!  ENTRY CVGET
!----------
ENTRY CVGET (XDUM, I, J)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = XDUM(1)
  IDANUW = I
  IDANUW = J
RETURN
!----------
!  ENTRY CVPUT
!----------
ENTRY CVPUT (XDUM, I, J, II, JJ)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = XDUM(1)
  IDANUW = I
  IDANUW = J
  IDANUW = II
  IDANUW = JJ
RETURN
!----------
!  ENTRY CVACTV
!----------
ENTRY CVACTV (LACTV)
  LACTV=.FALSE.
RETURN
!
END
