SUBROUTINE EXDBS
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!  EXTERNAL REFERENCES FOR THE DATA BASE CONNECTION CODE.
!----------

INTEGER JOSTND,KEY,IWHO,NAGE
INTEGER IYEAR,IAGE,IPRDLEN,IACC,IFORTP,IMORT,ITPA,IBA,ISDI, &
        ICCF,ITOPHT,ITCUFT,IMCUFT,IBDFT,IRTPA,IRTCUFT,IRMCUFT, &
        IRBDFT,ISZCL,ISTCL,IATBA,IATSDI,IATCCF,IATTOPHT, &
        CNPYHT,SMORTBA,MMORTBA,SMORTVOL,MMORTVOL,BIOMASS, &
        CONSUMED,REMOVED,KODE,ITREE,IPLOT,HISTORY, &
        CRWNR,DMG1,DMG2,DMG3,SVR1,SVR2,SVR3,TREEVAL,PRESCRIPT, &
        SLOPE,ASPECT,HABITAT,TOPOCODE,SITEPREP,STANDGT3,STANDTOTAL, &
        SVLH,SVLS,YRLAST,PERTRCR,RCODE,S1NHT,S2NHT,S3NHT,S1LHT, &
        S2LHT,S3LHT,S1SHT,S2SHT,S3SHT,S1CB,S2CB,S3CB,S1CC,S2CC,S3CC, &
        TOTCOV,NS,S1SC,S2SC,S3SC,NTREES,NSCL,ISDSP
REAL SFLMSU,MFLMSU,TORCHI,CROWNI,CNPYDNST,SPSMOKE,MPSMOKE, &
       FUELWT,SFUELWT,FQMD,FATQMD,YMAI,LITTER,DUFF,SDEADLT3, &
       SDEADGT3,SDEAD3TO6,SDEAD6TO12,SDEADGT12,HERB,SHRUB, &
       SURFTOTAL,SNAGSLT3,SNAGSGT3,FOLIAGE,STANDLT3, &
       DBH,DG,HT,HTG,HTTOPK,RCOUNT,SFLMTO,MFLMTO,SPTRCH,MPTRCH, &
       HCL1,HCL2,HCL3,HCL4,HCL5,HCL6,SCL1,SCL2,SCL3,SCL4,SCL5,SCL6, &
       ONEHR,TENHR,HUNDHR,THOUSHR,LIVEW,LIVEH,MFWIND,FLAME,SCORCH, &
       KILLED,TOTAL,BAKILL,VOKILL,MSE,CLT3,CGT3,C3TO6,C6TO12,CGT12, &
       CROWN,CTOTAL,PERCDUFF,PERCGT3,SM25,SM10,SDBH,SHTH, &
       SHTS,SDH,SDS,S1DBH,S2DBH,S3DBH,TEM
REAL PREDBKP,POSTDBKP,RV,STD_BA,BAH,BAK,TPA,TPAH,TPAK, &
        VOL,VOLH,VOLKld,BA_SP,SPCL_TPA,IPSLSH,REMBKP, &
        SANBAREM,SANTREM1,SANTREM2,VOLREMSAN,VOLREMSAL
REAL aTPA(10),aTPAH(10),TPAKLL(10),SPCLTRE(10), &
      SAN1,SAN2,SAN3,SAN4,SAN5,SAN6,SAN7,SAN8,SAN9,SAN10
REAL OLDBKP,NEWBKP,SELFBKP,TO_LS,FRM_LS,BKPIN,BKPOUT, &
    BKPSV,STRPBKP,STRP_SC,DVRV1,DVRV2,DVRV3,DVRV4,DVRV5, &
    DVRV6,DVRV7,DVRV8,DVRV9,TPAFAST,BAFAST,VOLFAST,SDLO,SDHI
REAL TVOL(10),HVOL(10),VOLK(10),NUMSC
REAL    STDMR,STDMI,ABIRTH,CFVOL,BFVOL,STDIST
REAL    DCTPA(10),DCINF(10),DCMRT(10),DCDMR(10),DCDMI(10)
REAL    SPDMR4(4),SPDMI4(4),SPINF4(4),SPMRT4(4)
REAL    SPPIN4(4),SPPMR4(4),SPPOC4(4),WT(4),FILL(200)
REAL SPVIAB,SPBA,SPTPA,SPMORT1,SPMORT2,SPGMULT, &
        SPSITGM,MXDENMLT,POTESTAB
INTEGER I,J,FM(4),I1,I2,I3,I4,CID
INTEGER ISTTPAT,ISTVOL,ISTTPAI,ISTBAI,ISTVOLI,ISTTPAM,ISTBAM
INTEGER ISTVOLM,ISTPIT,ISTPIV,ISTPMT,ISTPMV,SPECIESID
INTEGER FUELMOD,SFUELMOD,VARDIM
DIMENSION FUELMOD(*),FUELWT(*),SFUELMOD(*),SFUELWT(*),KILLED(*), &
             TOTAL(*),BAKILL(*),VOKILL(*),SDBH(*),SHTH(*),SHTS(*), &
             SDH(*),SDS(*),SVLH(*),SVLS(*)
CHARACTER*(*) KEYWRD
CHARACTER*3 SPECIES,S1MS1,S1MS2,S2MS1,S2MS2,S3MS1,S3MS2
CHARACTER*4 SCLASS
CHARACTER*2 CSP(*),SPECCD
CHARACTER*8 NODBS,PASKEY,SFTYPE,MFTYPE,FTYPE
CHARACTER*26 NPLT
CHARACTER*3 NLABS(5)
CHARACTER*(*) HABTYP,SERIES
REAL ARRAY(*),VAR(*)
LOGICAL DEBUG,LACTV,LNOTBK(*),LCOUT,LCIN,LKECHO
integer :: beginAnalYear, endTime
real :: costUndisc, revUndisc, costDisc, revDisc, npv, irr, &
         bcRatio, rrr, sev, forestValue, reprodValue
logical :: sevCalculated, rrrCalculated, &
         forestValueCalculated, reprodValueCalculated, &
         irrCalculated, bcRatioCalculated
character(len=*) :: pretend
real :: minDia, maxDia, minDbh, maxDbh
integer :: tpaCut, tpaValue, tonsPerAcre, ft3Volume, ft3Value, &
         bfVolume, bfValue, totalValue
integer :: status
REAL RDANUW
INTEGER IDANUW
CHARACTER*1 CDANUW
LOGICAL LDANUW
!
! Entry parameter declarations
REAL BA,INGROW,TPAIN,TPASUM,HTAVE,TPATOT,WTHTAVE, &
     PRBSTK,SUMTPA,SUMPCT,BESTTPA,BESTPCT,AVEHT,PASTPA,PASPCT, &
     PCTNONE,PCTMECH,PCTBURN
INTEGER NUMPTS,M,NOYEAR,MECHYEAR,BURNYEAR,NTALLY,TOT
!
DATA NODBS/'*NO DBAS'/
!
!----------
!  ENTRY DBSIN
!----------
ENTRY DBSIN (KEYWRD,ARRAY,ISDSP,SDLO,SDHI,LNOTBK,LKECHO)
  CALL ERRGRO (.TRUE.,11)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  CDANUW(1:1) = KEYWRD(1:1)
  RDANUW = ARRAY(1)
  IDANUW = ISDSP
  RDANUW = SDLO
  RDANUW = SDHI
  LDANUW = LNOTBK(1)
  LDANUW = LKECHO
RETURN
!----------
!  ENTRY DBSINIT
!----------
ENTRY DBSINIT
RETURN
!----------
!  ENTRY DBSACTV
!----------
ENTRY DBSACTV(LACTV)
  LACTV = .FALSE.
RETURN
!----------
!  ENTRY DBSKEY
!----------
ENTRY DBSKEY (KEY,PASKEY)
  PASKEY=NODBS
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = KEY
RETURN
!----------
!  ENTRY DBSCMPU
!----------
ENTRY DBSCMPU
RETURN
!----------
!  ENTRY DBSCLOSE
!----------
ENTRY DBSCLOSE(LCOUT,LCIN)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  LDANUW = LCOUT
  LDANUW = LCIN
RETURN
!----------
!  ENTRY DBSSUMRY
!----------
ENTRY  DBSSUMRY(IYEAR,IAGE,NPLT,ITPA,IBA,ISDI,ICCF, &
     ITOPHT,FQMD,ITCUFT,IMCUFT,IBDFT,IRTPA,IRTCUFT,IRMCUFT,IRBDFT, &
     IATBA,IATSDI,IATCCF,IATTOPHT,FATQMD,IPRDLEN,IACC,IMORT,YMAI, &
     IFORTP,ISZCL,ISTCL)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IYEAR
  IDANUW = IAGE
  CDANUW = NPLT(1:1)
  IDANUW = ITPA
  IDANUW = IBA
  IDANUW = ISDI
  IDANUW = ICCF
  IDANUW = ITOPHT
  RDANUW = FQMD
  IDANUW = ITCUFT
  IDANUW = IMCUFT
  IDANUW = IBDFT
  IDANUW = IRTPA
  IDANUW = IRTCUFT
  IDANUW = IRMCUFT
  IDANUW = IRBDFT
  IDANUW = IATBA
  IDANUW = IATSDI
  IDANUW = IATCCF
  IDANUW = IATTOPHT
  RDANUW = FATQMD
  IDANUW = IPRDLEN
  IDANUW = IACC
  IDANUW = IMORT
  RDANUW = YMAI
  IDANUW = IFORTP
  IDANUW = ISZCL
  IDANUW = ISTCL
RETURN
!----------
!  ENTRY DBSSTATS
!----------
ENTRY  DBSSTATS(SPECCD,TPA,BA,CFVOL,BFVOL,STDIST)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  CDANUW = SPECCD
  RDANUW = TPA
  RDANUW = BA
  RDANUW = CFVOL
  RDANUW = BFVOL
  RDANUW = STDIST
RETURN
!----------
!  ENTRY DBSSPRT
!----------
ENTRY  DBSSPRT(SPECCD,TPASUM,HTAVE,TPATOT, &
     WTHTAVE,TOT,IYEAR)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  CDANUW = SPECCD
  RDANUW = TPASUM
  RDANUW = HTAVE
  RDANUW = TPATOT
  RDANUW = WTHTAVE
  IDANUW = TOT
  IDANUW = IYEAR
RETURN
!----------
!  ENTRY DBSSITEPREP
!----------
ENTRY  DBSSITEPREP(NOYEAR,MECHYEAR,BURNYEAR,PCTNONE, &
    PCTMECH,PCTBURN)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = NOYEAR
  IDANUW = MECHYEAR
  IDANUW = BURNYEAR
  IDANUW = PCTNONE
  IDANUW = PCTMECH
  IDANUW = PCTBURN
RETURN
!----------
!  ENTRY DBSPLOTHAB
!----------
ENTRY  DBSPLOTHAB(NUMPTS,HABTYP,SERIES,M)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = NUMPTS
  CDANUW = HABTYP
  CDANUW = SERIES
  IDANUW = M
RETURN
!----------
!  ENTRY DBSTALLY
!----------
ENTRY  DBSTALLY(PRBSTK,NTALLY,SPECCD,SUMTPA,SUMPCT,BESTTPA, &
    BESTPCT,AVEHT,PASTPA,PASPCT,IYEAR)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = PRBSTK
  IDANUW = NTALLY
  CDANUW = SPECCD
  RDANUW = SUMTPA
  RDANUW = SUMPCT
  RDANUW = BESTTPA
  RDANUW = BESTPCT
  RDANUW = AVEHT
  RDANUW = PASTPA
  RDANUW = PASPCT
  IDANUW = IYEAR
RETURN
!----------
!  ENTRY DBSINGROW
!----------
ENTRY  DBSINGROW(IYEAR,INGROW,SPECCD,TPAIN)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IYEAR
  RDANUW = INGROW
  CDANUW = SPECCD
  RDANUW = TPAIN
RETURN
!----------
!  ENTRY DBSATRTLS
!----------
ENTRY DBSATRTLS(IWHO,KODE,TEM)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IWHO
  IDANUW = KODE
  RDANUW = TEM
RETURN
!----------
!  ENTRY DBSTRLS
!----------
ENTRY DBSTRLS(IWHO,KODE,TEM)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IWHO
  IDANUW = KODE
  RDANUW = TEM
RETURN
!----------
!  ENTRY DBSCLSUM
!----------
ENTRY DBSCLSUM(NPLT,IYEAR,CSP,SPVIAB, &
             SPBA,SPTPA,SPMORT1,SPMORT2,SPGMULT, &
             SPSITGM,MXDENMLT,POTESTAB)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  CDANUW = NPLT(1:1)
  IDANUW = IYEAR
  CDANUW = CSP(1)(1:1)
  RDANUW = SPVIAB
  RDANUW = SPBA
  RDANUW = SPTPA
  RDANUW = SPMORT1
  RDANUW = SPMORT2
  RDANUW = SPGMULT
  RDANUW = SPSITGM
  RDANUW = MXDENMLT
  RDANUW = POTESTAB
RETURN
!----------
!  ENTRY DBSCUTS
!----------
ENTRY DBSCUTS(IWHO,KODE)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IWHO
  IDANUW = KODE
RETURN
!----------
!  ENTRY DBSFMPF
!----------
ENTRY DBSFMPF(IYEAR,NPLT,SFLMSU,MFLMSU,SFLMTO,MFLMTO,SFTYPE, &
     MFTYPE,SPTRCH,MPTRCH,TORCHI,CROWNI,CNPYHT, &
     CNPYDNST,SMORTBA,MMORTBA,SMORTVOL,MMORTVOL, &
     SPSMOKE,MPSMOKE,SFUELMOD,SFUELWT,FUELMOD,FUELWT,KODE)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IYEAR
  CDANUW = NPLT(1:1)
  RDANUW = SFLMSU
  RDANUW = MFLMSU
  RDANUW = SFLMTO
  RDANUW = MFLMTO
  CDANUW = SFTYPE(1:1)
  CDANUW = MFTYPE(1:1)
  RDANUW = SPTRCH
  RDANUW = MPTRCH
  RDANUW = TORCHI
  RDANUW = CROWNI
  IDANUW = CNPYHT
  RDANUW = CNPYDNST
  IDANUW = SMORTBA
  IDANUW = MMORTBA
  IDANUW = SMORTVOL
  IDANUW = MMORTVOL
  RDANUW = SPSMOKE
  RDANUW = MPSMOKE
  IDANUW = SFUELMOD(1)
  RDANUW = SFUELWT(1)
  IDANUW = FUELMOD(1)
  RDANUW = FUELWT(1)
  IDANUW = KODE
RETURN
!----------
!  ENTRY DBSFUELS
!----------
ENTRY DBSFUELS(IYEAR,NPLT,LITTER,DUFF,SDEADLT3,SDEADGT3,SDEAD3TO6, &
     SDEAD6TO12,SDEADGT12,HERB,SHRUB,SURFTOTAL,SNAGSLT3,SNAGSGT3, &
     FOLIAGE,STANDLT3,STANDGT3,STANDTOTAL,BIOMASS,CONSUMED,REMOVED, &
     KODE)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IYEAR
  CDANUW = NPLT(1:1)
  RDANUW = LITTER
  RDANUW = DUFF
  RDANUW = SDEADLT3
  RDANUW = SDEADGT3
  RDANUW = SDEAD3TO6
  RDANUW = SDEAD6TO12
  RDANUW = SDEADGT12
  RDANUW = HERB
  RDANUW = SHRUB
  RDANUW = SURFTOTAL
  RDANUW = SNAGSLT3
  RDANUW = SNAGSGT3
  RDANUW = FOLIAGE
  RDANUW = STANDLT3
  RDANUW = STANDGT3
  RDANUW = STANDTOTAL
  RDANUW = BIOMASS
  RDANUW = CONSUMED
  RDANUW = REMOVED
  IDANUW = KODE
RETURN
!----------
!  ENTRY DBSFMCRPT
!----------
ENTRY DBSFMCRPT(IYEAR,NPLT,VAR,VARDIM,KODE)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IYEAR
  CDANUW = NPLT(1:1)
  RDANUW = VAR(1)
  IDANUW = VARDIM
  IDANUW = KODE
RETURN
!----------
!  ENTRY DBSFMHRPT
!----------
ENTRY DBSFMHRPT(IYEAR,NPLT,VAR,VARDIM,KODE)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IYEAR
  CDANUW = NPLT(1:1)
  RDANUW = VAR(1)
  IDANUW = VARDIM
  IDANUW = KODE
RETURN
!----------
!  ENTRY DBSFMDWVOL
!----------
ENTRY DBSFMDWVOL(IYEAR,NPLT,VAR,VARDIM,KODE)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IYEAR
  CDANUW = NPLT(1:1)
  RDANUW = VAR(1)
  IDANUW = VARDIM
  IDANUW = KODE
RETURN
!----------
!  ENTRY DBSFMDWCOV
!----------
ENTRY DBSFMDWCOV(IYEAR,NPLT,VAR,VARDIM,KODE)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IYEAR
  CDANUW = NPLT(1:1)
  RDANUW = VAR(1)
  IDANUW = VARDIM
  IDANUW = KODE
RETURN
!----------
!  ENTRY DBSFMSSNAG
!----------
ENTRY DBSFMSSNAG(IYEAR,NPLT,HCL1,HCL2,HCL3,HCL4,HCL5,HCL6, &
     SCL1,SCL2,SCL3,SCL4,SCL5,SCL6,KODE)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IYEAR
  CDANUW = NPLT(1:1)
  RDANUW = HCL1
  RDANUW = HCL2
  RDANUW = HCL3
  RDANUW = HCL4
  RDANUW = HCL5
  RDANUW = HCL6
  RDANUW = SCL1
  RDANUW = SCL2
  RDANUW = SCL3
  RDANUW = SCL4
  RDANUW = SCL5
  RDANUW = SCL6
  IDANUW = KODE
RETURN
!----------
!  ENTRY DBSFMDSNAG
!----------
ENTRY DBSFMDSNAG(IYEAR,SDBH,SHTH,SHTS,SVLH,SVLS, &
     SDH,SDS,YRLAST,KODE)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IYEAR
  RDANUW = SDBH(1)
  RDANUW = SHTH(1)
  RDANUW = SHTS(1)
  IDANUW = SVLH(1)
  IDANUW = SVLS(1)
  RDANUW = SDH(1)
  RDANUW = SDS(1)
  IDANUW = YRLAST
  IDANUW = KODE
RETURN
!----------
!  ENTRY DBSFMFUEL
!----------
ENTRY DBSFMFUEL(IYEAR,NPLT,MSE,LITTER,DUFF,CLT3,CGT3, &
     C3TO6,C6TO12,CGT12,HERB,CROWN,CTOTAL,PERCDUFF,PERCGT3, &
     PERTRCR,SM25,SM10,KODE)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IYEAR
  CDANUW = NPLT(1:1)
  RDANUW = MSE
  RDANUW = LITTER
  RDANUW = DUFF
  RDANUW = CLT3
  RDANUW = CGT3
  RDANUW = C3TO6
  RDANUW = C6TO12
  RDANUW = CGT12
  RDANUW = HERB
  RDANUW = CROWN
  RDANUW = CTOTAL
  RDANUW = PERCDUFF
  RDANUW = PERCGT3
  IDANUW = PERTRCR
  RDANUW = SM25
  RDANUW = SM10
  IDANUW = KODE
RETURN
!----------
!  ENTRY DBSFMMORT
!----------
ENTRY DBSFMMORT(IYEAR,KILLED,TOTAL,BAKILL, &
     VOKILL,KODE)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IYEAR
  RDANUW = KILLED(1)
  RDANUW = TOTAL(1)
  RDANUW = BAKILL(1)
  RDANUW = VOKILL(1)
  IDANUW = KODE
RETURN
!----------
!  ENTRY DBSFMBURN
!----------
ENTRY DBSFMBURN(IYEAR,NPLT,ONEHR,TENHR,HUNDHR,THOUSHR,DUFF, &
     LIVEW,LIVEH,MFWIND,SLOPE,FLAME,SCORCH,FTYPE,FM,WT,KODE)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IYEAR
  CDANUW = NPLT(1:1)
  RDANUW = ONEHR
  RDANUW = TENHR
  RDANUW = HUNDHR
  RDANUW = THOUSHR
  RDANUW = DUFF
  RDANUW = LIVEW
  RDANUW = LIVEH
  RDANUW = MFWIND
  IDANUW = SLOPE
  RDANUW = FLAME
  RDANUW = SCORCH
  CDANUW = FTYPE(1:1)
  IDANUW = FM(1)
  RDANUW = WT(1)
  IDANUW = KODE
RETURN
!----------
!  ENTRY DBSFMCANPR
!----------
ENTRY DBSFMCANPR(IYEAR,FILL,NPLT)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IYEAR
  RDANUW = FILL(1)
  CDANUW = NPLT(1:1)
RETURN
!----------
!  ENTRY DBSFMLINK
!----------
ENTRY DBSFMLINK(I)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I
RETURN
!----------
!  ENTRY DBSTREESIN
!----------
ENTRY DBSTREESIN(IPLOT,ITREE,RCOUNT,HISTORY,SPECIES,DBH,DG, &
       HT,HTTOPK,HTG,CRWNR,DMG1,SVR1,DMG2,SVR2,DMG3,SVR3,TREEVAL, &
       PRESCRIPT,SLOPE,ASPECT,HABITAT,TOPOCODE,SITEPREP,KODE, &
       DEBUG,JOSTND,LKECHO,ABIRTH)
  KODE=0
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IPLOT
  IDANUW = ITREE
  RDANUW = RCOUNT
  IDANUW = HISTORY
  CDANUW = SPECIES(1:1)
  RDANUW = DBH
  RDANUW = DG
  RDANUW = HT
  RDANUW = HTTOPK
  RDANUW = HTG
  IDANUW = CRWNR
  IDANUW = DMG1
  IDANUW = SVR1
  IDANUW = DMG2
  IDANUW = SVR2
  IDANUW = DMG3
  IDANUW = SVR3
  IDANUW = TREEVAL
  IDANUW = PRESCRIPT
  IDANUW = SLOPE
  IDANUW = ASPECT
  IDANUW = HABITAT
  IDANUW = TOPOCODE
  IDANUW = SITEPREP
  LDANUW = DEBUG
  IDANUW = JOSTND
  LDANUW = LKECHO
  RDANUW = ABIRTH
RETURN
!----------
!  ENTRY DBSMIS1
!----------
ENTRY DBSMIS1(IYEAR,NPLT,CSP, &
     SPDMR4,SPDMI4,SPINF4,SPMRT4,SPPIN4,SPPMR4,SPPOC4, &
     KODE)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IYEAR
  CDANUW = NPLT(1:1)
  CDANUW = CSP(1)(1:1)
  RDANUW = SPDMR4(1)
  RDANUW = SPDMI4(1)
  RDANUW = SPINF4(1)
  RDANUW = SPMRT4(1)
  RDANUW = SPPIN4(1)
  RDANUW = SPPMR4(1)
  RDANUW = SPPOC4(1)
  IDANUW = KODE
RETURN
!----------
!  ENTRY DBSMIS2
!----------
ENTRY DBSMIS2(IYEAR,NPLT,NAGE, &
     ISTTPAT,IBA,ISTVOL,ISTTPAI,ISTBAI,ISTVOLI,ISTTPAM,ISTBAM, &
     ISTVOLM,ISTPIT,ISTPIV,ISTPMT,ISTPMV,STDMR,STDMI,KODE)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IYEAR
  CDANUW = NPLT(1:1)
  IDANUW = NAGE
  IDANUW = ISTTPAT
  IDANUW = IBA
  IDANUW = ISTVOL
  IDANUW = ISTTPAI
  IDANUW = ISTBAI
  IDANUW = ISTVOLI
  IDANUW = ISTTPAM
  IDANUW = ISTBAM
  IDANUW = ISTVOLM
  IDANUW = ISTPIT
  IDANUW = ISTPIV
  IDANUW = ISTPMT
  IDANUW = ISTPMV
  RDANUW = STDMR
  RDANUW = STDMI
  IDANUW = KODE
RETURN
!----------
!  ENTRY DBSMIS3
!----------
ENTRY DBSMIS3(IYEAR,NPLT,NLABS, &
     DCTPA,DCINF,DCMRT,DCDMR,DCDMI,KODE)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IYEAR
  CDANUW = NPLT(1:1)
  CDANUW = NLABS(1)(1:1)
  RDANUW = DCTPA(1)
  RDANUW = DCINF(1)
  RDANUW = DCMRT(1)
  RDANUW = DCDMR(1)
  RDANUW = DCDMI(1)
  IDANUW = KODE
RETURN
!----------
!  ENTRY DBSEVM
!----------
ENTRY DBSEVM (I,J,KODE,JOSTND)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I
  IDANUW = J
  IDANUW = KODE
  IDANUW = JOSTND
RETURN
!----------
!  ENTRY DBSPPPUT
!----------
ENTRY DBSPPPUT (ARRAY,I,J)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = ARRAY(1)
  IDANUW = I
  IDANUW = J
RETURN
!----------
!  ENTRY DBSPPGET
!----------
ENTRY DBSPPGET (ARRAY,I,J)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = ARRAY(1)
  IDANUW = I
  IDANUW = J
RETURN
!----------
!  ENTRY DBSPUSPUT
!----------
ENTRY DBSPUSPUT (KEYWRD,I,J)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  CDANUW(1:1) = KEYWRD(1:1)
  IDANUW = I
  IDANUW = J
RETURN
!----------
!  ENTRY DBSPUSGET
!----------
ENTRY DBSPUSGET (KEYWRD,I,J)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  CDANUW(1:1) = KEYWRD(1:1)
  IDANUW = I
  IDANUW = J
RETURN
!----------
!  ENTRY DBSCASE
!----------
ENTRY DBSCASE (I)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I
RETURN
!----------
!  ENTRY DBSVKFN
!----------
ENTRY DBSVKFN (KEYWRD)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  CDANUW(1:1) = KEYWRD(1:1)
RETURN
!----------
!  ENTRY DBSSTRCLASS
!----------
ENTRY DBSSTRCLASS(IYEAR,NPLT,RCODE,S1DBH,S1NHT,S1LHT,S1SHT, &
     S1CB,S1CC,S1MS1,S1MS2,S1SC,S2DBH,S2NHT,S2LHT,S2SHT,S2CB,S2CC, &
     S2MS1,S2MS2,S2SC,S3DBH,S3NHT,S3LHT,S3SHT,S3CB,S3CC,S3MS1,S3MS2, &
     S3SC,NS,TOTCOV,SCLASS,KODE,NTREES)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IYEAR
  CDANUW = NPLT(1:1)
  IDANUW = RCODE
  RDANUW = S1DBH
  IDANUW = S1NHT
  IDANUW = S1LHT
  IDANUW = S1SHT
  IDANUW = S1CB
  IDANUW = S1CC
  CDANUW = S1MS1(1:1)
  CDANUW = S1MS2(1:1)
  IDANUW = S1SC
  RDANUW = S2DBH
  IDANUW = S2NHT
  IDANUW = S2LHT
  IDANUW = S2SHT
  IDANUW = S2CB
  IDANUW = S2CC
  CDANUW = S2MS1(1:1)
  CDANUW = S2MS2(1:1)
  IDANUW = S2SC
  RDANUW = S3DBH
  IDANUW = S3NHT
  IDANUW = S3LHT
  IDANUW = S3SHT
  IDANUW = S3CB
  IDANUW = S3CC
  CDANUW = S3MS1(1:1)
  CDANUW = S3MS2(1:1)
  IDANUW = S3SC
  IDANUW = NS
  IDANUW = TOTCOV
  CDANUW = SCLASS(1:1)
  IDANUW = KODE
  IDANUW = NTREES
RETURN
!----------
!  ENTRY DBSBMMAIN
!----------
ENTRY DBSBMMAIN(NPLT,IYEAR,PREDBKP,POSTDBKP,RV,STD_BA,BAH, &
            BAK,TPA,TPAH,TPAK,VOL,VOLH,VOLKld,BA_SP,SPCL_TPA,IPSLSH, &
            SANBAREM,SANTREM1,SANTREM2,VOLREMSAN,VOLREMSAL, &
            REMBKP,CID)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  CDANUW = NPLT(1:1)
  IDANUW = IYEAR
  RDANUW = PREDBKP
  RDANUW = POSTDBKP
  RDANUW = RV
  RDANUW = STD_BA
  RDANUW = BAH
  RDANUW = BAK
  RDANUW = TPA
  RDANUW = TPAH
  RDANUW = TPAK
  RDANUW = VOL
  RDANUW = VOLH
  RDANUW = VOLKLD
  RDANUW = BA_SP
  RDANUW = SPCL_TPA
  RDANUW = IPSLSH
  RDANUW = SANBAREM
  RDANUW = SANTREM1
  RDANUW = SANTREM2
  RDANUW = VOLREMSAN
  RDANUW = VOLREMSAL
  RDANUW = REMBKP
  IDANUW = CID
RETURN
!----------
!  ENTRY DBSBMTREE
!----------
ENTRY DBSBMTREE(NSCL,NPLT,IYEAR,aTPA,aTPAH,TPAKLL,SPCLTRE, &
      SAN1,SAN2,SAN3,SAN4,SAN5,SAN6,SAN7,SAN8,SAN9,SAN10,CID)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = NSCL
  CDANUW = NPLT(1:1)
  IDANUW = IYEAR
  RDANUW = ATPA(1)
  RDANUW = ATPAH(1)
  RDANUW = TPAKLL(1)
  RDANUW = SPCLTRE(1)
  RDANUW = SAN1
  RDANUW = SAN2
  RDANUW = SAN3
  RDANUW = SAN4
  RDANUW = SAN5
  RDANUW = SAN6
  RDANUW = SAN7
  RDANUW = SAN8
  RDANUW = SAN9
  RDANUW = SAN10
  IDANUW = CID
RETURN
!----------
!  ENTRY DBSBMBKP
!----------
ENTRY DBSBMBKP(NPLT,IYEAR,OLDBKP,NEWBKP,SELFBKP, &
              TO_LS,FRM_LS,BKPIN,BKPOUT,BKPSV,STRPBKP, &
              STRP_SC,REMBKP,RV,DVRV1,DVRV2,DVRV3,DVRV4,DVRV5, &
              DVRV6,DVRV7,DVRV8,DVRV9,TPAFAST,BAFAST,VOLFAST,CID)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  CDANUW = NPLT(1:1)
  IDANUW = IYEAR
  RDANUW = OLDBKP
  RDANUW = NEWBKP
  RDANUW = SELFBKP
  RDANUW = TO_LS
  RDANUW = FRM_LS
  RDANUW = BKPIN
  RDANUW = BKPOUT
  RDANUW = BKPSV
  RDANUW = STRPBKP
  RDANUW = STRP_SC
  RDANUW = REMBKP
  RDANUW = RV
  RDANUW = DVRV1
  RDANUW = DVRV2
  RDANUW = DVRV3
  RDANUW = DVRV4
  RDANUW = DVRV5
  RDANUW = DVRV6
  RDANUW = DVRV7
  RDANUW = DVRV8
  RDANUW = DVRV9
  RDANUW = TPAFAST
  RDANUW = BAFAST
  RDANUW = VOLFAST
  IDANUW = CID
RETURN
!----------
!  ENTRY DBSBMVOL
!----------
ENTRY DBSBMVOL(NPLT,IYEAR,TVOL,HVOL,VOLK,NUMSC,CID)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  CDANUW = NPLT(1:1)
  IDANUW = IYEAR
  RDANUW = TVOL(1)
  RDANUW = HVOL(1)
  RDANUW = VOLK(1)
  RDANUW = NUMSC
  IDANUW = CID
RETURN
!----------
!  ENTRY DBSWW
!----------
ENTRY DBSWW (I1,I2,I3,I4)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I1
  IDANUW = I2
  IDANUW = I3
  IDANUW = I4
RETURN
!----------
!  ENTRY DBSWW2
!----------
ENTRY DBSWW2 (CID)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = CID
RETURN
!----------
!  ENTRY DBSECSUM
!----------
ENTRY DBSECSUM(beginAnalYear,endTime,pretend, &
             costUndisc,revUndisc,costDisc,revDisc, &
             npv,irr,irrCalculated,bcRatio,bcRatioCalculated, &
             rrr,rrrCalculated,sev,sevCalculated, &
             forestValue,forestValueCalculated, &
             reprodValue,reprodValueCalculated)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = BEGINANALYEAR
  IDANUW = ENDTIME
  CDANUW = PRETEND(1:1)
  RDANUW = COSTUNDISC
  RDANUW = REVUNDISC
  RDANUW = COSTDISC
  RDANUW = REVDISC
  RDANUW = NPV
  RDANUW = IRR
  LDANUW = IRRCALCULATED
  RDANUW = BCRATIO
  LDANUW = BCRATIOCALCULATED
  RDANUW = RRR
  LDANUW = RRRCALCULATED
  RDANUW = SEV
  LDANUW = SEVCALCULATED
  RDANUW = FORESTVALUE
  LDANUW = FORESTVALUECALCULATED
  RDANUW = REPRODVALUE
  LDANUW = REPRODVALUECALCULATED
RETURN
!----------
!  ENTRY DBSECHARV_OPEN
!----------
ENTRY DBSECHARV_open()
RETURN
!----------
!  ENTRY DBSECHARV_INSERT
!----------
ENTRY DBSECHARV_insert(beginAnalYear,speciesID,minDia,maxDia, &
             minDbh,maxDbh,tpaCut,tpaValue,tonsPerAcre,ft3Volume, &
             ft3Value,bfVolume,bfValue,totalValue)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = BEGINANALYEAR
  IDANUW = SPECIESID
  RDANUW = MINDIA
  RDANUW = MAXDIA
  RDANUW = MINDBH
  RDANUW = MAXDBH
  IDANUW = TPACUT
  IDANUW = TPAVALUE
  IDANUW = TONSPERACRE
  IDANUW = FT3VOLUME
  IDANUW = FT3VALUE
  IDANUW = BFVOLUME
  IDANUW = BFVALUE
  IDANUW = TOTALVALUE
RETURN
!----------
!  ENTRY DBSECHARV_CLOSE
!----------
ENTRY DBSECHARV_close()
RETURN
!----------
!  ENTRY GETDBSECONSTATUS
!----------
ENTRY getDbsEconStatus(status)
  status = 0
RETURN
!----------
!  ENTRY DBSCHPUT
!----------
ENTRY DBSCHPUT (KEYWRD,I1,I2)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  CDANUW(1:1) = KEYWRD(1:1)
  IDANUW = I1
  IDANUW = I2
RETURN
!----------
!  ENTRY DBSCHGET
!----------
ENTRY DBSCHGET (KEYWRD,I1,I2)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  CDANUW(1:1) = KEYWRD(1:1)
  IDANUW = I1
  IDANUW = I2
RETURN
!
END

