SUBROUTINE EXDFB
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     EXTRA EXTERNAL REFERENCES FOR DFB CALLS
!
LOGICAL L,LNOTBK,LKECHO
CHARACTER*8 KEYWRD,NODFB
REAL ARRAY(12)
DIMENSION LNOTBK(12)
INTEGER ICODES(6),II,KEY
REAL RDANUW
INTEGER IDANUW
CHARACTER*8 CDANUW
LOGICAL LDANUW
!
DATA NODFB/'*NO DFB'/
!
!----------
!  ENTRY DFBINT
!----------
ENTRY DFBINT
RETURN
!
!----------
!  ENTRY DFBIN
!----------
ENTRY DFBIN (KEYWRD,ARRAY,LNOTBK,LKECHO)
  CALL ERRGRO (.TRUE.,11)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  CDANUW(1:8) = KEYWRD(1:8)
  RDANUW = ARRAY(1)
  LDANUW = LNOTBK(1)
  LDANUW = LKECHO
RETURN
!
!----------
!  ENTRY DFBDAM
!----------
ENTRY DFBDAM (II,ICODES)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = II
  IDANUW = ICODES(1)
RETURN
!
!----------
!  ENTRY DFBSCH
!----------
ENTRY DFBSCH
RETURN
!
!----------
!  ENTRY DFBDRV
!----------
ENTRY DFBDRV
RETURN
!
!----------
!  ENTRY DFBBO
!----------
ENTRY DFBGO (L)
  L = .FALSE.
RETURN
!
!----------
!  ENTRY DFBOUT
!----------
ENTRY DFBOUT
RETURN
!
!----------
!  ENTRY DFBINV
!----------
ENTRY DFBINV
RETURN
!
!----------
!  ENTRY DFBWIN
!----------
ENTRY DFBWIN (L)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  LDANUW = L
RETURN
!
!----------
!  ENTRY DFBKEY
!----------
ENTRY DFBKEY (KEY,KEYWRD)
  KEYWRD=NODFB
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = KEY
RETURN
!
END
