SUBROUTINE EXDFTM
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     EXTRA EXTERNAL REFERENCES FOR DFTM CALLS
!
INTEGER II,MGMID,KEY
INTEGER ICODES(6)
LOGICAL L,LKECHO
CHARACTER*8 KEYWRD,NODFTM
CHARACTER*26 NPLT
INTEGER IDANUW
CHARACTER*8 CDANUW
LOGICAL LDANUW
!
DATA NODFTM/'*NO DFTM'/
!
!----------
!  ENTRY TMINIT
!----------
ENTRY TMINIT
RETURN
!
!----------
!  ENTRY DFTMIN
!----------
ENTRY DFTMIN(LKECHO)
  CALL ERRGRO (.TRUE.,11)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  LDANUW = LKECHO
RETURN
!
!----------
!  ENTRY TMDAM
!----------
ENTRY TMDAM (II,ICODES)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = II
  IDANUW = ICODES(1)
RETURN
!
!----------
!  ENTRY TMOPS
!----------
ENTRY TMOPS
RETURN
!
!----------
!  ENTRY TMCOUP
!----------
ENTRY TMCOUP
RETURN
!
!----------
!  ENTRY DFTMGO
!----------
ENTRY DFTMGO (L)
  L = .FALSE.
RETURN
!
!----------
!  ENTRY TMBMAS
!----------
ENTRY TMBMAS
RETURN
!
!----------
!  ENTRY TMHED
!----------
ENTRY TMHED (NPLT,MGMID)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  CDANUW(1:8) = NPLT(1:8)
  IDANUW = MGMID
RETURN
!
!----------
!  ENTRY TMOUT
!----------
ENTRY TMOUT
RETURN
!
!----------
!  ENTRY TMKEY
!----------
ENTRY TMKEY(KEY,KEYWRD)
  KEYWRD=NODFTM
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = KEY
RETURN
!
END
