SUBROUTINE EXFIRE
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!  EXTRA EXTERNAL REFERENCES FOR THE FIRE MODEL.
!----------
!
LOGICAL     LACTV,LDEB,LFM,LKECHO,L1,L2
!
CHARACTER*4 NSP(1,*)
CHARACTER*7 CH7
CHARACTER*8 KEYWRD,NOFM
CHARACTER*13 CFOTO
!
INTEGER     I,I1,I2,I3,I4,J,K,IYR
INTEGER     IVAC,IREC,ISPC,IC,ITFN,NCLAS,NR,NC,KEY
!
REAL        XMXVOL(*),CTCRWN(*),SSNG(*),DSNG(*),TKCRWN(*),FLNY(*)
REAL        D,H,P,X,WEIGHT,XXX(*),X1,X2,X3,X4,X5,X6
REAL        CRBSHT,CRBLKD,CANCOV,POKL,POVK
REAL        KFMS(*),FMWTS(*),FMLOADS(*),AX(*)
REAL RDANUW
INTEGER IDANUW
CHARACTER*1 CDANUW
LOGICAL LDANUW
!----------
!  DATA STATEMENTS:
!----------
DATA NOFM/'*NO FIRE'/
!----------
!  ENTRY POINTS:
!
!  ENTRY FMIN
!----------
ENTRY FMIN (I1,NSP,LKECHO)
  CALL ERRGRO (.TRUE.,11)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I1
  CDANUW = NSP(1,1)(1:1)
  LDANUW = LKECHO
RETURN
!----------
!  ENTRY FMINIT
!----------
ENTRY FMINIT
RETURN
!----------
!  ENTRY FMCMPR
!----------
ENTRY FMCMPR (NCLAS)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = NCLAS
RETURN
!----------
!  ENTRY FMTDEL
!----------
ENTRY FMTDEL (IVAC,IREC)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IVAC
  IDANUW = IREC
RETURN
!----------
!  ENTRY FMSDIT
!----------
ENTRY FMSDIT
RETURN
!----------
!  ENTRY FMMAIN
!----------
ENTRY FMMAIN
RETURN
!----------
!  ENTRY FMKILL
!----------
ENTRY FMKILL(I)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I
RETURN
!----------
!  ENTRY FMSSEE
!----------
ENTRY FMSSEE (I,ISPC,D,H,P,IC,LDEB,J)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I
  IDANUW = ISPC
  RDANUW = D
  RDANUW = H
  RDANUW = P
  IDANUW = IC
  LDANUW = LDEB
  IDANUW = J
RETURN
!----------
!  ENTRY FMSCUT
!----------
ENTRY FMSCUT(XMXVOL,NR,NC,SSNG,DSNG,CTCRWN,TKCRWN)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = XMXVOL(1)
  IDANUW = NR
  IDANUW = NC
  RDANUW = SSNG(1)
  RDANUW = DSNG(1)
  RDANUW = CTCRWN(1)
  RDANUW = TKCRWN(1)
RETURN
!----------
!  ENTRY FMSALV
!----------
ENTRY FMSALV(IYR,X1)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IYR
  RDANUW = X1
RETURN
!----------
!  ENTRY FMSVTREE
!----------
ENTRY FMSVTREE(I1,I2)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I1
  IDANUW = I2
RETURN
!----------
!  ENTRY FMSVFL
!----------
ENTRY FMSVFL(I)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I
RETURN
!----------
!  ENTRY FMGETFL
!----------
ENTRY FMGETFL(I,FLNY)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I
  RDANUW = FLNY(1)
RETURN
!----------
!  ENTRY FMKEY
!----------
ENTRY FMKEY(KEY,KEYWRD)
  KEYWRD=NOFM
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = KEY
RETURN
!----------
!  ENTRY FMOUT
!----------
ENTRY FMOUT
RETURN
!----------
!  ENTRY FMTRIP
!----------
ENTRY FMTRIP(ITFN,I,WEIGHT)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = ITFN
  IDANUW = I
  RDANUW = WEIGHT
RETURN
!----------
!  ENTRY FMPRUN
!----------
ENTRY FMPRUN(CTCRWN)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = CTCRWN(1)
RETURN
!----------
!  ENTRY FMATV
!----------
ENTRY FMATV(LACTV)
  LACTV = .FALSE.
RETURN
!----------
!  ENTRY FMLNKD
!----------
ENTRY FMLNKD(LACTV)
  LACTV = .FALSE.
RETURN
!----------
!  ENTRY FMEVSNG
!----------
ENTRY FMEVSNG(X, I, J, K, X1, X2, X3, X4, I4)
  I4=1
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = X
  IDANUW = I
  IDANUW = J
  IDANUW = K
  RDANUW = X1
  RDANUW = X2
  RDANUW = X3
  RDANUW = X4
RETURN
!----------
!  ENTRY FMEVCWD
!----------
ENTRY FMEVCWD(X, I, J, I4)
  I4=1
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = X
  IDANUW = I
  IDANUW = J
RETURN
!----------
!  ENTRY FMEVFLM
!----------
ENTRY FMEVFLM(X, I, I4)
  I4=1
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = X
  IDANUW = I
RETURN
!----------
!  ENTRY FMEVSAL
!----------
ENTRY FMEVSAL(X,I,I1,I2,I4)
  I4=1
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = X
  IDANUW = I
  IDANUW = I1
  IDANUW = I2
RETURN
!----------
!  ENTRY FMEVMRT
!----------
ENTRY FMEVMRT(X,I,I4)
  I4=1
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = X
  IDANUW = I
RETURN
!----------
!  ENTRY FMEVTYP
!----------
ENTRY FMEVTYP(X,I,I4)
  I4=1
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = X
  IDANUW = I
RETURN
!----------
!  ENTRY FMEVCARB
!----------
ENTRY FMEVCARB(X,I,I4)
  I4=1
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = X
  IDANUW = I
RETURN
!----------
!  ENTRY FMDWD
!----------
ENTRY FMDWD(X,I,J,K,I2,I4)
  I4=1
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = X
  IDANUW = I
  IDANUW = J
  IDANUW = K
  IDANUW = I2
RETURN
!----------
!  ENTRY FMEVSRT
!----------
ENTRY FMEVSRT(X,I,I4)
  I4=1
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = X
  IDANUW = I
RETURN
!----------
!  ENTRY FMEVRIN
!----------
ENTRY FMEVRIN(X,I,I4)
  I4=1
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = X
  IDANUW = I
RETURN
!----------
!  ENTRY FMEVFMD
!----------
ENTRY FMEVFMD(X,I,J,I4)
  I4=1
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = X
  IDANUW = I
  IDANUW = J
RETURN
!----------
!  ENTRY FMSADD
!----------
ENTRY FMSADD (I,J)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I
  IDANUW = J
RETURN
!----------
!  ENTRY FMSATV
!----------
ENTRY FMSATV(LFM)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  LDANUW = LFM
RETURN
!----------
!  ENTRY FMPHOTOCODE
!----------
ENTRY FMPHOTOCODE(I,CFOTO,J,K)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I
  CDANUW = CFOTO(1:1)
  IDANUW = J
  IDANUW = K
RETURN
!----------
!  ENTRY FMTREM
!----------
ENTRY FMTREM(DSNG,SSNG,AX)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = DSNG(1)
  RDANUW = SSNG(1)
  RDANUW = AX(1)
RETURN
!----------
!  ENTRY FMEVTBM
!----------
ENTRY FMEVTBM(X1,I,I1,I2,I3,X2,X3,X4,X5,I4)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = X1
  IDANUW = I
  IDANUW = I1
  IDANUW = I2
  IDANUW = I3
  RDANUW = X2
  RDANUW = X3
  RDANUW = X4
  RDANUW = X5
  IDANUW = I4
RETURN
!----------
!  ENTRY FMEVMSN
!----------
ENTRY FMEVMSN(X)
  X=0.
RETURN
!----------
!  ENTRY FMEVLSF
!----------
ENTRY FMEVLSF(X, I, I4)
  X=0.
  I4=1
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I
RETURN
!----------
!     ENTRIES FOR THE PPE:
!
!  ENTRY FMPPHV
!----------
ENTRY FMPPHV(IYR,CRBSHT,CRBLKD,CANCOV,KFMS,FMWTS, &
                POKL,POVK,FMLOADS)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IYR
  RDANUW = CRBSHT
  RDANUW = CRBLKD
  RDANUW = CANCOV
  RDANUW = KFMS(1)
  RDANUW = FMWTS(1)
  RDANUW = POKL
  RDANUW = POVK
  RDANUW = FMLOADS(1)
RETURN
!----------
!  ENTRY FMPPGET
!----------
ENTRY FMPPGET (XXX,I1,I2)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = XXX(1)
  IDANUW = I1
  IDANUW = I2
RETURN
!----------
!  ENTRY FMPPPUT
!----------
ENTRY FMPPPUT (XXX,I1,I2)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = XXX(1)
  IDANUW = I1
  IDANUW = I2
RETURN
!----------
!  ENTRY FMSVL2
!----------
ENTRY FMSVL2(I1,X1,X2,X3,X4,L1,L2,I2)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I1
  RDANUW = X1
  RDANUW = X2
  RDANUW = X3
  RDANUW = X4
  LDANUW = L1
  LDANUW = L2
  IDANUW = I2
RETURN
!----------
!  ENTRY FMSNGHT
!----------
ENTRY FMSNGHT(CH7,I1,X1,X2,I2,X3)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  CDANUW = CH7(1:1)
  IDANUW = I1
  RDANUW = X1
  RDANUW = X2
  IDANUW = I2
  RDANUW = X3
RETURN
!----------
!  ENTRY FMSNGDK
!----------
ENTRY FMSNGDK(CH7,I1,X1,X2)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  CDANUW = CH7(1:1)
  IDANUW = I1
  RDANUW = X1
  RDANUW = X2
RETURN
!----------
!  ENTRY FMSFALL
!----------
ENTRY FMSFALL(I1,I2,X1,X2,X3,I3,X4,X5,X6)
  X6 = 0.
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I1
  IDANUW = I2
  RDANUW = X1
  RDANUW = X2
  RDANUW = X3
  IDANUW = I3
  RDANUW = X4
  RDANUW = X5
  RDANUW = X6
RETURN
!----------
!  ENTRY SNGCOE
!----------
ENTRY SNGCOE
RETURN
!----------
!  ENTRY FMCBA
!----------
ENTRY FMCBA (I1,I2)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I1
  IDANUW = I2
RETURN
!
END
