SUBROUTINE EXPPE
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     ENTRY EXTERNAL REGERENCES FOR THE PARALLEL PROCESSING EXTENSION.
!----------
LOGICAL L
CHARACTER C*8,CISN*11
INTEGER IA(*), JA(*)
INTEGER I,J,I2,I3
REAL R,X,R2,X1,X2
REAL RDANUW
INTEGER IDANUW
CHARACTER*8 CDANUW
!----------
!  ENTRY PPECYC
!     CALLED BY INSCYC TO FIND OUT IF IS LEGAL TO INSERT A CYCLE AT
!     YEAR I
!----------
ENTRY PPECYC (I,L)
  L=.TRUE.
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I
RETURN
!----------
!  ENTRY PPEATV
!     RETURNS L, TO INDICATE THAT PPE IS NOT PART OF THE PROGRAM.
!----------
ENTRY PPEATV (L)
  L=.FALSE.
RETURN
!----------
!  ENTRY PPEVMI: EVENT MONITOR/PPE INTERFACE. SIMPLY RETURNS.
!----------
ENTRY PPEVMI (I,IA,JA,J)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I
  IDANUW = J
  IDANUW = IA(1)
  IDANUW = JA(1)
RETURN
!----------
!  ENTRY PPLDEV: LOAD THE EVENT MONITOR PPE VARIABLES.
!----------
ENTRY PPLDEV
RETURN
!----------
!  ENTRY PPLDX
!     CALLED TO LOAD PPE VARIALBES FOR EXPRESSION EVALUATION.  RETURN
!     A CODE INDICATING THAT THE REQUESTED VARIABLE IS UNDEFINED.
!----------
ENTRY PPLDX (R,I,I2)
  I2=1
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I
  RDANUW = R
RETURN
!----------
!  ENTRY PPKEY
!     CALLED TO FIND THE NUMBER OF USER-DEFINED VARIALBES.  PASS BACK
!     A CODE INDICATING THAT THE VARIABLE COULD NOT BE FOUND.
!----------
ENTRY PPKEY (C,I,I2)
  I2=1
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I
  CDANUW(1:8) = C(1:8)
RETURN
!----------
!  ENTRY PPBRPH
!     CALLED BY TREGRO TO FIND OUT IF SOME PARTS OF TREGRO NEED TO
!     BE SKIPPED.
!----------
ENTRY PPBRPH (I)
  I=0
RETURN
!----------
!  ENTRY PPLABS
!     NEEDED BY CVOUT AND OTHER ROUTINES TO WRITE THE CORRECT LABELS
!----------
ENTRY PPLABS (J)
!----------
!     WRITE THE STAND POLICY LABEL...
!----------
  CALL LBSPLW (J)
RETURN
!----------
!  ENTRY PPISN: RETURNS THE CURRENT ISN.
!----------
ENTRY PPISN (CISN)
  CISN='00000000000'
RETURN
!----------
!  ENTRY PPISND: RETURNS THE CURRENT STAND NUMBER.
!----------
ENTRY PPISND (I)
  I=0
RETURN
!----------
!  ENTRY PPWEIG
!     CALLED BY PRTRLS TO GET THE SAMPLING WEIGHT FOR THE TREELIST.
!----------
ENTRY PPWEIG (I,X)
  X=0.0
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I
RETURN
!----------
!  ENTRY PPCLOP
!     CALLED BY GROHED TO CLOSE THE OPTION OUTPUT TABLE, IF NEEDED.
!----------
ENTRY PPCLOP (I)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I
RETURN
!----------
!  ENTRY MSTRGT
!----------
ENTRY MSTRGT
RETURN
!----------
!  ENTRY MSTRPT
!----------
ENTRY MSTRPT
RETURN
!----------
!  ENTRY GPNEW
!----------
ENTRY GPNEW (I,I2,I3,R,R2)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I
  IDANUW = I2
  IDANUW = I3
  RDANUW = R
  RDANUW = R2
RETURN
!----------
!  ENTRY GPCLOS
!----------
ENTRY GPCLOS
RETURN
!----------
!  ENTRY PPPDEN
!     CALLED TO MODIFIY THE POINT DENSITY STATISTICS FOR THE ESTAB
!     MODEL FOR MODELING EFFECTS OF NEIGHBORING DENSITY.
!     (CALLED FROM GRADD).
!----------
ENTRY PPPDEN
RETURN
!----------
! ENTRY FMPPHV_REPORT
! CALLED BY THE FFE POTENTIAL FIRE PROGRAM TO STORE SOME DATA
!----------
ENTRY FMPPHV_REPORT(X1,X2)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = X1
  RDANUW = X2
RETURN
!
END
