SUBROUTINE EXRD
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     EXTRA EXTERNAL REFERENCES FOR THE WESTERN ROOT DISEASE MODEL
!     VERSION 3.0
!
!
INCLUDE 'PRGPRM.f90'
!
!----------
INTEGER ICODES(6),I3(*),I2(*),ITN1,ITN2,II,I,I1,II1
INTEGER ILIMIT,IPNT,II2,III2,KEY
REAL ARRAY(12),R1(*),RR2,RR1,OLD,WK3
LOGICAL L,LNOTBK(12),LTR,LTEE,LDUM,LKECHO
CHARACTER*8 KEYWRD,NORR
REAL RDANUW
INTEGER IDANUW
CHARACTER*8 CDANUW
LOGICAL LDANUW
!
DATA NORR/'*NO RROT'/
!----------
!  ENTRY RDIN CALLED FROM INITRE
!----------
ENTRY RDIN (KEYWRD,ARRAY,LNOTBK,LKECHO)
  CALL ERRGRO (.TRUE.,11)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = ARRAY(1)
  CDANUW(1:8) = KEYWRD(1:8)
  LDANUW = LNOTBK(1)
  LDANUW = LKECHO
RETURN
!----------
!  ENTRY RDATV CALLED FROM INTREE
!----------
ENTRY RDATV(L,LTEE)
  L=.FALSE.
  LTEE=.FALSE.
RETURN
!----------
!  ENTRY RDTRES CALLED FROM INTREE
!----------
ENTRY RDTRES (ITN1,ITN2)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = ITN1
  IDANUW = ITN2
RETURN
!----------
!  ENTRY RDINIT CALLED FROM INITRE
!----------
ENTRY RDINIT
RETURN
!----------
!  ENTRY RDDAM CALLED FROM DAMCDS
!----------
ENTRY RDDAM  (II,ICODES)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = II
  IDANUW = ICODES(1)
RETURN
!----------
!  ENTRY RDTRP CALLED FROM MAIN, GRINCR
!----------
ENTRY RDTRP(LTR)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  LDANUW = LTR
RETURN
!----------
!  ENTRY RDROUT CALLED FROM MAIN
!----------
ENTRY RDROUT
RETURN
!----------
!  ENTRY RDPRIN CALLED FROM NOTRE
!----------
ENTRY RDPRIN (I)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I
RETURN
!----------
!  ENTRY RDESIN CALLED FROM INITRE
!----------
ENTRY RDESIN
RETURN
!----------
! RDTREG CALLED FROM GRADD
!----------
ENTRY RDTREG
RETURN
!----------
!  ENTRY RDCMPR CALLED FROM COMPRS
!----------
ENTRY RDCMPR (I1,R1,I2,I3)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I1
  IDANUW = I2(1)
  IDANUW = I3(1)
  RDANUW = R1(1)
RETURN
!----------
!  ENTRY RDSTR CALLED FROM CUTS
!----------
ENTRY RDSTR (II1,RR1,RR2)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = II1
  RDANUW = RR1
  RDANUW = RR2
RETURN
!----------
!  ENTRY RDESCP CALLED FROM ESTAB, ESUCKR
!----------
ENTRY RDESCP (II1,II2)
  II2=II1
RETURN
!----------
!  ENTRY RDESTB CALLED FROM ESTAB
!----------
ENTRY RDESTB (I1,R1)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I1
  RDANUW = R1(1)
RETURN
!----------
!  ENTRY RDMN1 CALLED FROM MAIN
!----------
ENTRY RDMN1 (II)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = II
RETURN
!----------
!  ENTRY RDMN2 CALLED FROM GRINCR
!----------
ENTRY RDMN2 (OLD)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = OLD
RETURN
!----------
!  ENTRY RDPR CALLED FROM MAIN
!----------
ENTRY RDPR
RETURN
!----------
!  ENTRY RDTRIP CALLED FROM TRIPLE
!----------
ENTRY RDTRIP (II1,III2,RR1)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = II1
  IDANUW = III2
  RDANUW = RR1
RETURN
!----------
!  ENTRY RDTDEL CALLED FROM TREDEL
!----------
ENTRY RDTDEL (II1,II2)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = II1
  IDANUW = II2
RETURN
!----------
!  ENTRY RDKEY CALLED FROM OPLIST
!----------
ENTRY RDKEY (KEY,KEYWRD)
  KEYWRD=NORR
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = KEY
RETURN
!----------
!  ENTRY RDPPATV - PPE -
!----------
ENTRY RDPPATV (LDUM)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  LDANUW = LDUM
RETURN

!----------
!  ENTRY RDPPPT - PPE -
!----------
ENTRY RDPPPT (WK3,IPNT,ILIMIT)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = WK3
  IDANUW = IPNT
  IDANUW = ILIMIT
RETURN
!----------
!  ENTRY RDPPGT - PPE -
!----------
ENTRY RDPPGT (WK3,IPNT,ILIMIT)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  RDANUW = WK3
  IDANUW = IPNT
  IDANUW = ILIMIT
RETURN
!
END
