SUBROUTINE EXSV
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     STAND VISUALIZATION EXTERNAL REFERENCES
!     N.L.CROOKSTON -- RMRS MOSCOW -- MARCH 1998
!     A.H.DALLMANN -- RMRS MOSCOW -- JANUARY 2000
!
INTEGER I1,I2,I
LOGICAL L(*)
REAL A(*),A1(*),A2(*)
CHARACTER*(*) C
INTEGER IDX(*)
REAL RDANUW
INTEGER IDANUW
CHARACTER*1 CDANUW
LOGICAL LDANUW
!----------
!  ENTRY SVCMP1
!----------
ENTRY SVCMP1
RETURN
!----------
!  ENTRY SVCMP2
!----------
ENTRY SVCMP2(I1,I2)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I1
  IDANUW = I2
RETURN
!----------
!  ENTRY SVCMP3
!----------
ENTRY SVCMP3
RETURN
!----------
!  ENTRY SVCUTS
!----------
ENTRY SVCUTS(I,A,A1,A2)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I
  RDANUW = A(1)
  RDANUW = A1(1)
  RDANUW = A2(1)
RETURN
!----------
!  ENTRY SVMORT
!----------
ENTRY SVMORT (I1, A, I2)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I1
  IDANUW = I2
  RDANUW = A(1)
RETURN
!----------
!  ENTRY SVOUT
!----------
ENTRY SVOUT(I1,I2,C)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I1
  IDANUW = I2
  CDANUW = C(1:1)
RETURN
!----------
!  ENTRY SVTOBJ
!----------
ENTRY SVTOBJ(I1)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I1
RETURN
!----------
!  ENTRY SVINIT
!----------
ENTRY SVINIT
RETURN
!----------
!  ENTRY SVKEY
!----------
ENTRY SVKEY(C,L,A)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  CDANUW = C(1:1)
  LDANUW = L(1)
  RDANUW = A(1)
RETURN
!----------
!  ENTRY SVSTART
!----------
ENTRY SVSTART
RETURN
!----------
!  ENTRY SVTDEL
!----------
ENTRY SVTDEL(IDX,I2)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = IDX(1)
  IDANUW = I2
RETURN
!----------
!  ENTRY SVTRIP
!----------
ENTRY SVTRIP(I1,I2)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I1
  IDANUW = I2
RETURN
!----------
!  ENTRY SVESTB
!----------
ENTRY SVESTB(I1)
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
  IF(.TRUE.)RETURN
  IDANUW = I1
RETURN
!
END




