SUBROUTINE FORMCL(ISPC,IFOR,D,FC)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
! THIS PROGRAM CALCULATES FORM FACTORS FOR CALCULATING CUBIC AND
! BOARD FOOT VOLUMES.
!
! THIS IS THE VANILLA VERSION FOR USE IN VARIANTS THAT DON'T USE
! FORM CLASS, OR ONLY SET DEFAULT FORM CLASSES BY SPECIES.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
!OMMONS
!
INTEGER IFOR,ISPC
REAL FC,D
REAL RDANUW
INTEGER IDANUW
!
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
RDANUW = D
IDANUW = IFOR
!
!----------
!  LOAD FORM CLASS VALUE
!----------
FC=FRMCLS(ISPC)
!
RETURN
END
