SUBROUTINE FVS(IRTNCD)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     THE PROGNOSIS MODEL FOR STAND DEVELOPMENT
!
!     DEVELOPED UNDER THE LEADERSHIP OF:
!
!     DR. ALBERT R. STAGE
!     FORESTRY SCIENCES LABORATORY
!     INTERMOUNTAIN FOREST AND RANGE EXPERIMENT STATION
!     USDA  --  FOREST SERVICE
!     1221 SOUTH MAIN
!     MOSCOW, IDAHO   83843    --    USA.
!
!     PHONE (208) 882-3557
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'OUTCOM.f90'
!
!
INCLUDE 'PDEN.f90'
!
!
INCLUDE 'ECON.f90'
!
!
INCLUDE 'WORKCM.f90'
!
!
!OMMONS
!

!DEC$ ATTRIBUTES DLLEXPORT, C, DECORATE, ALIAS : "FVS" :: FVS
!DEC$ ATTRIBUTES REFERENCE :: IRTNCD

INTEGER I,IA,N,K,J
REAL STAGEA,STAGEB
LOGICAL DEBUG,LCVGO
INTEGER IBA
INTEGER IRSTRTCD,ISTOPDONE,IRTNCD,ISTOPRES,lenCl
!
!     ******************     EXECUTION BEGINS     ******************
!
DEBUG=.FALSE.
!-----------
!  SEE IF WE NEED TO DO SOME DEBUG.
!  NEEDED FOR STOP/RESTART DEBUG OPTION TO CONTINUE.
!-----------
CALL DBCHK (DEBUG,'MAIN',4,0)

!     Check the current return code, if -1 the cmdLine has never been processed.

call fvsGetRtnCode(IRTNCD)
if (IRTNCD == -1) then
  lenCl = 0
  CALL fvsSetCmdLine(' ',lenCl,IRTNCD)
  IF (IRTNCD.NE.0) RETURN
endif

!     FIND THE RESTART, AND BRANCH AS REQUIRED

call fvsRestart (IRSTRTCD)
call fvsGetRtnCode(IRTNCD)

IF (DEBUG) WRITE(JOSTND,*) "In FVS, IRSTRTCD=",IRSTRTCD, &
     & " IRTNCD=",IRTNCD
if (IRTNCD.ne.0) return
if (IRSTRTCD.lt.0) return
if (IRSTRTCD.eq.7) goto 19
if (IRSTRTCD.ge.1) goto 41
!
ICL1=0
LSTART = .TRUE.
LFLAG = .TRUE.
ICYC=0
!
!     INITIATE THE PROGNOSIS
!
CALL INITRE
CALL fvsGetRtnCode(IRTNCD)
IF (IRTNCD.NE.0) RETURN
!-----------
!  SEE IF WE NEED TO DO SOME DEBUG.
!-----------
CALL DBCHK (DEBUG,'MAIN',4,0)
!
!     PROCESS ARRAY IY
!
IF (NCYC.LE.0)  NCYC=1
IF (NCYC.GT.MAXCYC) NCYC=MAXCYC
DO I = 2, MAXCY1
   IF (IY(I).EQ.-1) IY(I)=10
   IY(I) = IY(I-1) + IY(I)
ENDDO
!
!     ADD IN CYCLES FOR REQUESTED YEARS...BUT DO NOT EXTEND THE END
!     OR CHANGE THE BEGINNING OF THE SIMULATION.
!
IF (IWORK1(1).GT.0) THEN
  DO IA=2,IWORK1(1)+1
    IF (IWORK1(IA).LE.IY(1).OR.IWORK1(IA).GE.IY(NCYC+1)) THEN
      CYCLE
    ELSE
      N=NCYC
      DO I=1,N
        IF (IWORK1(IA).GT.IY(I).AND.IWORK1(IA).LT.IY(I+1)) THEN
          NCYC=NCYC+1
          IF (NCYC.GT.MAXCYC) NCYC=MAXCYC
          DO K=NCYC+1,I+2,-1
            IY(K)=IY(K-1)
          ENDDO
          IY(I+1)=IWORK1(IA)
          EXIT
        ENDIF
      ENDDO
    ENDIF
  ENDDO
ENDIF
!
!     WRITE BUG MODEL HEADERS AND WRITE AND PROCESS OPTION LISTS
!     THE CALL TO TMOPTS MUST BE PLACED BEFORE CALL OPEXPN AS TMOPTS
!     CALLS SCHED WHICH CHANGES THE CONTENTS OF THE ARRAY IY.
!
CALL MPBOPS
CALL TMOPS
CALL DFBSCH
!
!     SET UP ECON COST & REVENUE INDEXES BY SPECIES
!     CALL ECSETP PRIOR TO PROCESSING ACTIVITY SCHEDULE TO ENSURE CORRECT ECON ACTIVITY SORTING
!
CALL ECSETP(IY)
!
!     PROCESS AND LIST THE ACTIVITY SCHEDULE.
!
CALL OPEXPN (JOSTND,NCYC,IY)
CALL OPCYCL (NCYC,IY)
IF(ITABLE(4).EQ.0)CALL OPLIST (.TRUE.,NPLT,MGMID,ITITLE)
!
!     SET UP INDEX POINTERS TO SPECIES SORT.
!
CALL SETUP
!
!     CALCULATE TREES/ACRE ( = LOAD PROB )
!
CALL NOTRE
!
!     WESTERN ROOT DISEASE MODEL VER. 3.0 INITIALIZATION
!
CALL RDMN1 (1)
!
!     COMPUTE DEAD LPP/ACRE.
!
CALL MPSDLP
!
!     COMPUTE DEAD DFB/ACRE.
!
CALL DFBINV

ICYC = 1
!
!     SET THE OPTION POINTERS FOR THE INITIALIZATION PHASE TO
!     THE CYCLE-1 OPTIONS.
!
CALL OPCSET(ICYC)
!
!     PROCESS STOPPOINT 7

CALL fvsStopPoint (7,ISTOPRES)
IF (ISTOPRES.NE.0) RETURN
CALL fvsGetRtnCode(IRTNCD)
IF (IRTNCD.NE.0) RETURN
!     BRANCH HERE IF RESTARTING FROM STOPCODE 7
19 CONTINUE
!
!     CALIBRATE GROWTH FUNCTIONS AND FILL GAPS
!     SDICLS IS CALLED HERE SO CROWNS WILL DUB CORRECTLY IN VARIANTS
!     USING THE WEIBULL DISTRIBUTION
!
CALL SDICLS(0,0.,999.,1,SDIAC,SDIAC2,STAGEA,STAGEB,0)
CALL CRATET
!
!     SET CALIBRATION AND FLAG BEST TREE RECORDS FOR ESTAB. MODEL.
!
CALL ESFLTR
!
ICYC = 0
!
!     COMPUTE INITIAL CROWN WIDTH VALUES.
!
CALL CWIDTH
!
!     COMPUTE INITIAL VOLUME STATISTICS
!
CALL VOLS
!
!     COMPUTE INITIAL PERCENTILE POINTS IN THE DISTRIBUTION OF
!     DIAMETERS FOR ALL VOLUME STANDARDS.  FIRST CONVERT VOLUMES TO A
!     PER ACRE REPRESENTATION (SKIP IF THERE ARE NO TREE RECORDS).
!
IF (ITRN.LE.0) GOTO 25
DO 20 I=1,ITRN
CFV(I)=CFV(I)*PROB(I)
BFV(I)=BFV(I)*PROB(I)
MCFV(I)=MCFV(I)*PROB(I)
SCFV(I)=SCFV(I)*PROB(I)
ABVGRD_BIO(I)=ABVGRD_BIO(I)*PROB(I)
MERCH_BIO(I)=MERCH_BIO(I)*PROB(I)
CUBSAW_BIO(I)=CUBSAW_BIO(I)*PROB(I)
FOLI_BIO(I)=FOLI_BIO(I)*PROB(I)
ABVGRD_CARB(I)=ABVGRD_CARB(I)*PROB(I)
MERCH_CARB(I)=MERCH_CARB(I)*PROB(I)
CUBSAW_CARB(I)=CUBSAW_CARB(I)*PROB(I)
FOLI_CARB(I)=FOLI_CARB(I)*PROB(I)

20 CONTINUE
25 CONTINUE
CALL PCTILE(ITRN,IND,CFV,WK3,OCVCUR(7))
CALL DIST(ITRN,OCVCUR,WK3)
CALL PCTILE(ITRN,IND,BFV,WK3,OBFCUR(7))
CALL DIST(ITRN,OBFCUR,WK3)
CALL PCTILE(ITRN,IND,MCFV,WK3,OMCCUR(7))
CALL DIST(ITRN,OMCCUR,WK3)
CALL PCTILE(ITRN,IND,SCFV,WK3,OSCCUR(7))
CALL DIST(ITRN,OSCCUR,WK3)
!     COMPUTE BIOMASS AND CARBON
CALL PCTILE(ITRN,IND,ABVGRD_BIO,WK3,OAGBIOCUR(7))
CALL DIST(ITRN,OAGBIOCUR,WK3)
CALL PCTILE(ITRN,IND,MERCH_BIO,WK3,OMERBIOCUR(7))
CALL DIST(ITRN,OMERBIOCUR,WK3)
CALL PCTILE(ITRN,IND,CUBSAW_BIO,WK3,OCSAWBIOCUR(7))
CALL DIST(ITRN,OCSAWBIOCUR,WK3)
CALL PCTILE(ITRN,IND,FOLI_BIO,WK3,OFOLIBIO(7))
CALL DIST(ITRN,OFOLIBIO,WK3)
!
CALL PCTILE(ITRN,IND,ABVGRD_CARB,WK3,OAGCARBCUR(7))
CALL DIST(ITRN,OAGCARBCUR,WK3)
CALL PCTILE(ITRN,IND,MERCH_CARB,WK3,OMERCARBCUR(7))
CALL DIST(ITRN,OMERCARBCUR,WK3)
CALL PCTILE(ITRN,IND,CUBSAW_CARB,WK3,OCSAWCARBCUR(7))
CALL DIST(ITRN,OCSAWCARBCUR,WK3)
CALL PCTILE(ITRN,IND,FOLI_CARB,WK3,OFOLICARB(7))
CALL DIST(ITRN,OFOLICARB,WK3)

!
!     IF THERE ARE TREE RECORDS, THEN: CONVERT CFV TO A PER TREE
!     REPRESENTATION.
!
IF (ITRN.LE.0) GOTO 35
DO 30 I=1,ITRN
CFV(I)=CFV(I)/PROB(I)
BFV(I)=BFV(I)/PROB(I)
MCFV(I)=MCFV(I)/PROB(I)
SCFV(I)=SCFV(I)/PROB(I)
ABVGRD_BIO(I)=ABVGRD_BIO(I)/PROB(I)
MERCH_BIO(I)=MERCH_BIO(I)/PROB(I)
CUBSAW_BIO(I)=CUBSAW_BIO(I)/PROB(I)
FOLI_BIO(I)=FOLI_BIO(I)/PROB(I)
ABVGRD_CARB(I)=ABVGRD_CARB(I)/PROB(I)
MERCH_CARB(I)=MERCH_CARB(I)/PROB(I)
CUBSAW_CARB(I)=CUBSAW_CARB(I)/PROB(I)
FOLI_CARB(I)=FOLI_CARB(I)/PROB(I)
30 CONTINUE
35 CONTINUE
!
!     ASSIGN THE EXAMPLE TREES TO THE OUTPUT ARRAYS.
!
CALL EXTREE
!
!     FIND OUT IF THE COVER MODEL WILL BE CALLED.
!
CALL CVGO (LCVGO)
!
!     CALL **CVBROW** TO COMPUTE SHRUB DENSITY AND WILDLIFE
!     BROWSE STATISTICS (MAKE THIS CALL REGARDLESS OF LCVGO).
!
IF(DEBUG) WRITE(JOSTND,9000) ICYC
9000 FORMAT(' CALLING CVBROW, CYCLE=',I2)
CALL CVBROW (.FALSE.)
!
!     CALL **CVCNOP** TO COMPUTE CANOPY COVER STATISTICS.
!
IF (DEBUG) WRITE (JOSTND,8005) ICYC
8005 FORMAT (' CALLING CVCNOP, CYCLE =',I2)
CALL CVCNOP (.FALSE.)
!
!     CALL **STATS** TO COMPUTE STATISTICAL DESCRIPTION OF INPUT DATA.
!
IF(DEBUG) WRITE(JOSTND,9005) ICYC
9005 FORMAT(' CALLING STATS, CYCLE = ',I2)
CALL STATS
!
!     OUTPUT SIMULATION REFERENCE DATA
!
CALL DBSREFERENCE
!
!     WRITE OUTPUT HEADING FOR STAND COMP TABLE IF NOT TO BE SUPPRESSED
!     USING DELOTAB KEYWORD.
!
IF (ITABLE(1) .EQ. 0) CALL GHEADS (NPLT,MGMID,JOSTND,0,ITITLE)
!
!     WRITE INITIAL STAND STATISTICS.  MAKE SURE THAT ICL6 IS POSITIVE
!
ICL6=1
CALL DISPLY
CALL fvsGetRtnCode(IRTNCD)
IF (IRTNCD.NE.0) RETURN
!
!     IF TREE LIST OUTPUT IS REQUESTED...CALL TREE LIST PRINTER.
!
CALL MISPRT
CALL PRTRLS (1)
CALL DBS_FIAVBC_TRLS
!
!     CREATE THE INITIAL STAND VISULIZATION.
!
CALL SVSTART
!
!     LOAD OLD VOLUME VARIABLES WITH CYCLE 0 VOLUMES
!
CALL FVSSTD (1)
!
!     DONE WITH DEAD TREES THAT WERE PRESENT IN THE INVENTORY. PURGE
!     THEM FROM THE LIST (VIA RESET POINTER)
!
IREC2=MAXTP1
!
!     WESTERN ROOT DISEASE MODEL VER. 3.0 MODEL INITIALIZATION
!
CALL RDMN1 (2)
CALL RDPR
!
!     BLISTER RUST MODEL INITIALIZATION
!
CALL BRSETP
CALL BRPR
!
LFLAG=.FALSE.
LSTART = .FALSE.
!
!     INITIALIZE TYPE 1 EVENT MONTITOR VARIABLES
!
CALL EVTSTV(-1)
!
!     PROJECT THE TREE GROWTH AND PRINT STATISTICS
!
40 CONTINUE
!
!     ADVANCE TIME INCREMENT
!
ICYC = ICYC + 1

41 CONTINUE
!
!     SIMULATE HARVEST (THINNINGS), GROWTH, MORTALITY, AND
!     ESTABLISHMENT.
!
IF (DEBUG) WRITE (JOSTND,50) ICYC
50 FORMAT (/,' CALLING TREGRO, CYCLE = ',I4)
CALL TREGRO
CALL fvsGetRtnCode(IRTNCD)
IF (IRTNCD.NE.0) RETURN
CALL getAmStopping (ISTOPDONE)
IF (ISTOPDONE.NE.0) RETURN
!
!     ASSIGN THE EXAMPLE TREES TO THE OUTPUT ARRAYS.
!
CALL EXTREE
!
!     WRITE STAND STATISTICS
!
IF (DEBUG) WRITE (JOSTND,70) ICYC
70 FORMAT (/,' CALLING DISPLY, CYCLE = ',I4)
CALL DISPLY
CALL fvsGetRtnCode(IRTNCD)
IF (IRTNCD.NE.0) RETURN
!
!     CALL RESAGE TO RESET STAND AGE.
!
CALL RESAGE
!
!     DWARF MISTLETOE MODEL OUTPUT
!
CALL MISPRT
!
!     WESTERN ROOT DISEASE MODEL VER. 3.0 OUTPUT
!
CALL RDPR
!
!     BLISTER RUST MODEL OUTPUT
!
CALL BRPR
!
!     IF TREE LIST OUTPUT IS REQUESTED...CALL TREE LIST PRINTER.
!
CALL PRTRLS (1)
CALL DBS_FIAVBC_TRLS
!
!     IF RUNNING FVSSTAND POST-PROCESSOR, CALL FILE PRINTER.
!
CALL FVSSTD (1)
!
IF ( ICYC .LT. NCYC ) THEN
  CALL ClearRestartCode
  GOTO 40
ENDIF

!     signal that stopping for this stand can not continue.

call fvsStopPoint (-1,ISTOPDONE)
!
!     PROJECTION COMPLETED.  SET ICL6 NEGATIVE, SAVE DENSITIES
!     FOR PRINTING, AND CALL DISPLY.
!
ICYC=ICYC+1
ICL6=-99
ONTREM(7)=0.0
OLDTPA=TPROB
OLDBA=BA
OLDAVH=AVH
ORMSQD=RMSQD
ODR016=DR016
RELDM1=RELDEN
CALL SDICLS(0,0.,999.,1,SDIBC,SDIBC2,STAGEA,STAGEB,0)
SDIAC=SDIBC
SDIAC2=SDIBC2
!
CALL DISPLY
CALL fvsGetRtnCode(IRTNCD)
IF (IRTNCD.NE.0) RETURN

IBA = 1
CALL SSTAGE(IBA,ICYC,.FALSE.)
!
!     PRINT THE VISULIZATION FOR FINAL OUTPUT.
!
CALL SVOUT(IY(ICYC),3,'End of projection')
LFLAG=.TRUE.
CALL ESOUT (LFLAG)
CALL CVOUT
CALL MPBOUT
CALL DFBOUT
CALL TMOUT
CALL BWEOUT
!      CALL RDROUT ! RD output now handled by GENPRT 12/5/14 LD
CALL BRROUT
!
CALL GENPRT
!
RETURN
!
END

