SUBROUTINE GRADD (DEBUG,IPMODI,LTMGO,LMPBGO,LDFBGO, &
                     LBWEGO,LCVATV)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     UPDATES TREE DESCRIPTIONS, COMPUTES END-OF-CYCLE SHRUB AND
!     CVBROW STATISTICS, ESTABLISHIES NEW TREES, AND COMPUTES OTHER
!     END-OF-CYCLE STATISTICS.
!
!     CALLED FROM: TREGRO
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'COEFFS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'OUTCOM.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'OPCOM.f90'
!
!
!OMMONS
!
LOGICAL LTMGO,LMPBGO,LDFBGO,LBWEGO,LCVATV,DEBUG
!
!     DIMENSION SPCNT -- CUMULATIVE TREES PER ACRE BY SPECIES AND
!                        TREE CLASS.
!
REAL SPCNT(MAXSP,3)
INTEGER IPMODI,I,IS,IYR1,IYR2,IFIRES,IDT,ISTAT,KODE, &
           NPRMS,ILE,IM,ISTOPRES,IRTNCD
REAL SCALE,D,BARK,BRATIO,DDS
!
!     GET THE RESTART CODE AND BRANCH ACCORDINGLY
!
CALL fvsGetRestartCode (ISTOPRES)
!
IF (DEBUG) WRITE (JOSTND,10) NPLT,ICYC,ISTOPRES
10 FORMAT (/' IN GRADD, NPLT=',A26,'; ICYC=',I2,'; ISTOPRES=',I2)
IF (ISTOPRES.EQ.5) GOTO 57
IF (ISTOPRES.EQ.6) GOTO 97

!----------
!  CALL **MPBCUP** IF THERE IS A MOUNTAIN PINE BEETLE OUTBREAK THIS
!  CYCLE. NOTE THAT DG MUST BE ON A YR-PERIOD BASIS FOR MPBMOD.
!----------
IF (IPMODI.EQ.1 .AND.LMPBGO) THEN
   IF (DEBUG) WRITE(JOSTND,20) ICYC
20    FORMAT (' CALLING MPBCUP, CYCLE=',I2)
   CALL MPBCUP
ENDIF
!
!     CALL DFBDRV IF THERE IS A DOUGLAS-FIR BEETLE OUTBREAK THIS
!     CYCLE.
!
CALL DFBWIN(LDFBGO)
IF (IPMODI .EQ. 1 .AND. LDFBGO) THEN
   CALL DFBDRV
ENDIF
!
!     SCALE DIAMETER GROWTH TO A FINT-YEAR BASIS.
!
IF (ITRN.GT.0 .AND. FINT.NE.YR) THEN
   SCALE=FINT/YR
   DO 30 I=1,ITRN
   IS=ISP(I)
   D=DBH(I)
   BARK=BRATIO(IS,D,HT(I))
   IF(DG(I) .GT. 0.) THEN
     DDS=(DG(I)*(2.0*BARK*D+DG(I)))*SCALE
     DG(I)=SQRT((D*BARK)**2+DDS)-BARK*D
   ELSE
     DG(I)=0.0
   ENDIF
30    CONTINUE
ENDIF
!
!     CALL MISTLETOE SUBROUTINE
!
CALL MISTOE
!
!     CALL **TMCOUP** IF THERE IS A TUSSOCK MOTH OUTBREAK THIS CYCLE.
!
IF (IPMODI.EQ.1 .AND. LTMGO) THEN
   IF (DEBUG) WRITE (JOSTND,40) ICYC
40    FORMAT(' CALLING TMCOUP, CYCLE=',I2)
   CALL TMCOUP
ENDIF
!
!     CALL THE WESTERN SPRUCE BUDWORM (BUDLITE) MODEL INTERFACE.
!
IF (IPMODI.EQ.1 .AND. LBWEGO) THEN
   IF (DEBUG) WRITE(JOSTND,50) ICYC
50    FORMAT (' CALLING BWECUP, CYCLE=',I2)
   CALL BWECUP
ENDIF
!
!     CALL THE FIRE MODEL
!
IF (DEBUG) WRITE(JOSTND,51) ICYC
51 FORMAT (' CALLING FMMAIN, CYCLE=',I2)
CALL FMMAIN
CALL fvsGetRtnCode(IRTNCD)
IF (IRTNCD.NE.0) RETURN

CALL FMKILL(1)
!
!     CALL BLISTER RUST SUBROUTINE TO BEGIN SIMULATION.
!
CALL BRTREG
!
!     CALL WESTERN ROOT DISEASE VER. 3.0 SUBROUTINE TO BEGIN DISEASE
!     SIMULATION
!
CALL RDTREG
!
!     CALL THE FIRE MODEL MORTALITY ROUTINE
!
CALL FMKILL(2)
!----------
!  SET LFIRE=.TRUE. IF A SIMFIRE KEYWORD WAS USED THIS CYCLE
!  LFIRE CONTROLS USE OF OLDBA, OLDTPA AND ORMSQD IN POST-DISTURBANCE
!  COVER CALCULATIONS IN THE **CVCBMS AND CCFCAL** ROUTINES
!----------
IF(ICYC.LE.0)THEN
  IYR1=IY(1)
  IYR2=IY(1)
ELSE
  IYR1=IY(ICYC)
  IYR2=IY(ICYC+1)
ENDIF
IFIRES=0
IDT=0
ISTAT=0
CALL OPSTUS (2506,IYR1,IYR2,0,IFIRES,IDT,NPRMS,ISTAT,KODE)
IF((ISTAT.GT.0).AND.(IDT.GE.IYR1).AND.(IDT.LE.IYR2))THEN
  LFIRE=.TRUE.
ENDIF
!
!     CALL HTGSTP TO PROCESS HTGSTOP OPTION, IF USED.
!
CALL HTGSTP
!
!     UPDATE THE VISULIZATION FOR MORTALITY
!
IF (DEBUG) WRITE (JOSTND,55) ICYC
55 FORMAT(' CALLING SVMORT, CYCLE=',I2)
CALL SVMORT (0,WK2,IY(ICYC))
!
!     UPDATE TREE DESCRIPTIONS.
!
!     IS THIS A STOPPING POINT?
!
CALL fvsStopPoint (5,ISTOPRES)
IF (ISTOPRES.NE.0) RETURN
CALL fvsGetRtnCode(IRTNCD)
IF (IRTNCD.NE.0) RETURN
!
!     BRANCH HERE IF RESTARTING FROM STOPCODE=5.
!
57 CONTINUE
IF (DEBUG) WRITE (JOSTND,60) ICYC
60 FORMAT(' CALLING UPDATE, CYCLE=',I2)
CALL UPDATE
!
!     RESORT THE TREE RECORDS BY DIAMETER.
!
IF (DEBUG) WRITE (JOSTND,70) ICYC
70 FORMAT(' CALLING RDPSRT, CYCLE=',I2)
IF(ITRN.GT.0)CALL RDPSRT(ITRN,DBH,IND,.TRUE.)
!
!     CALL **DENSE** TO CALCULATE POST-MORTALITY AND BAI DENSITY STATS.
!
IF (DEBUG) WRITE (JOSTND,80) ICYC
80 FORMAT(' CALLING DENSE, CYCLE=',I2)
CALL DENSE
!
!     CALL **CVBROW** TO COMPUTE SHRUB DENSITY AND WILDLIFE CVBROW
!     STATISTICS.
!
CALL CVGO (LCVATV)
IF (DEBUG.AND.LCVATV) WRITE (JOSTND,90) ICYC
90 FORMAT(' CALLING CVBROW, CYCLE=',I2)
IF (LCVATV) CALL CVBROW (.FALSE.)
!
!     INCREMENT ABIRTH ARRAY
!
DO 95 I= 1, ITRN
ABIRTH(I)= ABIRTH(I) + FINT
95 CONTINUE
!
!     IS THIS A STOPPING POINT?
!
CALL fvsStopPoint (6,ISTOPRES)
IF (ISTOPRES.NE.0) RETURN
CALL fvsGetRtnCode(IRTNCD)
IF (IRTNCD.NE.0) RETURN
!
!     BRANCH HERE IF RESTARTING FROM STOPCODE=6.
!
97 CONTINUE
!
!     CALL CLIMATE-DRIVEN ESTABLISHMENT
!
IF (DEBUG) WRITE(JOSTND,99) ICYC
99 FORMAT(' CALLING CLAUESTB, CYCLE=',I2)
CALL CLAUESTB
!
!     CALL THE REGENERATION ESTABLISHMENT SUBSYSTEM.
!
IF (DEBUG) WRITE(JOSTND,100) ICYC
100 FORMAT(' CALLING ESNUTR, CYCLE=',I2)
CALL ESNUTR
!
!     UPDATE THE VISULIZATION FOR NEW TREES
!
IF (DEBUG) WRITE (JOSTND,105) ICYC
105 FORMAT(' CALLING SVESTB, CYCLE=',I2)
CALL SVESTB(1)
!
!     CALL ECCALC TO CALCULATE COSTS & REVENUES FOR ECON EXTENSION
!
CALL ECCALC(IY, ICYC, JSP, MGMID, NPLT, ITITLE)
!
!     CALL DENSE TO CALCULATE POST-ESTABLISHMENT DENSITY.
!
IF (DEBUG) WRITE(JOSTND,80) ICYC
CALL DENSE
!
!     CALCULATE CHANGE IN CROWN RATIOS.
!
IF (DEBUG) WRITE (JOSTND,110) ICYC,NPLT
110 FORMAT(' CALLING CROWN, CYCLE=',I2,'  NPLT= ',A)
CALL CROWN
!
!     UPDATE CROWN WIDTHS
!
CALL CWIDTH
!
!     CALL **CVCNOP** TO COMPUTE CROWN AREA AND FOLIAGE BIOMASS
!     STATISTICS.
!
IF (DEBUG.AND.LCVATV) WRITE (JOSTND,120) ICYC
120 FORMAT (' CALLING CVCNOP, CYCLE=',I3)
IF (LCVATV) CALL CVCNOP (.FALSE.)
!
!     SAVE PCT IN OLDPCT TO RETAIN AN OLD PCTILE VALUE
!
IF (ITRN.GT.0) THEN
   DO 130 ILE=1,ITRN
   OLDPCT(ILE)= PCT(ILE)
130    CONTINUE
   DO 140 I=1,MAXSP
   SPCNT(I,1)=0.0
   SPCNT(I,2)=0.0
   SPCNT(I,3)=0.0
140    CONTINUE
!
!        ACCUMULATE TREES PER ACRE BY SPECIES AND TREE CLASS.
!
   DO 150 I=1,ITRN
   IS=ISP(I)
   IM=IMC(I)
   SPCNT(IS,IM)=SPCNT(IS,IM)+PROB(I)
150    CONTINUE
ENDIF
!
!     COMPUTE DISTRIBUTION OF DIAMETERS AND SPECIES-TREE CLASS COMPOS.
!     FOR TREES PER ACRE.  IF NEW TREES HAVE BEEN ADDED VIA THE
!     ESTABLISHMENT SUBSYSTEM AND/OR THE TREE COMPRESSION HAS
!     TAKEN PLACE, INS WILL BE REDEFINED IN THE NEXT CALL TO DIST.
!
CALL PCTILE(ITRN,IND,PROB,WK3,ONTCUR(7))
CALL DIST(ITRN,ONTCUR,WK3)
CALL COMP(OSPCT,IOSPCT,SPCNT)
!
!     COMPUTE PERCENTILE POINTS IN THE DISTRIBUTION OF DIAMETERS FOR
!     TOTAL CUBIC VOLUME.  THIS CALL IS PLACED HERE SO THAT ACCRETION
!     DISTRIBUTION RELATES TO DIAMETERS AT THE START OF THE CYCLE AND
!     TOTAL VOLUME DISTRIBUTION RELATES TO UPDATED DIAMETERS. FIRST
!     CONVERT VOLUMES TO A PER ACRE REPRESENTATION.
!
IF (ITRN.GT.0) THEN
   DO 160 I=1,ITRN
   CFV(I)=CFV(I)*PROB(I)
   BFV(I)=BFV(I)*PROB(I)
   MCFV(I)=MCFV(I)*PROB(I)
   SCFV(I)=SCFV(I)*PROB(I)
   ABVGRD_BIO(I)=ABVGRD_BIO(I)*PROB(I)
   MERCH_BIO(I)=MERCH_BIO(I)*PROB(I)
   CUBSAW_BIO(I)=CUBSAW_BIO(I)*PROB(I)
   FOLI_BIO(I)=FOLI_BIO(I)*PROB(I)
   ABVGRD_CARB(I)=ABVGRD_CARB(I)*PROB(I)
   MERCH_CARB(I)=MERCH_CARB(I)*PROB(I)
   CUBSAW_CARB(I)=CUBSAW_CARB(I)*PROB(I)
   FOLI_CARB(I)=FOLI_CARB(I)*PROB(I)
160    CONTINUE
ENDIF
CALL PCTILE(ITRN,IND,CFV,WK3,OCVCUR(7))
CALL DIST(ITRN,OCVCUR,WK3)
CALL PCTILE(ITRN,IND,BFV,WK3,OBFCUR(7))
CALL DIST(ITRN,OBFCUR,WK3)
CALL PCTILE(ITRN,IND,MCFV,WK3,OMCCUR(7))
CALL DIST(ITRN,OMCCUR,WK3)
CALL PCTILE(ITRN,IND,SCFV,WK3,OSCCUR(7))
CALL DIST(ITRN,OSCCUR,WK3)
!     CARBON AND BIOMASS
IF(LFIANVB) THEN
  CALL PCTILE(ITRN,IND,ABVGRD_BIO,WK3,OAGBIOCUR(7))
  CALL DIST(ITRN,OAGBIOCUR,WK3)
  CALL PCTILE(ITRN,IND,MERCH_BIO,WK3,OMERBIOCUR(7))
  CALL DIST(ITRN,OMERBIOCUR,WK3)
  CALL PCTILE(ITRN,IND,CUBSAW_BIO,WK3,OCSAWBIOCUR(7))
  CALL DIST(ITRN,OCSAWBIOCUR,WK3)
  CALL PCTILE(ITRN,IND,FOLI_BIO,WK3,OFOLIBIO(7))
  CALL DIST(ITRN,OFOLIBIO,WK3)
  CALL PCTILE(ITRN,IND,ABVGRD_CARB,WK3,OAGCARBCUR(7))
  CALL DIST(ITRN,OAGCARBCUR,WK3)
  CALL PCTILE(ITRN,IND,MERCH_CARB,WK3,OMERCARBCUR(7))
  CALL DIST(ITRN,OMERCARBCUR,WK3)
  CALL PCTILE(ITRN,IND,CUBSAW_CARB,WK3,OCSAWCARBCUR(7))
  CALL DIST(ITRN,OCSAWCARBCUR,WK3)
  CALL PCTILE(ITRN,IND,FOLI_CARB,WK3,OFOLICARB(7))
  CALL DIST(ITRN,OFOLICARB,WK3)
ENDIF
!
!     CONVERT CFV BACK TO A PER TREE REPRESENTATION. ALLOW FOR THE
!     FACT THAT SOME PROBS MAY BE ZERO (NL CROOKSTON, 06/11/91).
!
IF (ITRN.GT.0) THEN
   DO 170 I=1,ITRN
   IF (PROB(I).GT.0.0) THEN
      CFV(I)=CFV(I)/PROB(I)
      MCFV(I)=MCFV(I)/PROB(I)
      SCFV(I)=SCFV(I)/PROB(I)
      BFV(I)=BFV(I)/PROB(I)
      IF(LFIANVB) THEN
        ABVGRD_BIO(I)=ABVGRD_BIO(I)/PROB(I)
        MERCH_BIO(I)=MERCH_BIO(I)/PROB(I)
        CUBSAW_BIO(I)=CUBSAW_BIO(I)/PROB(I)
        FOLI_BIO(I)=FOLI_BIO(I)/PROB(I)
        ABVGRD_CARB(I)=ABVGRD_CARB(I)/PROB(I)
        MERCH_CARB(I)=MERCH_CARB(I)/PROB(I)
        CUBSAW_CARB(I)=CUBSAW_CARB(I)/PROB(I)
        FOLI_CARB(I)=FOLI_CARB(I)/PROB(I)
      ENDIF
   ENDIF
170    CONTINUE
ENDIF
RETURN
END
