!ODE SEGMENT HTCAL
!----------
! COMMON $Id$
!----------
!
LOGICAL LHCOR2
!
LOGICAL LHTCAL(MAXSP)
!
INTEGER IFINTH,IHTG
!
REAL    FINTH
!
REAL    HCOR2(MAXSP),HSIG(MAXSP)
!
COMMON /HTCAL/ FINTH,HCOR2,HSIG,IFINTH,IHTG,LHCOR2,LHTCAL
!
!----------
!  HEIGHT GROWTH CALIBRATION COMMON /HTCAL/
!----------
!     FINTH = MEASURMENT PERIOD FOR SMALL TREE HEIGHT GROWTH.
!     HCOR2 = USER SUPPLIED CORRECTION TERMS...TO CORRECT THE
!             HEIGHT GROWTH MODELS PRIOR TO CALIBRATION.
!     HSIG  = DUMMY...MAY BE USED FOR SIGMAS.
!     IFINTH= INTEGER VERSION OF FINTH.
!     IHTG  = THE HEIGHT GROWTH VERSION OF IDG.
!     LHCOR2= TRUE IF HCOR2 IS TO BE USED TO MODIFY HEIGHT GROWTH
!             MODELS. SET FALSE IN GRINIT.
!     LHTCAL= TRUE IF HEIGHT GROWTH CALIBRATION IS TO BE DONE,
!             SET TRUE IN GRINIT.
!
!-----END SEGMENT
