SUBROUTINE HTGSTP
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
!OMMONS
!
EXTERNAL RANN
INTEGER MYACT(2)
INTEGER NEW,IOD,ITRC1,ITRC2,I,K,IG,IULIM,IGRP,I1,I2,IS,IS1,IS2
INTEGER ISPC,IDT,IACT,NP,ITODO,NTODO
REAL STDPBR,AVEPRB,PRB,HT1,HT2,H,BRK,BRATIO,X,PKIL,BACHLO
REAL TOPK,TOPH,D,AF,DTK,CN
EQUIVALENCE (WK6(2),HT1),(WK6(3),HT2),(WK6(4),PRB), &
               (WK6(5),AVEPRB),(WK6(6),STDPBR)
DATA MYACT/110,111/
!
!     FIND OPTIONS
!
CALL OPFIND(2,MYACT,NTODO)
IF (NTODO .EQ. 0) RETURN
!
!     ENTER LOOP TO PROCESS ALL OPTIONS SPECIFIED.
!
DO 200 ITODO=1,NTODO
CALL OPGET(ITODO,6,IDT,IACT,NP,WK6)
IF (IACT.LT.0) GOTO 200
CALL OPDONE (ITODO,IY(ICYC))
!
!     LOAD PARAMETERS.  NOTE THAT SEVERAL PARAMETERS ARE EQUIVALENCED
!     TO WK6 THUS THEY ARE LOADED AUTOMATICALLY.
!
ISPC=IFIX(WK6(1))
!
!     SET INDICIES TO SPECIES COUNTERS.
!
IF (ISPC.LE.0) GOTO 10
IS1=ISPC
IS2=ISPC
GOTO 20
10 CONTINUE
IS1=1
IS2=MAXSP
20 CONTINUE
!
!     ENTER SPECIES LOOP
!
DO 110 IS=IS1,IS2
I1=ISCT(IS,1)
!
!     IF THERE ARE NO TREES OF THIS SPECIES, THEN BRANCH.
!
IF (I1.LE.0) GOTO 110
!
!     LOAD TREE INDEX.
!
I2=ISCT(IS,2)
!----------
!  IF PROCESSING A SPECIES GROUP AND THIS SPECIES IS NOT IN THE GROUP,
!  THEN SKIP THIS SPECIES.
!----------
IF(ISPC .LT. 0)THEN
  IGRP = -ISPC
  IULIM = ISPGRP(IGRP,1)+1
  DO 90 IG=2,IULIM
  IF(IS .EQ. ISPGRP(IGRP,IG))GO TO 91
90   CONTINUE
  GO TO 110
91   CONTINUE
ENDIF
!
!     ENTER TREE LOOP
!
DO 100 K=I1,I2
I=IND1(K)
!
!     LOAD HEIGHT AND CHECK HEIGHT RANGE.  IF OUT-OF-RANGE, THEN SKIP
!     TREE RECORD.
!
H=HT(I)
BRK=BRATIO(IS,DBH(I),H)
IF (H.LE.HT1 .OR. H.GT.HT2) GOTO 100
!
!     IF A RANDOM NUMBER IS GREATER THAN THE PROBABILITY OF DAMAGE,
!     THEN: THE TREE ESCAPES.
!
IF (PRB.GT. 0.99999) GOTO 30
CALL RANN(X)
IF (X.GT.PRB) GOTO 100
!
!     ELSE: THE TREE WILL BE DAMAGED.
!
30 CONTINUE
!
!     COMPUTE PROPORTION REDUCTION IN HEIGHT OR HIEGHT GROWTH.
!
PKIL=BACHLO(AVEPRB,STDPBR,RANN)
IF (PKIL.LE.0.0) GOTO 100
!
!     IF SIMULATING HTGSTOP.
!
IF (IACT.EQ.110) THEN
!
!        SET THE HEIGHT GROWTH AND BIRTH YEAR.
!
   IF (PKIL.GE.1.0) PKIL=1.0
   HTG(I)=HTG(I)*PKIL
   ABIRTH(I)=0.0
   GOTO 100
ENDIF
IF (PKIL.GT.0.8) PKIL=.8
!
!     COMPUTE ABSOLUTE NUMBER OF FEET TOP-KILLED.
!
TOPK=H*PKIL
TOPH=H-TOPK
ITRC2=IFIX(TOPH*100.+.5)
!
!     IF THE TREE IS NOT ALREADY TOPKILLED, THEN: BRANCH TO TOPKILL.
!
ITRC1=ITRUNC(I)
IF (ITRC1.LE.0) GOTO 40
!
!     IF THE NEW POINT IS BELOW THE POINT OF TRUNCATION, THEN:
!     REDUCE THE POINT OF TRUNCATION.
!
IF (ITRC1.GT.ITRC2) ITRUNC(I)=ITRC2
HT(I)=TOPH
GOTO 100
40 CONTINUE
!
!     ELSE: THE TREE HAS NOT BEEN TOP KILLED.  IF THE HEIGHT IS LESS
!     THAN 25 OR THE DBH IS LESS THAN 6, THEN:  THE TREE WILL BE
!     TEMPORARILY KILLED.
!
D=DBH(I)*BRK
IF (H.LT. 25 .OR. D.LT.6.0) GOTO 60
!
!     ELSE:
!     IF THE DIAMETER AT THE POINT OF TOPKILL IS LESS THAN A CRITICAL
!     VALUE, THEN TEMPORARILY TOPKILL THE TREE.
!     COMPUTE THE DIAMETER AT POINT OF TOPKILL USING THE BEHRE HYPER-
!     BOLOID (MONSERUD 1981 FOREST SCI. 27:253/265.)
!
AF=CFV(I)/(.00545415*D*D*H)
AF=.44244-(.99167/AF)-(1.43237*ALOG(AF))+(1.68581*SQRT(AF)) &
      -(.13611*AF*AF)
DTK=TOPK/H
DTK=(DTK/((AF*DTK)+(1-AF)))*D
IF (DTK.LT. 4.0) GOTO 60
!
!     PERMANENTLY TOPKILL THE TREE.
!
ITRUNC(I)=ITRC2
NORMHT(I)=IFIX(H*100.+.5)
!
!     SET THE MANAGEMENT CODE FOR PERMANENTLY TOPKILLED TREES
!     EQUAL TO 3
!
IMC(I)=3
60 CONTINUE
HT(I)=TOPH
!
!     IF THE CROWN RATIO HAS NOT BEEN ADJUSTED BY THE BUG MODELS
!     (THE CROWN RATIO IS NEG IF CROWN HAS BEEN ADJUSTED BY BUG MODELS),
!     THEN: REDUCE THE CROWN RATIO TO ACCOUNT FOR THE DAMAGE.
!
IOD=ICR(I)
IF (IOD.LT.0) GOTO 100
CN=(IOD/100.*H)-H+TOPH
NEW=IFIX(CN/TOPH*100.+.5)
!
!     TOPKILL WILL NOT REDUCE THE CROWN RATIO TO LESS THAN 5 PERCENT.
!
IF (NEW.LT.5) NEW=5
ICR(I)=-NEW
!
!     MAKE SURE THAT THE MANAGEMENT CODE FOR TOP DAMAGED TREES
!     IS GREATER THAN 1 (WHICH IS A LOWER SCORE THUS NORMALLY
!     INDICATING HIGHER PRIORITY FOR CUTTING).
!
IF (IMC(I).EQ.1) IMC(I)=2
100 CONTINUE
110 CONTINUE
200 CONTINUE
RETURN
END
