SUBROUTINE LB1MEM (IP1,IP2,SETIN,LENONE,ONEMEM)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     GET THE FIRST MEMBER OF SETIN FOUND BETWEEN LOCATION IP1
!     AND IP2 AND RETURN IT AS STRING ONEMEM WITH LENGTH LENONE.
!
!     PART OF THE LABEL PROCESSING COMPONENT OF THE PROGNOSIS SYSTEM
!     N.L. CROOKSTON -- INTERMOUNTAIN RESEARCH STATION -- JAN 1987
!
!     IP1   = THE STARTING POSITION FOR THE SET MEMBER
!     IP2   = THE LAST POSITION THAT WILL BE CHECKED FOR SET MEMBERSHIP
!     SETIN = THE STRING HOLDING THE FIRST SET
!     LENONE= THE LENGTH OF THE MEMBER, ZERO IF NO MEMBER EXISTS.
!     ONEMEM= THE STRING HOLDING THE FIRST MEMBER
!
INTEGER LENONE,IP1,IP2,LCOMMA,IEND
CHARACTER*250 SETIN,ONEMEM
!
!     INITIALIZE THE LENGTH OF THE MEMBER TO ZERO.
!
LENONE=0
!
!     IF THE NUMBER OF CHARACTERS BETWEEN IP1 AND IP2 IS LESS THAN
!     OR EQUAL TO ZERO, NO MEMBER EXISTS.
!
IF (IP1.LE.0 .OR. IP2.LE.0 .OR. IP2-IP1.LT.0) GOTO 100
!
!     FIND THE LOCATION OF THE FIRST COMMA BETWEEN IP1 AND IP2
!
LCOMMA=INDEX(SETIN(IP1:IP2), ',')
!
!     IF THERE IS NO COMMA, THEN THE MEMBER IS THE ENTIRE STRING.
!     IF THERE IS A COMMA, THEN THE MEMBER IS THE STRING BETWEEN IP1
!     AND THE LOCATION OF THE COMMA MINUS 1 (ASSUMING THAT THAT STRING
!     WILL ALSO BE GREATER THAN ZERO).
!
IF (LCOMMA.EQ.0) THEN
   LENONE=IP2-IP1+1
   ONEMEM=SETIN(IP1:IP2)
ELSE
   LENONE=LCOMMA-1
   IEND=LENONE+IP1-1
   IF (LENONE.GT.0) THEN
      ONEMEM=SETIN(IP1:IEND)
   ELSE
      LENONE=0
      ONEMEM=' '
   ENDIF
ENDIF
100 CONTINUE
RETURN
END
