SUBROUTINE LBGET1 (IREAD,IRECNT,RECORD,IRPS,LENMEM,MEM,KIND,KODE)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     READ RECORDS FORM IREAD AND PUT THE FIRST MEMBER IN
!     STRING MEM WITH LENGTH LENMEM.  THIS ROUTINE IS DESIGNED
!     TO CREATE TWO KINDS OF MEMBERS, AS DEFINED BELOW (SEE KIND).
!
!     PART OF THE LABEL PROCESSING COMPONENT OF THE PROGNOSIS SYSTEM
!     N.L. CROOKSTON -- INTERMOUNTAIN RESEARCH STATION -- JAN 1987
!
!     IREAD = DATA SET REFERENCE NUMBER
!     IRECNT= NUMBER OF RECORDS READ ON IREAD.
!     RECORD= THE READ RECORD.
!     IRPS  = FIRST POSITION IN RECORD WHERE THE LABEL MAY BE.
!             IF IRPS=0 ON INPUT, A RECORD IS READ.
!     LENMEM= THE LENGTH OF THE STRING HOLDING THE MEMBER
!     MEM   = THE MEMBER.
!     KIND  = 0 FOR A NORMAL LABEL (PERIODS ARE DELETED),
!             1 FOR A HARVEST POLICY LABEL (ONE PERIOD IS KEPT).
!     KODE  = 0 PROCESSING ENDED WITHOUT ERROR.
!             1 STRING MEM IS OVER FULL.
!             2 END-OF-DATA HAS OCCURRED IN IREAD.
!
CHARACTER*250 MEM
CHARACTER*(*) RECORD
LOGICAL LBKADD,LPERD,LPDONE
INTEGER KODE,KIND,LENMEM,IRPS,IRECNT,IREAD,MXLEN,I,ISTLNB
!
!     INITIALIZE KODE AND MXLEN
!
KODE=0
IF (KIND.EQ.0) THEN
   MXLEN=250
ELSE
   MXLEN=40
ENDIF
!
!     INITIALIZE LENMEM AND THE MEMBER STRING.
!
LENMEM=0
LBKADD=.FALSE.
LPERD =.FALSE.
LPDONE=.TRUE.
MEM=' '
!
!     IF THE POSTION OF THE RECORD IS ZERO, THEN READ A RECORD.
!
10 CONTINUE
IF (IRPS.EQ.0) THEN
   READ (IREAD,'(A)',END=200) RECORD
   IRECNT=IRECNT+1
ENDIF
!
!     LOOP THROUGH THE INPUT STRING AND EXTRACT THE FIRST MEMBER.
!
20 CONTINUE
IRPS=IRPS+1
!
!     IF THE END OF THE RECORD IS REACHED, THE END OF THE MEMBER
!     MUST HAVE BEEN REACHED BY DEFINITION.
!
IF (IRPS.GT.LEN(RECORD)) GOTO 300
!
!     IF THE CHARACTER IS AN AMPERSAND ('&'), THEN READ ANOTHER
!     RECORD.
!
IF (RECORD(IRPS:IRPS).EQ.'&') THEN
   IRPS=0
   GOTO 10
ENDIF
!
!     IF THE LENGTH OF THE MEMBER IS ZERO, THEN SKIP ALL BLANKS,
!     COMMAS, AND PERIODS.
!
IF (LENMEM.EQ.0) THEN
   IF (RECORD(IRPS:IRPS).EQ.' ') GOTO 20
   IF (RECORD(IRPS:IRPS).EQ.',') GOTO 20
   IF (RECORD(IRPS:IRPS).EQ.'.') GOTO 20
ENDIF
!
!     WHEN THE LENGTH IS GREATER THAN ZERO, A COMMA INDICATES THE END
!     OF THE MEMBER.
!
IF (RECORD(IRPS:IRPS).EQ.',') GOTO 300
!
!     IF THE CHARACTER IS A BLANK, SET A FLAG INDICATING THAT A BLANK
!     SHOULD BE ADDED TO THE MEMBER BEFORE ANOTHER NON-BLANK CHAR.
!
IF (RECORD(IRPS:IRPS).EQ.' ') THEN
   LBKADD=.TRUE.
   GOTO 20
ENDIF
!
!     IF THE CHAR. IS A PERIOD, THEN PROCESS ACCORDING TO VALUE OF
!     KIND. (0=NORMAL,1=HARVEST).
!
IF (RECORD(IRPS:IRPS).EQ.'.') THEN
   IF (KIND.EQ.0) GOTO 20
   IF (LPERD) GOTO 20
   LPERD=.TRUE.
   LPDONE=.FALSE.
   GOTO 20
ENDIF
!
!     ADD THE CHARACTER TO THE STRING.
!     IF A KIND IS 1 AND A PERIOD IS NEEDED, THEN THERE MUST BE 3
!     CHARS AVAILABLE.
!     IF A BLANK IS NEEDED, THEN  THERE MUST BE TWO CHARS AVAILABLE,
!     IF A BLANK NOR A PERIOD IS NEEDED, THEN ONE CHAR IS NEEDED.
!
IF (LPERD .AND. .NOT.LPDONE) THEN
   LPDONE=.TRUE.
   LBKADD=.FALSE.
   IF (LENMEM+3.LE.MXLEN) THEN
      LENMEM=LENMEM+1
      MEM(LENMEM:LENMEM+1)='. '
      LENMEM=LENMEM+2
      MEM(LENMEM:LENMEM)=RECORD(IRPS:IRPS)
      GOTO 20
   ELSE
      KODE=1
      GOTO 310
   ENDIF
ENDIF
IF (LBKADD) THEN
   IF (LENMEM+2.LE.MXLEN) THEN
      LENMEM=LENMEM+1
      MEM(LENMEM:LENMEM)=' '
      LENMEM=LENMEM+1
      MEM(LENMEM:LENMEM)=RECORD(IRPS:IRPS)
      LBKADD=.FALSE.
   ELSE
      KODE=1
      GOTO 310
   ENDIF
ELSE
   IF (LENMEM+1.LE.MXLEN) THEN
      LENMEM=LENMEM+1
      MEM(LENMEM:LENMEM)=RECORD(IRPS:IRPS)
   ELSE
      KODE=1
      GOTO 310
   ENDIF
ENDIF
!
!     GET THE NEXT CHARACTER.
!
GOTO 20
200 CONTINUE
KODE=2
300 CONTINUE
RETURN
!
!     STRING MEM IS OVER FULL. DROP RECORDS AS NECESSARY TO GET PAST
!     ALL OF THE REMAINING RECORDS THAT DEFINE THE LABEL.
!
310 CONTINUE
I=ISTLNB(RECORD)
IF (I.GT.0) THEN
   IF (RECORD(I:I).EQ.'&') THEN
      READ (IREAD,'(A)',END=200) RECORD
      IRECNT=IRECNT+1
      GOTO 310
   ENDIF
ENDIF
RETURN
END
