SUBROUTINE LBSPLR (KEYWRD,JOSTND,IREAD,IRECNT,RECORD,KODE,LKECHO)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     READ A STAND POLICY LABEL FROM IREAD.
!
!     PART OF THE LABEL PROCESSING COMPONENT OF THE PROGNOSIS SYSTEM
!     N.L. CROOKSTON -- INTERMOUNTAIN RESEARCH STATION -- JAN 1987
!
!     KEYWRD= KEYWORD STRING.
!     JOSTND= PRINT MESSAGE FILE.
!     IREAD = READER FILE
!     IRECNT= NUMBER OF RECORDS READ ON IRECNT.
!     RECORD= INPUT RECORD
!     KODE  = 0: OK, 1: END-OF-DATA FOUND ON IREAD.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'OPCOM.f90'
!
!
!OMMONS
!
!
CHARACTER*8 KEYWRD
CHARACTER*(*) RECORD
LOGICAL LKECHO
INTEGER KODE,IRECNT,IREAD,JOSTND,I1,I2
!
!     READ THE STAND LABEL SET
!
CALL LBSTRD (IREAD,LENSLS,SLSET,IRECNT,RECORD,KODE,WKSTR1,WKSTR2)
IF (KODE.GT.1) THEN
   KODE=1
   GOTO 40
ENDIF
!
!     SIGNAL THAT LABEL PROCESSING HAS BEEN ACTIVATED.
!
LBSETS=.TRUE.
!
!     ECHO THE KEYWORD AND THE SLS.
!
IF(LKECHO)WRITE(JOSTND,10) KEYWRD
10 FORMAT (/A8,'   STAND POLICY LABEL SET:')
I1=1
I2=100
20 CONTINUE
IF (I2.GT.LENSLS) I2=LENSLS
IF(LKECHO)WRITE(JOSTND,'(T12,A)') SLSET(I1:I2)
IF (I2.LT.LENSLS) THEN
   I1=I2+1
   I2=I2+100
   GOTO 20
ENDIF
IF (KODE.EQ.1) THEN
   KODE=0
   WRITE (JOSTND,30)
30    FORMAT (/'********   WARNING: THIS LABEL SET IS SHORTER ', &
              'THAN THE ONE YOU SPECIFIED.')
   CALL RCDSET (1,.TRUE.)
ENDIF
40 CONTINUE
RETURN
END





