SUBROUTINE LBSPLW (JOSTND)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     WRITE THE STAND POLICY LABEL SET ON DATA SET JOSTND
!
!     PART OF THE LABEL PROCESSING COMPONENT OF THE PROGNOSIS SYSTEM
!     N.L. CROOKSTON -- INTERMOUNTAIN RESEARCH STATION -- JAN 1987
!
!     JOSTND= PRINT MESSAGE FILE.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'OPCOM.f90'
!
!
!OMMONS
!
INTEGER JOSTND,I1,I2
!
!     IF LABEL PROCESSING HAS NOT BEEN ACTIVIATED, BRANCH TO EXIT.
!
IF (.NOT.LBSETS) GOTO 40
!
!     IF THE STAND POLICY LABEL IS UNSET (LENSLS=-1) THEN: BRANCH
!     TO EXIT.
!
IF (LENSLS.EQ.-1) GOTO 40
!
!     WRITE THE STAND LABEL SET.
!
I1=1
I2=100
20 CONTINUE
IF (I2.GT.LENSLS) I2=LENSLS
IF (I1.EQ.1) THEN
   WRITE (JOSTND,'(/''STAND POLICIES:'',T19,A)') SLSET(I1:I2)
ELSE
   WRITE (JOSTND,'(T19,A)') SLSET(I1:I2)
ENDIF
IF (I2.LT.LENSLS) THEN
   I1=I2+1
   I2=I2+100
   GOTO 20
ENDIF
40 CONTINUE
RETURN
END
