SUBROUTINE LBTRIM (MAE,MAELNK)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     CALLED FROM PPEVMI, DELETE ACTIVITY GROUPS THAT MIGHT CREATE
!     BRANCHES IF THE INTERSECTION OF THE STAND LABEL SET AND THE
!     ACTIVITY GROUP LABEL SET IS NULL.
!
!     N.L. CROOKSTON--FORESTRY SCIENCES LAB, MOSCOW, ID--JAN 1987.
!
!     MAE   = LENGTH OF MAELNK.
!     MAELNK= LIST OF ACTIVITY GROUPS THAT ARE ASSOCIATED WITH
!             AN EVENT THAT HAS MORE THAN ONE ACTIVITY GROUP
!             ASSOCIATED WITH IT.
!             (1,.)= POINTS TO THE ENTRY IN IEVACT, AGLSET, & LENAGL
!             (2,.)= POINTS TO THE ENTRY IN IEVNTS
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'OPCOM.f90'
!
!
!OMMONS
!
INTEGER MAELNK(2,50),MAE,IDEL,I,J,KODE,LEN
!
!     IF THE LENGTH OF MAELNK IS ZERO, BRANCH TO RETURN
!
IF (MAE.LE.0) GOTO 100
!
!     DO THROUGH THE ACTIVITY GROUPS, AND FLAG MEMBERS OF MEMLNK
!     FOR ACTIVITY GROUPS THAT SHOULD BE DROPPED.
!
IDEL=0
DO 10 I=1,MAE
!
J=MAELNK(1,I)
!
!     IF THE LENGTH OF THE AGLSET IS -1, THEN KEEP THE ACTIVIY GROUP
!
IF (LENAGL(J).GE.0) THEN
   CALL LBINTR (LENSLS,SLSET,LENAGL(J), &
                   AGLSET(J),LEN,WKSTR1,KODE)
   IF (LEN.EQ.0) THEN
      MAELNK(1,I)=0
      IDEL=IDEL+1
   ENDIF
ENDIF
10 CONTINUE
!
!     IF SOME ACTIVITY GROUPS ARE DELETED, THEN
!
IF (IDEL.GT.0) THEN
!
!        IF ALL OF THE ACTIVIY GROUPS HAVE BEEN DELETED, THEN:
!
   IF (IDEL.EQ.MAE) THEN
      MAE=0
   ELSE
!
!           ELSE SOME HAVE BEEN DELETED, COMPRESS THE LIST MAELNK.
!
      LEN=0
      DO 20 I=1,MAE
      IF (MAELNK(1,I).LE.0) GOTO 20
      LEN=LEN+1
      MAELNK(1,LEN)=MAELNK(1,I)
      MAELNK(2,LEN)=MAELNK(2,I)
20       CONTINUE
      MAE=LEN
   ENDIF
ENDIF
!
100 CONTINUE
RETURN
END
