SUBROUTINE LBUNIN (LEN1,SET1,LEN2,SET2,LNUNIN,UNION,KODE)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     SET UNION OPERATION
!
!     PART OF THE LABEL PROCESSING COMPONENT OF THE PROGNOSIS SYSTEM
!     N.L. CROOKSTON -- INTERMOUNTAIN RESEARCH STATION -- JAN 1987
!
!     LEN1  = LENGTH OF THE DEFINED PART OF THE STRING SET1 IS IN
!     SET1  = C*250 STRING CONTAINING THE FIRST SET
!     LEN2  = LENGTH OF SECOND STRING
!     SET2  = C*250 STRING CONTAINING THE SECOND SET
!     LNUNIN= THE LENGTH OF THE UNION SET STRING
!     UNION = C*250 SET CONTAINING THE UNION
!     KODE  = RETURN CODES: 0= OK, 1=UNION IS OVER 250 CHARS
!             (THE ROUTINE CREATES AS MUCH OF A UNION IS POSSIBLE
!             WITHOUT CREATING A PARTIAL LABEL).
!
CHARACTER*250 SET1,SET2,UNION,WRKS1,WRKS2
LOGICAL LBMEMR
INTEGER KODE,LNUNIN,LEN1,LEN2,IP,LENWRK
!
!     INITIALIZE THE RETURN CODE TO ZERO AND THE UNION TO ZERO LENGTH.
!
KODE=0
LNUNIN=0
UNION=' '
!
!     IF EITHER OF THE SETS HAVE ZERO LENGTH OR IF THEY ARE UNDEFINED,
!     THE UNION IS THE OTHER SET (UNLESS IT, TOO, IS UNDEFINED OR HAS
!     ZERO LENGTH).
!
IF (LEN1.LE.0) THEN
   IF (LEN2.GT.0) THEN
      LNUNIN=LEN2
      UNION=SET2
   ENDIF
   GOTO 20
ENDIF
IF (LEN2.LE.0) THEN
   IF (LEN1.GT.0) THEN
      LNUNIN=LEN1
      UNION=SET1
   ENDIF
   GOTO 20
ENDIF
!
!     BOTH SETS HAVE GREATER THAN ZERO LENGTH...PROCEED WITH THE
!     UNION.  START WITH THE FIRST SET AS THE UNION.
!
UNION=SET1
LNUNIN=LEN1
!
!     CONCATINATE MEMBERS OF THE SECOND SET THAT ARE NOT ALREADY
!     MEMBERS OF THE UNION.
!
!     LOOP THRU ALL OF THE MEMBERS OF THE SECOND SET.
!
IP=1
10 CONTINUE
!
!     IF IP IS EQUAL TO THE LENGTH OF THE SECOND SET, END THE LOOP.
!
IF (IP.GT.LEN2) GOTO 20
!
!     LET WRKS1 BE THE FIRST MEMBER OF SET2 BETWEEN LOCATION IP
!     AND THE END OF THE STRING HOLDING SET2.
!
CALL LB1MEM (IP,LEN2,SET2,LENWRK,WRKS1)
!
!     FIND OUT IF WRKS1 IS IN THE UNION.  IF IT IS NOT, THEN ADD IT
!     ONTO THE END (IF THERE IS ROOM).
!
IF (.NOT.LBMEMR(LENWRK,WRKS1,LNUNIN,UNION)) THEN
   IF (LNUNIN+LENWRK+2.LE.250) THEN
      WRKS2 = UNION(1:LNUNIN) // ', ' // WRKS1(1:LENWRK)
      LNUNIN = LNUNIN+LENWRK+2
      UNION = WRKS2
   ELSE
      KODE = 1
   ENDIF
ENDIF
!
!     SET THE IP TO THE LAST CHARACTER OF THE CURRENT MEMBER PLUS 2
!     (ONE FOR THE COMMA AND ANOTHER FOR THE BLANK THAT PRECEDES EACH
!     OF THE MEMBERS PAST THE FIRST ONE).
!
IP=IP+LENWRK+2
!
!     BRANCH BACK TO PROCESS THE NEXT LABEL.
!
GOTO 10
20 CONTINUE
RETURN
END
