SUBROUTINE MEANSD (A,N,ABAR,VAR,STD)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     COMPUTE THE MEAN AND STANDARD DEVIATION OF A REAL VECTOR.
!
!     PARAMETERS:
!
!     A: REAL VECTOR TO COMPUTE MEAN AND STANDARD DEVIATION OVER.
!     N: LENGTH OF A.
!     ABAR: COMPUTED MEAN OF A.
!     VAR: VARIANCE OF A.
!     STD: COMPUTED STANDARD DEVIATION OF A.
!
REAL A(N)
INTEGER I,N
DOUBLE PRECISION APX, ABAR, VAR, STD, SUM, SUMSQ, DN, Z
!
DN=N
APX=0D0
DO 30 I=1,N
APX=APX+A(I)
30 CONTINUE
APX=APX/DN
SUM=0D0
SUMSQ=0D0
DO 40 I=1,N
Z=A(I)-APX
SUM=SUM+Z
SUMSQ=SUMSQ+Z*Z
40 CONTINUE
ABAR=SUM/DN
VAR=(SUMSQ-(SUM*ABAR))/(DN-1)
STD=DSQRT(VAR)
ABAR=ABAR+APX
RETURN
END
