SUBROUTINE MSBMRT(EFFMRT,T2KILL,DLO,DHI,MFLAG,DEBUG)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!  THIS SUBROUTINE IS USED TO SIMULATE BREAKUP OF OVERMATURE STANDS
!  OF TREES BY INFLICTING ADDITIONAL MORTALITY IN THE SPECIFIED
!  DIAMETER RANGE.  MOVING ACROSS ALL TREE RECORDS IN THE DBH RANGE,
!  EITHER FROM ABOVE, BELOW, OR THROUGHOUT THE RANGE, IT KILLS A PROPORTION
!  OF THE TREES PER ACRE REPRESENTED BY A TREE RECORD UNTIL THE TARGET
!  NUMBER OF TREES IS REACHED. THE TARGET NUMBER OF TREES IS COMPUTED
!  FROM THE ALTERNATE MORTALITY EQUATION PROVIDED BY THE USER.
!  CALLED FROM **MORTS** IF THE ALTERNATE MORTALITY LOGIC IS BEING
!  INVOKED.
!  NOTE: IF THE MORTALITY EFFICIENCY IS SET TO LOW TO ACHIEVE THE TARGET
!        MORTALITY, IT GETS RECOMPUTED IN **MORTS** FOR THIS CYCLE AND
!        PROCESSING CONTINUES.
!  NOTE: TO BE ABSOLUTELY CORRECT, THIS ROUTINE SHOULD ITERATIVELY
!        SOLVE THE NUMBER OF TREES TO KILL WITH THE QMD AND THE MORTALITY
!        EFFICIENCY. HOWEVER, SINCE INVOKING THIS LOGIC REQUIRES A RESET
!        OF THE MORTALITY TRAJECTORY NEXT CYCLE ANYWAY, IT SEEMS
!        SUFFICIENT TO JUST TAKE THIS 1 PASS APPROXIMATATION AND GO ON.
!        GED 6/10/09
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
!OMMONS
!----------
LOGICAL DEBUG
REAL T2KILL,XKILL,TEMKIL,SUMKIL,TEMP,EFFMRT,DLO,DHI,DBHEND,BARK, &
        BRATIO
INTEGER K,IJ,JJ,MFLAG
!-----------
! PRINT STARTING DEBUG IF CALLED FOR
!-----------
IF(DEBUG) WRITE(JOSTND,10)ICYC,T2KILL,EFFMRT
10 FORMAT(' ENTERING SUBROUTINE MSBMRT  CYCLE =',I5,'  TREES TO KILL &
   = ',F9.4,'  MORTALITY EFFICIENCY =',F9.4)
IF(DEBUG) WRITE(JOSTND,11)DLO,DHI,MFLAG
11 FORMAT(' ENTERING SUBROUTINE MSBMRT  LOWER DBH =',F7.3,'  UPPER DB &
   H =',F7.3,'  MORTALITY FLAG = ',I4)
IF(DEBUG)WRITE(JOSTND,15)ITRN,(WK2(JJ),JJ=1,ITRN)
15 FORMAT(' ENTERING MSBMRT ITRN,WK2= ',I10,/, &
    97(1H ,14F9.4,/))
IF(DEBUG)WRITE(JOSTND,20)ITRN,(IND(JJ),JJ=1,ITRN)
20 FORMAT(' IN MSBMRT ITRN,IND =',I6,/,86(1H ,32I4,/))
!----------
!  ENTER THE LOOP FOR SPECIES DEPENDENT VARIABLES
!  NOTE, IND() CONTAINS THE DIAMETER SORTED INDICIES; IND(1)=INDEX OF
!  THE LARGEST DIAMETER TREE; IND(ITRN)=INDEX OF SMALLEST DIAMETER TREE
!----------
TEMP=0.
TEMKIL=0.
SUMKIL=0.
IF(MFLAG.EQ.1 .OR. MFLAG.EQ.3)THEN
  DO K=1,ITRN
  IJ=IND(K)
  BARK=BRATIO(ISP(IJ),DBH(IJ),HT(IJ))
  DBHEND=DBH(IJ)+(DG(IJ)/BARK)*(FINT/10.0)
  IF(DBHEND.GE.DLO .AND. DBHEND.LT.DHI)THEN
    XKILL=(PROB(IJ)-WK2(IJ))*EFFMRT
    TEMP=PROB(IJ)-WK2(IJ)-XKILL
    IF(TEMP .LT. 0.00001)XKILL=PROB(IJ)-WK2(IJ)
    IF(XKILL .LT. 0.)XKILL=0.
    TEMKIL=SUMKIL+XKILL
    IF(TEMKIL .GT. T2KILL)XKILL=T2KILL-SUMKIL
    SUMKIL=SUMKIL+XKILL
    WK2(IJ)=WK2(IJ)+XKILL
    IF(DEBUG)WRITE(JOSTND,30)IJ,DBHEND,PROB(IJ),WK2(IJ),XKILL, &
       SUMKIL,T2KILL,EFFMRT
30     FORMAT(' IN MSBMRT13 IJ,DBH,PROB,WK2,XKILL,SUMKIL,T2KILL,', &
       'EFFMRT= ',/,1H ,I5,7F12.5)
    IF(SUMKIL .GE. T2KILL)GO TO 50
  ENDIF
  ENDDO
ELSE
  DO K=ITRN,1,-1
  IJ=IND(K)
  BARK=BRATIO(ISP(IJ),DBH(IJ),HT(IJ))
  DBHEND=DBH(IJ)+(DG(IJ)/BARK)*(FINT/10.0)
  IF(DBHEND.GE.DLO .AND. DBHEND.LT.DHI)THEN
    XKILL=(PROB(IJ)-WK2(IJ))*EFFMRT
    TEMP=PROB(IJ)-WK2(IJ)-XKILL
    IF(TEMP .LT. 0.00001)XKILL=PROB(IJ)-WK2(IJ)
    IF(XKILL .LT. 0.)XKILL=0.
    TEMKIL=SUMKIL+XKILL
    IF(TEMKIL .GT. T2KILL)XKILL=T2KILL-SUMKIL
    SUMKIL=SUMKIL+XKILL
    WK2(IJ)=WK2(IJ)+XKILL
    IF(DEBUG)WRITE(JOSTND,40)IJ,DBHEND,PROB(IJ),WK2(IJ),XKILL, &
       SUMKIL,T2KILL,EFFMRT
40     FORMAT(' IN MSBMRT2 IJ,DBH,PROB,WK2,XKILL,SUMKIL,T2KILL,', &
       'EFFMRT= ',/,1H ,I5,7F12.5)
    IF(SUMKIL .GE. T2KILL)GO TO 50
  ENDIF
  ENDDO
ENDIF
!
50 CONTINUE
IF(DEBUG)WRITE(JOSTND,9010)ITRN,(WK2(JJ),JJ=1,ITRN)
9010 FORMAT(' LEAVING MSBMRT 9010 FORMAT ITRN,WK2= ',I10,/, &
    97(1H ,14F9.4,/))
IF(DEBUG)WRITE(JOSTND,90)ICYC
90 FORMAT(' LEAVING SUBROUTINE MSBMRT  CYCLE =',I5)
!
RETURN
END
