SUBROUTINE MULTS (KIND,IDT,XMULT)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
!OMMONS
!
!     GETS THE MULTIPLIERS - NL CROOKSTON - JAN 1981 - MOSCOW.
!
!     KIND  = THE TYPE OF MULTIPLIER, WHERE:
!             1 IS BAIMULT    (FROM **DGDRIV** )
!             2 IS HTGMULT    (FROM **HTGF**   )
!             3 IS REGHMULT   (FROM **REGENT** )
!             4 IS MORTMULT
!             5 IS ESTBMULT
!             6 IS REGDMULT   (FROM **REGENT** )
!             7 IS MANAGED    (FROM **DGDRIV** )
!
!     IDT   = THE CURRENT YEAR=IY(ICYC).
!     XMULT = SPECIES SPECIFIC MULTIPLIERS.
!
REAL XMULT(MAXSP)
INTEGER MYACTS(7)
REAL PRM(2)
INTEGER IDT,KIND,NTODO,I,NP,IACTK,IDATE,ISP,IGRP,IULIM,IG,ISPG
DATA MYACTS/91,92,93,94,95,96,82/
!
!     IF KIND IS OUT-OF-RANGE; RETURN
!
IF (KIND.GT.7 .OR. KIND.LT.1) RETURN
!
!     FIND OUT IF THERE ARE ANY MULTIPLIERS.
!
CALL OPFIND (1,MYACTS(KIND),NTODO)
!
!     IF THERE ARE NONE;
!     THEN: RETURN
!
IF (NTODO .EQ. 0) RETURN
!
!     ELSE: GET THE MULTIPLIERS AND LOAD THEM INTO THE XMULT ARRAY.
!
DO 50 I=1,NTODO
CALL OPGET(I,2,IDATE,IACTK,NP,PRM)
IF (IACTK.LT.0) GOTO 50
!
!     SET THE STATUS OF THE OPTION AS ACCOMPLISHED IN THE YEAR 'IDT'
!
CALL OPDONE(I,IDT)
!----------
!  PROCESS MANAGED KEYWORD
!----------
IF(KIND .EQ. 7) THEN
  XMULT(1)=PRM(1)
  GO TO 50
ENDIF
!
!     IF SPECIES CODE IS:
!        < 0 THEN IT APPLIES TO SPECIES IN A GROUP
!        = 0 THEN IT APPLIES TO ALL SPECIES
!        > 0 THEN IT APPLIES TO JUST THIS SPECIES
!
ISP=IFIX(PRM(1))
IF(ISP .LT. 0)THEN
  IGRP = -ISP
  IULIM = ISPGRP(IGRP,1)+1
  DO 30 IG=2,IULIM
  ISPG = ISPGRP(IGRP,IG)
  XMULT(ISPG)=PRM(2)
30   CONTINUE
ELSEIF(ISP.EQ.0)THEN
  DO 40 ISP=1,MAXSP
  XMULT(ISP)=PRM(2)
40   CONTINUE
ELSE
  XMULT(ISP)=PRM(2)
ENDIF
50 CONTINUE
RETURN
END
