SUBROUTINE NOTRE
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!  THIS SUBROUTINE CALCULATES THE NUMBER OF TREES PER ACRE EACH
!  TREE RECORD REPRESENTS BASED ON THE INPUT SAMPLING DESIGN
!  FACTORS.  ON INPUT, THE TREE LIST IS SEPARATED INTO 2 GROUPS
!  DEPENDING ON WHETHER RECORDS ARE PROJECTABLE OR NOT. THE
!  FIRST IREC1 RECORDS IN THE LIST ARE PROJECTABLE. THE RECORDS
!  FROM (MAXTP1-IREC2) TO MAXTRE ARE NON-PROJECTABLE.
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
!OMMONS
!----------
!       VP -- VARIABLE PLOT EXPANSION FACTOR.  IF BAF IS NEGATIVE,
!             VP IS SET TO ZERO, AND BAF IS ASSUMED TO BE THE
!             INVERSE OF THE AREA FOR THE FIXED PLOT ON WHICH LARGE
!             TREES WERE SAMPLED.
!       FP -- FIXED PLOT EXPANSION FACTOR FOR SMALL TREE SAMPLE.
!       FP2-- FIXED PLOT EXPANSION FACTOR FOR LARGE TREE SAMPLE, SET
!             TO ZERO WHEN BAF IS POSITIVE.
!----------
!
REAL FP,FP2,VP,P,D
INTEGER I1,I2,I
!
IF ((ITRN.LE.0).AND.(IREC2.GE.MAXTP1)) RETURN
FP = FPA/PI
FP2=0.0
IF(TFPA.GT.0.0) FP=1.0/TFPA
VP = BAF*183.3465/PI
IF(BAF.GT.0.0) GO TO 5
VP=0.0
FP2=-BAF/PI
5 CONTINUE
I1= 1
I2= IREC1
!----------
!  FIRST, PROCESS THE PROJECTABLE TREE RECORDS.
!----------
10 CONTINUE
DO 40 I= I1, I2
P=PROB(I)
D=DBH(I)
IF (P .LE. 0.0) P=1.0
IF ( D .LT. BRK ) GO TO 20
P = P*VP/(D*D) + P*FP2
GO TO 30
20 P = P*FP
30 IF ( P .LE. 0.0 ) P = 9.E-25
!----------
!  ASSIGN PROB; ADJUST FOR NON-STOCKABLE POINTS.
!----------
PROB(I)=P*GROSPC
!
!        IT WAS FOUND THAT INDIVIDUAL TREE RECORD TPA VALUES GREATER
!        THAN 1000 CAN CAUSE MATHEMATICAL ERROR IN CALCULATION OF
!        FFE POTENTIAL FLAME LENGTH CALCULATION SPECIFICALLY (FMPOFL.F).
!
IF (P .GT. 1000.0) THEN
   CALL ERRGRO (.TRUE.,40)
   WRITE(JOSTND,32) IDTREE(I),I,ISP(I),DBH(I),PROB(I)
32    FORMAT(/, &
      '********   FVS40 WARNING:  TREE_ID=',I6,' TREE INDEX=', &
      I4,' SPECIES=',I3,' DIAMETER=',F5.1,' TPA=',F8.2)
ENDIF

!----------
!   CALL WESTERN ROOT DISEASE MODEL VER. 3.0 SUBROUTINE TO ASSIGN TPA
!   VALUES TO WESTERN ROOT DISEASE PROB VARIABLES
!----------
CALL RDPRIN (I)
!----------
!   CALL TO FIRE AND FUEL EFFECTS MODEL IS DONE IN **CRATET**,
!   SINCE SNAG HEIGHT DUBBING MAY BE REQUIRED
!----------
40 CONTINUE
IF( I1 .NE. 1 ) GO TO 60
IF( IREC2 .EQ. MAXTP1 ) GO TO  60
!----------
!  RETURN TO STATEMENT 10 TO PROCESS THE NON-PROJECTABLE RECORDS
!  AT THE END OF THE LIST.
!----------
I1= IREC2
I2= MAXTRE
!----------
!  MULTIPLY THE PROB OF MORTALITY TREES BY THE RATIO OF THE GROWTH
!  MEASUREMENT PERIOD LENGTH TO THE MORTALITY OBSERVATION PERIOD
!
!  THE INFLATION OF PROB FOR DEAD TREES IS DONE TO FACILITATE
!  CALIBRATION. DURING CALIBRATION THE RECENT DEAD TREES NEED
!  TO BE ADDED BACK INTO THE STAND TO GET THE CORRECT BACKDATED
!  DENSITY. THE CORRECT ADJUSTMENT IS THE CYCLE LENGTH DIVIDED
!  BY THE LENGTH OF THE MORTALITY OBSERVATION PERIOD. IT IS ASSUMED
!  THAT THE SAME PROPORTION OF TREES WILL DIE/YEAR IN THE CYCLE, AS
!  DIED/YEAR IN THE MORTALITY OBSERVATION PERIOD. THE PROB
!  VALUES ARE INFLATED FOR ALL DEAD TREES, BUT ONLY THE RECENT
!  DEAD TREES ARE USED FOR CALCULATING BACKDATED DENSITY. TREES
!  CLASSIFIED AS "OLDER DEAD" ARE IGNORED IN THIS PROCESS. HOWEVER,
!  WHEN IT COMES TO REPRESENTING THE TREES/ACRE FOR A RECORD IN THE
!  TREELIST, OR WHEN NEEDED IN OTHER CALCULATIONS, THIS INFLATION
!  SHOULD NOT BE DONE.  ANY TIME THESE RECORDS ARE USED FOR ANOTHER
!  PURPOSE DURING "CYCLE 0" PROCESING, THIS SCALING NEEDS TO BE
!  "UNDONE" (SEE CALL TO **FMSSEE** IN **CRATET**, AND PROB
!  DEFLATING IN **PRTRLS**, TO SEE HOW THIS IS DONE).
!----------
VP=VP*(FINT/FINTM)
FP=FP*(FINT/FINTM)
FP2=FP2*(FINT/FINTM)
GO TO 10
60 CONTINUE
RETURN
END
