SUBROUTINE OPBISR(N,IA,IF,IP)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     OPTION PROCESSING ROUTINE - NL CROOKSTON - JAN 1981 - MOSCOW
!
!     BINARY SEARCH ROUTINE:  FINDS THE SUBSCRIPT LOCATION OF IF IN
!     ARRAY IA.
!
!     N  = THE LENGTH OF IA.
!     IA = A LIST OF INTEGERS SORTED INTO ASCENDING ORDER
!     IF = AN INTEGER WHICH YOU WISH FIND IN IA.
!     IP = THE POSITION IN IA WHERE IF WAS FOUND; OR
!          0 WHEN IF IS NOT A MEMBER OF IA.
!
INTEGER IA(*),IP,IF,N,IMID,ITOP,IBOT
!
IMID=1
IF (IF.LE.IA(1)) GOTO 40
IMID=N
IF (IF.GE.IA(N)) GOTO 40
ITOP=1
IBOT=N
20 CONTINUE
IMID=(IBOT+ITOP)/2
IF (IF.GE.IA(IMID)) GOTO 30
IBOT=IMID-1
IF (IF.GT.IA(IBOT)) GOTO 40
GOTO 20
30 CONTINUE
ITOP=IMID+1
IF (IF.LT.IA(ITOP)) GOTO 40
GOTO 20
40 CONTINUE
IP=IMID
IF (IF.NE.IA(IP)) IP=0
RETURN
END
