SUBROUTINE OPCACT (KODE,CSTR)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!     OPTION PROCESSING ROUTINE - NL CROOKSTON - JAN 2003 - MOSCOW
!
!     OPCACT IS USED TO STORE A STRING ASSOCIATED WITH THE MORE RECENTLY
!     STORED ACTIVITIY.  THIS ROUTINE MUST BE CALLED AFTER THE CALL THAT
!     ADDS AN ACTIVITY TO THE ACTIVITY LIST.  THE STRING IS ASSOCITED WITH
!     THE MOST RECENTLY ADDED ACTIVITY. ONLY CALL THIS ROUTINE IF THE
!     MOST RECENTLY ADDED ACTIVITY WAS SUCCESSFULLY ADDED.
!
!     KODE = THE RETURN CODE WHERE:
!            0   ALL WENT OK,
!            1   STRING COULD NOT BE ADDED BECAUSE STORAGE IS FULL.
!                A WARNING MESSAGE IS ISSUED VIA ERRGRO.
!     CSTR = THE STRING THAT IS BEING ADDED.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'OPCOM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
!OMMONS
!
LOGICAL LDEB
CHARACTER*(*) CSTR
INTEGER KODE,NCHAR,I
!
!     SEE IF WE NEED WRITE DEBUG.
!
CALL DBCHK (LDEB,'OPCACT',6,ICYC)
IF (LDEB) WRITE (JOSTND,10) ICACT,MXCACT,LOPEVN,IMPL,IEPT, &
      TRIM(CSTR)
10 FORMAT (' IN OPCACT: ICACT=',I4,' MXCACT=',I6,' LOPEVN=',L2, &
           ' IMPL=',I4,' IEPT=',I5,' CSTR=',A)
!
!     MAKE SURE THERE IS ROOM IN THE ACTIVITY STORAGE AREAS
!     TO STORE THE ACTIVITY AND ITS PARAMETERS.
!
NCHAR=LEN_TRIM(CSTR)
IF (NCHAR+ICACT.GT.MXCACT) THEN
   KODE=1
   CALL ERRGRO (.TRUE.,10)
   WRITE (JOSTND,*) 'ISSUED IN OPCACT CANNOT ADD ACTIVITY STRING'
   RETURN
ELSE
   KODE=1
!
!        SET THE POINTER TO THE MOST RECENT ACTIVITY AND LOAD THE
!        STARTING POSITION.
!
   IF (LOPEVN) THEN
      I=IEPT+1
   ELSE
      I=IMGL-1
   ENDIF
   IACT(I,5)=ICACT
!
!        STORE THE CHARACTER STRING.
!
   DO I=1,NCHAR
      CACT(ICACT)=CSTR(I:I)
      ICACT=ICACT+1
   ENDDO
   CACT(ICACT)=CHAR(0)
   ICACT=ICACT+1
ENDIF
RETURN
END
