SUBROUTINE OPCSET (ICYC)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     OPTION PROCESSING ROUTINE - NL CROOKSTON - JAN 1981 - MOSCOW
!
!     SETS UP IOPCYC AS AN WITHIN CYCLE SORT INTO ASSENDING ORDER
!     OF ACTIVITY NUMBER.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'OPCOM.f90'
!
!
!OMMONS
!
INTEGER ICYC,I
!
!     IF IMG1 IS ZERO (THERE ARE NO ACTIVITIES FOR THE CYCLE);
!     THEN: RETURN
!
IMG1=IMGPTS(ICYC,1)
IF (IMG1 .EQ. 0) RETURN
IMG2=IMGPTS(ICYC,2)
!
!     COPY THIS CYCLE'S PORTION OF THE ALL CYCLE SORT ARRAY INTO
!     THE WITHIN CYCLE SORT ARRAY
!
DO 10 I=IMG1,IMG2
IOPCYC(I)=IOPSRT(I)
10 CONTINUE
!
!     SORT IOPCYC ON ASSENDING ACTIVITY NUMBERS.
!
CALL IAPSRT(IMG2-IMG1+1,IACT,IOPCYC(IMG1),.FALSE.)
RETURN
END
