SUBROUTINE OPMERG (NMYA,MYACTS,NTODO)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     OPTION PROCESSING ROUTINE - NL CROOKSTON - JAN 1981 - MOSCOW
!
!     OPMERG TAKES A LIST OF POSSIBLE ACTIVITIES (MYACTS) AND
!     FORMS A LIST OF POINTERS TO ACTIVITIES TO DO (IPTODO) WHICH
!     ARE BOTH WITHIN THE CURRENT CYCLE AND WITHIN 'MYACTS'.
!
INTEGER MYACTS(NMYA),NTODO,NMYA,IPA,IMYA,MY,I,IA
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'OPCOM.f90'
!
!
!OMMONS
!
!     SET THE NUMBER OF ACTIVITIES TO DO EQUAL TO ZERO.
!
NTODO=0
!
!     IF 1. THERE ARE NO ACTIVITIES FOR THIS CYCLE, OR
!        2. YOU HAVE INDECATED YOU HAVE NO ACTIVITIES (NMYA=0), OR
!        3. THE LOWEST VALUE OF YOUR ACTIVITIES IS GREATER THAN THE
!           LARGEST ACTIVITY SCHEDULED FOR THIS CYCLE, OR
!        4. THE HIGHEST VALUE OF YOUR ACTIVITIES IS LESS THAN THE
!           LOWEST ACTIVITY SCHEDULED FOR THIS CYCLE.
!
!     THEN: RETURN
!
IF (IMG1 .EQ. 0) RETURN
IF (NMYA .EQ. 0) RETURN
IPA=IOPCYC(IMG2)
IF (MYACTS(1) .GT. IACT(IPA,1)) RETURN
IPA=IOPCYC(IMG1)
IF (MYACTS(NMYA) .LT. IACT(IPA,1)) RETURN
!
!     ELSE: PREFORM THE MERGE
!
!     LOAD THE FIRST "MY" ACTIVITY
!
IMYA=1
MY=MYACTS(1)
!
!     DO FOR ALL ACTIVITIES IN THIS CYCLE IN ORDER OF ASSENDING
!     MAGNITUDE OF ACTIVITY CODES (PLACED IN ORDER BY OPCSET).
!
DO 30 I=IMG1,IMG2
IPA=IOPCYC(I)
!
!     IF THIS ACTIVITY IS MARKED ACCOMPLISHED OR DELETED;
!     THEN SKIP IT AND GO ON.
!
IF (IACT(IPA,4) .NE. 0) GOTO 30
IA=IACT(IPA,1)
!
!     RETEST-MY-ACTIVITY:
!
10 CONTINUE
!
!     IF THE "MY" ACTIVITY IS GREATER THAN THE SCHEDULED ACTIVITY;
!     THEN: GO ON TO NEXT SCHEDULED ACTIVITY.
!
IF (MY.GT.IA) GOTO 30
!
!     IF THE "MY" ACTIVITY IS LESS THAN THE SCHEDULED ACTIVITY;
!
IF (MY .EQ. IA) GOTO 20
!
!     THEN: INCREMENT IMYA
!
IMYA=IMYA+1
!
!     IF ALL "MY" ACTIVITIES HAVE BEEN SCANED;
!     THEN: SEARCH IS COMPETE
!
IF (IMYA .GT. NMYA) GOTO 40
!
!     ELSE: RELOAD MY AND RETEST MY.
!
MY=MYACTS(IMYA)
GOTO 10
20 CONTINUE
!
!     ELSE: THE "MY" ACTIVITY IS EQUAL TO THE SCHEDULED ACTIVITY;
!     INCREMENT NTODO, SAVE THE POINTER (IPA) IN IPTODO(NTODO)
!     AND GO ON TO THE NEXT SCHEDULED ACTIVITY.
!
NTODO=NTODO+1
IF (NTODO.GT.MXPTDO) THEN
   CALL ERRGRO (.TRUE.,10)
   WRITE (16,*) &
        'ISSUED IN OPMERG ADDING ACTIVITY EXCEEDS LIMIT'
   GOTO 40
ENDIF
IPTODO(NTODO)=IPA
30 CONTINUE
!
40 CONTINUE
!
!     MEARGE IS COMPLETE:
!     IF THERE WERE NO MATCHES (NTODO IS ZERO);
!     THEN: RETURN
!
IF (NTODO .EQ. 0) RETURN
!
!     ELSE: SORT THE POINTERS TO THE MACTCHED LIST ON THE DATE ARRAY
!
CALL OPSORT (NTODO,IDATE,ISEQ,IPTODO,.FALSE.)
RETURN
END
