SUBROUTINE OPNEW (KODE,IDT,IACTK,NPRMS,PRMS)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     OPTION PROCESSING ROUTINE - NL CROOKSTON - JAN 1981 - MOSCOW
!     MODIFIED AUG 1982 TO STORE ACTIVITIES FOR FUTURE SCHEDULING.
!
!     OPNEW IS USED TO ADD USER-SPCEIFED OPTIONS TO THE
!     ACTIVITY LIST.  IT IS DESIGNED TO BE CALLED DURING
!     THE INITIAL PROCESSING (FROM INITRE, OR A SIMILAR
!     ROUTINE) OF THE OPTIONS.  THE ARGUMENTS:
!
!     KODE = THE RETURN CODE WHERE:
!            0   ALL WENT OK,
!            1   OPTION COULD NOT BE ADDED BECAUSE OPTION ARRAYS
!                ARE FULL.  A WARNING MESSAGE IS ISSUED VIA ERRGRO.
!     IDT  = THE DATE, CYCLE, OR A ZERO (ALL CYCLES) CODE TO
!            INDECATE WHEN THE ACTIVITY IS TO BE IMPLIMENTED.
!     IACTK= THE ACTIVITY CODE.
!     NPRMS= THE NUMBER OF PARAMETERS ASSOCIATED WITH THE ACTIVITY.
!     PRMS = THE PARAMETER LIST.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'OPCOM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
!OMMONS
!
INTEGER NPRMS,IACTK,IDT,KODE,IPEND,I,J
REAL PRMS(*)
LOGICAL LMODE,LDEB
!
!     SEE IF WE NEED WRITE DEBUG.
!
CALL DBCHK (LDEB,'OPNEW',5,ICYC)
!
!     MAKE SURE THERE IS ROOM IN THE ACTIVITY STORAGE AREAS
!     TO STORE THE ACTIVITY AND ITS PARAMETERS.
!
IPEND=IMPL+NPRMS-1

IF (LDEB) THEN
  WRITE(JOSTND,*) 'OPNEW: IPEND, IMPL, NPRMS=',IPEND,IMPL,NPRMS
  WRITE(JOSTND,*) 'OPNEW: IMGL, IEPT, ITOPRM=',IMGL,IEPT,ITOPRM
ENDIF

IF (IMGL .LE. IEPT+1 .AND. IPEND .LE. ITOPRM) GOTO 10
KODE=1
I=0
CALL ERRGRO (.TRUE.,10)
GOTO 50
10 CONTINUE
KODE=0
!
!     STORE THE ACTIVITY AND THE PARAMETERS; INSURE THAT THE
!     ACTIVITY IS LISTED AS 'NOT ACCOMPLISHED'.
!     IF THE ACTIVITY IS TO BE STORED UNTIL AN EVENT OCCURS, THEN:
!     STORE THE POINTERS IN THE BOTTOM OF IACT.
!
I=IMGL
IF (LOPEVN) I=IEPT
IACT(I,1)=IACTK
IACT(I,4)=0
IACT(I,5)=0
!
!     IF THERE ARE NO PARAMETERS;
!     THEN: SET PARAMETER POINTERS TO ZERO.
!
IF (NPRMS .GT. 0) GOTO 15
IACT(I,2)=0
IACT(I,3)=0
IDATE(I)=IDT
GOTO 30
15 CONTINUE
!
!     ELSE:  STORE THE PARAMETERS, POINTERS, AND DATE.
!
IACT(I,2)=IMPL
IACT(I,3)=IPEND
IDATE(I)=IDT
DO 20 J=IMPL,IPEND
PARMS(J)=PRMS(J-IMPL+1)
20 CONTINUE
IMPL=IPEND+1
30 CONTINUE
!
!     IF THE ACTIVITY IS BEING STORED FOR SCHEDULING AFTER AN EVENT,
!     THEN: UPDATE THE VALUE OF IEPT AND RETURN.
!
IF (.NOT.LOPEVN) GOTO 40
IEPT=IEPT-1
GOTO 50
40 CONTINUE
!
!     ELSE: STORE THE POINTER IN IOPSRT AND UPDATE IMGL.
!
IOPSRT(IMGL)=IMGL
IMGL=IMGL+1
!
!     BRANCH HERE TO EXIT: WRITE DEBUG IF REQUESTED.
!
50 CONTINUE
IF (LDEB) WRITE (JOSTND,60) IACTK,NPRMS,LOPEVN,IDT,IMPL,IMGL, &
      I,IPEND,KODE
60 FORMAT (' IN OPNEW: IACTK=',I4,' NPRMS=',I3,' LOPEVN=',L2, &
           ' IDT=',I4,' IMPL=',I5,' IMGL=',I5,' I=',I5, &
           ' IPEND=',I5,' KODE=',I2)
RETURN
!
ENTRY OPMODE (LMODE)
!
!     RETURNS THE MODE THAT OPTIONS ARE BEING STORED.
!
!     LMODE = TRUE IF OPTIONS FOLLOW AN EVENT AND FALSE
!             IF OPTIONS ARE BEING PROCESSED NORMALLY.
!
LMODE=LOPEVN
RETURN
END
