SUBROUTINE PCTILE (N,INDEX,CHAR,PERCNT,TOT)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!   THIS SUBROUTINE COMPUTES PERCENTILE WITHIN THE DISTRIBU-
!   TION OF A REAL VECTOR (SUCH THAT THE LARGEST ELEMENT HAS
!   A PERCNT((I)=100.0, WHERE I=INDEX(I)) AND ALSO COMPUTES
!   THE SUMS OF THE VECTOR.  VARIABLES USED ARE:
!
!     CHAR -- ARRAY LOADED WITH REAL VECTOR VALUES FOR EACH
!             RECORD
!
!    INDEX -- INDEXING ARRAY WHICH POINTS TO THE MEMBERS OF
!             'CHAR' IN DESCENDING ORDER.
!
!        N -- CURRENT NUMBER OF RECORDS
!
!   PERCNT -- ARRAY LOADED WITH VECTOR PERCENTILES FOR EACH
!             RECORD
!
!      TOT -- SUM OF THE VECTOR VALUES
!
!----------
!   DECLARATIONS
!----------
INTEGER N,NM1,INDN,I,J,INDJP1,INDJ,INDX1,INDI
REAL TOT,PERCNT(*),PCTIN1,CHAR(*)
INTEGER INDEX(*)
!
IF(N .EQ. 0) THEN
  PERCNT(1)=0.
  TOT=0.
ELSE
  PERCNT(1)= 100.
  TOT=CHAR(1)
ENDIF
!----------
!   RETURN IF ONLY 1 RECORD
!----------
IF( N .LE. 1 )RETURN
NM1 = N - 1
INDN = INDEX(N)
PERCNT(INDN) = CHAR(INDN)
!----------
!   ACCUMULATE THE SUM OF THE VECTORS
!----------
DO 10 I = 1,NM1
J = N-I
INDJP1 = INDEX(J+1)
INDJ = INDEX(J)
PERCNT(INDJ)=PERCNT(INDJP1)+CHAR(INDJ)
10 CONTINUE
INDX1 = INDEX(1)
!----------
!   DESIGNATE THE SUM
!---------
TOT = PERCNT(INDX1)
PERCNT(INDX1) = TOT/100.
!----------
!   RETURN IF THE SUM IS LESS THAN OR EQUAL TO 0.0
!----------
IF ( TOT .LE. 0.0 )  RETURN
PCTIN1= PERCNT(INDX1)
DO 20 I = 2,N
INDI = INDEX(I)
!----------
!   COMPUTE THE PERCENTILE WITHIN THE DISTRIBUTION
!----------
PERCNT(INDI)=PERCNT(INDI)/PCTIN1
20 CONTINUE
PERCNT(INDX1) = 100.
RETURN
END
