SUBROUTINE PTGDECD(POINTNO,KARD,IFLAG)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     DECODE THE POINT GROUP NAME CODE
!     POINTNO IS THE POINT NUMBER, IF THE POINT GROUP IS A NAME,
!                THEN ASSIGN A SEQUENTIAL, NEGATIVE, GROUP NUMBER
!     IFLAG = 0 IF POINT GROUP IS NOT FOUND; 1 IF IT IS.
!     KARD  = CHARACTER REPRESENTATION OF POINT FIELD
!
!OMMONS
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
!OMMONS
!----------
INTEGER IFLAG,POINTNO,J,I
CHARACTER*10 TEMP
CHARACTER*10 KARD
!----------
!  IF ISPC IS A POSITIVE NON-ZERO NUMBER THEN ITS A NUMERIC SPECIES
!  CODE
!----------
IF(POINTNO .GT. 0) THEN
  IFLAG = 0
  GO TO 100
ENDIF
!----------
!  POINTNO = 0, CHECK FOR ALPHA POINT GROUP NAME.
!  LOAD TEMP WITH UP TO TEN NON-BLANK CHARS IN KARD.
!----------
TEMP='          '
J=0
DO 10 I=1,10
IF (KARD(I:I).NE.' ') THEN
  DO 5 J=1,MIN(10,10-I+1)
  TEMP(J:J)=KARD(I+J-1:I+J-1)
  CALL UPCASE(TEMP(J:J))
5   CONTINUE
  EXIT
ENDIF
10 CONTINUE
!
DO 30 I=1,NPTGRP
IF(TEMP .EQ. PTGNAME(I)) THEN
  POINTNO=-I
  IFLAG=1
  GO TO 50
ENDIF
30 CONTINUE
!
IFLAG = 0
GO TO 100
!
50 CONTINUE
KARD=TEMP
!
100 CONTINUE
!----------
! NOTHING WAS FOUND, SO IT MUST BE BLANK AND NOT A POINT GROUP NAME.
!----------
RETURN
END
!----------
