SUBROUTINE RESAGE
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     RESAGE RESETS THE AGE OF THE STAND TO THE VALUE SPECIFIED
!     BY KEYWORD. THIS ROUTINE IS CALLED FROM MAIN AFTER THE CALL
!     TO DISPLY AND THE REGENERATION/ESTABLISHMENT SYSTEM.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
!OMMONS
!
INTEGER MYACT2(1)
REAL PRMS(1)
INTEGER NTODO,KDT,NP,IACTK,IDT
DATA MYACT2/443/
!
!     PROCESS RESETAGE KEYWORD
!
CALL OPFIND (1,MYACT2,NTODO)
IF (NTODO.LE.0) RETURN
KDT=IY(ICYC+1)-1
CALL OPGET (NTODO,1,IDT,IACTK,NP,PRMS)
IF (IACTK.LT.0) RETURN
CALL OPDONE (NTODO,KDT)
IAGE=IFIX(PRMS(1))-IDT+IY(1)
!
RETURN
END
