SUBROUTINE SPESRT
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     REALIGNS THE SPECIES-ORDER SORT AFTER THE TREE LIST HAS
!     BEEN COMPRESSED AND/OR TREES HAVE BEEN ADDED VIA THE
!     REGENERATION ESTABLISHMENT SUBMODEL.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
INTEGER I
!
!OMMONS
!
!     INITIALIZE VARIABLES
!
NUMSP=0
DO I=1,MAXSP
   ISCT(I,1)=0
   ISCT(I,2)=0
   IBEGIN(I)=0
   IREF(I)=0
   KOUNT(I)=0
ENDDO
IF (IREC1.EQ.0) THEN
   ITRN=0
ELSE
!
!        SET UP INDEX POINTERS FOR CHAIN SORTING.
!
!        ESTABLISH A LINK IN THE CHAIN SORT FOR ALL LIVE TREES.
!
   DO I=1,IREC1
      CALL LNKCHN (I)
   ENDDO
!
!        SET UP THE POINTERS TO THE SPECIES-ORDER SORT; IND1 AND ISCT.
!
   CALL SETUP
ENDIF
!
RETURN
END
