!ODE SEGMENT SUMTAB
!----------
! COMMON $Id$
!----------
!
INTEGER MAIFLG,NEWSTD
!
INTEGER IBTAVH(MAXCY1),IBTCCF(MAXCY1),IOLDBA(MAXCY1), &
           ISDI(MAXCY1),ISDIAT(MAXCY1)
!
REAL    AGELST,TOTREM
!
REAL    BCYMAI(MAXCY1),QDBHAT(MAXCY1),QSDBT(MAXCY1)
!
COMMON /SUMTAB/ AGELST,BCYMAI,IBTAVH,IBTCCF,IOLDBA,ISDI,ISDIAT, &
                   MAIFLG,NEWSTD,QDBHAT,QSDBT,TOTREM
!
!----------
!  VARIABLE DEFINITIONS:
!----------
!  AGELST =
!  BCYMAI =
!  IBTAVH =
!  IBTCCF =
!  IOLDBA =
!    ISDI =
!  ISDIAT =
!  MAIFLG =
!  NEWSTD =
!  QDBHAT =
!   QSDBT =
!  TOTREM =
!
!-----END SEGMENT
