SUBROUTINE SVCMP2(ITARG,ISOUR)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     STAND VISUALIZATION GENERATION
!     N.L.CROOKSTON -- RMRS MOSCOW -- NOVEMBER 1998
!
!     REGISTER MOVEMENTS OF TREE RECORDS WITH THE VISUALIZATION DATA
!
!     INPUT:
!     ITARG IS A TARGET LOCATION TO WHICH A TREE WILL BE PLACED
!     ISOUR IS THE INDEX OF THE TREE BEING MOVED.
!
!     CALLED FROM COMPRS AND TREDEL.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'SVDATA.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'WORKCM.f90'
!
!
!OMMONS
!
INTEGER ISOUR,ITARG
INTEGER IWKCM1(MAXTRE)
EQUIVALENCE (IWKCM1,WORK1)
!
IF (JSVOUT.EQ.0) RETURN
!
IWKCM1(ISOUR)=ITARG
RETURN
END
