SUBROUTINE SVCMP3
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     STAND VISUALIZATION GENERATION
!     N.L.CROOKSTON -- RMRS MOSCOW -- NOVEMBER 1998
!
!     CALLED FROM COMPRS AND TREDEL.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'SVDATA.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'WORKCM.f90'
!
!
!OMMONS
!
INTEGER ISVOBJ,IPT
INTEGER IWKCM1(MAXTRE)
EQUIVALENCE (IWKCM1,WORK1)
!
IF (JSVOUT.EQ.0) RETURN
IF (NSVOBJ.EQ.0) RETURN
!
!     IF THERE ARE NO LIVE TREES LEFT, THEN REMOVE REFERENCES
!     TO LIVE TREES.
!
IF (ITRN.EQ.0) THEN
   DO ISVOBJ=1,NSVOBJ
      IF (IOBJTP(ISVOBJ).EQ.1) IOBJTP(ISVOBJ)=0
   ENDDO
   RETURN
ENDIF
!
!     IPT POINTS TO TREE RECORDS.  IF ZERO, THEN THE POINTER
!     POINTS TO A RECORD THAT WILL BE REMOVED.
!
DO ISVOBJ=1,NSVOBJ
   IF (IOBJTP(ISVOBJ).EQ.1) THEN
      IPT=IS2F(ISVOBJ)
      IF (IPT.GT.0) THEN
         IPT=IWKCM1(IPT)
         IF (IPT.GT.0) IS2F(ISVOBJ)=IPT
      ENDIF
   ENDIF
ENDDO
RETURN
END
