SUBROUTINE SVDFLN (X1,Y1,X2,Y2,A,B,KODE)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     STAND VISUALIZATION GENERATION
!     N.L.CROOKSTON -- RMRS MOSCOW -- NOVEMBER 1998
!
!     RETURNS A AND B FOR THE FORMULA Y=A+BX OF THE LINE
!     KODE = 0 IF OK, 1 = INFINITE SLOPE, NO INTERCEPT
!
REAL X1,Y1,X2,Y2,A,B
INTEGER KODE
A = 0.
B = 0.
KODE = 0
!
!     IF THE Y'S ARE EQUAL, THEN WE HAVE 0 SLOPE.  THE INTERCEPT
!     IS Y1, SLOPE IS SET TO 0.
!
IF (ABS(Y1-Y2) .LT. .000001) THEN
   A = Y1
   RETURN
ENDIF
!
!     IF THE X'S ARE EQUAL, THEN WE HAVE INFINITE SLOPE AND THE
!     INTERCEPT IS UNDEFINED.
!
IF (ABS(X1-X2) .LT. .000001) THEN
   KODE = 1
   RETURN
ENDIF
!
B = (Y2-Y1) / (X2-X1)
!
A = Y1 - (B*X1)
!
RETURN
END
