SUBROUTINE SVLCOL (X,Y,R,X1,Y1,X2,Y2,KODE)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     STAND VISUALIZATION GENERATION
!     N.L.CROOKSTON -- RMRS MOSCOW -- NOVEMBER 1998
!
!     RETURN KODE = 0 IF THE CIRCLE AND LINE DO NOT OVERLAP
!     RETURN KODE = 1 IF THEY DO.
!
INTEGER KODE
REAL Y1,Y2,X1,X2,R,X,Y,B1,A1,B,A,XS,YS
!
!     COMPUTE THE FORMULA FOR THE LINE.
!
CALL SVDFLN (X1,Y1,X2,Y2,A1,B1,KODE)
!
!     CASE 1: KODE = 1 IF THE SLOPE IS INFINITE.
!
IF (KODE.EQ.1) THEN
!
!        THE CIRCLE AND LINE INTERSECT IF X1 IS LESS THAN R FROM
!        THE LINE.
!
   IF (ABS(X1-X) .LT. R) THEN
      KODE = 1
   ELSE
      KODE = 0
   ENDIF
!
!     CASE 2: IF THE SLOPE IS ZERO.
!
ELSEIF (ABS(B1) .LE. .000001) THEN

   IF (ABS(Y1-Y) .LT. R) THEN
      KODE = 1
   ELSE
      KODE = 0
   ENDIF
!
ELSE

!     CASE 3: SLOPE IS NON ZERO AND NOT INFINITE.
!
!        DEFINE A PERPENDICULAR LINE THAT IS THROUGH THE CENTER OF THE
!        CIRCLE.

   B = -1.0/B1
   A = Y-(B*X)

!        FIND THE POINT WHERE THE TWO LINES CROSS.

   XS = (A-A1)/(B1-B)
   YS = A+(B*XS)

!        IF XS,YS IS CLOSER THAN R AWAY FROM X,Y THEN THE LINE BISECTS
!        THE CIRCLE.

   IF ( ((X-XS)**2)+((Y-YS)**2) .LT. R*R) THEN
      KODE = 1
   ELSE
      KODE = 0
   ENDIF
ENDIF
RETURN
END
