SUBROUTINE SVMORT (ICALLER, CUMMORT, ICURYEAR)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     STAND VISUALIZATION GENERATION
!     N.L.CROOKSTON -- RMRS MOSCOW -- NOVEMBER 1998
!     J.J.MARCHINEK -- RMRS MOSCOW -- JANUARY 1999
!     A.H.DALLMANN  -- RMRS MOSCOW -- JANUARY 2000
!     L.R.DAVID     -- FHTET FORT COLLINS -- JULY 2005
!
!     INPUT:
!     ICALLER = IDENTIFICATION OF THE CALLER.
!               0 - CALLED FROM GRINIT FOR FINAL MORTALITY...MORTALITY
!                   COMES FROM WK2...AND THIS IS THE LAST CALL FOR
!                   THE CYCLE (IMORTCNT IS RESET TO ZERO).
!               1 - CALLED FROM ELSEWHERE FOR INCREMENTAL MORTALITY
!                   AS STORED IN CUMMORT (THESE CALLS MUST COME PRIOR
!                   TO ANY CALLS WHERE ICALLER IS 0).
!               2 - CALLED FROM WESTWIDE PINE BEETLE FOR INCREMENTAL
!     CUMMORT = VECTOR OF CUMMULATIVE TREE MORTIALITY WHEN ICALLER
!               IS 1 OR 2, AND IS IGNORED WHEN ICALLER IS 0. ONLY THE
!               ADDITIONAL MORTALITY FROM THE LAST CALL IS PROCESSED.
!
!
!     UPDATES THE VISUALIZATION FOR MORTALITY. THIS CALL
!     ASSUMES THAT ALL THE TREES THAT "DIE" ARE STANDING
!     SNAGS.
!
!     CALLED FROM GRADD JUST BEFORE UPDATE.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'SVDATA.f90'
!
!
!OMMONS
!
!     SUM= TOTAL CHANGE IN MORT THIS CALL
!     CREATE DUMMY VERSIONS OF SSNG,DSNG,CTCRWN
!
REAL SUM,TEMP
INTEGER ICURYEAR,ICALLER,I
REAL SSNG(1),DSNG(1),CTCRWN(1)
REAL CUMMORT(*)
SUM = 0.

!     CHECK TO SEE IF MORT HAS NOT BEEN DONE YET THIS CYCLE.
!     IF IT HAS NOT, PROCESS ALL CHANGES.

IF (ICALLER .EQ. 0) THEN
   IF (IMORTCNT .EQ. 0) THEN

!           INITIALIZE SVMSAVE WITH WK2'S VALUES, AND FIND THE SUM
!           OF ALL THE VALUES IN WK2.

      DO I=1, ITRN
         SVMSAVE(I) = WK2(I)
         SUM = SUM + WK2(I)
      ENDDO
   ELSE

!           MODIFY WK2, REMOVING MORTALITY THAT HAS ALREADY BEEN DONE
!           DURING THIS CYCLE.  THIS NEW VALUE WILL BE PASSED INTO
!           SVRMOV, AND THEN WK2 WILL HAVE THE OLD VALUE ADDED BACK IN.

      DO I=1, ITRN
         TEMP = WK2(I)
         WK2(I) = WK2(I) - SVMSAVE(I)
         IF (WK2(I).LT. 0.0) WK2(I)=0.0
         SUM = SUM + WK2(I)
         SVMSAVE(I) = TEMP
      ENDDO

   ENDIF
ELSE

!        IF MORT HAS ALREADY BEEN DONE DURING THIS CYCLE, THEN ONLY
!        PROCESS THE NEW MORTALITY.

   IF (IMORTCNT .EQ. 0) THEN

!           INITIALIZE SVMSAVE WITH CUMMORT'S VALUES, AND FIND THE
!           SUM OF ALL THE VALUES IN CUMMORT.

      DO I=1, ITRN
         SVMSAVE(I) = CUMMORT(I)
         SUM = SUM + CUMMORT(I)
      ENDDO
   ELSE

!           MODIFY CUMMORT, REMOVING MORTALITY THAT HAS ALREADY BEEN DONE
!           DURING THIS CYCLE.  THIS NEW CUMMORT WILL BE PASSED INTO
!           SVRMOV, AND THEN CUMMORT WILL HAVE THE OLD VALUE ADDED BACK IN.

      DO I=1, ITRN
         TEMP = CUMMORT(I)
         CUMMORT(I) = CUMMORT(I) - SVMSAVE(I)
         IF (CUMMORT(I).LT.0.0) CUMMORT(I)=0.0
         SUM = SUM + CUMMORT(I)
         SVMSAVE(I) = TEMP
      ENDDO
   ENDIF

!        INCREMENT IMORTCNT TO SHOW THAT THE NUMBER OF TIMES SVMORT
!        HAS BEEN CALLED HAS INCREASED.

   IMORTCNT = IMORTCNT + 1

ENDIF

!     THIS ROUTINE WILL ONLY CALL SVRMOV WHEN THERE IS SOME AMOUNT OF CHANGE.

IF (SUM .GT. 0.) THEN
   IF (ICALLER .EQ. 0) THEN
      CALL SVRMOV (WK2,2,SSNG,DSNG,CTCRWN,ICURYEAR)
   ELSE
      IF (ICALLER .EQ. 1) THEN
         I = 1
      ELSEIF (ICALLER .EQ. 2) THEN
         I = 3
      ENDIF
      CALL SVRMOV (CUMMORT,I,SSNG,DSNG,CTCRWN,ICURYEAR)
   ENDIF
ENDIF

!     RESTORE THE VALUES STORED IN THE CUMMORT/WK2 ARRAY.

IF (ICALLER .EQ. 0) THEN
   DO I=1, ITRN
      WK2(I) = SVMSAVE(I)
   ENDDO

!        RESET THE MORTALITY CALL COUNTER TO 0...

   IMORTCNT = 0

ELSE
   DO I=1, ITRN
      CUMMORT(I) = SVMSAVE(I)
   ENDDO
ENDIF

RETURN
END
