SUBROUTINE SVONLN (X,Y,X1,Y1,X2,Y2,KODE)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     STAND VISUALIZATION GENERATION
!     N.L.CROOKSTON -- RMRS MOSCOW -- NOVEMBER 1998
!
!     RETURN KODE = 0 IF X,Y IS NOT WITHIN THE INTERVAL (X1,Y1),(X2,Y2)
!     RETURN KODE = 1 IF THIS POINT IS WITHIN THE INTERVAL.
!
!     THIS ROUTINE ONLY WORKS IF (X,Y) IS ON THE LINE...IT ONLY
!     CHECKS IF THE POINT IS ON THE INTERVAL...INCLUDING THE
!     ENDPOINTS.
!
INTEGER KODE
REAL X,Y,X1,Y1,X2,Y2
KODE = 0
IF (X1.LT.X2) THEN
   IF (X1.LE.X .AND. X.LE.X2) GOTO 10
ELSE
   IF (X2.LE.X .AND. X.LE.X1) GOTO 10
ENDIF
RETURN
!
10 CONTINUE
IF (Y1.LT.Y2) THEN
   IF (Y1.LE.Y .AND. Y.LE.Y2) GOTO 20
ELSE
   IF (Y2.LE.Y .AND. Y.LE.Y1) GOTO 20
ENDIF
!
RETURN
20 CONTINUE
KODE = 1
RETURN
END
