SUBROUTINE TREGRO
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!    CALLED FROM **MAIN** EACH CYCLE.
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
!OMMONS
!
!----------
!  DECLARATIONS:
!----------
LOGICAL LTMGO,LMPBGO,LDFBGO,LBWEGO,LCVATV,DEBUG
INTEGER :: ISTOPRES,IRTNCD,ISTOPDONE
LTMGO=.FALSE.
LMPBGO=.FALSE.
LDFBGO=.FALSE.
LBWEGO=.FALSE.
LCVATV=.FALSE.
!-----------
!  SEE IF WE NEED TO DO SOME DEBUG.
!-----------
CALL DBCHK (DEBUG,'TREGRO',6,ICYC)
!-----------
!  GET THE RESTART CODE AND BRANCH ACCORDINGLY.
!-----------
CALL fvsGetRestartCode (ISTOPRES)
IF (DEBUG) WRITE(JOSTND,2) ICYC,ISTOPRES
2 FORMAT (' IN TREGRO, ICYC=',I3,' ISTOPRES=',I3)
IF (ISTOPRES.GE.5 .and. .not. ISTOPRES.EQ.7) GOTO 10
!-----------
!  CALL GRINCR TO COMPUTE INCREMENTS AND SEE IF BUG MODELS ARE ACTIVE.
!-----------
CALL GRINCR (DEBUG,1,LTMGO,LMPBGO,LDFBGO,LBWEGO,LCVATV)
CALL getAmStopping (ISTOPDONE)
IF (ISTOPDONE.NE.0) RETURN
CALL fvsGetRtnCode(IRTNCD)
IF (IRTNCD.NE.0) RETURN
10 CONTINUE
!-----------
!  CALL GRADD TO COMPUTE BUGS AND ADD THE INCREMENTS.
!-----------
CALL GRADD (DEBUG,1,LTMGO,LMPBGO,LDFBGO,LBWEGO,LCVATV)
CALL fvsGetRtnCode(IRTNCD)
IF (IRTNCD.NE.0) RETURN
!----------
!  END OF CYCLE.
!----------
IF(DEBUG) WRITE(JOSTND,9022) ICYC
9022 FORMAT(' END OF TREGRO, CYCLE=',I2)
RETURN
END
