SUBROUTINE TRNASP
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!  TRNASP DECODES THE INPUT AZIMUTH VALUE GIVEN IN DEGREES AND CONVERTS
!  THE VALUE TO RADIANS. THE VALUE IS THEN ASSIGNED TO THE VARIABLE
!  ASPECT.
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
!OMMONS
!
!----------
!   CONVERT ASPECT TO RADIANS.
!----------
ASPECT=ASPECT*0.0174533
RETURN
END
