SUBROUTINE UNBLNK (RECORD,IRLEN)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!
!     THIS SUBROUTINE REMOVES ALL BLANKS FROM A CHARACTER
!     STRING, LEAVING THE NONBLANK CONTENTS OF THE STRING
!     LEFT JUSTIFIED, AND THE REST OF THE STRING BLANK.
!     IRLEN IS RETURNED AS THE LENGTH OF THE NONBLANK PORTION.
!
INTEGER IRLEN,LENREC,I
CHARACTER*(*) RECORD

IRLEN=0

LENREC=LEN(RECORD)
DO I=1,LENREC
   IF (RECORD(I:I).NE.' ') THEN
      IRLEN=IRLEN+1
      IF (IRLEN.LT.I) RECORD(IRLEN:IRLEN)=RECORD(I:I)
   ENDIF
ENDDO
IF (IRLEN.LT.LENREC) RECORD(IRLEN+1:LENREC)=' '
!
RETURN
END
