SUBROUTINE VOLKEY(DEBUG)
IMPLICIT NONE
!----------
! BASE $Id$
!----------
!  THIS SUBROUTINE PROCESSES THE KEYWORDS USED TO MODIFY VOLUME
!  STANDARDS AND EQUATIONS.
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'COEFFS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'OUTCOM.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'VOLSTD.f90'
!
!
!OMMONS
!
!----------
LOGICAL DEBUG
INTEGER MYACTS(4)
REAL PRMS(10)
INTEGER NTODO,I,NP,IACTK,KDT,INUM,ISPC,IGRP,IULIM,IG,IGSP,J
!----------
!  INITIALIZE ACTIVITY VECTORS.
!    215 = MCDEFECT
!    216 = BFDEFECT
!    217 = VOLUME
!    218 = BFVOLUME
!----------
DATA MYACTS/215,216,217,218/
!----------
!  IF CYCLE EQUAL ZERO, THEN THIS STUFF "CAN NOT" BE DONE.
!----------
IF (ICYC.EQ.0) GO TO 9960
!----------
!  DETERMINE IF VOLUME STANDARDS CHANGE THIS CYCLE.
!----------
CALL OPFIND(4,MYACTS,NTODO)
IF(NTODO.LE.0) GO TO 9960
DO 7 I=1,NTODO
CALL OPGET(I,12,KDT,IACTK,NP,PRMS)
!----------
!  IF THE PARAMETER COUNT IS TOO LOW, DELETE THE ACTIVITY.
!----------
IF (NP.LT.6) THEN
   CALL OPDEL1 (I)
   GOTO 7
ENDIF
INUM=219-IACTK
SELECT CASE (INUM)
!----------
!  CASE 1: CHANGE MERCHANTABILITY STANDARDS FOR THE BOARD FOOT VOLUME
!  EQUATIONS.  EMPIRICAL ADJUSTMENT DEVELOPED BY J. E. BRICKELL,
!  REGION ONE, TM.
!  BFVOLUME KEYWORD (IACTK=218).
!----------
CASE (1)
  CALL OPDONE(I,IY(ICYC))
  ISPC=IFIX(PRMS(1))

  IF(ISPC .LT. 0)THEN
    IGRP = -ISPC
    IULIM = ISPGRP(IGRP,1)+1
    DO IG=2,IULIM
      IGSP = ISPGRP(IGRP,IG)
      BFMIND(IGSP)=PRMS(2)
      BFTOPD(IGSP)=PRMS(3)
      BFSTMP(IGSP)=PRMS(4)
      FRMCLS(IGSP)=PRMS(5)
      METHB(IGSP)=IFIX(PRMS(6))
    END DO
  ELSEIF(ISPC .EQ. 0) THEN
    DO J=1,MAXSP
      BFMIND(J)=PRMS(2)
      BFTOPD(J)=PRMS(3)
      BFSTMP(J)=PRMS(4)
      FRMCLS(J)=PRMS(5)
      METHB(J)=IFIX(PRMS(6))
    END DO
  ELSE
    BFMIND(ISPC)=PRMS(2)
    BFTOPD(ISPC)=PRMS(3)
    BFSTMP(ISPC)=PRMS(4)
    FRMCLS(ISPC)=PRMS(5)
    METHB(ISPC)=IFIX(PRMS(6))
  ENDIF
!----------
!  CASE 2: CHANGE MERCHANTABILITY STANDARDS FOR MERCHANTABLE CUBIC
!  FOOT VOLUME EQUATIONS.  ADJUSTMENTS BASED ON BEHRE HYPERBOLA.
!  VOLUME KEYWORD (IACTK=217).
!----------
CASE (2)
  IF(.NOT. LFIANVB) THEN
    CALL OPDONE(I,IY(ICYC))
    ISPC=IFIX(PRMS(1))
    IF(ISPC .LT. 0)THEN
      IGRP = -ISPC
      IULIM = ISPGRP(IGRP,1)+1
      DO IG=2,IULIM
        IGSP = ISPGRP(IGRP,IG)
        DBHMIN(IGSP)=PRMS(2)
        TOPD(IGSP)=PRMS(3)
        STMP(IGSP)=PRMS(4)
        FRMCLS(IGSP)=PRMS(5)
        METHC(IGSP)=IFIX(PRMS(6))
        SCFMIND(IGSP)=PRMS(7)
        SCFTOPD(IGSP)=PRMS(8)
        SCFSTMP(IGSP)=PRMS(9)
      END DO
    ELSEIF(ISPC .EQ. 0) THEN
      DO J=1,MAXSP
        DBHMIN(J)=PRMS(2)
        TOPD(J)=PRMS(3)
        STMP(J)=PRMS(4)
        FRMCLS(J)=PRMS(5)
        METHC(J)=IFIX(PRMS(6))
        SCFMIND(J)=PRMS(7)
        SCFTOPD(J)=PRMS(8)
        SCFSTMP(J)=PRMS(9)
      END DO
    ELSE
      DBHMIN(ISPC)=PRMS(2)
      TOPD(ISPC)=PRMS(3)
      STMP(ISPC)=PRMS(4)
      FRMCLS(ISPC)=PRMS(5)
      METHC(ISPC)=IFIX(PRMS(6))
      SCFMIND(ISPC)=PRMS(7)
      SCFTOPD(ISPC)=PRMS(8)
      SCFSTMP(ISPC)=PRMS(9)
    ENDIF
  ENDIF
!----------
!  CASE 3: CHANGE DEFECT STANDARDS FOR BOARD FOOT VOLUME. ADJUSTMENTS ARE
!  BASED ON LINE SEGMENT DATA.
!  BFDEFECT KEYWORD (IACTK=216).
!----------
CASE (3)
  CALL OPDONE(I,IY(ICYC))
  ISPC=IFIX(PRMS(1))
  IF(ISPC .LT. 0)THEN
    IGRP = -ISPC
    IULIM = ISPGRP(IGRP,1)+1
    DO IG=2,IULIM
      IGSP = ISPGRP(IGRP,IG)
      BFDEFT(2,IGSP)=PRMS(2)
      BFDEFT(3,IGSP)=PRMS(3)
      BFDEFT(4,IGSP)=PRMS(4)
      BFDEFT(5,IGSP)=PRMS(5)
      BFDEFT(6,IGSP)=PRMS(6)
      BFDEFT(7,IGSP)=PRMS(6)
      BFDEFT(8,IGSP)=PRMS(6)
      BFDEFT(9,IGSP)=PRMS(6)
    END DO
  ELSEIF(ISPC .EQ. 0) THEN
    DO J=1,MAXSP
      BFDEFT(2,J)=PRMS(2)
      BFDEFT(3,J)=PRMS(3)
      BFDEFT(4,J)=PRMS(4)
      BFDEFT(5,J)=PRMS(5)
      BFDEFT(6,J)=PRMS(6)
      BFDEFT(7,J)=PRMS(6)
      BFDEFT(8,J)=PRMS(6)
      BFDEFT(9,J)=PRMS(6)
    END DO
  ELSE
    BFDEFT(2,ISPC)=PRMS(2)
    BFDEFT(3,ISPC)=PRMS(3)
    BFDEFT(4,ISPC)=PRMS(4)
    BFDEFT(5,ISPC)=PRMS(5)
    BFDEFT(6,ISPC)=PRMS(6)
    BFDEFT(7,ISPC)=PRMS(6)
    BFDEFT(8,ISPC)=PRMS(6)
    BFDEFT(9,ISPC)=PRMS(6)
  ENDIF
!----------
!  CASE 4: CHANGE DEFECT STANDARDS FOR CUBIC FOOT VOLUME. ADJUSTMENTS ARE
!  BASED ON SEGMENTED LINED DATA.
!  MCDEFECT KEYWORD (IACTK=215).
!----------
CASE (4)
  IF(.NOT. LFIANVB) THEN
    CALL OPDONE(I,IY(ICYC))
    ISPC=IFIX(PRMS(1))
    IF(ISPC .LT. 0)THEN
      IGRP = -ISPC
      IULIM = ISPGRP(IGRP,1)+1
      DO IG=2,IULIM
        IGSP = ISPGRP(IGRP,IG)
        CFDEFT(2,IGSP)=PRMS(2)
        CFDEFT(3,IGSP)=PRMS(3)
        CFDEFT(4,IGSP)=PRMS(4)
        CFDEFT(5,IGSP)=PRMS(5)
        CFDEFT(6,IGSP)=PRMS(6)
        CFDEFT(7,IGSP)=PRMS(6)
        CFDEFT(8,IGSP)=PRMS(6)
        CFDEFT(9,IGSP)=PRMS(6)
      END DO
    ELSEIF(ISPC .EQ. 0) THEN
      DO J=1,MAXSP
        CFDEFT(2,J)=PRMS(2)
        CFDEFT(3,J)=PRMS(3)
        CFDEFT(4,J)=PRMS(4)
        CFDEFT(5,J)=PRMS(5)
        CFDEFT(6,J)=PRMS(6)
        CFDEFT(7,J)=PRMS(6)
        CFDEFT(8,J)=PRMS(6)
        CFDEFT(9,J)=PRMS(6)
      END DO
    ELSE
      CFDEFT(2,ISPC)=PRMS(2)
      CFDEFT(3,ISPC)=PRMS(3)
      CFDEFT(4,ISPC)=PRMS(4)
      CFDEFT(5,ISPC)=PRMS(5)
      CFDEFT(6,ISPC)=PRMS(6)
      CFDEFT(7,ISPC)=PRMS(6)
      CFDEFT(8,ISPC)=PRMS(6)
      CFDEFT(9,ISPC)=PRMS(6)
    ENDIF
  ENDIF
END SELECT
7 CONTINUE
!
9960 CONTINUE
IF(DEBUG) WRITE(JOSTND,9970) (BFMIND(I),BFTOPD(I),BFSTMP(I), &
                                 I,I=1,MAXSP)
9970 FORMAT(' BFMIND=',F10.2,' BFTOPD=',F10.2,' BFSTMP=', &
          F10.2,' SPECIES=',I3)
!
RETURN
END
