SUBROUTINE CUTS
IMPLICIT NONE
!----------
! VBASE $Id$
!----------
!  THIS SUBROUTINE IS CALLED ONCE PER CYCLE.  IT INITIALIZES THE
!  THINNING SUMMARY ARRAYS AND THEN EXECUTES THE THINNING STRATEGY
!  INDICATED.  CALLS **CLSSTK** AND **AUTSTK** WHICH ARE ENTRY
!  POINTS IN SUBROUTINE **CUTSTK**.  ALSO CALLS **SDICLS**, **CCCLS**,
!  AND **RDCLS** WHICH ARE ENTRY POINTS IN **SDICAL**, CALLS **CUTQFA**
!  TO PROCESS UNEVEN AGE MANAGEMENT ACTION
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'COEFFS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'OUTCOM.f90'
!
!
INCLUDE 'PDEN.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'VARCOM.f90'
!
!
INCLUDE 'ECON.f90'
!
!
INCLUDE 'ESHOOT.f90'
!
!
!OMMONS
!----------
!  TYPE DECLARATIONS FOR INTERNAL VARIABLES.
!----------
REAL SPCRT(MAXSP,3),SPCRC(MAXSP,3),SPCRES(MAXSP,3), &
             SPCBR(MAXSP,3),SPCMR(MAXSP,3),SSNG(MAXTRE), &
             SPCSR(MAXSP,3), &
             DSNG(MAXTRE),CTCRWN(MAXTRE),TKCRWN(MAXTRE)
REAL BASNEW,CUTMAX,FTCUT,CRLEN,CRI,HTI,DHI,DLOW,PPROP
REAL FEET,PREM2,P,DMAX,REMTPA,DIFF,ORGWK4,TREERD,TEMP,CWDI
REAL CRBASE,CUT,PREM,XMORE,XLEFT,THIS,TOTCUT,XSZ,V,D,SUMD2,CLKNT
INTEGER IOLDCR,ISPEC,IMETH,IPRUN,NPRUN,IM,INDX,ISPG,ISPC,IDMR
INTEGER INEG,IPOS,IG,IULIM,IGRP,IP,IS,IDMCUT,ICUT,JSPCUT,JTYP
REAL SDIC,STAGEA,STAGEB,CUTEF1,CSDI,CBA,CTPA,VALMAX,VALMIN,CSTOCK
REAL HTHI,HTLO,DBHHI,DBHLO,RSTOCK,REMOVE,FULSTK,STOCK,CUTEFF
REAL TARGET,TREES,CMCUT,TSUMD2,TCLKNT,PRLOST,PRDSNG,PRCRWN
REAL BACUT,BFCUT,CFCUT,SCCUT,TCUT,ZSDI
REAL CCCLC1,CCCLC21,CCCSDI,CCT,CRADIF,CCCDIF
INTEGER IPCHK,NPS,KUT,JPNUM,KDT,IACTK,NP,NTODO,IC,J,ISPCUT
INTEGER KUTNOW,IT,IVAC,I
LOGICAL LBAREA,LBELOW,LSPECL,LNOAUT,DEBUG,LPDBH,LNOCUT(MAXTRE)
LOGICAL LSDI,LPRTND
REAL PRFMIS(MAXSP,6), LOSS, SALVTPA,CCC
INTEGER ISHAG,QFATAR,JOSTND1,ICFLAGQFA,JPTGRP,JPT
LOGICAL LYARD,LINCL,LPTALL
LOGICAL LQFA,LZEIDEQFA,DEBUG1,LDELQFA,LPTGROUP
REAL DIACW,QFAC,TARQFA,VALMINQFA,VALMAXQFA,CFVOLI

!     ADDITIONAL RDCLS ARGUMENTS THAT ARE NOT USED IN CUTS
REAL TPAFAC,DIAMFAC

!----------
!  ACTIVITY ARRAYS
!----------
INTEGER MYACTS(23)
REAL    PRMS(7)
DATA MYACTS/200,201,202,203,206, &
               222,223,224,225,226,227,228,229,230,231,232,233,234, &
               235,236,237, &
               248,249/
!----------
!  DEFINITIONS OF IMPORTANT VARIABLES:
!
!  ACTIVITIES:
!     200 = MINHARV
!     201 = SPECPREF
!     202 = TCONDMLT
!     203 = YARDING   (CURRENTLY TIED TO THE FIRE MODEL)
!     206 = SPLEAVE
!     222 = THINAUTO  (221 ALSO INDICATES THINAUTO)
!
!     223 = THINBTA
!     224 = THINATA
!     225 = THINBBA
!     226 = THINABA
!     227 = THINPRSC
!     228 = THINDBH
!     229 = SALVAGE (ABANDONED, CAN REUSE THIS SLOT. GED 11.23.05)
!     230 = THINSDI
!     231 = THINCC
!     232 = THINHT
!     233 = THINMIST
!     234 = THINRDEN
!     235 = THINPT
!     236 = THINRDSL
!     237 = THINQFA-TPA,BA,SDI
!
!     248 = SETPTHIN
!     249 = PRUNE
!
!  LAUTON = LOGICAL FLAG TO DETECT PRESENCE OF THINAUTO KEYWORD IN
!           THE RUNSTREAM.
!           .TRUE.  IF THINAUTO KEYWORD IS PRESENT
!           .FALSE. OTHERWISE
!  LBAREA = LOGICAL FLAG IF BASAL AREA THINNING IS BEING ATTEMPTED
!           .TRUE.  IF THINABA, THINBBA, OR THINDBH TO A BA TARGET
!           .FALSE. OTHERWISE
!  LBELOW = LOGICAL FLAG IF THINNING FROM BELOW IS BEING ATTEMPTED
!           .TRUE.  IF THINAUTO, THINBTA, OR THINBBA
!           .TRUE.  IF THINSDI, THINCC, THINRDEN, OR THINPT FROM BELOW
!           .FALSE. OTHERWISE
!   LINCL = LOGICAL VARIABLE USED TO INDICATE WHETHER THE TREE, BASED
!           ON SPECIES, GETS CONSIDERED IN THE CUT OR NOT.
!           .TRUE.  IF THE TREE SHOULD BE CONSIDERED BASED ON SPECIES
!           .FALSE. OTHERWISE
!  LSPECL = LOGICAL FLAG FOR THINNINGS WHICH DO NOT REQUIRE A SORTED
!           REMOVAL PRIORITY LIST
!           .TRUE.  IF THINPRSC, SALVAGE, THINDBH, THINHT, OR
!                   THINSDI, THINCC, OR THINRDEN THAT IS THROUGHOUT
!                   THE STAND, OR THINPT THROUGHOUT THE POINT.
!           .FALSE. OTHERWISE
!  LNOAUT = LOGICAL FLAG TO SUPPRESS AUTOMATIC THINNINGS WHEN OTHER
!           THINNINGS ARE PRESENT
!           .TRUE.  IF AUTOMATIC THINNING IS TO BE SUPRESSED
!           .FALSE. OTHERWISE
!  LPDBH  = LOGICAL FLAG TO INDICATE SIZE TERM IN REMOVAL PRIORITY
!           .TRUE.  IF DBH IS TO BE USED AS THE SIZE TERM
!           .FALSE. IF HT  IS TO BE USED AS THE SIZE TERM
!  LNOCUT = LOGICAL FLAG TO INDICATE TREE RECORD IS OUTSIDE THE
!           SPECIFIED CUTTING CLASS DBH/HT/SPECIES RANGE
!           .TRUE.  IF THE TREE RECORD IS EXEMPT FROM CUTTING
!           .FALSE. IF THE TREE RECORD CAN BE CONSIDERED FOR CUTTING
!  LSDI   = LOGICAL FLAG TO INDICATE THAT AN SDI, CC, RD OR PT THINNING
!           IS BEING ATTEMPTED.
!           .TRUE.  IF THINSDI, THINCC, THINRDEN, OR THINPT IS BEING ATTEMPTED
!           .FALSE. OTHERWISE
!  LYARD  = LOGICAL FLAG TO INDICATE THAT YARDING KEYWORD IS ACTIVE
!           .TRUE.  IF YARDING ENABLED; LOSSES MAY OCCUR
!           .FALSE. IF YARDING ABSENT; REMOVALS ARE PERFECT
!  LPRTND = LOGICAL FLAG WHICH INDICATES WHETHER 'PRETEND' MODE IS
!           ACTIVE. THIS FEATURE IS PART OF THE ECON EXTENSION.
!  LPTALL = LOGICAL FLAG TO INDICATE THAT ALL POINTS ARE BEING THINNED
!           WITH THE THINPT KEYWORD (SETPTHIN, PRMS(1)=0)
!    LQFA = LOGICAL RETURN VARIABLE FROM CUTQFA
!           .TRUE. MORE DIAMETER CLASSES TO BE PROCESSED
!           .FALSE. LAST DIAMETER CLASS TO BE PROCESSED
! LDELQFA = LOGICL FLAG TO DELETE THINQFA ACTIVITY IF TARGET .GT. STOCKING
!           SET IN **CUTQFA**
! LPTGROUP= LOGICAL FLAG IS TRUE IF A GROUP OF POINTS IS TO BE PROCESSED
!  JPTGRP = HOLDS THE POINT GROUP NUMBER FOR PROCESSING IN CUTS
!
!  QFATAR = FLAG TO SET THINQFA TARGET 0=BA, 1=TPA, 2= SDI
!
!  CFMIN  = MINIMUM HARVEST IN MERCHANTABLE CUBIC FEET
!  BFMIN  = MINIMUM HARVEST IN MERCHANTABLE BOARD FEET
!  BAMIN  = MINIMUM HARVEST IN SQUARE FEET OF BASAL AREA
! TCFMIN  = MINIMUM HARVEST IN TOTAL CUBIC FEET
! SCFMIN  = MINIMUM HARVEST IN SAWLOG CUBIC FOOT
!
!  THE FOLLOWING VARIABLES ARE SUMS FOR ALL THINS IN THE CYCLE
!   CFCUT = TOTAL CUBIC FEET CUT
!   BFCUT = TOTAL BOARD FEET CUT
!   BACUT = TOTAL BASAL AREA CUT
!   TCUT  = TOTAL TREES PER ACRE CUT
!   CMCUT = TOTAL MERCHANTABLE CUBIC FEET CUT
!   SCCUT= TOTAL SAWLOG CUBIC FOOT CUT
!
!  TREES  = TOTAL TREES PER ACRE BEFORE ANY THINNINGS
!  ICFLAG = CUTTING FLAG SET TO ACTIVITY NUMBER - 220
!  RSTOCK = RESIDUAL STOCKING AFTER THIN
!  STOCK  = AMOUNT OF STOCKING IN TPA OR BA ON A STAND LEVEL
!           WHICH IS AVAILABLE TO BE CUT
!  CSTOCK = AMOUNT OF STOCKING IN TPA OR BA IN A SPECIFIED CLASS
!           WHICH IS AVAILABLE TO BE CUT
!  TARGET = AFTER THINNING TARGET IN TPA OR BA
!  REMOVE = AMOUNT OF STOCKING IN TPA OR BA WHICH NEEDS TO BE
!           REMOVED IN THE THIN
!  CUTEFF = CUTTING EFFICIENCY
!  KUTNOW = CODE FROM THINPRSC KEYWORD WHICH INDICATES WHICH TREES
!           ARE BEING REMOVED DURING CURRENT PRESCRIPTION THIN. A SPECIAL
!           VALUE OF -1 MEANS THAT WK6 IS PRELOADED WITH THE PROPORTION OF
!           EACH TREE TO BE REMOVED.
!  DBHLO  = LOWER DBH CLASS BOUNDARY FOR THIN (GE)
!  DBHHI  = UPPER DBH CLASS BOUNDARY FOR THIN (LT)
!  HTLO   = LOWER HT  CLASS BOUNDARY FOR THIN (GE)
!  HTHI   = UPPER HT  CLASS BOUNDARY FOR THIN (LT)
!  ISPCUT = SPECIES BEING CUT, OR SPECIES CLASS FOR THIN
!  IDMCUT = DWARF MISTLETOE RATING BEING CUT FOR THINMIST
!  VALMIN = LOWER DBH OR HT CLASS BOUNDARY (GE)
!  VALMAX = UPPER DBH OR HT CLASS BOUNDARY (LT)
!  CTPA   = RESIDUAL CLASS TARGET TPA FOR THINDBH OR THINHT
!  CBA    = RESIDUAL CLASS TARGET BA  FOR THINDBH OR THINHT
!
!  AUTMIN = THINAUTO LOWER LIMIT
!  AUTMAX = THINAUTO UPPER LIMIT
!  AUTEFF = THINAUTO CUTTING EFFICIENCY
!
!  WORK ARRAYS:
!     WK2 = STORES REMOVAL PRIORITY DURING TRIAL THINNING, AND
!           STORES TOTAL CF VOLUME REMOVED IN FINAL PASS
!     WK3 = STORES REMOVED TREES PER ACRE
!     WK4 = STORES CURRENT TREES PER ACRE REPRESENTATION OF TREE
!           RECORD, ADJUSTED AS THINNINGS ARE DONE
!     WK5 = STORES REMOVED MERCH CF VOLUME
!     WK6 = STORES REMOVED MERCH BF VOLUME. UPON THE SUBROUTINE ENTRY
!           WK6 CAN BE PRELOADED WITH THE PROPORTION OF EACH TREE THAT
!           WILL BE REMOVED WHEN THINPREC IS USED WITH KUTNOW SET TO -1
!
!  THE FOLLOWING ARRAYS STORE VALUES BY SPECIES BY IMC CLASS
!    SPCRT  = REMOVED TREES PER ACRE
!    SPCRC  = REMOVED TOTAL CUBIC FOOT VOLUME
!    SPCRES = RESIDUAL TREES PER ACRE FOLLOWING THINNINGS
!    SPCBR  = REMOVED MERCH BOARD FOOT VOLUME
!    SPCMR  = REMOVED MERCH CUBIC FOOT VOLUME
!
!  THE FOLLOWING ARRAYS STORE VALUES BY THE NOMINAL PERCENTILE
!  DISTRIBUTION VALUES (10,30,50,70,90,100, & TOTAL)
!    ONTREM = REMOVED TREES PER ACRE
!    OCVREM = REMOVED TOTAL CUBIC FOOT VOLUME
!    ONTRES = RESIDUAL TREES PER ACRE FOLLOWING THINNINGS
!    OBFREM = REMOVED MERCH BOARD FOOT VOLUME
!    OMCREM = REMOVED MERCH CUBIC FOOT VOLUME
!    OSCREM = REMOVED CUBIC SAW FOOT VOLUME
!
!  ARRAYS RELATED TO YARDLOSS AND PRUNE KEYWORDS
!     SSNG  = SNAGS/ACRE CREATED BY CUTTING, BUT LEFT STANDING
!     DSNG  = SNAGS/ACRE CREATED BY CUTTING, DOWN LEFT IN STAND
!     CTCRWN= TREES/ACRE REMOVED BUT WHOSE CROWNS ARE STILL IN THE
!             STAND. LATER, IN THE PRUNE PROCESSING, THIS IS
!             THE PROPORITON OF THE CROWN THAT HAS BEEN PRUNED.
!     TKCRWN= TREES/ACRE CROWNS TAKEN OUT OF THE STAND
!-----------
!  SEE IF WE NEED TO DO SOME DEBUG. SET VARIANT.
!-----------
CALL DBCHK (DEBUG,'CUTS',4,ICYC)
IF (DEBUG) WRITE (JOSTND,9000) &
     &ORMAT (/' IN CUTS: VALUES OF PROB (15/LINE):'/)
IF (DEBUG) WRITE (JOSTND,9010) (PROB(I),I=1,ITRN) &
     &ORMAT (1X,12F10.4)
!----------
!  IF TREES GET HERE MARKED FOR DELETION, OR THEY GET HERE WITH ZERO
!  PROB FROM PREVIOUS CYCLE MORTALITY, DELETE THOSE TREE RECORDS.
!----------
IVAC=0
IF (ITRN .GT. 0) THEN
  CALL RDPSRT(ITRN,PROB,IND2,.TRUE.)
  DO 5 I=1,ITRN
  IT=IND2(I)
  IF(IT.LE.0)THEN
    IVAC=IVAC+1
  ELSEIF(PROB(IT).LE.1E-10)THEN
    IVAC=IVAC+1
    IND2(I)=-IT
  ENDIF
5   CONTINUE
  IF(DEBUG) WRITE (JOSTND,9091) IVAC,ITRN
9091   FORMAT (/' IN CUTS, TOTALLY DEAD TREES=',I5,'; TOT TREES=',I5)
  IF (IVAC.LE.0) GO TO 6
  CALL TREDEL (IVAC,IND2)
  CALL SPESRT
  IFST=1

!CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
!        THIS CODE WAS COMMENTED OUT BECAUSE SOME EVENT MONITOR
!        VARIABLES WERE NOT GETTING CALCULATED WHEN ALL TREES WERE DEAD
!        SPECIFIC CASE WAS WILDFIRE CAUSING 100% MORTALITY AND THEN
!        A COMPUTED SALVAGE VOLUME ON SUBSEQUENT CYCLE, 2 YEARS POST FIRE.
!        LANCE DAVID 03/05/2020
!
!        IF (ITRN.LE.0)THEN
!C----------
!C  CHECK FOR REQUEST OF SALVAGE ACTION FOR THE SPECIAL CASE WHERE ALL
!C  TREES IN THE STAND WERE KILLED
!C----------
!          CALL FMSALV (IY(ICYC),SALVTPA)
!          IF ( DEBUG ) THEN
!          WRITE (JOSTND,9013) SALVTPA
! 9013     FORMAT(' ','IN CUTS, FOLLOWING CALL TO FMSALV',
!     &    ' FOR SPECIAL CASE WHERE ALL TREES IN STAND ARE KILLED:',
!     &    ' SALVTPA=',F7.2)
!          GO TO 1900
!          ENDIF
!        ENDIF
!CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

  IND(1)=0
  CALL RDPSRT(ITRN,DBH,IND,.TRUE.)
6   CONTINUE
ENDIF
!----------
!  INITIALIZE REMOVAL SUMMARY ARRAYS AND LOGICAL FLAGS:
!----------
TPAFAC = 0.0
DIAMFAC = 0.0
TSUMD2 = 0.0
TCLKNT = 0.0
ASTPAR=0.0
ASBAR=0.0
KUTNOW=0
JPTGRP=0
JPT=0
LPDBH=.TRUE.
LNOAUT=.FALSE.
LQFA=.FALSE.
LDELQFA=.FALSE.
LPTGROUP=.FALSE.
ISPCUT=0
DO 10 I=1,7
ONTREM(I)=0.0
OCVREM(I)=0.0
ONTRES(I)=0.0
OBFREM(I)=0.0
OMCREM(I)=0.0
OSCREM(I)=0.0
!     CARBON AND BIOMASS
OAGBIOREM(I)    = 0.0
OAGCARBREM(I)   = 0.0
OMERBIOREM(I)   = 0.0
OMERCARBREM(I)  = 0.0
OCSAWBIOREM(I)  = 0.0
OCSAWCARBREM(I) = 0.0
OFOLIBIOREM(I)  = 0.0
OFOLICARBREM(I) = 0.0


PRMS(I)=0.
10 CONTINUE
DO 30 I=1,MAXSP
DO 20 J=1,3
SPCRT(I,J)=0.0
SPCRC(I,J)=0.0
SPCRES(I,J)=0.0
SPCBR(I,J)=0.0
SPCMR(I,J)=0.0
SPCSR(I,J)=0.0
20 CONTINUE
30 CONTINUE
!----------
! ZERO OUT THE REMOVED TREES (WK3), SNAG ARRAYS, YARDLOSS ARRAY
!----------
DO 31 IC=1,MAXTRE
WK3(IC)=0.
SSNG(IC)=0.
DSNG(IC)=0.
CTCRWN(IC)=0.
TKCRWN(IC)=0.
YRDLOS(IC)=0.
31 CONTINUE
!----------
!  SET YARDLOSS ACTIVE WITH DEFAULTS IF FIRE IS MODEL ACTIVE
!----------
CALL FMATV(LYARD)
PRLOST = 0.
PRDSNG = 0.
PRCRWN = 1.
!----------
!  IF CHEAPO WAS REQUESTED CALL **ECVOLS**
!----------
IF (LECON) CALL ECVOLS
!----------
!  CALL ECON EXTENSION ROUTINE TO LOAD ECON RELATED HARVEST/THIN
!  INFORMATION. THIS INFO IS PRE-HARVEST. ALSO CALL ROUTINE TO
!  DETERMINE WHETHER ECON 'PRETEND' HARVEST MODE IS ACTIVE THIS CYCLE.
!  CHECK ECON EXTENSION FOR "PRETEND" MODE - ENTRY IN ECSTATUS
!----------
CALL GETISPRETENDACTIVE(LPRTND)
IF (DEBUG) WRITE (JOSTND,*) 'ECON PRETEND MODE= ',LPRTND
!----------
!  PROCESS SALVAGE CUTS
!----------
CALL FMSALV (IY(ICYC),SALVTPA)
IF ( DEBUG ) THEN
   WRITE (JOSTND,9015) SALVTPA
9015    FORMAT(' ','IN CUTS, FOLLOWING FMSALV CALL: SALVTPA=',F7.2)
ENDIF
!----------
!  SUPPRESS THINAUTO OPTION IF OTHER THINNINGS ARE SCHEDULED.
!  THIS DOES NOT INCLUDE SETPTHIN OR PRUNING.
!  ACTIVITIES 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
!             234, 235, 236, 237
!----------
CALL OPFIND(15,MYACTS(7),NTODO)
IF(NTODO.GT.0) LNOAUT=.TRUE.
!----------
!  CHECK FOR UPDATE OF MINHARV PARAMETERS.
!  ACTIVITY 200
!----------
CALL OPFIND (1,MYACTS(1),NTODO)
IF(NTODO.LE.0) GO TO 40
CALL OPGET (NTODO,5,KDT,IACTK,NP,PRMS)
IF (IACTK.LT.0) GO TO 40
CALL OPDONE(NTODO,IY(ICYC))
BAMIN  = PRMS(1)
TCFMIN = PRMS(2)
CFMIN  = PRMS(3)
IF(VARACD.EQ.'CS' .OR. VARACD.EQ.'LS' &
      .OR. VARACD.EQ.'NE' .OR. VARACD.EQ.'SN' &
      .OR. LFIANVB) THEN
  SCFMIN = PRMS(4)
ELSE IF (.NOT.LFIANVB .AND. PRMS(4).GT.0) THEN
  CALL ERRGRO(.TRUE.,53)
END IF
BFMIN  = PRMS(5)
40 CONTINUE
!----------
!  PROCESS MISTLETOE CUTTING PREFERENCE KEYWORD.
!----------
CALL MISCPF(PRFMIS)
!----------
!  DETERMINE IF THINNING RELATED ACTIVITIES ARE SCHEDULED THIS CYCLE.
!  ACTIVITIES 201,202,203,206,222,223,224,225,226,227,228,229,230,231,232,
!             233,234,235,236,237,248
!----------
CALL OPFIND (21,MYACTS(2),NTODO)
IF (DEBUG) WRITE (JOSTND,9020) NTODO,(MYACTS(I),I=2,23) &
     &ORMAT (' IN CUTS:  NTODO=',I4,'; MYACTS=',22I5)
IF (NTODO.LE.0) THEN
   TCUT=0.0
   GO TO 1950
ENDIF
IF(DEBUG)THEN
  DO 701 I=1,MAXPLT
  IF(PTBAA(I).EQ.0. .AND. PCCF(I).EQ.0. .AND. PTPA(I).EQ.0.) &
     &O TO 701
  WRITE(JOSTND,*)' I,IPVEC(I),PTBAA,PCCF,PTPA = ', &
     &,IPVEC(I),PTBAA(I),PCCF(I),PTPA(I)
701   CONTINUE
ENDIF
!----------
!  INITIALIZE TRIAL THINNING VECTOR AND CONTROL VARIABLES.
!----------
IACTK=0
50 CONTINUE
IF (ITRN.LE.0) GO TO 100
DO 90 I=1,ITRN
WK4(I)=PROB(I)
90 CONTINUE
100 CONTINUE
CFCUT=0.0
BFCUT=0.0
BACUT=0.0
TCUT=0.0
CMCUT=0.0
SCCUT=0.0
TREES=ONTCUR(7)
JPNUM = 0
LPTALL=.FALSE.
!----------
!  BEGIN PROCESSING THINNING OPTIONS.
!----------
DO 1400 KUT=1,NTODO
LBELOW=.FALSE.
LSPECL=.FALSE.
LBAREA=.FALSE.
LSDI=.FALSE.
LQFA=.FALSE.
DO 101 I=1,7
PRMS(I)=0.
101 CONTINUE
!----------
!  BYPASS OPTION ASSIGNMENTS IF AUTOMATIC THINNING IS IN EFFECT.
!  NOTE: THINAUTO ASSIGNED ACTIVITY 221 AFTER 1950 CONTINUE
!----------
IF(IACTK.EQ.221) GO TO 150
CALL OPGET (KUT,7,KDT,IACTK,NPS,PRMS)
IF (DEBUG) WRITE (JOSTND,9030) KDT,IACTK,NPS,(PRMS(I),I=1,NPS) &
     &ORMAT (' IN CUTS:  KDT=',I5,'; IACTK=',I4,'; NPS=',I2, &
          '; PRMS=',10F8.2)
IF (IACTK.LT.0) GO TO 1400
!----------
!  PROCESS SETPTHIN KEYWORD. IF POINT NUMBER IS INVALID, CANCEL
!  KEYWORD REQUEST. IF IT IS VALID, FIND THE FVS
!  SEQUENTIAL POINT NUMBER FOR FURTHER PROCESSING.
!----------
IF(IACTK.EQ.248)THEN
  IF(PRMS(1).GE.0)THEN
    JPNUM=IFIX(PRMS(1)+0.5)
  ELSE
    JPNUM=IFIX(PRMS(1)-.5)
  ENDIF
  IF((JPNUM.GT.-.005).AND.(JPNUM.LT..005))THEN
    LPTALL=.TRUE.
    GOTO 12813
  ENDIF
  IF(JPNUM.LT.0)THEN
!
!  SET THE FIRST POINT IN THE POINT GROUP HERE AND CYCLE THROUGH THE
!  OTHER POINTS IN THE POINT GROUP BELOW STATEMENT NO 475
!
    LPTGROUP = .TRUE.
    JPT=1
    JPTGRP=-JPNUM
    JPNUM=IPTGRP(JPTGRP,2)
  ENDIF
  DO IPCHK=1,IPTINV
  IF(ITHNPI .EQ. 1)THEN
    IF(JPNUM .EQ. IPVEC(IPCHK))THEN
      JPNUM=IPCHK
      GO TO 12813
    ENDIF
  ELSE
    IF(JPNUM .LE. IPTINV) GO TO 12813
  ENDIF
  ENDDO
  CALL OPDEL1(KUT)
  GO TO 1400
12813   CONTINUE
  IF(PRMS(1).GE.0.)ITHNPN=IFIX(PRMS(1))
  IF(PRMS(2).GT.0.)ITHNPA=IFIX(PRMS(2))
  CALL OPDONE(KUT,IY(ICYC))
  IF(DEBUG)WRITE(JOSTND,*)' SETPTHIN PROCESSING ITHNPN,ITHNPA,', &
     &JPNUM,IPTINV= ',ITHNPN,ITHNPA,JPNUM,IPTINV
  GO TO 1400
ENDIF
!----------
!  RESET THE DATE, SET THE CUTTING FLAG, SET THE CUTTING
!  EFFICIENCY, AND THE TARGET.  IF THE AUTO THIN WAS SPECIFIED,
!  AUTMAX, AUTMIN, AND AUTEFF, ARE IN PRMS(1-3).
!----------
ICFLAG=IACTK-220
IF(ICFLAG .NE. 15)JPNUM=0
!----------
!  BRANCH TO END OF THINNING LOOP TO PROCESS SPECPREF OR
!  TCONDMLT REQUESTS.
!----------
IF(ICFLAG.LE.0) GO TO 1150
!----------
!  BRANCH TO PRUNING SECTION; NOTE: LNOAUT IS .TRUE.
!----------
IF(ICFLAG.GT.28) GO TO 1950
!----------
!  SAVE THE PARAMETERS FOR THE THINAUTO OPTION.
!----------
IF (ICFLAG.EQ.2) THEN
  AUTMIN=PRMS(1)
  AUTMAX=PRMS(2)
  AUTEFF=PRMS(3)
  LAUTON=.TRUE.
  CALL OPDONE(KUT,IY(ICYC))
  GO TO 1400
ENDIF
!----------
!  IF TREE LIST IS EMPTY, CANCEL THE CUTTING OPTION.
!----------
IF (ITRN.GT.0) GO TO 125
CALL OPDEL1 (KUT)
GO TO 1400
!
125 CONTINUE
TARGET=PRMS(1)
IF(TARGET.LT.0.)TARGET=0.
IF(NPS.GT.1)CUTEFF=PRMS(2)
STOCK=TREES-TCUT
SELECT CASE(ICFLAG)
CASE(1)
  GO TO 150
CASE(2,3)
  GO TO 200
CASE(4)
  GO TO 225
CASE(5)
  GO TO 250
CASE(6)
  GO TO 275
CASE(7,9)
  GO TO 300
CASE(8,12)
  GO TO 325
CASE(10,11,14,16)
  GO TO 400
CASE(13)
  GO TO 450
CASE(15)
  GO TO 475
CASE(17)
  GO TO 350
END SELECT
150 CONTINUE
ICFLAG=1
STOCK=TREES-TCUT
!----------
!  AUTOMATIC THINNING.
!----------
CUTEFF=AUTEFF
!----------
!  CALL AUTSTK TO CALCULATE FULSTK FOR AUTO THIN.
!  FULSTK IS NORMAL FULL STOCKING IN STEMS PER ACRE.
!----------
CALL AUTSTK (FULSTK)
!----------
!  THINNING WILL NOT BE EXECUTED IF STOCK IS LESS THAN AUTMAX
!  PERCENT OF NORMAL.
!----------
REMOVE=0.0
IF(STOCK.LT.(AUTMAX/100.0)*FULSTK) GO TO 2000
RSTOCK=(AUTMIN/100.0)*FULSTK
REMOVE=STOCK-RSTOCK
IF (REMOVE .LE. 0.) GO TO 2000
LBELOW=.TRUE.
IF (DEBUG) WRITE (JOSTND,9040) ICFLAG,STOCK,AUTMIN,AUTMAX,CUTEFF, &
      FULSTK,RMSQD,REMOVE,RSTOCK,LBELOW &
     &ORMAT (' ICFLAG  STOCK  AUTMIN  AUTMAX  CUTEFF  FULSTK  RMSQD ', &
     & REMOVE  RSTOCK  LBELOW'/1X,I5,8F8.2,L8)
GO TO 700
!----------
!  SET REMOVE AND RSTOCK FOR OPTIONS THINBTA AND THINATA. IF
!  THINBTA SET LBELOW TRUE.
!  BRANCHING HERE FOR THINAUTO IN COMPUTED "GO TO" WONT HAPPEN
!----------
200 CONTINUE
LBELOW=.TRUE.
225 CONTINUE
DBHLO=PRMS(3)
DBHHI=PRMS(4)
HTLO=PRMS(5)
HTHI=PRMS(6)
LPDBH = DBHHI-DBHLO .LE. HTHI-HTLO
JTYP= 1
JSPCUT= 0
CALL CLSSTK(CSTOCK,JTYP,JSPCUT,DBHLO,DBHHI,HTLO,HTHI,0)
RSTOCK=TARGET
REMOVE=CSTOCK-RSTOCK
GO TO 550
!----------
!  SET STOCK, REMOVE, RSTOCK, AND LBAREA FOR OPTIONS THINBBA AND
!  THINABA. IF THINBBA SET LBELOW TRUE.
!----------
250 CONTINUE
LBELOW=.TRUE.
275 CONTINUE
LBAREA=.TRUE.
DBHLO=PRMS(3)
DBHHI=PRMS(4)
HTLO=PRMS(5)
HTHI=PRMS(6)
JTYP= 2
JSPCUT= 0
CALL CLSSTK(CSTOCK,JTYP,JSPCUT,DBHLO,DBHHI,HTLO,HTHI,0)
RSTOCK=TARGET
REMOVE=CSTOCK-RSTOCK
GO TO 550
!----------
!  SET LSPECL, REMOVE, AND RSTOCK FOR PRESCRIPTION AND DIAMETER
!  LIMIT AND THINHT THINNINGS. VALMAX AND VALMIN ARE LOADED WITH
!  MAX AND MIN DBH WHEN THINDBH IS CALLED FOR AND THEY ARE LOADED WITH
!  MAX AND MIN HEIGHT WHEN THINHT IS CALLED FOR.
!----------
300 CONTINUE
!----------
!   THINPRSC OPTION.
!----------
CUTEFF=PRMS(1)
RSTOCK=0.0
REMOVE=99999.0
LSPECL=.TRUE.
IF(NPS.GT.1)KUTNOW=IFIX(PRMS(2))
GO TO 550
325 CONTINUE
!----------
!   THINDBH, THINHT, AND  OPTIONS.
!----------
VALMIN=PRMS(1)
VALMAX=PRMS(2)
IF(VALMAX .LT.VALMIN) VALMAX=9999.0
CUTEFF=PRMS(3)
ISPCUT=INT(PRMS(4))
CTPA=PRMS(5)
IF(CTPA.LT.0.)CTPA=0.
CBA=PRMS(6)
IF(CBA.LT.0.)CBA=0.
RSTOCK=0.0
REMOVE=99999.0
LSPECL=.TRUE.
GO TO 355
!----------
!   THINQFA OPTION.
!----------
350 CONTINUE
IF(DEBUG)WRITE(JOSTND,*)' PRMS= ',PRMS
VALMINQFA=PRMS(1)
VALMAXQFA=PRMS(2)
ISPCUT=INT(PRMS(3))
IF(VALMAXQFA .LT. VALMINQFA) VALMAXQFA=9999.0
QFAC=PRMS(4)
DIACW=PRMS(5)
TARQFA=PRMS(6)
QFATAR=INT(PRMS(7))
IF(TARQFA.LT.0.)TARQFA=0.
IF(DEBUG)WRITE(JOSTND,*)' QFATAR= ',QFATAR
IF(QFATAR.LE.0)THEN
  CTPA=0.
  CBA=TARQFA
  CSDI=0.
ELSEIF(QFATAR.LE.1)THEN
  CTPA=TARQFA
  CBA=0.
  CSDI=0.
ELSEIF(QFATAR.LE.2)THEN
  CTPA=0.
  CBA=0.
  CSDI=TARQFA
  LSDI=.TRUE.
ENDIF
CUTEFF=1.
CUTEF1=CUTEFF
RSTOCK=0.0
REMOVE=99999.0
LSPECL=.TRUE.
IF(DEBUG)WRITE(JOSTND,*)' ICFLAG,TARQFA,CTPA,CBA,CSDI,QFATAR= ', &
   ICFLAG,TARQFA,CTPA,CBA,CSDI,QFATAR
!----------
!  CALL CUTQFA TO PREPROCESS THE TARGET TPA,BA,SDI DIAMETER LIMIT
!  TARGETS FOR EACH DIAMETER CLASS
!----------
ICFLAGQFA=ICFLAG
LZEIDEQFA=LZEIDE
JOSTND1=JOSTND
DEBUG1=DEBUG
CALL CUTQFA(VALMINQFA,VALMAXQFA,ISPCUT,LZEIDEQFA,ICFLAGQFA, &
               CTPA,CBA,CSDI,QFATAR,QFAC,DIACW,JOSTND1, &
               DEBUG1,LDELQFA,LQFA)
IF(LDELQFA)THEN
  LQFA=.FALSE.
  CALL OPDEL1(KUT)
  GO TO 1400
ENDIF
352 CONTINUE
!----------
!  RETURN HERE TO PROCESS NEXT DIAMETER CLASS FOR THINQFA KEYWORD
!  CYCQFA IS AN ENTRY IN CUTQFA
!----------
CALL CYCQFA(VALMIN,VALMAX,CTPA,CBA,CSDI,QFATAR,DIACW, &
               ICFLAGQFA,JOSTND1,DEBUG1,LQFA)
IF((ICFLAG.EQ.17).AND.(QFATAR.EQ.2))GOTO 425
!----------
!  COMPUTE TOTAL REMOVAL AND CUTTING EFFICIENCY FOR A DIAMETER-
!  SPECIES CLASS WHEN RESIDUAL TPA OR BA IS SPECIFIED FOR THE CLASS.
!  CTPA AND CBA ARE SET TO .GE. 0 IN INITRE; CBA IS ALSO SET TO 0
!  WHEN CTPA GT 0.
!----------
355 CONTINUE
IF(CTPA.EQ.0.0 .AND. CBA.EQ.0.0) GO TO 360
CSTOCK=0.0
JTYP=1
IF(CBA.GT.0.)JTYP=2
IF ((ICFLAG.EQ.8).OR.((ICFLAG.EQ.17).AND.(QFATAR.LE.1))) THEN
  CALL CLSSTK(CSTOCK,JTYP,ISPCUT,VALMIN,VALMAX,0.,999.,0)
ELSEIF (ICFLAG.EQ.12) THEN
  CALL CLSSTK(CSTOCK,JTYP,ISPCUT,0.,999.,VALMIN,VALMAX,0)
ENDIF
IF(CSTOCK.LE.0.0) GO TO 360
RSTOCK=CTPA+CBA
REMOVE=CSTOCK-RSTOCK
IF(CBA.GT.0.0) LBAREA=.TRUE.
CUTEFF=REMOVE/CSTOCK
IF (CUTEFF.GT.1.0) CUTEFF=1.0
IF(ICFLAG.EQ.17)GO TO 360
!----------
!  RESET THE STORED PARAMETERS FOR CUTEFF.
!----------
PRMS(3)=MAX(0.0,CUTEFF)
CALL OPCHPR (KUT,6,PRMS)
360 CONTINUE
IF (DEBUG) WRITE(JOSTND,9050) CTPA,CBA &
     &ORMAT(' IN CUTS: CTPA=',F8.2,' CBA=',F8.2)
GO TO 550
!----------
!   THINSDI  OPTION (ICFLAG=10)
!   THINCC   OPTION (ICFLAG=11)
!   THINRDEN OPTION (ICFLAG=14)
!   THINPT   OPTION (ICFLAG=15)
!   THINRDSL OPTION (ICFLAG=16)
!   THINQFA- OPTION (ICFLAG=17)
!----------
400 CONTINUE
!----------
IF(DEBUG)WRITE(JOSTND,*)' AFTER STATEMENT 400-JPNUM= ',JPNUM
!----------
!  IF THIS IS A THINRDSL AND THE SILVAH FOREST TYPE IS NOT ONE WHERE THE
!  SILVAH RELATIVE DENSITY IS VALID, THEN CANCEL THE THINNING.
!  IF THIS IS A POINT THINNING TO A SILVAH RD TARGET AND THE FOREST TYPE
!  IS NOT A DEFINED SILVAH FOREST TYPE, THEN CANCEL THE THINNING.
!----------
IF((ICFLAG.EQ.16 .AND. ISILFT.EQ.0) .OR. (ICFLAG.EQ.15 .AND. &
       ITHNPA.EQ.6 .AND. ISILFT.EQ.0)) THEN
  CALL OPDEL1(KUT)
  GO TO 1400
ENDIF
!----------
CSDI = PRMS(1)
IF(CSDI.LT.0.)CSDI=0.
CUTEF1 = PRMS(2)
ISPCUT = INT(PRMS(3))
VALMIN = PRMS(4)
DBHLO = PRMS(4)
VALMAX = PRMS(5)
DBHHI = PRMS(5)
ICUT = INT(PRMS(6))
HTLO = 0.
HTHI = 999.
RSTOCK = 0.
REMOVE = 99999.
LSDI = .TRUE.
LPDBH = .TRUE.
LSPECL = .TRUE.
IF(ICUT .GT. 0) LSPECL = .FALSE.
IF(ICUT .EQ. 1) LBELOW = .TRUE.
425 CONTINUE
!
!  IF CLASS RESIDUAL TARGET IS GREATER THAN ZERO, DETERMINE CURRENT
!  STOCKING IN THE CLASS.
!
IF(DEBUG) &
     &RITE (JOSTND,*) 'IN CUTS: ICFLAG=',ICFLAG,' CSDI=',CSDI
IF(CSDI .GT. 0.) THEN
  IF(ICFLAG.EQ.10 .OR. (ICFLAG.EQ.15 .AND. ITHNPA.EQ.3) &
        .OR.((ICFLAG.EQ.17).AND.(QFATAR.EQ.2)))THEN
    CALL SDICLS(ISPCUT,VALMIN,VALMAX,2,SDIC,ZSDI, &
                   STAGEA,STAGEB,JPNUM)
    IF(LZEIDE)SDIC=ZSDI
  ELSEIF(ICFLAG.EQ.11 .OR. (ICFLAG.EQ.15 .AND. ITHNPA.EQ.4))THEN
    IF (CSDI.LT.100.)THEN
      CSDI=(43560.0*ALOG(1.0-(CSDI/100.))/0.785398)*(-1.0)
      IF(DEBUG) &
           WRITE (JOSTND,*) 'IN CUTS: RECALCULATED CSDI=',CSDI
      CALL CCCLS(ISPCUT,VALMIN,VALMAX,2,SDIC,JPNUM)
      IF(DEBUG) WRITE (JOSTND,*) &
         'IN CUTS: CCCLS RETURN-ISPCUT,VALMIN,VALMAX,SDIC,JPNUM=', &
         ISPCUT,VALMIN,VALMAX,SDIC,JPNUM
    ELSE
      CALL OPDEL1(KUT)
      GOTO 1400
    ENDIF
  ELSEIF(ICFLAG.EQ.14 .OR. (ICFLAG.EQ.15 .AND. ITHNPA.EQ.5))THEN
    CALL RDCLS(ISPCUT,VALMIN,VALMAX,2,SUMD2,CLKNT,SDIC,JPNUM, &
                  TPAFAC,DIAMFAC)
    TSUMD2 = SUMD2
    TCLKNT = CLKNT
  ELSEIF(ICFLAG.EQ.16 .OR. (ICFLAG.EQ.15 .AND. ITHNPA.EQ.6))THEN
    CALL RDCLS2(ISPCUT,VALMIN,VALMAX,2,SDIC,JPNUM)
  ELSEIF(ICFLAG.EQ.15 .AND. ITHNPA.EQ.1)THEN
    CALL CLSSTK(SDIC,1,ISPCUT,VALMIN,VALMAX,0.,999.,JPNUM)
  ELSEIF(ICFLAG.EQ.15 .AND. ITHNPA.EQ.2)THEN
    CALL CLSSTK(SDIC,2,ISPCUT,VALMIN,VALMAX,0.,999.,JPNUM)
    LBAREA=.TRUE.
  ENDIF
  IF(DEBUG)WRITE(JOSTND,*)'ISPCUT,VALMIN,VALMAX,SDIC,CSDI,ICFLAG', &
     & JPNUM= ',ISPCUT,VALMIN,VALMAX,SDIC,CSDI,ICFLAG,JPNUM
  IF(DEBUG)WRITE(JOSTND,*)' CUTEFF, CUTEF1= ',CUTEFF, CUTEF1
!
!  IF CANOPY COVER ADJUSTMENT (KEYWORD CCADJ) IS IN USE, THE DIFFERENCE
!  BETWEEN UNADJUSTED AND ADJUSTED COVER VALUES (CRADIF) NEEDS TO BE
!  INCLUDED IN THE CURRENT STOCKING VALUE (SDIC) FOR COMPARISON TO
!  TARGET VALUE (CSDI)
!
  CCC=1
  IF(CCCOEF.NE.1)CCC=CCCOEF
  IF(CCCOEF2.NE.1)CCC=CCCOEF2
! Uncorrected PCC for the given target PCC
  CCCLC1 = 100.0*CSDI*0.785398/43560.
! Corrected PCC adjusted using target PCC and CCC
  CCCLC21 = 100.0*(1.0-EXP(-(CCC/100)*CCCLC1))
  IF(CCCLC21.GT.CCCLC1)CCCLC21=CCCLC1
! Corrected PCC adjusted using target PCC and CCC assuming random
  CCT=(100.0*(1.0-EXP(-0.01*(100.0*CSDI*0.785398/43560.))))
! Uncorrected PCC required to reach target using CCC
  CCCSDI = ((ALOG(1+(-CCT/100)))/(CCC/100)*(-1))
! Crown area difference between the adjusted and unadjusted
  CRADIF = ABS((((CCCSDI/100)/0.785398)*43560)-CSDI)
  IF(DEBUG)WRITE(JOSTND,*) 'CCC,CCCLC21,CCT,CCCSDI,CRADIF=', &
            CCCOEF,CCCLC21,CCT,CCCSDI,CRADIF
!
!  IF CURRENT STOCKING EXCEEDS THE TARGET, SET TARGET RESIDUAL STOCKING,
!  AMOUNT TO REMOVE, AND CUTTING EFFICIENCY.
!
  IF((SDIC + CRADIF) .GT. CSDI) THEN
    IF (ICFLAG.EQ.11) THEN
      IF(CCC.LT.1)THEN
          RSTOCK = CSDI+CRADIF
          REMOVE = SDIC-RSTOCK
      ELSEIF(CCC.GT.1)THEN
          RSTOCK = CSDI-CRADIF
          REMOVE = SDIC-RSTOCK
      ELSE
        RSTOCK = CSDI
        REMOVE = SDIC-CSDI
      ENDIF
    ELSE
      RSTOCK = CSDI
      REMOVE = SDIC-CSDI
    ENDIF

    IF(DEBUG)WRITE(JOSTND,*)' RSTOCK,REMOVE,ICUT,CCCDIF,CCCLC1=', &
          RSTOCK,REMOVE,ICUT,CCCDIF,CCCLC1
    CUTEFF = REMOVE/SDIC
    IF(CUTEFF .GT. 1.) CUTEFF=1.
    IF(CUTEF1 .LT. CUTEFF)THEN
      PRMS(2)=MAX(0.,CUTEFF)
      CALL OPCHPR(KUT,6,PRMS)
    ELSE
      IF(ICUT.GT.0)CUTEFF = CUTEF1
    ENDIF
  ELSE
    REMOVE = 0.
  ENDIF
!
!  IF CLASS RESIDUAL TARGET IS ZERO, THEN SET TARGET RESIDUAL STOCKING
!  TO ZERO, SET AMOUNT TO REMOVE TO THE CURRENT STOCKING IN THE CLASS,
!  AND SET THE CUTTING EFFICIENCY TO 1.
!
ELSE
  IF(ICFLAG.EQ.10 .OR. (ICFLAG.EQ.15 .AND. ITHNPA.EQ.3) &
        .OR.((ICFLAG.EQ.17).AND.(QFATAR.EQ.2)))THEN
    CALL SDICLS(ISPCUT,VALMIN,VALMAX,2,SDIC,ZSDI, &
                   STAGEA,STAGEB,JPNUM)
    IF(LZEIDE)SDIC=ZSDI
  ELSEIF(ICFLAG.EQ.11 .OR. (ICFLAG.EQ.15 .AND. ITHNPA.EQ.4))THEN
    CALL CCCLS(ISPCUT,VALMIN,VALMAX,2,SDIC,JPNUM)
  ELSEIF(ICFLAG.EQ.14 .OR. (ICFLAG.EQ.15 .AND. ITHNPA.EQ.5))THEN
    CALL RDCLS(ISPCUT,VALMIN,VALMAX,2,SUMD2,CLKNT,SDIC,JPNUM, &
                  TPAFAC,DIAMFAC)
    TSUMD2 = SUMD2
    TCLKNT = CLKNT
  ELSEIF(ICFLAG.EQ.16 .OR. (ICFLAG.EQ.15 .AND. ITHNPA.EQ.6))THEN
    CALL RDCLS2(ISPCUT,VALMIN,VALMAX,2,SDIC,JPNUM)
  ELSEIF(ICFLAG.EQ.15 .AND. ITHNPA.EQ.1)THEN
    CALL CLSSTK(SDIC,1,ISPCUT,VALMIN,VALMAX,0.,999.,JPNUM)
  ELSEIF(ICFLAG.EQ.15 .AND. ITHNPA.EQ.2)THEN
    CALL CLSSTK(SDIC,2,ISPCUT,VALMIN,VALMAX,0.,999.,JPNUM)
    LBAREA=.TRUE.
  ENDIF
  REMOVE = SDIC
  RSTOCK = 0.
  CUTEFF = 1.
ENDIF
IF(DEBUG)WRITE(JOSTND,*)' CUTTING EFFICIENCY =',CUTEFF
GO TO 550
!----------
!   THINMIST OPTION (ICFLAG=12)
!----------
450 CONTINUE
IDMCUT=IFIX(PRMS(1))
DBHLO=PRMS(2)
DBHHI=PRMS(3)
IF(DBHHI .LT.DBHLO) DBHHI=9999.0
CUTEFF=PRMS(4)
RSTOCK=0.0
REMOVE=99999.0
LSPECL=.TRUE.
GO TO 550
!----------
!   THINPT OPTION (ICFLAG=15)
!----------
475 CONTINUE
!
!  IF THE POINT NUMBER OR THINNING ATTRIBUTE HAS NOT BEEN ENTERED,
!  CANCEL THE REQUEST.
!
IF(((ITHNPN.EQ.0).AND.(.NOT.LPTALL)).OR.(ITHNPA.EQ.0))THEN
  CALL OPDEL1(KUT)
  GOTO 1400
ENDIF
!
! PROCESS THE THINPT REQUEST:
!
IF(ITHNPA .LE. 7)THEN
  IF(LPTALL)THEN
    JPNUM=JPNUM+1
    GO TO 400
  ELSEIF(LPTGROUP.AND.(JPT.LE.IPTGRP(JPTGRP,1)))THEN
    JPT=JPT+1
    JPNUM=IPTGRP(JPTGRP,JPT)
    IF(ITHNPI .EQ. 1)THEN
      DO IPCHK=1,IPTINV
      IF(JPNUM .EQ. IPVEC(IPCHK))THEN
        JPNUM=IPCHK
        GO TO 400
      ENDIF
      ENDDO
    ELSEIF(JPNUM.LE.IPTINV)THEN
      GOTO 400
    ENDIF
  ELSE
    GOTO 400
  ENDIF
ELSE
  CALL OPDEL1(KUT)
  GO TO 1400
ENDIF
! 500 CONTINUE
!----------
!   ** FREE SPOT **
!----------
!     REMOVE=0.0
!----------
!  WRITE DEBUG OUTPUT IF DESIRED.
!----------
550 CONTINUE
IF(.NOT.DEBUG) GO TO 600
WRITE(JOSTND,9060) ICYC,ICFLAG,STOCK,RSTOCK,REMOVE,LBAREA, &
            LBELOW,LSPECL,KUTNOW,JPNUM &
     &ORMAT(' IN CUTS, CYCLE=',I3,' ICFLAG=',I2,' STOCK=',F8.1, &
          ' RSTOCK=',F8.1,' REMOVE=',F8.1,' LBAREA=',L1, &
          ' LBELOW=',L1,' LSPECL=',L1,' KUTNOW=',I2,' JPNUM=',I5)
600 CONTINUE
!----------
! IF REMOVE LESS THAN OR EQUAL TO 0.0, DELETE AND PROCESS THE NEXT.
!----------
IF((REMOVE.GT.0.0).OR.(LPTALL.AND.(JPNUM.LT.IPTINV)))GO TO 650
IF(LPTGROUP)THEN
  IF(JPT.LT.IPTGRP(JPTGRP,1))GO TO 650
ENDIF
CALL OPDEL1(KUT)
GO TO 1400
650 CONTINUE
!------------
!  SET THE CUTTING OPTION STATUS TO ACCOMPLISHED.  IF THE MIN.
!  HARVEST RESULTS IN THE TOTAL CUT NOT BEING ACCOMPLISHED, THEN
!  THE STATUS IS RESET TO 'DELETED'.
!-----------
CALL OPDONE(KUT,IY(ICYC))
700 CONTINUE
!----------
!  LOAD ARRAY WK2 WITH PRIORITIES FOR REMOVAL.
!----------
DO 850 I=1,ITRN
IS=ISP(I)
D=DBH(I)
IP=ITRE(I)
V=D
IF (ICFLAG .EQ. 12) V=HT(I)
LNOCUT(I)=.FALSE.
!----------
!  SET LINCL
!----------
LINCL = .FALSE.
IF(JPNUM.GT.0 .AND. ITRE(I).NE.JPNUM)GO TO 710
IF((ISPCUT.EQ.0 .OR. ISPCUT.EQ.ISP(I)).AND..NOT.LEAVESP(IS))THEN
  LINCL = .TRUE.
ELSEIF(ISPCUT.LT.0)THEN
  IGRP = -ISPCUT
  IULIM = ISPGRP(IGRP,1)+1
  DO 705 IG=2,IULIM
  IF((IS .EQ. ISPGRP(IGRP,IG)).AND..NOT.LEAVESP(IS))THEN
    LINCL = .TRUE.
    GO TO 710
  ENDIF
705   CONTINUE
ENDIF
710 CONTINUE
!----------
!  GET MISTLETOE RATING FOR CURRENT TREE RECORD.
!----------
CALL MISGET(I,IDMR)
!----------
!  SET REMOVAL PRIORITY FOR THINMIST REQUESTS
!----------
IF(ICFLAG.EQ.13)THEN
  LNOCUT(I)=D.LT.DBHLO.OR.D.GE.DBHHI .OR. &
               (IDMR.NE.IDMCUT .AND. IDMCUT.NE.0) .OR. &
               IDMR.EQ.0
  WK2(I)=1.0
  IF(LNOCUT(I))WK2(I)=0.0
  GO TO 850
ENDIF
!----------
!  GO TO STATEMENT 750 TO PROCESS PRESCRIPTIONS AND DIAMETER LIMIT
!  THINNINGS.
!----------
IF(LSPECL) GO TO 750
!----------
!  IF THINNING FROM BELOW, REVERSE THE SIGN OF THE TREE SIZE TERM
!  IN THE THINNING PRIORITY FORMULA.
!----------
IF (LPDBH) THEN
  XSZ=DBH(I)
ELSE
  XSZ=HT(I)
ENDIF
IF (LBELOW) XSZ=-XSZ
WK2(I)=XSZ + IORDER(IS) + TCWT * IMC(I) + SPCLWT*ISPECL(I) &
          + PBAWT*PTBAA(IP) + PCCFWT*PCCF(IP) + PTPAWT*PTPA(IP)
IF(DEBUG)WRITE(JOSTND,*)' I,WK2,XSZ,IORDER,IS,TCWT,IMC,SPCLWT,', &
   'ISPECL,IP,PBAWT,PTBAA,PCCFWT,PCCF,PTPAWT,PTPA= ',I,WK2(I),XSZ, &
   IORDER(IS),IS,TCWT,IMC(I),SPCLWT,ISPECL(I),IP,PBAWT,PTBAA(IP), &
   PCCFWT,PCCF(IP),PTPAWT,PTPA(IP)
IF(IDMR.GT.0) WK2(I)=WK2(I)+PRFMIS(IS,IDMR)
!
IF(ICFLAG.EQ.1) GO TO 850
LNOCUT(I)=DBH(I).LT.DBHLO.OR.DBH(I).GE.DBHHI .OR. &
             HT (I).LT.HTLO .OR.HT (I).GE.HTHI
!
!  IF THINNING BY SDI, CC, RDEN, RDSL, OR PT, AND THE TREE IS NOT OF THE
!  RIGHT SPECIES OR ON THE RIGHT POINT, FLAG TREE AS A NO CUT TREE.
!
IF((ICFLAG.EQ.10 .OR. ICFLAG.EQ.11 .OR. ICFLAG.EQ.14 .OR. &
      ICFLAG.EQ.15 .OR. ICFLAG.EQ.16 .OR. ((ICFLAG.EQ.17).AND. &
      (QFATAR.EQ.2))).AND. .NOT.LINCL) &
      LNOCUT(I)=.TRUE.
!
!  IF THINING BY BA OR TPA, AND THE TREE IS DESIGNATATED AS A LEAVE
!  SPECIES, FLAG TREE AS A NO CUT TREE
!
IF(LEAVESP(IS))LNOCUT(I)=.TRUE.
!
IF(DEBUG)WRITE(JOSTND,*)' I,WK2(),LNOCUT()= ',I,WK2(I),LNOCUT(I)
GO TO 850
750 CONTINUE
WK2(I)=1.0
IF(ICFLAG.EQ.8 .OR. ICFLAG.EQ.12 .OR. ((ICFLAG.EQ.17).AND. &
   (QFATAR.LE.1))) GO TO 800
IF(LSDI) GO TO 800
!----------
!  THINNING PRIORITY FROM PRESCRIPTION. NPS IS THE NUMBER OF
!  PARAMETERS SPECIFIED IN THE THINPRSC KEYWORD.  IF NPS IS 2
!  THEN CHECK KUTKOD FOR VALUES EQUAL TO KUTNOW.  IF NPS IS 1
!  THEN CHECK KUTKOD FOR VALUES GREATER OR EQUAL TO 2.
!----------
IF(NPS.EQ.1) THEN
  IF(KUTKOD(I).LT.2) WK2(I)=0.0
ELSE
  IF(KUTNOW.EQ.-1) THEN
    WK2(I)=WK6(I)
  ELSE
    IF(KUTNOW.NE.KUTKOD(I)) WK2(I)=0.0
  ENDIF
ENDIF
GO TO 850
!----------
!  DIAMETER LIMIT OR HEIGHT LIMIT THINNING.
!----------
800 CONTINUE
IF(V.LT.VALMIN.OR.V.GE.VALMAX) WK2(I)=0.0
IF(.NOT.LINCL) WK2(I)=0.0
850 CONTINUE
!----------
!  SORT REMOVAL PRIORITY ARRAY IN DESCENDING ORDER.  THE ARRAY IND2
!  CONTAINS THE SUBSCRIPTS TO THE SORTED ORDER.  BYPASS THE SORT
!  IF LSPECL IS TRUE.
!----------
IF(LSPECL) GO TO 900
IF (ITRN .GT. 0) CALL RDPSRT(ITRN,WK2,IND2,.TRUE.)
900 CONTINUE
!----------
!  LOOP THROUGH THE TREE LIST TO COMPUTE TRIAL THINNING STATISTICS.
!  ADJUSTED PROBS ARE STORED IN THE VECTOR WK4 UNTIL ALL
!  SCHEDULED THINNINGS ARE COMPLETE.  QUANTITIES OF BF VOLUME,
!  CF VOLUME, AND BASAL AREA REMOVED PER ACRE ARE ACCUMULATED ACROSS
!  ALL THINNINGS TO TEST FOR OVERALL COMPLIANCE WITH MINIMUM HARVEST
!  STANDARDS.
!----------
TOTCUT=0.0
THIS=0.0
XLEFT=999999.
DO 1100 I=1,ITRN
!----------
!    IT -- SUBSCRIPT TO RECORD WITH NEXT HIGHEST PRIORITY FOR
!          REMOVAL.  IF LSPECL IS TRUE, IT IS EQUAL TO I.  IF
!          LSPECL IS FALSE, IT IS EQUAL TO IND2(I).
!  PREM -- NUMBER OF TREES PER ACRE REMOVED BY THINNING TREE IT.
!   CUT -- STOCKING REMOVED BY THINNING TREE IT, STATED IN THE
!          APPROPRIATE UNITS (BASAL AREA OR TREES PER ACRE).
!  DMAX -- DIAMETER OF LARGEST TREE RECORD FOR WHICH SOME PORTION
!          WAS REMOVED.
!----------
IT=IND2(I)
IF (.NOT.LSPECL) GO TO 950
IT=I
IND2(I)=I
950 CONTINUE
D=DBH(IT)
XMORE=0.
!----------
!  IF REMOVE-TOTCUT IS LESS THAN OR EQUAL TO ZERO, THINNING IS COMPLETE.
!  ZERO OUT WK2 FOR REMAINING TREES. THE GNU SOFTWARE LEAVES REDSIDUAL DIGITS
!  AT THE 7TH DECIMALL PLACE. THIS CAUSED THE XLEFT VARIABLE TO TO HAVE
!  AN INCORRECT NON-ZERO VALUE IN SOME CASES PROCESSING THE THINRDSL KEYWORD,
!  AND ABRANCH TO STAEMENT 1000 BELOW WHEN THE THE CUT CARIABLE WAS ZERO.
!  THIS CAUSED A NUMERICAL ERROR EVALUATING PREM BELOW STATEMANT 1046.
!  WE NOW REQUIRE XLEFT TO BE GREATER THAN .0005, RATHER THAN ZERO, TO
!  PROCEED WITH CUTTING. TREES WITH A RESIDUAL OF LE .0005 AFTER CUTTING
!  ARE DELETED FROM THE TREE LIST BELOW STAEMENT 1500.
!
!----------
IF(DEBUG)WRITE(JOSTND,*)' LSDI,ICFLAG,XLEFT,REMOVE,TOTCUT= ', &
   LSDI,ICFLAG,XLEFT,REMOVE,TOTCUT
!
IF(LSDI.AND.((ICFLAG.EQ.10 .OR. ICFLAG.EQ.16 &
    .OR. ((ICFLAG.EQ.17).AND.(QFATAR.EQ.2)) &
    .OR. ((ICFLAG.EQ.15) .AND. (ITHNPA.EQ.3)) &
    .OR. ITHNPA.EQ.5 .OR. ITHNPA.EQ.6)))THEN
  IF(XLEFT .GT. .0005)GO TO 1000
ELSE
  IF(REMOVE-TOTCUT.GT.0.0) GO TO 1000
ENDIF
WK2(IT)=0.0
GO TO 1100
!----------
!  BRANCH TO END OF LOOP IF LNOCUT IS TRUE OR IF WK2(IT)=0
!  AND LSPECL IS TRUE.
!----------
     &F(WK2(IT).LE.0.0.AND.LSPECL) GO TO 1100
IF(LNOCUT(IT)) GO TO 1100
!----------
!  DETERMINE THE AMOUNT OF EACH TREE CUT AND COLLECT REMOVAL
!  SUMMARY INFORMATION.
!----------
if (KUTNOW.eq.-1) then
  PREM=Wk4(IT)*WK2(IT)
ELSE
  PREM=WK4(IT)*CUTEFF
ENDIF
IF (PREM.GT.WK4(IT)) PREM=WK4(IT)
IF (PREM.LE.0.0) GO TO 1100
CUT=PREM
IF(LBAREA) CUT=PREM*D*D*0.005454154
IF(ICFLAG.EQ.15 .AND. (ITHNPA.EQ.1 .OR. ITHNPA.EQ.2)) &
    CUT=CUT*(PI-FLOAT(NONSTK))
XLEFT=REMOVE-(TOTCUT+CUT)
IF(LSDI) THEN
  IF(ICFLAG.EQ.10 .OR. ((ICFLAG.EQ.17).AND.(QFATAR.EQ.2)) &
      .OR. (ICFLAG.EQ.15 .AND.ITHNPA.EQ.3))THEN
    CALL SDICLS(ISPCUT,VALMIN,VALMAX,2,SDIC,ZSDI, &
                   STAGEA,STAGEB,JPNUM)
    IF(LZEIDE)SDIC=ZSDI
    IF(DEBUG)WRITE(JOSTND,*)' SDI THINNING, TREE= ',IT,' DBH= ', &
       D,' RANGE= ',VALMIN,VALMAX,' WK4= ',WK4(IT),' CUTEFF= ', &
       CUTEFF,' PREM= ',PREM,' EXISTING SDI IN CLASS= ',SDIC, &
       ' PARAMETERS= ',STAGEA,STAGEB
    CUT=PREM*(STAGEA+STAGEB*D*D)
    IF(LZEIDE)CUT=PREM*(D/10.)**1.605
    IF(ICFLAG.EQ.15 .AND. ITHNPA.EQ.3)CUT=CUT*(PI-FLOAT(NONSTK))
    XLEFT = SDIC-(CSDI+CUT)
  ELSEIF(ICFLAG.EQ.11 .OR. (ICFLAG.EQ.15 .AND. ITHNPA.EQ.4))THEN
    CWDI = CRWDTH(IT)
    CUT=PREM*CWDI*CWDI
    IF(ICFLAG.EQ.15 .AND. ITHNPA.EQ.4)CUT=CUT*(PI-FLOAT(NONSTK))
    XLEFT=REMOVE-(TOTCUT+CUT)
  ELSEIF(ICFLAG.EQ.14)THEN
!         USE LU, H.B. TPA AND DIAMETER FACTORS TO CALCULATE CONTRIBUTION
!         OF THIS TREE TO THE CURTIS RD.

    CUT = (TPAFAC + DIAMFAC*(DBH(IT)**2.0))*PREM
    XLEFT = REMOVE - (TOTCUT + CUT)

  ELSEIF(ICFLAG.EQ.15 .AND. ITHNPA.EQ.5)THEN
    TEMP=TSUMD2-PREM*DBH(IT)*DBH(IT)
    CUT=SDIC-(TEMP*0.0054542)/(TEMP/(TCLKNT-PREM))**0.25
    CUT=CUT*(PI-FLOAT(NONSTK))
    XLEFT = SDIC-(CSDI+CUT)

  ELSEIF(ICFLAG.EQ.16 .OR. (ICFLAG.EQ.15 .AND. ITHNPA.EQ.6))THEN
    CALL RDSLTR(ISP(IT),IT,TREERD)
    CUT=PREM*TREERD
    IF(ICFLAG.EQ.15 .AND. ITHNPA.EQ.6)CUT=CUT*(PI-FLOAT(NONSTK))
    IF(DEBUG)WRITE(JOSTND,*)' CUT,PI,PREM,TREERD= ', &
       CUT,PI,PREM,TREERD
    XLEFT=REMOVE-(TOTCUT+CUT)
  ENDIF
ENDIF
IF(DEBUG)WRITE(JOSTND,*)' IT,WK4,CUTEFF,PREM,REMOVE,TOTCUT,CUT,', &
   'XLEFT= ',IT,WK4(IT),CUTEFF,PREM,REMOVE,TOTCUT,CUT,XLEFT
IF(LSDI .AND. (ICFLAG.EQ.10 .OR. ICFLAG.EQ.14 .OR. ICFLAG.EQ.16 &
     &OR. ((ICFLAG.EQ.17).AND.(QFATAR.EQ.2)) .OR. (ICFLAG.EQ.15 &
     &AND.(ITHNPA.EQ.3 .OR.ITHNPA.EQ.5 .OR. ITHNPA.EQ.6))))THEN
  XMORE=SDIC-CSDI
  IF(DEBUG)WRITE(JOSTND,*)' SDIC, CSDI, XMORE=',SDIC, CSDI, XMORE
  IF((ICFLAG.EQ.14) .OR. (ICFLAG.EQ.16) .OR. &
       (ICFLAG.EQ.15.AND.ITHNPA.EQ.6)) THEN
    XMORE=REMOVE-TOTCUT
    IF(DEBUG)WRITE(JOSTND,*)' IT,XMORE,REMOVE,TOTCUT= ', &
       IT,XMORE,REMOVE,TOTCUT
  ENDIF
  IF(XMORE.GT.CUT)GO TO 1050
  GO TO 955
ENDIF
IF(XLEFT.GE.0.0) GO TO 1050
!----------
!  THIS IS THE LAST TREE TO REMOVE.
!  THINSDI OR THINRDEN PREM NEEDS TO BE DETERMINED ITERATIVELY
!----------
955 CONTINUE
IF(DEBUG)WRITE(JOSTND,*)' AT 955 REMOVE,TOTCUT,XMORE,PREM,WK4=', &
     &EMOVE, TOTCUT, XMORE, PREM, WK4(IT), &
     & LSDI, ICFLAG, ITHNPA=',LSDI, ICFLAG, ITHNPA
IF(LSDI.AND.(ICFLAG.EQ.10.OR.((ICFLAG.EQ.17).AND.(QFATAR.EQ.2)) &
       .OR.(ICFLAG.EQ.15 .AND. ITHNPA.EQ.3)))THEN
  PREM=XMORE/(STAGEA+STAGEB*D*D)
  IF(LZEIDE)PREM=XMORE/(D/10)**1.605
  IF(PREM .GT. WK4(IT))PREM=WK4(IT)
  IF(DEBUG)WRITE(JOSTND,*)' IT,D,XMORE,CUT,STAGEA,STAGEB,EST PRE', &
     &M= ',IT,D,XMORE,CUT,STAGEA,STAGEB,PREM
  IPOS=0
  INEG=0
  ORGWK4=WK4(IT)
1045   CONTINUE
  IF(IPOS.GT.0 .AND. INEG.GT.0)GO TO 1046
  WK4(IT)=ORGWK4-PREM
  CALL SDICLS(ISPCUT,VALMIN,VALMAX,2,SDIC,ZSDI, &
                 STAGEA,STAGEB,JPNUM)
  IF(LZEIDE)SDIC=ZSDI
  DIFF=SDIC-CSDI
  IF(DEBUG)WRITE(JOSTND,*)' ITERATIVE THINSDI IT,SDIC WITH EST PR' &
     &'EM,CSDI,DIFF,', &
     &PREM,ORGWK4,WK4,STAGEA,STAGEB,IPOS,INEG,JPNUM= ', &
     &T,SDIC,CSDI,DIFF,PREM,ORGWK4,WK4(IT),STAGEA,STAGEB,IPOS,INEG, &
     &PNUM
  IF(ABS(DIFF).GT.0.5)THEN
    IF(DIFF.LT.0.)THEN
      PREM=PREM-0.05
      INEG=1
      GO TO 1045
    ELSE
      PREM=PREM+0.05
      IPOS=1
      GO TO 1045
    ENDIF
  ENDIF
1046   CONTINUE
  WK4(IT)=ORGWK4
ELSEIF(LSDI .AND. (ICFLAG.EQ.14 .OR. ICFLAG.EQ.16 .OR. &
                     (ICFLAG.EQ.15 .AND. ITHNPA.EQ.5).OR. &
                     (ICFLAG.EQ.15 .AND. ITHNPA.EQ.6)))THEN
  IF(DEBUG)WRITE(JOSTND,*)' IT,D,XMORE,CUT,PREM= ', &
     &T,D,XMORE,CUT,PREM
  PREM=(XMORE/CUT)*PREM
  IF(PREM .GT. WK4(IT))PREM=WK4(IT)
  IPOS=0
  INEG=0
  ORGWK4=WK4(IT)
1047   CONTINUE
  IF(IPOS.GT.0 .AND. INEG.GT.0)GO TO 1048
  WK4(IT)=ORGWK4-PREM
  IF((ICFLAG.EQ.14).OR.(ICFLAG.EQ.15 .AND. ITHNPA.EQ.5))THEN
!         THE TARGET AT THIS POINT IS NOT WHAT IS LEFT IN THE STAND, BUT WHAT
!         HAS BEEN SELECTED FOR CUTTING
!         GET RELATIVED DENSITY (SDIC) OF TREES TO BE CUT USING WK4 TPA
!         WHICH IS THE PARAMETER 2 -------v
    CALL RDCLS(ISPCUT,VALMIN,VALMAX,2,SUMD2,CLKNT,SDIC,JPNUM, &
                  TPAFAC,DIAMFAC)
    IF(DEBUG)WRITE(JOSTND,*)' CUTTING TREES- MIN, MAX, SDIC, ', &
         'REMOVE= ',VALMIN, VALMAX, SDIC,REMOVE
    DIFF = REMOVE - SDIC
  ELSE
    CALL RDCLS2(ISPCUT,VALMIN,VALMAX,2,SDIC,JPNUM)
    DIFF=SDIC-CSDI
  ENDIF

  IF(DEBUG)WRITE(JOSTND,*)' ITERATIVE THINRDEN IT,SDIC WITH EST P' &
     &'REM,CSDI,DIFF,', &
     &PREM,ORGWK4,WK4,IPOS,INEG,JPNUM= ', &
     &T,SDIC,CSDI,DIFF,PREM,ORGWK4,WK4(IT),IPOS,INEG,JPNUM
  IF(ABS(DIFF).GT.0.01)THEN
    IF(DIFF.LT.0.)THEN
      PREM=PREM-0.2
      INEG=1
      IF(DEBUG)WRITE(JOSTND,*)' CUT LESS - IT, DBH(IT), PREM =', &
           IT,DBH(IT),PREM
      IF(PREM .LE. 0.0) GO TO 1048
      GO TO 1047
    ELSE
      PREM=PREM+0.2
      IPOS=1
      IF(DEBUG)WRITE(JOSTND,*)' CUT MORE - IT, DBH(IT), PREM =', &
           IT,DBH(IT),PREM
      IF (PREM .GT. ORGWK4) GO TO 1048
      GO TO 1047
    ENDIF
  ENDIF
1048   CONTINUE
  WK4(IT)=ORGWK4
ELSE
  PREM=((XLEFT+CUT)/CUT)*PREM
ENDIF
CUT=REMOVE-TOTCUT
!----------
!  INCREMENT THE VALUE OF TCUT.
!----------
     &OTCUT=TOTCUT+CUT
TSUMD2=TSUMD2-PREM*DBH(IT)*DBH(IT)
TCLKNT=TCLKNT-PREM
IF(DEBUG)WRITE(JOSTND,*)'IT,CUT,TOTCUT,TSUMD2,TCLKNT= ', &
   IT,CUT,TOTCUT,TSUMD2,TCLKNT
!----------
!  IF YARDING LOSSES ARE BEING ACCOUNTED FOR, SOME OF THE
!  CUT IS PLACED IN SEPARATE POOLS AND DOES
!  NOT BECOME PART OF THE USUAL REMOVAL STATISTICS.
!----------
IF (LYARD) THEN
  LOSS = PREM * PRLOST
  DSNG(IT)=DSNG(IT) + LOSS * PRDSNG
  SSNG(IT)=SSNG(IT) + LOSS * (1.0 - PRDSNG)
  CTCRWN(IT)=CTCRWN(IT) + (PRCRWN * (PREM - LOSS)) + &
                (LOSS * PRDSNG)
  TKCRWN(IT)=TKCRWN(IT) + ((1.0 - PRCRWN) * (PREM - LOSS))
ELSE
  CTCRWN(IT)=CTCRWN(IT) + PREM
ENDIF
WK4(IT)=WK4(IT)-PREM
YRDLOS(IT)=YRDLOS(IT)+PREM*PRLOST
CFCUT=CFCUT+PREM*CFV(IT)
CMCUT=CMCUT+PREM*(1.-PRLOST)*MCFV(IT)
BFCUT=BFCUT+PREM*(1.-PRLOST)*BFV(IT)
SCCUT=SCCUT+PREM*(1.-PRLOST)*SCFV(IT)
BACUT=BACUT+PREM*D*D*0.005454154
TCUT=TCUT+PREM
THIS=THIS+PREM
IF (DEBUG) WRITE (JOSTND,9070) IT,TOTCUT,CUT,WK4(IT),CUTEFF,PREM, &
   PRLOST,PRDSNG,CFCUT,BFCUT,DSNG(IT),SSNG(IT),CTCRWN(IT),YRDLOS(IT) &
     &ORMAT (' IT=',I4,' TOTCUT=',F10.3,' CUT=',F10.3,' WK4(IT)=',F8.3, &
    ' CUTEFF=',F8.3,' PREM=',F8.3,' PRLOST=',F5.3,' PRDSNG=',F5.3/8X, &
    ' CFCUT=',F9.2,' BFCUT=',F9.2,' DSNG=',F7.2,' SSNG=',F7.2, &
    ' CTCRWN=',F7.2,' YRDLOS=',F10.5) &
     &ONTINUE
!----------
!   END TREE LOOP
!----------
GO TO 1350 &
     &ONTINUE
!----------
!  PROCESS SPECPREF AND TCONDMLT REQUESTS.
!----------
CALL OPDONE(KUT,IY(ICYC))
IF(IACTK.EQ.201) GO TO 1200
IF(IACTK.EQ.203) GO TO 1325
IF(IACTK.EQ.206) GO TO 1340

!
!     OPTION 202... TCONDMLT
!
TCWT=PRMS(1)
SPCLWT=PRMS(2)
PBAWT=PRMS(3)
PCCFWT=PRMS(4)
PTPAWT=PRMS(5)
GO TO 1400
!
!     OPTION 201... SPECPREF
!
     &ONTINUE
!
!     IF SPECIES CODE IS:
!        < 0 THEN IT APPLIES TO SPECIES IN A GROUP
!        = 0 THEN IT APPLIES TO ALL SPECIES
!        > 0 THEN IT APPLIES TO JUST THIS SPECIES
!
ISPC=IFIX(PRMS(1))
IF(ISPC .LT. 0)THEN
  IGRP = -ISPC
  IULIM = ISPGRP(IGRP,1)+1
  DO 1210 IG=2,IULIM
  ISPG = ISPGRP(IGRP,IG)
  IORDER(ISPG)=INT(PRMS(2))
1210   CONTINUE
ELSEIF(ISPC.EQ.0)THEN
  DO 1220 IS=1,MAXSP
  IORDER(IS)=INT(PRMS(2))
1220   CONTINUE
ELSE
  IORDER(ISPC)=INT(PRMS(2))
ENDIF
GO TO 1400
!
!     OPTION 203... YARDLOSS
!
     &ONTINUE
LYARD  = .TRUE.
PRLOST = PRMS(1)
PRDSNG = PRMS(2)
PRCRWN = PRMS(3)
GO TO 1400
!----------
!   OPTION 206... SPLEAVE
!   PROCESS THE SPLEAVE KEYWORD BY SETTING THE ELEMENTS OF THE LOGICAL
!   ARRAY LEAVESP: LEAVE THE SPECIES = .TRUE.
!                  DON NOT LEAVE THE SECIES = .FALSE.
!----------
     &ONTINUE
IF(IFIX(PRMS(1)-.5).LT.0)THEN
  IGRP=INT(-PRMS(1))
  IULIM=ISPGRP(IGRP,1)+1
  DO IG=2,IULIM
  IF(IFIX(PRMS(2)+.5).GT.0)THEN
    LEAVESP(ISPGRP(IGRP,IG))=.TRUE.
  ELSE
    LEAVESP(ISPGRP(IGRP,IG))=.FALSE.
  ENDIF
  ENDDO
ELSEIF(IFIX(PRMS(1)+.5).EQ.0)THEN
  DO I=1,MAXSP
  LEAVESP(I)=.FALSE.
  ENDDO
ELSE
  IF(IFIX(PRMS(2)+.5).GT.0)THEN
    LEAVESP(IFIX(PRMS(1)+.5))=.TRUE.
  ELSE
    LEAVESP(IFIX(PRMS(1)+.5))=.FALSE.
  ENDIF
ENDIF
GO TO 1400
!
     &ONTINUE
!
!  THE FOLLOWING IF-THEN CONSTRUCT MANAGES THINING ALL POINTS (PRM(I)=0
!  WITH THE THINPT /SETPTHIN KEYWORDS
!
IF(DEBUG)WRITE(JOSTND,*)'LPTALL,JPNUM,IPTINV,LQFA=', &
   LPTALL,JPNUM,IPTINV,LQFA
IF(LPTALL)THEN
  IF(JPNUM.LT.IPTINV)THEN
    JPNUM=JPNUM+1
    GO TO 400
  ELSE
    LPTALL=.FALSE.
  ENDIF
ELSEIF(LPTGROUP)THEN
  IF(JPT.LE.IPTGRP(JPTGRP,1))THEN
    JPT=JPT+1
    JPNUM=IPTGRP(JPTGRP,JPT)
    IF(ITHNPI .EQ. 1)THEN
      DO IPCHK=1,IPTINV
      IF(JPNUM .EQ. IPVEC(IPCHK))THEN
        JPNUM=IPCHK
        GO TO 400
      ENDIF
      ENDDO
    ELSE
      IF(JPNUM .LE. IPTINV) GO TO 400
    ENDIF
  ENDIF
ENDIF
!
IF (THIS.LE.0.0) CALL OPDEL1(KUT)
!
IF(LQFA)GOTO 352
!
     &ONTINUE
!----------
!  IF THERE WERE NO REMOVALS, BYPASS THE CALCULATION OF
!  DISTRIBUTION STATISTICS.
!----------
IF(TCUT.LE.0.0)  GO TO 1950
!----------
!  IF TRIAL THINNINGS RESULT IN A TRIVIAL TPA REMAINING IN THE STAND,
!  THEN ADJUST TRIAL THINNINGS SO ALL TPA IN THE STAND ARE REMOVED.
!  ADDITIONAL YARDING LOSSES ARE IGNORED SINCE THE TPA ARE SO SMALL.
!----------
REMTPA = TREES - TCUT
IF(REMTPA .GT. 0. .AND. REMTPA .LT. 0.01) THEN
  DO 1405 INDX=1,ITRN
  IF(WK4(INDX) .GT. 0.) THEN
    CFCUT=CFCUT+WK4(INDX)*CFV(INDX)
    CMCUT=CMCUT+WK4(INDX)*MCFV(INDX)
    SCCUT=SCCUT+WK4(INDX)*SCFV(INDX)
    BFCUT=BFCUT+WK4(INDX)*BFV(INDX)
    BACUT=BACUT+WK4(INDX)*DBH(INDX)*DBH(INDX)*0.005454154
    TCUT=TCUT+WK4(INDX)
    WK4(INDX)=0.
  ENDIF
1405   CONTINUE
ENDIF
!----------
!  TRIAL THINNINGS COMPLETED.  TEST FOR COMPLIANCE WITH THE MINIMUM
!  HARVEST STANDARDS. IF ECON 'PRETEND' MODE IN EFFECT THEN DO
!  NOT ACTUALLY PERFORM THE THINNING.
!----------
IF (DEBUG) WRITE (JOSTND,9080) BACUT,BAMIN,CMCUT,CFMIN, &
                                  BFCUT,BFMIN,CFCUT,TCFMIN &
     &ORMAT (' IN CUTS: BACUT,BAMIN=',2F10.3, &
           '; CMCUT,CFMIN=',2F10.2,';'/,10x,'BFCUT,BFMIN=',2F10.2, &
           '; CFCUT,TCFMIN=',2F10.2)
!
IF(BACUT.GE.BAMIN .AND. CMCUT.GE.CFMIN .AND. BFCUT.GE.BFMIN &
   .AND. CFCUT.GE.TCFMIN .AND. SCCUT .GE. SCFMIN &
   .AND. .NOT. LPRTND) GO TO 1500
!----------
!  FLAG THINNINGS AS DELETED (NO COMPLIANCE WITH MINIMUM).  CUT WILL ALSO
!  BE CANCELED IF ECON 'PRETEND' MODE IS ACTIVE.
!----------
IF (ICFLAG .EQ. 1) GO TO 2000
DO 1450 I=1,NTODO
CALL OPGET (I,7,KDT,IACTK,NPS,PRMS)
IF (IABS(IACTK).GT.222) CALL OPDEL1(I) &
     &ONTINUE
!----------
! RESET YARD LOSS ACCUMULATOR TO 0.
!----------
DO 1455 I=1,MAXTRE
YRDLOS(I)=0. &
     &ONTINUE
!-------
!    INSURE THAT REMOVAL INFO IS NOT LOADED INTO THE ECON EXTENSION
!    IF REMOVAL WAS CANCELED BECAUSE MINIMUM REQUIREMENTS WERE NOT
!    MET.
!-------
IF (.NOT. LPRTND .OR. BACUT.LT.BAMIN .OR. CMCUT.LT.CFMIN .OR. &
     &FCUT.LT.BFMIN .OR. CFCUT.LT.TCFMIN .OR. SCCUT.LT.SCFMIN) &
     &O TO 1950
!
     &ONTINUE
!----------
!  TRIAL THINNING IS ACCEPTABLE.  ONE FINAL PASS THROUGH THE TREE
!  LIST IS NEEDED TO EFFECT REMOVALS AND SUMMARIZE THE RESULTS.
!----------
DMAX=0.0
IVAC=0
DO 1700 I=1,ITRN
IT=IND2(I)
IS=ISP(IT)
IM=IMC(IT)
WK2(IT)=0.0
WK5(IT)=0.0
WK6(IT)=0.0
WK7(IT)=0.0
WK8(IT)=0.0
WK9(IT)=0.0
WK10(IT)=0.0
WK11(IT)=0.0
WK12(IT)=0.0
WK13(IT)=0.0
WK14(IT)=0.0
WK15(IT)=0.0
D=DBH(IT)
!----------
!  PREM IS THE DIFFERENCE BETWEEN ORIGINAL DENSITY AND THE TOTAL OF
!  MERCH REMOVALS AND ALL YARDING LOSSES. IF YARDING IS INACTIVE
!  THEN THE DSNG/SSNG POOLS WILL BE ZERO.
!----------
PREM=PROB(IT)-WK4(IT)
IF (LPRTND) GOTO 1640
!----------
!  IF THE RESIDUAL FOR THE TREE RECORD IS NEARLY ZERO, THEN:
!  SIGNAL THAT THE TREE BE DELETED AND CUT THE ENTIRE TREE.
!  -- ADDED CONDITION IF PREM EQUALS 0.0 SO THAT ONLY TREE RECORDS
!  SPECIFICALLY SELECTED WITHIN THE CUTTING TARGET DBH/HT SIZE
!  RANGE SHOW UP IN THE CUTLIST -- LRD 11/6/18
!----------
P=PROB(IT)-PREM
IF (P .GT. 0.0005 .OR. PREM .EQ. 0.0) GO TO 1550
IF(DEBUG)WRITE(JOSTND,*) &
    'TPA < .0005 REMOVE. IT, DBH, P, PROB, PREM = ', &
                         IT, D, P, PROB(IT), PREM
PREM=PROB(IT)
PROB(IT)=0.0
IF(LYARD)YRDLOS(IT)=YRDLOS(IT)+P*PRLOST
IVAC=IVAC+1
IND2(I)=-IT
GO TO 1600 &
     &ONTINUE
!---------
!  IF THE PROBABILITY OF REMOVAL IS TRIVIAL, DON NOT CUT THE TREE
!----------
IF(PREM.LT.0.00001) GO TO 1650
PROB(IT)=P &
     &ONTINUE
IF(D.GT.DMAX) DMAX=D
!----------
!  IF YARDING LOSSES ARE ACCOUNTED FOR, REMOVE THE AMOUNT
!  SUCCESSFULLY REMOVED FROM THE STAND BY THE PROPORTIONAL
!  LOSS. NOTE THAT PREM2 IS THE REDEFINED PREM: THE TPA
!  ACTUALLY REMOVED FROM THE STAND. THIS IS A BIT OF A KLUDGE
!  SO THAT THE MERCH CF AND BF VOLUMES ARE THE AMOUNTS TAKEN
!  FROM THE STAND, AND WK2 AND WK3 ACCOUNT FOR THE AMOUNTS KILLED
!----------
     &ONTINUE
PREM2 = AMAX1(0.0,PREM - DSNG(IT) - SSNG(IT))
!----------
!  CALL ECON EXTENSION TO ACCUMULATE REMOVAL BFV
!  INFORMATION TO BE USED IN BFV REVENUE CALCULATIONS.
!  IF WE ARE IN ECON PRETEND MODE DO NOT ACCUMULATE STATISTICS
!  FOR THE CUT.
!----------
IF(PREM2.GT.0.00001)THEN
  IF (VARACD .EQ. 'CS' .OR. VARACD .EQ. 'LS' &
          .OR. VARACD .EQ. 'NE' .OR. VARACD .EQ. 'SN') THEN
    CFVOLI = SCFV(I)
  ELSE
    CFVOLI = MCFV(I)
  ENDIF
  CALL ECHARV (BFV(IT),D,CFVOLI,GROSPC,PREM2,IS,IT,ICYC,IY)
ENDIF
IF (LPRTND) GOTO 1700
!
IF(DEBUG)WRITE(JOSTND,*)' IT,PREM,PREM2,DSNG,SSNG,YRDLOS(IT)= ', &
    IT,PREM,PREM2,DSNG(IT),SSNG(IT),YRDLOS(IT)
!
IF(PREM.LE.0.)THEN
  YRDLOS(IT)=0.
ELSE
  YRDLOS(IT)=YRDLOS(IT)/PREM
ENDIF
IF(DEBUG)WRITE(JOSTND,*)' IT,YRDLOS FINAL= ',IT,YRDLOS(IT)
WK2(IT)=PREM*CFV(IT)
WK3(IT)=PREM
PREM2 = AMAX1(0.0,PREM - DSNG(IT) - SSNG(IT))
WK5(IT)=PREM2*MCFV(IT)
WK7(IT)=PREM2*SCFV(IT)
WK6(IT)=PREM2*BFV(IT)
!     CARBON AND BIOMASS
!       Non-products reflect total cut (PREM)
WK8(IT)=PREM*ABVGRD_BIO(IT)
WK9(IT)=PREM*ABVGRD_CARB(IT)
WK14(IT)=PREM*FOLI_BIO(IT)
WK15(IT)=PREM*FOLI_CARB(IT)
!       Commerical products reflect total cut, less loss volume (PREM2)
WK10(IT)=PREM2*MERCH_BIO(IT)
WK11(IT)=PREM2*MERCH_CARB(IT)
WK12(IT)=PREM2*CUBSAW_BIO(IT)
WK13(IT)=PREM2*CUBSAW_CARB(IT)
!     SPECIES DISTRIBUTION
SPCBR(IS,IM)=SPCBR(IS,IM)+WK6(IT)
SPCMR(IS,IM)=SPCMR(IS,IM)+WK5(IT)
SPCSR(IS,IM)=SPCSR(IS,IM)+WK7(IT)
SPCRT(IS,IM)=SPCRT(IS,IM)+WK3(IT)
SPCRC(IS,IM)=SPCRC(IS,IM)+WK2(IT)
!----------
!     ADD STUMPS TO LIST FOR REGENERATION SPROUTS.
!----------
ISHAG = IFINT
CALL ESTUMP (IS,D,AMAX1(0.0,PREM-SSNG(IT)),ITRE(IT),ISHAG)
!----------
!  CALL WESTERN ROOT DISEASE MODEL VER. 3.0 SUBROUTINE TO ADD STUMPS
!  TO STUMP LIST
!----------
CALL RDSTR (IT,PREM,P+PREM)
!----------
!  CALL WESTWIDE BEETLE MODEL SUBROUTINE TO CREATE SLASH FOR IPS
!----------
CALL BMSLSH (IS,PREM,CFV(IT),0) &
     &ONTINUE
!
SPCRES(IS,IM)=SPCRES(IS,IM)+PROB(IT)
!
     &ONTINUE
!----------
!  CALL ECON EXTENSION ROUTINE TO LOAD HARVEST/THIN ECON INFORMATION
!  FOR REMOVED TREES. IF WE ARE IN 'PRETEND' MODE SKIP ACCUMULATION OF REMOVAL
!  STATISTICS.
!----------
IF (LPRTND) GOTO 1950
!----------
!  CALL PRTRLS TO PROCESS THE CUTLIST (ARGUMENT=2) OR AFTER TREATEMENT
!  (ARGUMENT=3) OPTION.
!----------
CALL PRTRLS (2)
CALL DBS_FIAVBC_CUTLST
CALL PRTRLS (3)
CALL DBS_FIAVBC_ATRTLS
!----------
!  CALL FVSSTD TO PROCESS THE CUTLIST FOR STAND TABLE DEVELOPMENT.
!----------
CALL FVSSTD (2)
!----------
! RESET YARD LOSS ACCUMULATOR TO 0.
!----------
DO 1710 I=1,MAXTRE
YRDLOS(I)=0. &
     &ONTINUE
!----------
!  PROCESS THE VISUALIZATION FOR CUTS
!----------
CALL SVCUTS (IVAC,SSNG,DSNG,CTCRWN)
!----------
!  IF CHEAPO WAS REQUESTED CALL **ECREMS**
!----------
IF (LECON) CALL ECREMS
!----------
!  DETERMINE SPECIES-TREE CLASS COMPOSITION FOR REMOVED TREES,
!  REMOVED VOLUME, AND RESIDUAL TREES.
!----------
CALL COMP(OSPTT,IOSPTT,SPCRT)
CALL COMP(OSPTV,IOSPTV,SPCRC)
CALL COMP(OSPBR,IOSPBR,SPCBR)
CALL COMP(OSPMR,IOSPMR,SPCMR)
CALL COMP(OSPSR,IOSPSR,SPCSR)
!----------
!  COMPUTE PERCENTILE POINTS IN THE DISTRIBUTION OF REMOVED TREES.
!----------
CALL PCTILE(ITRN,IND,WK3,PCT,ONTREM(7))
CALL DIST(ITRN,ONTREM,PCT)
!----------
!  COMPUTE PERCENTILE POINTS IN THE DISTRIBUTION OF REMOVED VOLUME.
!----------
CALL PCTILE(ITRN,IND,WK2,PCT,OCVREM(7))
CALL DIST(ITRN,OCVREM,PCT)
IF(CMCUT.LE.0.0) GO TO 1750
CALL PCTILE(ITRN,IND,WK5,PCT,OMCREM(7))
CALL DIST(ITRN,OMCREM,PCT)
CALL PCTILE(ITRN,IND,WK7,PCT,OSCREM(7))
CALL DIST(ITRN,OSCREM,PCT) &
     &ONTINUE
IF(BFCUT.LE.0.0) GO TO 1800
CALL PCTILE(ITRN,IND,WK6,PCT,OBFREM(7))
CALL DIST(ITRN,OBFREM,PCT) &
     &ONTINUE
!----------
!  COMPUTE PERCENTILE POINTS IN THE DISTRIBUTION OF REMOVED CARBON AND BIOMASS.
!----------
IF(LFIANVB) THEN
  CALL PCTILE(ITRN,IND,WK8,PCT,OAGBIOREM(7))
  CALL DIST(ITRN,OAGBIOREM,PCT)
  CALL PCTILE(ITRN,IND,WK9,PCT,OAGCARBREM(7))
  CALL DIST(ITRN,OAGCARBREM,PCT)
  CALL PCTILE(ITRN,IND,WK10,PCT,OMERBIOREM(7))
  CALL DIST(ITRN,OMERBIOREM,PCT)
  CALL PCTILE(ITRN,IND,WK11,PCT,OMERCARBREM(7))
  CALL DIST(ITRN,OMERBIOREM,PCT)
  CALL PCTILE(ITRN,IND,WK12,PCT,OCSAWBIOREM(7))
  CALL DIST(ITRN,OCSAWBIOREM,PCT)
  CALL PCTILE(ITRN,IND,WK13,PCT,OCSAWCARBREM(7))
  CALL DIST(ITRN,OCSAWCARBREM,PCT)
  CALL PCTILE(ITRN,IND,WK14,PCT,OFOLIBIOREM(7))
  CALL DIST(ITRN,OFOLIBIOREM,PCT)
  CALL PCTILE(ITRN,IND,WK15,PCT,OFOLICARBREM(7))
  CALL DIST(ITRN,OFOLICARBREM,PCT)
ENDIF
!----------
!  REPLACE MAXIMUM DIAMETER IN DISTRIBUTIONS FOR REMOVED TREES AND
!  REMOVED VOLUME WITH DMAX.
!----------
ONTREM(6)=DMAX
OCVREM(6)=DMAX
OMCREM(6)=DMAX
OSCREM(6)=DMAX
OBFREM(6)=DMAX
!----------
!  CALL FIRE MODEL TO UPDATE SNAGS before TREES RECORDS ARE DELETED
!----------
IF (DEBUG) WRITE (JOSTND,'('' CUTS: CALLING FMSCUT.'')')
CALL FMSCUT(SPCRC,MAXSP,3,SSNG,DSNG,CTCRWN,TKCRWN)
!----------
!     SAVE REMOVALS FOR PROCESSING WITH THE TREEBIO EM FUNCTION.
!----------
CALL FMTREM(DSNG,SSNG,TKCRWN)
!----------
!  IF SOME OR ALL OF THE TREES ARE COMPLETELY CUT, THEN:
!  DELETE THE CUT TREE RECORDS.
!----------
IF(DEBUG) WRITE (JOSTND,9090) IVAC,ITRN &
     &ORMAT (/' IN CUTS, TOTALLY CUT TREES=',I5,'; TOT TREES=',I5)
IF (IVAC.LE.0) GO TO 1850
CALL TREDEL (IVAC,IND2)
CALL SPESRT
IFST=1
IF (ITRN.LE.0) GO TO 1900
IND(1)=0
CALL RDPSRT(ITRN,DBH,IND,.TRUE.) &
     &ONTINUE
!----------
!  COMPUTE PERCENTILE POINTS IN THE DISTRIBUTION OF RESIDUAL TREES.
!----------
CALL PCTILE(ITRN,IND,PROB,PCT,ONTRES(7)) &
     &ONTINUE
CALL DIST(ITRN,ONTRES,PCT)
CALL COMP(OSPRT,IOSPRT,SPCRES) &
     &ONTINUE
IF (ITRN.LE.0 .OR. (.NOT.LAUTON.OR.LNOAUT)) GO TO 2000
LNOAUT=.TRUE.
IACTK=221
NTODO=1
IF (DEBUG) WRITE (JOSTND,9100) &
     &ORMAT (' CUTS: THINAUTO IS BEING ATTEMPTED')
GO TO 50 &
     &ONTINUE
!----------
! IF WE HAD AN FFE SALVAGE REMOVAL, BUT NO LIVE TREE REMOVALS, THE
!  "POST-THIN" SVS FILE HAS NOT BEEN CREATED--DO IT NOW.
!----------
IF (DEBUG) THEN
   WRITE(JOSTND,2005) SALVTPA, TCUT
2005    FORMAT(' ','CUTS: TESTING FOR SALVAGE W/O CUT: SALVTPA=',F7.2, &
                 ', TCUT=',F7.2)
ENDIF
IF ( SALVTPA .GT. 0.0 .AND. TCUT .LE. 0.0 ) THEN
   CALL SVOUT(IY(ICYC),2,'Post salvage')
ENDIF
!----------
! PROCESS ANY PRUNING REQUESTS.
!----------
CALL OPFIND(1,MYACTS(23),NTODO)
IF (DEBUG) WRITE (JOSTND,2010) NTODO,ITRN &
     &ORMAT (' CUTS: PRUNE, NTODO=',I4,' ITRN=',I4)
IF(NTODO .LE. 0)GO TO 2500
DO 2490 NPRUN=1,NTODO
CALL OPGET(NPRUN,7,KDT,IACTK,NP,PRMS)
IF(IACTK.LT.0)GO TO 2490
!
! IF NO TREES REMAIN AFTER THINNINGS, CANCEL PRUNING.
! OTHERWISE, INITIALIZE PRUNING PARAMETERS.
!
IF(ITRN.LE.0) THEN
   CALL OPDEL1(NPRUN)
   GO TO 2490
ELSE
   IPRUN=0
   IMETH=IFIX(PRMS(1))
   FEET=PRMS(2)
   PPROP=PRMS(3)
   ISPEC=INT(PRMS(4))
   DLOW=PRMS(5)
   DHI=PRMS(6)
   IF (DEBUG) WRITE (JOSTND,2020) IMETH,FEET,PPROP,ISPEC,DLOW,DHI
2020    FORMAT (' CUTS: PRUNE, IMETH=',I2,' FEET=',F7.2,' PPROP=', &
              F7.2,' ISPEC=',I3,' DLOW=',F7.2,' DHI=',F7.2)
ENDIF
!
! ZERO OUT THE CTCRWN VECTOR...IT KEEPS TRACK OF THE PROPORTION OF THE
! CROWN THAT IS BEING PRUNED AND REPORTS THIS TO THE FUELS&FIRE MODEL.
!
DO I=1,ITRN
   CTCRWN(I)=0.
ENDDO
!----------
! LOOP THROUGH TREES AND ATTEMPT PRUNING.
!----------
DO 2480 I=1,ITRN
!----------
!  SET LINCL
!----------
LINCL = .FALSE.
IF(ISPEC.EQ.0 .OR. ISPEC.EQ.ISP(I))THEN
  LINCL = .TRUE.
ELSEIF(ISPEC.LT.0)THEN
  IGRP = -ISPEC
  IULIM = ISPGRP(IGRP,1)+1
  DO 2021 IG=2,IULIM
  IF(ISP(I) .EQ. ISPGRP(IGRP,IG))THEN
    LINCL = .TRUE.
    GO TO 2022
  ENDIF
2021   CONTINUE
ENDIF &
     &ONTINUE
!----------
! SKIP TREE IF IT DOES NOT MATCH SPECIFIED SPECIES OR SIZE
!----------
IF(.NOT.LINCL) GO TO 2480
IF(DBH(I).LT.DLOW .OR. DBH(I).GE.DHI) GO TO 2480
!
!  COMPUTE CROWN LENGTH AND HEIGHT TO BASE OF CROWN.
!
IOLDCR=ICR(I)
HTI=HT(I)
CRI=FLOAT(ICR(I))
CRLEN=HTI*CRI/100.
CRBASE=HTI-CRLEN
!
! METHOD 1: PRUNE TO A SPECIFIED HEIGHT.
!
IF(IMETH.EQ.1 .AND. FEET.GT.0.)THEN
  IF(FEET .GT. CRBASE) THEN
    ICR(I)=IFIX( ((HTI-FEET)/HTI)*100. + 0.5 )
    IF (ICR(I).LT. 5 .AND. IOLDCR.GT. 5) ICR(I)=5
    IPRUN=IPRUN+1
  ENDIF
!
! METHODS 2 & 3: PRUNE TO A SPECIFIED HEIGHT SUBJECT TO A MAXIMUM
! CROWN RATIO REMOVAL PERCENTAGE.  IF IN PRUNING TO THE SPECIFIED
! HEIGHT, THE CR REMOVAL PERCENTAGE WOULD BE EXCEEDED:
! METHOD 2 -- ONLY REMOVE ENOUGH CROWN TO REACH THE REMOVAL PERCENT.
! METHOD 3 -- DO NOT REMOVE ANY CROWN FROM THE TREE.
!
ELSEIF((IMETH.EQ.2 .OR. IMETH.EQ.3) .AND. &
           FEET.GT. 0. .AND. PPROP.GT.0.) THEN
  IF(FEET .GT. CRBASE) THEN
    FTCUT=FEET-CRBASE
    CUTMAX=CRLEN*PPROP
    IF(FTCUT .LE. CUTMAX)THEN
!
! CR REMOVAL PERCENTAGE NOT EXCEEDED
!
      ICR(I)=IFIX( ((HTI-FEET)/HTI)*100. + 0.5 )
      IPRUN=IPRUN+1
    ELSE
!
! CR REMOVAL PERCENTAGE EXCEEDED
!
      IF(IMETH .EQ. 2) THEN
        ICR(I)=IFIX( ((CRLEN-CUTMAX)/HTI)*100. + 0.5 )
        IPRUN=IPRUN+1
      ENDIF
    ENDIF
  ENDIF
!
! METHOD 4: REMOVE A SPECIFIED PROPORTION OF EVERY TREES CROWN.
!
ELSEIF(IMETH.EQ.4 .AND. PPROP.GT.0.)THEN
  ICR(I)=IFIX( CRI*(1.0-PPROP) + 0.5 )
  IPRUN=IPRUN+1
!
! METHOD 5: REMOVE A SPECIFIED LENGTH OF CROWN FROM EVERY TREE.
!
ELSEIF(IMETH.EQ.5 .AND. FEET.GT.0.)THEN
  ICR(I)=IFIX( ((CRLEN-FEET)/HTI)*100. + 0.5 )
  IF (ICR(I).LT. 5 .AND. IOLDCR.GT. 5) ICR(I)=5
  IPRUN=IPRUN+1
!
! METHODS 6 & 7: REMOVE A SPECIFIED LENGTH OF CROWN SUBJECT TO A
! MAXIMUM CR REMOVAL PERCENTAGE.  IF IN PRUNING THE SPECIFIED
! LENGTH, THE CR REMOVAL PERCENTAGE WOULD BE EXCEEDED:
!  METHOD 6 -- ONLY REMOVE ENOUGH CROWN TO REACH THE REMOVAL PERCENT.
!  METHOD 7 -- DO NOT REMOVE ANY CROWN FROM THE TREE.
!
ELSEIF((IMETH.EQ.6 .OR. IMETH.EQ.7) .AND. &
           FEET .GT. 0. .AND. PPROP.GT.0.) THEN
  CUTMAX=CRLEN*PPROP
  IF(FEET .LE. CUTMAX) THEN
!
! CR REMOVAL PERCENTAGE NOT EXCEEDED.
!
    ICR(I)=IFIX( ((CRLEN-FEET)/HTI)*100. + 0.5 )
    IPRUN=IPRUN+1
  ELSE
!
! CR REMOVAL PERCENTAGE WOULD BE EXCEEDED.
!
    IF(IMETH .EQ. 6) THEN
      ICR(I)=IFIX( ((CRLEN-CUTMAX)/HTI)*100. + 0.5 )
      IPRUN=IPRUN+1
    ENDIF
  ENDIF
ENDIF
BASNEW=(1.-(FLOAT(ICR(I))*.01))*HTI
CTCRWN(I)=AMAX1(0.,1.-((HTI-BASNEW)/(HTI-CRBASE)))
IF(DEBUG)WRITE(JOSTND,2040) I,IOLDCR,ICR(I),IOLDCR-ICR(I), &
           CRBASE,BASNEW,CTCRWN(I) &
     &ORMAT (' CUTS: PRUNE, I=',I4,' IOLDCR=',I3,' ICR=',I3, &
           ' DIFF=',I3,' OLD&NEW BASE HT=',2F7.1,' CTCRWN=',F6.3) &
     &ONTINUE
!
!  IF ANY PRUNING WAS DONE, MARK REQUEST DONE AND PASS THE PRUNED MATERIAL
!  TO THE DEBRIS POOLS.
!  IF NOT, DELETE THE REQUEST.
!
IF(IPRUN .GT. 0) THEN
  CALL FMPRUN(CTCRWN)
  CALL OPDONE(NPRUN,IY(ICYC))
ELSE
  CALL OPDEL1(NPRUN)
ENDIF
IF(DEBUG)WRITE(JOSTND,2050) IPRUN &
     &ORMAT (' CUTS: PRUNE, IPRUN=',I4) &
     &ONTINUE
!----------
! END OF PRUNING SEGMENT
!----------
     &ONTINUE
!----------
!  IF CHEAPO WAS REQUESTED CALL **ECOUT**
!----------
IF (LECON) CALL ECOUT
!
!
RETURN
END
