SUBROUTINE EVTSTV (IUSERV)
IMPLICIT NONE
!----------
! VBASE $Id$
!----------
!
!     CALLED FROM EVMON, LOADS AND MAINTAINS THE TEST VARIABLE TABLES.
!
!     EVENT MONITOR ROUTINE - NL CROOKSTON - AUG 1982 - MOSCOW, ID
!
!     IUSERV=0 FOR NORMAL CALLS AND 1 WHEN THIS ROUTINE IS BEING ASKED
!            TO JUST COMPUTE THE USER DEFINED VARIABLES. IF GT 1, THEN
!            THIS IS A YEAR AND USER DEFINED VARIABLES ONLY SCHEDULED
!            EXACTLY FOR THE YEAR ARE COMPUTED.
!            IF LT 0, THEN ONLY DEFINE TYPE 1 VARIABLES.
!
!     ENTRY POINTS:
!     EVTSTV CALLED BY EVMON, AS STATED ABOVE.
!     EVSET4 CALLED BY VARIOUS ROUTINES TO SAVE SPECIFIC VARIABLES.
!     EVUST4 CALLED BY VARIOUS ROUTINES TO SET THE STATUS OF A
!            VARIABLE TO UNSET.
!     EVGET4 CALLED TO GET THE VALUE OF A STORED VARIABLE.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'OPCOM.f90'
!
!
INCLUDE 'OUTCOM.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'SUMTAB.f90'
!
!
INCLUDE 'VARCOM.f90'
!
!
!OMMONS
!
LOGICAL LDEB,LDEB2,LSET
INTEGER MYACT(3)
REAL PRM(3)
INTEGER IUSERV,I,IDMR,NTODO,ITODO,NP,IACTK,IDAT,ITS5,LOCOD,IRC
INTEGER ISET,IVAL
REAL VSET,VALUE,X,TADWBA,CURVOL,ZERO,AGE,DMRSUM,PRBSUM,FINDX,CRD
REAL TAHWBA,VALUE2
!
DATA MYACT/33,101,102/
!
!     SEE IF WE NEED WRITE DEBUG.
!
CALL DBCHK (LDEB,'EVTSTV',6,ICYC)
!
!     THE VARIABLES FOR EACH GROUP ARE DEFINED AS FOLLOWS:
!
!     GROUP 1, SET IN PHASE 1 AND ALWAYS KNOWN.
!
!     101 YEAR      BEGINNING CYCLE YEAR.
!     102 AGE       AGE AT CYCLE BEGINNING YEAR.
!     103 BTPA      BEFORE THIN TREES PER ACRE
!     104 BTCUFT    BEFORE THIN TOTAL CUFT
!     105 BMCUFT    BEFORE THIN MERCH CUFT
!     106 BBDFT     BEFORE THIN BD FOOT VOL
!     107 BBA       BEFORE THIN BASAL AREA
!     108 BCCF      BEFORE THIN CCF
!     109 BTOPHT    BEFORE THIN AVERAGE DOM HT
!     110 BADBH     BEFORE THIN QUADRATIC MEAN DBH
!     111 YES       A CONSTANT EQUAL TO 1.
!     112 NO        A CONSTANT EQUAL TO 0.
!     113 CYCLE     CYCLE NUMBER.
!     114 NUMTREES  NUMBER OF TREE RECORDS.
!     115 BSDIMAX   BEFORE THIN SDI MAX
!     116 BSDI      BEFORE CUT STAND DENSITY INDEX.
!     117 BRDEN     BEFORE CUT RELATIVE DENSITY (CURTIS)
!     118 BRDEN2    BEFORE CUT RELATIVE DENSITY (SILVAH)
!     119 BHTWTBA   BEFORE THIN HEIGHT WEIGHTED BY BA
!
!     120 BSCUFT    BEFORE THIN CUBIC SAW VOLUME CUFT
!
!     126 HABTYPE   STAND HABITAT TYPE AS USED BY THE MODEL.
!     127 SLOPE     STAND SLOPE CODE (RECODED FROM INPUT).
!     128 ASPECT    STAND ASPECT CODE (RECODED FROM INPUT, CONVERTED
!                   TO RADIANS IN TRNASP.F AND INTO DEGREES(IASPEC)HERE.
!     129 ELEV      STAND ELEV CODE (RECODED FROM INPUT).
!     130 SAMPWT    STAND SAMPLING WEIGHT.
!     131 INVYEAR   INVENTORY YEAR.
!     132 CENDYEAR  END YEAR OF CURRENT CYCLE.
!     133 EVPHASE   EVENT MONITOR PHASE NUMBER.
!     134 SMR       STAND MISTLETOE RATING
!     135 SITE      STAND SITE INDEX FOR SITE SPECIES
!     136 CUT       0, BEFORE CUT OR IF STAND IS NOT CUT, 1 IF
!                   STAND IS CUT (CAN ONLY BE 1.0 AFTER CUTS, PHASE 2).
!     137 LAT       STAND LATITUDE (RECORDED FROM INPUT).
!     138 LONG      STAND LONGITUDE (RECORDED FROM INPUT).
!     139 STATE     STAND LOCATION, STATE (RECORDED FROM INPUT)
!     140 COUNTY    STAND LOCATION, COUNTY (RECORDED FROM INPUT)
!     141 FORTYP    FOREST TYPE CODE BASED ON FIA NATIONAL ALGORITHM
!     142 SIZCLS    STAND SIZE CLASS BASED ON FIA NATIONAL ALGORITHM
!     143 STKCLS    STOCKING CLASS BASED ON FIA NAIONAL ALGORITHM
!     144 PROPSTK   PROPORTION OF THE STAND CONSIDERED STOCKABLE
!     145 MAI       MEAN ANNUAL INCREMENT, BEGINNING OF CYCLE
!     146 AGECMP    STAND AGE COMPUTED FROM SIZE CLASS AND ABIRTH
!     147 BDBHWTBA  BEFORE CUT AVERAGE DBH OF OVERSTORY TREES (FOR INFORMS)
!     148 SILVAHFT  FOREST TYPE ACCORDING TO SILVAH DEFINITIONS
!     149 FISHERIN  R5 FISHER HABITAT SUITABILITY INDEX
!     150 BSDI2     ZEIDE SUMMATION BEFORE CUT STAND DENSITY INDEX.
!
!     BIOMASS AND CARBON MEASURES ADDED SEPTEMBER 2024
!     151 BABVBIO   BEFORE THIN ABOVE GROUND BIOMASS
!     152 BMERBIO   BEFORE THIN MERCHANTABLE BIOMASS
!     153 BSAWBIO   BEFORE THIN CUBIC SAWLOG BIOMASS
!     154 BFOLBIO   BEFORE THIN FOLIAGE BIOMASS
!     155 BABVCRB   BEFORE THIN ABOVE GROUND CARBON
!     156 BMERCRB   BEFORE THIN MERCHANTABLE CARBON
!     157 BSAWCRB   BEFORE THIN CUBIC SAWLOG CARBON
!     158 BFOLCRB   BEFORE THIN FOLIAGE CARBON
!
!     159  BGMD BEFORE THIN GENERALIZED MEAN DIAMETER (REINEKE'S DIAMETER) -- FEB 2026
!
!     GROUP 2, SET IN PHASE 2, AFTER THIN.
!
!     201 ATPA      AFTER THIN TREES PER ACRE
!     202 ATCUFT    AFTER THIN TOTAL CUFT
!     203 AMCUFT    AFTER THIN MERCH CUFT
!     204 ABDFT     AFTER THIN BOARD FOOT VOL.
!     205 ABA       AFTER THIN BASAL AREA
!     206 ACCF      AFTER THIN CCF
!     207 ATOPHT    AFTER THIN AVERAGE DOM HT
!     208 AADBH     AFTER THIN QUADRATIC MEAN DBH.
!     209 RTPA      REMOVED TREES PER ACRE
!     210 RTCUFT    REMOVED TOTAL CUFT
!     211 RMCUFT    REMOVED MERCH CUFT
!     212 RBDFT     REMOVED BDFT
!     213 ASDIMAX   AFTER THIN SDI MAX
!     214 ASDI      AFTER THIN STAND DENSITY INDEX
!     215 ARDEN     AFTER THIN RELATIVE DENSITY (CURTIS)
!     216 ADBHWTBA  AFTER CUT AVERAGE DBH OF OVERSTORY TREES (FOR INFORMS)
!     217 ARDEN2    AFTER THIN RELATIVE DENSITY (SILVAH)
!     218 ASDI2     ZEIDE SUMMATION AFTER THIN STAND DENSITY INDEX
!     219 AHTWTBA   AFTER THIN HEIGHT WEIGHTED BY BA
!
!     220 ASCUFT    AFTER THIN THIN SAW LOG MERCH CUFT
!     221 RSCUFT    REMOVED SAW LOG MERCH CUFT
!
!     BIOMASS AND CARBON MEASURES ADDED SEPTEMBER 2024
!     222 AABVBIO   AFTER THIN ABOVE GROUND BIOMASS
!     223 RABVBIO   REMOVED ABOVE GROUND BIOMASS
!     224 AMERBIO   AFTER THIN MERCHANTABLE BIOMASS
!     225 RMERBIO   REMOVED MERCHANTABLE BIOMASS
!     226 ASAWBIO   AFTER THIN CUBIC SAWLOG BIOMASS
!     227 RSAWBIO   REMOVED CUBIC SAWLOG BIOMASS
!     228 AABVCRB   AFTER THIN ABOVE GROUND CARBON
!     229 RABVCRB   REMOVED ABOVE GROUND CARBON
!     230 AMERCRB   AFTER THIN MERCHANTABLE CARBON
!     231 RMERCRB   REMOVED MERCHANTABLE CARBON
!     232 ASAWCRB   AFTER THIN CUBIC SAWLOG CARBON
!     233 RSAWCRB   REMOVED CUBIC SAWLOG CARBON
!     234 AFOLBIO   AFTER THIN FOLIAR BIOMASS
!     235 RFOLBIO   REMOVED FOLIAR BIOMASS
!     236 AFOLCRB   AFTER THIN FOLIAR CARBON
!     237 RFOLCRB   REMOVED FOLIAR CARBON
!
!   238  AGMD AFTER THIN GENERALIZED MEAN DIAMETER (REINEKE'S DIAMETER) -- FEB 2026
!
!     GROUP 3, THOSE KNOWN AFTER CYCLE 1.
!
!     301 ACC       ACCREATION FROM LAST CYCLE
!     302 MORT      MORTALITY FROM LAST CYCLE
!     303 PAI       PERIODIC ANNUAL INCREMENT, BEGINNING OF CYCLE
!     304 VACANT SPOT --- USED TO BE MAI WHICH IS NOW A TYPE 1 VARIABLE
!     305 DTPA      DELTA TPA, CHANGE IN TREES PER ACRE FROM LAST CYCLE
!     306 DTPA%     DELTA TPA IN PERCENT
!     307 DBA       DELTA BASAL AREA
!     308 DBA%      DELTA BA IN PERCENT
!     309 DCCF      DELTA CCF
!     310 DCCF%     DELTA CCF IN PERCENT
!     311 ORG%CC    ORGANON PERCENT CANOPY COVER (OC AND OP VARIANTS)
!     312 ORGAHT    ORGANON AVERAGE HEIGHT OF THE TOP 40 TREES OF BIG-6 SPECIES.
!
!     GROUP 4, THOSE KNOWN WHEN THE SETTING ROUTINE SAYS SO, AND
!     NOT KNOWN THE REST OF THE TIME.
!
!     401 TM%STND   PERCENT STAND DEFOLIATION CAUSED BY TUSSOCK MOTH
!     402 TM%DF     PERCENT DOUGLAS-FIR DEF. CAUSED BY TM
!     403 TM%GF     PERCENT GRAND FIR DEF. CAUSED BY TM
!     404 MPBTPAK   TREES PER ACRE KILLED BY MOUNTAIN PINE BEETLE (MP)
!     405 BW%STND   PERCENT STAND DEFOLIATION CAUSED BY BUDWORM (BW)
!     406 MPBPROB   PROBABILITY OF MPB OUTBREAK
!     407-415       vacant
!     416 BSCLASS   BEFORE THIN STRUCTURAL CLASS (MUST HAVE STRCLASS ON)
!     417 ASCLASS   AFTER THIN STRUCTURAL CLASS (MUST HAVE STRCLASS ON)
!     418 BSTRDBH   BEFORE THIN DBH OF UPPERMOST STRATUM (STRCLASS ON)
!     419 ASTRDBH   AFTER THIN DBH OF UPPERMOST STRATUM (STRCLASS ON)
!     420 FIRE      0 IF STAND HAS NO FIRE, 1 IF FIRE OCCURS (FM)
!     421 MINSOIL   PERCENTAGE OF MINERAL SOIL EXPOSURE; -1 INITIALLY (FM)
!     422 CROWNIDX  CROWNING INDEX FROM POTENTIAL FIRE REPT (FM)
!     423 FIREYEAR  CALENDAR YEAR OF LAST FIRE; -1 INITIALLY (FM)
!     424 BCANCOV   BEFORE THIN CANOPY COVER (STRCLASS ON)
!     425 ACANCOV   AFTER THIN CANOPY COVER (STRCLASS ON)
!     426 CRBASEHT  CROWN BASE HT FROM POTENTIAL FIRE REPT (FM)
!     427 TORCHIDX  TORCHING INDEX FROM POTENTIAL FIRE REPT (FM)
!     428 CRBULKDN  CROWN BULK DENSITY FROM POTENTIAL FIRE REPT (FM)
!     430 DISCCOST  DISCOUNTED TOTAL ACCUMULATED COSTS (ECON)
!     431 DISCREVN  DISCOUNTED TOTAL ACCUMULATED REVENUES (ECON)
!     432 FORSTVAL  PRESENT VALUE OF FOREST, LAND AND TREES (ECON)
!     433 HARVCOST  UNDISCOUNTED TOTAL HARVEST COSTS (ECON)
!     434 HARVREVN  UNDISCOUNTED TOTAL HARVEST REVENUES (ECON)
!     435 IRR       INTERNAL RATE OF RETURN (ECON)
!     436 PCTCOST   UNDISCOUNTED TOTAL PRE-COMMERCIAL THINNING COSTS (ECON)
!     437 PNV       PRESENT NET VALUE (ECON)
!     438 RPRODVAL  PRESENT VALUE OF TREES OR REPRODUCTION (ECON)
!     439 SEV       COMPUTED SOIL EXPECTATION VALUE (ECON)
!     440 BMAXHS    BEFORE THIN TALLEST HT, UPPERMOST STRATUM (STRCLASS)
!     441 AMAXHS    AFTER THIN TALLEST HT, UPPERMOST STRATUM  (STRCLASS)
!     442 BMINHS    BEFORE THIN SHORTEST HT, UPPERMOST STRATUM(STRCLASS)
!     443 AMINHS    AFTER THIN SHORTEST HT, UPPERMOST STRATUM (STRCLASS)
!     444 BNUMSS    BEFORE THIN TOTAL NUMBER OF STRATUM       (STRCLASS)
!     445 ANUMSS    AFTER THIN TOTAL NUMBER OF STRATUM        (STRCLASS)
!     446 DISCRATE  DISCOUNT RATE (ECON)
!     447 UNDISCST  UNDISCOUNTED TOTAL ACCUMULATED COSTS (ECON)
!     448 UNDISRVN  UNDISCOUNTED TOTAL ACCUMULATED REVENUES (ECON)
!     449 ECCUFT    CUBIC FEET VALUED BY ECON (ECON)
!     450 ECBDFT    BOARD FEET VALUED BY ECON (ECON)
!
!
!     GROUP 5 ARE USER DEFINED.
!
!
IF (LDEB) WRITE (JOSTND,1) IUSERV,ICYC,GROSPC,BA,RMSQD
1 FORMAT (' IN EVTSTV,IUSERV=',I4,' ICYC=',I4,' GROSPC=',F5.3, &
     & ' BA=',F7.3,' RMSQD=',F6.3)
IF (IUSERV.GE.1) GOTO 20
!
!     LOAD VARIABLES IN GROUP ONE, THOSE SET IN PHASE 1 AND ALWAYS KNOWN
!
IF (IUSERV.LT.0) THEN
  IPHASE=1
  BTSDIX=0
  SDIBC=0
  SDIBC2=0
ELSE
  IF (IPHASE.GT.1) GOTO 10
ENDIF
IF (LDEB) WRITE (JOSTND,91) IPHASE,ICYC
91 FORMAT (' IN EVTSTV,IPHASE,ICYC=',2I4)
TSTV1(1)=IY(MAX(1,ICYC))
TSTV1(2)=IAGE+IY(MAX(1,ICYC))-IY(1)
IF(LDEB)WRITE(JOSTND,*)' ICYC,IAGE,IY(ICYC),IY(1),TSTV102= ', &
     & ICYC,IAGE,IY(MAX(1,ICYC)),IY(1),TSTV1(2)
TSTV1(3)=TPROB/GROSPC
TSTV1(4)=OCVCUR(7)/GROSPC
TSTV1(5)=OMCCUR(7)/GROSPC
TSTV1(6)=OBFCUR(7)/GROSPC
TSTV1(20)=OSCCUR(7)/GROSPC
TSTV1(7)=BA/GROSPC
TSTV1(51)=(OAGBIOCUR(7)/GROSPC)/2000
TSTV1(52)=(OMERBIOCUR(7)/GROSPC)/2000
TSTV1(53)=(OCSAWBIOCUR(7)/GROSPC)/2000
TSTV1(54)=(OFOLIBIO(7)/GROSPC)/2000
TSTV1(55)=(OAGCARBCUR(7)/GROSPC)/2000
TSTV1(56)=(OMERCARBCUR(7)/GROSPC)/2000
TSTV1(57)=(OCSAWCARBCUR(7)/GROSPC)/2000
TSTV1(58)=(OFOLICARB(7)/GROSPC)/2000
TSTV1(8)=RELDEN
TSTV1(9)=AVH
TSTV1(10)=RMSQD
TSTV1(11)=1.0
TSTV1(12)=0.0
TSTV1(13)=ICYC
TSTV1(14)=ITRN
TSTV1(15)=BTSDIX
TSTV1(16)=SDIBC
TSTV1(59)=DR016
IF(RMSQD .EQ. 0.)THEN
  TSTV1(17)=0.
ELSE
  TSTV1(17)=TSTV1(7)/(TSTV1(10)**0.5)
ENDIF
CALL RDCLS2(0,0.,999.,1,CRD,0)
TSTV1(18)=CRD/GROSPC
DO 6 I=1,MAXSP
BCCFSP(I)=RELDSP(I)
6 CONTINUE
IF (ICYC.LE.1) THEN
   TSTV1(27)=ISLOP
   TSTV1(28)=IASPEC
   TSTV1(29)=ELEV*100.
   TSTV1(30)=SAMWT
   TSTV1(31)=IY(1)
   TSTV1(37)=TLAT
   TSTV1(38)=TLONG
   TSTV1(39)=ISTATE
   TSTV1(40)=ICNTY
ENDIF
TSTV1(26)=ICL5
TSTV1(32)=IY(MAX(1,ICYC)+1)-1
TSTV1(33)=IPHASE
TSTV1(34)=0.0
TSTV1(41)=IFORTP
TSTV1(42)=ISZCL
TSTV1(43)=ISTCL
TSTV1(44)=1./GROSPC
TSTV1(45)=0. !initialize so debug output is consistent.
TSTV1(46)=ICAGE
TSTV1(47)=0. !initialize so debug output is consistent.
TSTV1(19)=0. !initialize so debug output is consistent.
TSTV1(48)=ISILFT
CALL FISHER(FINDX)
TSTV1(49)=FINDX
TSTV1(50)=SDIBC2
IF(ITRN .GE. 1) THEN
  PRBSUM=0.
  DMRSUM=0.
  DO 7 I=1,ITRN
  CALL MISGET (I,IDMR)
  PRBSUM=PRBSUM+PROB(I)
  DMRSUM=DMRSUM+FLOAT(IDMR)*PROB(I)
7   CONTINUE
  IF(PRBSUM .LT. 0.000001)THEN
    TSTV1(34)=0.
  ELSE
    TSTV1(34)=DMRSUM/PRBSUM
  ENDIF
ENDIF
IF (ISISP.GT.0) THEN
   TSTV1(35)=STNDSI
ELSE
   TSTV1(35)=0.0
ENDIF
TSTV1(36)=0.
IF (LDEB) WRITE (JOSTND,92) (I,TSTV1(I),I=1,50)
92 FORMAT (' TSTV1='/10(I3,E11.3))
IF (IUSERV.LT.0) RETURN
!----------
!  MAI LOGIC
!  MAIFLG IS 1 WHEN: 1) INITIAL STAND AGE IS 0 AND INITIAL TPA IS NOT 0,
!  OR 2) STAND AGE GETS RESET TO 0 AND THE STAND WAS NOT CLEARCUT.
!  NEWSTD IS 1 WHEN A NEW STAND IS INITIATED SUCH AS AFTER CLEARCUTTING
!  OR IN A BARE GROUND PLANT SCENARIO.
!  IF MAIFLG IS 1 AND NEWSTD IS 0, THE MAI CALCULATION IS SHUT OFF.
!
!  LOAD CYCLE 1 MAI VALUE FOR THE SUMMARY TABLE OUTPUT
!
IF(ICYC.EQ.1) THEN
  IF(TSTV1(2).GT.0.)THEN
    SELECT CASE (VARACD)
!            CASE ('CS','LS','NE','SN','ON')
!              BCYMAI(ICYC)=IOSUM(4,ICYC)/TSTV1(2)
      CASE DEFAULT
        BCYMAI(ICYC)=IOSUM(5,ICYC)/TSTV1(2)
    END SELECT
  ELSE
    BCYMAI(ICYC)=0.
!
!  AGE AT BEGINNING IS 0. IF TPA IS ALSO ZERO, SET NEW STAND FLAG TO 1,
!  IF TPA IS NOT ZERO, SET MAIFLG TO 1 TO SHUT OFF MAI CALCULATION.
!
    IF(TSTV1(3).EQ.0.)THEN
      NEWSTD=1
    ELSE
      MAIFLG=1
    ENDIF
  ENDIF
  TSTV1(45)=BCYMAI(ICYC)
  AGELST=TSTV1(2)
!
!  LOAD MAI FOR CYCLES 2 AND BEYOND. ZERO IS A VARIABLE TO TEST WHETHER
!  THE AGE HAS BEEN RESET TO ZERO. IN THIS CASE, START THE REMOVALS
!  ACCUMULATION OVER.
!
ELSE
  AGE = TSTV1(2)
  ZERO = AGE - (IY(ICYC)-IY(ICYC-1))
  IF(AGE .LT. AGELST) TOTREM = 0.0
  IF(LDEB)WRITE(JOSTND,*)' AGE,AGELST,TOTREM= ',AGE,AGELST,TOTREM
  IF(LDEB)WRITE(JOSTND,*)' ICYC,IAGE,MAIFLG,NEWSTD,VARACD= ', &
     & ICYC,IAGE,MAIFLG,NEWSTD,VARACD
!
!  IF AGE HAS BEEN RESET TO 0, OR INITIAL EXISTING STAND CAME IN WITH
!  A ZERO AGE, SET MAI TO ZERO. ALSO IF THE AGE WAS SET TO 0 AND A
!  CLEARCUT DID NOT HAPPEN, SET MAIFLG TO SHUT OFF MAI CALCULATIONS.
!
  IF(ZERO.EQ.0.0 .OR. (MAIFLG.EQ.1 .AND. NEWSTD.NE.1)) THEN
    BCYMAI(ICYC) = 0.
    IF(NEWSTD.EQ.0)MAIFLG = 1
    GO TO 11
  ENDIF
!
!  IN THE FOLLOWING CALCULATIONS, IF AGE WAS RESET DON'T INCLUDE LAST
!  CYCLES REMOVALS IN THE MAI CALCULATION.
!
  SELECT CASE (VARACD)
!           CASE ('CS','LS','NE','SN','ON')
!             CURVOL=IOSUM(4,ICYC)
!             IF(AGE .GT. AGELST)TOTREM=IOSUM(8,ICYC-1)+TOTREM
!             BCYMAI(ICYC)=(TOTREM + CURVOL )/AGE
!             IF(LDEB)WRITE(JOSTND,*)' CURVOL,TOTREM,AGE,BCYMAI= ',
!      &      CURVOL,TOTREM,AGE,BCYMAI(ICYC)
    CASE DEFAULT
      CURVOL=IOSUM(5,ICYC)
      IF(AGE .GT. AGELST)TOTREM=IOSUM(9,ICYC-1)+TOTREM
      BCYMAI(ICYC)=(TOTREM + CURVOL )/AGE
      IF(LDEB)WRITE(JOSTND,*)' CURVOL,TOTREM,AGE,BCYMAI= ', &
     & CURVOL,TOTREM,AGE,BCYMAI(ICYC)
  END SELECT
 11   CONTINUE
!
!  IF AFTER TREATMENT VALUES FROM PREVIOUS CYCLE SHOW A CLEARCUT,
!  SET NEW STAND FLAG AND START REMOVALS ACCUMULATION OVER.
!
  IF(LDEB)WRITE(JOSTND,*)' TSTV205,TSTV206,TSTV214,TSTV209= ', &
     & TSTV2(5),TSTV2(6),TSTV2(14),TSTV2(9)
  IF(TSTV2(5).EQ.0 .AND. TSTV2(6).EQ.0 .AND. &
     & TSTV2(14).EQ.0 .AND. TSTV2(9).GT.0) THEN
    NEWSTD = 1
    TOTREM = 0.0
  ENDIF
!
!  IF AGE WAS RESET TO ZERO AND TPA IS ZERO, SET NEW STAND FLAG.
!
  IF(ZERO .EQ. 0.0 .AND. TSTV1(3) .EQ. 0.0) NEWSTD=1
!
  TSTV1(45)=BCYMAI(ICYC)
  AGELST=AGE
ENDIF
!
!  END OF MAI LOGIC
!----------
TADWBA=0.
TAHWBA=0.
DO 60 I=1,ITRN
TADWBA = TADWBA + (DBH(I)**3.)*0.0054542*PROB(I)
60 CONTINUE
TSTV1(47)=0.
IF(BA.GT.0.0 .AND. GROSPC.GT.0.0) TSTV1(47)=(TADWBA/BA)
!      Add logic for BHTWTBA
TAHWBA=0.
DO I=1,ITRN
  TAHWBA = TAHWBA + HT(I)*(DBH(I)**2)*0.0054542*PROB(I)
END DO
TSTV1(19)=0
IF(BA.GT.0.0 .AND. GROSPC.GT.0.0) TSTV1(19)=(TAHWBA/BA)

!----------
!
!     IF PAST CYCLE 1, SET GROUP 3 VARIABLES, THOSE KNOWN IN PHASE 1,
!     ONLY AFTER CYCLE 1.
!
IF (ICYC.LE.1) GOTO 20
TSTV3(1)=IOSUM(15,ICYC-1)
TSTV3(2)=IOSUM(16,ICYC-1)
TSTV3(3)=TSTV3(1)-TSTV3(2)
TSTV3(4)=0.
TSTV3(5)=TPROB/GROSPC-FLOAT(IOSUM(3,ICYC-1))
TSTV3(6)=0.
X=FLOAT(IOSUM(3,ICYC-1))
IF (X.GT.0.) TSTV3(6)=TPROB/GROSPC/X*100.
TSTV3(7)=BA/GROSPC-FLOAT(IOLDBA(ICYC-1))
TSTV3(8)=0.
X=FLOAT(IOLDBA(ICYC-1))
IF (X.GT.0.) TSTV3(8)=BA/GROSPC/X*100.
TSTV3(9)=RELDEN/GROSPC-FLOAT(IBTCCF(ICYC-1))
TSTV3(10)=0.
X=FLOAT(IBTCCF(ICYC-1))
IF (X.GT.0.) TSTV3(10)=RELDEN/GROSPC/X*100.
!
!  ORGANON VARIABLES ORG%CC AND ORGAHT
!
CALL GETORGV (1,VALUE2)
TSTV3(11)=VALUE2
CALL GETORGV (2,VALUE2)
TSTV3(12)=VALUE2
!
IF (LDEB) WRITE (JOSTND,93) (TSTV3(I),I=1,12)
93 FORMAT (' TSTV3(1/12)=',12E10.3)
GOTO 20
10 CONTINUE
!
!     LOAD PHASE...A GROUP 1 VARIABLE THAT CHANGES BETWEEN PHASES
!
TSTV1(33)=IPHASE
TSTV1(48)=ISILFT
IF(ONTREM(7) .GT. 0.)THEN
  CALL FISHER(FINDX)
  TSTV1(49)=FINDX
ENDIF
!
!     LOAD GROUP 2 VALUES, THOSE KNOWN AFTER THIN EVERY CYCLE.
!
TSTV1(14)=ITRN
IF (ONTREM(7).GT.0.0) TSTV1(36)=1.0
TSTV2(1)=TPROB/GROSPC
TSTV2(5)=BA/GROSPC
TSTV2(6)=RELDEN
TSTV2(7)=AVH
TSTV2(8)=RMSQD
TSTV2(9)=ONTREM(7)/GROSPC
TSTV2(10)=OCVREM(7)/GROSPC
TSTV2(11)=OMCREM(7)/GROSPC
TSTV2(12)=OBFREM(7)/GROSPC
TSTV2(21)=OSCREM(7)/GROSPC
TSTV2(23)=(OAGBIOREM(7)/GROSPC)/2000
TSTV2(29)=(OAGCARBREM(7)/GROSPC)/2000
TSTV2(25)=(OMERBIOREM(7)/GROSPC)/2000
TSTV2(31)=(OMERCARBREM(7)/GROSPC)/2000
TSTV2(27)=(OCSAWBIOREM(7)/GROSPC)/2000
TSTV2(33)=(OCSAWCARBREM(7)/GROSPC)/2000
TSTV2(35)=(OFOLIBIOREM(7)/GROSPC)/2000
TSTV2(37)=(OFOLICARBREM(7)/GROSPC)/2000
TSTV2(38)=DR016

DO 16 I=1,MAXSP
ACCFSP(I)=RELDSP(I)
16 CONTINUE
TSTV2(13)=ATSDIX
TSTV2(14)=SDIAC
TSTV2(18)=SDIAC2
IF(RMSQD .EQ. 0.)THEN
  TSTV2(15)=0.
ELSE
  TSTV2(15)=TSTV2(5)/(TSTV2(8)**0.5)
ENDIF
TSTV2(2)=(OCVCUR(7)-OCVREM(7))/GROSPC
TSTV2(3)=(OMCCUR(7)-OMCREM(7))/GROSPC
TSTV2(4)=(OBFCUR(7)-OBFREM(7))/GROSPC
TSTV2(20)=(OSCCUR(7)-OSCREM(7))/GROSPC
!     AFTER THIN BIOMASS / CARBON
TSTV2(22)=((OAGBIOCUR(7)-OAGBIOREM(7))/GROSPC)/2000
TSTV2(28)=((OAGCARBCUR(7)-OAGCARBREM(7))/GROSPC)/2000
TSTV2(24)=((OMERBIOCUR(7)-OMERBIOREM(7))/GROSPC)/2000
TSTV2(30)=((OMERCARBCUR(7)-OMERCARBREM(7))/GROSPC)/2000
TSTV2(26)=((OCSAWBIOCUR(7)-OCSAWBIOREM(7))/GROSPC)/2000
TSTV2(32)=((OCSAWCARBCUR(7)-OCSAWCARBREM(7))/GROSPC)/2000
TSTV2(34)=((OFOLIBIO(7)-OFOLIBIOREM(7))/GROSPC)/2000
TSTV2(36)=((OFOLICARB(7)-OFOLICARBREM(7))/GROSPC)/2000
!
IF (LDEB) WRITE (JOSTND,94) (TSTV2(I),I=1,14)
94 FORMAT (' TSTV2=',10E11.3)
!
TADWBA=0.
DO 70 I=1,ITRN
TADWBA = TADWBA + (DBH(I)**3.)*0.0054542*PROB(I)
70 CONTINUE
TSTV2(16)=0.
IF(BA.GT.0.0 .AND. GROSPC.GT.0.0)TSTV2(16)=(TADWBA/BA)
CALL RDCLS2(0,0.,999.,1,CRD,0)
TSTV2(17)=CRD/GROSPC
!     Add logic for AHTWTBA here
TAHWBA = 0.
DO I=1,ITRN
  TAHWBA = TAHWBA + HT(I)*(DBH(I)**2)*0.0054542*PROB(I)
END DO
TSTV2(19)=0
IF(BA.GT.0.0 .AND. GROSPC .GT. 0.0)TSTV2(19)=(TAHWBA/BA)
!
!     LOAD GROUP 5 VARIABLES.
!
20 CONTINUE
IF (IUSERV.GT.1) IPHASE=2
!
!     FIND OUT IF ANY COMPUTE ACTIVITIES ARE SCHEDULED.
!
CALL OPFIND (3,MYACT,NTODO)
IF (LDEB) WRITE (JOSTND,21) NTODO
21 FORMAT (/' IN EVTSTV; NTODO: ',I4)
!
!     BRANCH TO NEXT GROUP IF THERE ARE NONE.
!
IF (NTODO.EQ.0) GOTO 50
!
!     SET UP THE DEBUG SWITCH FOR ALGEVL.
!
CALL DBCHK (LDEB2,'ALGEVL',6,ICYC)
!
!     GET THE COMPUTE PARMS AND BE READY TO "DO" THEM.
!
DO 30 ITODO=1,NTODO
CALL OPGET(ITODO,3,IDAT,IACTK,NP,PRM)
IF (IUSERV.GT.1 .AND. IUSERV.NE.IDAT) GOTO 30
IF (LDEB) WRITE (JOSTND,25) ITODO,IACTK
25 FORMAT(' IN EVTSTV: ITODO=',I4,' IACTK=',I4)
IF (IACTK.LT.0) GOTO 30
IF (IACTK.EQ.33) THEN
!
!        A POINTER TO THE OP CODE IS PRM(3) AND A POINTER TO THE ENTRY
!        IN TSTV5 IS PRM(2).
!
   ITS5 =IFIX(PRM(2))
   IF (ITS5.GT.500) ITS5=ITS5-500
   LOCOD=IFIX(PRM(3))
!
!        COMPUTE THE VALUE OF THE EXPRESSION.
!
   CALL ALGEVL (LREG,MXLREG,XREG,MXXREG,IEVCOD(LOCOD), &
     & MAXCOD-LOCOD+1,IY(1),IY(ICYC),LDEB2,JOSTND,IRC)
!
!        TAKE ACTION BASED ON THE RETURN CODE:
!        IRC=0: COMPUTATION OK, STORE ANSWER, SIGNAL ACTIVITY "DONE".
!        IRC=1: REFERENCE TO UNDEFINED VARIABLE, SET THIS VARIABLE
!               UNDEFINED, BRANCH TO NEXT.
!        IRC>1: SOME MAJOR PROBLEM, SET THIS VARIABLE UNDEFINED,
!               SIGNAL ACTIVITY "DELETED OR CANCELED", ISSUE ERROR MSG.
!
   IF (IRC.EQ.0) THEN
      TSTV5(ITS5)=XREG(1)
      LTSTV5(ITS5)=.TRUE.
      PARMS(IACT(IPTODO(ITODO),2))=XREG(1)
      I=IY(ICYC)
      IF (IUSERV.GT.1 .AND. IUSERV.EQ.IDAT) I=IUSERV
      CALL OPDONE (ITODO,I)
   ELSEIF (IRC.EQ.1) THEN
      LTSTV5(ITS5)=.FALSE.
   ELSE
      LTSTV5(ITS5)=.FALSE.
      CALL OPDEL1 (ITODO)
   ENDIF
   IF (LDEB) WRITE (JOSTND,26) ITS5,LOCOD,LTSTV5(ITS5), &
     & TSTV5(ITS5),CTSTV5(ITS5),IRC
26    FORMAT(' IN EVTSTV: ITS5=',I4,' LOCOD=',I4,' LTSTV5=',L2, &
     & ' TSTV5=',E15.7,' CTSTV5(ITS5)= ',A,' IRC=',I2)
ELSE
!
!        INTERACT WITH THE DBS EXTENSION TO STORE AND GET DATA.
!
   CALL DBSEVM (ITODO,IACTK,IY(ICYC),JOSTND)
ENDIF
30 CONTINUE
50 CONTINUE
IF (IUSERV.EQ.1) RETURN
!
RETURN
!
ENTRY EVSET4 (ISET,VALUE)
TSTV4(ISET)=VALUE
LTSTV4(ISET)=.TRUE.
RETURN
!
ENTRY EVUST4 (ISET)
LTSTV4(ISET)=.FALSE.
RETURN
!
ENTRY EVGET4 (IVAL,VSET,LSET)
VSET = TSTV4(IVAL)
LSET  = LTSTV4(IVAL)
RETURN
END


