SUBROUTINE FVSSTD (IWHO)
IMPLICIT NONE
!----------
! VBASE $Id$
!----------
!
!     CREATE A FILE FOR FVSTAND POST-PROCESSOR INPUT.
!
!     IWHO=1 IF CALLED FROM MAIN, IWHO=2 IF CALLED FROM CUTS
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'HTCAL.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'ESTREE.f90'
!
!
INCLUDE 'VARCOM.f90'
!
!
INCLUDE 'WORKCM.f90'
!
!
INCLUDE 'STDSTK.f90'
!
!
INCLUDE 'SUMTAB.f90'
!
!
INCLUDE 'OUTCOM.f90'
!
!
INCLUDE 'ECON.f90'
!
!
INCLUDE 'OPCOM.f90'
!
!
INCLUDE 'FVSSTDCM.f90'
!
!
!OMMONS
!----------
INTEGER IWHO,MYACT(1),KSDI,IOPEN,I,NTODO,ITODO,NPRMS,IACTK,IDT
INTEGER KODE,ISTLNB,JYR,IP,ITPLAB,ITMFOR,IBA,IKNT,ISITE
INTEGER KAGE,ISPC,I1,I2,I3,IICR,IDMR,ICDF,IBDF,IPTBAL
REAL TEM(6),TEMSDI,STAGEA,STAGEB,XXWT,TEMBA,P,DP,CW,DGI
REAL PDBHI,BRATIO,PHTI,DUMSDI,RTCUFV,RMCUFV,RPTOCFV,RMRCFV
DIMENSION CLAB1(2)
CHARACTER CISN*11,TIM*8,DAT*10,TID*8,CLAB1*4
CHARACTER REV*10
INTEGER*4 IDCMP1,IDCMP2
DATA MYACT/204/
DATA IDCMP1,IDCMP2/10000000,20000000/
DATA CLAB1/'TREE','CUT '/
!----------
!  COMPUTE CURRENT SDI FOR PRINTING
!----------
DO I=1,6
  TEM(I) = 0.0
ENDDO
!----------
!  COMPUTE CURRENT SDI FOR PRINTING
!----------
TEMSDI=0.
CALL SDICLS(0,0.,999.,1,TEMSDI,DUMSDI,STAGEA,STAGEB,0)
KSDI=INT(TEMSDI/GROSPC + 0.5)
!----------
!  SET OLD VOLUME VARIABLES TO ZERO IF THIS IS CYCLE 0
!----------
IF (LSTART) THEN
  IOPEN=0
  DO 10 I=1,ITRN
  PTOCFV(I)=0.
  PMRCFV(I)=0.
  PSCFV(I)=0.
  PMRBFV(I)=0.
  NCFDEF(I)=0
  NBFDEF(I)=0 &
     &ONTINUE
ENDIF
!----------
!  SET OLD PPE VARIABLE TO BLANK, BUT KEEP TO PRESERVE HEADER FORMAT
!----------
CISN = '           '
!----------
!  FIND OUT IF THERE IS A FVSSTAND OPTION.
!----------
CALL OPFIND (1,MYACT(1),NTODO)
!----------
!  IF THERE ARE NONE TO DO, RETURN
!----------
IF (NTODO.EQ.0) GO TO 220
!----------
!  ELSE: DO THE OPTIONS PRESENT.
!----------
DO 200 ITODO=1,NTODO
CALL OPGET (ITODO,2,IDT,IACTK,NPRMS,TEM)
IF (IACTK.LT.0) GOTO 200
!----------
!  IF THE OUTPUT FILE IS NOT OPEN, OPEN IT.
!----------
IF(.NOT.FSTOPEN) THEN
  CALL MYOPEN(KOLIST,KWDFIL(1:ISTLNB(KWDFIL))//'.fst', &
                 5,170,0,1,1,0,KODE)
  IF(KODE .GT. 0) THEN
    WRITE(JOSTND,*)'FVSSTAND FILE DID NOT OPEN'
    CALL RCDSET (2,.TRUE.)
    GO TO 200
  ENDIF
  FSTOPEN=.TRUE.
ENDIF
!----------
!  LET IP BE THE RECORD OUTPUT COUNT
!  SET THE OUTPUT REPORTING YEAR.
!----------
IF(IWHO .EQ. 1) THEN
  JYR=IY(ICYC+1)
  IP=ITRN
  ITPLAB=1
ELSE
  JYR=IY(ICYC)
  IP=0
  DO 1 I=1,ITRN
  IF(WK3(I) .GT. 0.) IP=IP+1
1   CONTINUE
  ITPLAB=2
ENDIF
!----------
!  IF AT THE PRE-PROJECTION TIME, FIND OUT IF A FVSSTAND HAS BEEN
!  SUPPRESSED. IF YES, BRANCH TO NOT ACCOMPLISH THE REQUEST.
!  ONLY MARK THE OPTION DONE IF THIS IS CALLED FROM MAIN.
!----------
IF (LSTART) THEN
  IF (NPRMS.GE.1 .AND. TEM(1).EQ.1.) GOTO 200
  IF(NPRMS.GE.1 .AND. TEM(1).EQ.2)CALL OPDONE(ITODO,JYR)
ELSE
  IF (NPRMS.GE.1 .AND. TEM(1).EQ.2.) GOTO 200
  IF(IWHO .EQ. 1)THEN
    CALL OPDONE (ITODO,JYR-1)
  ELSE
!         CALL OPDONE(ITODO,JYR)
  ENDIF
ENDIF
!----------
!  WRITE A MARKER AND THE NUMBER OF RECORDS WHICH FOLLOW.
!----------
XXWT=SAMWT
CALL REVISE (VARACD,REV)
CALL GRDTIM (DAT,TIM)
SELECT CASE (VARACD)
  CASE ('KT')
    ITMFOR=KODFOR/100000
  CASE DEFAULT
    ITMFOR=KODFOR
END SELECT
IBA=NINT(BA/GROSPC)
IF(IWHO.NE.1)THEN
  TEMBA=0.
  DO 40 I=1,ITRN
  TEMBA=TEMBA+0.0054542*DBH(I)*DBH(I)*PROB(I) &
     &ONTINUE
  IBA=NINT(TEMBA/GROSPC)
ENDIF
IKNT=ICYC+1
ISITE=IFIX(SITEAR(ISISP))
IF(LSTART) THEN
  KAGE=IAGE
ELSE
  IF(IWHO .EQ. 1) THEN
    KAGE=IAGE + IY(IKNT) - IY(1)
  ELSE
    KAGE=IAGE + IY(ICYC) - IY(1)
  ENDIF
ENDIF
WRITE (KOLIST,2) IP,ICYC,JYR,NPLT,MGMID,VARACD,DAT,TIM, &
                    CLAB1(ITPLAB)(1:1),IFINT,XXWT,REV,CISN, &
    KAGE,ITMFOR,FIAJSP(ISISP),ISITE,IPTINV,IBA,KSDI
2 FORMAT (' -999',3I5,3(1X,A),5X,3(1X,A),I3,E14.7,2(1X,A), &
     &,I4,12X,I9,1X,A3,I5,I2,I3,I5)
!----------
!  PROCESS TREELIST
!----------
DO 60 ISPC=1,MAXSP
I1=ISCT(ISPC,1)
IF(I1.EQ.0) GO TO 60
I2=ISCT(ISPC,2)
DO 50 I3=I1,I2
I=IND1(I3)
IF(ITPLAB .EQ. 1) THEN
  P = PROB(I) / GROSPC
  IF(ICYC.GT.0) THEN
    DP = WK2(I)/ GROSPC
  ELSE
    DP = 0.0
  ENDIF
ELSE
  P = WK3(I)/GROSPC
  DP = 0.
  IF(P .LE. 0.) GO TO 50
ENDIF
IICR=((ICR(I)-1)/10)+1
IF (IICR.GT.9) IICR=9
!----------
!   TRANSLATE TREE IDS FOR TREES THAT HAVE BEEN COMPRESSED OR
!   GENERATED THROUGH THE ESTAB SYSTEM.
!----------
IF (IDTREE(I) .GT. IDCMP1) THEN
   IF (IDTREE(I) .GT. IDCMP2) THEN
      WRITE(TID,'(''CM'',I6.6)') IDTREE(I)-IDCMP2
   ELSE
      WRITE(TID,'(''ES'',I6.6)') IDTREE(I)-IDCMP1
   ENDIF
ELSE
   WRITE(TID,'(I8)') IDTREE(I)
ENDIF
!----------
!  GET MISTLETOE RATING FOR CURRENT TREE RECORD.
!----------
CALL MISGET(I,IDMR)
!----------
!  SET CROWN WIDTH.
!----------
CW=CRWDTH(I)
!----------
!  DECODE DEFECT AND ROUND OFF POINT BAL.
!----------
ICDF=(DEFECT(I)-((DEFECT(I)/10000)*10000))/100
IBDF= DEFECT(I)-((DEFECT(I)/100)*100)
NCFDEF(I)=ICDF
NBFDEF(I)=IBDF
IPTBAL=NINT(PTBALT(I))
!----------
!  CYCLE 0, PRINT INPUT DG ONLY
!----------
DGI = DG(I)
IF(LSTART) DGI = WORK1(I)
!
IF(IDG.EQ.0 .OR. IDG.EQ.2)THEN
  IF(DGI .GT. 0. .AND. &
      ((DGI/BRATIO(ISP(I),DBH(I)-DG(I),HT(I)).LT.DBH(I))))THEN
    PDBHI=DBH(I)-(DG(I)/BRATIO(ISP(I),DBH(I)-DG(I),HT(I)))
  ELSE
    PDBHI=0.
  ENDIF
ELSE
  PDBHI=PDBH(I)
ENDIF
PDBH(I)=0.
!
IF(IHTG.EQ.0 .OR. IHTG.EQ.2)THEN
  IF(HTG(I) .GT. 0.)THEN
    PHTI=HT(I)-HTG(I)
  ELSE
    PHTI=0.
  ENDIF
ELSE
  PHTI=PHT(I)
ENDIF
PHT(I)=0.
!     USING REPORTED TOTAL AND MERCHANTABLE CUBIC FOOT VOLUMES TO MAINTAIN
!     HISTORIC DIFFERENCE BETWEEN EASTERN AND WESTERN VARIANT VOLUME REPORTING
IF(VARACD.EQ.'CS' .OR. VARACD.EQ.'LS' .OR. &
      VARACD.EQ.'NE' .OR. VARACD.EQ.'SN') THEN
  RTCUFV=MCFV(I)
  RMCUFV=SCFV(I)
  RPTOCFV=PMRCFV(I)
  RMRCFV=PSCFV(I)
ELSE
  RTCUFV=CFV(I)
  RMCUFV=MCFV(I)
  RPTOCFV=PTOCFV(I)
  RMRCFV=PMRCFV(I)
END IF
!
IF(P.LT.9999.9995 .AND. DP.LT.9999.9995)THEN
  WRITE(KOLIST,21) TID,I,NSP(ISP(I),1)(1:2),ISP(I),IMC(I), &
     &SPECL(I),ITRE(I),P,DP,DBH(I),DGI     ,HT(I),HTG(I),ICR(I),CW, &
     &DMR,PCT(I),IPTBAL,RTCUFV,RMCUFV,BFV(I),ICDF,IBDF, &
     &(ITRUNC(I)+5)/100),PDBHI,PHTI, &
     &PTOCFV,RMRCFV,PMRBFV(I),NCFDEF(I),NBFDEF(I), &
     &RDLOS(I),((NORMHT(I)+5)/100),ABIRTH(I),IPVEC(ITRE(I)) &
     &ORMAT(1X,A8,1X,I4,1X,A2,I3,2(1X,I2),1X,I3,1X,F8.3,1X,F8.3, &
          1X,F5.1,1X,F5.2,1X,F5.1,1X,F4.1,1X,I2,1X,F4.1,1X,I2, &
          1X,F6.2,1X,I5,1X,F6.1,1X,F6.1,1X,F7.1,1X,I2,1X,I2, &
          1X,I3, &
          1X,F5.1,1X,F5.1,1X,F6.1,1X,F6.1,1X,F7.1,1X,I2,1X,I2, &
          1X,F7.5,1X,I5,1X,F6.0,1X,I8)
ELSE
  WRITE(KOLIST,20) TID,I,NSP(ISP(I),1)(1:2),ISP(I),IMC(I), &
     &SPECL(I),ITRE(I),P,DP,DBH(I),DGI     ,HT(I),HTG(I),ICR(I),CW, &
     &DMR,PCT(I),IPTBAL,CFV(I),MCFV(I),SCFV(I),BFV(I),ICDF,IBDF, &
     &(ITRUNC(I)+5)/100),PDBHI,PHTI, &
     &PTOCFV,RMRCFV,PMRBFV(I),NCFDEF(I),NBFDEF(I), &
     &RDLOS(I),((NORMHT(I)+5)/100),ABIRTH(I),IPVEC(ITRE(I)) &
     &ORMAT(1X,A8,1X,I4,1X,A2,I3,2(1X,I2),1X,I3,1X,F8.2,1X,F8.2, &
          1X,F5.1,1X,F5.2,1X,F5.1,1X,F4.1,1X,I2,1X,F4.1,1X,I2, &
          1X,F6.2,1X,I5,1X,F6.1,1X,F6.1,1X,F7.1,1X,I2,1X,I2, &
          1X,I3, &
          1X,F5.1,1X,F5.1,1X,F6.1,1X,F6.1,1X,F7.1,1X,I2,1X,I2, &
          1X,F7.5,1X,I5,1X,F6.0,1X,I8)
ENDIF
50 CONTINUE
60 CONTINUE
!
!  FOR CYCLE 0 LIST, PRINT DEAD TREES WHICH WERE PRESENT IN
!  THE INVENTORY DATA AT THE BOTTOM OF THE FVSSTAND LIST
!
IF(IREC2.GT.MAXTRE .OR. ITPLAB.EQ.2) GO TO 200
DO 150 I=IREC2,MAXTRE
P =(PROB(I) / GROSPC) / (FINT/FINTM)
IICR=((ICR(I)-1)/10)+1
IF (IICR.GT.9) IICR=9
WRITE(TID,'(I8)') IDTREE(I)
!----------
!     GET MISTLETOE RATING FOR CURRENT TREE RECORD.
!----------
CALL MISGET(I,IDMR)
!----------
!     SET CROWN WIDTH.
!----------
CW=CRWDTH(I)
!----------
!     DECODE DEFECT AND ROUND OFF POINT BAL.
!----------
ICDF=(DEFECT(I)-((DEFECT(I)/10000)*10000))/100
IBDF= DEFECT(I)-((DEFECT(I)/100)*100)
NCFDEF(I)=ICDF
NBFDEF(I)=IBDF
IPTBAL=NINT(PTBALT(I))
!----------
!  CYCLE 0, PRINT INPUT DG ONLY, UNLESS DIRECTED TO PRINT ESTIMATES.
!----------
DGI=DG(I)
IF(ICYC.EQ.0 .AND. TEM(6).EQ.0) DGI=WORK1(I)
PDBHI = 0.
PHTI = 0.
!----------
!  PUT PROB IN MORTALITY COLUMN
!----------
DP = P
P = 0.
!
!     USING REPORTED TOTAL AND MERCHANTABLE CUBIC FOOT VOLUMES TO MAINTAIN
!     HISTORIC DIFFERENCE BETWEEN EASTERN AND WESTERN VARIANT VOLUME REPORTING
IF(VARACD.EQ.'CS' .OR. VARACD.EQ.'LS' .OR. &
      VARACD.EQ.'NE' .OR. VARACD.EQ.'SN') THEN
  RTCUFV=MCFV(I)
  RMCUFV=SCFV(I)
  RPTOCFV=PMRCFV(I)
  RMRCFV=PSCFV(I)
ELSE
  RTCUFV=CFV(I)
  RMCUFV=MCFV(I)
  RPTOCFV=PTOCFV(I)
  RMRCFV=PMRCFV(I)
END IF
!
IF(P.LT.9999.9995 .AND. DP.LT.9999.9995)THEN
  WRITE(KOLIST,21) TID,I,NSP(ISP(I),1)(1:2),ISP(I),IMC(I), &
     &SPECL(I),ITRE(I),P,DP,DBH(I),DGI     ,HT(I),HTG(I),ICR(I),CW, &
     &DMR,PCT(I),IPTBAL,RTCUFV,RMCUFV,BFV(I),ICDF,IBDF, &
     &(ITRUNC(I)+5)/100),PDBHI,PHTI, &
     &PTOCFV,RMRCFV,PMRBFV(I),NCFDEF(I),NBFDEF(I), &
     &RDLOS(I),((NORMHT(I)+5)/100),ABIRTH(I),IPVEC(ITRE(I))
ELSE
  WRITE(KOLIST,20) TID,I,NSP(ISP(I),1)(1:2),ISP(I),IMC(I), &
     &SPECL(I),ITRE(I),P,DP,DBH(I),DGI     ,HT(I),HTG(I),ICR(I),CW, &
     &DMR,PCT(I),IPTBAL,RTCUFV,RMCUFV,BFV(I),ICDF,IBDF, &
     &(ITRUNC(I)+5)/100),PDBHI,PHTI, &
     &PTOCFV,RMRCFV,PMRBFV(I),NCFDEF(I),NBFDEF(I), &
     &RDLOS(I),((NORMHT(I)+5)/100),ABIRTH(I),IPVEC(ITRE(I))
ENDIF
150 CONTINUE
!
200 CONTINUE
!
220 CONTINUE
RETURN
END
