SUBROUTINE BFREAD (BUFFER,IPNT,ILIMIT,VARBLE,ILEN,IBEGIN)
IMPLICIT NONE
!----------
! PG $Id$
!----------
!
!     READ A VARIABLE FROM A BUFFER.
!
!     PART OF THE PARALLEL PROCESSING EXTENSION OF PROGNOSIS SYSTEM.
!
!        BUFFER - A SINGLE DIMENSIONAL WORK ARRAY USED AS A PRINT
!                 BUFFER.
!        IPNT   - POINTER TO THE CURRENT WORD IN THE BUFFER.
!                 WHEN READING THE FIRST RECORD IN A SERIES,
!                 IPNT IS SET TO THE END OF THE BUFFER IN ORDER
!                 BE RESET TO ZERO ON THE FIRST READ.
!        ILIMIT - END OF BUFFER.  MAX NUMBER OF WORDS WHICH CAN
!                 BE STORED IN BUFFER.
!        VARBLE - THE ARRAY WHICH IS READ FROM BUFFER.
!        ILEN   - THE NUMBER OF WORDS IN VARBLE.
!        IBEGIN - SIGNAL DESCRIBING WHETHER WE ARE BEGINNING A
!                 SERIES OF CALLS TO BFREAD, IN THE MIDDLE OF A
!                 SERIES OF CALLS, OR AT THE END OF A SERIES OF CALLS.
!                 1 - THIS IS THE FIRST CALL IN A GROUP TO BFREAD.
!                     THE BUFFER COUNTER IS SET FULL, SO WE WILL
!                     BEGIN READING FROM A NEW RECORD.
!                 2 - THIS IS A MIDDLE CALL TO BFREAD.
!                 3 - THIS IS THE LAST CALL TO BFREAD.
!
REAL BUFFER (*), VARBLE (*)
INTEGER IBEGIN,ILEN,ILIMIT,IPNT,IWORD,I
IF (IBEGIN.EQ.1) IPNT=ILIMIT
IF (ILEN.LT.1) GOTO 1000
DO 900 IWORD=1,ILEN
IF (IPNT.LT.ILIMIT) GOTO 500
CALL DSTASH (BUFFER,IPNT)
call fvsGetRtnCode(I)
if (I.ne.0) return
IPNT=0
500 CONTINUE
IPNT=IPNT+1
VARBLE (IWORD)=BUFFER (IPNT)
900 CONTINUE
1000 CONTINUE
RETURN
END

SUBROUTINE BFWRIT (BUFFER,IPNT,ILIMIT,VARBLE,ILEN,IBEGIN)
IMPLICIT NONE
!----------
!  **BFWRIT--PPBASE    DATE OF LAST REVISION:  07/31/08
!----------
!
!     STORE A VARIABLE IN A BUFFER.
!
!     CALLED FROM:
!
!       PUTSTD - STORE A STAND ON DIRECT ACCESS FILE IDAIO.
!       MSTRPT - STORE THE MASTER SCHEDULED OPTION LIST.
!       PPAUSE - PAUSE THE PARALLEL PROCESSINT EXTENSION BY
!                WRITING ITS DATA TO DIRECT ACCESS FILE IDAIO.
!
!     SUBROUTINES CALLED:
!
!       STASH  - STORE A RECORD IN THE DIRECT ACCESS FILE IDAIO.
!
!     PARAMETERS:
!
!        BUFFER - A SINGLE DIMENSIONAL WORK ARRAY USED AS A PRINT
!                 BUFFER.
!        IPNT   - POINTER TO THE CURRENT WORD IN THE BUFFER.
!                 WHEN READING THE FIRST RECORD IN A SERIES,
!                 IPNT IS SET TO THE END OF THE BUFFER IN ORDER
!                 BE RESET TO ZERO ON THE FIRST READ.
!        ILIMIT - END OF BUFFER.  MAX NUMBER OF WORDS WHICH CAN
!                 BE STORED IN BUFFER.
!        VARBLE - THE ARRAY WHICH IS WRITTEN TO THE BUFFER.
!        ILEN   - THE NUMBER OF WORDS IN VARBLE.
!        IBEGIN - SIGNAL DESCRIBING WHETHER WE ARE BEGINNING A
!                 SERIES OF CALLS TO BFWRIT, IN THE MIDDLE OF A
!                 SERIES OF CALLS, OR AT THE END OF A SERIES OF CALLS.
!
!                 1 - THIS IS THE FIRST CALL IN A GROUP TO BFWRIT.
!                     THE BUFFER IS SET EMPTY, SO WE WILL
!                     BEGIN WRITING TO A NEW RECORD.
!                 2 - THIS IS A MIDDLE CALL TO BFWRIT.
!                 3 - THIS IS THE LAST CALL TO BFWRIT, WHICH
!                     DUMPS THE CONTENTS OF THE BUFFER, AND
!                     FINALIZES THE WRITE.
!
REAL BUFFER (*), VARBLE (*)
INTEGER IBEGIN,ILEN,ILIMIT,IPNT,IWORD
IF (IBEGIN.EQ.1) IPNT=0
IF (ILEN.LT.1) GOTO 1000
DO 900 IWORD=1,ILEN
IF (IPNT.LT.ILIMIT) GOTO 500
CALL STASH (BUFFER,ILIMIT)
IPNT=0
500 CONTINUE
IPNT=IPNT+1
BUFFER (IPNT)=VARBLE (IWORD)
900 CONTINUE
1000 CONTINUE
IF (IBEGIN.EQ.3) CALL STASH (BUFFER,ILIMIT)
RETURN
END

SUBROUTINE CHREAD (CBUFF,IPNT,LNCBUF,CVARBL,IBEGIN)
IMPLICIT NONE
!----------
!  **CHREAD  DATE OF LAST REVISION:  07/31/08
!----------
!
INTEGER IBEGIN,IPNT,LNCBUF,I
CHARACTER CBUFF(LNCBUF)
CHARACTER CVARBL
IF (IBEGIN.EQ.1) IPNT=LNCBUF
IF (IPNT.LT.LNCBUF) GOTO 500
CALL CHDSTH (CBUFF,IPNT)
call fvsGetRtnCode(I)
if (I.ne.0) return
IPNT=0
500 CONTINUE
IPNT=IPNT+1
CVARBL=CBUFF(IPNT)
RETURN
END

SUBROUTINE CHWRIT (CBUFF,IPNT,LNCBUF,CVARBL,IBEGIN)
IMPLICIT NONE
!----------
!  **CHWRIT  DATE OF LAST REVISION:  07/31/08
!----------
!
INTEGER IBEGIN,IPNT,LNCBUF,I
CHARACTER CBUFF(LNCBUF)
CHARACTER CVARBL
IF (IBEGIN.EQ.1) IPNT=0
IF (IPNT.GE.LNCBUF) THEN
   CALL CHSTSH (CBUFF,LNCBUF)
   IPNT=0
ENDIF
IPNT=IPNT+1
CBUFF(IPNT)=CVARBL
IF (IBEGIN.EQ.3) THEN
   IF (IPNT.LT.LNCBUF) THEN
      DO I=IPNT+1,LNCBUF
         CBUFF(I)=' '
      ENDDO
   ENDIF
   CALL CHSTSH (CBUFF,LNCBUF)
ENDIF
RETURN
END


SUBROUTINE LFREAD(BUFFER,IPNT,ILIMIT,LVAR,ILEN,IBEGIN)
IMPLICIT NONE
!----------
!  **LFREAD--PPBASE    DATE OF LAST REVISION:  07/31/08
!----------
!
LOGICAL LVAR(*),LSTOR
REAL BUFFER(*),RSTOR
INTEGER IBEGIN,ILEN,ILIMIT,IPNT,IWORD,I
EQUIVALENCE (LSTOR,RSTOR)
IF (IBEGIN.EQ.1) IPNT=ILIMIT
IF (ILEN.LT.1) GOTO 1000
DO 900 IWORD=1,ILEN
IF (IPNT.LT.ILIMIT) GOTO 500
CALL DSTASH (BUFFER,IPNT)
call fvsGetRtnCode(I)
if (I.ne.0) return
IPNT=0
500 CONTINUE
IPNT=IPNT+1
RSTOR=BUFFER(IPNT)
LVAR(IWORD)=LSTOR
900 CONTINUE
1000 CONTINUE
RETURN
END


SUBROUTINE LFWRIT (BUFFER,IPNT,ILIMIT,LVAR,ILEN,IBEGIN)
IMPLICIT NONE
!----------
!  **LFWRIT--PPBASE    DATE OF LAST REVISION:  07/31/08
!----------
!
LOGICAL LVAR(*),LSTOR
REAL BUFFER(*),RSTOR
INTEGER IBEGIN,ILEN,ILIMIT,IPNT,IWORD
EQUIVALENCE (RSTOR,LSTOR)
IF (IBEGIN.EQ.1) IPNT=0
IF (ILEN.LT.1) GOTO 1000
DO 900 IWORD=1,ILEN
IF (IPNT.LT.ILIMIT) GOTO 500
CALL STASH (BUFFER,ILIMIT)
IPNT=0
500 CONTINUE
LSTOR=LVAR(IWORD)
IPNT=IPNT+1
BUFFER(IPNT)=RSTOR
900 CONTINUE
1000 CONTINUE
IF (IBEGIN.EQ.3) CALL STASH (BUFFER,ILIMIT)
RETURN
END



SUBROUTINE IFREAD(BUFFER,IPNT,ILIMIT,IVAR,ILEN,IBEGIN)
IMPLICIT NONE
!----------
!  **IFREAD--PPBASE   DATE OF LAST REVISION:  07/31/08
!----------
!
REAL BUFFER(*)
INTEGER IVAR(*)
INTEGER IBEGIN,ILEN,ILIMIT,IPNT,IWORD,I
REAL RSTOR
INTEGER*4 ISTOR
EQUIVALENCE (RSTOR,ISTOR)
IF (IBEGIN.EQ.1) IPNT=ILIMIT
IF (ILEN.LT.1) GOTO 1000
DO 900 IWORD=1,ILEN
IF (IPNT.LT.ILIMIT) GOTO 500
CALL DSTASH (BUFFER,IPNT)
call fvsGetRtnCode(I)
if (I.ne.0) return
IPNT=0
500 CONTINUE
IPNT=IPNT+1
RSTOR=BUFFER(IPNT)
IVAR(IWORD)=ISTOR
900 CONTINUE
1000 CONTINUE
RETURN
END

SUBROUTINE IFWRIT (BUFFER,IPNT,ILIMIT,IVAR,ILEN,IBEGIN)
IMPLICIT NONE
!----------
!  **IFWRIT--PPBASE    DATE OF LAST REVISION:  07/31/08
!----------
!
REAL BUFFER(*),RSTOR
INTEGER IVAR(*),IBEGIN,ILEN,ILIMIT,IPNT,IWORD
INTEGER*4 ISTOR
EQUIVALENCE (RSTOR,ISTOR)
IF (IBEGIN.EQ.1) IPNT=0
IF (ILEN.LT.1) GOTO 1000
DO 900 IWORD=1,ILEN
IF (IPNT.LT.ILIMIT) GOTO 500
CALL STASH (BUFFER,ILIMIT)
IPNT=0
500 CONTINUE
ISTOR=IVAR(IWORD)
IPNT=IPNT+1
BUFFER(IPNT)=RSTOR
900 CONTINUE
1000 CONTINUE
IF (IBEGIN.EQ.3) CALL STASH (BUFFER,ILIMIT)
RETURN
END
