SUBROUTINE VARGET (WK3,IPNT,ILIMIT,REALS,LOGICS,INTS)
IMPLICIT NONE
!----------
! PG $Id$
!----------
!
!     READ THE VARIANT SPECIFIC VARIABLES.
!
!     PART OF THE PARALLEL PROCESSING EXTENSION TO PROGNOSIS.
!
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
!OMMONS
!
!     NOTE: THE ACTUAL STORAGE LIMIT FOR INTS, LOGICS, AND REALS
!     IS MAXTRE (SEE PRGPRM).
!
INTEGER ILIMIT,IPNT,MXL,MXI,MXR
PARAMETER (MXL=1,MXI=1,MXR=1)
LOGICAL LOGICS(*)
REAL WK3(MAXTRE)
INTEGER INTS(*)
REAL REALS(*)
LOGICAL LDANUW
REAL RDANUW
INTEGER IDANUW
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
IDANUW = ILIMIT
IDANUW = INTS(1)
IDANUW = IPNT
LDANUW = LOGICS(1)
RDANUW = REALS(1)
RDANUW = WK3(1)
!
RETURN
END

SUBROUTINE VARCHGET (CBUFF, IPNT, LNCBUF)
IMPLICIT NONE
!----------
!     Get variant-specific character data
!----------

INCLUDE 'PRGPRM.f90'

INTEGER LNCBUF
CHARACTER CBUFF(LNCBUF)
CHARACTER CDANUW
INTEGER IDANUW
INTEGER IPNT
! Stub for variants which need to get/put character data
! See /bc/varget.f and /bc/varput.f for examples of VARCHGET and VARCHPUT
!----------
!  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
!----------
CDANUW = CBUFF(1)
IDANUW = IPNT
IDANUW = LNCBUF
!
RETURN
END
