SUBROUTINE BWEADV(IYR1)
IMPLICIT NONE
!----------
! WSBWE $Id$
!----------
!
!     ADJUST PROGNOSIS VARIABLES.
!
!     PART OF THE WESTERN SPRUCE BUDWORM MODEL/PROGNOSIS LINKAGE CODE.
!     NL CROOKSTON--FORESTRY SCIENCES LAB--MOSCOW, MAY, 1984
!     minor changes by K.Sheehan 7/96 to remove LBWDEB,LBWGRO,IHABIT
!        STNDEL, SCSTAG
!
!     DESCRIPTION :
!
!     THIS ROUTINE ADJUSTS VARIABLES WHICH COME FROM PROGNOSIS SO
!     THEY WILL FIT INTO BUDWORM MODEL COMPONENTS.
!
!     CALLED FROM :
!
!       BWESIT - CREATE A BUDWORM MODEL STAND FROM A PROGNOSIS STAND.
!
!     PARAMETERS :
!
!       IYR1   - INVENTORY YEAR OF THE STAND.
!
! Revision History:
!  17-MAY-2005 Lance R. David (FHTET)
!     Added FVS parameter file PRGPRM.F77.
!  14-JUL-2010 Lance R. David (FMSC)
!     Added IMPLICIT NONE and declared variables as needed.
!-----------------------------------------------------------
!
!OMMONS
!
INCLUDE 'PRGPRM.f90'
INCLUDE 'BWESTD.f90'
INCLUDE 'BWECOM.f90'
!
!OMMONS
!
INTEGER ICROWN, IHOST, IYR1
!
!     IF THERE IS LARCH, ADD THE FOLIAGE TO NON-HOST AND SET
!     THE LARCH FLAG EQUAL TO ZERO.
!
IF (IFHOST(6).EQ.0) GOTO 1020
DO 1015 ICROWN=1,NCROWN
FOLNH(ICROWN)=FOLNH(ICROWN)+FOLADJ(6,ICROWN,1)+ &
      FOLADJ(6,ICROWN,2)+FOLADJ(6,ICROWN,3)+FOLADJ(6,ICROWN,4)
1015 CONTINUE
IFHOST(6)=0
1020 CONTINUE
!
DO 1040 IHOST=1,NHOSTS
IF (IFHOST(IHOST).EQ.0) GOTO 1040
DO 1035 ICROWN=1,NCROWN
FNEW(ICROWN,IHOST)=FOLADJ(IHOST,ICROWN,1)
FOLD1(ICROWN,IHOST)=FOLADJ(IHOST,ICROWN,2)* &
                       PRBIO(IHOST,ICROWN,2)
FOLD2(ICROWN,IHOST)=FOLADJ(IHOST,ICROWN,3)* &
                       PRBIO(IHOST,ICROWN,3)
FREM(ICROWN,IHOST)=FOLADJ(IHOST,ICROWN,4)* &
                       PRBIO(IHOST,ICROWN,4)
!
1035 CONTINUE
1040 CONTINUE
!
!     CHECK THE YEARS.
IBWYR1=IYR1
!
RETURN
END
