!ODE SEGMENT BWEBOX
!----------
! WSBWE $Id$
!----------
!
! Revision History:
!   21-NOV-2002 Lance R. David (FHTET)
!      Previous date of change noted was 06/09/00.
!      Changed variable ISTATE to ISTNUM.
!   10-AUG-2006 Lance R. David (FHTET)
!      Reorganizing and removing obsolete variable in preparation for
!      linkage with PPE.
!   30-AUG-2006 Lance R. David (FHTET)
!      Changed array orientation of IEVENT from (4,250) to (250,4) for
!      efficiency purposes of the PPE processes in bwepppt and bweppgt.
!   28-AUG-2013 Lance R. David (FMSC)
!      Expanded IEVENT to 5 columns for weather year.
!----------------------------------------------------------------------
!
!     BWEBOX: DIALOG BOX VARIABLES
!
CHARACTER*4 MGMIDB
CHARACTER*8 DEFLAB,DLABS(5)
CHARACTER*12 STATES(10,2)
CHARACTER*16 WSLOOK(100,10)
CHARACTER*20 TEMPS2(3)
CHARACTER*40 OUTNAM(8),STNAME,WFNAME
CHARACTER*50 EVENT(20)
CHARACTER*72 ITITLB

INTEGER IBUDYR,IBWOPT,IDEF(100,5),IDEFPR,IDEFSP(5), &
      IEVENT(250,5),IFLAG,IOBACT,IOBSCH(3,2),IPARA,IQUALD, &
      IQUALW,ISTN,ISTNUM,ITEMP(5),IWSRC,JOWE,NEVENT,NOBDON, &
      NOBSCH,NUMCOL,NUMSTN(10)

REAL    NEMULT(4,3), RAINDM, RAINDS, RAINM(3), RAINS(3), &
           WHOTM, WHOTSD

LOGICAL LTEMP1(4), LP1, LP2, LP3, LP4, LP5, LP6, LP7, LP8

COMMON / BWBOXC / DEFLAB,DLABS,EVENT,ITITLB,MGMIDB,OUTNAM, &
      STATES,STNAME,TEMPS2,WFNAME,WSLOOK


COMMON / BWBOX / IBUDYR,IBWOPT,IDEF,IDEFPR,IDEFSP,IEVENT,IFLAG, &
      IOBACT,IOBSCH,IPARA,IQUALD,IQUALW,ISTN,ISTNUM,ITEMP,IWSRC, &
      JOWE,LP1,LP2,LP3,LP4,LP5,LP6,LP7,LP8,LTEMP1,NEMULT,NEVENT, &
      NOBDON,NOBSCH,NUMCOL,NUMSTN,RAINDM,RAINDS,RAINM,RAINS, &
      WHOTM,WHOTSD


!   DEFLAB - LABEL FOR NEXT COLUMN IN DEFOLIATION GRAPHIC OUTPUT TABLE
!   DLABS(5) - DEFOLIATION COLUMN LABELS FOR GRAPHIC OUTPUT TABLE
!   EVENT(20) - NAMES OF EVENTS STORED IN IEVENT & PRINTED IN TABLE 4
!   IBUDYR - CURRENT BUDWORM YEAR (FOR STORING DEFOL. VALUES IN IDEF)
!   IDEF(100,5) - ARRAY THAT STORES DEFOLIATION VALUES FOR GRAPHS
!   IDEFPR - =0 FOR NO DEFOL. GRAPHS, 1 FOR DEFOLIATION BY SPECIES,
!            AND 2 FOR DEFOLIATION BY STANDS (EX. DIFFERENT SEEDS)
!   IDEFSP(5) - =1 IF DEFOLIATION IS TO BE PRINTED FOR THIS TREE SPECIES
!   IEVENT(250,5) - BW SPECIAL EVENTS SUMMARY ARRAY
!   IFLAG - STORES NO. THAT IDENTIFIES WHERE DIALOG BOX WAS EXITED [BWEBOX]
!   IOBACT - IS MOST RECENT OUTBREAK STILL ACTIVE? 1=YES, 2=NO
!   IPARA  - PARASITISM RATES VARY? 1=YES, 2=NO
!   IQUALD - FOL. QUALITY EFFECTS ON DEVEL. RATES VARY? (1=Y,2=N)
!   IQUALW - FOL. QUALITY EFFECTS ON PUPAL WEIGHTS VARY? (1=Y,2=N)
!   ISTNUM - STATE NUMBER TO BE USED
!   ISTN   - WEATHER STATION NUMBER TO BE USED
!   ITEMP(5)  - STORES INTEGER VARIABLES SET BY MENUS
!     1=NUMBER OF OUTBREAK STATISTICS AREAS; 2=CURRENT OUTBR. ST. AREA;
!     3=NO. OF STATES; 4=       CURRENT STATE; 5=CURRENT WEATHER STATION NO.
!   ITITLB - TITLE FOR BW MODEL
!   IWSRC  - WEATHER DATAFILE SOURCE (1=BUDLITE, 2=USER, NAME = WFNAME)
!   JOWE - FILE NUMBER ASSIGNED TO STNAME
!   KFNAME - DEFAULT FILE NAME FOR BW MODEL KEYWORDS
!   LP1-6  - BW OUTPUT FLAGS (TRUE=PRINT, FALSE=NO PRINT) [BWEBOX]
!   LTEMP1(4) - LOGICAL VARIABLES SET BY KEYWORD OPTIONS.
!     1=T IF OUTBREAK IS CURRENTLY ACTIVE
!     2=T IF PARASITISM RATES INCREASE DURING OUTBREAK
!     3=T IF LARVAL DEVELOPMENT TIMES INCREASE DURING OUTBREAK
!     4=T IF PUPAL WEIGHTS DECREASE DURING THE OUTBREAK
!   MGMIDB - MANAGEMENT ID TAG FOR BW MODEL [BWEBOX]
!   NEMULT(4,3) - MULTIPLIERS FOR NATURAL ENEMY EFFECTS [BWEBOX]
!   NEVENT - NUMBER OF BW SPECIAL EVENTS TO DATE
!   NUMCOL - NUMBER OF DEFOLIATION COLUMNS IN GRAPHICS OUTPUT TABLE)
!   NUMSTN(10) - NUMBER OF WEATHER STATIONS BY STATE
!   OUTNAM(8) - DEFAULT NAMES FOR BW OUTPUT TABLES
!   STATES(10,2) - NAMES OF STATES, & WEATHER DATA FILE NAME
!   STNAME - NAME OF FILE CONTAINING LIST OF WEATHER STATIONS
!   TEMPS2(3) - STORES NAMES OF OUTBREAK STATISTICS AREAS
!     1=No. NM, 2=BLUE MTNS.  3=MT
!   WFNAME - NAME OF WEATHER FILE SUPPLIED BY USER
!   WSLOOK(50,10) - STORES WEATHER STATION NAMES BY STATE
!
!-----END SEGMENT

