SUBROUTINE BWECUP
IMPLICIT NONE
!----------
! WSBWE $Id$
!  **BWECUP             DATE OF LAST REVISION:  03/23/17
!----------
!
!     PART OF THE WESTERN SPRUCE BUDWORM MODEL/PROGNOSIS LINKAGE CODE.
!
!     major revision by K.Sheehan 7/96+ to strip out BW Pop.Dyn.stuff
!
!     DESCRIPTION :
!
!     BWECUP CONTROLS INTERACTION BETWEEN THE WEATHER MODEL, THE
!     ADULT DISPERSAL MODEL, THE BUDWORM LIFECYCLE MODEL, THE
!     FOLIAGE DAMAGE MODELS, AND PROGNOSIS.
!
!     CALLED FROM :
!
!       GRADD - PROGNOSIS SINGLE STAND TREE GROWTH MODEL.
!
!     SUBROUTINES CALLED :
!
!     BWESIT - BUILD BUDWORM PSUEDO-STAND FROM PROGNOSIS TREE LIST.
!     BWEDR  - DRIVE THE BUDWORM MODEL FOR ONE YEAR.
!     BWEPDM - COMPUTES PERIODIC DAMAGE TO PROGNOSIS TREES.
!     BWEPRB - COMPUTE FINAL ADJUSTMENT TO PROPORTION OF RETAINED
!              BIOMASS ARRAY.
!     BWEEST - TELLS ESTABLISHMENT MODEL ABOUT BW DEFOLIATION
!
!   SOME VARIABLE DEFINITIONS:
!
!   IBWYR2 = LAST YEAR IN BUDWORM SIMULATION
!   ICYC -- INDEX TO CURRENT CYCLE.  VALUE SET IN **MAIN**.
!   IFINT -- FIXED POINT REPRESENTATION OF CURRENT CYCLE LENGTH.
!   IY -- IY(1)=INVENTORY DATE, IY(2)=ENDPOINT OF FIRST CYCLE,
!         IY(3)=ENDPOINT OF SECOND CYCLE,...,IY(MAXCY1)=ENDPOINT
!         OF FORTIETH CYCLE.  KEYWORD CONTROLLED.
!
! Revision History:
!   11-JUN-01 Lance David (FHTET)
!      .Added debug handling.
!   30-AUG-2006 Lance R. David (FHTET)
!      Changed array orientation of IEVENT from (4,250) to (250,4) for
!      efficiency purposes of the PPE processes in bwepppt and bweppgt.
!   14-JUL-2010 Lance R. David (FMSC)
!      Added IMPLICIT NONE and declared variables as needed.
!   28-FEB-2012 Lance R. David (FMSC)
!      Added check for presence of host species and exit if none present.
!   28-AUG-2013 Lance R. David (FMSC)
!      Added loading of weather year into IEVENT array.
!   23-MAR-2017 Lance R. David (FMSC)
!      Corrected index used in detected presence of host species in stand.
!-----------------------------------------------------------------------------
!
!OMMONS
!
INCLUDE 'PRGPRM.f90'
INCLUDE 'PLOT.f90'
INCLUDE 'CONTRL.f90'
INCLUDE 'BWESTD.f90'
INCLUDE 'BWECOM.f90'
INCLUDE 'BWECM2.f90'
INCLUDE 'BWEBOX.f90'
!
!OMMONS
!
INTEGER IYEAR, NSPYR, LASTYR, I, K
LOGICAL DEBUG, LBWHOST
!
!.... Check for DEBUG
!
CALL DBCHK(DEBUG,'BWECUP',6,ICYC)

IF (DEBUG) WRITE (JOSTND,*) 'ENTER BWECUP: ICYC = ',ICYC, &
    ' IBWSPM=',IBWSPM,' ISCT=',ISCT
!
!     Check for presence of host species. If no host, exit.
!
LBWHOST = .FALSE.
DO  I=1,MAXSP
  K=IBWSPM(I)
  IF (K .LT. 7) THEN
     IF (ISCT(I,1).GT.0) LBWHOST = .TRUE.
  ENDIF
IF (DEBUG) WRITE (JOSTND,*) 'IN BWECUP: I=',I,', K=',K, &
      ', ISCT(I,1_2)=',ISCT(I,1),ISCT(K,2),' LBWHOST = ',LBWHOST
END DO
IF (DEBUG) WRITE (JOSTND,*) 'IN BWECUP: LBWHOST = ',LBWHOST
IF (.NOT. LBWHOST) GOTO 300

!     ************************ EXECUTION BEGINS ************************
!
!     PROCESS STAND OPTIONS, AND CREATE FOLIAGE PROFILE.
!
IF (DEBUG) WRITE (JOSTND,*) 'IN BWECUP: CALL BWESIT'
CALL BWESIT
IF (DEBUG) WRITE (JOSTND,*) 'IN BWECUP: RETURN FROM BWESIT'
!
!     IF PROGNOSIS TELLS US THAT BUDWORM OR MANUAL DEFOLIATION IS
!     NOT SCHEDULED FOR THIS CYCLE, RETURN TO TREGRO.  IF WE GOT HERE,
!     THERE SHOULD EITHER BE A CALL TO BUDWORM OR A CALL TO DEFOL,
!     BUT, BETTER SAFE THAN SORRY......
!
IYEAR=0
NSPYR=1
!
!     DO FOR ALL YEARS...
!
LASTYR=IY(ICYC)+IFINT-1
IF (DEBUG) WRITE (JOSTND,*) 'IN BWECUP: LASTYR = ',LASTYR

DO 250 IYRCUR=IY(ICYC),LASTYR
IYEAR=IYEAR+1
IF (DEBUG) WRITE (JOSTND,*) 'IN BWECUP: IYEAR,IYRCUR= ', &
                                IYEAR,IYRCUR
LSPRAY=.FALSE.
!
!     IS AN INSECTICIDE APPLICATION SCHEDULED FOR THIS YEAR?
!
IF (ISPYR(NSPYR).EQ.IYRCUR) THEN
   INSTSP=SPINST(NSPYR)
   SPEFF=SPEFFS(NSPYR)
   LSPRAY=.TRUE.
   NSPYR=NSPYR+1
   IF (DEBUG) WRITE (JOSTND,*) 'IN BWECUP: LSPRAY,NSPYR,SPEFF=', &
                                   LSPRAY,NSPYR,SPEFF
!
! IF SO, SEND A NOTE TO THE SPECIAL EVENTS TABLE
!
   IF (LP4) THEN
     NEVENT=NEVENT+1
     IF (NEVENT.GT.250) THEN
       WRITE (JOBWP4,8250)
8250        FORMAT ('********   ERROR - WSBW: MORE THAN 250 ENTRIES!')
       LP4 = .FALSE.
     ELSE
       IEVENT(NEVENT,1)=IYRCUR
       IEVENT(NEVENT,2)=7
       IEVENT(NEVENT,3)=0
       IEVENT(NEVENT,4)=11

!            weather year is reported only if RAWS data is in use
       IF (IWSRC .EQ. 3) THEN
         IEVENT(NEVENT,5)=BWPRMS(11,IWYR)
       ELSE
         IEVENT(NEVENT,5)=0
       ENDIF
     ENDIF
   ENDIF
ENDIF
!
IF (DEBUG) WRITE (JOSTND,*) 'IN BWECUP: CALL BWEDR'
CALL BWEDR
!
!     LET THE ESTAB MODEL KNOW IF THERE WAS DEFOLIATION THIS YEAR.
!
IF (DEBUG) WRITE (JOSTND,*) 'IN BWECUP: CALL BWEEST'
CALL BWEEST
!
!     END YEAR LOOP.
!
250 CONTINUE
!
!     COMPUTE PERIODIC DAMAGE.
!
IF (DEBUG) WRITE (JOSTND,*) 'IN BWECUP: CALL BWEPDM'
CALL BWEPDM
!
!     COMPUTE FINAL ADJUSTMENT TO PRBIO ARRAY.
!
IF (DEBUG) WRITE (JOSTND,*) 'IN BWECUP: CALL BWEPRB'
CALL BWEPRB
!
!     SAVE LAST YEAR IN IYRLST, AND NUKE IBWYR2 SO NO OTHER STANDS
!     USE IT ACCIDENTALLY.
!
IBWYR2=-1
!
300 IF (DEBUG) WRITE (JOSTND,*) 'EXIT BWECUP: ICYC= ',ICYC

RETURN
END
