!ODE SEGMENT BWECM2
!----------
! WSBWE $Id$
!----------
!
!     BWECM2: Common variables for the GenDefol / Budworm Model
!               (BudLite)
!
! Revision History:
!   05-MAY-00 Lance David (FHTET)
!     Added variables OBSEER and WSEEDR to BLCOM4 common block.
!   16-MAY-00 Lance David (FHTET)
!     Added variable ILOBYR for reporting.
!   10-AUG-2006 Lance R. David (FHTET)
!     Reorganizing and removing obsolete variable in preparation for
!     linkage with PPE.
!   01-28-09 - Lance R. David
!      Common blocks ADDED for character and double precision variables
!      that were in common BLCOM4 due to compiler complaint (mixed
!      variable types in common) reported by Don Robinson (ESSA).
!   14-JUL-2010 Lance R. David (FMSC)
!      Declared variables as needed for IMPLICIT NONE.
!   23-JUN-2011 Lance R. David (FMSC)
!      Added BWPRMS array for RAWS daily weather processing to BLCOM3.
!   28-AUG-2013 Lance R. David (FMSC)
!     Added IYRNG array.
!---------------------------------------------------------------------

!     BLCOMN
LOGICAL LBUDL,LFIRST,LREGO,LSPRAY
INTEGER ILOBYR,IOBLOC,IYRECV,IYREND,IYROBL,IYRSRC,IYRST, &
           JOBWP1,JOBWP2,JOBWP3,JOBWP4,JOBWP5,JOBWP6,JOBWP7, &
           JOBWP8
REAL    BW(9,6),DEFYRS(6),DISPMR,EATEN(2,6),EGG1(6),EGG2(6), &
           EGGDEN,EGGS,FRESHC(6),FWSURV,GPERM2, &
           OBPHAS(3,2),OBTABL(8,3), &
           OLDMAX,OUT1(9,6,17),OUT2(6,3,8),OUT3(9,6,20), &
           PHENOL(3,6),TREEDD,WASTED(2),WCOLDW,WHOTF,WRAIND


!     BLCOM2
REAL    A1(9,6),A2(9,6),A3(9,6),A4(9,6),ACTNEW(9,6),ANTDEN(9,6), &
           AVEAMT(6),BIRDEN(9,6),DAYS(3),DISPX(4),DISPY(4), &
           ECI(2,6),EWTX(4),EWTY(4),GMAX(9,6),GMIN(9,6), &
           MYS1DN(9,6),MYS2DN(9,6),MYS3DN(9,6),OLDX(4),OLDY(4), &
           PMATED,SRATIO,STARVX(2,4),STARVY(2,4),WASTO


!     BLCOM3
INTEGER INSTSP,ISPRAY,ISPVAR,ISPYR(5),IWOPT,LIMITS,NSPRAY,IYRCNT, &
           IYRNG(2)
REAL    ANT_BD(9),APRED(3),BPRED(3),BWEATH(10,4),DEFLYR,DEVEL, &
           DEVELS(3),DFLUSH,FOLDVX(4),FOLDVY(4),FOLWTX(4),FOLWTY(4), &
           M1PRED(3),M2PRED(3),M3PRED(3),OBPHX(4),OBPHY(4),PRATE(9), &
           RPHEN(6),SPEFF,SPEFFS(10),SPINST(10),SYNCHX(6),SYNCHY(6), &
           TRIGGR,WRAIN1(3),WRAIN2(3),WRAIN3(3),WRAINA(3),WRAINB(3), &
           BWPRMS(11,50)


!     BLCOM4
CHARACTER*3 IOUT6A(3)
INTEGER IOBDUR,IOBOPT,IWYR,KRECVR,LOWYRS,NUMAPP
REAL    ADMORT,DISPDR(9),DISPMX(4),DISPMY(4),EGDISP,EPMASS, &
           HOSTST,OBSEER,WSEEDR
DOUBLE  PRECISION OBSEED,WSEED


COMMON /BLCOMN/ BW,DEFYRS,DISPMR,EATEN,EGG1,EGG2,EGGDEN,EGGS, &
      FRESHC,FWSURV,GPERM2,ILOBYR,IOBLOC,IYRECV,IYREND,IYROBL, &
      IYRSRC,IYRST,JOBWP1,JOBWP2,JOBWP3,JOBWP4,JOBWP5,JOBWP6, &
      JOBWP7,JOBWP8,LBUDL,LFIRST,LREGO,LSPRAY,OBPHAS,OBTABL, &
      OLDMAX,OUT1,OUT2,OUT3,PHENOL,TREEDD,WASTED,WCOLDW,WHOTF, &
      WRAIND

COMMON /BLCOM2/ A1,A2,A3,A4,ACTNEW,ANTDEN,AVEAMT,BIRDEN,DAYS, &
      DISPX,DISPY,ECI,EWTX,EWTY,GMAX,GMIN,MYS1DN,MYS2DN,MYS3DN, &
      OLDX,OLDY,PMATED,SRATIO,STARVX,STARVY,WASTO

COMMON /BLCOM3/ ANT_BD,APRED,BPRED,BWEATH,DEFLYR,DEVEL,DEVELS, &
      DFLUSH,FOLDVX,FOLDVY,FOLWTX,FOLWTY,INSTSP,ISPRAY,ISPVAR, &
      ISPYR,IWOPT,IYRCNT,LIMITS,M1PRED,M2PRED,M3PRED,NSPRAY, &
      OBPHX,OBPHY,PRATE,RPHEN,SPEFF,SPEFFS,SPINST,SYNCHX,SYNCHY, &
      TRIGGR,WRAIN1,WRAIN2,WRAIN3,WRAINA,WRAINB,BWPRMS,IYRNG

COMMON /BLCOM4/ ADMORT,DISPDR,DISPMX,DISPMY,EGDISP,EPMASS, &
      HOSTST,IOBDUR,IOBOPT,IWYR,KRECVR,LOWYRS,NUMAPP, &
      OBSEER,WSEEDR

COMMON /BLCOM4d/ OBSEED,WSEED
COMMON /BLCOM4c/ IOUT6A

!
!   A1-A4  - SHOOT ELONGATION PARAM.S FROM BECKWITH & KEMP (1984)
!   ACTNEW - ACTUAL AMOUNT OF NEW FOLIAGE GROWN & NOT EATEN TO DATE
!   ADMORT - ADULT MORTALITY SOON AFTER ECLOSION (BEFORE EGG LAYING OR DISP)
!   ANT_BD - PROP. OF PREDATOR MORTALITY ASSIGNED TO ANTS (BY CROWN LEVEL);
!            (1.0-ANT_BD) = PROP. ASSIGNED TO BIRDS
!   ANTDEN - ANT DENSITY FACTOR (SET TO 1.0 NOW)
!   AVEAMT - AVERAGE AMT. OF FOLIAGE EATEN BY A FEMALE LARVAE BY HOST
!   BIRDEN - BIRD DENSITY FACTOR (SET TO 1.0 NOW)
!   BW(9,6) - BUDWORM LARVAE COUNT BY CROWN THIRD AND HOST.
!   BWEATH(22,4) - WEATHER PARAMETER ARRAY [BWECM2]
!   DAYS   - NO. OF DAYS SPENT IN A LIFE STAGE
!   DEFLYR - TOTAL DEFOLIATION LAST YEAR (WT.D BY POT. HOST FOLIAGE, USED
!              AS A POSSIBLE TRIGGER FOR INSECTICIDE APPLICATION
!   DEFYRS - NO. OF YEARS WITH >20% DEFOL. BY HOST (THIS OUTBREAK ONLY)
!   DEVEL  - AMT. OF FOL. CLIPPED PER LARVA BY LARVAE THAT LATER DIED (=DEADL)
!   DEVELS - MODIFIER FOR DEVEL FOR THOSE LARVAE KILLED BY SPRAYING
!   DISPDR - CROWN LEVEL WT'ING FACTOR USED WHEN DISTRIBUTING DISP. LARVAE
!   DISPMR - MORTALITY RATE FOR DISPERSING LARVAE
!   DISPMX - SLIP FUNC. TO CONVERT NO. OF HOST TREES PER ACRE TO RATE OF
!               MORTALITY DURING DISPERSAL (X VALUES)
!   DISPMY - SLIP FUNC. TO CONVERT NO. OF HOST TREES PER ACRE TO RATE OF
!               MORTALITY DURING DISPERSAL (Y VALUES)
!   DISPX  - SLIP FUNC. TO CONVERT PROP. OF LARVAE THAT ATE NEW FOLIAGE TO
!               PROP. THAT WILL DISPERSE (X VALUES)
!   DISPY  - SLIP FUNC. TO CONVERT PROP. OF LARVAE THAT ATE NEW FOLIAGE TO
!               PROP. THAT WILL DISPERSE (Y VALUES)
!   DFLUSH - NO. OF DAYS FROM L2 EMERG. TO FIRST BUDFLUSH (CALC. IN BWEWEA)
!   EARLYX - SLIP FUNCT. TO CONVERT RATIO TO PROP. OF LARVAE THAT PUPATE
!            EARLY WHEN THERE ISN'T ENOUGH NEW FOLIAGE (X VALUES)
!   EARLYY - SLIP FUNCT. TO CONVERT RATIO TO PROP. OF LARVAE THAT PUPATE
!            EARLY WHEN THERE ISN'T ENOUGH NEW FOLIAGE (Y VALUES)
!   EATEN  - AMOUNT OF FOLIAGE EATEN BY SMALL OR LARGE LARVAE BY HOST
!   ECI    - EFFICIENCY INDEX FOR CONVERTING FOLIAGE TO BIOMASS FOR
!            NEW (1,HOST) OR OLD (2,HOST) FOLIAGE
!   EGDISP - SUMS THE TOTAL NUMBER OF DISPERSING EGGS (FOR ALL STANDS)
!   EGG1,2 - PARAMS. TO CONVERT PUPAL DRY WT TO NO. OF EGGS
!   EGGDEN - INITIAL EGGS PER M2 (SET IN BLOCK DATA)
!   EGGS   - INITIAL TOTAL NUMBER OF EGGS IN THE STAND
!   EPMASS - AVERAGE NUMBER OF EGGS PER EGG MASS
!   FOLDVX - SLIP FUNCT. TO CONVERT NO. OF YEARS OF DEFOLIATION (DEFYRS)
!            TO RELATIVE FOL. QUALITY -- EFFECTS ON DEVEL. RATES (X VALUES)
!   FOLDVY - SLIP FUNCT. TO CONVERT NO. OF YEARS OF DEFOLIATION (DEFYRS)
!            TO RELATIVE FOL. QUALITY -- EFFECTS ON DEVEL. RATES (Y VALUES)
!   FOLWTX - SLIP FUNCT. TO CONVERT NO. YEARS OF DEFOLIATION (DEFYRS) TO
!            RELATIVE FOLIAGE QUALITY (X VALUES)
!   FOLWTY - SLIP FUNCT. TO CONVERT NO. YEARS OF DEFOLIATION (DEFYRS) TO
!            RELATIVE FOLIAGE QUALITY (Y VALUES)
!   FRESHC - CONVERTS FRESH PUPAL WTS TO DRY PUPAL WTS BY HOST
!   FWSURV - FALL & OVERWINTER SURVIVAL RATE (SET IN BLOCK DATA)
!   GMAX   - MAX. SHOOT LENGTH (FROM BECKWITH & KEMP 1984, SHEEHAN ET AL.1989)
!   GMIN   - MIN. SHOOT LENGTH (FROM BECKWITH & KEMP 1984, SHEEHAN ET AL.1989)
!   GPERM2 - GRAMS OF FOLIAGE PER M2 (SET IN BLOCK DATA)
!   HOSTST - NO. OF HOST STEMS PER ACRE
!   INSTSP - INDEX FOR TARGET INSTAR
!   IOBDUR - OUTBREAK DURATION (IN YEARS)
!   IOBLOC - LOCATION INDEX FOR OUTBREAK STATISTICS [BWECM2]
!   IOBOPT - OUTBREAK SCHEDULING OPTION (1=ONLY START IS SCHEDULED,
!            2=START & END SCHEDULED, 3=USER SPECIFIES START & END)
!   ISPRAY - IF 1, THEN ISPVAR=YEAR, ELSE ISPVAR=% DEFOL. TRIGGER
!   ISPVAR - DEP. ON ISPRAY,= EITHER YEAR OF SPRAY OR % DEFOL.
!            THAT TRIGGERS A SPRAY
!   IWOPT  - WEATHER OPTION (1= INCORP. VARIATION, 2= USE MEANS ONLY) [BWECM2]
!   IWYR   - WEATHER YEAR COUNTER (USED TO ADVANCE THE WEATHER RANDOM
!            NUMBER SEED TO ACCOUNT FOR YEARS WHEN BUDLITE IS NOT CALLED)
!   IYROBL - YEAR THAT LAST REGIONAL OUTBREAK STARTED [BWECM2]
!   ILOBYR - YEAR OF LAST REGIONAL OUTBREAK AT RUN INITIALIZATION [BWECM2]
!   IYRST  - YEAR THAT NEXT REGIONAL OUTBREAK STARTS  [BWECM2]
!   IYREND - YEAR THAT NEXT REGIONAL OUTBREAK ENDS [BWECM2]
!   IYRECV - YEAR THAT TREES WILL BE COMPLETELY RECOVERED [BWECM2]
!                 FROM NEXT OUTBREAK
!   IYRNG  - YEAR RANGE ARRAY FOR LOADING RAWS DATA: (1) START YR, (2) END YR.
!            IF VLAUES ARE ZERO, ALL YEARS WILL BE LOADED.
!   IYRSRC - NUMBER OF YEARS AFTER END OF OUTBREAK THAT TREES [BWECM2]
!                 WILL BE COMPLETELY RECOVERED

!   JOBWP1 - FILE NUMBER ASSIGNED TO OUTPUT TABLE 1
!   JOBWP2 - FILE NUMBER ASSIGNED TO OUTPUT TABLE 2
!   JOBWP3 - FILE NUMBER ASSIGNED TO OUTPUT TABLE 3
!   JOBWP4 - FILE NUMBER ASSIGNED TO OUTPUT TABLE 4
!   JOBWP5 - FILE NUMBER ASSIGNED TO OUTPUT TABLE 5
!   JOBWP6 - FILE NUMBER ASSIGNED TO OUTPUT TABLE 6
!   JOBWP7 - FILE NUMBER ASSIGNED TO OUTPUT TABLE 7
!   JOBWP8 - FILE NUMBER ASSIGNED TO OUTPUT TABLE 8
!   KRECVR - COUNTER FOR THE NUMBER OF YEARS SINCE THE OUTBREAK ENDED
!              (WHEN KRECVR = IYRSRC, TREES HAVE RECOVERED FROM DEFOL.)
!   LBUDL  - FLAG SET TO TRUE IF A BW OUTBREAK IS (WILL BE) ACTIVE [BWECM2]
!   LFIRST - INDICATES THAT THE NEXT CALL TO BWELIT WILL BE AT THE
!            START OF A NEW OUTBREAK
!   LIMITS - LIMIT TO NO. OF SPRAYS PER OUTBREAK (1=ONLY 1, 2=NO LIMIT)
!   LOWYRS - NO. OF CONSECUTIVE YRS OF LOW NEW FOLIAGE DEFOLIATION (<5%)
!              CALC. FOR ALL NEW HOST FOLIAGE, USED TO DET. END OF OUTBREAKS
!   LREGO  - TRUE IF A REGIONAL OUTBREAK IS ACTIVE, FALSE IF NOT
!   LSPRAY - TRUE IF INSECTICIDES ARE TO BE SPRAYED IN THE CURRENT YEAR[BWECM2]
!   M1PRED - MYSTERY_1 PREDATOR MULTIPLIER (SET TO 1.0 NOW)
!   M2PRED - MYSTERY_2 PREDATOR MULTIPLIER (SET TO 1.0 NOW)
!   M3PRED - MYSTERY_3 PREDATOR MULTIPLIER (SET TO 1.0 NOW)
!   MYS1DN - MYSTERY_1 DENSITY FACTOR (SET TO 0.0 NOW)
!   MYS2DN - MYSTERY_2 DENSITY FACTOR (SET TO 0.0 NOW)
!   MYS3DN - MYSTERY_3 DENSITY FACTOR (SET TO 0.0 NOW)
!   NUMAPP - NUMBER OF INSECTICIDE APPL.S DONE DURING THE CURRENT OUTBREAK
!   OBPHAS - STORES PARASITISM RATES BY OUTBREAK PHASE AND LIFE STAGE
!   OBPHX  - SLIP FUNC. TO CONVERT YEARS OF DEFOLIATION (DEFYRS) TO PARA. RATE
!   OBPHY  - SLIP FUNC. TO CONVERT YEARS OF DEFOLIATION (DEFYRS) TO PARA. RATE
!   OBSEED - RANDOM NO. SEED FOR OUTBREAK STATISTICS
!   OBSEER - RANDOM NO. SEED FOR OUTBREAK STATISTICS (FOR REPORTING ONLY)
!   OBTABL(8,3) - OUTBREAK PARAMETER TABLE (PARAMETER=IOBLOC) [BWECM2]
!   OLDMAX - PROP. OF OLD FOLIAGE THAT IS AVAIL. TO FEEDING LARVAE (BLOCK DATA)
!   OLDX   - SLIP FUNCT. TO CONVERT RATIO TO PROP. OF LARVAE THAT FEED ON
!            OLD FOL. WHEN THERE ISN'T ENOUGH NEW FOLIAGE (X VALUES)
!   OLDY   - SLIP FUNCT. TO CONVERT RATIO TO PROP. OF LARVAE THAT FEED ON
!            OLD FOL. WHEN THERE ISN'T ENOUGH NEW FOLIAGE (Y VALUES)
!   OUT1   - STORES VARIABLES FOR TABLE 1 (SEE P1 FOR DETAILS)
!   OUT2   - STORES VARIABLES FOR TABLE 2 (SEE P2 FOR DETAILS)
!   OUT3   - STORES VARIABLES FOR TABLE 3 (SEE P3 FOR DETAILS)
!   PMATED - PROP. OF ADULT FEMALES THAT MATE
!   PHENOL - RELATIVE PHENOLOGY AMONG CROWN THIRDS & HOSTS (BECKWITH & KEMP)
!   RPHEN  - PHENOLOGY OF EACH HOST RELATIVE TO DOUGLAS-FIR
!   SPEFF  - SPRAY EFFICACY
!   SRATIO - SEX RATIO OF EMERGING ADULTS
!   STARVX - STORES SSTARX VALUES FOR THE 3 LIFE STAGES
!   STARVY - STORES SSTARY VALUES FOR THE 3 LIFE STAGES
!   SYNCHX - SLIP FUNCTION TO CONVERT ELAPSED DAYS TO BW SURVIVAL (X VALUES)
!   SYNCHY - SLIP FUNCTION TO CONVERT ELAPSED DAYS TO BW SURVIVAL (Y VALUES)
!   TREEDD - DEGREE-DAYS ABOVE 5.5C ACCUMULATED AT L4 (SET IN BWEWEA)
!   WASTED - PROP. OF TOTAL NEW CLIPPED FOLIAGE THAT IS WASTED (SMALL,LARGE L)
!   WASTO  - PROP. OF CLIPPED OLD FOLIAGE THAT IS WASTED)
!   WCOLDW - WEATHER PARAM.: EXTREME WINTER WEATHER (SET IN BWEWEA)
!   WHOTF  - WEATHER PARAM.: L2 MORT. DUE TO PREV.WARM FALL TEMPS (BWEWEA)
!   WRAINA - EFFECT OF HEAVY PPT. ON ANT PREDATION (BY LIFE STAGE)
!   WRAINB - EFFECT OF HEAVY PPT. ON BIRD PREDATION (BY LIFE STAGE)
!   WRAIN1 - EFFECT OF HEAVY PPT. ON OTHER1 PREDATION (BY LIFE STAGE)
!   WRAIN2 - EFFECT OF HEAVY PPT. ON OTHER2 PREDATION (BY LIFE STAGE)
!   WRAIN3 - EFFECT OF HEAVY PPT. ON OTHER3 PREDATION (BY LIFE STAGE)
!   WRAIND - EFFECT OF HEAVY PPT. DURING L2 EMERG. (SET IN BWEWEA)
!   WSEED  - RANDOM NO. SEED FOR WEATHER STATISTICS
!   WSEEDR - RANDOM NO. SEED FOR WEATHER STATISTICS (FOR REPORTING ONLY)
!
!----------------------------------------------------------------------------
!
!  Terminology used in variable descriptions:
!
!  Cell    - A single crown third of one host tree species size class.
!            Their are a total of nine cells for each host tree species in
!            this model, 3 crown thirds (top, middle, bottom) and 3 tree
!            height size classes: small  (up to 7 meters (23 feet))
!                                 medium (7 to 14 meters (23-46 feet))
!                                 large  (over 14 meters (46 feet)
!
!            The order of the size class crown third cells in the arrays are:
!                (1)  (2)  (3)   (4)  (5)  (6)   (7)  (8)  (9)
!                ----small----   ---medium----   ----large----
!                top  mid  bot   top  mid  bot   top  mid  bot
!
!-----END SEGMENT
