SUBROUTINE BWEDEF
IMPLICIT NONE
!----------
! WSBWE $Id$
!----------
!
!     APPLIES DEFOLIATION RATES AS SPECIFIED BY A USER USING DEFOL
!     OPTION.
!
!     PART OF THE WESTERN SPRUCE BUDWORM MODEL/PROGNOSIS LINKAGE CODE.
!     N.L. CROOKSTON--FORESTRY SCIENCES LAB, MOSCOW, ID--JANUARY 1984
!
!     minor changes by K.Sheehan 7/96 to remove LBWDEB
!
!     CALLED FROM :
!
!       BWEDR - DRIVE THE BUDWORM MODEL FOR ONE STAND IN ONE YEAR.
!
!     SUBROUTINES CALLED :
!
!       OPGET  - GET NEXT OPTION.
!       OPDEL1 - DELETE OPTION.
!       OPDONE - SIGNAL THAT OPTION IS DONE.
!       BWESIN - SET DO LOOP INDICES FOR SETPRBIO AND DEFOL OPTIONS.
!
! REVISION HISTORY
!   05-OCT-2006 Lance R. David
!     Previous date noted was 2/25/97 by Kathy Sheehan.
!     Added debug handling.
!   14-JUL-2010 Lance R. David (FMSC)
!     Added IMPLICIT NONE and declared variables as needed.
!----------------------------------------------------------------------
!
!OMMONS
!
INCLUDE 'PRGPRM.f90'
INCLUDE 'CONTRL.f90'
INCLUDE 'BWESTD.f90'
INCLUDE 'BWECOM.f90'
!
!OMMONS
!
INTEGER IACT, ICRC1, ICRC2, ICRC3, ICROWN, IDT, IHOST, &
           IS1, IS2, NP
REAL PARMS(6)
LOGICAL DEBUG

!
!.... Check for DEBUG
!
CALL DBCHK(DEBUG,'BWEDEF',5,ICYC)

IF (DEBUG) WRITE (JOSTND,*) 'ENTER BWEDEF: ICYC=',ICYC, &
     ' ITODO=',ITODO,' NTODO=',NTODO,' IYRCUR=',IYRCUR

10 CONTINUE
!
!     IF ALL OF THE OPTIONS HAVE BEEN PROCESSED, THEN:  RETURN.
!
IF (ITODO.GT.NTODO) GOTO 1000
CALL OPGET (ITODO,6,IDT,IACT,NP,PARMS)
IF (DEBUG) WRITE (JOSTND,*) 'IN BWEDEF: OPGET RETURN: ', &
     'ITODO, IDT, IACT, PARMS= ', ITODO, IDT, IACT, PARMS

!
!     IF THE DATE OF THE OPTION IS GREATER OR EQUAL TO THE CURRENT YEAR,
!     THEN: KEEP THE OPTION.
!
IF (IDT.GE.IYRCUR) GOTO 20
!
!     ELSE: THE OPTION IS OLDER THAN THE YEAR, DELETE IT AND GET THE
!     NEXT ONE.
!
CALL OPDEL1 (ITODO)
ITODO=ITODO+1
GOTO 10
20 CONTINUE
!
!     IF THE DATE OF THIS OPTION IS GREATER THAN THE CURRENT DATE, THEN:
!     RETURN.
!
IF (IDT.GT.IYRCUR) GOTO 1000
!
!     SIGNAL THAT THE OPTION IS DONE.
!
CALL OPDONE (ITODO,IYRCUR)
ITODO=ITODO+1
!
!     LOAD INDEXING BOUNDS.
!
CALL BWESIN (PARMS,IBWSPM,IS1,IS2,ICRC1,ICRC2,ICRC3)
IF (DEBUG) WRITE (JOSTND,*) &
     'IN BWEDEF: IBWSPM, IS1, IS2, ICRC1, ICRC2, ICRC3', &
     IBWSPM, IS1, IS2, ICRC1, ICRC2, ICRC3

!
!     IF THE SPECIES MAPED TO NON-HOST, THEN DELETE OPTION.
!
IF (IS1.LE.6) GOTO 30
CALL OPDEL1 (ITODO-1)
GOTO 10
30 CONTINUE
!
!     APPLY MANUAL DEFOLIATION.
!
DO 80 IHOST=IS1,IS2
IF (IFHOST(IHOST).EQ.0) GOTO 80
DO 70 ICROWN=ICRC1,ICRC2,ICRC3
FNEW(ICROWN,IHOST)=FNEW(ICROWN,IHOST)*(1.-(PARMS(3)/100.))
FOLD1(ICROWN,IHOST)=FOLD1(ICROWN,IHOST)*(1.-(PARMS(4)/100.))
FOLD2(ICROWN,IHOST)=FOLD2(ICROWN,IHOST)*(1.-(PARMS(5)/100.))
FREM (ICROWN,IHOST)=FREM (ICROWN,IHOST)*(1.-(PARMS(6)/100.))
70 CONTINUE
80 CONTINUE
!
!     GET ANOTHER OPTION.
!
GOTO 10
1000 CONTINUE
IF (DEBUG) WRITE (JOSTND,*)'EXIT BWEDEF: ICYC=', ICYC
RETURN
END
