SUBROUTINE BWEFDK (NUMBER,KEYWRD,TABLE,ISIZE,KODE,IOUT)
IMPLICIT NONE
!----------
! WSBWE $Id$
!----------
!
!     FUNCTION TO FIND A KEYWORD IN A TABLE.
!
!     PART OF THE WESTERN SPRUCE BUDWORM MODEL.
!     NICHOLAS L. CROOKSTON                          SEPT 1979
!     INT-FORESTRY SCIENCES LABORATORY-MOSCOW, IDAHO
!
!     NUMBER= THE KEYWORD NUMBER (TABLE INDEX VALUE) RETURNED
!             TO CALLING SUBROUTINE.
!     KEYWRD= KEYWORD TO BE FOUND IN TABLE ARRAY
!     TABLE = CHARACTER*8 ARRAY CONTAINING THE KEYWORDS
!     ISIZE = THE DIMENSIONAL SIZE OF TABLE ARRAY
!     KODE  = RETURN CODE:
!             0= NO ERRORS FOUND.
!             1= KEYWORD NOT FOUND
!     IOUT  = OUTPUT WRITE UNIT REFERENCE NUMBER
!
! Revision History:
!   12-MAY-00 Lance David
!     Brought comments and variable descriptions up to date.
!     Changed TABLE array definition to inherit dimension from
!     calling program unit.
!   14-JUL-2010 Lance R. David (FMSC)
!     Added IMPLICIT NONE and declared variables as needed.
!----------
INTEGER     I, IOUT, ISIZE, KODE, NUMBER
CHARACTER*8 KEYWRD,TABLE(*)

NUMBER=0
DO 10 I=1,ISIZE
IF (KEYWRD.NE.TABLE(I)) GOTO 10
NUMBER=I
GOTO 15
10 CONTINUE
15 CONTINUE
IF (NUMBER.EQ.0) THEN
  KODE=1
  WRITE (IOUT,85) KEYWRD
85   FORMAT (/,'''',A8,''' :KEYWORD SPECIFIED')
ELSE
  KODE=0
ENDIF
RETURN
END
