SUBROUTINE BWEKRD (INUNIT,IOUT,KEYWRD,LNOTBK, &
                      ARRAY,IRECNT,KODE,KARD)
IMPLICIT NONE
!----------
! WSBWE $Id$
!  **BWEKRD                 DATE OF LAST REVISION:  03/23/17
!----------
!
!  Also revised by K.Sheehan 7/1/96 to run on PowerStation
!
!     KEYWORD CARD READER FOR THE STAND PROGNOSIS SYSTEM
!
!     ARGUMENTS:
!     INUNIT= READER REFERENCE NUMBER
!     IOUT  = PRINTER REFERENCE NUMBER
!     KEYWRD= CHARACTER*8 KEYWORD.
!     LNOTBK= DIMENSION 7, VALUES ARE TRUE IF THE CORRESPONDING
!             NUMERIC FIELD IS NOT BLANK, FALSE IF THEY ARE.
!     ARRAY = DIMENSION 7, VALUES READ FROM THE NUMERIC FIELD.
!     IRECNT= RECORD COUNTER.
!     KODE  = RETURN CODE:
!             0= NO ERRORS FOUND.
!             1= FIRST COLUMN OF CARD WAS BLANK OR INVALID CHAR DATA
!                WAS FOUND.
!             2= END-OF-FILE WAS FOUND.
!             LESS THAN ZERO:  PARMS STATEMENT IS ON THE RECORD START-
!             ING IN FIELD IABS(KODE).
!
!  Revision History:
!    14-JUL-2010 Lance R. David (FMSC)
!       Added IMPLICIT NONE and declared variables as needed.
!    23-MAR-2017 Lance R. David (FMSC)
!       Was not properly processing alph entries in fields. Made
!       consistent with FVS base routine keyword reader (keyrdr.f).
!----------
!  DECLARATIONS AND DATA STATEMENTS:
!----------
CHARACTER*80 RECORD
CHARACTER*10 KARD(12)
CHARACTER*8  KEYWRD
INTEGER I, INUNIT, IOS, IOUT, IP, IRECNT, ISTLNB, J, K, KODE, NF
REAL         ARRAY(12)
LOGICAL      LNOTBK(12),LCOM

!----------
!  READ KEYWORD AND LOCATE BLANK PARAMETER FIELDS.
!----------
LCOM=.FALSE.
5 CONTINUE
!      READ (INUNIT,10,END=30) RECORD
READ (INUNIT,10,END=30,iostat=ios) RECORD
10 FORMAT (A80)
IRECNT = IRECNT + 1
IF (RECORD(1:1).EQ.'!') GOTO 5
IF (RECORD(1:1).EQ.'*'.OR. RECORD.EQ.' ') THEN
   IF (.NOT.LCOM) THEN
      WRITE (IOUT,'(/)')
      LCOM=.TRUE.
   ENDIF
   WRITE (IOUT,'(T13,A)') RECORD(1:ISTLNB(RECORD))
   GOTO 5
ELSE
   LCOM=.FALSE.
ENDIF
!
!     CHECK FOR THE PRESENCE OF A 'P' SO THAT THE PARMS STATEMENT
!     MAY BE DETECTED.
!
NF=12
K=11
DO WHILE (K <= 73)
   IP=INDEX(RECORD(K:73),'P')
   IF (IP.EQ.0) IP=INDEX(RECORD(K:73),'p')
   IF (IP.GT.0) THEN
!
!        BORROW THE USE OF KEYWRD TO HOLD "PARMS" IN MIXED, THEN UPPER
!        CASE...
!
      KEYWRD(1:5)=RECORD(IP+K-1:IP+K+4)
      DO I=1,5
         CALL UPCASE (KEYWRD(I:I))
      ENDDO
      IF (KEYWRD(1:5).EQ.'PARMS') THEN
         IP=K+IP-11
         NF=(IP-1)/10
         EXIT
      ENDIF
      K=K+IP
      CYCLE
   ELSE
      EXIT
   ENDIF
END DO
!
!     LOAD THE KEYWORD INTO KEYWRD...DECODE THE FIELDS.
!
KEYWRD=RECORD(1:8)
J=1
DO 25 I=1,NF
J=J+10
KARD(I)=RECORD(J:J+9)
ARRAY(I)=0.0
!
!     MAKE SURE ALL OF THE CHARACTERS IN KARD ARE NUMBERS...
!
DO 15 K=1,10
IF (INDEX(' .+-eE0123456789',KARD(I)(K:K)).EQ.0) GOTO 25
15 CONTINUE
READ (KARD(I),'(G10.0)',ERR=25) ARRAY(I)
25 CONTINUE
GOTO 40
!
30 CONTINUE
KODE = 2
RETURN
!
40 CONTINUE
CALL BWEUKY (KEYWRD)
KODE = 0
DO 50 I=1,NF
LNOTBK(I) = KARD(I).NE.' '
50 CONTINUE
IF (NF.LT.7) THEN
   KODE=-(NF+1)
   DO 55 I=NF+1,7
   LNOTBK(I)=.FALSE.
   ARRAY(I)=0.0
   J=I*10+1
   KARD(I)=RECORD(J:J+9)
55    CONTINUE
ENDIF
!
60 CONTINUE
RETURN
END
