SUBROUTINE BWEPPATV (L)
IMPLICIT NONE
!----------
! WSBWE $Id$
!----------
!
!  RETURNS L=TRUE, TO INDICATE THAT GENDEFOL/BUDWORM MODEL IS AVAILABLE
!  TO PARALLEL PROCESSOR.
!
!  CALLED BY :
!     GETSTD  [PARALLEL PROCESSOR]
!     PUTSTD  [PARALLEL PROCESSOR]
!
!  CALLS     :
!     NONE
!
!  PARAMETERS :
!     L     - FLAG THAT IS SET TO TRUE WHEN THE BUDWORM MODEL IS
!             ATTACHED WITH PPE.
!
LOGICAL L

L = .TRUE.

RETURN
END
