FUNCTION BWERNP (XMEAN,XMXVAR)
IMPLICIT NONE
!----------
! WSBWE $Id$
!----------
!
!     PART OF THE WESTERN SPRUCE BUDWORM MODEL/PROGNOSIS LINKAGE CODE.
!     N.L. CROOKSTON--FORESTRY SCIENCES LAB, MOSCOW, ID--APRIL 1989
!
!     CALLED FROM :
!
!     BWEDAM - APPLY BUDWORM DAMAGE TO PROGNOSIS SAMPLE TREES.
!
!     SUBROUTINES CALLED :
!
!     BWEBET - BETA DISTRIBUTION RANDOM NUMBER GENERATOR.
!
!     PARAMETERS :
!
!     XMEAN = A MEAN PROPORTION...ON A 0 TO 1.0 RANGE.
!     XMXVAR= THE MAX VARIANCE AT XMEAN=.5
!
!     BWERNP  = A BETA RANDOM NUMBER WHEREBY THE VARIANCE IS A
!              SIMPLE FUNCTION OF THE MEAN.
!
!  Revision History:
!    14-JUL-2010 Lance R. David (FMSC)
!       Previous noted revision 12/05/90
!       Added IMPLICIT NONE and declared variables as needed.
!----------
INTEGER KODE
REAL BWERNP, C, SC, V, VAR, W, XM, XMEAN, XMXVAR, X(1)

DATA C/2.7/,SC/0.9304/
X(1)=0.0
!
!     IF THE MEAN IS CLOSE TO EITHER ZERO OR ONE, THEN SKIP THIS STUFF.
!
IF (XMEAN.LT. 0.001 .OR. XMEAN.GT.  0.999) THEN
   BWERNP=XMEAN
ELSE
!
!        COMPUTE THE VARIANCE AS A FUNCTION OF THE MEAN AND XMXVAR.
!        ASSUME THAT THE RELATIONSHIP IS SYMMETRICAL ABOUT .5
!
   IF (XMEAN.GT. 0.5) THEN
      XM=1.-XMEAN
   ELSE
      XM=XMEAN
   ENDIF
   VAR=(SC*XMXVAR)*(C*(XM*(C-1.))**(C-1.)*EXP(-((C-1.)*XM)**C))
!
!        COMPUTE THE PARAMETERS OF THE BETA
!
   W=(XMEAN*(1.-XMEAN)/VAR)-1.
   V=XMEAN*W
   W=(1.-XMEAN)*W
!
!        GET ONE BETA VARIATE.
!
!        WRITE (16,*) 'IN BWERNP: bCALL BWEBET V=',V,' W=',W,' X=',X
   CALL BWEBET (V,W,X,1,KODE)
!        WRITE (16,*) 'IN BWERNP: aCALL BWEBET V=',V,' W=',W,' X=',X
   IF (KODE.LT.0) THEN
      BWERNP=XMEAN
   ELSE
      BWERNP=X(1)
   ENDIF
ENDIF
RETURN
END
