SUBROUTINE BWERAN(SEL)
IMPLICIT NONE
!----------
! WSBWE $Id$
!----------
!
!     BASE RANDOM NUMBER GENERATOR
!
!     PART OF THE WESTERN SPRUCE BUDWORM MODEL.
!     N.L. CROOKSTON--FORESTRY SCIENCES LAB., MOSCOW, ID.--MAY 1983.
!
!     DESCRIPTION :
!
!     THIS RANDOM NUMBER GENERATOR HAS A STOCK SEED FOR MULTIPLE
!     RUNS, OR CAN BE SUPPLIED WITH ANY OTHER SEED.  IT GENERATES
!     A REAL NUMBER BETWEEN 0. AND 1.
!
!     CALLED FROM :
!
!       BWBETA
!       BWRNP  - RANDOM DEFOLIATION GIVEN A MEAN.
!
!     SUBROUTINES CALLED : NONE
!
!     MULTIPLE ENTRIES :
!
!      BWERSD - REINITIALIZE RANDOM NUMBER GENERATOR.
!      BWERPT - RESTORE RANDOM NUMBER SEED.
!      BWERGT - GET RANDOM NUMBER SEED.
!
!     KNOWN MACHINE DEPENDENCIES : NONE
!
!     PARAMETERS :
!
!     SEL - RANDOM NUMBER RETURNED
!
!
!     THIS RANDOM NUMBER GENERATOR WAS MODIFIED FROM THE ALGORTHM
!     FOUND IN IN THE IMSL LIBRARY VOL 1 EDITION 4 TO 5,
!     DEC. 1, 1975, AND CAN BE FOUND IN THE FOLLOWING REFERENCES:
!
!     LEWIS, P.A.W., GOODMAN, A.S., AND MILLER, J.M. PSUEDO-RANDOM
!     NUMBER GENERATOR FOR THE SYSTEM/360, IBM SYSTEMS JOURNAL, NO. 2,
!     1969.
!
!     LEARMONTH, G.P. AND LEWIS, P.A.W., NAVAL POSTGRADUATE SCHOOL
!     RANDOM NUMBER GENERATOR PACKAGE LLRANDOM, NPS55LW73061A, NAVAL
!     POSTGRADUATE SCHOOL, MONTEREY, CALIFORNIA, JUNE, 1973.
!
!     LEARMONTH, G.P., AND LEWIS, P.A.W., STATISTICAL TESTS OF SOME
!     WIDELY USED AND RECENTLY PROPOSED UNIFORM RANDOM NUMBER
!     GENERATORS. NPS55LW73111A, NAVAL POSTGRADUATE SCHOOL, MONTEREY
!     CALIFORNIA, NOV. 1973.
!
!     THE CODE WAS WRITTEN BY N.L. CROOKSTON, FORESTRY SCIENCES LAB,
!     OCT 1982, FROM THE ALGORITHM PUBLISHED IN THE IMSL MANUAL AND
!     TESTED BY COMPAIRING THE FIRST 10000 DRAWS FORM THIS VERSION AND
!     AND THE GENERATOR 'GGUBS' IN THE 1981 EDITION OF IMSL.
!
!  Revision History:
!    14-JUL-2010 Lance R. David (FMSC)
!       Previous noted revision 12/05/90
!       Added IMPLICIT NONE and declared variables as needed.
!----------
REAL SEED, SEL, SS
DOUBLE PRECISION S0,S1,DSEED
LOGICAL LSET
DATA S0/55329D0/,SS/55329./
!
!
S1=DMOD(16807D0*S0,2147483647D0)
SEL=S1/2147483648D0
S0=S1
!
!     WRITE (44,*) 'BWERAN: SEL= ',SEL                             ! Temp debug
RETURN
!
!     YOU MAY RESEED THE GENERATOR BY SUPPLYING AN ODD NUMBER OF TYPE
!     REAL WITH LSET=TRUE; IF LSET=FALSE, A CALL TO BWRNSD WILL
!     CAUSE THE RANDOM NUMBER GENERATOR TO START OVER.
!
ENTRY BWERSD (LSET,SEED)
!
!
IF (LSET) GOTO 10
SEED=SS
S0=SEED
GOTO 20
10 CONTINUE
IF (AMOD(SEED,2.0).EQ.0.) SEED=SEED+1
SS=SEED
S0=SEED
20 CONTINUE
!
RETURN
!
!     ENTRY POINT TO GET RANDOM NUMBER SEED.
!
ENTRY BWERGT (DSEED )
DSEED=S0
RETURN
!
!     ENTRY POINT TO REPLACE RANDOM NUMBER SEED.
!
ENTRY BWERPT (DSEED)
S0=DSEED
RETURN
END
